### ISSUE TITLE
Ordering issue with `company-complete-common`

### ISSUE THREAD

**Issue by johndebord** [company-mode/company-mode#1001]
Is there a way to switch up the ordering so that it's more consistent with how bash orders completions?

<hr>

Here are a couple screenshots of what I mean:

![image](https://user-images.githubusercontent.com/35586806/89972585-2ecbc780-dc2c-11ea-8bfe-731f3eeea98c.png)

![image](https://user-images.githubusercontent.com/35586806/89972600-37240280-dc2c-11ea-8ec9-85912d79d81b.png)

**Comment by dgutov** [comment]
Which backend is this coming from?

Try `M-x company-diag`.

**Comment by johndebord** [comment]
```text
Emacs 26.3.50 (x86_64-pc-linux-gnu) of 2020-08-11 on debord
Company 0.9.10

company-backends: ((company-capf))

Used backend: (company-capf)

Major mode: eshell-mode
Prefix: "build"
Completions:
  #("build/" 0 5 (face completions-common-part) 5 6 (face (completions-first-difference)))
  #("build-aux/" 0 5 (face completions-common-part) 5 6 (face (completions-first-difference)))
```

**Comment by johndebord** [comment]
@dgutov do you need any more diagnostics?

**Comment by dgutov** [comment]
Oh, sorry, got delayed.

I've done the extra diagnostics myself: the completions come from `pcomplete-completions-at-point`. Which doesn't define the sorting function, so we're sorting alphabetically.

The completions come from Emacs, so you'll need to `M-x report-emacs-bug` for any chance of having this improved. You can reproduce this same behavior using `M-x completion-at-point`.

I'm not 100% it's possible to get bash's behavior, though: the completions generation algorithm is likely different. But if you describe bash's logic in detail, it could be possible to reproduce.

**Comment by johndebord** [comment]
No worries. But if we're sorting in alphabetical order, then `build` should come before `build-aux` in the drop down pop-up -- unless it's reversed? I'm pretty sure bash sorts alphabetically, and `pcomplete-completions-at-point` doesn't. Unless I'm misunderstanding something here.

**Comment by dgutov** [comment]
What are your contents of `company-transformers`?

**Comment by johndebord** [comment]
Just ran it in `eshell-mode` and the value is:
```text
company-transformers is a variable defined in ‘company.el’.
Its value is nil

Documentation:
Functions to change the list of candidates received from backends.

Each function gets called with the return value of the previous one.
The first one gets passed the list of candidates, already sorted and
without duplicates.

You can customize this variable.

[back]
```

<hr>


I think I figured it out. It looks like the sorting is defaulting to ASCII sort order:
[http://support.ecisolutions.com/doc-ddms/help/reportsmenu/ascii_sort_order_chart.htm](http://support.ecisolutions.com/doc-ddms/help/reportsmenu/ascii_sort_order_chart.htm)

![image](https://user-images.githubusercontent.com/35586806/91254080-598b4500-e72f-11ea-806f-4f60529bca67.png)

<hr>

Still not sure where that behavior is defaulted to in the code.

**Comment by dgutov** [comment]
I'm fairly sure it's just `(sort candidates 'string<)` in `company--preprocess-candidates`.

Alphabetical and ascii order are not the same?
