### ISSUE TITLE
Error: "Symbol’s function definition is void: mapcan" on command post-command

### ISSUE THREAD

**Issue by heymo** [company-mode/company-mode#1003]
Recently updated company, now I get this error message whenever company ist trying to show completions:
```
Company: frontend company-pseudo-tooltip-unless-just-one-frontend error "Symbol’s function definition is void: mapcan" on command post-command
```
Here is the relevant part of my init file:
```
  (use-package company
    :ensure t
    :init
    (add-hook 'after-init-hook 'global-company-mode))
```
Any ideas?

**Comment by dgutov** [comment]
Hi!

Please specify your Emacs version.

**Comment by heymo** [comment]
Sorry, forgot:

Aquamacs/vanilla  GNU Emacs 25.3.50.1 (x86_64-apple-darwin16.7.0, NS appkit-1504.83 Version 10.12.6 (Build 16G2016)) dated 2019-08-18

Mac OSX 10.15.6

**Comment by dgutov** [comment]
Thanks for the report, and sorry about that.

Should be fixed now.

**Comment by heymo** [comment]
Yep, solved it for me.

Thank you for the swift fix!
