### ISSUE TITLE
company-mode does not auto trigger comlete after "/" in Clojure code

### ISSUE THREAD

**Issue by stardiviner** [company-mode/company-mode#1005]
I'm using CIDER for Clojure code completion. When I type in `(java.lang.System/|)`. The `|` represent the cursor point.
The company-mode does not auto trigger completion after the `/` character. The complete candidates is avaiable after manually triggered `company-complete`. I tried to add `/` character into `company-auto-complete-chars`. Like this:
```elisp
(setq company-auto-complete-chars '(?\  ?\) ?. ?/ ?# ?$))
```

But still does not work.

**Comment by dgutov** [comment]
Hi!

When/where idle completion happens, if up to the respective backend. The CIDER project, in this case.

`company-auto-complete-chars` has no effect on this, as you can see from its docstring. But it's a frequent mistake, so it's high time to rename these vars.

`company-auto-finish`? `company-auto-commit`? `company-auto-insert`?

If anybody visiting this discussion has an opinion, please go ahead and voice them.

**Comment by stardiviner** [comment]
> When/where idle completion happens, if up to the respective backend. The CIDER project, in this case.

It's not because of idle delay. Because I have `company-idle-delay 0.3` and `company-tooltip-idle-delay 0`. So should not be the delay problem. Also CIDER backend completion is fast for `java.lang.System` input prefix. No reason slow for completion after `/`. And Even I waited 20 seconds, still no popup.

> company-auto-finish? company-auto-commit? company-auto-insert?

I would like `company-auto-commit`. Because `commit` means select candidate and commit insertation. And `insert` means auto insert something, there is no background of in completion.

**Comment by dgutov** [comment]
> So should not be the delay problem.

It's most likely a prefix calculation issue.

> I would like company-auto-commit.

:ok_hand: Noted.

**Comment by stardiviner** [comment]
> It's most likely a prefix calculation issue.

I tried to edebug on `company-diag`, it shows the `prefix` value is correct `java.lang.System/`. Seem not prefix calculation. And in `company-diag`, completion candidates are correct.

**Comment by dgutov** [comment]
OK. Can you show the full `M-x company-diag` output?

**Comment by stardiviner** [comment]
Here is the complete `M-x company-diag` output:

```
Emacs 28.0.50 (x86_64-pc-linux-gnu) of 2020-08-23 on dark
Company 0.9.13

company-backends: ((company-capf :separate company-yasnippet :separate company-keywords)
 (company-dabbrev-code :with company-abbrev)
 company-files)

Used backend: (company-capf :separate company-yasnippet :separate company-keywords)

Value of c-a-p-f: (cider-complete-at-point t)
Major mode: cider-repl-mode
Prefix: "java.lang.System/"
Completions:
  #("java.lang.System/arraycopy" 0 1 (type "static-method" ns nil)) " <sm>"
  #("java.lang.System/clearProperty" 0 1 (type "static-method" ns nil)) " <sm>"
  #("java.lang.System/console" 0 1 (type "static-method" ns nil)) " <sm>"
  #("java.lang.System/currentTimeMillis" 0 1 (type "static-method" ns nil)) " <sm>"
  #("java.lang.System/err" 0 1 (type "static-field" ns nil)) " <sf>"
  #("java.lang.System/exit" 0 1 (type "static-method" ns nil)) " <sm>"
  #("java.lang.System/gc" 0 1 (type "static-method" ns nil)) " <sm>"
  #("java.lang.System/getLogger" 0 1 (type "static-method" ns nil)) " <sm>"
  #("java.lang.System/getProperties" 0 1 (type "static-method" ns nil)) " <sm>"
  #("java.lang.System/getProperty" 0 1 (type "static-method" ns nil)) " <sm>"
  #("java.lang.System/getSecurityManager" 0 1 (type "static-method" ns nil)) " <sm>"
  #("java.lang.System/getenv" 0 1 (type "static-method" ns nil)) " <sm>"
  #("java.lang.System/identityHashCode" 0 1 (type "static-method" ns nil)) " <sm>"
  #("java.lang.System/in" 0 1 (type "static-field" ns nil)) " <sf>"
  #("java.lang.System/inheritedChannel" 0 1 (type "static-method" ns nil)) " <sm>"
  #("java.lang.System/lineSeparator" 0 1 (type "static-method" ns nil)) " <sm>"
  #("java.lang.System/load" 0 1 (type "static-method" ns nil)) " <sm>"
  #("java.lang.System/loadLibrary" 0 1 (type "static-method" ns nil)) " <sm>"
  #("java.lang.System/mapLibraryName" 0 1 (type "static-method" ns nil)) " <sm>"
  #("java.lang.System/nanoTime" 0 1 (type "static-method" ns nil)) " <sm>"
  #("java.lang.System/out" 0 1 (type "static-field" ns nil)) " <sf>"
  #("java.lang.System/runFinalization" 0 1 (type "static-method" ns nil)) " <sm>"
  #("java.lang.System/setErr" 0 1 (type "static-method" ns nil)) " <sm>"
  #("java.lang.System/setIn" 0 1 (type "static-method" ns nil)) " <sm>"
  #("java.lang.System/setOut" 0 1 (type "static-method" ns nil)) " <sm>"
  #("java.lang.System/setProperties" 0 1 (type "static-method" ns nil)) " <sm>"
  #("java.lang.System/setProperty" 0 1 (type "static-method" ns nil)) " <sm>"
  #("java.lang.System/setSecurityManager" 0 1 (type "static-method" ns nil)) " <sm>"
```

**Comment by dgutov** [comment]
> Major mode: cider-repl-mode

This is a major mode for a REPL.

You said completion didn't work in Clojure code buffers?

**Comment by stardiviner** [comment]
Same in clojure source code.

```
Emacs 28.0.50 (x86_64-pc-linux-gnu) of 2020-08-23 on dark
Company 0.9.13

company-backends: ((company-capf :separate company-yasnippet :separate company-keywords)
 (company-dabbrev-code :with company-abbrev)
 company-files)

Used backend: (company-capf :separate company-yasnippet :separate company-keywords)

Value of c-a-p-f: (cider-complete-at-point t)
Major mode: clojure-mode
Prefix: "java.lang.System/"
Completions:
  #("java.lang.System/arraycopy" 0 1 (type "static-method" ns nil)) " <sm>"
  #("java.lang.System/clearProperty" 0 1 (type "static-method" ns nil)) " <sm>"
  #("java.lang.System/console" 0 1 (type "static-method" ns nil)) " <sm>"
  #("java.lang.System/currentTimeMillis" 0 1 (type "static-method" ns nil)) " <sm>"
  #("java.lang.System/err" 0 1 (type "static-field" ns nil)) " <sf>"
  #("java.lang.System/exit" 0 1 (type "static-method" ns nil)) " <sm>"
  #("java.lang.System/gc" 0 1 (type "static-method" ns nil)) " <sm>"
  #("java.lang.System/getLogger" 0 1 (type "static-method" ns nil)) " <sm>"
  #("java.lang.System/getProperties" 0 1 (type "static-method" ns nil)) " <sm>"
  #("java.lang.System/getProperty" 0 1 (type "static-method" ns nil)) " <sm>"
  #("java.lang.System/getSecurityManager" 0 1 (type "static-method" ns nil)) " <sm>"
  #("java.lang.System/getenv" 0 1 (type "static-method" ns nil)) " <sm>"
  #("java.lang.System/identityHashCode" 0 1 (type "static-method" ns nil)) " <sm>"
  #("java.lang.System/in" 0 1 (type "static-field" ns nil)) " <sf>"
  #("java.lang.System/inheritedChannel" 0 1 (type "static-method" ns nil)) " <sm>"
  #("java.lang.System/lineSeparator" 0 1 (type "static-method" ns nil)) " <sm>"
  #("java.lang.System/load" 0 1 (type "static-method" ns nil)) " <sm>"
  #("java.lang.System/loadLibrary" 0 1 (type "static-method" ns nil)) " <sm>"
  #("java.lang.System/mapLibraryName" 0 1 (type "static-method" ns nil)) " <sm>"
  #("java.lang.System/nanoTime" 0 1 (type "static-method" ns nil)) " <sm>"
  #("java.lang.System/out" 0 1 (type "static-field" ns nil)) " <sf>"
  #("java.lang.System/runFinalization" 0 1 (type "static-method" ns nil)) " <sm>"
  #("java.lang.System/setErr" 0 1 (type "static-method" ns nil)) " <sm>"
  #("java.lang.System/setIn" 0 1 (type "static-method" ns nil)) " <sm>"
  #("java.lang.System/setOut" 0 1 (type "static-method" ns nil)) " <sm>"
  #("java.lang.System/setProperties" 0 1 (type "static-method" ns nil)) " <sm>"
  #("java.lang.System/setProperty" 0 1 (type "static-method" ns nil)) " <sm>"
  #("java.lang.System/setSecurityManager" 0 1 (type "static-method" ns nil)) " <sm>"
```

**Comment by dgutov** [comment]
All right, thanks.

But I have tried to reproduce the problem, and could not. I type `java.lang.System/` - and see the completion popup.

Do you have `/` bound to some non-default command, maybe?

Otherwise, I'll need a step-by-step reproduction scenario starting with `emacs -Q -L ~/.emacs.d./elpa/company-xxxx`.

**Comment by stardiviner** [comment]
I try to reproduce this problem with `emacs -Q -L ...`, It works fine.
Then I use `bug-hunter-init-file` to bisect my init files, after a long time. Finally found the problem.
The `clj-refactor-mode` caused this problem. Don't know why. I check the `clj-refactor-mode` source code, but don't understand how caused this problem.

**Comment by dgutov** [comment]
Interesting!

Here's the reason: https://github.com/clojure-emacs/clj-refactor.el/blob/master/clj-refactor.el#L320

**Comment by dgutov** [comment]
I take it you didn't check the binding for `/`?

**Comment by dgutov** [comment]
You can add this command to `company-begin-commands` to fix the problem.

**Comment by stardiviner** [comment]
> I take it you didn't check the binding for `/`?

Yes, I only use `M-.` to jump code following minor-mode definition and some function definitions, have not check all code.
Thanks a lot! @dgutov.  for other people who might got same problem. I paste the solution code here.
```elisp
;; fix "/" does not trigger `company-mode' auto popup.
  (add-to-list 'company-begin-commands 'cljr-slash)
```
