### ISSUE TITLE
error-messages after updating company 

### ISSUE THREAD

**Issue by phisu** [company-mode/company-mode#1007]
i updated 
company-box to 20200904.533
company-lsp to 20190612.1553
company-prescient to 20200716.1414

and now i get frequently the following error-message:

Company: An error occurred in auto-begin
Company: frontend company-box-frontend error "Wrong number of arguments: ((t) (string) (let ((selection company-selection) (common (or company-common company-prefix))) (save-current-buffer (set-buffer (company-box--get-buffer)) (erase-buffer) (insert string "
") (setq mode-line-format nil display-line-numbers nil truncate-lines t cursor-in-non-selected-windows nil) (set (make-local-variable (quote scroll-step)) 1) (set (make-local-variable (quote scroll-conservatively)) 10000) (set (make-local-variable (quote scroll-margin)) 0) (set (make-local-variable (quote scroll-preserve-screen-position)) t) (add-hook (quote window-configuration-change-hook) (quote company-box--prevent-changes) t t) (company-box--update-line selection common)))), 2" on command show

**Comment by dgutov** [comment]
> company-box-frontend error

Please report that to `company-box`.
