### ISSUE TITLE
How to cycle overloads

### ISSUE THREAD

**Issue by thomasheartman** [company-mode/company-mode#1008]
Hi,

For languages that allow method overloading (in my case C# specifically), is there a way to see which overloads exist and to select a specific overload?

For instance, when completing `_logger.LogIn`, I'm shown an entry that says 
```
LogInformation void LogInformation(EventId eventId, Exception exception, string message, params object[] args) (+ 3 overloads(s)) (Method)
```

Is there a way to select and have it complete to one of the other overloads? In this case, I'd like to use the overload that only takes a single string. I've done some searching around the web and the issue tracker, but haven't found what I'm looking for. 

Thanks for all your work on an amazing package, by the way!

**Comment by dgutov** [comment]
Hi!

Do you mean a way to choose the overload before template expansion, to see a different list of inserted arguments?

**Comment by thomasheartman** [comment]
Yeah, that sounds like what I want! Sorry if it wasn't explained well.

Just to make it clear, I'd like to be able to expand the same method into this:
```cs
_logger.LogInformation(string message)
```
instead of into this:
```cs
_logger.LogInformation(EventId eventId, Exception exception, string message, params object[] args)
```

But because this overload doesn't appear in the list of completions, I don't know how I'd achieve this.

**Comment by dgutov** [comment]
> But because this overload doesn't appear in the list of completions

Good observation. Why doesn't it?

What backend are you using for C#? `company-diag` can help if you don't know.

And we should ask the author(s) of that backend.

**Comment by thomasheartman** [comment]
Here's the result of company-diag. I don't think I've done anything fancy with it.

```
Emacs 28.0.50 (x86_64-apple-darwin19.2.0) of 2020-01-14 on aa-c0d9e-015
Company 0.9.13

company-backends: (company-tide company-bbdb company-semantic company-cmake company-capf company-clang company-files
	      (company-dabbrev-code company-gtags company-etags company-keywords)
	      company-oddmuse company-dabbrev)

Used backend: company-capf
Value of c-a-p-f: (lsp-completion-at-point)
Major mode: csharp-mode
Prefix: ""
Completions: none
```

I haven't really dug around much in how Company is configured before, so I'm not sure exactly what this means. Is `company-capf` the backend you're looking for here?

By the way, here's a screenshot of what I get. As you can see, it clearly states that there are overloads available, but it doesn't show them explicitly.

![Screenshot 2020-09-11 at 11 56 58](https://user-images.githubusercontent.com/17786332/92907774-e881a800-f425-11ea-89d0-08c76b4d9b17.png)

**Comment by dgutov** [comment]
> Is company-capf the backend you're looking for here?

Yup. And then I look at the next line.

So this is a responsibility of `lsp-mode`.

@yyoncho @kiennq What do you think? Does `lsp-mode` have a toggle for showing all overloads?

Ideally, either the popup shows all overloads, and post-completion inserts arguments in a template. Or there is no arguments insertion in post-completion, but a callsig popup is shown instead. Especially if said popup allows switching between overloads. As I recall you had a new feature that could do that (or gain that capability)?

**Comment by yyoncho** [comment]
> Does `lsp-mode` have a toggle for showing all overloads?

There is no such thing in the spec but csharp language server might have a custom setting to achieve that.

**Comment by dgutov** [comment]
OK. Could you clarify, then, where does the `+ 3 overload(s)` string come from? Is that just part of their annotation?

**Comment by yyoncho** [comment]
It is annotation coming from the language server and we cannot control it on client-side. At least with core spec.

**Comment by dgutov** [comment]
All right, thank you.

I think it would be great if `lsp-mode` did either:

1. Prompt, before template expansion, which overload to use. If that's feasible, of course. Possibly guarded by a user option.
2. Didn't insert arguments at all, and relied exclusively on the callsig popup. After all, the purpose of the arguments insertion is just to show which arguments are available, right? The language server doesn't insert actual local variables, matches by types?

**Comment by yyoncho** [comment]
1. There is no such thing in the spec. There is only one snippet sent by the server.
2. Some servers are smart and insert the best-guessed arguments matched by type. But anyway, the inserted values are the snippet placeholders. You could go through them using TAB. I guess we can expand the snippet without the placeholders, I think that there was a feature request in lsp-mode repo about that.

**Comment by dgutov** [comment]
> You could go through them using TAB.

Or delete the extra fields with `C-d`, if I'm not mistaken, if `yasnippet` is used.

> Some servers are smart and insert the best-guessed arguments matched by type.

That is interesting.

> I guess we can expand the snippet without the placeholders, I think that there was a feature request in lsp-mode repo about that.

Is that feasible to implement?

**Comment by yyoncho** [comment]
> Is that feasible to implement?

I think it is a matter of running regex over the snippet to expand, no?

**Comment by dgutov** [comment]
I suppose. Some languages might have unusual syntax, but you could solve that if/when it become a problem.

**Comment by yyoncho** [comment]
> I suppose. Some languages might have unusual syntax, but you could solve that if/when it become a problem.

I think it is a matter if the snippet syntax which is well defined.

**Comment by thomasheartman** [comment]
I'm very happy to see the fruitful discussion on this issue! Thank you very much for helping me understand what the problem is.

Just to make sure that I've understood what's going on here, would it be accurate to say that:
- The C# language server currently only supplies a single overload for each method (though it does inform you that overloads exist).
- Because of this, Company and lsp-mode doesn't have the required information to allow the user to cycle between overloads.
- A suggested remedy for this is to insert the snippet without any template arguments (so it would expand to `LogInformation(|)` instead of `LogInformation(|string msg)`, where `|` is the cursor position). This may or may not be implemented by lsp-mode, but there is already an issue for it in the lsp-mode repo.

Is there anything else I can do to help or any more information I can provide?

**Comment by yyoncho** [comment]
> * A suggested remedy for this is to insert the snippet without any template arguments (so it would expand to `LogInformation(|)` instead of `LogInformation(|string msg)`, where `|` is the cursor position). This may or may not be implemented by lsp-mode, but there is already an issue for it in the lsp-mode repo.

Just to clarify: the lsp-mode issue is about stripping the placeholders and pretty much this is everything we can do. So, if there are 3 parameters and before lsp-mode/yasnippet will insert `(foo|, bar, baz)` and after the fix lsp-mode will insert `(|,,)`. In both cases you will be able to iterate the positions via TAB.

As a side note, I suspect that there is a setting in the server which will result in all overloads being listed as separate items but I was unable to find that in C# sources. FYI the server settings are unique and most of the time undocumented and we have to find them in the server sources. I checked the server source but it seems to me that the completion items are provided by some of the server dependencies.

**Comment by thomasheartman** [comment]
>  if there are 3 parameters and before lsp-mode/yasnippet will insert `(foo|, bar, baz)` and after the fix lsp-mode will insert `(|,,)`

Thanks for the clarification! I think I'd prefer to have the placeholders in that case, but that really just comes down to personal preference.

Thanks also for looking through the server source (and your general work on the lsp-mode package), by the way. It seems like a useful setting to have, but I guess there's not much we can do if it's not there at all.

@dgutov Do you want (me) to close this issue? It seems there's nothing here for company to handle, at least, and it also seems like the lsp-mode crew is out of luck with regards to this one.

**Comment by dgutov** [comment]
I'm curious what's the VS Code behavior with this language server. Is it the same as lsp-mode's default?

Looking at some languages servers, I was under the impression that the recent trend was to forego arguments insertion in favor of callsig popup alone (the "other" option in one of my first messages here). Which would mean only inserting the parens but not the commas inside of them. But maybe it's still different for different servers.

**Comment by dgutov** [comment]
@thomasheartman

> Do you want (me) to close this issue?

If you like. I was going to close it as soon as the discussion exhausted itself. Thanks for the question, either way,
