### ISSUE TITLE
Visual bugs with completion menu

### ISSUE THREAD

**Issue by ludwj61** [company-mode/company-mode#1013]
![image](https://user-images.githubusercontent.com/42984254/94436314-4d4d3a00-016a-11eb-9021-75dcbc6b09ba.png)
![image](https://user-images.githubusercontent.com/42984254/94436177-20008c00-016a-11eb-800c-4580702c8ca4.png)

As in the images, the completion menu does a few weird things. 

First, it makes line numbers disappear (1st image) (and I couldn't get it to happen but I feel like I've seen it do other weird things with line numbers, like make extra show up if the completion menu appears at the end of a file.

Second, the background of the completion menu extends the entirety of the buffer (both images).

Third, the background of the completion menu extends past the end of completion menus with few options (2nd image).

I am on Arch Linux (btw) with i3gaps.
Emacs 27.1 (occurs with native comp and pgtk as well)
I am using DOOM emacs config

**Comment by dgutov** [comment]
Hi!

The line numbers thing is expected, it's a limitation of overlay-based rendering. Use `company-posframe` or `company-box` to avoid it.

The background things, however, shouldn't be. Can you reproduce it with the default theme?

**Comment by ludwj61** [comment]
Thanks for the help. It actually _doesnt_ happen with the default theme, I never thought it would be theme related as it happens with all of doom themes. I guess this is something that repo has to fix, then. 

Would you happen to know if there's any known tweak I can make to the offending themes to fix this myself?

**Comment by dgutov** [comment]
Could you give an example of such theme? I'll take a look then.

**Comment by ludwj61** [comment]
sure, here is one https://github.com/ianpan870102/vscode-dark-plus-emacs-theme

**Comment by dgutov** [comment]
Hi again!

I've installed the theme from MELPA (20200926.900) and tried to reproduce this, with company-mode from master, and both Emacs 27.1 and Emacs 28 (master). And I couldn't.

First, are you sure that no alternative package for popup is used, such as `company-box`? There was a recent report about that.

If not, could you provide a repro step-by-step starting with vanilla Emacs (`emacs -Q`)? Both to verify yourself that no extra settings in Doom cause this, or if they do, to include them in the scenario.

And BTW, is that really the right theme? This one I installed uses different colors than those that I see on your screenshots. E.g. light yellow for method names (which are purple on the screenshots). Another difference is I don't see a special background under the current line's number. And the color of that background (on your screenshots) suspiciously matches the color of the glitch (and not the popup's background color).

**Comment by ludwj61** [comment]
Thanks for the reply.

The theme I link was one that was not in doom themes which has the issue for me, but the one I used in the screenshots was doom-one which is in doom-themes. To clarify, I get issues with themes both in and out of doom themes so I just linked a random one I tried.

I am not using any popup, in fact I tested it and when using ``company-box`` or ``company-posframe`` I do not get the issue I described with any theme.

As for testing this outside of doom, I am honestly unsure of how to do so as I have only ever used emacs with doom. For example I've never installed company, an lsp, etc myself. Is there any small config I can copy-paste or something to do this?

Thanks again

**Comment by dgutov** [comment]
All right, thank you for clarifications.

> As for testing this outside of doom, I am honestly unsure of how to do so as I have only ever used emacs with doom. For example I've never installed company, an lsp, etc myself. Is there any small config I can copy-paste or something to do this?

I guess there are two options:

* You report this issue to Doom with a link to this report and hope someone else will do the extra debugging.
* You ask this same question (how do I reproduce and report an issue without Doom) somewhere in that list: https://github.com/hlissner/doom-emacs#getting-help

But in short, it comes down to bisecting your Doom configuration and finding the setting (user option, minor mode, etc) that triggers the bug.

**Comment by dgutov** [comment]
Of course you could alternatively launch a bare Emacs session and install packages one by one (`M-x list-packages`, followed by marking the packages with `i` and then installing them with `x`). It's a good exercise to least Emacs basics, but I'm afraid you'll have to bisect the Doom config anyway, since I'm not seeing this problem with a more "bare" configuration.

**Comment by ludwj61** [comment]
Thanks so much for your help. I will close this as yea this is probably a doom thing, but if I find a fix ill put it here.
