### ISSUE TITLE
Company autocomplete menu / company box blacks out

### ISSUE THREAD

**Issue by noblekid96** [company-mode/company-mode#1015]
I'm using emacs 27.1 with the doom framework. When I'm typing code with company-mode's autocompletion along with company-box and some form of intellisense on, I occasionally encounter a problem whereby the definition snippet and company autocomplete menu displaying black images. Is there a way to mitigate this while retaining company-box ?

( In the screenshots below I was writing Python code but I noticed similar issues while writing Ruby code as well )

Versions:
Emacs v27.1
Doom v2.0.9
Company v0.9.13

![image](https://user-images.githubusercontent.com/44386386/94565151-66a1d380-029b-11eb-9dfe-4197166e6806.png)
![image](https://user-images.githubusercontent.com/44386386/94565162-6dc8e180-029b-11eb-88c5-061b51d03195.png)

**Comment by dgutov** [comment]
Does this only happen with `company-box`?

Should you perhaps file this report to that project?

You also say:

> company autocomplete menu displaying black images

Where is that, on the attached screenshots?

**Comment by noblekid96** [comment]
Yes it only happens with company-box... I didn't know that it was a separate project I will file this issue to them.

> Where is that, on the attached screenshots?

It is not obvious but beside the completion menu, there is a popup with a few words on the method or library definition/docs. The expected behavior is it will show the everything but in the screenshots above, they are truncated and the rest of the popup is just a black canvas.

![image](https://user-images.githubusercontent.com/44386386/94659696-43c4fd00-0337-11eb-8189-e1b0178fca8e.png)

This also occurs for the completion menu popup as well.

If this is not an issue caused by company-mode then you can close this issue. Thanks.

**Comment by dgutov** [comment]
I see, thanks.

But if this also only happens with `company-box-mode` enabled, then it's for them to fix.

**Comment by dgutov** [comment]
BTW, if you're on WSL, it could be a bug in the X server you are using.

At least I remember seeing a report with a glitch like this. It was fixed by switching to another X server.

**Comment by noblekid96** [comment]
Yes I forgot to mention that in my initial opening :) Thank you for telling me about this
