### ISSUE TITLE
Help filtering candidates

### ISSUE THREAD

**Issue by ChabadJDP** [company-mode/company-mode#1016]
Company show candidates and its categories. In the screenshot below, you can see some candidates are instance, other are functions, and they could be class or parameter. I would like to know if I can filter candidates by category (I don't know if this is the correct term). In other words, I would like company to show sometimes only function, or another category, is it possible?

![company candidates](https://user-images.githubusercontent.com/34318013/94575917-2286e280-024b-11eb-8f4a-d990d6d38201.png)

**Comment by dgutov** [comment]
Hi!

It's possible to add such a feature. Perhaps by searching within annotations, or, after we add "completion types" filtering by types directly.

In the example on the screenshot I'm wondering, though: shouldn't the backend do some filtering already? Like, when there is a period before the prefix, shouldn't it only suggest "instance" methods, and not "function"-s? And when there is no period - vice versa.

What backend is this?
