### ISSUE TITLE
Popup tooltip not aligned around double width unicode

### ISSUE THREAD

**Issue by blahgeek** [company-mode/company-mode#1017]
![2020-09-30_14-06-37](https://user-images.githubusercontent.com/1308450/94651333-e75be080-032a-11eb-91d2-920cf4416d5e.png)

See the attached image. The popup window is not aligned correctly due to the double-width unicode character.

**Comment by dgutov** [comment]
You probably already found that out (e.g. by searching this very issue tracker), but this is not supported by the default frontends, and cannot be (overlay-based rendering is not that powerful).

`company-posframe` and `company-box` are the recommended alternatives.
