### ISSUE TITLE
Company-complete does not automatically use company-rtags

### ISSUE THREAD

**Issue by variemai** [company-mode/company-mode#1018]
**Company-complete does not automatically use company-rtags**. Indexing works fine but when I try to use code completion I need to manually invoke the company-rtags. Although company-rtags is included in the company backends. Do I need to change the order of the backend lists? If so, how can I do that?

**Environment (please complete the following information):**
 - OS/Version: Gentoo 5.8.11 kernel
 - RTags(rdm,rc): 2.39.133
 - Emacs: 27.1
 - LLVM/Clang: 10.1

**Comment by dgutov** [comment]
What does `M-x company-diag` say?

**Comment by variemai** [comment]
Nevermind, it is related to another issue. Thanks for your time
