### ISSUE TITLE
Company: backend company-capf error "Symbol’s function definition is void: :interrupted" with args (candidates std)

### ISSUE THREAD

**Issue by chenyidao110** [company-mode/company-mode#1021]
What did you expect to happen?
...After today upgrade, there is something wrong in code complete while edit python/c/c++ source files.

What actually happened?
...
Upgrade doom-emacs as follow:
~/.emacs.d/bin/doom upgrade, then edit python/c/c++ with emacs,but code complete cannot work normally
![95292101-6c9f4200-08a3-11eb-9b89-567d90fc0f50](https://user-images.githubusercontent.com/14362421/95418006-07158900-0969-11eb-9e46-7db9f90b4fdf.png)

Additional details:
message buffer:
Company: An error occurred in auto-begin
Company: backend company-capf error "Symbol’s function definition is void: :interrupted" with args (candidates std)

**Comment by dgutov** [comment]
That's the work of a particular backend. Probably `lsp-mode`.

What does `M-x company-diag` say?

**Comment by chenyidao110** [comment]
> 
> 
> That's the work of a particular backend. Probably `lsp-mode`.
> 
> What does `M-x company-diag` say?

Emacs 27.1 (x86_64-pc-linux-gnu) of 2020-10-07 on DESKTOP-1ODIMFE
Company 0.9.13

company-backends: (company-capf company-yasnippet)

Used backend: company-capf
Value of c-a-p-f: (lsp-completion-at-point)
Major mode: c++-mode
Prefix: ("" . t)

Completions: none(error fetching)

**Comment by dgutov** [comment]
You should report it to `lsp-mode`, then. But you might want to try reinstalling it first.

**Comment by chenyidao110** [comment]
> 
> 
> You should report it to `lsp-mode`, then. But you might want to try reinstalling it first.

Thank you. I will report it to lsp-mode.
