### ISSUE TITLE
frontend company-pseudo-tooltip-frontend error

### ISSUE THREAD

**Issue by OrionRandD** [company-mode/company-mode#1027]
I am getting this error for a few days now

Company: An error occurred in post-command
Company: frontend company-pseudo-tooltip-frontend error "Wrong number of arguments: (2 . 2), 1" on command post-command

**Comment by dgutov** [comment]
Try `M-x toggle-debug-on-error` and then `M-x company-complete-common` to see the backtrace.

**Comment by OrionRandD** [comment]
when I run emacs --debug-init, I get this backtrace:

Debugger entered--Lisp error: (error "Unknown option ‘-init’")
  signal(error ("Unknown option ‘-init’"))
  error("Unknown option `%s'" "-init")
  command-line-1(("-init"))
  command-line()
  normal-top-level()

When I do, M-x toggle-debug-on-error and then M-x company-complete-common to see the backtrace.
Like you told me, I get: 

Debug on Error enabled globally
Error in post-command-hook (evil-repeat-post-hook): (wrong-type-argument number-or-marker-p nil)
Invalid face attribute :extend t [224 times]
Quit

**Comment by podiki** [comment]
Similar error here, `Company: An error occurred in post-command
Company: frontend company-pseudo-tooltip-unless-just-one-frontend error "Wrong type argument: number-or-marker-p, nil" on command post-command`. This started a few days ago, sorry I'm not sure which version was okay before (or any other packages). Emacs version 28.0.50, native (pgtk) compile.

Backtrace:
```
Debugger entered--Lisp error: (wrong-number-of-arguments #<subr company--face-attribute> 1)
  company--face-attribute(nil)
  company--face-attribute((:family "M+ 2p Light") :background)
  company--face-attribute(default :background)
  company--replacement-string((#(" task                                     " 0 1 (mouse-face (company-tooltip-mouse) face (company-tooltip-selection company-tooltip)) 1 5 (mouse-face (company-tooltip-mouse) face (company-tooltip-common-selection company-tooltip-selection company-tooltip)) 5 42 (mouse-face (company-tooltip-mouse) face (company-tooltip-selection company-tooltip))) #(" tasks                                    " 0 1 (mouse-face (company-tooltip-mouse) face (company-tooltip)) 1 5 (mouse-face (company-tooltip-mouse) face (company-tooltip-common company-tooltip)) 5 42 (mouse-face (company-tooltip-mouse) face (company-tooltip)))) nil 1 t nil)
  company-pseudo-tooltip-show(3 1 0)
  company-pseudo-tooltip-show-at-point(14 4)
  company-pseudo-tooltip-frontend(post-command)
  company-pseudo-tooltip-unless-just-one-frontend(post-command)
  company-call-frontends(post-command)
  company-post-command()
```

**Comment by OrionRandD** [comment]
Mine also started some days ago...
It was ok back then...
Seems it is a bug on campany package...

**Comment by dgutov** [comment]
@OrionRandD @podiki Could you both please make sure to update to the latest version of `company` from MELPA?

**Comment by dgutov** [comment]
From the looks of the backtrace, this should have been fixed in https://github.com/company-mode/company-mode/commit/18b7b79d579ac3a93920762742a1eaa35491592f, 3 days ago.

**Comment by OrionRandD** [comment]
@dgutov I do not use melpa. Doom Emacs uses straight   :(

**Comment by OrionRandD** [comment]
But, I suppose I can get in ~/.emacs.d/.local/straight/repos/company-mode and 
git pull
Did this but got this warning
You are not currently on a branch.
Please specify which branch you want to merge with.
See git-pull(1) for details.

    git pull <remote> <branch>

**Comment by dgutov** [comment]
@OrionRandD Try using whichever method Doom offers for updating packages.

straight should pull in the same changes just as well.

**Comment by podiki** [comment]
Thanks, latest updates seems to have fixed it. I should have made sure I was on the latest version (I'm an obsessive updater), thanks for the quick response and fix!
