### ISSUE TITLE
company-complete doesn't show all candidates

### ISSUE THREAD

**Issue by jhartotr** [company-mode/company-mode#1028]
Completion candidates that start with letters between 'a' and 'f' are only shown if I restart emacs and I can insert only one of such completion candidates. After that only candidates starting with 'g' are shown by company-complete, see screenshot below (result of```: C-c SPC```):

![grafik](https://user-images.githubusercontent.com/22501936/96339501-6c6a2800-1095-11eb-802d-e93ce0a81967.png)

What could be the reason of this behavior? In my case it happens with the following versions:

Emacs:
```
GNU Emacs 28.0.50 (build 1, i686-pc-linux-gnu, GTK+ Version 3.22.30, cairo version 1.15.10) of 2020-10-16
```

Company:
```
Package company is installed.

     Status: Installed in ‘company-20201014.2251/’ (unsigned).
    Version: 20201014.2251
     Commit: 5f5949b6ae8ea9df94c6cb3e01d9cae43623b794
    Summary: Modular text completion framework
   Requires: emacs-24.3
Required by: company-emoji-20200612.1902
   Homepage: http://company-mode.github.io/
   Keywords: abbrev convenience matching 
 Maintainer: Dmitry Gutov <dgutov@yandex.ru>
     Author: Nikolaj Schumacher
Other versions: 20201014.2251 (melpa), 0.9.13 (gnu).
```

**Comment by dgutov** [comment]
Hi!

You should probably report that to the backend in question. `company-emoji`, in this case.

**Comment by jhartotr** [comment]
You are right, I checked and there is already an issue for this in company-emoji's github,

https://github.com/dunn/company-emoji/issues/10

 will follow-up there. Thanks.
