### ISSUE TITLE
company-tng breaks company-search-candidates

### ISSUE THREAD

**Issue by dsedivec** [company-mode/company-mode#1030]
Steps to reproduce:

1. Install MELPA and then install company through MELPA
2. Start Emacs, go into `*scratch*` buffer
3. Turn on company-mode: <kbd>M-x</kbd> `company-mode` <kbd>RET</kbd>
4. Turn on company-tng-mode: <kbd>M-x</kbd> `company-tng-mode` <kbd>RET</kbd>
5. Type something with lots of completions, such as `find-` and wait for candidates to appear
6. Type <kbd>C-s</kbd> to start searching
7. Type something to search for, such as `lit` as in `find-file-literally`

Expected results: Candidate `find-file-literally` is selected

Actual results: The candidate above `find-file-literally` is selected (if you try to match the first candidate by searching, the first candidate is never selected)

Tested in Emacs 27.1 and a native-comp build from the prior week, same results in both.  macOS 10.14.6, NS port.  I tested using an empty init.el with company-mode from 5f5949b6ae8ea9df94c6cb3e01d9cae43623b794.  No other packages were installed other than company and its deps.

**Comment by dgutov** [comment]
Hi! Thanks for the report.

@kiennq, could you take a look?

Also Cc @nikital.

**Comment by dgutov** [comment]
Should be fixed now.
