### ISSUE TITLE
Completion attempt with company-jedi backend says "An error occured in auto-begin Wrong type argument: stringp, 126"

### ISSUE THREAD

**Issue by BigBaaadBob** [company-mode/company-mode#1031]
GNU Emacs 26.3 (build 1, x86_64-w64-mingw32)

Using miniconda3 virtual environments

Company and company-jedi installed from Melpa:
```
  company            20201014.2251 installed 
  company-jedi       20200324.25   installed
  pyvenv             20191202.1039 installed 
```
Prereqs installed:
```
$ conda list | grep 'epc\|jedi'
epc                       0.0.5                    pypi_0    pypi
jedi                      0.17.2                   pypi_0    pypi
```
Config:
```
;; company
(eval-after-load "company"
  '(add-to-list 'company-backends 'company-jedi))
(add-hook 'after-init-hook 'global-company-mode)
(setq jedi:server-command "~/.emacs.d/elpa/jedi-core-20191011.1750/jediepcserver.py")
```
No completion ever happens: instead this error occurs:
```
Company: An error occurred in auto-begin
Wrong type argument: stringp, 126
```

Completion seems to be working fine for elisp. I haven't tried any other backends.

**Comment by dgutov** [comment]
Please report that to the author of `company-jedi`.

**Comment by BigBaaadBob** [comment]
I'll do that.  I started here because:

- Company was listed in the text of the error, and
- I don't know enough about elisp to figure out where the error is occurring

Thanks!

**Comment by dgutov** [comment]
You can try:

`M-x toggle-debug-on-error` followed by `M-x company-complete-common` to see the backtrace.

**Comment by BigBaaadBob** [comment]
Thanks @dgutov, that helped.

While I still can't get company-jedi working, this error was my fault.

`(setq jedi:server-command "~/.emacs.d/elpa/jedi-core-20191011.1750/jediepcserver.py")`

should be 

`(setq jedi:server-command '("~/.emacs.d/elpa/jedi-core-20191011.1750/jediepcserver.py"))`

I'll close this.

**Comment by dgutov** [comment]
Oh, excellent.
