### ISSUE TITLE
Input lags only while company popup open

### ISSUE THREAD

**Issue by LoveSponge** [company-mode/company-mode#1034]
I've narrowed down my input lag to be directly linked to the relationship between `company` and `typescript-lsp`. I'm using DOOM emacs latest on emacs 27 so everything is as up to date and optimised as it's gonna get... But even then...

There is horrible input lag (probably milliseconds but feels like it gets worse the longer company is narrowing completions for) when typing. `(setq company-idle-delay nil)` Prevents the popup from coming up, but manually triggering it still gives me the input lag.

I'm not an emacs guru, there could be something incredibly obvious i'm missing, so don't be afraid to point out the obvious. Just looking for help as this has plagued me for a really long time. I've never realised it was actually company that seems to be the root of the issue.

Is there some way i can generate a log of input-delay so that this can be more concretely seen/tested.

Thanks in advance for any help, also thanks for the awesome completion framework.

**Comment by dgutov** [comment]
Hi!

Is that an actual input lag, or it it just waiting for the completion backend to produce some completions?

Perhaps you could make a video. Or a gif.

**Comment by LoveSponge** [comment]
i'm 99% sure it's input lag, as it's not just when the popup appears, but also typing __while__ the it's is open - meaning the completions are already there and theoretically it's just filtering from an existing list...

It almost feels like it's just taking forever to loop over the list and as a result, freezing the view or however it works in elisp. Or maybe looping more times than is necessary, or maybe there are allot of completions... although on other threads i saw that company can handle 10's of thousands of completions gracefully and typescript is only giving <6k.

Unfortunately i'm not able to make a video or a gif of this right now as i'm trying to build gccemacs. Also i'm not sure this would really be visible in a video or a gif, as it's based off when i press the key, which you wouldn't see in the video...

**Comment by LoveSponge** [comment]
Let me know if there's a way to show some kind of debug logs or something that might actually help you... reading my comment and original post back , i realise how useless it is without any kind of logs...

**Comment by dgutov** [comment]
> meaning the completions are already there and theoretically it's just filtering from an existing list

Not necessarily. Whether completions are cached or not, depends on the individual backend, which will make that choice based on which matching method is used.

Does `M-x company-diag` work quickly? You can also measure the time `(company-capf 'candidates "")` takes to evaluate.

**Comment by LoveSponge** [comment]
I think it's related to the specific backend server taking forever to do its thing.
Sorry for the late reply.
