### ISSUE TITLE
Is it possible to disable auto-completion for class methods followed by .?

### ISSUE THREAD

**Issue by flcong** [company-mode/company-mode#1035]
I am using python pandas in Emacs with company-mode. However, the auto-completion of large DataFrames is very slow for the `DataFrame.T` method. So if I don't type the method name of a DataFrame fast enough (e.g. to type `df.apply`), it will get stuck at `df.` for a very long time trying to load the auto-completions. Since I don't really need auto-completion for class methods (`.` followed by method or property names), is it possible to disable auto-completion for this specific case?

**Comment by dgutov** [comment]
What's the backend that you are using? It could be done there, for instance.

`M-x company-diag` can help.

**Comment by flcong** [comment]
```
Emacs 27.1 (x86_64-w64-mingw32) of 2020-08-21 on CIRROCUMULUS
Company 0.9.13

company-backends: (company-capf company-yasnippet)

Used backend: company-yasnippet
Major mode: python-mode
Prefix: #("assign" 0 6
    (fontified t face
                    (rainbow-identifiers-identifiers-6)))
Completions: none
```
Is this what you meant?

**Comment by dgutov** [comment]
Not exactly. Apparently at that position `company-yasnippet` was the backend used?

Which doesn't fit your problem description.

**Comment by flcong** [comment]
Ah. Sorry, I see what you mean. It should be the following?
```
Emacs 27.1 (x86_64-w64-mingw32) of 2020-08-21 on CIRROCUMULUS
Company 0.9.13

company-backends: (company-capf company-yasnippet)

Used backend: company-capf 
Value of c-a-p-f: (python-completion-at-point tags-completion-at-point-function)
Major mode: python-mode
Prefix: "tr"
Completions:
  #("tr.abs" 0 2 (face (completions-common-part)) 3 4 (face (completions-first-difference)))
  #("tr.accrint" 0 2 (face (completions-common-part)) 3 4 (face (completions-first-difference)))
  #("tr.add" 0 2 (face (completions-common-part)) 3 4 (face (completions-first-difference)))
...
```
where `tr` is a very large dataframe. When I type `tr.` it is stuck for a while. After that, when I immediately run `M-x company-diag`, it is stuck for a while, too. So the backend is `company-capf`?

**Comment by dgutov** [comment]
`company-capf` is an adapter, so the actual backend would be `python-completion-at-point`. That's a function from a built-in package in Emacs. It's a "core" package, so newer versions show up in GNU ELPA as well.

So you can request an improvement with `M-x report-emacs-bug` that prefix should start only after `.`. Then you'll need to type `company-minimun-prefix-length` number of characters after `.` first to see the completion popup, for instance (it could also trigger after `.` automatically, based on a user option).

Alternatively, or as a local workaround in the meantime, you can write an around-advice for `python-completion-at-point` that looks at the character before point and returns nil if that character is `.`. Or uses some more complex logic.

**Comment by flcong** [comment]
> `company-capf` is an adapter, so the actual backend would be `python-completion-at-point`. That's a function from a built-in package in Emacs. It's a "core" package, so newer versions show up in GNU ELPA as well.
> 
> So you can request an improvement with `M-x report-emacs-bug` that prefix should start only after `.`. Then you'll need to type `company-minimun-prefix-length` number of characters after `.` first to see the completion popup, for instance (it could also trigger after `.` automatically, based on a user option).
> 
> Alternatively, or as a local workaround in the meantime, you can write an around-advice for `python-completion-at-point` that looks at the character before point and returns nil if that character is `.`. Or uses some more complex logic.

Thank you very much for your advice. I'll dig into it after learning a bit elisp.
