### ISSUE TITLE
(setq company-tooltip-offset-display 'lines) do not work?

### ISSUE THREAD

**Issue by vanniuner** [company-mode/company-mode#1036]
The config do not work,It seems like the default config effected.
(setq company-tooltip-offset-display 'lines)

**Comment by dgutov** [comment]
What do you mean by "do not work"?

I've just tried it, and the popup is rendered as promised (no scrollbar, replaced with before and after counters).

**Comment by vanniuner** [comment]
It means use lines but scrollbar also.

**Comment by dgutov** [comment]
Ah...

Are you using `company-box` or `company-posframe`?

**Comment by vanniuner** [comment]
I use company-box

**Comment by dgutov** [comment]
Please report that problem there, then.
