### ISSUE TITLE
company-gtags does not work with tramp

### ISSUE THREAD

**Issue by Ergus** [company-mode/company-mode#1038]
Hi:

Some backends like company-gtags doesn't work with tramp. I proposed a merge-request #1037 to solve the issues that are:

1. The global executable should be buffer local and searched at least once per buffer.
2. On emacs versions >=27 the executable-find may use the extra parameter REMOTE.
3. The process-file call must be called from the buffer where company is running instead of in a temporal buffer.

**Comment by dgutov** [comment]
Hi! It seems we've desynchronized between the two communication channels.

Here's my reply from the email:

Regarding the problem in general, have you looked into https://www.gnu.org/software/emacs/manual/html_node/elisp/Connection-Local-Variables.html?

I have a vague idea that they might be appropriate here. Haven't looked too closely, though.

But if they help, it would be good to avoid calling `executable-find` for each buffer, at least locally.

Or if that's too complex, maybe try this scheme:

- Do assign a default value to company-gtags-executable (the result of `executable-find`).
- Before it's used, check that the buffer is remote. If not, use the global value. If it is, create a buffer-local value using `executable-find`. You can also cache it based on the "connection" part of the current buffer-file-name (which is returned by `file-remote-p`).

**Comment by Ergus** [comment]
I just pushed two commits implementing both optimizations. Please REVIEW them as I am not sure it is totally ok and I don't have more time for corrections and testing.

Best,

**Comment by dgutov** [comment]
Thanks. I'll merge this now, and try to simplify a bit later.

**Comment by dgutov** [comment]
> he process-file call must be called from the buffer where company is running instead of in a temporal buffer

Could you explain this?

IIUC temporary buffers inherit `default-directory` from the "parent" buffer, so any `process-file` call in there should be performed remotely anyway. And the new `company-gtags--executable` function only references `default-directory` too, right?

**Comment by Ergus** [comment]
> > he process-file call must be called from the buffer where company is running instead of in a temporal buffer
> 
> Could you explain this?
> 
> IIUC temporary buffers inherit `default-directory` from the "parent" buffer, so any `process-file` call in there should be performed remotely anyway. And the new `company-gtags--executable` function only references `default-directory` too, right?

Probably you may be right; I am not totally aware of the hierarchy relations between buffers in lisp; specially the things related with locations. I wrote such a code because that's what I needed to do in counsel-gtags to make it work. But then I was using a different buffer for output, not a temporal one. If you think it may work in tramp without that code, feel free to remove that... `Simpler is better than complicated`

Same applies to the other function. I think there is a simpler approach to check the connection-local variable, because it is set by default in new connections and as it is only one maybe it worth doing something simpler like using `hack-connection-local-variables` instead of `with-connection-local-variables`. Because that code is only needed when the more than one connection buffer is open to a file in the server, but gtags is detected latter (maybe because company is loaded lazily).

**Comment by dgutov** [comment]
> I wrote such a code because that's what I needed to do in counsel-gtags to make it work. But then I was using a different buffer for output, not a temporal one.

Ok, I've reverted that part and made another small change. Please check that it still works for you.

**Comment by dgutov** [comment]
> Same applies to the other function. I think there is a simpler approach to check the connection-local variable

I'd have to revisit that later. If you beat me to it, all the better ;-)

**Comment by Ergus** [comment]
Hi:

Probably is is not simpler from the code point of view after trying a bit and doing it optimal. The following code (untested) describes the simpler/optimal approach to search for a connection-local variable and only call find-executable in the worst case. 

This also avoids some internal calls like `with-connection-local` that sets and resets the environment. The execution is fine, the only issue is that the code looks complex and ugly... but that's probably something to solve in the api. Specially `hack-connection-local-variables` may have some equivalent that just returns the alist and connection-local-set-profile-variables should have something to append/add/modify.

```
(defun company-gtags--search-connection-var-executable (var-connection executable)
  "Search cached value for VAR-CONNECTION in connection local vars."
  (if (boundp var-connection)
      ;; connection local search happened before opening this
      ;; buffer. So the connection variable is already set.
      (symbol-value var-connection)

    ;; else there are 2 possibilities:
    ;; 1. executable was already found in another remote buffer in the same host but after this buffer was open.
    ;; 2. no executable was found yet.
    (let* ((enable-connection-local-variables t)
	   (host (file-remote-p default-directory 'host))
	   (criteria `(:machine ,host))
	   (symvars (intern (concat host "-gtags")))
	   connection-local-variables-alist
	   pair executable)

      ;; Writes to connection-local-variables-alist
      (hack-connection-local-variables criteria)

      ;; Search in connection-local-variables-alist
      (setq pair (assq var-connection connection-local-variables-alist))
      ;; if pair -> 1: so return the cdr
      (if pair (cdr pair)

	;; else -> 2: search executable-find
	(setq executable (executable-find executable t))

	;; create a profile
	(connection-local-set-profile-variables
         symvars
         `((,var-connection . ,executable)))

	;; set as local
	(connection-local-set-profiles criteria symvars)
	executable))))
```

Best,
Ergus

**Comment by Ergus** [comment]
BTW: 

I just checked some of the improvements you did to my previous pull request. And I will like to do some comments/questions.

1. The var `company-gtags--executable` is buffer local any way. Setting it in the function will make the function exit on the very first `cond` in the following calls, like caching it directly. In general the idea is to avoid `with-connection-local-variables` which does a lot of iterative things to set and reset the environment; undesirable when several connection-local variables are available.

2. In the same function I forgot to add company-gtags--executable after calling `connection-local-set-profiles` to return it.

3. I think that a more general function like the one in the previous message could be more useful; ugly, but efficient ;p. WDYT?

**Comment by dgutov** [comment]
> The var company-gtags--executable is buffer local any way. Setting it in the function will make the function exit on the very first cond in the following calls, like caching it directly

Why, yes. Is it a problem? I figured setting it once per buffer is what we wanted anyway.

> In the same function I forgot to add company-gtags--executable after calling connection-local-set-profiles to return it.

I have added it now. Please test and let me know: does the current `company-gtags` work in the remote case?

I don't have any remote machines I regularly work with (certainly none with GNU Global installed), so it's difficult for me to do any proper testing of this feature.

> I think that a more general function like the one in the previous message could be more useful; ugly, but efficient ;p. WDYT?

I don't really know, I'm not a regular Tramp user. It's probably better to discuss this with @albinus.

Is the longer code snippet trying to avoid using `with-connection-local-variables`? Does that one add a significant overhead?

Looking at the docs, it seems idiomatic to use it, and since it's employed even in `start-file-process-shell-command`, it must be fast. Our use seems to be closer to what the `shell` function does, though.

**Comment by Ergus** [comment]
> 
> Why, yes. Is it a problem? I figured setting it once per buffer is what we wanted anyway.
>
Yes, but 
```
(t     ;; use default value (searched locally)
    company-gtags-executable) 
```

Is not setting it, just returning. So following calls will need to check all the previous conditions. You removed the setq-local in 3a27fd960ac76a98c166c03be5145815 that's why I am asking.

**Comment by dgutov** [comment]
> So following calls will need to check all the previous conditions.

Yes. But this way any customization of `company-gtags-executable` will take effect immediately locally. Which seems like a good thing, and a continuation of the previous behavior, at least for the local case.

All 3 checks are indeed repeated every time, but `benchmark` says that `(company-gtags--executable)` takes ~0.1 ms on my machine, so it seems like they're cheap enough.

**Comment by Ergus** [comment]
> > So following calls will need to check all the previous conditions.
> 
> Yes. But this way any customization of `company-gtags-executable` will take effect immediately locally. Which seems like a good thing, and a continuation of the previous behavior, at least for the local case.
> 
> All 3 checks are indeed repeated every time, but `benchmark` says that `(company-gtags--executable)` takes ~0.1 ms on my machine, so it seems like they're cheap enough.

Ok then. I don't actually know the local behavior because I never use company-gtags for local editing ;p. I have lsp for that. (Which btw removed the company-lsp support)

> Is the longer code snippet trying to avoid using with-connection-local-variables? Does that one add a significant overhead?

Yes and no, `with-connection-local-variables` does too much work we don't actually need and the actual code cannot be reused in company-ctags or company-clang etc. In the new code there is an extra condition (as explained); because the variable may be set already so in that case the call to `with-connection-local-variables` is not needed and we can exit earlier. Then the reset of the environment at the end of `with-connection-local-variables` is not needed either. IMO the new code is simpler/cleared and more efficient. And could be reused in many other places. It just looks more complex because of the comments and the inputs. But is basically the same. just with the extra if.

**Comment by dgutov** [comment]
> Ok then. I don't actually know the local behavior because I never use company-gtags for local editing ;p. I have lsp for that

Yeah. I do believe we have users who stay with etags/gtags/etc, though. I use a custom solution rather than LSP, too.

> (Which btw removed the company-lsp support)

It still works with company, though (through capf).

> Yes and no, with-connection-local-variables does too much work we don't actually need and the actual code cannot be reused in company-ctags or company-clang etc. In the new code there is an extra condition (as explained); because the variable may be set already so in that case the call to with-connection-local-variables is not needed and we can exit earlier. Then the reset of the environment at the end of with-connection-local-variables is not needed either. IMO the new code is simpler/cleared and more efficient. And could be reused in many other places. It just looks more complex because of the comments and the inputs. But is basically the same. just with the extra if.

OK, I see it. And the new code is not that much longer (just by a few lines, I guess). Despite that, `with-connection-local-variables` is probably fast enough, even though it does extra work.

Either way, I'd be happy to accept a tested-and-working patch that replaces `with-connection-local-variables` with the approach you have shown above, that calls `hack-connection-local-variables` instead. That should take only several lines.

If you wanted to add a backend- and executable-agnostic helper function like `company-gtags--search-connection-var-executable` -- even better, but in that case I'd like to see a patch that updates at least two backends to use it.

**Comment by dgutov** [comment]
Should be fixed now, with that merge request and subsequent reports.
