### ISSUE TITLE
 Default config can't auto complete string in current buffer.

### ISSUE THREAD

**Issue by zw963** [company-mode/company-mode#1041]
I want to auto-complete the string `replace_regex` in following buffer.

![image](https://user-images.githubusercontent.com/549126/102686246-4988fb00-4221-11eb-9f01-86014632cae6.png)

As it does when used with AC.

![image](https://user-images.githubusercontent.com/549126/102686277-74734f00-4221-11eb-99b4-11d4b5ea6dc7.png)

But it return many don't understand candidates.

Following is my config: (Run with very few package)

```cl
(require 'company)
(require 'company-capf)
(add-hook 'after-init-hook 'global-company-mode)
(setq company-show-numbers t)
(define-key company-active-map (kbd "C-n") 'company-select-next)
(define-key company-active-map (kbd "C-p") 'company-select-previous)
(define-key company-active-map (kbd "C-s") 'company-filter-candidates)
(setq company-frontends
      '(company-pseudo-tooltip-unless-just-one-frontend
        company-preview-frontend
        company-echo-metadata-frontend))
```

Following is my backends

```
(company-bbdb company-semantic company-cmake company-capf company-clang company-files
              (company-dabbrev-code company-gtags company-etags company-keywords)
              company-oddmuse company-dabbrev)
```

Thank you.

**Comment by dgutov** [comment]
Which source from auto-complete gave that result?

Where do the other candidates come from with company, in your opinion?

**Comment by zw963** [comment]
Sorry for late.

> Which source from auto-complete gave that result?

Following is `ac-sources`, 
(ac-source-abbrev ac-source-dictionary ac-source-words-in-same-mode-buffers)''

i guess it come from ac-source-words-in-same-mode-buffers?
so, how to get above same behavior use company as AC recommendation?

> Where do the other candidates come from with company, in your opinion?

I tested one by one.

`repo-add` seems like come from this:   (company-dabbrev-code company-gtags company-etags company-keywords)

But for `replace_space_to_new_line`, and `replace_space_with__`, It's so weird those word come from ...
i remove all backends, to only left one, `company-capf`, i can still get those both candidate.

Thank you.

**Comment by dgutov** [comment]
> i remove all backends, to only left one, company-capf, i can still get those both candidate.

Then it comes from one of your `completion-at-point-functions`. Those generally provide better quality completions than dabbrev. But if you really want AC-like behavior (not sure why), excluding `company-capf` from your configuration should help.

**Comment by zw963** [comment]
> > i remove all backends, to only left one, company-capf, i can still get those both candidate.
> 
> Then it comes from one of your `completion-at-point-functions`. Those generally provide better quality completions than dabbrev. But if you really want AC-like behavior (not sure why), excluding `company-capf` from your configuration should help.

Thank you, i tried, current `company-backends` is `(company-bbdb company-semantic company-capf)`.

But, i can't get expected result in current `(sh-mode)` buffer.

In fact, there is no any candidates

![image](https://user-images.githubusercontent.com/549126/104814278-fd919c00-5848-11eb-9d74-570416275b2a.png)

but, i expect it can auto-complete `replace_regex` in current buffer.

**Comment by dgutov** [comment]
So you get the "weird" completions from `company-capf` but not the one you wanted?

What does `M-x company-diag` say?

**Comment by zw963** [comment]
> So you get the "weird" completions from `company-capf` but not the one you wanted?
> 
> What does `M-x company-diag` say?

Emacs 27.1 (x86_64-pc-linux-gnu) of 2020-08-29 on juergen
Company 0.9.13

company-backends: (company-capf)

Used backend: company-capf
Value of c-a-p-f: (sh-completion-at-point-function comint-completion-at-point t)
Major mode: sh-mode
Prefix: "repl"
Completions:
  #("replace_space_with__" 0 4 (face (completions-common-part)) 4 5 (face (completions-first-difference)))
  #("replace_space_to_new_line" 0 4 (face (completions-common-part)) 4 5 (face (completions-first-difference)))

**Comment by dgutov** [comment]
Apparently, the completion function in `sh-mode` is not very smart. And it only suggests functions defined in the current file.

If you prefer how `company-dabbrev-code` works, why not use that instead?

**Comment by zw963** [comment]
> Apparently, the completion function in `sh-mode` is not very smart. And it only suggests functions defined in the current file.
> 
> If you prefer how `company-dabbrev-code` works, why not use that instead?

In fact,  my `company-backends` is: `(company-semantic company-capf company-files
		  (company-dabbrev-code company-gtags company-etags company-keywords)
		  company-dabbrev)`

But,  when i typing `repl`,  still can't get expected result.

![image](https://user-images.githubusercontent.com/549126/104939679-ae37a100-59eb-11eb-9d36-7b3e04b7984b.png)


```
Emacs 27.1 (x86_64-pc-linux-gnu) of 2020-08-29 on juergen
Company 0.9.13

company-backends: (company-semantic company-capf company-files
		  (company-dabbrev-code company-gtags company-etags company-keywords)
		  company-dabbrev)

Used backend: company-capf
Value of c-a-p-f: (sh-completion-at-point-function comint-completion-at-point t)
Major mode: sh-mode
Prefix: "repl"
Completions:
  #("replace_space_with__" 0 4 (face (completions-common-part)) 4 5 (face (completions-first-difference)))
  #("replace_space_to_new_line" 0 4 (face (completions-common-part)) 4 5 (face (completions-first-difference)))
```

**Comment by dgutov** [comment]
Try removing `company-capf` from the list. Maybe only do that in buffer-local value of `company-backends` set inside `sh-mode-hook`.

**Comment by zw963** [comment]
> Try removing `company-capf` from the list. Maybe only do that in buffer-local value of `company-backends` set inside `sh-mode-hook`.

If i remove `company-capf`, will get nothing when i start with `repl`, the current issue is, how to get what i expected result , `replace_regex` ??

Thank you.

**Comment by dgutov** [comment]
You can create group with `company-capf` and `company-dabbrev-code` in it.

**Comment by zw963** [comment]
It's working after add `'company-dabbrev-code` into company-backends, thank you.

```cl
(add-hook 'company-mode-hook '(lambda ()
                                (add-to-list 'company-backends 'company-dabbrev-code)
                                ))
```

**Comment by zw963** [comment]
> You can create group with `company-capf` and `company-dabbrev-code` in it.

Hi, @dgutov , more than one year passed since ask question, i still don't now what the group means.

Please ignore those comment before this one, i have some question for you help, thank you.

-------------------------

 Following is my default company-backends

```el
(company-bbdb company-semantic company-cmake company-capf company-clang company-files
              (company-dabbrev-code company-gtags company-etags company-keywords)
              company-oddmuse company-dabbrev)
```

1.  what is the difference of following form?

( (company-dabbrev-code company-gtags company-etags company-keywords) company-dabbrev)
and

(company-dabbrev-code company-gtags company-etags company-keywords  company-dabbrev)

2.  for ( company-capf company-dabbrev-code), if one candidate is matching on company-capf, it never retrieve the matching from company-dabbrev-code, right?, can we have both of them candidate all show on tooltip, and let me select it?


Thank you.
