### ISSUE TITLE
Provide option to keep completion dialog open even if there is only one match

### ISSUE THREAD

**Issue by yyoncho** [company-mode/company-mode#1046]
As per discussion at https://github.com/emacs-lsp/lsp-mode/pull/2483

IMHO this should be the default behaviour considering the fact that it is very confusing for the users using completion backends which require post-completion.

Screenshot from vscode:

![image](https://user-images.githubusercontent.com/13259670/103452481-b4820980-4cd8-11eb-9c0e-8915af1331b7.png)

cc @kiennq

**Comment by dgutov** [comment]
Hi! Thanks for filing this.

Looking at the screenshot, it seems VS Code shows the popup even when completion won't have any visible effect, right?

No associated snippet or the like.

**Comment by yyoncho** [comment]
> Looking at the screenshot, it seems VS Code shows the popup even when completion won't have any visible effect, right?

Yes.

**Comment by dgutov** [comment]
This should do it.

**Comment by kiennq** [comment]
@dgutov The case of `company--continue` is missed, PR here #1047
