### ISSUE TITLE
company cannot use capf-functions

### ISSUE THREAD

**Issue by Vurp** [company-mode/company-mode#1048]
Company cannot seem to access any completion at point functions. `M-x completion-at-point` gives me a window with completions (as it should), but `M-x company-capf` only gives me the message: "Cannot complete at point" in the minibuffer.

Emacs version: 27.1
Company version: 0.9.13

**Comment by Vurp** [comment]
As it turns out I can use `M-x company-capf` in a elisp buffer but not in a slime enabled lisp buffer.

**Comment by dgutov** [comment]
Hi!

What does `M-x company-diag` say there?

**Comment by Vurp** [comment]
Here are the outputs:

```
Emacs 27.1 (x86_64-pc-linux-gnu) of 2020-07-31 on dhcp-10-253-232-203
Company 0.9.13

company-backends: (company-bbdb company-eclim company-semantic company-clang company-xcode company-cmake company-capf company-files
              (company-dabbrev-code company-gtags company-etags company-keywords)
              company-oddmuse company-dabbrev)

Used backend: company-capf
Value of c-a-p-f: (tags-completion-at-point-function)
Major mode: emacs-lisp-mode
Prefix: "defu"
Completions:
  #("defun*" 0 4 (face (completions-common-part)) 4 5 (face (completions-first-difference)))
  #("defun-gmm" 0 4 (face (completions-common-part)) 4 5 (face (completions-first-difference)))
  #("defun-markdown-ref-checker" 0 4 (face (completions-common-part)) 4 5 (face (completions-first-difference)))
  #("defun" 0 4 (face (completions-common-part)) 4 5 (face (completions-first-difference)))
  #("defun-markdown-buffer" 0 4 (face (completions-common-part)) 4 5 (face (completions-first-difference)))
 ``` 
 
 ```
  Emacs 27.1 (x86_64-pc-linux-gnu) of 2020-07-31 on dhcp-10-253-232-203
Company 0.9.13

company-backends: (company-bbdb company-eclim company-semantic company-clang company-xcode company-cmake company-capf company-files
              (company-dabbrev-code company-gtags company-etags company-keywords)
              company-oddmuse company-dabbrev)

Used backend: (company-dabbrev-code company-gtags company-etags company-keywords)

Major mode: lisp-mode
Prefix: #("defu" 0 4
  (fontified t))

Completions: none
```

I have managed to replicate the issue with `emacs -q` and loading company and slime separately, so the issue is not my personal config.

**Comment by dgutov** [comment]
Looks like the completion function you're using in `lisp-mode` is `tags-completion-at-point-function`.

Your completion is based on etags, right?

If so, this is because `company-capf` blacklists this function, to give `company-clang` and `company-files` a chance.

The built-in backend you're looking for is `company-etags`. Isn't it working?

**Comment by Vurp** [comment]
> Your completion is based on etags, right?

No. It doesn't seem that way to me judging from the output above. 

If I try to complete from `(def` in the lisp buffer I get a few completions based on dabbrev but nothing from etags or capf.

**Comment by dgutov** [comment]
But you do have a tags table visited?

**Comment by dgutov** [comment]
If so, is it in some parent directory of the current buffer?

**Comment by Vurp** [comment]
> But you do have a tags table visited?

> If so, is it in some parent directory of the current buffer?

Not that I know of. I have not explicitly used any tag generating command or program and as far as I know neither Emacs or slimes completion relies on any tags table.

**Comment by dgutov** [comment]
OK then.

Could you evaluate `completion-at-point-functions` see what it's set to, and copy it here?

**Comment by Vurp** [comment]
> Could you evaluate completion-at-point-functions see what it's set to, and copy it here?

```
Value in #<buffer init.lisp>
(slime--completion-at-point
 t)
```

**Comment by Vurp** [comment]
> All right. Do you have `slime-complete-symbol-function` set to something non-nil?

No, `slime-complete-symbol-function` is `nil`.

**Comment by dgutov** [comment]
Could you try evaluating this?

```
(run-hook-wrapped 'completion-at-point-functions
                                     ;; Ignore misbehaving functions.
                                     #'completion--capf-wrapper 'optimist)
```

and then, if it returns nil,

```
(run-hook-wrapped 'completion-at-point-functions
                                     ;; Ignore misbehaving functions.
                                     #'completion--capf-wrapper 'all)
```

**Comment by Vurp** [comment]
As it turns out the default configuration of slime includes a contrib which adds `slime-c-p-c-completion-at-point` to `slime-completion-at-point-functions` which does not appear to work with company. If I remove it from the list, company works without issue.

**Comment by dgutov** [comment]
Perhaps `slime-c-p-c-completion-at-point` does this, as described in `completion-at-point-functions`'s docstring:

```
Each function on this hook is called in turn without any argument and
should return ...
or a function of no arguments to perform completion (discouraged)
...
```

It's an old convention, and it simply cannot work with company because instead of returning necessary data that function will want to perform all the completion process by itself (including the display phase).

Anyway, it's discouraged, and there should be fewer and fewer such functions as time goes on.
