### ISSUE TITLE
Annoying completion order for company-files

### ISSUE THREAD

**Issue by mlemerre** [company-mode/company-mode#1049]
Hi,
I tried to use company as a completion backend for shell buffers, using the following configuration:

`(eval-after-load "shell"
  '(define-key shell-mode-map (kbd "TAB") #'company-complete))
(add-hook 'shell-mode-hook #'company-mode)`

It works quite well, but one behaviour is quite annoying.
 Say I have a directory ~/tmp/foo and another ~/tmp/foo-doc. I write cd ~/tmp/fo, hit tab, and things are partially completed to ~/tmp/foo; but the first candidate is foo-doc and not foo, so if I hit RET, then foo-doc is inserted. It is quite unintuitive that foo is not the first candidate, especially from someone used to bash completion. 

The culprit code seems to be that files are sorted using string-lessp predicate, and if according to that predicate "foo" is smaller than "foo-doc", we do not have that "foo/" is small than "foo-doc/". But I don't know what would be the proper way to fix this code, by removing the / or changing the predicate? I am not very familiar with elisp.

Thanks for company by the way!
Matthieu

**Comment by dgutov** [comment]
Sounds kinda tricky. Some custom sorting logic would be needed, I guess.

Trying it in `eshell` and `shell`, they didn't seem to fare better, so there doesn't seem to be a precedent inside Emacs to follow.

> Thanks for company by the way!

Cheers!

**Comment by dgutov** [comment]
Also see #1001.
