### ISSUE TITLE
Trigger auto-complete with special chars

### ISSUE THREAD

**Issue by iris-garcia** [company-mode/company-mode#1050]
Is it possible to get company complete after a specific char? like the . (dot), even if I have `company-minimum-prefix-length` set to `1`?

I'm trying to achieve this for the last day without success.
Testing in typescript and python, both using `lsp-mode`

`console.` --> should trigger the complete function.

Thanks.

**Comment by dgutov** [comment]
This is up to each individual backend (they get to choose what a dot, for instance, means to them).

**Comment by iris-garcia** [comment]
Thanks @dgutov, and what about `company-capf`? I think this is the one I'm using.

**Comment by dgutov** [comment]
Then it's the completion function that gets to choose. Or, rather, the author of the package that wrote it.

`M-x company-diag` could tell you which completion function is used.

**Comment by iris-garcia** [comment]
```
Used backend: company-capf
Value of c-a-p-f: (lsp-completion-at-point)
```

```
(defun lsp-completion-at-point ()
  "Get lsp completions."
  (when (or (--some (lsp--client-completion-in-comments? (lsp--workspace-client it))
                    (lsp-workspaces))
            (not (nth 4 (syntax-ppss))))
    (let* ((trigger-chars (->> (lsp--server-capabilities)
                               (lsp:server-capabilities-completion-provider?)
                               (lsp:completion-options-trigger-characters?)))
```
So I guess I should ask in `lsp-mode` why the dot is not triggering the completion right?

**Comment by dgutov** [comment]
Yup!

AFAIK it should.

**Comment by iris-garcia** [comment]
Ok, thanks for the help @dgutov, and sorry for opening an issue just for a question.
