### ISSUE TITLE
d780069 breaks a function argument case

### ISSUE THREAD

**Issue by OGAWAHirofumi** [company-mode/company-mode#1055]
d780069 changes regex, and it is assuming there is no ")" in function define. But it is not true.
For example,

```c
static void test(void (*bad)(void))
{
  bad();
}
````

and type t and (company-complete)
The completion list in results is `test(void (*bad)` instead of `test(void (*bad)(void))`.

Parsing c define is much complex than just finding ")". So it would be better to use previous regex.

**Comment by dgutov** [comment]
Thanks for the report.

Could you try this regexp instead? `"\\(([^()]*\\(?:([^()]*)[^()]*\\)*)\\).*"`

The definition then becomes:

```el
(defun company-gtags--annotation (arg)
  (let ((meta (get-text-property 0 'meta arg)))
    (when (string-match (concat (regexp-quote arg)
                                "\\(([^()]*\\(?:([^()]*)[^()]*\\)*)\\).*")
                        meta)
      (match-string 1 meta))))
```

**Comment by OGAWAHirofumi** [comment]
Thanks. Unfortunately, that regex is still wrong for all c defines.
For example,

```c
static void test(void (*foo)(void (*bar)(void)))
{
}
```

**Comment by dgutov** [comment]
All right.

How about this one?

```el

(defun company-gtags--annotation (arg)
  (let ((meta (get-text-property 0 'meta arg)))
    (when (string-match (concat (regexp-quote arg) " *(") meta)
      (with-temp-buffer
        (let ((start (match-end 0)))
          (insert meta)
          (goto-char start)
          (forward-sexp)
          (buffer-substring-no-properties
           start (point)))))))
```

**Comment by OGAWAHirofumi** [comment]
Thanks. Looks like good in my tests except one point.

`" *("` may be better to be `"[ \t]*"` or such?

**Comment by dgutov** [comment]
Does anybody ever put a tab between a function name and its list of arguments? :)

**Comment by OGAWAHirofumi** [comment]
Thanks
