### ISSUE TITLE
company-cmake doesn't work in macOS GUI

### ISSUE THREAD

**Issue by jack2gs** [company-mode/company-mode#1060]
Hi,

It works in TUI but not GUI. Seem due to incorrect `company-cmake-executable` value. In GUI, it's nil but I didn't update it. Not sure why it changed to be nil. And emacs reports:
```
Company backend ’company-cmake’ could not be initialized:
Company found no cmake executable
```
cmake was installed with brew already: `/usr/local/bin/cmake`

* describe the variable in TUI:
```
company-cmake-executable is a variable defined in ‘company-cmake.el’.
Its value is "/usr/local/bin/cmake"
You can customize this variable.

Documentation:
Location of cmake executable.
```
* descripe the variable in GUI:
```
company-cmake-executable is a variable defined in ‘company-cmake.el’.
Its value is nil
Original value was 
"/usr/local/bin/cmake"

  You can customize this variable.

Documentation:
Location of cmake executable.
```

OS: macOS 11.1 Big Sur
Emacs: 27.1
Shell: zsh

Thanks,
Jack

**Comment by jack2gs** [comment]
sorry, found the root cause. `exec-path-from-shell` should run before `company`. Weird, it works in TUI rather than GUI. But anyway, solved. Close it now.

**Comment by dgutov** [comment]
> it works in TUI rather than GUI

That's how it is in macOS. Use a free operating system, if you can.
