### ISSUE TITLE
Can `company-complete` be triggered from `run-at-time`

### ISSUE THREAD

**Issue by kiennq** [company-mode/company-mode#1062]
I'm trying to implement the feature of letting `company-mode` popup show up programmatically from `post-completion`.
The use case is for example showing the completion when user insert `test.` from popup selection.
I've resorted to calling `company-complete`, but it seems that it not showing up popup reliably.

Repo steps:
- In `**scratch**` buffer, type `ta<|>` with `<|>` is cursor position
- Type `Alt + :`, enter `(run-at-time 0 nil #'company-complete)`

Expected: popup is showing up
Actual: Not shown.

If I change the time to something bigger (`0.5`) than `0` then the popup can showing up, but not reliably.
Do we suppose to call `company-complete` from `run-at-time`?

**Comment by dgutov** [comment]
Hi!

This should work, and it hopefully explains why your version didn't:

```el
(run-at-time 0 nil (lambda () (company-complete) (company-post-command)))
```

I agree it's not optimal, though.

**Comment by kiennq** [comment]
Oh, now I see why now. The `post-command-hook` needed to be run.
Thanks
