### ISSUE TITLE
company-files always suggests and inserts lowercase drive letter in Windows-style paths

### ISSUE THREAD

**Issue by cwfoo** [company-mode/company-mode#1064]
When using Emacs on Windows, if I type `C:/Use`, company-files will suggest `c:/Users/`, `c:/Users/All Users/`, etc. Notice that all the completion candidates have a lowercase drive letter although I have typed an uppercase drive letter. If I pick the first completion candidate, company-mode will insert `c:/Users/`. Notice that the inserted drive letter is lowercase although I have typed an uppercase drive letter. This is incorrect behavior.

If the user has typed an uppercase drive letter:
* the completion candidates must show uppercase drive letters, and
* the inserted path must have an uppercase drive letter.

(Somewhat related to #240)

**Comment by dgutov** [comment]
Patch welcome! I don't have a Windows system to test this on, unfortunately.

You might want to start with testing whether `file-name-all-completions` behaves as you want it, too. For instance, by seeing whether file name completion in `M-x shell` or `M-x term` satisfies there requirements.

**Comment by cwfoo** [comment]
Unfortunately, `file-name-all-completions` seems to return lowercase drive letters even if the argument given to it has an uppercase drive letter.

**Comment by dgutov** [comment]
Please `M-x report-emacs-bug`, then. Maybe we'll get some suggestions.
