### ISSUE TITLE
after update previously binded key does not work anymore

### ISSUE THREAD

**Issue by phisu** [company-mode/company-mode#1071]
i have  in my custom-post.el 

(global-set-key (kbd "C-x g") 'magit-status)

after the last update of centaur-emacs  C-x g does not work anymore. the mini-buffer says: C-x g is undefined. what is going wrong?

**Comment by dgutov** [comment]
Wrong bug tracker.

This line should work, though. Seem like you have an error somewhere before in your init script, so that execution doesn't reach it.

**Comment by phisu** [comment]
yes, i think too, it should work. but it does not. it is exactly the same custom-post.el like before the update. 

but when i do M-x magit-status. and then i quit the magit-status-buffer. and then i do C-x g and it works.  before the update C-x g worked at the first attempt.

**Comment by dgutov** [comment]
Before update of what? `company-mode` has no relation to Magit, so even if something broke your bindings, your guess is as good as mine.

Try `emacs --debug-init`, though.

**Comment by phisu** [comment]
sorry, i posted my issue to the wrong project. i should post it to  https://github.com/seagle0128/.emacs.d/. sorry!
