### ISSUE TITLE
company-dabbrev-ignore-case and company-dabbrev-downcase are ignored when completing strings and comments in programming modes

### ISSUE THREAD

**Issue by Franzo-** [company-mode/company-mode#1072]
I only use `company-dabbrev` for strings and comments completion and lately I encountered a strange behaviour: applying the completion always downcases the whole word.
For example: if I am coding in the `*scratch*` buffer and I type `"Lis"` I expect `company-dabbrev` to complete it with `"Lisp"`. This was true since I first started using this package, but now the completion resolves it with the lowercase word `"lisp"`.

This behaviour is a little annoying so I started searching for its root cause. My .emacs.d init file does not change `company-dabbrev` configuration, so its configuration variables should all be set to their default value. `company-dabbrev-ignore-case` and `company-dabbrev-downcase` are set to default too (`keep-prefix` and `case-replace` respectively) and changing their values as suggested in other issues does not produce any noticeable effect.

Searching the log history I found this commit: https://github.com/company-mode/company-mode/commit/288a7617c4c3e5f22a887a17a697ac2bfe4e567d
I am almost sure that this commit is the cause of the regression: I reverted the changes in `company--multi-backend-adapter` function and the downcasing effect disappeared.

Is this the intended behaviour? Are there any ways to circumvent the downcasing of completed words, such as customizing the configuration variables of `company-dabbrev` or using other completion backends for strings and comments?

Thank you for your hard work!

**Comment by dgutov** [comment]
Hi!

There are two separate backends: `company-dabbrev` and `company-dabbrev-code`. They apply in the different contexts (the latter only handles programming major modes and only when outside of strings and comments). 

The `keep-prefix` + `case-replace` combination of often handy but also occasionally a footgun, which we'll need to solve in a better way someday.

Looking at the referenced commit, do you have `company-dabbrev` grouped with something else in `company-backends`? The safe configuration is to have it go after programming-related backends, as is the case in the default `company-backends` value.

Although, if you have it grouped with something like `company-ispell`, I don't have any immediate recommendation for that use case.

**Comment by Franzo-** [comment]
Hi dgutov, thank you for your reply.

This is the result of `company-diag` in the case described in my first post
``` 
Emacs 28.0.50 (x86_64-pc-linux-gnu) of 2021-03-16 on lgw01-amd64-054
Company 0.9.13

company-backends: ((company-tide :with company-yasnippet)
 (company-bbdb :with company-yasnippet)
 (company-cmake :with company-yasnippet)
 (company-capf :with company-yasnippet)
 (company-clang :with company-yasnippet)
 (company-files :with company-yasnippet)
 (company-dabbrev-code company-gtags company-etags company-keywords :with company-yasnippet)
 (company-oddmuse :with company-yasnippet)
 (company-dabbrev :with company-yasnippet))

Used backend: (company-dabbrev :with company-yasnippet)

Major mode: lisp-interaction-mode
Prefix: "Lis"
Completions:
  "lisp"
```

So, `company-dabbrev` is grouped with `company-yasnippet` as any other entry of my `company-backends` and it is the last one of the list.

I changed my startup code to avoid adding `:with company-yasnippet` only to `company-dabbrev` and now strings and comments casing is handled correctly. I think that this workaround could work for me, but maybe it is better to keep this issue open in case someone actually needs to group `company-dabbrev` with some other backend.

**Comment by dgutov** [comment]
> but maybe it is better to keep this issue open in case someone actually needs to group company-dabbrev with some other backend

Yes, sure.

**Comment by joefbsjr** [comment]
> > but maybe it is better to keep this issue open in case someone actually needs to group company-dabbrev with some other backend
> 
> Yes, sure.

Me. I just stumbled at this problem :/ I am trying to group company-dabbrev with company-ispell and it doesn't work 'keep-prefix.

**Comment by Franzo-** [comment]
Hi dgutov, thank you for your work on this old issue.
Unfortunately, your commit seems to have introduced a regression on the use case described in this issue.

I tried to reproduce the same example of my first post (typing `"Lis"` in the `*scratch*` buffer) using Melpa version `20231015.122` of Company-Mode and this error message was reported in the Minibuffer:
```
Company: An error occurred in auto-begin
Company: backend company-dabbrev error "Wrong type argument: sequencep, #s(hash-table size 65 test equal rehash-size 1.5 rehash-threshold 0.8125 data ("This" t "buffer" t "text" t "that" t "saved" t "Lisp" t "evaluation" t "create" t "file" t "visit" t "with" t "enter" t "list" t "packages" t))" with args (candidates Lis)
```

Here is the result of running `company-diag`:
```
Emacs 30.0.50 (x86_64-pc-linux-gnu) of 2023-10-13 on lcy02-amd64-010
Company 0.10.2

company-backends: ((company-tide :with company-yasnippet)
 (company-bbdb :with company-yasnippet)
 (company-cmake :with company-yasnippet)
 (company-capf :with company-yasnippet)
 (company-clang :with company-yasnippet)
 (company-files :with company-yasnippet)
 (company-dabbrev-code company-gtags company-etags company-keywords
                       :with company-yasnippet)
 (company-oddmuse :with company-yasnippet) company-dabbrev)

Used backend: company-dabbrev

Major mode: lisp-interaction-mode
Prefix: "Lis"

Completions: none(error fetching)
```

**Comment by dgutov** [comment]
@Franzo- Hey, thanks for reporting. This was the same as #1413, should be fixed now.
