### ISSUE TITLE
Option to add prefix function to company-capf (and others?)

### ISSUE THREAD

**Issue by joefbsjr** [company-mode/company-mode#1074]
While editing a string or a coment it nice to be able to use `company-dabbrev` and others instead of receinving the "No completion found" from `company-capf`. In some modes it kinda works already, but I found it quite inconsistent, and in some modes, like `latex-mode` with `lsp-mode` it doesn't work at all (at least not while editing normal text). 

I fixed it for me with the following code:
```
(when 
    (cl-some 
        (lambda (func)
            (funcall func))
        company-capf-prefix-functions)
(company-other-backend))
(company-complete)
```

`company-capf-prefix-functions` is a list of functions. If any of them returns non-nil it means we should call `companh-other-backend` or otherwise "skip" company-capf.

However, this code requires a function to directly call `company-complete` or `company-other-backends` what can be less than ideal in certain use cases. I can make a pull request adding a customizable variable to include prefix-functions to `company-capf` or even `company--begin-new`, but I want to know if there is already a way of doing what I did. And if you guys think it is a good idea.

This issue is very similar to #818, but that one seems to be dead, and I don't want it to show other backends when no candidates are found, but to customize prefix treatment.

**Comment by dgutov** [comment]
You can always call `advice-add` on `company-capf`, right?

You make it return nil in select circumstances (like when inside comment or string), and control passes to another backend.
