### ISSUE TITLE
company-gtags regex issue

### ISSUE THREAD

**Issue by Ergus** [company-mode/company-mode#1075]
When using company with gtags there are some issues with the regex in gtags.

When functions has too many arguments there are entries like 
```
void fun(
    arg1,
    arg2
    ) {
        bla;
    }
```

In this case company-gtags--annotation gets an `arg` like:
```
void fun (
```
And in this case doing 

```
(goto-char start)
(forward-sexp)
```

will trigger an error like:
```
"Scan error: "Unbalanced parentheses", 10, 11"
```

Which is correct. 

But I don't know if this can be fixed with different gtags parameters  or adding `ignore-errors` around `forward-sexp`

**Comment by dgutov** [comment]
Hi!

Thanks for the report.

I think the important part is to add a test for this case, and the exact implementation choice is secondary.

**Comment by Ergus** [comment]
```lisp
  (let ((str (propertize
              "munmap"
              'meta "void munmap(")))
    (should (equal (company-gtags 'annotation str)
                   "(struct task *ctx, vaddr_t vaddr)")))
```

**Comment by dgutov** [comment]
Thank you.

Will you send a full PR with a fix too? I'm not sure how urgent this is.

**Comment by dgutov** [comment]
Actually, never mind. Looking into it.

FWIW, plain `ignore-errors` doesn't help because it leaves point at the position where `forward-sexp` was called.

**Comment by dgutov** [comment]
Please check it out.

There might be some cases where this will result in undesired behavior, but hopefully with minor downsides. Reports welcome, though.

**Comment by Ergus** [comment]
Thanks I will try them and report any issue.
