### ISSUE TITLE
Icons don't work with company-show-numbers set to 'left

### ISSUE THREAD

**Issue by leungbk** [company-mode/company-mode#1078]
When `company-show-numbers` is `left`, the numbers seem to clobber the icons set by `company-format-margin-function`. No such problem exists when `company-show-numbers` is some other non-nil value, in which case the icons are displayed on the left and the numbers are displayed on the right with no issue.

**Comment by dgutov** [comment]
Thanks for the report.

What would you suggest, behavior-wise? It seems like showing both the icon and the number on the left would look cramped, wouldn't it?

**Comment by leungbk** [comment]
I think it would be fine; even putting aside the fact that `company-format-margin-function` and `company-show-numbers` don't default to the cramped arrangement, I feel like it's not particularly difficult to read. The reason I personally set `company-show-numbers` to `left` is that I dislike having to move my eyes all the way across the spawned popup to determine which of `M-{1-9}` to hit. When `company-show-numbers` is set to `left`, having to visually hop over an icon is pretty easy in comparison.

**Comment by dgutov** [comment]
> I think it would be fine

If you're sure. Yes, as a default feature I'm not too worried about general ergonomics, but I hope you *will* end up using the result.

> When company-show-numbers is set to left, having to visually hop over an icon is pretty easy in comparison.

What order should they be in? First icon then number, or vice versa?

**Comment by leungbk** [comment]
> > When company-show-numbers is set to left, having to visually hop over an icon is pretty easy in comparison.
> 
> What order should they be in? First icon then number, or vice versa?

i personally like having the number before the icon, since this allows the icon and the candidate (both semantically-related entities) to be adjacent. Alternatively, there could be a `defcustom` that lets the user choose.

**Comment by dgutov** [comment]
This should do it. Hope you like the result.
