### ISSUE TITLE
Errors after recent updates

### ISSUE THREAD

**Issue by rprimus** [company-mode/company-mode#1079]
Mon Mar 29 13:00:27 BST 2021

![company-mode-error](https://user-images.githubusercontent.com/278414/112833552-6b96e280-9086-11eb-8202-61dda4579bcb.gif)

When attempting to `add-change-log-entry-other-window`,  the debugger is invoked multiple times (as seen above).

<details>
<summary>Setup:</summary>

### System Info:

- **OS**:
  - ProductName:	Mac OS X
  - ProductVersion:	10.15.7
  - BuildVersion:	19H524
- **Emacs**: GNU Emacs 27.2 (build 1, x86_64-apple-darwin19.6.0, Carbon Version
  162 AppKit 1894.6) of 2021-03-28
- **company-mode config**
```elisp
(use-package company
  :hook (after-init . global-company-mode)
  :bind
  (("M-C-/"   . company-complete)
   :map company-active-map
   ("C-d"     . company-show-doc-buffer)
   ("C-l"     . company-show-location)
   ("M-/"     . company-other-backend)
   ("C-n"     . company-select-next)
   ("C-p"     . company-select-previous))
  :init
  (setq company-idle-delay 0
        company-minimum-prefix-length 2
        company-show-numbers t
        company-tooltip-align-annotations t
        company-tooltip-limit 20
        company-tooltip-flip-when-above t)
  :config
  (use-package company-quickhelp
    :hook   (after-init . company-quickhelp-mode))
  (use-package company-dabbrev
    :straight company)
    (delq 'company-semantic company-backends))
```
<hr>
</details>

**Comment by dgutov** [comment]
Hi! What does `M-x company-version` say?

You might want to try upgrading to the next version again, but I haven't seen this exact problem.

If the problem is still there, please post the backtrace as text. I appreciate the gif, but that part is hard to read without being able to stop the animation.

**Comment by rprimus** [comment]
Mon Mar 29 13:37:25 BST 2021

> What does M-x company-version say?

Company version: 0.9.13

Am using straight and had updated to the latest commit 9c3fce68486481363bcf2c57c46a91b214248bb9 before the errors started.

> please post the backtrace as text

<details>
<summary>Backtraces</summary>

### Backtrace 1

```elisp
Debugger entered--Lisp error: (wrong-type-argument integerp " ")
  company--create-lines(0 20)
  company-pseudo-tooltip-show(3 27 0)
  company-pseudo-tooltip-show-at-point(73 2)
  company-pseudo-tooltip-frontend(post-command)
  company-pseudo-tooltip-unless-just-one-frontend(post-command)
  company-call-frontends(post-command)
  company-post-command()
  company-idle-begin(#<buffer ChangeLog> #<window 10 on ChangeLog> 127 73)
  apply(company-idle-begin (#<buffer ChangeLog> #<window 10 on ChangeLog> 127 73))
  timer-event-handler([t 24673 51944 81355 nil company-idle-begin (#<buffer ChangeLog> #<window 10 on ChangeLog> 127 73) nil 0])
  read-event(nil t 3)
  sit-for(3)
  flyspell-check-word-p()
  flyspell-post-command-hook()
```

### Backtrace 2 (continuation from Backtrace 1)

```elisp
Debugger entered--Lisp error: (error "Company: frontend company-pseudo-tooltip-unless-ju...")
  signal(error ("Company: frontend company-pseudo-tooltip-unless-ju..."))
  error("Company: frontend %s error \"%s\" on command %s" company-pseudo-tooltip-unless-just-one-frontend "Wrong type argument: integerp, \" \"" post-command)
  company-call-frontends(post-command)
  company-post-command()
  company-idle-begin(#<buffer ChangeLog> #<window 10 on ChangeLog> 127 73)
  apply(company-idle-begin (#<buffer ChangeLog> #<window 10 on ChangeLog> 127 73))
  timer-event-handler([t 24673 51944 81355 nil company-idle-begin (#<buffer ChangeLog> #<window 10 on ChangeLog> 127 73) nil 0])
  read-event(nil t 3)
  sit-for(3)
  flyspell-check-word-p()
  flyspell-post-command-hook()
```

<hr>
</details>

**Comment by dgutov** [comment]
Any chance you could add an Edebug breakpoint in `company--create-lines` (with `C-M-x`, unless you're using something like Evil), then trigger completion with `M-x company-complete-common` and step through the former function until the error is triggered?

If you could point at the exact line, that would help.

**Comment by rprimus** [comment]
Mon Mar 29 14:02:52 BST 2021

A git bisect produced the following:

```git
b798634b468248524cb51df5cf9287918da69fac is the first bad commit
commit b798634b468248524cb51df5cf9287918da69fac
Author: Dmitry Gutov <dgutov@yandex.ru>
Date:   Mon Mar 29 04:43:29 2021 +0300

    Don't create extra-wide margins when backend shows no kinds

 company.el | 59 ++++++++++++++++++++++++++++++++++++++---------------------
 1 file changed, 38 insertions(+), 21 deletions(-)
```

**Comment by dgutov** [comment]
Never mind with debugging, managed to reproduce it, thanks.

**Comment by rprimus** [comment]
Mon Mar 29 14:17:06 BST 2021

From edebug:

line: 2952
```elisp
(or (pop left-margins)
                              (company-space-string left-margin-size))
```

**Comment by rprimus** [comment]
Mon Mar 29 14:17:47 BST 2021

> Never mind with debugging, managed to reproduce it, thanks.

LOL.  At least I now have some `edebug` experience.  :-)

**Comment by dgutov** [comment]
Got it. It was a weird one: `left-margin` is also a global variable used by redisplay. Odd how this only affected some buffers.

> At least I now have some edebug experience. :-)

And that's always going to be useful ;-)
