### ISSUE TITLE
Annoying message, restore previous buffer

### ISSUE THREAD

**Issue by jcs090218** [company-mode/company-mode#1081]
I keep getting this message while using `company-mode`. Any idea? 😕 I think this is due to recent changes.

```
Type "q" in help window to restore its previous buffer.
```

**Comment by dgutov** [comment]
> I think this is due to recent changes.

Um, probably not? That's just how `elisp--company-doc-buffer` works. Improvements welcome, I guess.

**Comment by jcs090218** [comment]
Ah, okay. My bad.
