### ISSUE TITLE
Invalid image specification

### ISSUE THREAD

**Issue by jcs090218** [company-mode/company-mode#1082]
By setting variable `company-format-margin-function` to `#'company-vscode-dark-icons-margin`, I will get this error

```
Company: An error occurred in post-command
Company: frontend company-pseudo-tooltip-frontend error "Invalid image specification" on command post-command
```

**Comment by dgutov** [comment]
How do I reproduce? Seems to work fine here.

Does your Emacs support SVG?

**Comment by jcs090218** [comment]
I am actually confused with this issue. I encountered this error in these two circumstances.

1. Open Emacs in powershell (terminal)
2. My home machine doesn't show this error but my company's computer does, and both are on Windows

The first circumstance is simple, I would just have to set `company-format-margin-function` to `nil` when graphic does not support. And for the 2nd condition, I would need to further investigate... 😕

**Comment by dgutov** [comment]
Seems to be Windows-specific, then.

It would be good to file reports for every instance of inconsistent behavior between platforms.

If I try using this feature in the terminal, I get an error "Window system should be used", which is a lot easier to decipher.

Looking forward to the result of your investigation of 2.

**Comment by Aaronzinhoo** [comment]
@dgutov I checked to see if I have svg support using `(image-type-available-p 'svg)`. I am not able to get any icons to popup but I am not getting any errors. Is there anything else besides the one line to set it up?

```
(setq company-format-margin-function #'company-vscode-dark-icons-margin)
```

**Comment by dgutov** [comment]
@Aaronzinhoo Using `straight`, right? Check this out: https://github.com/company-mode/company-mode/issues/1087#issuecomment-811897057

**Comment by Aaronzinhoo** [comment]
I made the change to my company config. I also deleted the old package and rebuilt it but this is what is happening. It looks like the margins are not big enough to show the svg.


![image](https://user-images.githubusercontent.com/26849064/114220282-a4557800-9920-11eb-88c0-c9db92c6e9fa.png)

**Comment by dgutov** [comment]
@Aaronzinhoo What backend are you using there?

**Comment by dgutov** [comment]
Scratch buffer uses `elisp-completion-at-point`, which only supports icons with very recent Emacs.

`company-shell` is another third-party one, you might want to file a feature request with them as well.

`company-files` should show icons, however. You can try typing `"~/Doc` or etc.

In general, icons require every backend to indicate the "kind" of its every completion. For some backends this is going to be difficult, e.g. I'm still not sure how (and whether) to implement this feature for `company-etags`.

**Comment by Aaronzinhoo** [comment]
Ahhh Ok so that is on the upcoming v28 branch? I was trying to figure out which branch was necessary to use this. It makes sense why I dont have any icons now. Is there any backend that can use it now if I am not at a recent branch?

**Comment by dgutov** [comment]
> Ahhh Ok so that is on the upcoming v28 branch?

The branch is called `master`.

> Is there any backend that can use it now if I am not at a recent branch?

`company-dabbrev-code`, `company-dabbrev`, `company-files`, `company-yasnippet`, `company-ispell`, `company-keywords`.

`lsp-mode` also has support through `company-capf` already.

**Comment by Aaronzinhoo** [comment]
Sorry stupid question haha, I meant it would be something that would be eventually released in emacs 28? 

Ok sounds good, when I am home I will try with file that activates lsp-mode and see how it goes.

**Comment by dgutov** [comment]
You can also check if it's working at all with `M-x company-dabbrev-code`.

**Comment by Aaronzinhoo** [comment]
![image](https://user-images.githubusercontent.com/26849064/114230066-893d3500-992d-11eb-9389-204fba3f4c9e.png)


Does this about right? It seems like i need to use the light theme haha

**Comment by dgutov** [comment]
> Does this about right?

Err, I think so. Are the "dark icons" not contrasting with your background? :confused: 

You can try the light version indeed, but not necessarily of the theme: `(setq company-format-margin-function #'company-vscode-light-icons-margin)`.

**Comment by Aaronzinhoo** [comment]
Its all good, I was in light and switched to dark and it was fine. I think this just a theme issue I can solve though. The icons work in lsp mode buffers as well. Thanks

**Comment by jcs090218** [comment]
From the original issue, I don't see this error anymore from my company's machine.

@dgutov Thanks for the help! Close this issue now. :)
