### ISSUE TITLE
Weird tooltip behaviour with ESS

### ISSUE THREAD

**Issue by marbeno** [company-mode/company-mode#1084]
Hi,
I am running Aquamacs with Emacs 25.3.50.1.
After an update to
`Company version: 0.9.13`

The tooltip does not appear in all lines. Also, when it doesn't appear, a few lines below the cursor disappear.

https://user-images.githubusercontent.com/29627922/113123517-f4438900-9214-11eb-9681-9f9d60a6c2c5.mov

Below, output from `C-h m`

```
Enabled minor modes: Auto-Composition Auto-Compression Auto-Encryption
Blink-Cursor Column-Number Company Cua Delete-Selection Eldoc
Electric-Indent Electric-Pair Ess-Roxy File-Name-Shadow Folding
Font-Lock Global-Eldoc Global-Font-Lock Global-Linum Hi-Lock
Imenu-List Line-Number Linum Menu-Bar Mouse-Wheel Osx-Key
Rainbow-Delimiters Recentf Save-Place Savehist Shell-Dirtrack
Show-Paren Smart-Frame-Positioning Tabbar Tabbar-Mwheel Tooltip
Transient-Mark

(Information about these minor modes follows the major mode info.)

ESS[R] mode defined in ‘ess.el’:
```

**Comment by dgutov** [comment]
Hi!

This is new. Do you see any errors in `*Messages*` when this happens?

What if, at the position where the problem occurs, you `M-x company-complete-common`? Does the popup show up? Any errors?

**Comment by dgutov** [comment]
> Invalid face attribute :extend t [N times]

Hmm, that looks familiar. It's related to a 6-month old change, though.

Could you try applying this patch?

```diff
diff --git a/company.el b/company.el
index ac73a33..fe026cf 100644
--- a/company.el
+++ b/company.el
@@ -2864,8 +2864,8 @@ If SHOW-VERSION is non-nil, show the version in the echo area."
             new))
 
     ;; XXX: Also see branch 'more-precise-extend'.
-    (let* ((nl-face (list
-                     :extend t
+    (let* ((nl-face `(,@(when (version<= "27" emacs-version)
+                          '(:extend t))
                      :inverse-video nil
                      :background (or (company--face-attribute 'default :background)
                                      (face-attribute 'default :background nil t))))

```

**Comment by dgutov** [comment]
If it doesn't help (which is likely), could you produce a step-by-step scenario of how to reproduce a problem starting with `emacs -Q -L ~/.emacs.d/elpa/company-xyz -l company`?

I'm guessing this doesn't happen in just any buffer, right?

**Comment by marbeno** [comment]
Hi,
thanks for your reply

> Could you try applying this patch?

The message disappeared, but the behaviour is not changed

> If it doesn't help (which is likely), could you produce a step-by-step scenario of how to reproduce a problem starting with `emacs -Q -L ~/.emacs.d/elpa/company-xyz -l company`?

with `Aquamacs -Q -L Aquamacs/dir/stuff/elpa/company-20210330.1459 -l company`

The problem did not show up. I tried with an example.cpp I have (I never learned c++, btw), because I couldn't load ess in this way.

with `Aquamacs -L Aquamacs/dir/stuff/elpa/company-20210330.1459 -l company` and the same example.cpp the problem did show up again.

**Comment by dgutov** [comment]
Could you post than example.cpp?

**Comment by dgutov** [comment]
Oh! I see that the problem didn't occur with `-Q`.

Does it happen if you just load the ESS package with default config?

That would mean starting repro with something like `emacs -Q -L ~/.emacs.d/elpa/company-xyz -l company -L ~/.emacs.d/elpa/ess-xyz -l ess`.

Point is, I need a scenario I can reproduce myself locally, without loading your whole configuration. The smaller it is, the easier it will be to diagnose the problem.

**Comment by marbeno** [comment]
Hi,

I manage to get  reproducible examples.
Launched Aquamacs as:
``
Aquamacs -Q -L "~/Library/Preferences/Aquamacs Emacs/Packages/elpa/company-20210330.1459" -l company -l /Applications/Aquamacs.app/Contents/Resources/lisp/aquamacs/edit-modes/ess-mode/lisp/ess -l ess
``
Pasted in the scratch buffer the first 104 lines of code (skipping the first commented lines) of [company.el](https://github.com/company-mode/company-mode/blob/master/company.el) and I got this


https://user-images.githubusercontent.com/29627922/113200473-a193bc80-9268-11eb-993f-cc38a51faee4.mp4

I Uploaded the video because the behaviour changes from bottom-up.

I got the same after running 

```
Aquamacs -Q -L "~/Library/Preferences/Aquamacs Emacs/Packages/elpa/company-20210330.1459" -l company
```

If the buffer has 104 lines, the weird behaviour  starts from line 93 upwards, if the buffer has 105 lines it starts from the 94th line and so on. You can try by adding empty lines at the bottom of the buffer.

**Comment by dgutov** [comment]
> I got the same after running

Please clarify: does that mean I don't need to install ESS to reproduce the problem? Is the behavior the same as what you're showing on the video? Because I haven't been able to trigger it so far, neither when editing the real file (near its bottom or not), nor after copying its first 104 lines to scratch. Tried with Emacs 25.2 on GNU/Linux.

If it ends up something that's only reproducible with Aquamacs, could you try bisecting to find the commit that broke it? I'm guessing it could have been dff5856ed16a52d6ff00b70ba603a33dfdd3d55a, but it would help to know for sure.

**Comment by marbeno** [comment]
Hi,

I did a few attempts by deleting company and re-installing it from this repo release page.  I did it with three releases (0.9.10, 0.9.12, and 0.9.13) and all of them work. 
When I did the same thing with the melpa `company-20210331.1619.tar`, it did not work.
Every time I deleted the package before installing a different version. I installed them with:

```
M-x package-install-file
```

**Comment by dgutov** [comment]
> I did it with three releases (0.9.10, 0.9.12, and 0.9.13) and all of them work.
When I did the same thing with the melpa company-20210331.1619.tar, it did not work

Thanks! Can you bisect by Git commits, though?

For instance, do it like this:

* Clone this repo, visit `company.el` from the checkout. See the file history with `C-x v l`.
* Check out a particular revision of that file with `C-x v ~`, then call `eval-buffer` in there.

The classic bisect scenario uses binary search, but in this case I would test first whether dff5856ed16a52d6ff0 is "broken", and whether 915b79ad1cc3292c5f648e339 (the version right before it) doesn't have this problem.

**Comment by marbeno** [comment]
Hi,

> > I did it with three releases (0.9.10, 0.9.12, and 0.9.13) and all of them work.
> > When I did the same thing with the melpa company-20210331.1619.tar, it did not work

It worked for a while, then the problem reappeared.

> * Clone this repo, visit `company.el` from the checkout. See the file history with `C-x v l`.
> * Check out a particular revision of that file with `C-x v ~`, then call `M-x eval-buffer` in the opened buffer.
> 
> The classic bisect scenario uses binary search, but in this case I would start with testing whether [dff5856](https://github.com/company-mode/company-mode/commit/dff5856ed16a52d6ff00b70ba603a33dfdd3d55a) is "broken", and whether [915b79a](https://github.com/company-mode/company-mode/commit/915b79ad1cc3292c5f648e33971f45501db62ba5) (the version right before it) doesn't have this problem.

This is what I did
- deleted company with `package-delete RET company0.9.13`
- Cloned repo
- Visited `company.el` and `C-x v l`
- Selected a particular commit in vc-change-log buffer
- `f` to visit the revision
- `eval-buffer` in `company.el.~particularversioncode~`
- Tried to use company in an R script

I found that commit 5eb7d868c2a13bbfb14060b79d69f0d59f6a5f60 worked, while commit e1d58370cf1f6b42b929376eab2193bfc0914381 did not work.

**Comment by dgutov** [comment]
> It worked for a while, then the problem reappeared.

So... it occurs sporadically? That's unfortunate.

> I found that commit 5eb7d86 worked, while commit e1d5837 did not work.

Thank you. Please clarify: if the commit e1d5837 is broken, does that mean that you haven't updated to the latest MELPA version for more than half a year? Or only started using Emacs/company-mode recently?

**Comment by marbeno** [comment]
> Thank you. Please clarify: if the commit [e1d5837](https://github.com/company-mode/company-mode/commit/e1d58370cf1f6b42b929376eab2193bfc0914381) is broken, does that mean that you haven't updated to the latest MELPA version for more than half a year? Or only started using Emacs/company-mode recently?

I haven't updated it for a while. I do not update melpa packages very often.

**Comment by dgutov** [comment]
All right, that makes sense.

Unfortunately, the commit you pointed to created a sort of fundamental change: a switch to always using the `after-string` overlay property for rendering the popup. Which was necessary to add the rendering of icons.

I don't have a machine at hand that is capable of running Aquamacs. Perhaps if you could manage to reproduce this problem in "plain" Emacs, we could move forward.

Alternatively, we'd need to produce some example using `after-string` for a similar purpose that doesn't work in your editor (but works in "normal" Emacs), and then send it to the maintainer. Wish I could tag them in this discussion, but I don't know who it is, or if they have an account on GH.

**Comment by dgutov** [comment]
Also: if you have a solid repro scenario that works on Emacs but fails in Aquamacs, you could report it as-is, even if it requires the reproducer to install company-mode.

We do such reports in GNU Emacs development all the time.

**Comment by dgutov** [comment]
802838bce34 switched to use the `before-string` property again.

Here's hoping it fixed this one too.
