### ISSUE TITLE
Completion popup randomly reset

### ISSUE THREAD

**Issue by rrudakov** [company-mode/company-mode#1086]
Hello. 

After recent updates I've started facing the following issue:
Sometimes when completion candidates popup is visible and I already selected some item it just disappears (like if I press `C-g`, but I didn't press anything). I couldn't find 100% way to reproduce this issue, `toggle-debug-on-error` won't show anything when it happens.

How does it looks like:

https://user-images.githubusercontent.com/6093590/113273717-37692f00-92dd-11eb-9459-29dc98a05670.mp4

### My configuration:
```emacs-lisp
(use-package company
  :config
  (setq company-global-modes '(not org-mode markdown-mode shell-mode))
  (setq company-tooltip-align-annotations t
        company-idle-delay .2
        company-minimum-prefix-length 3)

  (global-company-mode)
  (company-tng-mode))
```
This problem appears at least in `CIDER`, `lsp-mode` and `emacs-lisp-mode`.

### Emacs version:
`GNU Emacs 27.2.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.20, cairo version 1.16.0) of 2021-03-28`

I think I need some instructions how to debug this problem to provide some more details. Thank you!

**Comment by dgutov** [comment]
Hi! This sounds suspiciously similar to #1084.

If you can, create a step-by-step reproduction scenario starting with `emacs -Q`. If that's too difficult, please try the bisecting instructions I just wrote there. This way we can find the offending commit and, from there, the exact line.

**Comment by dgutov** [comment]
Please also try to keep debugging to `emacs-lisp-mode`: that would exclude any problems with external packages and servers.

**Comment by rrudakov** [comment]
After a few days of debugging I figured out that my problem was related to `company-quickhelp` package. When I disable it everything works fine.

**Comment by dgutov** [comment]
Interesting.

What pointed you that way? Did you see any related errors in the echo area or `*Messages*`? Or did the problem simply occur with the same delay that the doc popup shows after?

**Comment by rrudakov** [comment]
Initially I've tried to reproduce it with `emacs -Q -L ~/.emacs.d/elpa/company-xyz -l company`. Then I disabled all company related packages in my config and enable them one by one.

No errors in echo area or `*Messages*` buffer. 

> Or did the problem simply occur with the same delay that the doc popup shows after?

yes, looks like the same delay.

**Comment by JekoTronik** [comment]
Same here ! 

Anytime I press the Meta key to navigate through candidate list, the list disappears.

```emacs-lisp
(use-package company
  :ensure t
  :config
  (setq company-idle-delay 0)
  (setq company-minimum-prefix-length 2)
  (global-company-mode t))

(use-package company-quickhelp
  :config
  (progn
    (company-quickhelp-mode 1)
    (setq company-quickhelp-delay nil)))
```

**Comment by JekoTronik** [comment]
Using Control key instead of Meta key fix the issue.

```emacs-lisp
(use-package company
  :ensure t
  :diminish company-mode
  :defines
  (company-dabbrev-ignore-case company-dabbrev-downcase)
  :bind
  (:map company-active-map
	("C-n" . company-select-next)
	("C-p" . company-select-previous)
	("<tab>" . company-complete-common-or-cycle)
	:map company-search-map
	("C-p" . company-select-previous)
	("C-n" . company-select-next))
  :custom
  (company-idle-delay 0)
  (company-echo-delay 0)
  (company-minimum-prefix-length 1)
  :config
  (global-company-mode t))
```

**Comment by dgutov** [comment]
@JekoTronik Interesting. Could it be related to your OS, window manager or some external program that does key translation?

**Comment by JekoTronik** [comment]
It might be related ! I'm running Ubuntu and I think the Meta key is bound to several things unfortunately (like displaying Unity HUD, or toogle menu bar, …). 
But I don't know how to disable all of it.

**Comment by dgutov** [comment]
@JekoTronik Unity indeed makes use of Alt, but I never noticed it have any effect on key sequences in applications (last tried it a couple of years ago; now I'm on GNOME + Unite).

@rrudakov It's a very long short, but any chance the same change in key bindings makes the problem go away too?

I've been thinking to change the default bindings for a while, because it seems everybody customizes them to use `C-n`/`C-p` anyway.

**Comment by rrudakov** [comment]
Hi @dgutov. No, unfortunately changing keybindings doesn't solve my problem. 

I'm 100% sure that `company-quickhelp` package is cause of my issue, probably I should open a bug in `company-quickhelp` repo.

**Comment by dgutov** [comment]
It will be a good thing to do, to continue the more specialized discussion. It's in the same org, though, so it'll still be us talking.

When you file it, some more investigation would be helpful if you have the time. In particular, does `company-posframe` exhibit the same problem? It also has a "documentation popup" feature implemented using posframe. `company-box` has one as well.

Another (more time-consuming) route it print-debugging: add lots of `(message ...)` calls to `company-quickhelp` and, when it fails, trace the execution.
