### ISSUE TITLE
Icons display as black squares when using straight.el (with fix!)

### ISSUE THREAD

**Issue by thomasheartman** [company-mode/company-mode#1087]
Hi, 

I ran into an issue when trying out the new icons feature, but it seems to have been because of how straight.el works and I think I have found out how to fix it. However, I wanted to report it here in case anyone else runs into the same issue. I'm also not entirely sure that this is the _right_ way, so I'm open to any suggestions.

Anyway, the problem was that icons weren't displaying. Instead, all I got was black squares, as in this screenshot:

![company dropdown with black squares in front of completions](https://user-images.githubusercontent.com/17786332/113293411-02b5a180-92f6-11eb-8ca2-49d0c837670b.png)

The reason for this seems to have been that straight _builds_ packages and creates symlinks in a build directory. The files it chooses depends on a `:file` argument that you can pass to it. The default value covers most use cases, but didn't include the `icons` directory. To work around it I added `icons` to the default list, this seems to fix the issue.

```emacs-lisp
(use-package company
  :straight `(:files ,(cons "icons" straight-default-files-directive)))
```

I'm not entirely sure what the right way to work with this is, so I'll also report this to straight.el and see what they say there.

Emacs version: GNU Emacs 28.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.24, cairo version 1.16.0)
Company version: 0.9.13

**Comment by dgutov** [comment]
Hi!

This came up before: https://github.com/company-mode/company-mode/issues/756#issuecomment-810563388

So IIUC the recipe is better written as

```el
(use-package company
  :straight (company :files (:defaults "icons")))
```

(It's really unfortunate that we can't fix this kind of problem for all users at once, like we did with the MELPA recipe.)

**Comment by thomasheartman** [comment]
Ah, right! I did look for other issues like this, but I think I checked that thread before that was posted. Thanks for letting me know! And yeah, you're probably right that that's a better way to write the recipe. 

In that case, it probably _is_ the right way to use straight, then. And yeah, it's unfortunate if there is no way to fix this for more users at once. Anyway, I'll probably still open the issue there just to get some clarification and to flag it. I feel like company-mode is used widely enough that it's at least worth logging for them too (and I couldn't find anyone else asking about the same issue).

**Comment by dgutov** [comment]
Sounds good.

Maybe they'll consider altering defaults based on that. And/or create some guideline for naming assets directories, so they are picked up by the default config.

**Comment by thomasheartman** [comment]
As mentioned in the [straight issue I created](https://github.com/raxod502/straight.el/issues/731), there is actually a fix for this. It's the user updating their Melpa recipe:

`M-x straight-pull-package melpa` should update your Melpa recipe, and the new recipe should include the `icons` directory (unless you've overridden the recipe in some other way). You can check that it includes the `icons` directory now by running `M-x straight-get-recipe company`. It should give you something like the following:
```
(company :type git :flavor melpa :files (:defaults "icons" "company-pkg.el") :host github :repo "company-mode/company-mode")
```

It seems that straight is smart enough to use recipes from the various package repositories and to update them automatically. As such, this issue shouldn't be encountered as long as the user updates their Melpa repository.

I'll close this issue now because it seems to be down to user error and we have both a manual override and the 'correct' fix listed. Thanks for your help!

**Comment by dgutov** [comment]
Thanks for the investigation. Should be helpful for whoever comes next with the same problem. :+1:
