### ISSUE TITLE
Company-pseudo-tooltip-if-one-frontend error

### ISSUE THREAD

**Issue by Aaronzinhoo** [company-mode/company-mode#1089]
Eamcs 27.1: I did nothing but recently update to the master branch. When I tried to edit my `init.el` after updating company, I started to receive this error:

```
An error occured in post command
Company: fontend company-pseudo-tooltip-unless-just-one-frontend error "Wrong type argument: sequencep, 1" on command post-command
```

As for the trace... I can only get an image for now since wsl copy/paste is acting weird

![image](https://user-images.githubusercontent.com/26849064/114148020-308a7f80-98ce-11eb-8027-f0eca17405c3.png)

This is my config, it is ugly and can be fixed up a lot I know lol but bear with me. 

```
(use-package company
  :straight (:type git :host github :repo "company-mode/company-mode" :branch "master")
  :diminish company-mode
  :bind
  ([remap indent-for-tab-command] . company-indent-or-complete-common)
  (:map company-active-map
        ("<tab>" . company-complete-common-or-cycle)
        ("<backtab>" . company-select-previous))
  :init
  (defun company-preview-if-not-tng-frontend (command)
    "`company-preview-frontend', but not when tng is active."
    (unless (and (eq command 'post-command)
                 company-selection-changed
                 (memq 'company-tng-frontend company-frontends))
      (company-preview-frontend command)))
  (setq company-idle-delay 0.1
        company-echo-delay 0 ;; remove annoying blinking
        company-tooltip-flip-when-above t
        company-tooltip-limit 15
        company-require-match nil
        company-dabbrev-ignore-case nil
        company-dabbrev-downcase nil
        company-show-numbers nil
        company-minimum-prefix-length 1
        company-selection-wrap-around t
        company-tooltip-align-annotations t
        company-transformers '(company-sort-by-backend-importance
                               company-sort-prefer-same-case-prefix
                               company-sort-by-occurrence))
  (setq company-auto-complete #'my-company-visible-and-explicit-action-p)
  (setq company-frontends
        '(company-preview-if-not-tng-frontend
          company-pseudo-tooltip-unless-just-one-frontend
          company-preview-if-just-one-frontend
          company-echo-metadata-frontend))
  :config
  (global-company-mode t))
```

If you need any other information let me know. I already seen 2 others with this issue and it was solved by updating so I am not sure if this is new. I made sure to delete the repos (I use straight) and pull them again when updating the package.

**Comment by dgutov** [comment]
Hi!

You also need to update `company-posframe` to the latest version, it had a compatibility fix corresponding to the latest changes.

**Comment by Aaronzinhoo** [comment]
@dgutov should it be already in master ? I am still experiencing the issue when updating `company-posframe`. It seems like they have a new branch `refposhandler` that was pushed to recently [here](https://github.com/tumashu/company-posframe/commits/refposhandler). Regardless though, either branch output this error

```
Company: fontend company-pseudo-tooltip-unless-just-one-frontend error "Wrong type argument: number-or-marker-p, nil" on command post-command
```

![image](https://user-images.githubusercontent.com/26849064/114209997-1d9a9e00-9914-11eb-9674-b55f399d4f6b.png)

It is definitely closer to the solution though which is nice!

**Comment by dgutov** [comment]
Try updating `posframe` as well.

**Comment by Aaronzinhoo** [comment]
Sounds good. I will move the discussion to posframe as well since this seems like an error on that side. Do not want to bother you with this when it is not even company's fault lol

**Comment by Aaronzinhoo** [comment]
Solved the problem , thanks @dgutov
