### ISSUE TITLE
Getting errors related to pysmell and unable to install pysmell... how can I remove pysmell?

### ISSUE THREAD

**Issue by andreimoment** [company-mode/company-mode#1090]
After installing company-mode and starting it, I am getting errors related to pysmell.

```
Error running timer 'company-idle-begin': (file missing "Cannot open load file" "No such file or directory" "pysmell")
```

I tried installing pysmell but was not able to.  I don't need it for my clojure development.

How can I remove pysmell from company-mode?

**Comment by dgutov** [comment]
Which version of `company-mode`, and where did you install it from?

`company-pysmell` was removed several years ago: https://github.com/company-mode/company-mode/blob/master/NEWS.md#2016-06-23-090

**Comment by andreimoment** [comment]
Update: the package-install company was installing v. 0.5 on my MacOS Catalina.
