### ISSUE TITLE
Tooltip hides target of completion and moves cursor when point is close to the bottom of the buffer

### ISSUE THREAD

**Issue by mattblackwell** [company-mode/company-mode#1094]
I am having an issue where the company tooltip often covers the word being completed and will sometimes move the cursor to a different location in the buffer. This usually happens when the cursor is close to the bottom of the buffer so that the tooltip moved above the completion point. Sometimes I can continue to type through the completion, but other times it then moves my cursor to the next line. It has been happening for a long time, so I do not think it's a recent update. As you might imagine, this is fairly frustrating. Here is a gif of what is happening. 

![company-glitch](https://user-images.githubusercontent.com/201554/115167414-835df700-a085-11eb-93e5-9fe808d38b3e.gif)

I've been able to recreate this problem using the following steps. On my Mac, I launched Emacs using the following command `/Applications/Emacs.app/Contents/MacOS/Emacs -Q -L ~/.emacs.d/elpa/company-20210405.2354 -l company`.  Then I open a file (no file extension, just the Fundamental major mode) with a bunch of text (see below for my file), run `M-x company-mode` scroll with my mouse to the bottom of the file so that there is roughly half a line between the point and the bottom of the cursor. Then I start typing the first tooltip moves the cursor. From some experimentation, it appears that the problem doesn't happen if (a) the distance between the point and the bottom of the buffer is big enough to handle the tooltip below the point or (b) the cursor is *exactly* flush with the bottom of the buffer. 

Perhaps relatedly, perhaps not: when I scroll with my mouse when the tooltip is visible, there is a lot of flickering and quick movement of the cursor. 

Version information: GNU Emacs 27.1, company-20210405.2354

File used (`test`):
```
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus id
arcu dapibus, ultricies ligula ut, imperdiet nunc. Nam mauris eros,
volutpat in tristique non, bibendum non leo. Proin eget ullamcorper
dui. Sed suscipit ultricies erat, sed convallis eros condimentum
ut. Nullam ultrices quis tellus a tristique. Phasellus elementum lacus
urna, eu imperdiet sem pellentesque in. Suspendisse potenti. Cras
viverra ullamcorper sollicitudin.

Sed viverra, ante ut tristique gravida, diam ipsum facilisis ipsum, a
varius arcu turpis eget ante. Etiam tincidunt consectetur purus. Cras
a tempor neque. Integer facilisis condimentum mauris varius
lobortis. Sed a dolor mollis, semper libero quis, molestie
magna. Aenean vitae molestie urna. Proin eleifend, nibh at blandit
condimentum, justo nibh volutpat libero, vitae varius velit velit nec
libero. In porttitor sagittis nisi, in gravida nunc aliquam
tincidunt. Vestibulum elit dolor, ornare ut tellus ac, tempor pharetra
magna. Sed eu urna tellus. Aenean sit amet enim posuere, malesuada leo
vel, scelerisque nulla. Nam posuere tempus lorem.

Mauris pulvinar fermentum cursus. Donec nec volutpat dui. Nam non
vestibulum quam, sed elementum sapien. Ut quis lorem quis nulla tempor
tristique eget eget justo. Vestibulum pretium ex maximus lorem
fermentum, sed efficitur velit posuere. Donec elit tortor, porttitor
id semper vel, rhoncus ut eros. Etiam eget elit eu orci efficitur
viverra. Donec consectetur posuere turpis, in rhoncus nibh. Maecenas
elementum blandit dapibus. In hac habitasse platea dictumst. Quisque
iaculis libero velit, vitae sodales neque dictum sit amet.
```

**Comment by dgutov** [comment]
Hi! I'm having trouble reproducing this, unfortunately.

First of all, how do you get the line after point to be half-width? To have a window whose height is not a multiple of the line height, you need to change `window-resize-pixelwise`, and that's not an `emacs -Q` configuration. But even if I do that (with two split windows, because the frame itself really doesn't want to resize to resize that way), I can't reproduce. Nor have I see this in practice.

I'm using a GTK3 GNU/Linux build, though. And there's no good way for me to try this on a Mac.

If others have seen this before, welcome to chime in.

**Comment by mattblackwell** [comment]
Thanks for checking. To clarify, I don't do anything to change the window height. I simply scroll with the mouse so that only half a line is visible below the point. Perhaps one piece of relevant info is that I am using the [Yamamoto Emac Mac port](https://bitbucket.org/mituharu/emacs-mac/src/master/), which has the following feature:
```
In addition to the standard Emacs 27 features, the Mac port includes
the following Mac-specific ones:

  * Pixel-based mouse wheel smooth scroll for newer mice/trackpads.
```

Perhaps this explains why I can scroll to keep a half-line visible with `emacs -Q`. Might also explain the flickering with scrolling.

**Comment by dgutov** [comment]
That must be it.

Not sure what to do about it, though: I can't reproduce it on my system (with Emacs 27.1 as well), so the bug is likely triggered by your port's implementation detail of that feature.

**Comment by dgutov** [comment]
If nothing helps, try installing one of the alternative frontends. `company-posframe`, for example.

**Comment by mattblackwell** [comment]
Thanks for the help. I actually think I managed to track down what the problem is. Here is the relevant code:

https://github.com/company-mode/company-mode/blob/4286972775832e29434becc6c72e767319139a1c/company.el#L3159-L3169

The issue arises because `(posn-actual-col-row)` and `(move-to-window-line)` handle fractional visible lines differently. The former, which defines the value that is passed to `company-pseudo-tooltip-show` as `row` indexes the half-visible line at the top of the visible window as 0, but `(move-to-window-line)` indexes it from the first fully visible line. You can recreate this problem with a window with a partially visible top line by `M-:` and then running:
```
(move-to-window-line (cdr (posn-actual-col-row (posn-at-point))))
```

This will move you to the next line. 

In any case, this will cause the overlay of the pseudo tooltip to be shifted down one row to what is intended. I'm a novice, so I'm not sure how to resolve this or if it's even possible, but I thought I would update with that info.

**Comment by mattblackwell** [comment]
Ok so I just tested adding the following above those lines and it seems to resolve the issue:
```{lisp}
      (save-excursion
        (when
            (> (move-to-window-line row) row)
          (setq row (+ row -1))))
```

Basically, this tests to see if the above issue is happening and adjusts the starting row of the pseudo tooltip accordingly.

**Comment by dgutov** [comment]
> You can recreate this problem with a window with a partially visible top line

That's it. Apparently only Mac Port can create this situation (so far), and this is what I haven't been able to reproduce.

But since `move-to-window-line` behaves this way no matter the where point is (only the scrolling position affects it, right?), shouldn't the bug reproduce not only at the bottom of the window?

As far as fixes go, perhaps number one would to try reporting this discrepancy to Yamamoto. Perhaps the correct fix is to resolve the off-by-one in `move-to-window-line` or in `posn-at-point`.

Calling `move-to-window-line` an extra time just the test for the problem is not ideal, since this function is not free. Is there another test to see whether the first line of the buffer is only half-visible? What does `(window-start)` return, for example?

**Comment by mattblackwell** [comment]
You are right that it looks like you can use `(window-start)`, which gives the position at the beginning of the window, whether or not it is fully visible. Nicely, the function `(pos-visible-in-window-p)` can be used to whether a position is fully (or partially) visible. 

So, this code seems to accomplish the same task as my last snippet:
```
      (when (not (pos-visible-in-window-p (window-start)))
        (setq row (+ row -1)))
```

**Comment by dgutov** [comment]
Very good (`pos-visible-in-window-p` is pretty fast).

Does it give you the desired behavior on every line, though? This code would change it everywhere (as long as the first line is half-scrolled), whereas you said the problem only reproduces when the point is at the last line?

Or are there some display problems around the popup no matter the current line?

**Comment by mattblackwell** [comment]
I think the problem would arise anytime the overlay needed to be drawn above the point because there wasn't enough room below. So it would definitely happen with one line below but could be more depending on the size of the overlay. With these changes, I haven't seen any cursor movement or overlays covering the point. I'm also not seeing any side effects like the overlay being in the wrong place when drawn below the point (when there is enough room). I'm very much a lisp novice/tinkerer, though, so I'm not 100% sure about that. 

I also sent a note to Yamamoto's bug list to see if they were interested in fixing (move-to-window-line) in the port. I suppose it needs a fix in one place or the other.

**Comment by dgutov** [comment]
OK. Please try running with this exact patch for a few days:

```diff
diff --git a/company.el b/company.el
index d9d744d..814f1f7 100644
--- a/company.el
+++ b/company.el
@@ -3156,6 +3156,9 @@ Returns a negative number if the tooltip should be displayed above point."
         (setq row (+ row height -1)
               above t))
 
+      (unless (pos-visible-in-window-p (window-start))
+        (cl-decf row))
+
       (let (nl beg end ov args)
         (save-excursion
           (setq nl (< (move-to-window-line row) row)
```

And as far as investigations go, not too bad for a "lisp novice". :wink:

**Comment by mattblackwell** [comment]
Added this patch and everything seems to be running fine with no problems so far. Thanks!

**Comment by dgutov** [comment]
No further problems reported, so I pushed the fix.

Thanks for the report and the help. :+1:

**Comment by mattblackwell** [comment]
Awesome, thanks!

**Comment by dgutov** [comment]
@NightMachinary So it sometimes happens for you, and sometimes does not, even when the window contents are the same? When the first visible line of the buffer is the same?

And you are using Yamamoto's Mac Port?

This kind of nondeterminism could signify a bug in the port itself. But without a more-or-less reliable reproducer it's hard to say.

But looking at the screenshot, it seems like you might be seeing a different bug. The point doesn't jump anywhere, does it? And the window doesn't scroll?

If the only problem you see is the broken rendering of the popup, it's a different bug. One I'd of course be happy to fix, though.

**Comment by dgutov** [comment]
If you can repro it reliably, try disabling some modes, one by one (and note which one stops the problem from happening).

For example, the indentation guides (not sure what's the mode called), and `display-line-numbers-mode`.

Also, it that terminal Emacs?
