### ISSUE TITLE
Snippets being expanded in TNG mode after completion

### ISSUE THREAD

**Issue by sangaline** [company-mode/company-mode#1097]
I'm using `python-mode` with `lsp-mode`, and trying to get TNG completion working with variables in the code. My `company-backends` variable is set to `(company-capf)`. If I start typing

```python
from math import sq
```

and then press tab, it will correctly autocomplete to:

```python
from math import sqrt
```

As soon as a do anything else, such as typing `,` or pressing enter to add another import, it will add `($0)` after the import name

```python
from math import sqrt($0)
```

and will produce this message:

```
company-call-backend-raw: Company: backend company-capf error "[yas] ‘yas-expand-snippet’ needs properly setup ‘yas-minor-mode’" with args (post-completion sqrt)
```

If I completely uninstall yasnippet, then `()` will be inserted instead of `($0)`. I would like to disable snippet insertion entirely, and it's syntactically incorrect for them to be inserted here anyway.

I'm having trouble figuring out how or why company-capf is trying to expand snippets here. I gather that it probably connects to #891 and #946. Perhaps there is another variable analogous to `company-semantic-insert-arguments` or `lsp-enable-snippet` that needs to be set to `nil` in `company-tng-configure-default`?

**Comment by dgutov** [comment]
Is `lsp-enable-snippet` really `nil` in your session? You can double-check using `M-:`.

What version of company-mode are you using? In the most recent one you should see a warning that `company-tng-configure-default` is an obsolete alias for `company-tng-mode`.

**Comment by sangaline** [comment]
All of `lsp-enable-snippet`, `company-require-match`, `company-clang-insert-arguments`, `company-semantic-insert-arguments`, and `company-rtags-insert-arguments` are `nil` in the session.

I'm using 7207cb14 from 29 days ago. I mentioned the obsolete function name accidentally because I was looking at the diff from #946.

**Comment by dgutov** [comment]
Please file a report against `lsp-mode`, then.

This should be a sufficient condition for having snippets disabled.

You can also double-check that lsp-mode's completion backend is used with `M-x company-diag`.

**Comment by sangaline** [comment]
You're correct, this does appear to be an `lsp-mode` issue. I talked to them on Discord, and apparently it's common for the Microsoft language servers to only work in the mode that vscode requires, so many of those won't respect the `lsp-enable-snippet` setting.

**Comment by dgutov** [comment]
But you said if you uninstall `yasnippet` entirely, it behaves correctly? For all completions from that server?

If so, it sounds like a workaround on `lsp-mode`'s side could be implemented. Probably not worth it only for the (deprecated) mspls, though.

**Comment by sangaline** [comment]
If I uninstall `yasnippet` it still inserts `()`, just without the `$0` in the middle. I think that's just because company-capf doesn't try to call `yas-expand-snippet` if it isn't installed.

I've since tried with pyls and lsp-jedi, and both of those have issues as well. They don't insert the parentheses after imports, but they do when autocompleting functions elsewhere. I get things like `sqrt($0)` and `randint(${1:a}, ${2:b})$0`. The `randint()` one is interesting because it almost seems like there are two sources of snippets or some conflict.

**Comment by dgutov** [comment]
> I've since tried with pyls and lsp-jedi, and both of those have issues as well.

I recommend opening an issue in lsp-mode after all. If those servers do misbehave as well, the report could be escalated to their bug trackers. Or perhaps it's some misconfiguration on your machine.

Also make sure to have `lsp-enable-snippet` to nil before the server is launched: client reports its capabilities at the very beginning, so a later change might have no effect.
