### ISSUE TITLE
How to disable icons?

### ISSUE THREAD

**Issue by andreyorst** [company-mode/company-mode#1102]
Adding icons resulted in misalignment of the company popup wit the text above it, when typing at the beginning of the line:

![image](https://user-images.githubusercontent.com/19470159/118356912-0ccaf100-b580-11eb-8590-81b6d0094f2b.png)

As opposed to when there's enough space before the window margin to align the popup:

![image](https://user-images.githubusercontent.com/19470159/118356767-7a2a5200-b57f-11eb-82d4-a0f6ba80e2d2.png)

But I don't see any option to disable icons, which I never found useful anyway. Setting `company-text-icons-mapping` to empty list does nothing. Setting `company-text-icons-format` to empty string also does nothing.

**Comment by dgutov** [comment]
To disable icons:

```el
(setq company-format-margin-function nil)
```

Regarding misalignment, there was a small discussion in https://github.com/company-mode/company-mode/issues/756#issuecomment-809021119, and the consensus was misalignment is less jarring than the icon sometimes being there and sometimes not. But I can see how there can be other opinions.

About what I see on the screenshot, though:

* Can the `(Variable)` part be disabled? With it displayed, of course, the icon just duplicates information.
* `load` is a variable? Really?

**Comment by andreyorst** [comment]
> ```emacs-lisp
> (setq company-format-margin-function nil)
> ```

Thanks. Would it make sense to make it into custom variable? Something like `company-use-icons`, which can be either `text`, `svg`, or `nil`?

> * Can the `(Variable)` part be disabled? With it displayed, of course, the icon just duplicates information.
> * `load` is a variable? Really?

That comes from the Clojure-LSP, not sure why they mark it as a variable, again, never found this info useful. CIDER marks it as a function, but there's no icons from CIDER:

![image](https://user-images.githubusercontent.com/19470159/118358573-1b1d0b00-b588-11eb-9145-f31790bf8ae4.png)

As for disabling, I think yes, if the icon display exactly the same info, some space can be saved

**Comment by manuel-uberti** [comment]
> CIDER marks it as a function, but there's no icons from CIDER

I wonder why this happens. The icons looks great in ELisp, though, so thanks @dgutov for the great work.

**Comment by andreyorst** [comment]
>     * `load` is a variable? Really?

That's the clojure-lsp bug, not a company problem: https://github.com/clojure-lsp/clojure-lsp/issues/426

**Comment by dgutov** [comment]
@manuel-uberti Cheers!

@andreyorst You can also remove the `(Variable)` annotation from lsp-mode completions, with `(setq lsp-completion-show-kind nil)`. Personally I think the icons are the better choice among these two.

Maybe kind annotations are generally less useful in Clojure (or other Lisp-1 languages), though.

**Comment by dgutov** [comment]
@manuel-uberti And if you were asking why CIDER's completions don't have icons, there is a missing piece that CIDER needs to implement. That applies to any backend, basically.

**Comment by andreyorst** [comment]
> Personally I think the icons are the better choice among these two.
> Maybe kind annotations are generally less useful in Clojure (or other Lisp-1 languages), though.

I guess it's just me, because I always look in the docs when I'm using something new, because annotation conveys very little info. And for things that I already know, I don't need docs and annotations. Icons are aesthetically better for some people, I just find those a bit distracting, as I need to memorize what they mean, even when I don't use those, that's just how my brain works :D

> there is a missing piece that CIDER needs to implement. That applies to any backend, basically.

Should I submit a ticket there?

**Comment by dgutov** [comment]
> Icons are aesthetically better for some people, I just find those a bit distracting, as I need to memorize what they mean, even when I don't use those, that's just how my brain works :D

They do indeed require some learning at first, but after that you get used to them very quickly IME, and tune them out when you don't need them.

> Should I submit a ticket there?

If it's not too much trouble. Thank you.

**Comment by andreyorst** [comment]
I think this can be closed now, as the main question was answered. Thanks everyone for the help!
