### ISSUE TITLE
Hope company candidate icon can support macOS Emacs.app

### ISSUE THREAD

**Issue by stardiviner** [company-mode/company-mode#1107]
I found company-mode icons does not work in macOS [Emacs.app](https://emacsforosx.com/). Because `svg` image format does not supported in this version. I'm using the latest version:
```
GNU Emacs 27.2 (build 1, arm-apple-darwin20.3.0, NS appkit-2022.30 Version 11.2.3 (Build 20D91)) of 2021-03-28
```

Hope company-mode can add another image type support like svg? Does it have image size problem if use png format instead of svg?

**Comment by dgutov** [comment]
Hi!

I don't really want to maintain support for multiple formats, or have both of them in the package for everybody to install. They also look worse: if you examine the screenshots for `company-box`, you'll see that the icons were made for specific backgrounds, and if your background is different, they have a weird-looking silhouette. Maybe Emacs doesn't handle PNG transparency well? Not sure.



Why don't you just ask the maintainer of Emacs.app to make their builds with librsvg enabled?

Alternatively, if you're fine with PNG's drawbacks, you can either ask `company-box` to migrate to the new `kind` support in backends, or create your own `company-format-margin-function`. Code-wise, you'll just need to copy the definition of the SVG one, chang `svg` to `png` and remove the scaling logic. And:

> Does it have image size problem if use png format instead of svg?

PNG icons scaled 2x would look much worse than SVG ones, of course.

**Comment by stardiviner** [comment]
I see，you're right. I will ask emacs.app maintainer to build with libsvg. Thanks for answering.
