### ISSUE TITLE
notmuch autoload issue.

### ISSUE THREAD

**Issue by Ergus** [company-mode/company-mode#1109]
Hi:

Trying to the notmuch backend I got an error.
```
Company: backend notmuch-company error "Symbol’s value as variable is void: notmuch-address-completion-headers-regexp" with args (prefix)
```

This seems to be related with the fact that `notmuch-company` has all `declare-function`  associated but is not loading "notmuch-address" because it does not have any autoload.

When I manually load notmuch the issue disappears. 
So probably we need o add some require or autoload in the company side?

**Comment by dgutov** [comment]
Sounds like `notmuch-company` needs to `require` the feature that contains the variable `notmuch-address-completion-headers-regexp`.

Not sure how any specific change in Company could help with that.

**Comment by Ergus** [comment]
I don't know how to report a bug to notmuch... it seems unmaintained... Do we have another alternative backend for email address completions??

**Comment by dgutov** [comment]
This says to use the mailing list: https://notmuchmail.org/#index9h2

And the "emacs" tag in there seems not entirely dead: https://nmbug.notmuchmail.org/nmweb/search/tag:notmuch%3A%3Aemacs (AFAICT David Bremner is the maintainer).

> Do we have another alternative backend for email address completions??

`company-bbdb`, maybe.

**Comment by dgutov** [comment]
Also: https://git.notmuchmail.org/git?p=notmuch;a=history;f=emacs/notmuch-company.el;h=c6a004aebe92bcd447ee93729a54a2518052200b;hb=HEAD
