### ISSUE TITLE
Company: backend company-capf error

### ISSUE THREAD

**Issue by avatar-lavventura** [company-mode/company-mode#1110]
I am using `lsp-mode` and `company` on top of Pyhton files. When I complete a function I am getting follwing error:

`
Company: backend company-capf error "[yas] ‘yas-expand-snippet’ needs properly setup ‘yas-minor-mode’" with args (post-completion get_job_block_number(requester_address, key, index))
`

---------

Completed function example:

` self.mongo_broker.get_job_block_number(${1:requester_address}, ${2:key}, ${3:index})$0`

which should be just: `self.mongo_broker.get_job_block_number()`

my setup:

```
(diminish 'yas-minor-mode)
(add-hook 'python-mode-hook 'lsp)
(add-hook 'python-mode-hook #'lsp-deferred)

(setq company-auto-complete t)
(global-set-key (kbd "C-c C-k") 'company-complete)

```

What may be the reason of this error and how can I resolve it?

--------

// Could be related with following question: https://emacs.stackexchange.com/questions/62183/company-backend-company-capf-error ; in comments recommended to open an issue

**Comment by dgutov** [comment]
lsp-mode bug tracker is over here: https://github.com/emacs-lsp/lsp-mode/

They also have a "troubleshooting" channel at Discord, you might want to start there.

**Comment by avatar-lavventura** [comment]
@dgutov Thanks
