### ISSUE TITLE
When completion menu is shown, if I press a key combination not bound in company-active-map, it doesn't forward the key combination to global keymap.

### ISSUE THREAD

**Issue by netjune** [company-mode/company-mode#1113]
The key combination is `Esc f5`. It is bound to a command(for example `forward-line`) in global keymap.

The key combination works well when company is not active(no completion menu).

When completion menu is shown, if I press the key combination, the completion menu disappears and then `[15~` is inserted in the buffer and the bound command `forward-line` is not run.

----- versions:
emacs: 26.3 running in terminal
company-mode: 0.9.13

**Comment by dgutov** [comment]
I have tried this snippet:

```el
(global-set-key (kbd "ESC <f5>") #'forward-line)
```

Couldn't reproduce the problem with any of the Emacs versions I've tried, with Company 0.9.13 or with current master. `ESC <f5>` invokes `forward-line` even when the popup is shown.

The terminal is GNOME Terminator.

Is there anything else I need to do to trigger this?

**Comment by netjune** [comment]
> 
> 
> I have tried this snippet:
> 
> ```emacs-lisp
> (global-set-key (kbd "ESC <f5>") #'forward-line)
> ```
> 
> Couldn't reproduce the problem with any of the Emacs versions I've tried, with Company 0.9.13 or with current master. `ESC <f5>` invokes `forward-line` even when the popup is shown.
> 
> The terminal is GNOME Terminator.
> 
> Is there anything else I need to do to trigger this?

I'm using mintty(WSL or ssh) on windows. Could you look at this? @mintty

**Comment by mintty** [comment]
So you have this problem in mintty, as I understand? I'm not an emacs user, so let's try to boil it down to something outside emacs. Possibly F5 sends different escape sequences in both terminals. This could depend on some setup by the application, so I'd like to ask for the following test case, in both mintty and some terminal where it works:
Produce the problem. If it can only be demonstrated while in emacs, `kill -9` the application, then on the command line enter ^V (Ctrl+V), then F5. To be sure, also run `od -t x1`, then enter F5, Enter, ^D.

**Comment by dgutov** [comment]
If that helps, in Terminator F5 is sending `[15~`.

I had to press `Ctrl+Q` instead of `Ctrl+V`, though.

**Comment by dgutov** [comment]
And:

```
$ od -t x1
^[[15~
0000000 1b 5b 31 35 7e 0a
0000006
```

Exactly the same output if I repeat after `kill -9`-ing Emacs.

**Comment by netjune** [comment]
> 
> 
> If that helps, in Terminator F5 is sending `[15~`.
> 
> I had to press `Ctrl+Q` instead of `Ctrl+V`, though.

In mintty it is `^[[15~`.

**Comment by netjune** [comment]
> 
> 
> And:
> 
> ```
> $ od -t x1
> ^[[15~
> 0000000 1b 5b 31 35 7e 0a
> 0000006
> ```
> 
> Exactly the same output if I repeat after `kill -9`-ing Emacs.

Only the following outputs after pressing `^D`:

```
$ od -t x1
^[[15~
```

If I press `^D` again, mintty quits.

**Comment by mintty** [comment]
Another idea comes to my mind: Perhaps emacs activates "application ESC mode" in mintty, i.e. ESC would send an escape sequence itself, in order to avoid the unpleasant ESCDELAY timeout. Please repeat the kill/od test but with just ESC rather than F5, in mintty.

**Comment by dgutov** [comment]
In Terminator, inside and outside of Emacs:

```
$ od -t x1
^[
0000000 1b 0a
0000002
```

**Comment by dgutov** [comment]
> If I run emacs in mintty and press ESC F5, it tells me "ESC is undefined"

To repro the exact scenario, you would need to evaluate the code snippet I wrote in the first reply.

**Comment by dgutov** [comment]
> As I understand, the problem occurs in mintty, right? This test is requested for mintty please.

Yes.

@netjune ?

**Comment by mintty** [comment]
@netjune, please upload the configuration (minimised as appropriate) so we can reproduce your setup.

**Comment by mintty** [comment]
Reading the original report again, I think this is what happens:
Your company thing does not know about ESC F5, so it gets the prefix ESC, waits for the rest of an escape sequence (which is normally what starts with ESC), then sees the second escape instead (the one F5 starts with) and quits (perhaps because ESC is just supposed to quit it). As the initial ESC of F5 has now been swallowed away already by the company menu, emacs only sees the rest of the escape sequence, without the ESC, and handles it as normal input.

**Comment by netjune** [comment]
> 
> 
> @netjune, please upload the configuration (minimised as appropriate) so we can reproduce your setup.

I should test with `emacs -Q`. I did just now. The problem doesn't happen with `emacs -Q`. After some testing, I find the cause. It is the following line in my configuration:
```
(define-key company-active-map "\e\e" 'company-abort)
```

After I delete this line, the problem disappears.

**Comment by netjune** [comment]
> 
> 
> Reading the original report again, I think this is what happens:
> Your company thing does not know about ESC F5, so it gets the prefix ESC, waits for the rest of an escape sequence (which is normally what starts with ESC), then sees the second escape instead (the one F5 starts with) and quits (perhaps because ESC is just supposed to quit it). As the initial ESC of F5 has now been swallowed away already by the company menu, emacs only sees the rest of the escape sequence, without the ESC, and handles it as normal input.

I think you are right.

**Comment by netjune** [comment]
Thanks. 
Closed.

**Comment by dgutov** [comment]
> It is the following line in my configuration:

That one I can reproduce, so it's not a problem with different terminals. @mintty thank for you help anyway, though.

**Comment by dgutov** [comment]
@netjune I really understand very little about how Emacs works in the terminal, and don't use it myself in there.

It will probably be good to `M-x report-emacs-bug` this scenario, and see what the gurus say.

For my part, I tried reverting a part of dff5856 which removed the `company-input-noop` stuff (and even without the version check), but that didn't seem to help. So at the very least, this problem has been with us for a long time.
