### ISSUE TITLE
Incremental drop-down menu completion for auctex through company-mode.

### ISSUE THREAD

**Issue by hongyi-zhao** [company-mode/company-mode#1121]
On Ubuntu 20.04, I installed auctex, ivy, and company-mode via [straight.el](https://github.com/raxod502/straight.el) with the following code snippet in `~/.emacs.d/init.el`:

```emacs-lisp
(straight-use-package
 `( auctex :type git :host nil :repo "https://git.savannah.gnu.org/git/auctex.git"
    :pre-build ,(pcase system-type
                (`berkeley-unix '("gmake"))
                (_ '(
                    ;("bash" "-c" "cd ~/.emacs.d/straight/repos/auctex")
                    ("./autogen.sh")
                    ("./configure")
                    ("make")
                    ("sudo" "make" "install"))))))
                  
(load "auctex.el" nil t t) 
(load "preview-latex.el" nil t t)
(setq TeX-auto-save t)
(setq TeX-parse-self t)
(setq-default TeX-master nil)

(straight-use-package
 `( swiper :type git :host github :repo "abo-abo/swiper"
    :pre-build (
               ;("bash" "-c" "cd ~/.emacs.d/straight/repos/swiper")
               ;https://github.com/abo-abo/swiper/issues/2886#issuecomment-860605327
               ("make" "deps")
               ("make" "compile")
               )))
                    
;(add-to-list 'load-path "~/.emacs.d/straight/repos/swiper/")
(require 'ivy)
(ivy-mode 1)
(setq ivy-use-virtual-buffers t)
(setq ivy-count-format "(%d/%d) ")  

(use-package company)
(add-hook 'after-init-hook 'global-company-mode)
```
Then I test my above configurations with a minimal LaTeX file as shown below:

```latex
\documentclass{paper}
\usepackage{hyperref}
\begin{document}
   Some testings come here.
\end{document}
```
In one word, what I really want is that once I start typing commands, the incremental drop-down menu should be triggered automatically immediately and the candidate results should be narrowed as the input sequence increases. To summarize, below is the drop-down menu that is triggered when only one command character is entered, and it should be gradually and precisely filtered as the input sequence grows:

![image](https://user-images.githubusercontent.com/11155854/121914087-88c57e00-cd64-11eb-8a59-953663ff6c88.png)

Any hint of implementing this feature will be highly appreciated.

Regards,
HY

**Comment by dgutov** [comment]
Hi!

First of all, have you tried https://github.com/alexeyr/company-auctex?

Second, there is a guide at https://github.com/company-mode/company-mode/wiki/Writing-backends

**Comment by hongyi-zhao** [comment]
Thank you for giving me insightful comments.

> First of all, have you tried https://github.com/alexeyr/company-auctex?

TBF, I noticed the author said the following on this repo, so I haven't tried it yet: 

`Please note that I am currently not using Emacs for LaTeX and therefore not maintaining this actively. `

**Comment by dgutov** [comment]
That doesn't necessarily mean it's broken.

But in any case, you could adopt some code or approaches from it.

**Comment by hongyi-zhao** [comment]
I tried `company-auctex` with the following in my `~/.emacs.d/init.el`:
```emacs-lisp
(straight-use-package
 `( company-auctex :type git :host github :repo "hongyi-zhao/company-auctex"))

(require 'company-auctex)
(company-auctex-init)
```
But still failed to trigger the incremental drop-down completion menu, as shown below:
![image](https://user-images.githubusercontent.com/11155854/121980153-0ec1e300-cdbe-11eb-9a59-6c11dc8cefeb.png)

**Comment by hongyi-zhao** [comment]
Based on the comments [here](https://develop.spacemacs.org/layers/+lang/latex/README.html#lsp)

```
This is the default backend if LSP layer is enabled. It provides proper IDE support and is recommended over company-auctex. 

Currently, the LaTeX LSP backend depends on TexLab.
```

So, it seems that LSP oriented solution is more powerful. For LaTeX and fiends, [this one](https://github.com/latex-lsp/texlab) comes into role.

**Comment by dgutov** [comment]
I'm glad it works for you.

**Comment by hongyi-zhao** [comment]
I'm still struggling to achieve a workable solution on this path. See [here](https://github.com/abo-abo/swiper/issues/2887#issuecomment-861463193) for some relevant discussions.
