### ISSUE TITLE
 Feature request: regexp-based search and completion result filtering displayed on the incremental drop-down menu.

### ISSUE THREAD

**Issue by hongyi-zhao** [company-mode/company-mode#1124]
On Ubuntu 20.04, I'm using `auctex`, `eglot`, `texlab`, and `company` as my Emacs based LaTeX document preparation system.
The detailed settings are described [here](https://github.com/astoff/digestif/issues/33#issuecomment-863134170). The company relevant configuration is shown below:

```emacs-lisp
(use-package company)
(add-hook 'after-init-hook 'global-company-mode)
```
And the real effect is represented in the following screenshot:

![image](https://user-images.githubusercontent.com/11155854/122422289-9aef2880-cfbf-11eb-9314-6f08e73306ea.png)

But, I want to know if it's possible to do the regexp-based search and completion result filtering displayed on the incremental drop-down menu. For example, if I typeset `\?*arrow*`, then all LaTeX commands including `arrow` will be shown up in the drop-down menu list.

Any hints for this feature will be highly appreciated.

Regards,
HY

**Comment by dgutov** [comment]
Not regexp search, but you can type `C-s arrow`.

**Comment by hongyi-zhao** [comment]
Really/exactly. Wonderful. Thank you for your comments. See the screenshot below:

![image](https://user-images.githubusercontent.com/11155854/122483933-3905e180-d006-11eb-8571-2a091afc20e5.png)

**Comment by hongyi-zhao** [comment]
Another issue I want to know if why some commands have icons, others don't, shown on the countdown second column.

**Comment by dgutov** [comment]
Which of the icons do you mean?

**Comment by dgutov** [comment]
Ah, the arrows? Those are returned by the backend.

**Comment by hongyi-zhao** [comment]
I mean, say, for the Dirac notation, there is no any icons rendered in the middle column of the drop-down menu.

![image](https://user-images.githubusercontent.com/11155854/122574028-ce928700-d081-11eb-841c-aa7308e04ba1.png)

**Comment by dgutov** [comment]
That's up to the backend. The language server, probably (if you're using lsp or eglot).

**Comment by hongyi-zhao** [comment]
Another issue: can I have a drop-down menu for normal writing/typesetting, just as we have for command completion with company, which is triggered by the threshold of a specific minimum input character number, say, 3, and then incrementally narrowed down as the input sequence increases. See [here](https://github.com/leotaku/flycheck-aspell/issues/13#issuecomment-864061784) for detailed discussion.

**Comment by dgutov** [comment]
Meaning completions from words-in-buffers? Or from installed dictionaries?

**Comment by hongyi-zhao** [comment]
From installed dictionaries. Only this is meaningful for document writing. We can't expect all input words are existed in the buffer, obviously.

**Comment by dgutov** [comment]
Something like this should work:

```el
(push '(company-capf :with company-ispell) company-backends)
```

Or without `:with`, if you're fine with only using these two backends in all your buffers.

**Comment by hongyi-zhao** [comment]
I tried with it, but noting appeared.

**Comment by dgutov** [comment]
Does `M-x company-ispell` work?

**Comment by hongyi-zhao** [comment]
Wonderful. See below:

![image](https://user-images.githubusercontent.com/11155854/122585176-c8a2a300-d08d-11eb-8865-3f2b0df886ee.png)

But once I hint RET to insert the result at the point, I must re-run `M-x company-ispell` again.

**Comment by dgutov** [comment]
What does `M-x company-diag` say?

**Comment by hongyi-zhao** [comment]
> What does `M-x company-diag` say?

![image](https://user-images.githubusercontent.com/11155854/122623960-c44ba980-d0d0-11eb-9ab3-f1cf42f27954.png)

**Comment by dgutov** [comment]
And what does it say after you evaluate `(push '(company-capf :with company-ispell) company-backends)`, which you said didn't help?

**Comment by hongyi-zhao** [comment]
![image](https://user-images.githubusercontent.com/11155854/122624283-0cb79700-d0d2-11eb-92ca-f40442fe2f78.png)

**Comment by dgutov** [comment]
And `M-x company-diag` says..?

**Comment by hongyi-zhao** [comment]
![image](https://user-images.githubusercontent.com/11155854/122624651-db3fcb00-d0d3-11eb-91be-d92ab3f449b5.png)

**Comment by dgutov** [comment]
The first 10 lines of that buffer are not visible, and they are the most imporant.

**Comment by hongyi-zhao** [comment]
Sorry for my cursory.

![image](https://user-images.githubusercontent.com/11155854/122625046-b51b2a80-d0d5-11eb-9c51-df6923425e4e.png)

**Comment by dgutov** [comment]
OK, so does completion work fine in this buffer?

But it doesn't offer dictionary completions in latex buffers? If so, you have a place in your config where you set up a buffer-local value of `company-backends` in latex buffers. When you find it, you can add that snippet to the function that's executing there.

**Comment by hongyi-zhao** [comment]
I don't understand your meaning at all. As I've said, each completion only and must be triggered by `M-x company-ispell`, regardless which buffer I'm in.

**Comment by hongyi-zhao** [comment]
`Company-wordfreq` is a company-backend for human language texts based on word frequency dictionaries. But I still fail to try it out, as described by this [issue](https://github.com/johannes-mueller/company-wordfreq.el/issues/5).

**Comment by dgutov** [comment]
Hmm, I though you were using Eglot, which works through `company-capf`.

Try `(push '(company-capf company-ispell) company-backends)`, then. It won't matter if capf is not used.

Or `(push '(company-capf company-wordfreq) company-backends)`.

**Comment by hongyi-zhao** [comment]
No, this can't solve the problem. I still must run `M-x company-ispell RET` before type each word to trigger the dropdown completion menu.
