### ISSUE TITLE
Can't display the math symbols represented by company-math.

### ISSUE THREAD

**Issue by hongyi-zhao** [company-mode/company-mode#1125]
On Ubuntu 20.04, I test the company-math package with some symbols listed in [The Comprehensive LATEX Symbol List](https://texdoc.org/serve/symbols-a4/0) in Emacs/AUCTeX with some of the same symbols shown [here](https://github.com/vspinu/company-math#readme). The Emacs configuration is as follows:

```emacs-lisp
(use-package company-math)
;; local configuration for TeX modes
(defun my-latex-mode-setup ()
  (setq-local company-backends
              (append '((company-math-symbols-latex company-math-symbols-unicode company-latex-commands))
                      company-backends)))
;If you are using AUCTeX you might need to use TeX-mode-hook instead:
(add-hook 'TeX-mode-hook 'my-latex-mode-setup)
```
But I can't get the same display results represented [here](https://github.com/vspinu/company-math#readme), see the following screenshots for more detailed info:

![image](https://user-images.githubusercontent.com/11155854/122627763-3bd70400-d0e4-11eb-8764-77c7a927d9e7.png)
![image](https://user-images.githubusercontent.com/11155854/122627815-9e300480-d0e4-11eb-970e-d7068394268b.png)

Any hints for this problem will be highly appreciated.

Regards,
HY

**Comment by dgutov** [comment]
> Any hints for this problem will be highly appreciated

I don't know, maybe your font doesn't support those symbols, and the backend somehow detects that?

It's a question for `company-math`'s maintainers. Or its documentation.
