### ISSUE TITLE
Company version 0.9.13: An error occurred in post-command

### ISSUE THREAD

**Issue by emadridm** [company-mode/company-mode#1126]
After update company package (`package-list-packages >> U >> x`) ...

`
Company: An error occurred in post-command
Company: frontend company-pseudo-tooltip-unless-just-one-frontend error "Symbol’s value as variable is void: icon-file" on command post-comman
`

Company version: 0.9.13
GNU Emacs 27.1 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.23, cairo version 1.16.0) of 2021-01-18, modified by Debian

**Comment by dgutov** [comment]
Hi!

What does `M-x company-diag` say?

Or we need the full backtrace.

**Comment by dgutov** [comment]
The latter can be fetched with `M-x toggle-debug-on-error` followed by `M-x company-complete-common`.
