### ISSUE TITLE
Company: backend company-capf error

### ISSUE THREAD

**Issue by 8x4y2z** [company-mode/company-mode#1127]
Hi. Im facing a very strange issue. In a particular python module I'm facing this issue where company doesn't provide completions. 
**Actual error:** Company: backend company-capf error "TypeError: ’NoneType’ object is not subscriptable" with args (candidates PIE_WID)

Output of `M-x company-diag`:
Emacs 27.2 (x86_64-pc-linux-gnu) of 2021-04-14 on user
Company 0.9.13

company-backends: (company-tide company-bbdb company-semantic company-cmake company-capf company-files
              (company-dabbrev-code company-gtags company-etags company-keywords)
              company-oddmuse company-dabbrev)

Used backend: company-capf
Value of c-a-p-f: (lsp-completion-at-point)
Major mode: python-mode
Prefix: "PIE_WID"
Completions: none(error fetching)

Output of `C-M-i`:
completion--some: TypeError: ’NoneType’ object is not subscriptable

I call it strange because It happens only for this particular python module, also only on my work computer. It doesnt happen on my personal laptop running ubuntu (for the same script). Add both laptops have the exact same config file. Here is the traceback:

```
Debugger entered--Lisp error: (error "TypeError: ’NoneType’ object is not subscriptable")
  signal(error ("TypeError: ’NoneType’ object is not subscriptable"))
  error("TypeError: 'NoneType' object is not subscriptable")
  lsp-request-while-no-input("textDocument/completion" (:textDocument (:uri "file:///home/pupil/hps_projects/enrep_plots/plotte...") :position (:line 482 :character 19) :context #<hash-table equal 1/65 0x1580cb958cd1>))
  #f(compiled-function () #<bytecode 0x1580cb91fe89>)()
  #f(compiled-function (probe pred action) #<bytecode 0x1580cb91fea5>)("PIE_WID" nil t)
  all-completions("PIE_WID" #f(compiled-function (probe pred action) #<bytecode 0x1580cb91fea5>) nil)
  completion-pcm--all-completions("" ("PIE_WID" point) #f(compiled-function (probe pred action) #<bytecode 0x1580cb91fea5>) nil)
  completion-basic-all-completions("PIE_WID" #f(compiled-function (probe pred action) #<bytecode 0x1580cb91fea5>) nil 7)
  #f(compiled-function (style) #<bytecode 0x1580cb958ca1>)(basic)
  completion--some(#f(compiled-function (style) #<bytecode 0x1580cb958ca1>) (basic partial-completion emacs22))
  completion--nth-completion(2 "PIE_WID" #f(compiled-function (probe pred action) #<bytecode 0x1580cb91fea5>) nil 7 (metadata (category . lsp-capf) (display-sort-function . identity)))
  completion-all-completions("PIE_WID" #f(compiled-function (probe pred action) #<bytecode 0x1580cb91fea5>) nil 7 (metadata (category . lsp-capf) (display-sort-function . identity)))
  company-capf--candidates("PIE_WID")
  company-capf(candidates "PIE_WID")
  apply(company-capf (candidates "PIE_WID"))
  company-call-backend-raw(candidates "PIE_WID")
  company--fetch-candidates("PIE_WID")
  company-calculate-candidates("PIE_WID" nil)
  company--begin-new()
  company--perform()
  company-auto-begin()
  company-idle-begin(#<buffer plotters.py> #<window 3 on plotters.py> 73967 15821)
  apply(company-idle-begin (#<buffer plotters.py> #<window 3 on plotters.py> 73967 15821))
  timer-event-handler([t 24794 48198 766382 nil company-idle-begin (#<buffer plotters.py> #<window 3 on plotters.py> 73967 15821) nil 400000])
  read-event(nil t 3)
  sit-for(3)
  flyspell-check-word-p()
  flyspell-post-command-hook()
```

**Comment by yugaego** [comment]
Have you figured this out eventually?

The error message looks like a [typical one for Python](https://www.pythonpool.com/typeerror-int-object-is-not-subscriptable/). So - guessing by looking at the backtrace - the probable scenario is that your language server returns this error message instead of completions candidates to your LSP client (I assume `lsp-mode` by `lsp-completion-at-point`), and that's why you get it.

If you still encounter the issue, it'd be a good idea to ask at the `lsp-mode` repo.
I see they already have several [TypeError issues](https://github.com/emacs-lsp/lsp-mode/search?q=TypeError&type=issues) (though not with the Python language server thus maybe not *strictly* related).

**Comment by 8x4y2z** [comment]
Ok, I'll go through the links and figure out. Thank you for the letting me know. I thought about the possibility that the issue lies with `lsp-mode`, but wasn't sure.

**Comment by woochica** [comment]
@8x4y2z did you figure out what went wrong? I'm having the same problem
