### ISSUE TITLE
Can I let company use counsel-unicode-char to display the symbols on its dropdown menu?

### ISSUE THREAD

**Issue by hongyi-zhao** [company-mode/company-mode#1131]
I have [`counsel`](https://github.com/abo-abo/swiper/blob/master/counsel.el) installed, and can use the command `counsel-unicode-char` to display the codepoint, Unicode name, and a character preview information all in one, as shown below:

![image](https://user-images.githubusercontent.com/11155854/124685071-1aa74d80-df03-11eb-9dcb-3039a4c03240.png)

But I want to know whether I can let `company` leverage the above feature supplied by `counsel-unicode-char` to render its symbols represented in the dropdown menu?

**Comment by dgutov** [comment]
That's something for each individual backend to implement.

**Comment by hongyi-zhao** [comment]
But why can't I let company display all the real symbols represented by some LaTeX mathematical commands?

**Comment by dgutov** [comment]
How do you expect this to happen?

**Comment by hongyi-zhao** [comment]
Without rely on some additional packages, say, company-math and so on.

**Comment by dgutov** [comment]
Whatever completions are shown, must come from a "backend".

If you don't want to rely on `company-math`, write your own backend, then.

**Comment by hongyi-zhao** [comment]
Let me describe my confusion in more detail as follows.

Say, the [`\Angstroem`](https://github.com/vspinu/math-symbol-lists/blob/1cf7e2885f3352f55852ee9eba26c7cb5a7cd74b/math-symbol-lists.el#L455) command is defined by comany-math's store package [math-symbol-lists](https://github.com/vspinu/math-symbol-lists) as below:

   ` ("mathalpha" "\\Angstroem" 8491 "Å")`

While `counsel-unicode-char` will show the codepoint (212b in base-16 and 8491 in base-10), Unicode name, and a character preview information all in one, as shown below:

![image](https://user-images.githubusercontent.com/11155854/124754786-2e7f9d80-df5d-11eb-8a7c-7a4bea295b31.png)

If all the codepoint, unicode name, and the character preview information already available in company, just as we have seen in `counsel-unicode-char`, why comany-math still need to store the character preview information in its store package, instead of obtain it directly with an in-situ manner?

**Comment by dgutov** [comment]
Because company doesn't know that it's dealing with math symbols, or character names, at all.

**Comment by hongyi-zhao** [comment]
Thank you for your systematic explanations.
