### ISSUE TITLE
Non-math commands also have been completed in math-mode.

### ISSUE THREAD

**Issue by hongyi-zhao** [company-mode/company-mode#1132]
See the screenshot below:

![image](https://user-images.githubusercontent.com/11155854/125186347-8ddef580-e25c-11eb-93db-6865f89e0e81.png)

How can I only let the math relevant commands completed in the math-mode?

Regards,
HY

**Comment by yugaego** [comment]
Looking at all the questions you asked, 
- Have you tried to use only `company-math` backend? Maybe that's what you need? [Example](https://github.com/company-mode/company-mode/issues/1130#issuecomment-880225651).
- If that's what you have configured, then I suppose the question would have to be redirected to the `company-math`, wouldn't it?
- BTW, have you tried searching through the issues in this repo? For instance, [for term latex](https://github.com/company-mode/company-mode/issues?q=is%3Aissue+latex). There's always a chance you might find something useful already discussed or mentioned or tried etc. _[It's hard to imagine how many treasures are hidden in all those mailing lists, tickets, discussions, issues, etc]._

Hope it helps.

**Comment by hongyi-zhao** [comment]
> BTW, have you tried searching through the issues in this repo? For instance, [for term LaTeX](https://github.com/company-mode/company-mode/issues?q=is%3Aissue+latex). 

Wonderful suggestion. I'll try to dig into them for valuable info and give the necessary feedback.

**Comment by yugaego** [comment]
> How to know I'm in AUCTeX's math environment, i.e., what's hook and how to toggle the corresponding to backend setting ?

I'm curious, doesn't all search engines return matches for "AUCTeX+hooks"?

For example, DuckDuckGo returned these first three results:
https://www.gnu.org/software/auctex/manual/auctex/Modes-and-Hooks.html
https://tex.stackexchange.com/questions/437294/use-beamer-auctexhooks-with-class-file-derived-from-beamer
https://stackoverflow.com/questions/22549804/setting-up-auctex-latex-mode-hook-does-not-work

**Comment by yugaego** [comment]
And from the `Emacs` usage perspective (though note it's an [off-topic](https://github.com/company-mode/company-mode/discussions/1139), this repository is dedicated to the `company-mode` package only),  
you could do:
`C-h i m <auctex> RET`, then `C-s <-hook>`, hitting `C-s` to see the following `-hook` matches.

I'd also recommend to read that `AUCTeX` manual as it seems you plan to use the package extensively.

**Comment by hongyi-zhao** [comment]
> I'm curious, doesn't all search engines return matches for "AUCTeX+hooks"?

Of course, I know this. But there are some confusion in my previous expression. To be clear, when I said: `How to know I'm in AUCTeX's math environment`, I mean to judge the math-environment when working with `AUCTeX` LaTeX mode.

**Comment by yugaego** [comment]
> Of course, I know this.

My curiosity was a sincere one. There're many search engines out there and different types of blockers/firewalls.
(Though I agree, one can never be sure which level/type of research had already been done - unless it have been explicitly stated.)

> I mean to judge the math-environment when working with AUCTeX LaTeX mode.

I personally can't help in this regard, because I don't even understand the question 😄  

Might be you need an AUCTeX specific support?

>  company-math package, which seems to give so many non-math symbols in the dropdown menu even I'm in LaTeX math-mode

You were suggested to ask this question at this third-party package. Did you? Any interesting ideas on that side?

**Comment by hongyi-zhao** [comment]
> My curiosity was a sincere one. 

Me too. I didn't mean anything else, and you're welcome. 

> You were suggested to ask this question at this third-party package. Did you? Any interesting ideas on that side?

TBF, till now, no.
