### ISSUE TITLE
c++-mode ':', '>' and '/' unnecessarily begin completion

### ISSUE THREAD

**Issue by ville-h** [company-mode/company-mode#1133]
By default the `company-begin-commands` contains: `c-electric-colon`, `c-electric-lt-gt` and `c-electric-slash` which does not result in very nice user experience. The completion popup is shown too early and can't seemingly complete to anything related or meaningful at least in c or c++. Removing those three then disables the completion popup from showing after: `::` or `->` which isn't very nice either, which is when a relevant completion could be shown.

Perhaps it would be possible for company-mode wrap or replace `c-electric-colon` and `c-electric-lt-gt` with their own versions that check for the previous character in the buffer. For `:` that it is the last in a `::` sequence and for `>` that it is last in a `->` sequence.

I am not sure why `c-electric-slash` is even on the list. Hard to think what it is supposed to complete as far as c or c++ syntax goes.

**Comment by dgutov** [comment]
Hi!

> Perhaps it would be possible for company-mode wrap or replace c-electric-colon and c-electric-lt-gt with their own versions that check for the previous character in the buffer. For : that it is the last in a :: sequence and for > that it is last in a -> sequence.

That can be done in the backend, in the `prefix` handler. Which one are you using, `company-clang` or one of the LSP ones?

**Comment by dgutov** [comment]
> I am not sure why c-electric-slash is even on the list.

For `company-c-headers`, I think. And similar functionality that can be implemented in other backends.

**Comment by ville-h** [comment]
> That can be done in the backend, in the `prefix` handler. Which one are you using, `company-clang` or one of the LSP ones?

I have to expose my unfamiliarity with emacs and company and say: "I dunno". I've not altered the value of `company-backends`, but I do have `lsp-mode` enabled. For a buffer with `lsp-mode` enabled the current value of `company-backends` looks like:
> (company-bbdb company-semantic company-cmake company-capf company-clang company-files (company-dabbrev-code company-gtags company-etags company-keywords) company-oddmuse company-dabbrev)

I haven't altered `company-backends` because any time I try to the completions stop working altogether and I can't find a decent explanation, for a non-elisp programmer, how it works.

**Comment by dgutov** [comment]
> I have to expose my unfamiliarity with emacs and company and say: "I dunno".

`M-x company-diag` could answer that question, but

> but I do have lsp-mode enabled

that almost certainly points to lsp-mode as the place for the next steps.

**Comment by ville-h** [comment]
Output for `company-diag`:

```
Emacs 27.2 (x86_64-pc-linux-gnu) of 2021-03-26 on juergen
Company 0.9.13

company-backends: (company-bbdb company-semantic company-cmake company-capf company-clang company-files
    (company-dabbrev-code company-gtags company-etags company-keywords)
    company-oddmuse company-dabbrev)

Used backend: company-capf
Value of c-a-p-f: (lsp-completion-at-point)
Major mode: c++-mode
Prefix: ""
<...huge block of lisp omitted...>
```

**Comment by dgutov** [comment]
> Used backend: company-capf
Value of c-a-p-f: (lsp-completion-at-point)

Yup.

**Comment by ville-h** [comment]
If I understand what you were saying and the output correctly, `lsp-mode` could in their `lsp-completion-at-point` prevent the popup from occuring?

**Comment by dgutov** [comment]
Yes. Try filing an issue, or asking at their Discord.

It might be non-trivial because LSP is supposed to be language-agnostic, and the corresponding language server might do something that we don't want to... but this is not something I could help with.

Try asking them anyway.

**Comment by ville-h** [comment]
It would [appear](https://github.com/emacs-lsp/lsp-mode/issues/2998) the problem is caused by lsp-mode. So as far as I am concerned this issue may be closed here. Thanks.
