### ISSUE TITLE
Completion based on company-mode and language server protocol. 

### ISSUE THREAD

**Issue by hongyi-zhao** [company-mode/company-mode#1135]
I've learned that both company-mode and clients for language server protocol servers, say, [eglot](https://github.com/joaotavora/eglot) and [lsp-mode](https://github.com/emacs-lsp/lsp-mode), can be used to do the completion. But what's the differences between them?

Regards,
HY

**Comment by dgutov** [comment]
The difference between Eglot and lsp-mode?

Try this Reddit thread, for example: https://www.reddit.com/r/emacs/comments/o5dnaz/what_was_your_experience_of_moving_from_lspmode/

**Comment by hongyi-zhao** [comment]
> The difference between Eglot and lsp-mode?

No. I mean that even without using `Eglot` or `lsp-mode`, it seems that the company-mode can do all things for me.

**Comment by dgutov** [comment]
Those are different sources, with different precision and completeness. LSP has the best options for C/C++ and Java completion, for example. There is nothing for Java in stock company-mode.

**Comment by hongyi-zhao** [comment]
Got it. Thank you very much.
