### ISSUE TITLE
Ensure the completion returned from `company-tabnine` have the highest priority.

### ISSUE THREAD

**Issue by hongyi-zhao** [company-mode/company-mode#1141]
See the following completion results for my case and the corresponding company-backends settings:

![image](https://user-images.githubusercontent.com/11155854/126465220-dee2bf94-8a7a-4e2a-ba21-9ce3f3d0e839.png)

I want to ensure that the completion candidates returned from `company-tabnine` have the highest priority. How to achieve this?

Regards,
HY

**Comment by dgutov** [comment]
What your value of `company-transformers`?

**Comment by hongyi-zhao** [comment]
See the screenshot below:

![image](https://user-images.githubusercontent.com/11155854/126503043-32a1d26d-e4db-4958-8267-144c38298032.png)

**Comment by dgutov** [comment]
Try removing the first element. Or see whether `company-prescient` has any relevant configuration. It's a third-party package, so I can't help there.

**Comment by hongyi-zhao** [comment]
Thank you very much. Got it. 

According to the documentation [here](https://github.com/raxod502/prescient.el#company-specific), customizing the user option `company-prescient-sort-length-enable` to `nil` will fix this problem:

```emacs-lisp
(use-package prescient :demand t)

(use-package company-prescient
  :after prescient
  :init (setq company-prescient-sort-length-enable nil)
  :config (company-prescient-mode t))
```
![image](https://user-images.githubusercontent.com/11155854/126573764-be732722-40b0-4c38-a2ef-97417b4c4d94.png)

I also tried to comment out all the configuration related to the `company-prescient` package, which can achieve the same result:

![image](https://user-images.githubusercontent.com/11155854/126573258-c0baf174-c575-4d18-87a2-a71191edcefe.png)

**Comment by dgutov** [comment]
I'll try converting this to a Discussion (Q&A). Let's see whether it will convert all the answers into one thread.
