### ISSUE TITLE
Create a customized dictionary and configure company-ispell to use it.

### ISSUE THREAD

**Issue by hongyi-zhao** [company-mode/company-mode#1146]
On Ubuntu 20.04, I've the following ispell/aspell dictionaries installed:
```
$ sudo apt-get --install-suggests install iamerican-insane
$ aspell dicts 
en
en-variant_0
en-variant_1
en-variant_2
en-w_accents
en-wo_accents
en_AU
en_AU-variant_0
en_AU-variant_1
en_AU-w_accents
en_AU-wo_accents
en_CA
en_CA-variant_0
en_CA-variant_1
en_CA-w_accents
en_CA-wo_accents
en_GB
en_GB-ise
en_GB-ise-w_accents
en_GB-ise-wo_accents
en_GB-ize
en_GB-ize-w_accents
en_GB-ize-wo_accents
en_GB-variant_0
en_GB-variant_1
en_GB-w_accents
en_GB-wo_accents
en_US
en_US-variant_0
en_US-variant_1
en_US-w_accents
en_US-wo_accents
```
And I also have the following [personal and replacement dictionaries](http://aspell.net/man-html/Format-of-the-Personal-and-Replacement-Dictionaries.html):

```
$ ls ~/.aspell.en.p*
/home/werner/.aspell.en.prepl  /home/werner/.aspell.en.pws
```

In Emacs, I use aspell as the value of `ispell-program-name`, as given by `C-h v R ispell-program-name R`:  
```
ispell-program-name is a variable defined in ‘ispell.el’.

Its value is "/usr/bin/aspell"
```
And see below for the list of all available dictionaries listed by `M-x ispell-change-dictionary RET SPC`:

![image](https://user-images.githubusercontent.com/11155854/126886314-09ae5ad7-7c8b-414d-bda6-19db72dbabc2.png)

But I want to know how to use multiple dictionaries and set the priorities among them, for example, let the `iamerican-insane` and personal customized ones have higher priority.

Regards,
HY

**Comment by redguardtoo** [comment]
@hongyi-zhao , I'm not sure if aspell  has anything to do with your requirement. Check code of `company-ispell--lookup-words` which is alias of `ispell-lookup-words`

![image](https://user-images.githubusercontent.com/184553/126892997-70e1ccde-796f-4142-b49e-021aa8ecd927.png)
****

So you need prepare a plain text dictionary which contains all the words you need complete.

**Comment by hongyi-zhao** [comment]
I noticed [the one used by you](https://gist.github.com/redguardtoo/8a232c0aad3b4d712bef1c2e910b8b33).

**Comment by redguardtoo** [comment]
@hongyi-zhao . That file contains the words aspell should *ignore*. As I said, aspell has nothing to do with your requirement.

See https://github.com/redguardtoo/emacs.d/blob/master/lisp/init-company.el#L143 how I set up company.

![image](https://user-images.githubusercontent.com/184553/126893741-a03dc88e-48f4-4e69-bedc-2c81cc337af6.png)

**Comment by hongyi-zhao** [comment]
> That file contains the words aspell should _ignore_. As I said, aspell has nothing to do with your requirement.

Thank you for correct my misunderstanding.
 
> See https://github.com/redguardtoo/emacs.d/blob/master/lisp/init-company.el#L143 how I set up company.

Thank you for telling me your settings. BTW, do you know any convenient method to generate such word list file from huge dictionaries, say,  `Webster's Third New International Dictionary, Unabridged (En-En)`? In my situation, I've [sdcv](https://github.com/Dushistov/sdcv) installed, and have added some dictionaries, as shown below:

```
$ sdcv -l
Dictionary's name   Word count
懒虫简明英汉词典    452185
Webster's Third New International Dictionary, Unabridged (En-En)    296190
```
But I want to prepare a complete word list file similar to [yours](https://github.com/redguardtoo/emacs.d/blob/master/misc/english-words.txt) from the above dictionary, `Webster's Third New International Dictionary, Unabridged (En-En)`.

**Comment by yugaego** [comment]
Closing, since the [follow-up discussion](https://github.com/company-mode/company-mode/discussions/1156) seems had exhausted the topic.
