### ISSUE TITLE
[Feature] company-quick-access-modifier doesn't support control

### ISSUE THREAD

**Issue by Inc0n** [company-mode/company-mode#1151]
I use control key modifier alongside with the numeric keys 1-9 and 0, to choose from the list of 10 choices.

I found out about `company-quick-access-modifier`, and realised this could be customized but only between the `meta`, `super`, `hyper` keys, and the implementation safeguard and forces the modifier to be fallback to `meta` when it doesn't recognize the value of `company-quick-access-modifier`. 

This is all well and good until, me, who would like control key to be part of the options as well.

Best wish,
Inc0n

**Comment by yugaego** [comment]
Hi Inc0n,
Yes, you got it all right.

This set of modifiers was a successive (only `meta` was suggested not so long ago) and [conscious](https://github.com/company-mode/company-mode/pull/1115#issuecomment-876230653)  choice.

In other words, it was chosen not to suggest `control` to avoid potential clashes with the default `Company` keymaps (see `M-x describe-keymap <(company-active-map|company-search-map)>`).

Taking this into notice, would `control` still be a desirable modifier for your use case?

**Comment by Inc0n** [comment]
So what you mean by clashes, if I understood correctly, are the potential clashes perhaps for the future key binding, the keys being `C-0` ... `C-9`?

Then I see there are considerations being made here, and I wouldn't object, since I rebind these keys (`C-0` ... `C-9`) to `company-complete-number` (which is "obsolete since 0.9.14" , didn't realise that, probably should update that in a bit).

> Taking this into notice, would `control` still be a desirable modifier for your use case?

Control would be suitable for my own personal use case, where I have also binded `C-0` to `C-9` to `winum-select-nth-window` for windows selection. But I would think that since there are thoughts put behind this decision, it would be understandable to stick with the current planning, instead of accommodate to just a few.

On that note, as the things they are, I am happy that my message has been delivered, and I will close this issue unless otherwise. 

Thanks!

**Comment by dgutov** [comment]
There had been some thought put into it, but if using `control` is something you genuinely want to do (and have tried the result, and it's working fine for you), that can make it a reasonable usage scenario. So we can add support for it.

**Comment by yugaego** [comment]
> So we can add support for it.

I agree, and `C-(digit)` seems to be a viable and potentially wanted use case.

@dgutov , Thinking about it, would it be a possible scenario to keep the current set of modifiers at `Customize` but allow `control` (in `company-keymap--quick-access-modifier`)  for those who want to configure it from the code?

In other words, are there any known/obvious drawbacks in providing different sets of allowed values in `Customize` vs code?
(other than *mildly* broken `Customize` interface and the need to document not obvious functionality).

After this feedback, it also seems to me a list of supported modifiers should be added to the docstring of `company-quick-access-modifier` anyway, would you agree?

@Inc0n , thank you for articulating your use-case. And yes, `company-complete-number` was renamed to `company-complete-tooltip-row` in master; both of these names are supported now.

**Comment by dgutov** [comment]
> Thinking about it, would it be a possible scenario to keep the current set of modifiers at Customize but allow control (in company-keymap--quick-access-modifier) for those who want to configure it from the code?

Definitely possible. But we can probably add it to Customize as well. As long as it's not the default value, any key binding conflicts will be the result of an explicit action by the user (and they can revert it from there as well).

If it causes trouble, we can take it back out anytime (from Customize, at least).

**Comment by dgutov** [comment]
@Inc0n Check out the latest version.

**Comment by Inc0n** [comment]
Loving it, now I am able to configure quick access with a `setq` to a variable.

I do appreciate the speed and the efforts into this. Thank you guys!

**Comment by yugaego** [comment]
> now I am able to configure quick access with a setq to company-quick-access-modifier

Though you'd be on a safer side using this approach:
```
(customize-set-variable 'company-quick-access-modifier 'control)
```

**Explanatory details:**
For instance, `company-search-map` won't be re-initialized properly having `setq` `company-quick-access-modifier`. You may try it for yourself by filtering candidates with `C-M-s` (`M-x company-filter-candidates`) so that the list of candidates changes. Hitting a quick-access key after that will select the wrong candidate.

This is an [expected behavior](https://github.com/company-mode/company-mode/pull/1115#issuecomment-857807722) caused by how `company-quick-access-modifier` (and `company-quick-access-keys`) are initialized. So this configurational peculiarity is mentioned in `C-h v <company-quick-access-modifier>` (and `company-quick-access-keys`) documentation.

**Comment by Inc0n** [comment]
I see thank you for the tip!
