### ISSUE TITLE
The appearance of the company completion dropdown is very different to my previous one.

### ISSUE THREAD

**Issue by hongyi-zhao** [company-mode/company-mode#1153]
I'm not sure what's the corresponding configuration options for controlling the appearance of the company completion dropdown. Now it looks like the following:

![image](https://user-images.githubusercontent.com/11155854/127593894-d37814cd-09e6-489c-adb0-ed78fad910d7.png)

But a few days ago, it looked like the following, as shown [here](https://github.com/company-mode/company-mode/issues/1141#issuecomment-884570548):

![image](https://user-images.githubusercontent.com/11155854/126573764-be732722-40b0-4c38-a2ef-97417b4c4d94.png)

Any hints for the corresponding settings and control options?

Regards,
HY

**Comment by dgutov** [comment]
No idea. Did you install something like `company-box`?

**Comment by hongyi-zhao** [comment]
Thank you very much. Really, I don't know when the following configuration was added:

```emacs-lisp
(use-package company-box
  :hook (company-mode . company-box-mode))
```
When I commented the above codes out, the appearance of company comes back again:

![image](https://user-images.githubusercontent.com/11155854/127660278-2ae34172-d9d7-4362-8feb-0f3cc15d4d55.png)
