### ISSUE TITLE
lsp cant get complete candidates after error response from lsp

### ISSUE THREAD

**Issue by wibed** [company-mode/company-mode#1210]
https://github.com/emacs-lsp/lsp-mode/issues/3028
https://github.com/emacs-lsp/lsp-sourcekit/issues/20
https://github.com/emacs-lsp/lsp-sourcekit/issues/18

tl;dr
after receiving 
```
[Trace - 12:41:11 PM] Received response 'textDocument/completion - (685)' in 7ms.
Result: {
  "code": -32800,
  "message": "request cancelled"
}
```

company-capf completion stops working, saying its waiting for resolution for said error.
clearing the cache works, but only for manual calling `company-complete`, until the error occurs again 
and one has to clear the cache again etc.

```
The problem seems to be with lsp-completion--get-context that is used as a parameter to the completion request.
For whatever reason, lsp-completion--cache gets set with an incomplete marker. 
The context sets specific :trigger-kind in this case which seems to break the completions.

Unfortunately, just deactivating caching with (setq lsp-completion-no-cache 't) doesn't seem to be enough, 
the :incomplete marker is still set.
```

**Comment by wibed** [comment]
it seem this one is related

https://github.com/emacs-lsp/lsp-mode/issues/2970

**Comment by dgutov** [comment]
This is clearly either an lsp-mode problem, or a problem with the server.

The link in the last message is likely unrelated.

I suggest you try and resolve this with the lsp-mode people.

In the meantime, you can try https://github.com/nathankot/company-sourcekit. It will have fewer features, but it might be easier to set up. Or not.

**Comment by wibed** [comment]
@dgutov 

> This is clearly either an lsp-mode problem, or a problem with the server.
this is true. i will close this here for now and continue the discussion on https://github.com/emacs-lsp/lsp-mode/issues/3028
