### ISSUE TITLE
Elisp: Additional variable binding forms like pcase-let, letrec

### ISSUE THREAD

**Issue by alphapapa** [company-mode/company-mode#1213]
Hi,

Having recently started using `company-mode` for some Elisping, I noticed that `company-elisp-var-binding-regexp` doesn't include forms like `pcase-let`, `pcase-let*`, and `letrec`, so I guess completion of local variables bound in these forms won't be offered.

https://github.com/company-mode/company-mode/blob/1887974e7ad50cb4884fbec27985078bba754b60/company-elisp.el#L73-L76

Fully supporting all of `pcase-let`'s semantics might be prohibitive, but I'm guessing that supporting non-destructuring bindings in it, ones equivalent to using `let`, wouldn't require much.  (I suppose one could consider macroexpanding a `pcase-let` form to get its expanded bindings, but I don't know if that would be a good idea.)

Thanks for your work on Company.

**Comment by dgutov** [comment]
Hi!

`company-elisp` is deprecated in favor of `company-capf` with recent enough Emacs releases.

`elisp-completion-at-point` supports a lot more macros and special forms. And yeah, it uses macro expansion.

**Comment by alphapapa** [comment]
Ah, I'm sorry for wasting your time on this then.  You're all way ahead of me.  :)

FWIW, I'm really enjoying using Company for Elisp on Emacs 28.  With the right `completion-styles`, it's so convenient to just be able to type, e.g. `buffilnam` and have Company instantly complete to `buffer-file-name`.  So thanks again for your work.
