### ISSUE TITLE
Back-end company-clang async timeout with args (candidates )

### ISSUE THREAD

**Issue by vbalnt** [company-mode/company-mode#122]
Hi, with company-mode for c++ & clang I get the following error

Company: An error occurred in auto-begin
Company: Back-end company-clang async timeout with args (candidates )

When I take a look at the _clang-output_ buffer all the suggestions are there but the problem I guess is transferring them to the company front-end. 

this is with the latest revision

**Comment by Breezee-ops** [comment]
I'm having this same issue for a program that's extremely small

**Comment by dgutov** [comment]
Sometimes the small C++ program might still be complex enough for the completion to be slow. If you want, post it here so somebody else can try it.

In any case, you can also fall back to any of the external completion backends that are based on Clang.
