### ISSUE TITLE
Key-chord does not trigger after completion with company-tng

### ISSUE THREAD

**Issue by BlueDrink9** [company-mode/company-mode#1224]
#### Output of the command `M-x company-diag`

Used backend is `company-dabbrev` for this minimal reproduction.

#### Describe the issue

Typing a key-chord after using company-tng to complete something does not trigger the expected key-chord. Instead, it seems only the first part of the key-chord binding triggers. I press `jk`, and instead of going to evil-normal-state, nothing happens for a second, and the minibuffer tells me I have pressed `key-chord` as if it is waiting for another key. If I then press `jk` an additional, it works as expected. However, if I press another key instead, e.g. `a`, I get `<key-chord> a` is undefined.

For the sake of minimal reproduction (i.e. without evil), I have replaced `evil-normal-state` with `print-buffer`

#### Steps to reproduce
List the steps to reproduce the behavior. Ideally starting with a bare Emacs session: `emacs -Q` (if you can).

emacs -Q config (requires straight.el installed somewhere for loading packages, I don't know how I would reproduce this without it.):

```elisp
(load-file "~/.emacs.d/straight/repos/straight.el/bootstrap.el")
(straight-use-package 'company)
(straight-use-package 'key-chord)
(company-mode)
(company-tng-mode)
(key-chord-mode 1)
(require 'key-chord 1)
(key-chord-define-global "jk"     'print-buffer)
```

After evaluating this, start a new sexp. Company pops up, push `tab` to complete something. Immediately after selecting an item, type jk.

#### Expected behavior

 Emacs asks if I want to print the buffer.

**Comment by dgutov** [comment]
Hi!

So this is a combination of Evil, key-chord-mode and company-tng? :fearful: It's a dangerous concentration of magic in one place.

I don't know how the other two packages work, but `company-tng`, when encountering a key outside a defined set, performs the completion and then "puts it back" by calling `company--unread-this-command-keys` which modifies `unread-command-events`. Could be it's not the state of affairs that `key-chord-mode` expects, IDK.

I would recommend asking the maintainer, but it appears the package is in "orphanage" with the issue tracker closed. The next step would be for you to try studying the implementation and do some print-debugging on its sources. It's only 200 lines long, so it should be possible, given enough determination.

I can give some further debugging advice, but I don't have the time to do it myself, sorry.

**Comment by BlueDrink9** [comment]
> dangerous concentration of magic

Possibly true, but seems a very natural combo to me; lots of vim users try to avoid esc by means of a two-letter escape shortcut, and tng was built to emulate vim behaviour. I was surprised to be the only one experiencing this issue.
(And anyway, evil itself has nothing to do with the bug, it's only tng + key-chord)

At this stage, I am not very comfortable with elisp and debugging, so this might sit around for a while. I am determined to find a solution eventually, it just might take time for me to learn and dig. I appreciate the offer of support.

It is indeed a shame that key-chord is abandoned, and that emacs has no better support for such things.
I suspect from its readme and limitations, key-chord is using a few things under the hood that might be considered hacky.

**Comment by BlueDrink9** [comment]
https://github.com/emacsorphanage/key-chord/blob/7f7fd7c5bd2b996fa054779357e1566f7989e07d/key-chord.el#L195 looks like the relevant area

**Comment by BlueDrink9** [comment]
Where does tng put things back into `unread-commands`?

**Comment by yugaego** [comment]
> Where does tng put things back into `unread-commands`?

https://github.com/company-mode/company-mode/blob/3eaac91b27d5041a97a0cbae32bb5b03e361d230/company-tng.el#L126

https://github.com/company-mode/company-mode/blob/3eaac91b27d5041a97a0cbae32bb5b03e361d230/company.el#L2762

**Comment by yugaego** [comment]
Hey @BlueDrink9 , any progress with your intention?
Feel free to close it if the topic is not relevant anymore. Thanks.

**Comment by BlueDrink9** [comment]
Haven't had a chance to dive in, but it is still relevant

**Comment by BlueDrink9** [comment]
With the help of modern technology (gpt4) I was eventually able to get a workaround for this. Since I only have one insert-mode key-chord, I've just set any chord event during completion to trigger the chord mapping.

```elisp
  (defun my/transition-to-evil-normal-after-tng-chord ()
    "Transition to evil-normal-state after company-tng completion when a key-chord is detected."
    (when unread-command-events
      (if (eq (car unread-command-events) 'key-chord)
        (progn
          (company-complete)
          (evil-normal-state)
          ; Clear the tng event storage that thinks it needs to trigger an extra key-chord
          (setq unread-command-events nil)
          ; Reset key-chord's unmatched key state - not sure this is actually necessary
          (setq key-chord-last-unmatched nil)))))

  (advice-add 'company--unread-this-command-keys :after #'my/transition-to-evil-normal-after-tng-chord)
```
