### ISSUE TITLE
Error after upgrade to the latest commit 5c84da83

### ISSUE THREAD

**Issue by tommyjiang** [company-mode/company-mode#1229]
#### Output of the command `M-x company-diag`
```
Emacs 27.2 (x86_64-apple-darwin18.7.0) of 2021-03-28 on Traviss-Mac.local
Company 0.9.13

company-backends: (company-capf
 (company-semantic company-dabbrev-code company-gtags company-etags company-keywords)
 company-files company-dabbrev)

Used backend: company-dabbrev
Major mode: org-mode
Prefix: nil
Completions: none
```
#### Describe the issue
The following error reported after upgrade to the latest commit `5c84da83`.

#### Expected behavior
Nothing happens before.

#### The error backtrace
```
Debugger entered--Lisp error: (args-out-of-range 0 12)
  add-face-text-property(0 12 company-preview-common nil #("获取对象地址" 0 6 (face company-preview)))
  company-preview-show-at-point(1074 "获取对象地址")
  company-preview-frontend(post-command)
  company-preview-if-just-one-frontend(post-command)
  company-call-frontends(post-command)
  company-post-command()
  company-idle-begin(#<buffer 20210927075700-csapp.org> #<window 3 on 20210927075700-csapp.org> 870 1074)
  apply(company-idle-begin (#<buffer 20210927075700-csapp.org> #<window 3 on 20210927075700-csapp.org> 870 1074))
  timer-event-handler([t 24916 6575 527271 nil company-idle-begin (#<buffer 20210927075700-csapp.org> #<window 3 on 20210927075700-csapp.org> 870 1074) nil 0])
  read-event(nil t 3)
  sit-for(3)
  flyspell-check-word-p()
  flyspell-post-command-hook()
```

**Comment by dgutov** [comment]
Hi!

Sorry for the wait.

Could you try this patch?

```diff
diff --git a/company.el b/company.el
index af657ad..455d718 100644
--- a/company.el
+++ b/company.el
@@ -3616,7 +3616,7 @@ Delay is determined by `company-tooltip-idle-delay'."
                               (string-prefix-p company-prefix company-common)
                               company-common))
          (common (company--common-or-matches completion)))
-    (setq completion (copy-sequence (company--pre-render completion)))
+    (setq completion (company--clean-string (company--pre-render completion)))
     (add-face-text-property 0 (length completion) 'company-preview
                             nil completion)
 
```

**Comment by tommyjiang** [comment]
> Hi!
> 
> Sorry for the wait.
> 
> Could you try this patch?
> 
> ```diff
> diff --git a/company.el b/company.el
> index af657ad..455d718 100644
> --- a/company.el
> +++ b/company.el
> @@ -3616,7 +3616,7 @@ Delay is determined by `company-tooltip-idle-delay'."
>                                (string-prefix-p company-prefix company-common)
>                                company-common))
>           (common (company--common-or-matches completion)))
> -    (setq completion (copy-sequence (company--pre-render completion)))
> +    (setq completion (company--clean-string (company--pre-render completion)))
>      (add-face-text-property 0 (length completion) 'company-preview
>                              nil completion)
>  
> ```

Thanks, I will try.

**Comment by dgutov** [comment]
Never mind, I've pushed another fix which makes string width/length handling more consistent.

Let me know if the problem occurs again.

**Comment by tommyjiang** [comment]
> Never mind, I've pushed another fix which makes string width/length handling more consistent.
> 
> Let me know if the problem occurs again.

OK, thanks again for the quick fix.
