### ISSUE TITLE
Whitespace mode issues

### ISSUE THREAD

**Issue by sethen** [company-mode/company-mode#1231]
#### Describe the issue
White space characters show up when company completes.  `company-box` does not have this issue, but `company-box` is also pretty buggy.  Why are whitespace characters shown out of the box with company?

#### Steps to reproduce
Turn on `(global-whitespace-mode)` and use company to autocomplete something.

#### Expected behavior
I would expect not to see these white dots in the completion dropdown.  It's drawing the whitespace characters I have assigned for whatever reason.

#### Screenshots
![Screenshot from 2021-10-02 21-34-14](https://user-images.githubusercontent.com/1493530/135736415-02b27172-489c-45b5-bf66-f9f1be532e96.png)

**Comment by dgutov** [comment]
Hi!

This is what this (unmerged) PR was opened for: https://github.com/company-mode/company-mode/pull/245

Sorry to say, I'm still not a fan of the implementation (too many changes for this kind of functionality). I simply recommend you remove `space-mark` from `whitespace-style`, it looks weird anyway.

Perhaps it will be good to remove it from the default value as well.

And the technical reason for this is the characters are shown using `buffer-display-table` which affects how all spaces look in the buffer. The mode tones the effect down by default with `whitespace-space` face using font-lock, but font-lock rules are not applies to the contents of the popup.

**Comment by dgutov** [comment]
Here's a simpler workaround, though, which does use `whitespace-face`. I don't think we'll be applying it by default, because it would affect [company-posframe](https://github.com/tumashu/company-posframe/)'s behavior as well, but see how it works for you.

```el
(defun company--replacement-with-ws-face (str)
  (if (and (or global-whitespace-mode whitespace-mode)
           (memq 'space-mark whitespace-active-style)
           (memq 'face whitespace-active-style)
           (memq 'spaces whitespace-active-style))
      (let ((face `(:foreground ,(face-attribute 'whitespace-space :foreground))))
        (replace-regexp-in-string
         " "
         (lambda (s)
           (setq s (copy-sequence s))
           (add-face-text-property 0 (length s) face nil s)
           s)
         str))
    str))

(advice-add #'company--replacement-string
	    :filter-return
	    #'company--replacement-with-ws-face)
```

**Comment by sethen** [comment]
This workaround makes the spaces less pronounced, but they are still there.  Before applying this when the popup comes up the spaces are white.  When applying this the spaces are the same color as they are in the editor.

**Comment by dgutov** [comment]
Right. Is that a problem?

It's "drawing the whitespace characters <you> have assigned", after all. And it's doing that with the appropriate face now.

**Comment by sethen** [comment]
I guess I was curious if there was anyway to get rid of the space characters completely in the company popup

**Comment by dgutov** [comment]
I'm not seeing a good solution.

It would be possible to replace the spaces with nbsp's, but `whitespace-display-mappings` also includes an entry for that character. And the other spaces seem to be either different with, or not present in common fonts (and thus end up using a proportional font, breaking the popup alignment), or both.

If you don't want to remove `space-mark` from `whitespace-style`, try `company-posframe`? It's been generally less buggy IME than `company-box`.

**Comment by sethen** [comment]
I just installed and tried out `company-posframe` and it looks exactly like I want it to.  One issue I have encountered with it is it seems to mess with my keybinds for selecting previous when setting binds for `company-active-map`.

**Comment by dgutov** [comment]
Could you give an example of settings it conflicts with?I'm not aware of any such problems.15:06, October 4, 2021, Sethen Maleno ***@***.***>:
I just installed and tried out company-posframe and it looks exactly like I want it to.  One issue I have encountered with it is it seems to mess with my keybinds for selecting previous when setting binds for company-active-map.

—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.

-- Dmitry Gutov

**Comment by dgutov** [comment]
That's too bad. The same snippet (though transformed into "plain" Elisp):

```el
(define-key company-active-map (kbd "C-j") #'company-select-next)
(define-key company-active-map (kbd "C-k") #'company-select-previous)
```

seems to have the desired effect here (both commands work). Might have something to do with the rest of the configuration your using. Doom/Evil/etc,

**Comment by sethen** [comment]
@dgutov I am using vanilla emacs with evil, so I am assuming this is an evil thing

**Comment by sethen** [comment]
Can confirm, this is an evil issue... taking it out of my set up and using the keybinds works fine

**Comment by dgutov** [comment]
Perhaps it assigns some special function to `C-k`.

E.g. in Vim's insert mode, `C-k` seems to serve a similar purpose to `C-q`.

**Comment by sethen** [comment]
I think you're correct.  Changing the binding to `M-k` and `M-j` worked flawlessly.  So, I guess that's what I will be using 🤷🏻
