### ISSUE TITLE
Fix that the company overlay does not disappear frequently when typing for async backends

### ISSUE THREAD

**Issue by Dima-369** [company-mode/company-mode#1235]
#### Output of the command `M-x company-diag`
```
Emacs 27.2 (x86_64-apple-darwin18.5.0) of 2021-04-05 on blueberry.local
Company 0.9.13

company-backends: (company-bbdb company-semantic company-cmake company-capf company-clang company-files
              (company-dabbrev-code company-gtags company-etags company-keywords)
              company-oddmuse company-dabbrev)

Used backend: company-capf
Value of c-a-p-f: (sly-complete-filename-maybe sly-complete-symbol)
Major mode: lisp-mode
```

#### Describe the issue
See https://github.com/joaotavora/sly/issues/468 for initial discussion.

>First of all I have tested this in `slime` and it also shows the same behavior apparently, so this might not be `sly/slime` related but maybe even a company issue?
>
>Nonetheless, I find it quite annoying when typing quickly as I keep thinking that there are no candidates anymore when the popup disappears but then it appears again which can happen multiple times on a long word.
>
>Here is a video (right side shows Emacs Lisp where it works but I suspect it works so well because the is no async capf function):
>
> https://user-images.githubusercontent.com/15002298/136171095-f3dfa7cd-43e5-4bbe-9dc2-e04cee828dc9.mov
>
>---
>
>Does anyone know of a fix for this? I would expect the company popup to stay open and only disappear once there are no candidates anymore. I don't see a problem with the company popup even showing the old candidates until updated. 
 
#### Steps to reproduce
Install `sly` package, open a file and enter `lisp-mode`. Then start tying like in the video shown above. Notice how the popup frequently disappears.

> You might also suggest finding
a compromise, such as greying out the completions when they're out
of date (instead of removing the popup altogether).

@monnier suggested to mention it here as well, as this seems to be a company issue. Greying out the completions sounds fine as well actually.

**Comment by dgutov** [comment]
Thanks for the report. :+1: 

I will respond in the original issue.
