### ISSUE TITLE
Org-indent-mode shifts popup

### ISSUE THREAD

**Issue by RagnarGrootKoerkamp** [company-mode/company-mode#1252]
#### Output of the command `M-x company-diag`
<details>

```
Emacs 28.0.50 (x86_64-pc-linux-gnu) of 2021-09-21 on cd861fee5b6b
Company 0.9.13

company-backends: (company-capf
 (:separate company-dabbrev company-yasnippet company-ispell))

Used backend: (:separate company-dabbrev company-yasnippet company-ispell)

Major mode: org-mode
Prefix: nil
Completions: none
```

</details>

#### Describe the issue
In org mode with `org-indent-mode` enabled, the indents before text interact with the popup positioning in a bad way. See the before/after screenshots below.
- The popup itself is shifted 2 chars to the right after the first line.
- The text in the 'background'  behind and on the few lines below the popup is also shifted 2 chars to the right.

#### Steps to reproduce
This is using Doom emacs using the `company` and `org` modules, without any additional configuration.

Make at least two headings containing some text, and trigger autocomplete just above the second heading.

#### Expected behavior
The popup is a rectangle and does not change the indentation of the text behind it.

#### Screenshots
Before:
![before](https://user-images.githubusercontent.com/6233682/139118124-c24048e4-d43b-45c8-83f6-98d9c8a29b36.png)

After triggering popup:
![after](https://user-images.githubusercontent.com/6233682/139118159-80d83151-7c75-41f2-bcf9-054483178790.png)

**Comment by dgutov** [comment]
Hi! Thanks for the report.

I can reproduce this. But unlike the previous incarnation of this problem (https://github.com/company-mode/company-mode/issues/404), there doesn't seem to be some obvious logic behind this behavior. Its might be an Emacs bug, but I don't have the energy now to report and investigate it through its bug tracker.

Please try the patch below. It (yet again) slightly changes the rendering method, so I worry about regressions, or potential similar (but mirrored) scenarios, but so far I haven't been able to find any. If you can run with it for a few days and be on a lookout for regressions, that would be great.

```diff
diff --git a/company.el b/company.el
index f9e7194..b4b5f32 100644
--- a/company.el
+++ b/company.el
@@ -3495,7 +3495,7 @@ Returns a negative number if the tooltip should be displayed above point."
   (when (overlayp company-pseudo-tooltip-overlay)
     (overlay-put company-pseudo-tooltip-overlay 'invisible nil)
     (overlay-put company-pseudo-tooltip-overlay 'line-prefix nil)
-    (overlay-put company-pseudo-tooltip-overlay 'after-string nil)
+    (overlay-put company-pseudo-tooltip-overlay 'before-string nil)
     (overlay-put company-pseudo-tooltip-overlay 'display nil)
     (overlay-put company-pseudo-tooltip-overlay 'face nil)))
 
@@ -3508,7 +3508,7 @@ Returns a negative number if the tooltip should be displayed above point."
       (overlay-put ov 'priority 111)
       ;; No (extra) prefix for the first line.
       (overlay-put ov 'line-prefix "")
-      (overlay-put ov 'after-string disp)
+      (overlay-put ov 'before-string disp)
       ;; `display' is better than `invisible':
       ;; https://debbugs.gnu.org/18285
       ;; https://debbugs.gnu.org/20847

```

**Comment by RagnarGrootKoerkamp** [comment]
This seemed so obscure I wasn't expecting a reply here - Thanks!

Your patch works for me as well. I'll report back here when I run into issues, but I'm not a heavy org user [yet], so don't take a lack of me finding them as proof that it works ;)

**Comment by RagnarGrootKoerkamp** [comment]
Actually, this patch also fixes another bug I was seeing, but thought to be unrelated. So that indicates that this is getting closer to the true correct implementation:

Before, line numbers on the left of the popup would disappear, and the line number shown on the first line of the popup would wrongly change to the number of the last line of the popup. I.e, it would be something like this:
```
...
 6: as<autocomplete here>
10: <first line of popup>   # with the patch, this is 7 again
  : <popup>
  : <popup>
  : <popup>
11: more text
```
With the patch, the correct line number is shown again.

(As I understand it, the disappearing of line numbers is 'intentional' and won't be fixed, so I didn't want to report that separately.)

**Comment by dgutov** [comment]
> Your patch works for me as well. I'll report back here when I run into issues, but I'm not a heavy org user [yet], so don't take a lack of me finding them as proof that it works ;)

Cool, thanks for checking. The change is small enough, so I guess I'll just push it now and wait for any regression reports, from you or others.

> Actually, this patch also fixes another bug I was seeing, but thought to be unrelated. So that indicates that this is getting closer to the true correct implementation:

Good note, that's a welcome change as well.

Let's hope this improvement is not accidental and will survive any subsequent implementation changes in d-l-n-mode.

> (As I understand it, the disappearing of line numbers is 'intentional' and won't be fixed, so I didn't want to report that separately.)

More like unavoidable, AFAIK. ;-(

Cheers!
