### ISSUE TITLE
Popup shifts a long line

### ISSUE THREAD

**Issue by cordelia04m** [company-mode/company-mode#1257]
#### Output of the command `M-x company-diag`
```
Emacs 27.2 (x86_64-pc-linux-gnu) of 2021-03-27 on juergen
Company 0.9.13

company-backends: (company-bbdb company-semantic company-cmake company-capf company-clang company-files
              (company-dabbrev-code company-gtags company-etags company-keywords)
              company-oddmuse company-dabbrev)

Used backend: company-dabbrev
Major mode: org-mode
Prefix: "c"
Completions: (omit)
```

#### Describe the issue
This issue is similar to https://github.com/company-mode/company-mode/issues/1252  The tooltip is shifted and a line behind the tooltip is shifted as well. I had this issue before and the patch in https://github.com/company-mode/company-mode/issues/1252 fixed it perfectly when the tooltip is triggered at the near end of the line. The issue still remains when the tooltip is triggered at the beginning of the line like the pic.
![company](https://user-images.githubusercontent.com/48050400/140758127-e8db317f-4ac6-442a-9249-6bf319b7ed04.png)

And this is what it looked like before I triggered company, you can see that the line is shifted (starting from the endd of 3rd sub-line of line 8)
![before company](https://user-images.githubusercontent.com/48050400/140760529-94d68b50-14dd-4512-a080-ee527e68b16f.png)

What's different from https://github.com/company-mode/company-mode/issues/1252 is I found that the issue presences on other modes as well, not just org mode.

#### Steps to reproduce
Here is the file I used in the screenshots 
[test-company.txt](https://github.com/company-mode/company-mode/files/7497672/test-company.txt)
In case the font and size matter, it's IBM Plex Mono size 15.
You need to enable visual line mode as well. 

#### Expected behavior
The text goes behind the company tooltip like it does when company is triggered near the end of the line.

**Comment by dgutov** [comment]
Hi!

This is with `visual-line-mode` enabled, right? Could have used that info in "Steps to reproduce".

Arguably a bug of the underlying mechanism with no way to predict how it's going to change in the future, so we're entering the hacks territory. But here is a patch to try:

```diff
diff --git a/company.el b/company.el
index b4b5f32..a799b51 100644
--- a/company.el
+++ b/company.el
@@ -3506,6 +3506,9 @@ Returns a negative number if the tooltip should be displayed above point."
       ;; Beat outline's folding overlays.
       ;; And Flymake (53). And Flycheck (110).
       (overlay-put ov 'priority 111)
+      ;; visual-line-mode
+      (when (memq (char-before (overlay-start ov)) '(?\s ?\t))
+        (setq disp (concat "\n" disp)))
       ;; No (extra) prefix for the first line.
       (overlay-put ov 'line-prefix "")
       (overlay-put ov 'before-string disp)
```

**Comment by cordelia04m** [comment]
@dgutov 
Yes, visual line mode is enabled. 

The patch works great! So far so good, I'll give it a try for a few days and I'll report back.

I guess it's OK to close this issue for now?

**Comment by dgutov** [comment]
:+1: 

Let's keep it open until a fix is in place.

**Comment by dgutov** [comment]
OK, no problems seem to have come up in the last few days. Guess it's time to apply the change.

Let me know if you see something wrong later.

**Comment by cordelia04m** [comment]
Hi. Yeah, I didn't notice any problem of the patch. Thank you.
