### ISSUE TITLE
Byte-compiler warnings in company.el

### ISSUE THREAD

**Issue by skangas** [company-mode/company-mode#1277]
I'm seeing these byte-compiler warnings in Emacs 28.0.90:

```
Warning (comp): company.el:785:7: Warning: Use keywords rather than deprecated positional arguments to `define-minor-mode' Disable showing Disable logging
Warning (comp): company.el:1977:7: Warning: Use keywords rather than deprecated positional arguments to `define-minor-mode' Disable showing Disable logging
```

**Comment by yugaego** [comment]
For reference: I confirm these warnings with Company 0.9.13, but not on master. The issue was addressed by the commit https://github.com/company-mode/company-mode/commit/da5a896963348d7a476b758b28bcdba24c40d523.

**Comment by dgutov** [comment]
Right. So: thanks for the report, but it's already been acted on.

@skangas  You can also see the latest version of the code at https://elpa.gnu.org/devel/company.html

**Comment by skangas** [comment]
OK, sorry for the noise!
