### ISSUE TITLE
Flymake check invalidates company-active-map in emacs-lisp-mode

### ISSUE THREAD

**Issue by mohkale** [company-mode/company-mode#1285]
#### Output of the command `M-x company-diag`
```
Emacs 29.0.50 (x86_64-pc-linux-gnu) of 2021-10-22 on mk-macbook
Company 0.9.13

company-backends: ((company-capf company-files company-yasnippet)
 company-bibtex company-capf)

Used backend: (company-capf company-files company-yasnippet)

Value of c-a-p-f: (elisp-completion-at-point tags-completion-at-point-function)
Major mode: emacs-lisp-mode
Prefix: stop
Completions: none
```

#### Describe the issue
I've run into this weird issue where if a syntax check is started by flymake after the company-popup is shown, then company-active-map stops for that session.

#### Steps to reproduce
List the steps to reproduce the behavior. Ideally starting with a bare Emacs session: `emacs -Q` (if you can).

Firstly navigate to an emacs-lisp mode buffer and populate flymake-diagnostic-functions.

```elisp
(add-hook 'flymake-diagnostic-functions 'elisp-flymake-byte-compile nil t)
(add-hook 'flymake-diagnostic-functions 'elisp-flymake-checkdoc nil t)
(setq company-tooltip-idle-delay nil)
```

Then create an empty function. Flymake should complain about a missing docstring.

```elisp
(defun foo ()
  )
```

Then open a new line and begin to enter a function or variable.

```elisp
(defun foo ()
  (com)
  )
```

The company tooltip should showup relatively quickly, wait for the syntax check to finish, now enter a key-combination in company-active-map such as RET to accept the current candidate. Instead of this happening, for me, a literal newline is inserted as if I hit return without ever using company.

#### Expected behavior
The candidate is accepted.

#### Additional context
I haven't managed to reproduce this with any other checker yet, it may only be an issue with this specific syntax checker.

**Comment by dgutov** [comment]
Hi!

> Steps to reproduce

This scenario is clearly missing the calls to enable `company-mode` and `flymake-mode`. Did you start with `emacs -Q` yourself?

> (setq company-tooltip-idle-delay nil)

This setting doesn't affect the default popup frontend -- it only affects the "with-delay" version. I'm assuming skipping it doesn't make a difference?

> The company tooltip should showup relatively quickly, wait for the syntax check to finish, now enter a key-combination in company-active-map such as RET to accept the current candidate. Instead of this happening, for me, a literal newline is inserted as if I hit return without ever using company.

I haven't been able to reproduce this, with my configuration (which would be difficult anyway since I only run syntax check on save) or with `emacs -Q`. With some recent Emacs from master. Not sure where to start debugging -- but you can try checking that the appropriate entry in `emulation-mode-map-alists` is still there (as set up by `company-ensure-emulation-alist`).

Sorry I can't recommend anything better than print-debugging.

**Comment by mohkale** [comment]
Hi @dgutov 

> Did you start with emacs -Q yourself?

No sorry, I've been trying to reproduce with `emacs -Q` but I can't seem to. It must be a conflict with another package. I'll try to debug some more when I get a chance but nothing obvious seems to be trigerring it. Oddly enough I've only found it happening with `elisp-flymake-checkdoc` so it might not be a company issue after all. For now I think it's safe to close this issue.

> Sorry I can't recommend anything better than print-debugging.

No problem, hopefully I'll figure out what's causing. Thanks for the advice.
