### ISSUE TITLE
The new company-mode manual is hard to read

### ISSUE THREAD

**Issue by matta** [company-mode/company-mode#1286]
See https://www.reddit.com/r/emacs/comments/rqewjw/comment/hqa834q/?utm_source=share&utm_medium=web2x&context=3

The lack of contrast in the styling makes it hard to read for some people, myself included.  See https://www.w3.org/WAI/perspective-videos/contrast/ for more info.  Here is what it currently looks like on my screen:

![image](https://user-images.githubusercontent.com/37314/147589756-690ce565-feb2-4d8b-a094-fb74494237e3.png)

And here is what it looks like in Firefox's "reader view", which I find much easier to read:

![image](https://user-images.githubusercontent.com/37314/147590262-1f9358b1-635a-4110-8a47-82a747ae60af.png)

**Comment by yugaego** [comment]
Thank you for the feedback. The styles belong to the `Company` homepage, so [the PR](https://github.com/company-mode/company-mode.github.com/pull/14) is open there.

**Comment by yugaego** [comment]
The fix was merged and published. Please take a look and let us know if it's easy to read now. Thanks!

**Comment by yugaego** [comment]
I'm closing the issue since the fix was applied. Feel free to re-open the issue. For new requests regarding the homepage (and the manual) styles, please preferably direct them to the corresponding [homepage repository](https://github.com/company-mode/company-mode.github.com).
