### ISSUE TITLE
When used on a line with flycheck error, lsp-ui can add an empty line before the popup

### ISSUE THREAD

**Issue by zw963** [company-mode/company-mode#1292]
![image](https://user-images.githubusercontent.com/549126/148567726-df91a5fe-3ecd-4551-9440-e60e8e83ef91.png)

I create a issue [here](https://github.com/cpaulik/emacs-material-theme/issues/53) too, but i consider maybe this is a company issue?

**Comment by zw963** [comment]
BTW, i can saw candidate is visible at first, but then disappear after a flash

**Comment by dgutov** [comment]
You should probably file it with `lsp-mode` first. Perhaps they have some ideas.

But also see #1285 which seems related, and the author ended up finding something in their config (or maybe an additional package) which caused the problem.

**Comment by zw963** [comment]
Okay, i try reproduce this issue use a minimum config, and finally, i find out the reason cause this:

```cl
(setq truncate-partial-width-windows t)
```

When above variable set to t, i can reproduce this behavior.

When i comment it out to use default value nil, i can get following strange behavior.

if i entering then remove `File` frequently, it give me two different UI, randomly, like following

![image](https://user-images.githubusercontent.com/549126/148671590-e515c3ab-0d0c-47c7-b0af-ee44233994ab.png)

--------------------

As you can see, it add a blank line after File.

![image](https://user-images.githubusercontent.com/549126/148671601-1147a5d2-5290-4e56-aa0e-ce2d3dd9f764.png)

this issue  seem like  only  happen when `File` is entering at the beginning of the line(although, i am not sure), but the fact is, it never happen when it complete on following position.

![image](https://user-images.githubusercontent.com/549126/148671888-ebee1396-7679-4ab7-b7c5-703561e1420f.png)

I can reproduce this issue even no flycheck, so, i will create a issue LSP there, and reference this, thank you.

**Comment by zw963** [comment]
This issue should not related to company? i guess, it caused by following config:

1. enable lsp action UI use (setq lsp-ui-sideline-show-code-actions t)
2. (setq truncate-partial-width-windows t)
3. ensure to open treemacs when try to reproduce this issue.



So, closing it  ...

**Comment by dgutov** [comment]
Thanks for the investigation.

Can you reproduce this with the latest Company master? Which version are you using?

Can you reproduce this without LSP? Say, inside an `.el` file? Or with some other built-in backend?

Does Flycheck have to be enabled? Does it happen with Flymake too?

**Comment by zw963** [comment]
> Can you reproduce this with the latest Company master? Which version are you using?

Yes,  i use f481c1e

> Can you reproduce this without LSP? Say, inside an .el file? Or with some other built-in backend?

No, In fact,  i guess because some config issue, company no meanful candidate for most of my code, i still try figure those things out, but, anyway,  i test it  `company-robe` source in enh-ruby-mode, and `.el`, never this issue happen, i think this issue only take effect by lsp-ui.

> Does Flycheck have to be enabled? Does it happen with Flymake too?

Yes, it can reproduce when work with builtin flymake.

BTW, this issue moved by lsp maintainer into lsp-ui, https://github.com/emacs-lsp/lsp-ui/issues/679

and @yyoncho  said, using company-posframe will fix the issue, though, i still never try it.

**Comment by zw963** [comment]
BTW, company-posframe work quite well for this cases

![image](https://user-images.githubusercontent.com/549126/148686614-ed98fc2a-af18-4104-bd81-8189aa1eb473.png)

**Comment by dgutov** [comment]
> company-posframe work quite well for this cases

Yes, of course. It uses a child frame, so it's not affected by any buffer contents.

Anyway, it seems like a company<->lsp-ui conflict, rather that a fundamental bug here. Let's see if lsp-ui's maintainers will have any further ideas. Thanks.
