### ISSUE TITLE
Make fuzzy match candidates appear in pop-up

### ISSUE THREAD

**Issue by LiGuoV** [company-mode/company-mode#1304]
### Discussed in https://github.com/company-mode/company-mode/discussions/1303

<div type='discussions-op-text'>

<sup>Originally posted by **LiGuoV** January 26, 2022</sup>
When I press  "tab"  the "fuzzy match buffer" appears
I want   pop-up fuzzy match candidates ...
I don't know...
thx
![image](https://user-images.githubusercontent.com/35767550/151053720-6d6ca4fc-7606-4147-b409-09a7d972faf2.png)
</div>

**Comment by yugaego** [comment]
It's sufficient to ask a question at one place; there's no need to double-post ;)
