### ISSUE TITLE
Company Capf does not currently check `completion-metadata` for annotations

### ISSUE THREAD

**Issue by LemonBreezes** [company-mode/company-mode#1305]
@minad, @karthink, and I have been working on @JonWaltman's [pcmpl-args.el](https://github.com/JonWaltman/pcmpl-args.el) because we would like to provide excellent completions for Eshell on the level of Zsh/Bash/Fish natively. We are currently ironing out some of the issues in `pcmpl-args`. 

During usage, we noticed that @minad's [Corfu](https://github.com/minad/corfu) package displayed annotations for `pcmpl-args` whereas `company-capf` did not. While reading the code for `company-capf--annotation`, Minad noticed this function does not check the dynamic completion table's `completion-metadata` for annotations. Changing the definition of `company-capf--annotation` to the following corrects this issue and causes the annotations to appear correctly:
```
(defun company-capf--annotation (arg)
  (let* ((f (or (plist-get (nthcdr 4 company-capf--current-completion-data)
                           :annotation-function)
                (cdr (assq 'annotation-function
                           (completion-metadata
                            (buffer-substring (nth 1 company-capf--current-completion-data)
                                              (nth 2 company-capf--current-completion-data))
                            (nth 3 company-capf--current-completion-data)
                            (plist-get (nthcdr 4 company-capf--current-completion-data)
                                       :predicate))))))
         (annotation (when f (funcall f arg))))
    (if (and company-format-margin-function
             (equal annotation " <f>")  ; elisp-completion-at-point, pre-icons
             (plist-get (nthcdr 4 company-capf--current-completion-data)
                        :company-kind))
        nil
      annotation)))
```

**Comment by dgutov** [comment]
Hi!

At some point I was hoping to move `:annotation-function` out of the completion tables entirely (just have it specified by CAPF), but since that's still not happening, sure. I hope the performance hit for long lists won't be too noticeable.

Could you make a PR, so I get the attribution right? An extra test case in `test/capf-tests.el` wouldn't hurt either.

**Comment by LemonBreezes** [comment]
> Hi!
> 
> At some point I was hoping to move `:annotation-function` out of the completion tables entirely (just have it specified by CAPF), but since that's still not happening, sure. I hope the performance hit for long lists won't be too noticeable.
> 
> Could you make a PR, so I get the attribution right? An extra test case in `test/capf-tests.el` wouldn't hurt either.

Sorry, life has taken a turn for the better lately but I have been a lot busier. I have put my Emacs work on hold temporarily.

**Comment by dgutov** [comment]
OK, I've pushed your patch, with attribution as best as I could do.
