### ISSUE TITLE
Cannot get completion from `company-clang` and `company-etags` in the same buffer

### ISSUE THREAD

**Issue by yszhang95** [company-mode/company-mode#1307]
#### Describe the issue
I cannot get completions from `company-clang` and `company-etags` in the same buffer, via `company-completion`.

Only the one in front of the other can work under `c++-mode`. I am not sure if this is expected.

#### Steps to reproduce
Start from bare emacs and add the following in `.emacs`,
```
(require 'package)
(add-to-list 'package-archives '("melpa" . "https://melpa.org/packages/") t)
(package-initialize)
(custom-set-variables
 '(package-selected-packages '(company)))
(global-company-mode)
(global-set-key (kbd "<tab>") #'company-indent-or-complete-common)
(with-eval-after-load 'company
  (define-key company-active-map (kbd "M-/") #'company-complete))
```
Create a minimal projects in shell,
```
mkdir include src
echo "void test();" > include/functions.hpp
echo "void test2();" > include/functions.hpp
cat > src/functions.cpp <<- _EOF_
#include "include/functions.hpp"
#include <iostream>
void test()
{ std::cout << "Hello, world!" << std::endl; }
void test2()
{ std::cout << "Hello, another world!" << std::endl; }
_EOF_
cat > src/main.cpp <<- _EOF_
#include "include/functions.hpp"
#include <iostream>
int main()
{ }
_EOF_
ctags -R -e
```
Insert `tes` in the body of `int main()`, there won't be pop-up until `M-x company-etags`. Given `tes`, `M-x company-complete` returns `no completion found`. However, if I insert `std::co`, a lot of possible candidates show up. Thus I think `company-clang` works.

I execute `(push 'company-etags company-backends)`. This time I have `company-etags` working but I cannot find completions from `company-clang` automatically. I need to manually execute `M-x company-clang`.

#### Expected behavior
I expect `M-/` or `company-complete` will return possible candidate.

**Comment by dgutov** [comment]
> Only the one in front of the other can work under c++-mode. I am not sure if this is expected.

This is expected, yes.

If you want their outputs together, try "grouping" them.

**Comment by yszhang95** [comment]
Thank you for this proposed way! Now it works!

I read again the corresponding user-guide [section](). I am sorry I missed the the important message
> One of the significant concepts to understand about Company is that the package relies on one backend at a time [5](https://company-mode.github.io/manual/Backends.html#FOOT5).
> The grouped backends act as one complex backend. See [Grouped Backends](https://company-mode.github.io/manual/Backends.html#Grouped-Backends).

Though the docs says:
> The backends are invoked one by one, in the sequential order of the items on the company-backends list.

Only one (grouped) backend work at each time! And `M-x company-diag` tells me by default, `company-clang` is the only backend running.
