### ISSUE TITLE
Partial rendering of company mode menu when typing for the first time in buffer

### ISSUE THREAD

**Issue by KulkarniKaustubh** [company-mode/company-mode#1312]
#### Output of the command `M-x company-diag`
Emacs 27.1 (x86_64-pc-linux-gnu) of 2020-09-19 on lgw01-amd64-021
Company 0.9.13

company-backends: (company-tabnine company-bbdb company-semantic company-cmake company-capf company-clang company-files
                 (company-dabbrev-code company-gtags company-etags company-keywords)
                 company-oddmuse company-dabbrev)

Used backend: company-dabbrev
Major mode: python-mode
Prefix: nil
Completions: none

#### Describe the issue
The full menu does not open when I am typing for the first time in a buffer. After that it works fine, but it sometimes does not show the full length of the selection as well. For example, if a menu selection is supposed to read `[1, 2, 3, 4, 5, 6, 7, 8]`, it would show me `[1, 2, 3, 4, 5,`.

#### Steps to reproduce
Open a `python` file (in my case), and start typing.

Here's my [init file](https://github.com/KulkarniKaustubh/dotfiles/blob/main/emacs/.emacs.d/init.el)

#### Expected behavior
The full menu appears when I type for the first time, and the full length of a menu entry appears.

#### Screenshots
A screenshot of the partial rendering of the menu is below:

![Screenshot from 2022-03-09 13-33-34](https://user-images.githubusercontent.com/55317079/157607707-ecffe03c-7b1d-4020-99c7-4ed5106ba32e.png)

**Comment by dgutov** [comment]
Try upgrading `company-box`.

If it doesn't help, file an issue against it. Thanks.
