### ISSUE TITLE
company-select-previous-or-abort quit when there is only company-tng-mode with only one candidates

### ISSUE THREAD

**Issue by tshu-w** [company-mode/company-mode#1316]
As we have discussed in https://github.com/company-mode/company-mode/discussions/1314, I think `company-select-previous-or-abort` should be fixed either.

<div type='discussions-op-text'>

<sup>Originally posted by **tshu-w** March 25, 2022</sup>
Is it by designed? Should `company-select-next-or-abort` take `company-selection-default` into account like `company-select-next`?

## minimal config
```lisp
;;; emacs -Q -l ~/.config/emacs/test.el

(setq package-archives '(("melpa"        . "https://melpa.org/packages/")
                         ("org"          . "https://orgmode.org/elpa/")
                         ("gnu"          . "https://elpa.gnu.org/packages/")))
(package-initialize)

(package-install 'company)
(global-company-mode)
(company-tng-mode)
```

## step to reproduce
1. `emacs -Q -l ~/.config/emacs/test.el`
2. type `crea`
## 
<img width="614" alt="Screen Shot 2022-03-25 at 22 01 42" src="https://user-images.githubusercontent.com/13161779/160136737-2fdc92fb-93e1-462e-b595-eda3d1202765.png">
3. company quit when press `C-n`</div>

**Comment by dgutov** [comment]
Fixed how? What would be the change in its behavior?

**Comment by tshu-w** [comment]
Sorry for not being clear.

### Steps to Reproduce
1. `emacs -Q -l ~/.config/emacs/test.el`
2. type `crea`
3. press `C-p`

### Excepted Behavior

selected the candidates like `company-select-next-or-abort`

### Actual Behavior

complete the candidates.

**Comment by dgutov** [comment]
Why would it select the completion?

It doesn't seem like a natural behavior. "select previous" is supposed to make the selection go up, but with nothing selected, it's conceptually "above" the first completion.

**Comment by tshu-w** [comment]
> Why would it select the completion?
> 
> It doesn't seem like a natural behavior. "select previous" is supposed to make the selection move up, but with nothing selected, it's conceptually "above" the first completion.

But If there are multi candidates. “select previous” select the last one, which is inconsistency with one candidate.

**Comment by dgutov** [comment]
That's the whole point of `company-select-previous-or-abort` as opposed to `company-select-previous`: behave differently when there is just one candidate.

**Comment by tshu-w** [comment]
> That's the whole point of `company-select-previous-or-abort` as opposed to `company-select-previous`: behave differently when there is just one candidate.

But `company-select-previous-or-abort` should not quit when `company-tng-mode` is enabled (i.e. `company-selection` is zero). What I'm trying to say is that I think this check https://github.com/company-mode/company-mode/commit/783287526a791590bea4f9a23992c2bfebdb4c8d should also be added to `company-select-previous-or-abort` too, not just `company-select-next-or-abort`.

Apologize for my poor English.

**Comment by dgutov** [comment]
> But company-select-previous-or-abort should not quit when company-tng-mode is enabled (i.e. company-selection is zero)

But why?

**Comment by tshu-w** [comment]
> > But company-select-previous-or-abort should not quit when company-tng-mode is enabled (i.e. company-selection is zero)
> 
> But why?

I forgot to emphasize again that I was talking about the case where `company-selection-wrap-around` is `t` and there should be no quit at this time?

**Comment by dgutov** [comment]
So your point is that `C-p` should wrap because there exists a value to *wrap to*?

Note that pressing `C-n` twice (when there is one one completion) isn't wrapping either, even with the latest change. Press once -> the first completion is selected; press second time -> completion is aborted and point moves to the next line.

Apparently you don't want the `-or-abort` behavior at all, do you? Then you can rebind the keymap to use the commands without `-or-abort`.

For additional consistency between `company-select-next-or-abort` and `company-select-previous-or-abort`, I suppose I could make `C-n C-p` end up with no completion selected. But that's not what you have asked for.
