### ISSUE TITLE
company-capf messes with completion-at-point-functions

### ISSUE THREAD

**Issue by ilohmar** [company-mode/company-mode#1318]
#### Describe the issue
I am transitioning to use the `company-capf` backend exclusively.  Now I am working on tweaking my usage of the `tags-completion-at-point-function` and noticed that it's removed from the `capf` default value in `company--capf-data-real`.

I understand the rationale, the defaults of `capf` clash with the defaults of `company-backends`.  But I deliberately removed tags-related backends from the latter --- to me, it's a bug that company messes with my `capf` value.

#### Steps to reproduce
```elisp
(require 'company)
(setq company-backends '(company-capf))
```
and check that no matter what you do (company-wise, that is), `tags-completion-at-point-function` is never called.

#### Expected behavior
I think there are a few possibilities.

1. Much preferred: Just do not mess with the `capf` value at all.
    a) Present a warning message in `company-etags` initialization if `capf` contains the `tags-capf..`
    b) Remove the `company-etags` backend from the `company-backends` default and put a note into its docstring.
2. Only remove `tags-capf` if `company-backends` contains `company-etags`.. somewhere.

Option 2 might use sth like
```elisp
(defun company--capf-data-real ()
  (cl-letf* (((default-value 'completion-at-point-functions)
              ;; Ignore tags-completion-at-point-function because it subverts
              ;; company-etags in the default value of company-backends, where
              ;; the latter comes later.
              (if (memq 'company-etags (flatten-tree company-backends))
                  (remove 'tags-completion-at-point-function
                          (default-value 'completion-at-point-functions))
                (default-value 'completion-at-point-functions)))
[...]
```
but that uses a `subr` function only present in Emacs 27.1.. (was just a quick writeup).

WDYT?

**Comment by dgutov** [comment]
I think I like the option 2, since option 1 will stop the default configuration working out-of-the-box as intended, without additional customization by the user.

The default config is pretty nice in that you have the etags completions mixed in with dabbrev and keywords.

I'm happy to merge a PR. Though indeed `flatten-tree` is only available in Emacs 27+, so some substitute would be required.

**Comment by dgutov** [comment]
Note the new addition in the master branch: to use `tags-completion-at-point-function` in the next release, you'll need to customize `company-capf-disabled-functions` and remove it there.

(Also linking #1320, in case anyone searching finds it first.)
