### ISSUE TITLE
When company-tooltip-flip-when-above set to t, and if the candidates output on the top of cursor, C-n/C-p move direction inverse.

### ISSUE THREAD

**Issue by zw963** [company-mode/company-mode#1340]
When company-tooltip-flip-when-above set to t, if the candidates output on the top of cursor.

Following C-n / C-p keybinding move direction is inverse. 

(define-key keymap (kbd "C-n") 'company-select-next-or-abort)
(define-key keymap (kbd "C-p") 'company-select-previous-or-abort)

That is, C-n select upper candidate, C-n select under candidated.

#### Output of the command `M-x company-diag`
Emacs 28.1.50 (x86_64-pc-linux-gnu) of 2022-06-14 on lggram
Company 0.9.13

company-backends: (company-bbdb company-cmake company-capf
	      (company-dabbrev-code company-gtags company-etags company-keywords)
	      company-dabbrev)

Used backend: (company-dabbrev-code company-gtags company-etags company-keywords)

Major mode: crystal-mode
Prefix: #("quali" 0 5
  (ws-butler-chg chg fontified t))

Completions:
  "qualified_total_count"
  "qualified_total_count"
  "qualified_target_rate"
  "qualified_processed_rate"
  "qualified_total_count"
  "qualified_processed_rate"
  "qualified_total_count"
  "qualified_total_count"
  "qualified_total_count"
  "qualified_total_count"
  "qualified_total_count:"
  "qualifiedTotalCount"

#### Expected behavior

![image](https://user-images.githubusercontent.com/549126/184663236-83ca3ab0-0991-4244-9926-cb6ff5289c8d.png)

In this case, C-p is expected move up, C-n move down, but, current behavior inversed.

Thank you.

**Comment by dgutov** [comment]
Please see https://github.com/company-mode/company-mode/issues/282
