### ISSUE TITLE
company-mode not working in inferior-python-mode

### ISSUE THREAD

**Issue by vnckppl** [company-mode/company-mode#1342]
#### Output of the command `M-x company-diag`
This command does not run in the inferior-python mode buffer (it gives the same error message as described below). If I run company-diag in another buffer, I get:
```
Emacs 29.0.50 (x86_64-pc-linux-gnu) of 2022-08-21 on lcy02-amd64-076
Company 0.9.13

company-backends: (company-bbdb company-semantic company-cmake company-capf company-clang company-files
              (company-dabbrev-code company-gtags company-etags company-keywords)
              company-oddmuse company-dabbrev)

Used backend: company-dabbrev
Major mode: org-mode
Prefix: ""
Completions: (truncated)
```

#### Describe the issue
Short description of the problem.
Company mode is not working in inferior-python-mode. It is working in other modes.

Copy/paste the exact error message: you can find it in the **\*Messages\*** buffer:

```
completion--capf-wrapper: Wrong type argument: integer-or-marker-p, nil [5 times]
Company: An error occurred in auto-begin
Company: backend company-capf error "Wrong type argument: integer-or-marker-p, nil" with args (prefix)
```

#### Steps to reproduce
List the steps to reproduce the behavior. Ideally starting with a bare Emacs session: `emacs -Q` (if you can).
I was able to reproduce this with a minimal init that only loads use-package, company, and python settings. I.e., I get the same error: `Wrong type argument: integer-or-marker-p`

#### Expected behavior
Company mode showing suggestions for auto-complete.

#### The error backtrace
If applicable, provide the backtrace of the error.
To enable backtracing, run the command: `M-x toggle-debug-on-error` *before* reproducing the error.
Copy/paste the text of the debugger’s backtrace. To disable backtracing, run the same command.

```
Debugger entered--Lisp error: (wrong-type-argument integer-or-marker-p nil)
  python-shell-completion-at-point()
  completion--capf-wrapper(python-shell-completion-at-point optimist)
  company--capf-wrapper(python-shell-completion-at-point optimist)
  company--capf-data-real()
  company--capf-data()
  company-capf(prefix)
  apply(company-capf prefix)
  company-call-backend-raw(prefix)
  company--force-sync(company-call-backend-raw (prefix) company-capf)
  company-call-backend(prefix)
  company--begin-new()
  company--perform()
  company-auto-begin()
  company-idle-begin(#<buffer *Python*> #<window 3 on *Python*> 86 239)
  apply(company-idle-begin (#<buffer *Python*> #<window 3 on *Python*> 86 239))
  timer-event-handler([t 25350 47745 848178 nil company-idle-begin (#<buffer *Python*> #<window 3 on *Python*> 86 239) nil 612000 nil])
```

**Comment by dgutov** [comment]
Hi! I haven't been able to reproduce it so far.

What if, instead of using Company, you press `C-M-i` in the same `inferior-python-mode` buffer? Does completion work with the default interface?

**Comment by vnckppl** [comment]
Thank you for looking into this. In emacs 29.05, `C-M-i` is bound to (complete-symbol ARG) (just checking if that is what you meant). Interestingly, running `M-x complete-symbol` at the end of a word shows a very similar error:

> completion--capf-wrapper: Wrong type argument: integer-or-marker-p, nil

I reverted back to emacs 28.1 to ensure that the issue was not related to the bleeding edge 29.05, but I do see the same issue there. This is the `company-diag` output on emacs 28.1 in the inferior python buffer:

```
Emacs 28.1 (x86_64-pc-linux-gnu) of 2022-06-23 on lcy02-amd64-106
Company 0.9.13

company-backends: (company-bbdb company-semantic company-cmake company-capf company-clang company-files
              (company-dabbrev-code company-gtags company-etags company-keywords)
              company-oddmuse company-dabbrev)

Used backend: company-capf
Value of c-a-p-f: (python-shell-completion-at-point comint-completion-at-point t)
Major mode: inferior-python-mode
Prefix: ""
Completions: (truncated)
```

In case it matters, this is how I have set up company mode:
```
(use-package company
  :ensure t
  :hook (after-init . global-company-mode)
  :bind
  (:map company-active-map
    ("<tab>" . company-complete-selection)
    ("<SPC>" . nil)
  )

  :custom
  (company-minimum-prefix-length 3)
  (company-idle-delay 0.0)

  :init
  ;; By default company mode sets everything to lowercase. Disable this.
  (setq company-dabbrev-downcase nil)
  (setq company-auto-complete-chars nil)
  (setq company-tooltip-align-annotations t)
  (setq company-tooltip-flip-when-above nil)
  )
```

**Comment by dgutov** [comment]
> Thank you for looking into this. In emacs 29.05, C-M-i is bound to (complete-symbol ARG) (just checking if that is what you meant). Interestingly, running M-x complete-symbol at the end of a word shows a very similar error:

Yup.

And that happens in any `run-python` shell you use? I haven't been able to reproduce this, but since it can be reproduced independent of `company-mode`, please `M-x report-emacs-bug`.

**Comment by dgutov** [comment]
When you file the report, please post the bug number here for future reference.

Or let me know if you encounter any problems filing it.

**Comment by vnckppl** [comment]
@dgutov, it turned out that in the past (a few years ago) I had to disable some parts of inferior-python-mode to because a bug made ipython not work. That bug has long been fixed, but the code was still in my init file. Removing that code fixed everything.
