### ISSUE TITLE
Load-time warning about how "Case 'light will match ‘quote’..."

### ISSUE THREAD

**Issue by kfogel** [company-mode/company-mode#1345]
This is in latest company-mode (HEAD of master is at commit 35408c0ac3a), in Emacs 29.0.50 (that is, latest GNU Emacs development version `master` branch, built from source, `emacs-repository-version' == "07257ac4eedcaedd8731b3b98e723850542aab8e").

I load company.el at startup time, and I get this warning in my `*Messages*` buffer:

> src/company-mode/company.el: Warning: Case 'light will match ‘quote’.  If that’s intended, write (light quote) instead.  Otherwise, don’t quote ‘light’.

I assume it's probably coming from the `cl-case' in this code:

```
(defun company-detect-icons-margin (candidate selected)
  "Margin function which picks the appropriate icon set automatically."
  (if (and (display-graphic-p)
           (image-type-available-p 'svg))
      (cl-case (frame-parameter nil 'background-mode)
        ('light (company-vscode-light-icons-margin candidate selected))
        (t (company-vscode-dark-icons-margin candidate selected)))
    (company-text-icons-margin candidate selected)))
```

...?  But I haven't done more research than that.

**Comment by dgutov** [comment]
Looks like a recently introduced byte-compilation warning. Thanks for the report!

**Comment by kfogel** [comment]
You're welcome, and thank you for the quick fix @dgutov.
