### ISSUE TITLE
`company-capf` error and not complete when editing C++ source with lsp-mode+clangd

### ISSUE THREAD

**Issue by Cycatz** [company-mode/company-mode#1346]
#### Output of the command `M-x company-diag`
```
Emacs 28.2 (x86_64-pc-linux-gnu) of 2022-09-12 on frederik
Company 0.9.13

company-backends: (company-bbdb company-semantic company-cmake company-capf company-clang company-files
	      (company-dabbrev-code company-gtags company-etags company-keywords)
	      company-oddmuse company-dabbrev)

Used backend: company-capf
Value of c-a-p-f: (lsp-completion-at-point tags-completion-at-point-function)
Major mode: c++-mode
Prefix: "ret"
Completions: (truncated)
```

#### Describe the issue
When editing a C++ source file and typing the first three characters  `ret` of the keyword `return` in a function body, the company window doesn't show the completion and the following error occurs:
```
Company: frontend company-pseudo-tooltip-unless-just-one-frontend error "Company: backend company-capf error "Wrong type argument: integer-or-marker-p, nil" with args (match ﻿•register_t)" on command post-comman
```

#### Steps to reproduce
Here is the minimal broken config (with lsp and company installed with `straight.el`):
```emacs-lisp
;; Invoked with emacs -Q -l config.el

;; Load straight initial config
(load-file  "~/.emacs.d/straight/repos/straight.el/bootstrap.el")

;; lsp
(straight-use-package 'lsp-mode)
(setq lsp-clients-clangd-args '("-j=8" "-background-index" "-log=error"))
(add-hook 'c++-mode-hook 'lsp)

;; company
(straight-use-package 'company-mode)
(global-company-mode t)

;; Load an example C++ source
(find-file "~/reproduce.hpp")
```
And the minimal broken c++ source `reproduce.hpp`:
```cpp
#include <cstdlib>

auto operator"" _S(const char *str, std::size_t sz)
{
    return [=](int w) {
        return w ? 0 : 1;
    };
    // Error when typing 'ret' here
}
```
Invoke Emacs with `emacs -Q -l config.el` and start typing in the `auto operator"" _S()` function. Apart from `ret`, typing other three-character combinations like `__b` (for  `__builtin_popcount`) or `con` (for `const`) also result in the same error.

However, I found a weird phenomenon that if I remove the line `(setq lsp-clients-clangd-args '("-j=8" "-background-index" "-log=error"))` in the config, there will be no error! But I am not sure if this workaround will affect any behavior of lsp-mode+clangd, I hope this can be a clue.

#### Expected behavior
The error should not happen and the company window should pop up correctly.

#### The error backtrace
```emacs-lisp
Debugger entered--Lisp error: (wrong-type-argument integer-or-marker-p nil)
  buffer-substring-no-properties(nil 139)
  (downcase (buffer-substring-no-properties (plist-get (text-properties-at 0 candidate) 'lsp-completion-start-point) (point)))
  (let* ((prefix (downcase (buffer-substring-no-properties (plist-get (text-properties-at 0 candidate) 'lsp-completion-start-point) (point)))) (prefix-len (length prefix)) (prefix-pos 0) (label (downcase candidate)) (label-len (length label)) (label-pos 0) matches start) (while (and (not matches) (< prefix-pos prefix-len)) (while (and (< prefix-pos prefix-len) (< label-pos label-len)) (if (equal (aref prefix prefix-pos) (aref label label-pos)) (progn (if start nil (setq start label-pos)) (setq prefix-pos (1+ prefix-pos))) (if start (progn (setq matches (nconc matches ...)) (setq start nil)))) (setq label-pos (1+ label-pos))) (if start (progn (setq matches (nconc matches (list (cons start label-pos)))))) (if (< prefix-pos prefix-len) (progn (setq matches nil))) (if matches nil (setq prefix-pos (1+ prefix-pos)) (setq label-pos 0))) matches)
  lsp-completion--company-match(#("﻿•register_t" 1 2 (lsp-completion-item #<hash-table equal 11/15 0x157e7835401b> lsp-sort-text "40faa292register_t" lsp-completion-start-point 136 lsp-completion-markers (136 #<marker (moves after insertion) at 139 in a.hpp>) lsp-completion-prefix "ret" face (completions-first-difference)) 2 12 (lsp-completion-prefix "ret" lsp-completion-markers (136 #<marker (moves after insertion) at 139 in a.hpp>) lsp-completion-start-point 136 lsp-sort-text "40faa292register_t" lsp-completion-item #<hash-table equal 11/15 0x157e7835401b>)))
  company-capf(match #("﻿•register_t" 1 2 (lsp-completion-item #<hash-table equal 11/15 0x157e7835401b> lsp-sort-text "40faa292register_t" lsp-completion-start-point 136 lsp-completion-markers (136 #<marker (moves after insertion) at 139 in a.hpp>) lsp-completion-prefix "ret" face (completions-first-difference)) 2 12 (lsp-completion-prefix "ret" lsp-completion-markers (136 #<marker (moves after insertion) at 139 in a.hpp>) lsp-completion-start-point 136 lsp-sort-text "40faa292register_t" lsp-completion-item #<hash-table equal 11/15 0x157e7835401b>)))
  apply(company-capf (match #("﻿•register_t" 1 2 (lsp-completion-item #<hash-table equal 11/15 0x157e7835401b> lsp-sort-text "40faa292register_t" lsp-completion-start-point 136 lsp-completion-markers (136 #<marker (moves after insertion) at 139 in a.hpp>) lsp-completion-prefix "ret" face (completions-first-difference)) 2 12 (lsp-completion-prefix "ret" lsp-completion-markers (136 #<marker (moves after insertion) at 139 in a.hpp>) lsp-completion-start-point 136 lsp-sort-text "40faa292register_t" lsp-completion-item #<hash-table equal 11/15 0x157e7835401b>))))
  company-call-backend-raw(match #("﻿•register_t" 1 2 (lsp-completion-item #<hash-table equal 11/15 0x157e7835401b> lsp-sort-text "40faa292register_t" lsp-completion-start-point 136 lsp-completion-markers (136 #<marker (moves after insertion) at 139 in a.hpp>) lsp-completion-prefix "ret" face (completions-first-difference)) 2 12 (lsp-completion-prefix "ret" lsp-completion-markers (136 #<marker (moves after insertion) at 139 in a.hpp>) lsp-completion-start-point 136 lsp-sort-text "40faa292register_t" lsp-completion-item #<hash-table equal 11/15 0x157e7835401b>)))
  apply(company-call-backend-raw (match #("﻿•register_t" 1 2 (lsp-completion-item #<hash-table equal 11/15 0x157e7835401b> lsp-sort-text "40faa292register_t" lsp-completion-start-point 136 lsp-completion-markers (136 #<marker (moves after insertion) at 139 in a.hpp>) lsp-completion-prefix "ret" face (completions-first-difference)) 2 12 (lsp-completion-prefix "ret" lsp-completion-markers (136 #<marker (moves after insertion) at 139 in a.hpp>) lsp-completion-start-point 136 lsp-sort-text "40faa292register_t" lsp-completion-item #<hash-table equal 11/15 0x157e7835401b>))))
  company--force-sync(company-call-backend-raw (match #("﻿•register_t" 1 2 (lsp-completion-item #<hash-table equal 11/15 0x157e7835401b> lsp-sort-text "40faa292register_t" lsp-completion-start-point 136 lsp-completion-markers (136 #<marker (moves after insertion) at 139 in a.hpp>) lsp-completion-prefix "ret" face (completions-first-difference)) 2 12 (lsp-completion-prefix "ret" lsp-completion-markers (136 #<marker (moves after insertion) at 139 in a.hpp>) lsp-completion-start-point 136 lsp-sort-text "40faa292register_t" lsp-completion-item #<hash-table equal 11/15 0x157e7835401b>))) company-capf)
  company-call-backend(match #("﻿•register_t" 1 2 (lsp-completion-item #<hash-table equal 11/15 0x157e7835401b> lsp-sort-text "40faa292register_t" lsp-completion-start-point 136 lsp-completion-markers (136 #<marker (moves after insertion) at 139 in a.hpp>) lsp-completion-prefix "ret" face (completions-first-difference)) 2 12 (lsp-completion-prefix "ret" lsp-completion-markers (136 #<marker (moves after insertion) at 139 in a.hpp>) lsp-completion-start-point 136 lsp-sort-text "40faa292register_t" lsp-completion-item #<hash-table equal 11/15 0x157e7835401b>)))
  company--common-or-matches(#("﻿•register_t" 1 2 (lsp-completion-item #<hash-table equal 11/15 0x157e7835401b> lsp-sort-text "40faa292register_t" lsp-completion-start-point 136 lsp-completion-markers (136 #<marker (moves after insertion) at 139 in a.hpp>) lsp-completion-prefix "ret" face (completions-first-difference)) 2 12 (lsp-completion-prefix "ret" lsp-completion-markers (136 #<marker (moves after insertion) at 139 in a.hpp>) lsp-completion-start-point 136 lsp-sort-text "40faa292register_t" lsp-completion-item #<hash-table equal 11/15 0x157e7835401b>)))
  company-fill-propertize(#("﻿•register_t" 1 2 (lsp-completion-item #<hash-table equal 11/15 0x157e7835401b> lsp-sort-text "40faa292register_t" lsp-completion-start-point 136 lsp-completion-markers (136 #<marker (moves after insertion) at 139 in a.hpp>) lsp-completion-prefix "ret" face (completions-first-difference)) 2 12 (lsp-completion-prefix "ret" lsp-completion-markers (136 #<marker (moves after insertion) at 139 in a.hpp>) lsp-completion-start-point 136 lsp-sort-text "40faa292register_t" lsp-completion-item #<hash-table equal 11/15 0x157e7835401b>)) " (Interface)" 29 nil #("  " 0 1 (display (image :file "/home/cycatz/.emacs.d/straight/build/company-mode/..." :type svg :width 16 :height 16 :ascent center :background "cornsilk")) 1 2 (display (space :width (0)))) " ")
  company--create-lines(0 10)
  company-pseudo-tooltip-show(8 4 0)
  company-pseudo-tooltip-show-at-point(139 3)
  company-pseudo-tooltip-frontend(post-command)
  company-pseudo-tooltip-unless-just-one-frontend(post-command)
  company-call-frontends(post-command)
  company-post-command()
  company-idle-begin(#<buffer a.hpp> #<window 3 on a.hpp> 150 139)
  apply(company-idle-begin (#<buffer a.hpp> #<window 3 on a.hpp> 150 139))
  timer-event-handler([t 25410 39093 179724 nil company-idle-begin (#<buffer a.hpp> #<window 3 on a.hpp> 150 139) nil 267000 nil])

```

#### Screenshots
![image](https://user-images.githubusercontent.com/24320926/194750359-ed9b77f6-ceb0-437f-9d06-8c9fd6c54271.png)

Here is the video:
https://i.imgur.com/CgPw7cb.mp4

#### Additional context
None

**Comment by dgutov** [comment]
Hi!

Please report that to `lsp-mode`.

**Comment by kiennq** [comment]
@dgutov @Cycatz It seems that the `company-mode` has altered the text properties of the candidate and make the `lsp-mode` can't find the correct starting point.
In this stack
```
company-fill-propertize(#("﻿•register_t" 1 2 (lsp-completion-item #<hash-table equal 11/15 0x157e7835401b> lsp-sort-text "40faa292register_t" lsp-completion-start-point 136 lsp-completion-markers (136 #<marker (moves after insertion) at 139 in a.hpp>) lsp-completion-prefix "ret" face (completions-first-difference)) 2 12 (lsp-completion-prefix "ret" lsp-completion-markers (136 #<marker (moves after insertion) at 139 in a.hpp>) lsp-completion-start-point 136 lsp-sort-text "40faa292register_t" lsp-completion-item #<hash-table equal 11/15 0x157e7835401b>)) " (Interface)" 29 nil #("  " 0 1 (display (image :file "/home/cycatz/.emacs.d/straight/build/company-mode/..." :type svg :width 16 :height 16 :ascent center :background "cornsilk")) 1 2 (display (space :width (0)))) " ")
```

The `"﻿•register_t"` should have its properties start from `0` instead of `1`.

**Comment by dgutov** [comment]
Hmm, okay. Does your completion table use completion boundaries now?

That should be the only case when `company-capf--candidates` prepends a part of prefix to the completions.

**Comment by Cycatz** [comment]
@dgutov I am not sure whether I have enabled it. My config is only as follows: 
```
;; Invoked with emacs -Q -l config.el

;; Load straight initial config
(load-file  "~/.emacs.d/straight/repos/straight.el/bootstrap.el")

;; lsp
(straight-use-package 'lsp-mode)
(setq lsp-clients-clangd-args '("-j=8" "-background-index" "-log=error"))
(add-hook 'c++-mode-hook 'lsp)

;; company
(straight-use-package 'company-mode)
(global-company-mode t)

;; Load an example C++ source
(find-file "~/reproduce.hpp")
```

**Comment by dgutov** [comment]
`company-capf` is enabled by default, don't worry about it.

**Comment by kiennq** [comment]
> Hmm, okay. Does your completion table use completion boundaries now?
> 
> That should be the only case when `company-capf--candidates` prepends a part of prefix to the completions.

Is that the one with `(eq (car-safe action) 'boundaries)`?
We return `nil` for it
``` elisp
       (lambda (probe pred action)
         (cond
          ((eq action 'metadata)
           '(metadata (category . lsp-capf)
                      (display-sort-function . identity)
                      (cycle-sort-function . identity)))
          ((eq (car-safe action) 'boundaries) nil)
          (t
           (complete-with-action action (funcall candidates) probe pred))))
```

**Comment by dgutov** [comment]
Ok, that's odd. I'll have to retest this myself and report back.

**Comment by dgutov** [comment]
Well... I can't repro so far. Pardon me for trying without `straight` (I don't have it installed), but I've tried with both Emacs 28 and 29-snapshot, stable versions of company and lsp-mode and the latest. Completion seems to work, see the attached video:

Except I get `__building_module` as the sole completion for `__b`, not `__builtin_popcount`. And I get three completions for `con`.

And originally I got only one completion for `ret` (which resulted in the popup not being shown), so I had to add a local var. But I don't get the `register_t` thingy in the list of suggestions. Could that cause the difference?

@kiennq Have you ever seen this error yourself?

**Comment by kiennq** [comment]
@dgutov Nope, I haven't encountered it on my end as well.
@Cycatz, FYI

**Comment by dgutov** [comment]
Perhaps either of you know how to make sure I get `register_t` among completions?

**Comment by Cycatz** [comment]
@dgutov I only got only one completion `return` too. Other candidates like `rethrow_exception` doesn't appear when typing `ret` but shows as an error.

![image](https://user-images.githubusercontent.com/24320926/196078957-66114388-3b1a-428d-8c5e-60410b21f98a.png)

But I was wondering whether the problem is relevant to lsp-clangd. 
When I removed `(setq lsp-clients-clangd-args '("-j=8" "-background-index" "-log=error"))` in `reproduce.el`, the company completion can pop up successfully.

![image](https://user-images.githubusercontent.com/24320926/196080793-13e43800-bdbd-4e1c-9495-d7572e5ac739.png)

**Comment by kiennq** [comment]
@Cycatz You can try with `(setq lsp-clients-clangd-args '("-j=8" "-background-index" "-log=error" "--header-insertion-decorators=0"))` that would remove the dot prepending the candidates and make `company-mode` works again.

I still don't understand why the dot prepended to the candidates lost its text properties though

**Comment by dgutov** [comment]
> I only got only one completion return too. Other candidates like rethrow_exception doesn't appear when typing ret but shows as an error

But apparently I don't get them at all. Maybe I'd see the error if I did.

> When I removed (setq lsp-clients-clangd-args '("-j=8" "-background-index" "-log=error")) in reproduce.el, the company completion can pop up successfully

I am trying with that setting. Maybe my version of Clang is too old, and the problem is caused by some newer feature? 
```sh
$ clangd --version
clangd version 10.0.0-4ubuntu1
```

**Comment by dgutov** [comment]
@Cycatz The screenshot also seems to indicate that you have some problem with the installation (probably unrelated): the icons look missing. Maybe a refresh of the Straight recipe will help.

**Comment by dgutov** [comment]
Very good. Perhaps it would be worth it to ask the maintainer of whatever recipe repository to flush the `company-mode` one. Not sure where it resides, though.

**Comment by dgutov** [comment]
> I am using Archlinux and my clangd version is 14.0.6. It's likely that clangd has some changes?

Thanks. Guess I'll circle around to this report after I upgrade to the newer Ubuntu LTS.

**Comment by blahgeek** [comment]
I am using archlinux with clangd 14.0.6. I cannot reproduce this issue either.

Just a hunch: `downcase` from the stacktrace seems suspicious. What's your locale setting?

**Comment by Cycatz** [comment]
@blahgeek Thanks for your report.
This is my locale settings:
```
~ >>> locale
LANG=en_US.UTF-8
LC_CTYPE=zh_TW.UTF-8
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=
```

**Comment by blahgeek** [comment]
Aha, I can reproduce it now (though I'm not sure if it's the exact same as your case)

I reproduced it by running `env LC_CTYPE=zh_TW.UTF-8 emacs`. My system doesn't have `zh_TW.UTF-8` locale configured, so emacs reports a warning 

```
(process:558448): Gtk-WARNING **: 20:53:59.281: Locale not supported by C library.
        Using the fallback 'C' locale.
```

With this, following your example gives me the exact same error.

So overall I think it's safe to presume that this issue 1. is related to locale settings 2. is related to the  `"•"` char which is enabled by clangd `--header-insertion-decorators`

**Comment by blahgeek** [comment]
@Cycatz Maybe you can try `env LC_CTYPE=en_US.UTF-8 emacs`?

**Comment by dgutov** [comment]
Could somebody who is able to reproduce this, try `edebug`-ing `company-capf--candidates` and see what kind of strings we get from `completion-all-completions`?

Do they already have the first character without the requisite text property, perhaps?

**Comment by dgutov** [comment]
From searching the bug tracker, I also notice that using `header-insertion-decorators` seems like a non-recommended configuration with lsp-mode. So it could be not as well tested.

**Comment by Cycatz** [comment]
> Maybe you can try env LC_CTYPE=en_US.UTF-8 emacs?

@blahgeek It works! There is no error with the `zh_TW` locale unset.

> (FYI, if you are setting the LC_CTYPE for the chinese input method issue, that's not required anymore as of emacs 28.1 :)

Really? Is it a recent change?

**Comment by Cycatz** [comment]
> Could somebody who is able to reproduce this, try edebug-ing company-capf--candidates and see what kind of strings we get from completion-all-completions?

@dgutov  I'll give it a try.

**Comment by mihaiolteanu** [comment]
I'm suddenly getting this error, as well.

```
Company: An error occurred in post-command
Company: frontend company-pseudo-tooltip-unless-just-one-frontend error "Company: backend company-capf error "Wrong type argument: integer-or-marker-p, nil" with args (match Console)" on command post-command
```

**Comment by dgutov** [comment]
> lsp-completion-at-point

That's the useful part. Please use the lsp-mode support channels.
