### ISSUE TITLE
Consider bumping version for GNU ELPA

### ISSUE THREAD

**Issue by skangas** [company-mode/company-mode#1349]
Hi Dmitry,

The latest release on GNU ELPA is "[company-0.9.13.tar](https://elpa.gnu.org/packages/company-0.9.13.tar), 2020-Jul-26, 350 KiB". Please consider releasing a new version.

Thanks in advance.

**Comment by dgutov** [comment]
Hi Stefan,

You are right, of course. I just wanted to cross out a few more items and then do a big version bump. I should have more time this month, let's see if all this can happen before the new year.

**Comment by jellelicht** [comment]
Hi Dmitry, is there an implicit checklist of TODO items, where volunteers could contribute and lighten the load?
Thanks for all the good work

**Comment by skangas** [comment]
Ping! Any progress here?

**Comment by bremner** [comment]
From the Debian side, we would also appreciate a new tagged release. 0.9.13 doesn't pass the tests anymore with emacs 29.1, and packaging a snapshot is not as nice in various ways.

**Comment by dgutov** [comment]
Hi folks! Sorry about procrastinating on this.

The "a few more items" are still not there, but the contents of `master` have certainly stabilized over the latest period of no big changes. So I should cut a new `0.9.*` release in the next few days.

I'll also create a milestone with specific things I wanted to resolve before bumping to 1.0.

**Comment by skangas** [comment]
Sounds great, and thanks for all your work.

**Comment by dgutov** [comment]
Considering the volume of changes, I went with `0.10.0`.

:tada: :tada: :tada:

Now we can go for some riskier changes.

Regarding the milestone and the issues, will post an update later.

**Comment by skangas** [comment]
Thanks! The new version is now on GNU ELPA:
https://elpa.gnu.org/packages/company.html

**Comment by bremner** [comment]
Stefan Kangas ***@***.***> writes:

> Thanks! The new version is now on GNU ELPA:
> https://elpa.gnu.org/packages/company.html
>

and in Debian unstable. Thanks also from me,

David

**Comment by dgutov** [comment]
Here's that milestone: https://github.com/company-mode/company-mode/milestone/1

As for potential help, if someone has extra time, trying out the PR branches (currently two of them) could help. And maybe see if you have anything to add to the comments in #340.
