### ISSUE TITLE
How to insert full function definition

### ISSUE THREAD

**Issue by braoult** [company-mode/company-mode#1355]
### Discussed in https://github.com/company-mode/company-mode/discussions/1354

<div type='discussions-op-text'>

<sup>Originally posted by **braoult** December 18, 2022</sup>
In C-mode, if I type `printf`, company will popup some candidates, like:
```
printf(const char *restrict format, ...)
dprintf(int fd, const char *restrict fmt, ...)
fprintf(FILE *restrict stream, const char *restrict format, ...)
...
```
If I select one of them, the function name is inserted (for example `fprintf`). Is there a way/shortcut to have the full declaration inserted (the same as proposed in list) ? This would be very useful for functions we don't know very well.

For example, in the above example, if I select the `printf` line, I would like to insert `printf(const char *restrict format, ...)` instead of only `printf`.
</div>

**Comment by dgutov** [comment]
Hi!

Which backend is being used here? You can find out with `M-x company-diag`.

**Comment by braoult** [comment]
Thanks @dgutov,

`M-x company-diag` gives:
```
company-backends: (company-capf
 (company-dabbrev-code company-gtags))

Used backend: company-capf
Value of c-a-p-f: (lsp-completion-at-point tags-completion-at-point-function)
Major mode: c-mode
```
Note that I use `lsp/ccls`.

**Comment by dgutov** [comment]
All right.

Step 1: Try installing `yasnippet` and enabling `yas-global-mode`.

If it doesn't help, the best place to investigate further is `lsp-mode`'s Discord, Issues, Discussions, etc.

**Comment by braoult** [comment]
hmmm. I tried `yas-global-mode`, no change (or maybe I need to understand how to use different shortcuts with `yassnippet` ?
However, I think `company` hasthe information, as it displays it :
![company](https://user-images.githubusercontent.com/8958429/208323786-c4b50784-52fc-438f-9a22-57166a71024a.png)

The decision to "complete/insert" with `printf` or `printf(const char *restrict format, ...)` is done by company, no ? I mean company displays some information to make a choice (the list above), and inserts something when a selection is made.

My question is more: Could company (with a different shortcut) insert what is displayed in list instead of a single word ?
I may be wrong, assuming is could be in company : I am sometimes totally lost trying to understand which package does what ;-) If it is the case, I will try to see ln `lsp-mode` side, but I am pessimistic...

**Comment by dgutov** [comment]
> hmmm. I tried yas-global-mode, no change

You might also need to restart the LSP server which is driving completion after that.

> (or maybe I need to understand how to use different shortcuts with yassnippet ?)

Just knowing to press TAB to iterate between snippet fields should be enough.

> The decision to "complete/insert" with printf or printf(const char *restrict format, ...) is done by company, no ? I mean company displays some information to make a choice (the list above), and inserts something when a selection is made.

It's done by individual backends. The data what to show in the popup and how to insert the arguments are different: the latter is more involved, because it enables more features.

**Comment by braoult** [comment]
It does work, somehow: Some functions arguments are inserted, some are not, macros parameters are not.

I will close this issue, as it does not look related to company-mode.

Thanks a lot, and Merry Christmas !
