### ISSUE TITLE
Incorrect keys for structure slots

### ISSUE THREAD

**Issue by EmilySeville7cfg** [company-mode/company-mode#1357]
**Please make sure to search in [existing issues](https://github.com/company-mode/company-mode/issues?q=) before filing a new report!**

[Feel free to remove pre-filled text **after** reading it.]

#### Output of the command `M-x company-diag`
Before posting, look carefully at the output of this command.
You may find important clues in it for figuring out the cause of the issue.

In particular, note the value on the line starting with `Used backend:`
- Compare the value to the names of the [third-party backends](https://github.com/company-mode/company-mode/wiki/Third-Party-Packages).
  -  It's likely that the issue should be reported to the corresponding third-party package instead.
- If the value is `company-capf`, then one more clue is on the line starting with `Value of c-a-p-f:`
  -  The issue could have been caused by a function listed there.
  -  Use `M-x find-function RET <function-name> RET` to identify which package it belongs to.

```
Emacs 27.1 (x86_64-pc-linux-gnu) of 2022-01-25 on lgw01-amd64-048
Company 0.9.13

company-backends: (company-bbdb company-semantic company-cmake company-capf company-clang company-files
	      (company-dabbrev-code company-gtags company-etags company-keywords)
	      company-oddmuse company-dabbrev)

Used backend: company-capf
Value of c-a-p-f: (elisp-completion-at-point t)
Major mode: lisp-interaction-mode
Prefix: ":re"
Completions:
  #(":reader" 0 3 (face (completions-common-part)) 3 4 (face (completions-first-difference)))
  #(":relief" 0 3 (face (completions-common-part)) 3 4 (face (completions-first-difference)))
  #(":reqs" 0 3 (face (completions-common-part)) 3 4 (face (completions-first-difference)))
  #(":repeat" 0 3 (face (completions-common-part)) 3 4 (face (completions-first-difference)))
  #(":reverse-video" 0 3 (face (completions-common-part)) 3 4 (face (completions-first-difference)))
  #(":reuseaddr" 0 3 (face (completions-common-part)) 3 4 (face (completions-first-difference)))
  #(":reload" 0 3 (face (completions-common-part)) 3 4 (face (completions-first-difference)))
  #(":relative-width" 0 3 (face (completions-common-part)) 3 4 (face (completions-first-difference)))
  #(":request" 0 3 (face (completions-common-part)) 3 4 (face (completions-first-difference)))
  #(":rehash-size" 0 3 (face (completions-common-part)) 3 4 (face (completions-first-difference)))
  #(":require" 0 3 (face (completions-common-part)) 3 4 (face (completions-first-difference)))
  #(":remote" 0 3 (face (completions-common-part)) 3 4 (face (completions-first-difference)))
  #(":rehash-threshold" 0 3 (face (completions-common-part)) 3 4 (face (completions-first-difference)))
  #(":read-only" 0 3 (face (completions-common-part)) 3 4 (face (completions-first-difference)))
  #(":regexp" 0 3 (face (completions-common-part)) 3 4 (face (completions-first-difference)))
  #(":reg-usage" 0 3 (face (completions-common-part)) 3 4 (face (completions-first-difference)))
  #(":resulttype" 0 3 (face (completions-common-part)) 3 4 (face (completions-first-difference)))
  #(":registry" 0 3 (face (completions-common-part)) 3 4 (face (completions-first-difference)))
  #(":relative-height" 0 3 (face (completions-common-part)) 3 4 (face (completions-first-difference)))
```

#### Describe the issue
Incorrect keys for structure slots are shown while the official [documentation](https://www.gnu.org/software/emacs/manual/html_node/cl/Structures.html) lists just 3 slot options: :read-only, :type, and :documentation.

#### Steps to reproduce
- Install this package via `M-x package-install RET company`
- Switch to `*Scratch*` buffer
- `M-x company-mode RET`
- Type `(cl-defstruct person (name :re` and see this incorrect suggestions

#### Expected behavior
Expected just 3 listed keys shown explained in documentation.

#### The error backtrace
If applicable, provide the backtrace of the error.
To enable backtracing, run the command: `M-x toggle-debug-on-error` *before* reproducing the error.
Copy/paste the text of the debugger’s backtrace. To disable backtracing, run the same command.

#### Screenshots
![image](https://user-images.githubusercontent.com/42812113/208654460-32b8a120-ce7f-433f-b4e7-0b5c3c1cf25b.png)

#### Additional context
Emacs 27.1

**Comment by dgutov** [comment]
Hi!

Unfortunately, `elisp-completion-at-point` is part of Emacs. So any changes in it can only be effected there.

`M-x report-emacs-bug` is the way to go.

**Comment by dgutov** [comment]
Also note the instructions above, about identifying which package completions belongs go.

**Comment by EmilySeville7cfg** [comment]
Already reported to `bug-gnu-emacs@gnu.org`, this issue can be closed.
