### ISSUE TITLE
Structure option's completion is broken: doesn't work as expected

### ISSUE THREAD

**Issue by EmilySeville7cfg** [company-mode/company-mode#1358]
**Please make sure to search in [existing issues](https://github.com/company-mode/company-mode/issues?q=) before filing a new report!**

[Feel free to remove pre-filled text **after** reading it.]

#### Output of the command `M-x company-diag`
Before posting, look carefully at the output of this command.
You may find important clues in it for figuring out the cause of the issue.

In particular, note the value on the line starting with `Used backend:`
- Compare the value to the names of the [third-party backends](https://github.com/company-mode/company-mode/wiki/Third-Party-Packages).
  -  It's likely that the issue should be reported to the corresponding third-party package instead.
- If the value is `company-capf`, then one more clue is on the line starting with `Value of c-a-p-f:`
  -  The issue could have been caused by a function listed there.
  -  Use `M-x find-function RET <function-name> RET` to identify which package it belongs to.

#### Describe the issue
No completions shown for [structure options](https://www.gnu.org/software/emacs/manual/html_node/cl/Structures.html) after opening a brace.

#### Steps to reproduce
- Type `(cl-defstruct person (:con` and expect `:constructor` to be suggested but nothing is shown

#### Expected behavior
`:constructor` suggested.

#### The error backtrace
If applicable, provide the backtrace of the error.
To enable backtracing, run the command: `M-x toggle-debug-on-error` *before* reproducing the error.
Copy/paste the text of the debugger’s backtrace. To disable backtracing, run the same command.

#### Screenshots
![image](https://user-images.githubusercontent.com/42812113/208660978-34f226af-3b51-45fb-b758-4ad232bb6642.png)

#### Additional context
Emacs 27.1

**Comment by EmilySeville7cfg** [comment]
Workaround: add space after brace.

**Comment by EmilySeville7cfg** [comment]
Already reported to `bug-gnu-emacs@gnu.org`, this issue can be closed.

**Comment by dgutov** [comment]
If you have the urls to reported issues, it would be helpful to post them here for posterity. Thanks.
