### ISSUE TITLE
cannot bind `<escape>` under `company-active-map` when using evil and company-quickhelp

### ISSUE THREAD

**Issue by Alan-Chen99** [company-mode/company-mode#1359]
only happens when `company-quickhelp` is enabled
#### Steps to reproduce
``` emacs
(require 'package)
(add-to-list 'package-archives
	'("melpa" . "https://melpa.org/packages/"))
(package-initialize)
(package-refresh-contents)

(unless (package-installed-p 'evil)
	(package-install 'evil))
(unless (package-installed-p 'company)
	(package-install 'company))
(unless (package-installed-p 'company-quickhelp)
	(package-install 'company-quickhelp))

(evil-mode 1)
(global-company-mode)
(company-quickhelp-mode)

(setq debug-on-error t)
(evil-define-key nil company-active-map (kbd "a") (lambda () (interactive) (error "throws as expected")))
(evil-define-key nil company-active-map (kbd "<escape>") (lambda () (interactive) (error "supposed to throw here but doesnt")))
;; go to scratch buffer and type something, wait until quickhelp shows up, then press escape
```

**Comment by dgutov** [comment]
Sorry, that sounds like an Evil question.

**Comment by Alan-Chen99** [comment]
how does `company-active-map` work, and why can it be affected by what `company-quickhelp` is doing?

**Comment by dgutov** [comment]
`company-quickhelp` doesn't alter any keymaps.

It works off fired timers which are set up, basically, in `post-command-hook`. Or to be more precise, from company's callbacks which usually fire in `post-command-hook`.

`company-active-map` is made active (current) during active completion. Perhaps you were looking for `company-mode-map`?

**Comment by Alan-Chen99** [comment]
The `<escape>` binding only fails to work when I enable `company-quickhelp`, and only after the quickhelp pops up. Does this part call any `evil` code?

**Comment by dgutov** [comment]
I don't really know how Evil works. But `company-quickhelp` certainly doesn't call into it directly.

It uses `pos-tip` to display popup, and then hide it after certain user interaction. Does pressing `Esc` do nothing when the quickhelp popup is displayed?

**Comment by Alan-Chen99** [comment]
Yea, no error is raised in that case

**Comment by dgutov** [comment]
Can you try reproducing your scenario without Evil?

This works for me:

```el
(define-key company-active-map (kbd "<escape>") (lambda () (interactive) (error "supposed to throw here")))
```

Pressing `Esc` writes this message to the message area. Whether the quickhelp popup is visible or not.

**Comment by dgutov** [comment]
Note that unless you `M-x toggle-debug-on-error`, the error is just shown as a message.

**Comment by Alan-Chen99** [comment]
When I disable `evil` the exception is raised, so the bug only happens with `evil`.

I have `(setq debug-on-error t)`, so it's not caused by the message being suppressed

**Comment by dgutov** [comment]
Looks like it's time to visit the Evil issue tracker. :shrug:
