### ISSUE TITLE
company-tempo: no dabbrev-code completion if company-tempo is the first backend of company-backends

### ISSUE THREAD

**Issue by condy0919** [company-mode/company-mode#1360]
#### Steps to reproduce

```
# where /tmp/a.el is the following Elisp 
emacs -Q -L ~/.emacs.d/elpa/company-* -l /tmp/a.el
```

```elisp
(setq company-idle-delay 0)
;; Easy navigation to candidates with M-<n>
(setq company-show-quick-access t)
(setq company-require-match nil)
(setq company-minimum-prefix-length 3)
(setq company-tooltip-width-grow-only t)
(setq company-tooltip-align-annotations t)
;; complete `abbrev' only in current buffer and make dabbrev case-sensitive
(setq company-dabbrev-other-buffers nil)
(setq company-dabbrev-ignore-case nil)
(setq company-dabbrev-downcase nil)
;; make dabbrev-code case-sensitive
(setq company-dabbrev-code-ignore-case nil)
(setq company-dabbrev-code-everywhere t)
;; call `tempo-expand-if-complete' after completion
(setq company-tempo-expand t)
;; Ignore uninteresting files. Items end with a slash are recognized as
;; directories.
(setq company-files-exclusions '(".git/" ".DS_Store"))
;; No icons
(setq company-format-margin-function nil)
(setq company-backends '(
			 company-tempo
			 company-files
			 (company-dabbrev-code company-keywords)
			 company-dabbrev
			 company-capf))

(require 'company)
(global-company-mode +1)
```

Switch the scratch buffer, then type `cre`, no company completion. The content of scratch is the default.

```
;; This buffer is for text that is not saved, and for Lisp evaluation.
;; To create a file, visit it with C-x C-f and enter text in its buffer.
```

typing `cre` is intended for the word `create`.

After commenting out the `company-tempo` backend and re-eval, `cre` can trigger completion.

**Comment by dgutov** [comment]
That's how company-backends work (check out its docstring). And that's why grouping is a feature.

**Comment by condy0919** [comment]
> That's how company-backends work (check out its docstring). And that's why grouping is a feature.

Does `company-tempo` behave like `company-yasnippet` that backends after which will never be called?

**Comment by dgutov** [comment]
Yep.

This is true of every backend. It's just some of them specialize on certain major modes, or certain contexts (e.g. outside of strings and comments), and pass on control to later backends when outside of that major mode or context.

`company-yasnippet` just doesn't specialize, and works in every major mode, and inside and outside of comments. That's why it's a bit of a special case, but not really. `company-tempo` is the same.

**Comment by condy0919** [comment]
Thanks for your explanation.
