### ISSUE TITLE
Odd background being applied behind icons on Windows

### ISSUE THREAD

**Issue by grolongo** [company-mode/company-mode#1362]
Hi! So I have a very weird bug that I can't iron out. Basically, there is an odd background being applied on the icons in the company candidates menu:

![company](https://user-images.githubusercontent.com/34292770/211624738-8844dbac-e1eb-4034-ae20-26293f91433c.png)

I am using the exact same `init.el` across different machines including macOS, Linux, WSLg and Windows (native).  
This problem _only_ appears on Windows.  
It was also working fine few days ago until I updated some packages, so I bisected my config but no luck.  
I reverted company before the latest commit to see if it was the culprit but no luck neither.

Have you ever seen something like this?

**Comment by dgutov** [comment]
Could it be related to the version of `librsvg`? Faulty handling of transparency? Did you upgrade Emacs or just library dependencies?

I haven't used Windows in quite some time, so I can't help much with that ecosystem, sorry. But you can try some other packages which use svg (some third-party mode-lines, for example).

**Comment by dgutov** [comment]
If you don't find a solution quickly enough, we can try creating a bare-bones example using svg and filing an Emacs bug report.

**Comment by grolongo** [comment]
>Did you upgrade Emacs or just library dependencies?

I only upgraded a few external packages like `consult`, `vertico` and `modus-themes`, not Emacs.

The Emacs version is the same as when it was working fine last week and now:
`"GNU Emacs 28.2 (build 2, x86_64-w64-mingw32) of 2022-09-13"` downloaded from the official website.  

This is the bare bone `init.el` config I'm using to reproduce the issue (no `early-init.el` involved):  

```elisp
;; package.el and MELPA
(require 'package)
(add-to-list 'package-archives '("melpa" . "https://melpa.org/packages/") t)

;; Make sure `use-package’ is available.
(unless (package-installed-p 'use-package)
  (package-refresh-contents)
  (package-install 'use-package))

;; Configure `use-package' prior to loading it.
(eval-and-compile
  (setq use-package-always-demand t))

(eval-when-compile
  (require 'use-package))

(use-package company
  :ensure t
  :custom (company-backends '((company-dabbrev company-capf)))
  :config (global-company-mode 1))
```

Test case result using the default theme:
![default-theme](https://user-images.githubusercontent.com/34292770/211814782-3b0ee86c-bf62-4293-9529-61ff4c878e9b.png)

Test case using `wheatgrass` theme:
![wheatgrass-theme](https://user-images.githubusercontent.com/34292770/211814883-89a404f3-470f-4314-927f-f6e73cb1aad4.png)

Notice that it looks fine using several built-in dark themes somehow.  
I'm still totally confused. Last week I even asked a not so related question about icons margins and on the screenshot it looks totally fine: https://github.com/company-mode/company-mode/discussions/1361  

>But you can try some other packages which use svg (some third-party mode-lines, for example).  

Corfu uses svg icons too but in a child frame, I'll try that. I'll also test with company-posframe and report back.

**Comment by dgutov** [comment]
That's pretty odd. What does

```el
(face-attribute (if selected
                                      'company-tooltip-selection
                                    'company-tooltip)
                                  :background)
```

evaluate to in such cases, in themes that have this problem, and those that do not?

**Comment by grolongo** [comment]
I get the same error for the few themes I tested:

```elisp
Debugger entered--Lisp error: (void-variable selected)
  (if selected 'company-tooltip-selection 'company-tooltip)
  (face-attribute (if selected 'company-tooltip-selection 'company-tooltip) :background)
  (progn (face-attribute (if selected 'company-tooltip-selection 'company-tooltip) :background))
  elisp--eval-last-sexp(nil)
  eval-last-sexp(nil)
  funcall-interactively(eval-last-sexp nil)
  command-execute(eval-last-sexp)
```

**Comment by dgutov** [comment]
Ah, sorry. Let's split that up:

```el
(face-attribute 'company-tooltip :background)
```

and

```el
(face-attribute 'company-tooltip-selection :background)
```

**Comment by dgutov** [comment]
Okay, nothing suspicious there.

Let me know if company-posframe will be different.

**Comment by grolongo** [comment]
>Let me know if company-posframe will be different.

Exact same problem. Looks odd using the default theme, no problem with another one.

**Comment by dgutov** [comment]
Okay. Please try this in `*scratch*`:

```el
(with-silent-modifications
  (insert (propertize " " 'display
                      (list 'image
                            :file (format "%s/vscode-light/symbol-variable.svg" company-icons-root)
                            :type 'svg
                            :width 46
                            :background "cornsilk"))))
```

Does it show the icon with expected background?

**Comment by grolongo** [comment]
>Does it show the icon with expected background?  

Looks like it doesn't. It should be a light yellow `#FFF8DC`, but turns out it is light blue in my case.

![cornsilk-test](https://user-images.githubusercontent.com/34292770/211843316-c02cab56-de94-49f5-8739-b420c18c79f4.png)

I deleted the icon and re-evaluated after enabling `wheatgrass` and I have the same light blue color:  

![cornsilk-test2](https://user-images.githubusercontent.com/34292770/211844066-d47ece00-3add-4a50-b410-87805f3e4e1b.png)

**Comment by dgutov** [comment]
I could imagine how a custom theme could get the definition wrong, but it should still work with the default one.

Could you try this patch, perhaps?

```diff
diff --git a/company.el b/company.el
index af056eb..38106ea 100644
--- a/company.el
+++ b/company.el
@@ -1608,7 +1608,8 @@ end of the match."
       (let* ((bkg (face-attribute (if selected
                                       'company-tooltip-selection
                                     'company-tooltip)
-                                  :background))
+                                  :background
+                                  nil t))
              (dfw (default-font-width))
              (icon-size (cond
                          ((integerp company-icon-size)

```

**Comment by grolongo** [comment]
I just tried and no luck unfortunately.

**Comment by dgutov** [comment]
If you're still seeing the problem, could you report it upstream with `M-x report-emacs-bug`?

Describing the usage scenario and saying that it looks different on GNU/Linux and macOS should be enough of a proof.

**Comment by dgutov** [comment]
And/or the aforementioned snippet and the resulting screenshots.

**Comment by grolongo** [comment]
Sorry for the delay, I will send a report.
