### ISSUE TITLE
company popup disappears unexpectly.

### ISSUE THREAD

**Issue by zylthinking** [company-mode/company-mode#1363]
For example

```c++
vector<int> v;
v.push_back(1);
```

after type **v.**,  candidate popup appears.
I can select push_back by up/down key
But, if I type **p**, the popup disappears. 
It appears again after I type **us**
this time, it appears even I continue typing "_back".

I just wan't to know why it disappear after the first letter following **.**
And how to prevent the disappearing.

The backend is capf.
Another backend clang does not disappear.

configuration:
```
(use-package company
  :ensure
   :init (setq company-backends '(company-capf))
  :custom
  (company-idle-delay 0.5)
  :bind
  (:map company-active-map
        ("C-n". company-select-next)
        ("C-p". company-select-previous)
        ("M-<". company-select-first)
        ("M->". company-select-last))
  :config
   (setq lsp-completion-provider :capf)
  )

(use-package ccls
    :ensure t
    :config
    (setq ccls-executable "/usr/bin/ccls")
    (setq lsp-prefer-flymake nil)
    (setq-default flycheck-disabled-checkers '(c/c++-clang c/c++-cppcheck c/c++-gcc))
    :hook ((c-mode c++-mode) .
	       (lambda () (require 'ccls) (lsp))))


```

**Comment by dgutov** [comment]
Since it works with one backend but not with another, it's a good idea to direct to question to the authors of the latter backend first.

Please post this bug report to the lsp-mode issue tracker.
