### ISSUE TITLE
Cursor appears at the end of completion ghost text when completion is multiline

### ISSUE THREAD

**Issue by Alan-Chen99** [company-mode/company-mode#1367]
```
(defun test-completion-at-point ()
    (list (1- (point)) (point) (list "a\n abcde")))
(setq completion-at-point-functions '(test-completion-at-point))
(setq company-frontends '(company-preview-frontend))
(setq company-backends '(company-capf))
(setq company-minimum-prefix-length 1)
```
Then if you type a, company does not persist cursor position.

**Comment by dgutov** [comment]
Hi! This looks a little tricky: apparently the use of `cursor` text property on an overlay doesn't work too well when the character it's on is a newline.

Solution could be to either report that to the core and investigate the reasons and/or replace the newline character in the previews with something else. `\`, for example.

Do you often have completions with newlines in them? They are pretty unusual.

**Comment by Alan-Chen99** [comment]
I am writing a client for codeium, which is AI based cloud service, so often you would have a newline (with indent on the next line). I don't think replacing with a \ would be viable.

Is the overlay placed on the previous character?

**Comment by Alan-Chen99** [comment]
(would it work if overlay is on the next character instead?)

**Comment by dgutov** [comment]
The whole replacement text (of what's made to look different in the buffer) is one overlay.

Inserting an extra space before newline might do the trick. Except if the current cursor is at the rightmost buffer position, that could cause additional unwanted wrapping. The extra space is also apparent to the user:

```diff
diff --git a/company.el b/company.el
index 11f8b06..0ba32da 100644
--- a/company.el
+++ b/company.el
@@ -3741,6 +3744,9 @@ Delay is determined by `company-tooltip-idle-delay'."
                          (company-strip-prefix completion)
                        completion))
 
+    (when (string-prefix-p "\n" completion)
+      (setq completion (concat " " completion)))
+
     (and (equal pos (point))
          (not (equal completion ""))
          (add-text-properties 0 1 '(cursor 1) completion))

```

**Comment by dgutov** [comment]
So... Codeium? Are you going to only use the preview frontend with it? Not the menu one?

**Comment by Alan-Chen99** [comment]
I find that often its easier to see on the preview. 
example:
![image](https://user-images.githubusercontent.com/51056554/217417079-1840e63c-9fd0-42eb-8323-22b380ce90df.png)

**Comment by Alan-Chen99** [comment]
I suppose it would be even better if the space is with the preview face and the newline without

**Comment by Alan-Chen99** [comment]
the only problem being that the space is capable of causing a wrap but that should be rare enough that it doesn't matter

**Comment by Alan-Chen99** [comment]
Anyways, I'll also report this to core

**Comment by dgutov** [comment]
Thanks. Now it seems the fix isn't coming anytime soon, at least: https://debbugs.gnu.org/cgi/bugreport.cgi?bug=61361

Now frequent is the issue in question, BTW? If it only happens once in a blue moon, we could chalk this up as "nice to have".

Anyway, here's the updated patch:

```diff
diff --git a/company.el b/company.el
index 11f8b06..9032f0d 100644
--- a/company.el
+++ b/company.el
@@ -3741,6 +3744,10 @@ Delay is determined by `company-tooltip-idle-delay'."
                          (company-strip-prefix completion)
                        completion))
 
+    (when (string-prefix-p "\n" completion)
+      (setq completion (concat (propertize " " 'face 'company-preview) "\n"
+                               (substring completion 1))))
+
     (and (equal pos (point))
          (not (equal completion ""))
          (add-text-properties 0 1 '(cursor 1) completion))
```

If this incident is rare enough, and typing at the edge of the window is rare too, perhaps an intersection of these conditions is indeed nothing to worry about.

**Comment by Alan-Chen99** [comment]
In my experience, the incident is frequent but pretty sure typing at the edge is very rare. Thanks for the patch!

**Comment by dgutov** [comment]
Thanks for testing, I've pushed the patch now.
