### ISSUE TITLE
The cursor jumps to the end of file when the drop-down menu hits the right margin

### ISSUE THREAD

**Issue by ywangmy** [company-mode/company-mode#1373]
**Please make sure to search in [existing issues](https://github.com/company-mode/company-mode/issues?q=) before filing a new report!**

[Feel free to remove pre-filled text **after** reading it.]

#### Output of the command `M-x company-diag`
```
Emacs 28.2 (aarch64-apple-darwin22.2.0) of 2023-02-13 on mac.local
Company 0.9.13

company-backends: (company-bbdb company-semantic company-cmake company-capf company-clang company-files
              (company-dabbrev-code company-gtags company-etags company-keywords)
              company-oddmuse company-dabbrev)

Used backend: company-dabbrev
Major mode: text-mode
Prefix: ""
Completions:
  "dist"
  "distribution"
  "distribution"
  "distribution"
  "distribution"
  "distribution"
  "distribution"
  "distort"
  "disturb"
  "distant"
  "distance"
```

#### Describe the issue

When the menu hit the right margin and I continue to type, the cursor jumps to the end of the file (if there is a few characters).
![bug](https://user-images.githubusercontent.com/90024054/219932488-a1ac779c-fbef-46d2-8aa4-64760cbf85c0.gif)

#### Steps to reproduce
List the steps to reproduce the behavior. Ideally starting with a bare Emacs session: `emacs -Q` (if you can).

1. Create a file with the following contents
```
distance
distant
disturb
distort
distribution distribution distribution distribution distribution distribution 

end
end
end
```
2. Do the same staff as shown in the gif above.

#### Expected behavior

The cursor should not jump elsewhere.

**Comment by dgutov** [comment]
Cannot reproduce.

But that's not a scenario starting with `emacs -Q`: by default Emacs does not show line numbers (which we see on the left), nor does company-mode by default uses numbers beside completions. And any such setting may affect this behavior. I couldn't reproduce the problem even after enabling both features, though.

Please provide the full reproduction scenario starting with `emacs -Q`.

**Comment by ywangmy** [comment]
ok. I found that it is a `whitespace-mode` issue.

<img width="623" alt="Screenshot 2023-02-20 at 09 38 01" src="https://user-images.githubusercontent.com/90024054/219990137-05c7677f-ea98-4e06-9408-5457043f8113.png">

I configured `whitespace-mode` to display newline characters. And the character is also displayed after each candidate line, somehow pushing the cursor to the end. 

Thanks.

**Comment by stardiviner** [comment]
company-mode might need to detect `whitespace-mode` and disable it in candidates.

**Comment by dgutov** [comment]
That doesn't seem easy to do.

People can try `company-posframe`, which switches to a child frame for rendering the popup.

**Comment by stardiviner** [comment]
Thanks for suggestion. `company-posframe` seems a good idea.
