### ISSUE TITLE
Documentation popup

### ISSUE THREAD

**Issue by expez** [company-mode/company-mode#138]
In #68 the possibility of a documentation popup, like the one found in AC, was discussed briefly.  A few months ago I attempted to implement this myself using pos-tip, but came up short.  IIRC one of the issues I ran into was that I couldn't change the background color of the popup to match the user's color theme.

Since I started using company I've tried to get several people to switch, but many won't do so precisely because they really like the documentation popup in AC. 

Even though the use of pos-tip would make this a third-party package, would you be willing to write it?  As an aside, it's surprising that Emacs proper doesn't have a library like pos-tip already.

**Comment by expez** [comment]
I've uploaded the [company-quickhelp](https://github.com/expez/company-quickhelp) package to `melpa`.  It's working well enough that I'm now using it in my day to work without it pissing me off.

It's my hope that it might eventually find a home in this fine organization where its visibility would be increased (and I wouldn't have to fix the bugs!).

**Comment by dgutov** [comment]
> in this fine organization where its visibility would be increased

Now that the package is in MELPA, I'm pretty sure the only way its visibility can be higher is if it somehow finds its way to GNU ELPA.

**Comment by zhihuiFan** [comment]
will company-mode use pos-up or other package which depends on a GUI in future?  I tried company-quickhelp and since it use pos-up,  so it can't work with NON-GUI system. 

BTW, I see this issue was closed with a label "wishlist",  how can I track this feature in future? 

Thanks

**Comment by dgutov** [comment]
@zhihuiFan Feel free to open a new issue (Documentation popup in non-GUI Emacs), but I have no idea when, or if, that would be implemented.

Maybe adding this feature request to `company-quickhelp` would be a better idea, but that's no really doable there either, until we have a Company-compatible overlay-based popup implementation that can display several popups at once.
