### ISSUE TITLE
company-capf broken in nxml-mode

### ISSUE THREAD

**Issue by viliaapro** [company-mode/company-mode#1386]
Hi,

I'm getting an error on Emacs 29.0.90 using Company 20230416.2034 from Melpa.
Company 0.9.13 from Gnu Elpa is working fine.

In Nxml-mode, completing an XML element gives the following error message:

`Company: An error occurred in post-command
Company: frontend company-pseudo-tooltip-unless-just-one-frontend error "Company: backend company-capf error "Wrong number of arguments: (0 . 0), 1" with args (kind table)" on command post-command
`

Here the `(kind table)` is for a Table element and is just an example.

**Comment by viliaapro** [comment]
Debugger entered--Lisp error: (wrong-number-of-arguments (0 . 0) 1)
  #f(compiled-function () #<bytecode 0x198003290b75>)(#("table" 0 1 (face (completions-common-part)) 1 2 (face (completions-first-difference))))
  company-capf(kind #("table" 0 1 (face (completions-common-part)) 1 2 (face (completions-first-difference))))
  apply(company-capf (kind #("table" 0 1 (face (completions-common-part)) 1 2 (face (completions-first-difference)))))
  company-call-backend-raw(kind #("table" 0 1 (face (completions-common-part)) 1 2 (face (completions-first-difference))))
  apply(company-call-backend-raw (kind #("table" 0 1 (face (completions-common-part)) 1 2 (face (completions-first-difference)))))
  company--force-sync(company-call-backend-raw (kind #("table" 0 1 (face (completions-common-part)) 1 2 (face (completions-first-difference)))) company-capf)
  company-call-backend(kind #("table" 0 1 (face (completions-common-part)) 1 2 (face (completions-first-difference))))
  company--render-icons-margin(((array . "symbol-array.svg") (boolean . "symbol-boolean.svg") (class . "symbol-class.svg") (color . "symbol-color.svg") (constant . "symbol-constant.svg") (constructor . "symbol-method.svg") (enum-member . "symbol-enumerator-member.svg") (enum . "symbol-enumerator.svg") (event . "symbol-event.svg") (field . "symbol-field.svg") (file . "symbol-file.svg") (folder . "folder.svg") (interface . "symbol-interface.svg") (keyword . "symbol-keyword.svg") (method . "symbol-method.svg") (function . "symbol-method.svg") (module . "symbol-namespace.svg") (numeric . "symbol-numeric.svg") (operator . "symbol-operator.svg") (property . "symbol-property.svg") (reference . "references.svg") (snippet . "symbol-snippet.svg") (string . "symbol-string.svg") (struct . "symbol-structure.svg") (text . "symbol-key.svg") (type-parameter . "symbol-parameter.svg") (unit . "symbol-ruler.svg") (value . "symbol-enumerator.svg") (variable . "symbol-variable.svg") (t . "symbol-misc.svg")) "/home/vilij/.emacs.d/elpa/company-20230416.2034/ic..." #("table" 0 1 (face (completions-common-part)) 1 2 (face (completions-first-difference))) t)
  company-vscode-light-icons-margin(#("table" 0 1 (face (completions-common-part)) 1 2 (face (completions-first-difference))) t)
  company-detect-icons-margin(#("table" 0 1 (face (completions-common-part)) 1 2 (face (completions-first-difference))) t)
  company--create-lines(0 10)
  company-pseudo-tooltip-show(2 5 0)
  company-pseudo-tooltip-show-at-point(142 1)
  company-pseudo-tooltip-frontend(post-command)
  company-pseudo-tooltip-unless-just-one-frontend(post-command)
  company-call-frontends(post-command)
  company-post-command()

**Comment by dgutov** [comment]
All right.

Could you try applying this patch to Emacs?

```diff
diff --git a/lisp/nxml/rng-nxml.el b/lisp/nxml/rng-nxml.el
index 568cf24451b..fd1f4fb904e 100644
--- a/lisp/nxml/rng-nxml.el
+++ b/lisp/nxml/rng-nxml.el
@@ -180,7 +180,7 @@ rng-complete-tag
                    (insert " "))))
               ((member completion extra-strings)
                (insert ">"))))
-          :company-kind ,(lambda () 'property))))))
+          :company-kind ,(lambda (_) 'property))))))
 
 (defconst rng-in-end-tag-name-regex
   (replace-regexp-in-string
```

**Comment by viliaapro** [comment]
I applied the patch, and still get an error.

Debugger entered--Lisp error: (wrong-number-of-arguments (0 . 0) 1)
  #f(compiled-function () #<bytecode 0x198007ed5b15>)(#("table" 0 1 (face (completions-common-part)) 1 2 (face (completions-first-difference))))
  company-capf(kind #("table" 0 1 (face (completions-common-part)) 1 2 (face (completions-first-difference))))
  apply(company-capf (kind #("table" 0 1 (face (completions-common-part)) 1 2 (face (completions-first-difference)))))
  company-call-backend-raw(kind #("table" 0 1 (face (completions-common-part)) 1 2 (face (completions-first-difference))))
  apply(company-call-backend-raw (kind #("table" 0 1 (face (completions-common-part)) 1 2 (face (completions-first-difference)))))
  company--force-sync(company-call-backend-raw (kind #("table" 0 1 (face (completions-common-part)) 1 2 (face (completions-first-difference)))) company-capf)
  company-call-backend(kind #("table" 0 1 (face (completions-common-part)) 1 2 (face (completions-first-difference))))
  company--render-icons-margin(((array . "symbol-array.svg") (boolean . "symbol-boolean.svg") (class . "symbol-class.svg") (color . "symbol-color.svg") (constant . "symbol-constant.svg") (constructor . "symbol-method.svg") (enum-member . "symbol-enumerator-member.svg") (enum . "symbol-enumerator.svg") (event . "symbol-event.svg") (field . "symbol-field.svg") (file . "symbol-file.svg") (folder . "folder.svg") (interface . "symbol-interface.svg") (keyword . "symbol-keyword.svg") (method . "symbol-method.svg") (function . "symbol-method.svg") (module . "symbol-namespace.svg") (numeric . "symbol-numeric.svg") (operator . "symbol-operator.svg") (property . "symbol-property.svg") (reference . "references.svg") (snippet . "symbol-snippet.svg") (string . "symbol-string.svg") (struct . "symbol-structure.svg") (text . "symbol-key.svg") (type-parameter . "symbol-parameter.svg") (unit . "symbol-ruler.svg") (value . "symbol-enumerator.svg") (variable . "symbol-variable.svg") (t . "symbol-misc.svg")) "/home/vilij/.emacs.d/elpa/company-20230416.2034/ic..." #("table" 0 1 (face (completions-common-part)) 1 2 (face (completions-first-difference))) t)
  company-vscode-light-icons-margin(#("table" 0 1 (face (completions-common-part)) 1 2 (face (completions-first-difference))) t)
  company-detect-icons-margin(#("table" 0 1 (face (completions-common-part)) 1 2 (face (completions-first-difference))) t)
  company--create-lines(0 9)
  company-pseudo-tooltip-show(7 5 0)
  company-pseudo-tooltip-show-at-point(142 1)
  company-pseudo-tooltip-frontend(post-command)
  company-pseudo-tooltip-unless-just-one-frontend(post-command)
  company-call-frontends(post-command)
  company-post-command()
  company-idle-begin(#<buffer paska.xml> #<window 6 on paska.xml> 2778 142)
  apply(company-idle-begin (#<buffer paska.xml> #<window 6 on paska.xml> 2778 142))
  timer-event-handler([t 25682 46855 389588 nil company-idle-begin (#<buffer paska.xml> #<window 6 on paska.xml> 2778 142) nil 123000 nil])

**Comment by viliaapro** [comment]
It works, thanks!

At first I forgot to restart the Emacs server.

**Comment by dgutov** [comment]
Excellent! Thanks for testing.

I have now pushed the fix to the `emacs-29` branch: https://git.savannah.gnu.org/cgit/emacs.git/commit/?h=emacs-29&id=cc090294d77c5d4047607d3234c304aaa1b0489c
