### ISSUE TITLE
The `company` candidates pop-up menu quits unexpectedly when typing ↓

### ISSUE THREAD

**Issue by ywwry66** [company-mode/company-mode#1396]
**Please make sure to search in [existing issues](https://github.com/company-mode/company-mode/issues?q=) before filing a new report!**

[Feel free to remove pre-filled text **after** reading it.]

#### Output of the command `M-x company-diag`
```
Used backend: company-capf
Value of c-a-p-f: (elisp-completion-at-point t)
```

#### Describe the issue
The `company` candidates pop-up menu quits unexpectedly when typing <kbd>↓</kbd>.

This happens when I have the following hook in `init.el`:
```elisp
(add-hook 'after-change-major-mode-hook
	    (lambda ()
	      (when buffer-read-only
		(company-mode -1))))
```
I use this hook along with `global-company-mode` to always turn on `company-mode` except for read-only buffers. This has been working very well for a long time and I recently noticed that it has caused this issue. Might be after the Emacs 29.1 update.

#### Steps to reproduce
1. run `emacs -q`
2. execute the following elisp code in `*scratch*` buffer:
```elisp
(require 'package)
(package-initialize)
(require 'company)
(add-hook 'after-change-major-mode-hook
	    (lambda ()
	      (when buffer-read-only
		(company-mode -1))))
(company-mode)
```
3. In a new line, enter the following keystrokes in the `*scratch*` buffer: <kbd>(</kbd><kbd>)</kbd><kbd>←</kbd><kbd>s</kbd><kbd>e</kbd><kbd>t</kbd><kbd>q</kbd><kbd>Space</kbd><kbd>c</kbd><kbd>o</kbd><kbd>m</kbd>
4. The `company` candidates pop-up menu should appear
5. Type <kbd>↓</kbd>

Outcome: the pop-up menu is gone, the point moves over the right parenthesis.

#### Expected behavior
The second candidate in the pop-up menu is chosen

#### The error backtrace
NA

#### Screenshots
NA

#### Additional context
Emacs 29.1
macOS 13.5
company 20230703.2021

**Comment by dgutov** [comment]
Hi!

> This happens when I have the following hook in init.el

Are you saying that, if you remove this hook from the init (or comment it out) and restart, the problem goes away?

**Comment by ywwry66** [comment]
> Are you saying that, if you remove this hook from the init (or comment it out) and restart, the problem goes away?

Yes exactly. But I really can't see how adding such a hook can interfere with `company`'s normal operation.

**Comment by ywwry66** [comment]
I just did some more testing. With `company` 0.9.13 and Emacs 28.2, I don't have this bug. Once I upgrade Emacs to 29.1, I can reproduce it every time.

**Comment by dgutov** [comment]
Curious bug. This seems to happen when Eldoc is triggered, it creates a temporary buffer and applies a major mode change in it, and calls `(company-mode -1)` thanks to your hook. Which does some global keymap manipulation, possibly causing this behavior. `eldoc-mode` has seen some changes in its implementation in Emacs 29, and this is one of the side-effects.

So, this does look like a bug, but fixing it might take some effort.

Why do you use this hook, though? When a buffer is read-only, you won't see any completion popups in it anyway because you are not typing.

Another way to work around the problem is to check whether the buffer is visiting a file, meaning the condition will look like:

```el
(and buffer-file-name buffer-read-only)
```

**Comment by ywwry66** [comment]
Thanks for taking the time to investigate the issue. It now makes sense to me as you pointed out the change to `eldoc-mode`.

> Why do you use this hook

Originally I added the hook to make mode line clean (only learned `diminish` later), and also to prevent potential hypothetical conflict with other packages. Then the code has been in my `init.el` ever since.

But you are right, I might just delete the hook as it really does not matter that much. I will leave it to you whether it is worth the effect to fix the unintended keymap change, so feel free to close the issue as you wish.

**Comment by dgutov** [comment]
Let's keep it open; maybe I'll find some elegant solution sooner or later, and/or somebody chimes in with more annoying cases which would bump up the priority.

**Comment by dgutov** [comment]
@ywwry66 Hi again!

Please try this out:

```diff
diff --git a/company.el b/company.el
index 43e236f..6249499 100644
--- a/company.el
+++ b/company.el
@@ -1044,10 +1044,10 @@ means that `company-mode' is always turned on except in `message-mode' buffers."
 (defun company-install-map ()
   (unless (or (cdar company-emulation-alist)
               (null company-my-keymap))
-    (setf (cdar company-emulation-alist) company-my-keymap)))
+    (setq-local company-emulation-alist `((t . ,company-my-keymap)))))
 
 (defun company-uninstall-map ()
-  (setf (cdar company-emulation-alist) nil))
+  (kill-local-variable 'company-emulation-alist))
 
 (defun company--company-command-p (keys)
   "Checks if the keys are part of company's overriding keymap"
```

**Comment by ywwry66** [comment]
Thanks, I can confirm it fixes the minimal reproducible example in the bug report👍🏻. But I haven't tested extensively yet.

BTW the patch looks much shorter than I expected.

**Comment by dgutov** [comment]
Thanks for checking. The change is indeed small (the best kind of change), but the effects could be far-reaching.

It does seem like it could be the more correct approach, so I'm going to push this (after a day of testing here, too) and see if anybody reports new and exciting new bugs because of it. ;-(
