### ISSUE TITLE
Emacs company-mode doesn't work correctly

### ISSUE THREAD

**Issue by yuchunzhou** [company-mode/company-mode#1397]
the detail is here: https://github.com/emacs-lsp/lsp-java/issues/449

**Comment by dgutov** [comment]
Let's wait for what the lsp-mode folks say.

**Comment by yuchunzhou** [comment]
> Let's wait for what the lsp-mode folks say.

okay

**Comment by yuchunzhou** [comment]
The newer version jdtls has fixed this problem, so i close this issue, thanks @dgutov.
