### ISSUE TITLE
candidates are automatically lowercased

### ISSUE THREAD

**Issue by redguardtoo** [company-mode/company-mode#14]
Say there is a candidate MyVariableName,
When the candidate window popup, the MyVariableName is displayed as "Myvariablename".

**Comment by sambrightman** [comment]
Is manually adding modes to `company-dabbrev-code-modes` the intended setup? Should third-party packages automatically add themselves to either this or `company-backends`?

**Comment by dgutov** [comment]
> Should third-party packages automatically add themselves to either this

They might, although a major mode should usually just inherit from `prog-mode`.

> or company-backends?

That's better left to the user.

**Comment by torgeir** [comment]
I hit this with `company-mode` when in `web-mode`. 

For the record, going `(add-to-list 'company-dabbrev-code-modes 'web-mode)` as per @eethann's suggestion fixes it.

**Comment by ntc2** [comment]
I had this problem with lowercased completions **in comments** in Haskell source code using Intero and fixed it by adding
```elisp
(setq-local company-dabbrev-downcase nil)
```
to my `haskell-mode-hook`.

**Comment by dgellow** [comment]
@ntc2 Oh, thank you. That fixes an issue I have since a long time with strings and comments in almost every programming modes!

**Comment by FabriceSalvaire** [comment]
I also encountered this issue with Markdown mode, where C++ camel case is altered.
