### ISSUE TITLE
Fails on Emacs 29 with `(void-function modifier)`

### ISSUE THREAD

**Issue by vemv** [company-mode/company-mode#1400]
`company-20230703.2021` is failing for me on Emacs 29 (vanilla, latest from https://emacsformacosx.com/) at load time because of the following condition:

<img width="1344" alt="image" src="https://github.com/company-mode/company-mode/assets/1162994/7da7424f-f993-4e73-97a5-b163a78e2472">

I wasn't able to repair this defun, other that by voiding it.

My `company-quick-access-modifier` has not been customized.

Would be happy to help with any info you may need.

Thanks - V

**Comment by vemv** [comment]
The issue is that one is using `if-let ((modifier` instead of `if-let (modifier`.

I found the same issue in e.g. CIDER.

**Comment by dgutov** [comment]
Are you quite sure? In Emacs 29, the below evaluates fine for me:

```el
(if-let ((a 1)) a)
```

**Comment by dgutov** [comment]
Its docstring mentions the case of a single element as a special case:

> As a special case, interprets a SPEC of the form (SYMBOL SOMETHING)
like ((SYMBOL SOMETHING)).  This exists for backward compatibility
with an old syntax that accepted only one binding.

**Comment by vemv** [comment]
Thanks for the healthy questioning. It turns out, I had an `if-let` definition in my .emacs.d. It hadn't given a problem to me in over a decade, so I had forgotten about its existence!
