### ISSUE TITLE
The completion popup gets closed if I scroll a buffer created via `:company-doc-buffer`

### ISSUE THREAD

**Issue by vemv** [company-mode/company-mode#1409]
#### Output of the command `M-x company-diag`

<details>

```
Emacs 27.2 (x86_64-apple-darwin20.6.0) of 2023-09-26 on vemvs-MacBook-Pro.local
Company 0.10.1

company-backends: (company-robe company-bbdb company-semantic company-cmake company-capf company-clang company-files company-oddmuse company-dabbrev)

Used backend: company-capf
Value of c-a-p-f: (cider-complete-at-point t)
Major mode: clojure-mode
Prefix: stop
Completions: none
```

</details>

#### Describe the issue

If I scroll a buffer created via `:company-doc-buffer` (e.g. because it may be quite long), the completion popup gets closed.

This didn't happen, a few commits ago.

#### Steps to reproduce

Can be provided on request

#### Expected behavior

I can scroll without the completion popup being closed.

#### Screenshots

A gif can be provided on request

Thanks - V

**Comment by dgutov** [comment]
Thanks for the report, this should do it.

**Comment by vemv** [comment]
Thanks much!
