### ISSUE TITLE
No result returned after success executon from ELisp.

### ISSUE THREAD

**Issue by Anoncheg1** [company-mode/company-mode#1410]
M-: (eval (company-complete))

result always nil !!!

M-: (eval (expand-abbrev))

result is "" if success or nil if failure.

#### Output of the command `M-x company-diag`
Emacs 28.2 (x86_64-pc-linux-gnu) of 2023-07-25 on host
Company 0.10.2

company-backends: (company-abbrev company-capf company-keywords company-files company-dabbrev)

Used backend: company-dabbrev
Major mode: org-mode
Prefix: nil
Completions: none

**Comment by dgutov** [comment]
It returns nil when there was nothing to complete, or there was a sole completion that was inserted.

When there are more completions, it returns a symbol.

Do you want to be able to distinguish between the first two cases?

**Comment by Anoncheg1** [comment]
of course I need to know if completion was success. I don't need and I don't know why it may be required to know if there is more that 1 completion was proposed.

**Comment by dgutov** [comment]
Ok, this should satisfy the above requirements.
