### ISSUE TITLE
Conflict between LSP and Yasnippet completion candidates

### ISSUE THREAD

**Issue by david-alvarez-rosa** [company-mode/company-mode#1418]
Whenever I'm using LSP mode for C++ (with `clang`) I'm loosing Yasnippet completion (they are not appearing as completion candidates on the list).

Printing the value of `company-backends` I have the following—

```elisp
Value:
(company-restclient company-bbdb company-semantic company-cmake company-capf company-clang company-files
                    (company-dabbrev-code company-gtags company-etags company-keywords)
                    company-oddmuse company-dabbrev)
Original value was 
(company-bbdb company-semantic company-cmake company-capf company-clang company-files
              (company-dabbrev-code company-gtags company-etags company-keywords)
              company-oddmuse company-dabbrev)
```

I saw that `company-yasnippet` backend was not listed there—hence I added it

```elisp
(add-to-list 'company-backends 'company-yasnippet)
```

however, when doing this I have the exact opposite problem—now LSP completion candidates are missing :(

**Comment by david-alvarez-rosa** [comment]
Happy to provide more context if needed. Thank you in advance!

**Comment by dgutov** [comment]
Hi!

Check this out: https://github.com/company-mode/company-mode/discussions/1249

In short, though, you can do `(add-to-list 'company-backends '(company-capf company-yasnippet))`

**Comment by david-alvarez-rosa** [comment]
Thank you @dgutov—that works indeed!
