### ISSUE TITLE
company-capf does not pass control to the next back-end

### ISSUE THREAD

**Issue by luciferasm** [company-mode/company-mode#142]
**Version:**
0.8.1-cvs (downloaded from MELPA as folder called "company-20140609.753")

**To reproduce bug (in terminal):**

> emacs -Q -nw
> (package-initialize)
> (require 'company)
> (global-company-mode)
> foobarqux
> foob<- point here

**Expected result:**
foobarqux should be offered as the only candidate.

**Actual result:**
No candidates are offered.

**Speculation of why:**
`company-backends` has entry `company-capf` in the middle, and ends with entry `company-dabbrev`. `company-capf` is apparently working, since it offers the candidates "footnote" and "footnote-mode <f>" when typing "foo". But when typing a "b" after "foo" in the effort to expand to "foobarqux" in the example above, `company-capf` does not seem to pass control to the next back-end though. In this case it should fall through several back-ends until finally reaching `company-dabbrev`, that could successfully take care of the desired expansion.

At closer inspection, the responsible code could maybe be found in the `company-capf`'s prefix clause, and specifically in the behavior of `company--capf-data`. `company-capf`'s prefix clause asks `company--capf-data` if there are any candidates. `company--capf-data` should return nil in our case, which would then pass control to the next back-end. But it seems like `company--capf-data` only return nil after characters that does not belong to the word or symbol constituent syntax classes. To illustrate, evaluate:

> (global-set-key [(f5)] (lambda () (interactive) (message "%s" (company--capf-data))))

When pressing f5 after any word or symbol, it returns a long list (i.e. a truthy value). It only returns nil after e.g. ; or a blank line.

**Comment by Wilfred** [comment]
For what it's worth, I've created [company-try-hard](https://github.com/Wilfred/company-try-hard) to explore this idea. This enables you to exhaustively try each backend for candidates.

**Comment by dgutov** [comment]
@Wilfred That's terrific. I'm glad you were able to implement it with not too much effort.

**Comment by NightMachinary** [comment]
> For what it's worth, I've created [company-try-hard](https://github.com/Wilfred/company-try-hard) to explore this idea. This enables you to exhaustively try each backend for candidates.

It seems this still doesn't work when the first backends encounter an error?

**Comment by dgutov** [comment]
@NightMachinary Do you mean encounters a bug? Backends are not supposed to signal errors.

**Comment by NightMachinary** [comment]
[**@dgutov**](https://github.com/dgutov) commented on [Mar 24, 2021, 3:13 PM GMT+4:30](https://github.com/company-mode/company-mode/issues/142#issuecomment-805709140 "2021-03-24T10:43:46Z - Replied by Github Reply Comments"):
> [@NightMachinary](https://github.com/NightMachinary) Do you mean encounters a bug? Backends are not supposed to signal errors.

Yes, bugs. I do not want bugs to completely break even `dabbrev`.

**Comment by dgutov** [comment]
If you see a bug, you should report it to be fixed. It would be bad if `company-try-hard` silently swallowed such issues.

**Comment by NightMachinary** [comment]
[**@dgutov**](https://github.com/dgutov) commented on [Mar 24, 2021, 3:42 PM GMT+4:30](https://github.com/company-mode/company-mode/issues/142#issuecomment-805735876 "2021-03-24T11:12:01Z - Replied by Github Reply Comments"):
> If you see a bug, you should report it to be fixed. It would be bad if `company-try-hard` silently swallowed such issues.

That is a long-term solution. I need my text editor to work all the time, and not be blocked by random bugs. There is no need to make simple things complex. A failed completion is not going to explode a nuclear reactor.

"Just working" is a very valuable feature. I am already spending more time than I am comfortable with on fixing my emacs setup ...

**Comment by dgutov** [comment]
Admittedly, this approach is workable only if such bugs are rare. But that is already the case, to my knowledge.
