### ISSUE TITLE
regression with pseudo-tooltip in dedicated windows

### ISSUE THREAD

**Issue by bymoz089** [company-mode/company-mode#1431]
#### Describe the issue
company does not display its tooltip in dedicated windows. It worked in previous versions.

exact message:             

    Company: An error occurred in post-command
    Company: frontend company-pseudo-tooltip-unless-just-one-frontend error "Window is dedicated to ‘*scratch*’" on command post-command

#### Steps to reproduce

 1. start emacs v29.1 with `emacs -Q`
 2. load all company elisp files (i.e. from dired with `L`)
 3. make a buffer dedicated (in this example I used `*scratch*`) via ` (set-window-dedicated-p (selected-window) t)`
 4. enable `company-mode`
 5. try to complete something from within the dedicated buffer via `company-complete`
 6. the error appears in the echo line and no tooltip for completion is popped up

#### Expected behavior

popup with completion candidates should also appear in dedicated buffers

#### Additional context
The regression came with one of this months commits as of 2023-nov-17. (sorry I really suck at git and therefore I am unable to revert commits in order to find the problematic commit)

**Comment by dgutov** [comment]
Thanks for the report, I can pretty much guess where the problem is. Will look into it.
