### ISSUE TITLE
Autocomplete error: "Args out of range: 0, -1"

### ISSUE THREAD

**Issue by DavidVujic** [company-mode/company-mode#1434]
#### Describe the issue
I get this error when about to auto-complete Python code:

```
Company: An error occurred in post-command
Company: frontend company-pseudo-tooltip-unless-just-one-frontend error "Args out of range: 0, -1" on command post-command
```

#### Steps to reproduce
Starting Emacs, with Python packages such as `elpy` and `company-jedi`.

Recently, when updating the packages (or, when clearing out the `.emacs.d` folder and restart to install all packages) I noticed the error above when writing Python code. It might be an issue for other languages too, I haven't yet checked that.

#### Expected behavior
Being able to autocomplete, and without the error message.

#### The error backtrace
```
Debugger entered--Lisp error: (args-out-of-range 0 -1)
  text-property-any(0 -1 emojified t "")
  ad-Advice-company-pseudo-tooltip-unhide(#f(compiled-function () #<bytecode -0xdce4cabdd229421>))
  apply(ad-Advice-company-pseudo-tooltip-unhide #f(compiled-function () #<bytecode -0xdce4cabdd229421>) nil)
  company-pseudo-tooltip-unhide()
  company-pseudo-tooltip-frontend(post-command)
  company-pseudo-tooltip-unless-just-one-frontend(post-command)
  company-call-frontends(post-command)
  company-post-command()
  company-idle-begin(#<buffer david.py> #<window 3 on david.py> 47 138)
  apply(company-idle-begin (#<buffer david.py> #<window 3 on david.py> 47 138))
  timer-event-handler([t 25954 21098 381020 nil company-idle-begin (#<buffer david.py> #<window 3 on david.py> 47 138) nil 0 nil])

```

#### Additional context
My temporary solution to get the auto-complete back again is:
- downloading a previous version (0.9.13) from elpa
- unzip it
- run `package-install-file` and select company.el.

When looking into my .emacs.d/elpa folder, there are two versions of company there (the latest 0.10.2, and the one manually installed with only a few files in it). When I restart emacs, it will load the latest version (I think). But running the install-file will re-enable the lost auto complete again :smile:

I have not done that much package install before, other than specifying the things I want in my init.el file. There’s probably a much better way than my manual approach but I can do that as a workaround.

**Comment by dgutov** [comment]
Hi!

According to the backtrace, there is some advice on `company-pseudo-tooltip-unhide`. Could you find out which one it is, and where it is from?

The list of advices should be at the end of the function's Help buffer. `C-h f company-pseudo-tooltip-unhide RET` to show it.

**Comment by DavidVujic** [comment]
When running the help buffer:

```
company-pseudo-tooltip-unhide is a byte-compiled Lisp function in
‘company.el’.

(company-pseudo-tooltip-unhide)


This function has :around advice: ‘ad-Advice-company-pseudo-tooltip-unhide’.
```

clicking on the advice link:
```
ad-Advice-company-pseudo-tooltip-unhide is a byte-compiled Lisp
function.

(ad-Advice-company-pseudo-tooltip-unhide AD--ADDOIT-FUNCTION &rest
IGNORED)

After-advice ‘emojify-display-emojis-in-company-tooltip’:
Advice to display emojis in company mode tooltips.

This function does two things, first it adds text properties to the completion
tooltip to make it display the emojis, secondly it makes company always render
the completion tooltip using ‘after-string’ overlay property rather than
‘display’ text property.

The second step is needed because emojify displays the emojis using ‘display’
text property, similarly company-mode in some cases uses ‘display’ overlay
property to render its pop, this results into a ‘display’ property inside
‘display’ property, however Emacs ignores recursive display text property.
Using ‘after-string’ works as well as ‘display’ while allowing the emojis to be
displayed.

[back]
```

**Comment by dgutov** [comment]
All right. So first of all, this is an error from https://github.com/iqbalansari/emacs-emojify/

Any chance you have an old version installed? Here's the corresponding report where they should have fixed a bug like this: https://github.com/iqbalansari/emacs-emojify/issues/74, with https://github.com/iqbalansari/emacs-emojify/commit/d886069974d05c8c15654204f9afeaee962f3e7d.

**Comment by DavidVujic** [comment]
🤯  🙏 

That was it! I had set the `emojify` to "melpa-stable" in my configuraion 🤦 , and that version looks like not have been updated yet. I haven't fully understood the differences with the two "melpas" + the "elpa" repositories. A big Thank You for helping me find this error, everything works as expected now. 🙏
