### ISSUE TITLE
Display of list of candidates corrupted when buffer is scrolled to the left

### ISSUE THREAD

**Issue by richardxday** [company-mode/company-mode#1436]
Similar to #1427, the list of candidates is either not aligned or not in the right place when `global-display-line-numbers-mode` is `t` and the buffer is scrolled to the left (i.e. the end of the line is displayed but the start of the line is not).

``` 
Emacs 29.1 (x86_64-pc-linux-gnu) of 2023-12-02 on nil
Company 0.10.2

company-backends: (company-ispell)

Used backend: company-ispell
Major mode: fundamental-mode
Prefix: "li"
Completions:
  "line"
  "liner"
  "liners"
  "linear"
  "linearization"
  "linearisation"
``` 

When the bug occurs, the list of candidates is either not displayed in the right place or are misaligned.

Crucially, `truncate-lines` **must** be `t` and the current line **must** be wider than the window width for the issue to occur  (so that the beginning of the lines can be scrolled off the lefthand edge of the window).

The following script, saved as `demonstratecompanybug.el` reproduces the issue:
``` 
;; create a simple dictionary file called 'dict.txt' in the current directory for company-ispell
;; it only contains words starting with 'lin' to illustrate the problem!
(find-file "dict.txt")
(with-current-buffer (get-buffer-create "dict.txt")
  (kill-region (point-min) (point-max))
  (insert "line\n")
  (insert "liner\n")
  (insert "liners\n")
  (insert "linear\n")
  (insert "linearization\n")
  (insert "linearisation\n")
  (save-buffer)
  (kill-buffer))

;; add melpa package source
(require 'package)
(customize-set-variable 'package-archives '(("melpa" . "http://melpa.org/packages/")
					    ("gnu" . "http://elpa.gnu.org/packages/")))
(package-refresh-contents)

;; install company
(package-install 'company)

;; configure ispell and company options
(require 'ispell)
(require 'company)
(setq company-ispell-available 'unknown)
(customize-set-variable 'company-backends '(company-ispell))
(customize-set-variable 'company-ispell-dictionary ispell-complete-word-dict)
(customize-set-variable 'display-line-numbers t)
(customize-set-variable 'global-company-mode t)
(customize-set-variable 'global-display-line-numbers-mode t)
(customize-set-variable 'ispell-alternate-dictionary nil)
(customize-set-variable 'ispell-complete-word-dict "dict.txt")
(customize-set-variable 'ispell-dictionary "en")
(customize-set-variable 'ispell-grep-options "-Ei")
(customize-set-variable 'ispell-look-p nil)
(customize-set-variable 'truncate-lines t)

;; create buffer with a bunch of lines in it
(with-current-buffer (get-buffer-create "test.txt")
  (pop-to-buffer (current-buffer))
  (delete-other-windows)
  (split-window-right)
  (company-mode t)
  (display-line-numbers-mode t)
  (insert "This is a long line,This is a long line,This is a long line,This is a long line,This is a long line,This is a long line,This is a long line,This is a long line,This is a long line,This is a long li\n")
  (insert "line2\n")
  (insert "line3\n")
  (insert "line4\n")
  (insert "line5\n")
  (goto-char (point-min))
  (end-of-line))

;; once loaded, simply press 'n' and look at the completions
``` 

It can be run using:
`emacs -Q -l demonstratecompanybug.el`

Once loaded, assuming the beginning of the lines are off the lefthand edge of the window, pressing `n` will illustrate the issue.

Here's an example:
![image](https://github.com/company-mode/company-mode/assets/8612921/176e6432-6aaa-475b-b015-2e29cb0b25e9)

Depending upon the window width, different things happen, here the candidates are displayed off screen:
![image](https://github.com/company-mode/company-mode/assets/8612921/1c0c2956-d74b-4bcb-874a-59c7a672720f)

If the beginning of the lines are visible, the candidates are displayed correctly every time:
![image](https://github.com/company-mode/company-mode/assets/8612921/2f713e77-7e7a-4d6b-b603-2aa0d019f3a3)

Disabling `display-line-numbers-mode` also fixes the issue.

**Comment by dgutov** [comment]
Thanks for the report.

It was easy enough to reproduce, but not so easy to fix quickly.

Would I be right to assume that you're only seeing this problem with the latest versions? Was behavior before (e.g. when using the stable 0.10.2) better in this scenario? Did it also have problems?

**Comment by dgutov** [comment]
This fixed all the problems that I managed to trigger.

See if you're still having some.

**Comment by richardxday** [comment]
Thank you for the fix, all appears good so far and I've not been able to reproduce the issue.

Thank you for all your hard work on this, it's awesome!
