### ISSUE TITLE
No completion found for python script

### ISSUE THREAD

**Issue by fabriziojpiva** [company-mode/company-mode#1451]
#### Output of the command `M-x company-diag`
```
Emacs 29.2 (x86_64-pc-linux-gnu) of 2024-01-31 on nil
Company 0.10.2

company-backends: (company-bbdb company-semantic company-cmake company-capf company-clang company-files
	      (company-dabbrev-code company-gtags company-etags company-keywords)
	      company-oddmuse company-dabbrev)

Used backend: company-capf
Value of c-a-p-f: (lsp-completion-at-point python-completion-at-point t)
Major mode: python-mode
Prefix: ("" . t)

Completions: none
```
#### Describe the issue
Company mode is not doing any completions. Here is the output of the **\*Messages\*** buffer:

```
Loading /home/fabrizio/.config/emacs/config.el (source)...
[yas] Prepared just-in-time loading of snippets (but no snippets found).
Loading /home/fabrizio/.config/emacs/config.el (source)...done
Loaded /home/fabrizio/.config/emacs/config.el
Loading ido...done
Loading nyan-mode...done
For information about GNU Emacs and the GNU system, type C-h C-a.
main.py has auto save data; consider M-x recover-this-file
Can’t guess python-indent-offset, using defaults: 4
LSP :: Connected to [pylsp:124753/starting /home/fabrizio/Projects/meanreversion_strategy]. [2 times]
LSP :: pylsp:124753 initialized successfully in folders: (/home/fabrizio/Projects/meanreversion_strategy)
Quit
No completion found [5 times]
```

#### Expected behavior
Company-mode to offer completions for what I am typing on the script.

#### The error backtrace
I tried to autocomplete with the error backtrace but I did not find any backtrace buffer with relevant information

#### Screenshots
![image](https://github.com/company-mode/company-mode/assets/21205575/22eb5a15-bb0a-4e82-85d8-f43c83af7e6f)

#### Additional context
Company-mode is not working with our without `lsp-mode`. I tried running `emacs -Q` and enabling `company-mode` in the same script and the completions did not work. So this issue is purely from `company-mode`

**Comment by dgutov** [comment]
Without lsp-mode, you'll need to call `M-x run-python` first (to get the shell buffer), and then some basic completion should work.

With lsp-mode you should get more advanced completion, but any problems should be reported to that package. Try their troubleshooting instructions, and so on.

**Comment by fabriziojpiva** [comment]
> Without lsp-mode, you'll need to call `M-x run-python` first (to get the shell buffer), and then some basic completion should work.
> 
> With lsp-mode you should get more advanced completion, but any problems should be reported to that package. Try their troubleshooting instructions, and so on.

Hi, Thanks for replying. Like I said in Additional context, `company-mode` is not working even with `emacs -Q` (see screenshot below):

![image](https://github.com/company-mode/company-mode/assets/21205575/63324620-06c6-453c-aece-14ae36fd3a52)

The only thing I did is running `emacs -Q -l company-plain-start.el`, where `company-plain-start.el` contains:

```
 ; MELPA
(require 'package)
(add-to-list 'package-archives
             '("melpa" . "https://melpa.org/packages/"))
(when (< emacs-major-version 24)
  (add-to-list 'package-archives '("gnu" . "http://elpa.gnu.org/packages/")))

;;; company-start-plain.el ends here
```
After launching emacs with that command, I installed company package and opened the python file and run `M-x run-python` just like you said. Then I don't get any completions, so the problem is clearly not with lsp-mode.
