### ISSUE TITLE
company-gtags template not expanding correctly when using tree-sitter. 

### ISSUE THREAD

**Issue by MirkoHernandez** [company-mode/company-mode#1452]
#### Describe the issue
This problem only occurs when using tree-sitter.
Expanding a gtags related completion candidate  creates the following error:

``` text
company-call-backend-raw: Company: backend company-gtags error "Invalid search bound (wrong side of point)" with args (post-completion fill)
```
#### Steps to reproduce
- enable tree-sitter M-x  `c-ts-mode`
- try to complete anything gtags related. 
- changing the mode to `c-mode `solves the issue.
 
#### Expected behavior
Expand the gtags template correctly.

#### Additional context

I tried to use edebug to find the source of the problem, it seems that `company-template-c-like-templatify ` uses the same argument in both `c-mode` and `c-ts-mode`. The second `search-backward` creates the error, the behavior of   `backward-sexp` changes when tree-sitter is enabled.

**Comment by MirkoHernandez** [comment]
This workaround fixed the issue: replace   `backward-sexp` with `sp-backward-sexp` in `company-template-c-like-templatify` but it requires the smartparens package.

**Comment by dgutov** [comment]
Could you try this patch?

```diff
diff --git a/company-template.el b/company-template.el
index 65fbf6e..2c92f17 100644
--- a/company-template.el
+++ b/company-template.el
@@ -205,6 +205,7 @@ after deleting a field in `company-template-remove-field'."
   (let* ((end (point-marker))
          (beg (- (point) (length call)))
          (templ (company-template-declare-template beg end))
+         forward-sexp-function
          paren-open paren-close)
     (with-syntax-table (make-syntax-table (syntax-table))
       (modify-syntax-entry ?< "(")
```

**Comment by MirkoHernandez** [comment]
This works, thanks!.

**Comment by dgutov** [comment]
Thanks for checking.
