### ISSUE TITLE
Error occurs when continuing to type after manually invoking `company-yasnippet`

### ISSUE THREAD

**Issue by zhenhua-wang** [company-mode/company-mode#1455]
#### Describe the issue
The error occurs when continuing to type after manually invoking `company-yasnippet` when `(setq company-abort-manual-when-too-short t)`. Below is the message in backtrace buffer.

```elisp
Debugger entered--Lisp error: (wrong-type-argument listp 1)
  company--prefix-min-length()
  company--continue()
  company--perform()
  company-post-command()
```

#### Steps to reproduce
1. (setq company-abort-manual-when-too-short t)
2. Manually call `company-yasnippet` (or `company-manual-begin`, `company-other-backend`).
3. Continue typing to further filter the completion list.

The second step works fine, but the third step would yield the above error.

Edit: This only occurs in org-mode

**Comment by dgutov** [comment]
Thanks for the report, should be fixed now.

> Edit: This only occurs in org-mode

This was an important bit of information.

**Comment by zhenhua-wang** [comment]
I am experiencing this again when completing python packages using `lsp`. For example, continuing typing after `numpy.` would yield the following error.

```elisp
Debugger entered--Lisp error: (wrong-type-argument number-or-marker-p t)
  company--prefix-min-length()
  company--continue()
  company--perform()
  company-post-command()
```

**Steps to reproduce**
1. enable `lsp-mode` or `eglot`
2. (setq company-abort-manual-when-too-short t
              company-minimum-prefix-length 1)
3. Type in `numpy.`
4. Call `company-manual-begin`
5. Continue typing to further filter the completion list

**Comment by dgutov** [comment]
Hi again!

Does that happen only with Python? I've been using more LSP completion lately (both modes), and haven't seen this particular error yet.

**Comment by zhenhua-wang** [comment]
Thank you for verifying! I just tested this in `emacs -Q` and noticed this issue occurs in both Python, R, and C++ .  It seems to be triggered by the presence of special characters. For example, after `numpy.` in Python and `std::` in C++. 

In the attached gif, I show this by invoking `company-manual-begin` following `std::` or `std::c`. Subsequently, typing anything would immediately yield that error.

![Screencast from 2024-02-28 13-01-22](https://github.com/company-mode/company-mode/assets/11971417/73b6c0b1-0e1f-4bb7-9747-b62ebfdab7db)

**Comment by dgutov** [comment]
@zhenhua-wang Thanks, should work now too.

This case is a little less obvious (how to interpret `company-abort-manual-when-too-short` with a prefix that has `t` in cdr), but the change should be fine for most situations. Let me know if you see exceptions.

**Comment by zhenhua-wang** [comment]
Hi, thanks for checking this. Unfortunately, another error `Wrong type argument: listp, t` shows up. 

I just checked the source code. It seems that when `company--manual-prefix` is `'("", t)`, and `(length '("" . t))` will yield the above error. 

I wonder if we should call `length` on  `(car-safe company--manual-prefix)`, instead of on `company--manual-prefix`. However, this brings another issue, where completion won't abort even when no prefix exists. I am currently stuck on debugging at here ...

**Comment by zhenhua-wang** [comment]
> I wonder if we should call `length` on `(car-safe company--manual-prefix)`, instead of on `company--manual-prefix`. However, this brings another issue, where completion won't abort even when no prefix exists. I am currently stuck on debugging at here ...

Update: this at least happen for `company-ispell` and `company-capf` with eglot in c++-mode. `emacs-lisp-mode` seems fine.

**Comment by dgutov** [comment]
All right, here's hoping the third time will be the charm. Pushed a new version.

**Comment by zhenhua-wang** [comment]
Thanks for the quick fix. It works great so far!
