### ISSUE TITLE
Cursor moves on company-complete when the same file is open in multiple buffers

### ISSUE THREAD

**Issue by furushchev** [company-mode/company-mode#1458]
When the same file is open in multiple windows, running `company-complete` causes a jump to the cursor position in another window instead of displaying the completion menu.

Here is how to reproduce the issue

1. Open any file in Emacs (`emacs file.cpp`)
2. `C-x 2` to open the same file in multiple windows
3. Move the cursor (i.e. `M->`)  and run `M-x company-complete`
4. The cursor jumps to the position of the cursor in another window. No completion menu shows up

The result of the `M-x company-diag` is as follows:

```console
Emacs 26.3 (aarch64-unknown-linux-gnu) of 2020-03-26 on bos02-arm64-033
Company 0.10.2

company-backends: (company-bbdb company-semantic company-cmake company-capf company-clang company-files
              (company-dabbrev-code company-gtags company-etags company-keywords)
              company-oddmuse company-dabbrev)

Used backend: company-clang
Major mode: c++-mode
Prefix: ""
```

I found that this issue does not occur on the older version:

```console
Emacs 26.3 (aarch64-unknown-linux-gnu) of 2020-03-26 on bos02-arm64-033
Company 0.9.13

company-backends: (company-bbdb company-semantic company-cmake company-capf company-clang company-files
              (company-dabbrev-code company-gtags company-etags company-keywords)
              company-oddmuse company-dabbrev)

Used backend: company-clang
Major mode: c++-mode
Prefix: ""
```

**Comment by dgutov** [comment]
Hi!

Did you test that with a "bare" configuration, e.g. starting with `emacs -Q`? 

I'm unable to reproduce.

**Comment by furushchev** [comment]
Hello! I'm so sorry for the delay.
I finally figured it out that the behavior only happens if it is used with `flycheck`.
When I disabled the flycheck package, it went back to normal.

**Comment by dgutov** [comment]
What is `carousel`? Can you link to that package?

**Comment by whatacold** [comment]
Hi @furushchev,

If you can reproduce it steadily, maybe you can consider to debug it
in edebug:

1.  Go to the definition of `company-complete`, and do `C-u M-x eval-defun`
2.  Run `M-x company-complete` as usual, it will trap into the
    definition, and then do some step debugging by hitting `n` multiple
    times until you see the cursor's beloning buffer changed, and then
    narrow the code space from there.

**Comment by dgutov** [comment]
Please report back if you see the problem again.
