### ISSUE TITLE
Cannot download company from MELPA 

### ISSUE THREAD

**Issue by Ghasak** [company-mode/company-mode#1461]
#### Describe the issue
It seems there is a problem with MELPA to download the version `company 20240301.346` it shows it is not existed!!
as  a working around I used (which is on local machine) 

```sh 
cp -r company-20240302.1525 company-20240301.346
```

#### Steps to reproduce
You cannot install `company` from melba and when you go to the MELPA website and click download it will not download anything the version which is not working is `company 20240301.346`

#### Expected behavior
The version company 20240301.346 should be downloaded as .tar from MELPA without a `404 Not Found nginx` , I assume it is a problem with the server not the package, but I wish some expert can look in to it. 

#### Screenshots
If applicable, add screenshots (not huge ones, please) to help explain your problem.
![Screenshot 2024-03-03 at 2 18 11](https://github.com/company-mode/company-mode/assets/27670946/762cbc1f-3cfd-4703-b301-124f9b8c1261)

#### Additional context
Please be easy on me, I am not expert in this!, I just report this as a bug but I don't think it's a problem of `company` package rather the server of MELPA, but if it is not downloadable there, then why it should be existed there!

**Comment by dgutov** [comment]
Try clearing the cache in your browser for melpa.org. Or just pressing <kbd>Ctrl-F5</kbd>.

The latest version on MELPA is `20240302.1525`, and it downloads fine. If it had problems, though, it would be a better idea to file the issue to the melpa repository - it is responsible for the distribution, after all.

**Comment by Ghasak** [comment]
Thank you very much, @dgutov 
I will consider your suggestion now. then I will close the issue.

**Comment by Ghasak** [comment]
Thank you very much again @dgutov 
Yes, I managed to install it now, I am happy to say that the problem resolved and it was just a cache problem as you suggested. I am in debt to you Sir! I will close this issue now, it was a false alarm from my side.
