### ISSUE TITLE
Evil using (setq evil-move-cursor-back nil)

### ISSUE THREAD

**Issue by maxfriis** [company-mode/company-mode#1473]
#### Output of the command `M-x company-diag`
    Emacs 30.0.50 (x86_64-pc-linux-gnu) of 2024-05-20 on lcy02-amd64-059 Company 0.10.2

    company-backends: (company-bbdb company-semantic company-cmake company-capf company-clang company-files
              (company-dabbrev-code company-gtags company-etags company-keywords)
              company-oddmuse company-dabbrev)

    Used backend: company-dabbrev

    Major mode: emacs-lisp-mode
    Prefix: nil

#### Company use a hack when exiting insert state
Company rely on the "move curser back" default Vim behavior to cancel a popup with suggestions when exiting insert state. I think this programming is a bit sloppy, since evil actually provide the option of not moving back with (setq evil-move-cursor-back nil). It is not a feature the evil package has meant to be used in a hack like that.

#### Steps to reproduce
Ensure evil and company packages are available.

    (setq evil-move-cursor-back nil)
    (require 'evil)    
    (evil-mode 1)
    (require 'company)
    (company-tng-mode 1)
    (global-company-mode 1)

After this open a buffer with some text.
Press "i" to enter insert state.
Type something until completions are suggested.
Press "\<esc\>" to exit insert state without selecting a completion option.
The completion popup persist in normal state. "C-g" or "h" will cancel the popup.

#### Expected behavior
The completion popup should disappear as it does if you use

    (setq evil-move-cursor-back t)

#### The error backtrace
No error is detected.

#### Screenshots
![Screenshot from 2024-05-26 12-20-22](https://github.com/company-mode/company-mode/assets/45585452/5e39f101-5a44-4571-9a65-6d366f802042)

#### Additional context
I have tryed to look at the code, but I'm no programmer. I write books and have fallen in love with [evil-cursor-model.el](https://www.dr-qubit.org/Evil_cursor_model.html) which I think is a logical choice if you have not started out with Vim and want easy Vim style keybindings.

**Comment by dgutov** [comment]
Hi!

I'm glad you like this package, but it code has no awareness of Evil's internals (nor do I), so it doesn't do anything with it.

There is some integration inside Evil itself (https://github.com/emacs-evil/evil/blob/89efb079a1b31c1881adcc6b370b20ce85f2b5bc/evil-integration.el#L200), and there is some more stuff in evil-collection (https://github.com/emacs-evil/evil-collection/blob/b34369cdb5c1bcecaf02094cf7e31e43c5534e32/modes/company/evil-collection-company.el).

Depending on whether you use only one of these packages, or both, you might want to direct your bug report correspondingly.

**Comment by maxfriis** [comment]
Thank you. I understand your position and will try to cook some solution for myself.

I don't think evil will want to or should cancel popups from other packages when changing states. Randomly the optional move back action just integrate nicely with company.

**Comment by maxfriis** [comment]
I understand why this is not an issue company should deal with.

**Comment by dgutov** [comment]
FWIW, I think Evil upstream might still want to hear about your problem and either do something themselves, or suggest the source of the problem here. Or if you are using a non-standard addon (evil-cursor-mode?), the report might be useful to its author, maybe.
