### ISSUE TITLE
Cannot install from melpa

### ISSUE THREAD

**Issue by WorikWork** [company-mode/company-mode#1481]
**Please make sure to search in [existing issues](https://github.com/company-mode/company-mode/issues?q=) before filing a new report!**

Related: https://github.com/company-mode/company-mode/issues/1461

#### Output of the command `M-x company-diag`
> company-call-backend-raw: Company: backend company-cmake error "Wrong type argument: listp, company-cmake" with args (prefix)

Odd, as I cannot find `company` or `company-mode` in my packages via `list-packages`

#### Describe the issue

`M-x package-install company` there is no such package

Using
```elisp
(require 'package)
(add-to-list 'package-archives
             '("melpa-stable" . "https://stable.melpa.org/packages/") t)
```

#### Additional context
Emacs 29.4.50
Debian-12

**Comment by dgutov** [comment]
Hi!

After adding the source to package-archives, you'll need to refresh the list. Type `M-x list-packages` and wait for the list to update. Then you can use the UI to install the package or proceed to use the `package-install` command you tried.

Also, this package is in GNU ELPA as well (the built-in repository). So you shouldn't even need to add MELPA Stable to install a stable release. Sometime later you can add the MELPA repository (the one that is not "Stable") to get the latest-and-greatest snapshot, but that's not required.

**Comment by WorikWork** [comment]
> After adding the source to package-archives

What does that mean?

**Comment by dgutov** [comment]
That's what your snippet does.

**Comment by WorikWork** [comment]
Emacs 29.  Company is not a package.  It is built in.  I have company mode, which is why (I assume) I cannot see it in the packages

**Comment by dgutov** [comment]
It's a package. It's not built-in.

**Comment by WorikWork** [comment]
> It's a package. It's not built-in.

Emacs disagrees with you!
