### ISSUE TITLE
Cannot use company-posframe-mode after upgrade

### ISSUE THREAD

**Issue by dgutov** [company-mode/company-mode#1484]
### Discussed in https://github.com/company-mode/company-mode/discussions/1483

<div type='discussions-op-text'>

<sup>Originally posted by **thattemperature** July 13, 2024</sup>
After I upgrade company-mode to the newest version in melpa(20240713.303), when I activate company-posframe-mode, It can pop up the box of candidates, but the box never disappear after I press return key (and any other keys), and the error message shown in echo area is: 
`company-call-frontends: Company: frontend company-pseudo-tooltip-unless-just-one-frontend error "Wrong type argument: stringp, nil" on command hide. `
The company-posframe-mode package did not update for a long time, so I think the upgrade of company-mode cause this problem.</div>

**Comment by dgutov** [comment]
Hey @thattemperature, thanks for the report.

I've pushed a workaround here that seems to fix it. Should avoid needing an update in company-posframe.

**Comment by thattemperature** [comment]
Very grateful for your prompt work. @dgutov
