### ISSUE TITLE
company-files + company-tng-mode file path disappearing problem

### ISSUE THREAD

**Issue by yurii-tov** [company-mode/company-mode#1487]
#### Output of the command `M-x company-diag`
```
    Emacs 29.1 (x86_64-pc-linux-gnu) of 2024-07-27 on nil
    Company 0.10.2

    company-backends: (company-files)

    Used backend: company-files
    Major mode: lisp-interaction-mode
    Prefix: ("/opt/TeamCity/buildAgent/" "")

    Completions:
      "bin/"
      "BUILD_129421"
      "conf/"
      "contrib/"
      "launcher/"
      "lib/"
      "README.md"
      "service.properties"
```

**Package version:** `20240719.2038` (from melpa)

#### Describe the issue
When completing file paths with the Company and navigating through the menu, there is an unpleasant visual artifact: the file path (which we are trying to complete) is disappearing.

#### Steps to reproduce
* Pre-conditions
  - company-tng-mode is enabled
  - company-files backend is enabled

* How to reproduce
  1. Suppose we have some file path in a buffer, e.g. `/opt/TeamCity/buildAgent`
  2. We try to complete it with Company:
     We type `/` at the end of the path and trigger completion menu
  3. Navigane through menu:
     Hitting TAB couple of times or use arrows / C-n / C-p

     => Initial file path disappears (in our example it is `/opt/TeamCity/buildAgent/`)

#### Expected behavior
File path we trying to complete should NOT disappear while we navigating completions menu

#### Video of a bug

https://github.com/user-attachments/assets/355fa745-e7c6-4efe-a0d1-b08d8e365a70

#### Example Company config to reproduce
``` emacs-lisp
    (progn (global-company-mode)
           (company-tng-mode))

    (setq-default company-backends '(company-files))
```

**Comment by dgutov** [comment]
Hi! Thanks for the report, this subpackage got a little stale.

I've pushed a minor fix which should improve on this particular scenario. Please let me know if you see any other breakage.

**Comment by yurii-tov** [comment]
Thank you for your help! I've checked, and the problem is now fixed. 😊
