### ISSUE TITLE
Expand-common breaks certain completion scenarios in CIDER

### ISSUE THREAD

**Issue by alexander-yakushev** [company-mode/company-mode#1493]
#### Problem
CIDER uses company-mode as a completion frontend together with a custom completion backend. When combined with `flex` completion-style, the backend can offer candidates that don't necessarily start with the completion prefix. Namely, CIDER can complete full Java classnames only from the short names (e.g., `List` -> `java.util.List`). This feature requires the completion prefix to be precisely the beginning of the shortname, not any arbitrary substring of the full name.

After #1488 (my assumption, because the problem appeared just recently), when such completion is invoked and there is more than one candidate, company-mode will find the common part of the candidates (e.g., the period before the shortname), prepend it to the prefix, and re-query the completion. E.g., `List` -> `.List`. Because of how CIDER completion backend operates, triggering on `.List` will no longer offer the desired completion candidates.

What I'd like is one of:
- Be able to turn off this behavior (adding common part to the front of the prefix) for CIDER from the user side.
- Specify in the completion source on the CIDER side that we don't want this behavior.
- Any other suggestion how to deal with this.

#### Output of the command `M-x company-diag`
```
Emacs 29.1 (aarch64-apple-darwin22.5.0) of 2023-08-16 on osaka.local
Company 0.10.2

company-backends: (company-bbdb company-semantic company-cmake company-capf company-clang company-files
              (company-dabbrev-code company-gtags company-etags company-keywords)
              company-oddmuse company-dabbrev)

Used backend: company-capf
Value of c-a-p-f: (cider-complete-at-point t)
Major mode: clojure-mode
Prefix: ("RT" "" nil)

Completions:
  #("clojure.lang.RT" 0 1 (completion-score 0.13333333333333333 ns nil type "class") 13 14 (face completions-common-part) 14 15 (face completions-common-part)) " <c>"
  #("javax.swing.text.rtf.RTFParser" 0 1 (completion-score 0.06666666666666667 ns nil type "class") 21 22 (face completions-common-part) 22 23 (face completions-common-part) 23 24 (face completions-first-difference)) " <c>"
  #("javax.swing.text.rtf.RTFReader" 0 1 (completion-score 0.06666666666666667 ns nil type "class") 21 22 (face completions-common-part) 22 23 (face completions-common-part) 23 24 (face completions-first-difference)) " <c>"
  #("javax.swing.text.rtf.RTFAttribute" 0 1 (completion-score 0.06060606060606061 ns nil type "class") 21 22 (face completions-common-part) 22 23 (face completions-common-part) 23 24 (face completions-first-difference)) " <c>"
  #("javax.swing.text.rtf.RTFEditorKit" 0 1 (completion-score 0.06060606060606061 ns nil type "class") 21 22 (face completions-common-part) 22 23 (face completions-common-part) 23 24 (face completions-first-difference)) " <c>"
  #("javax.swing.text.rtf.RTFGenerator" 0 1 (completion-score 0.06060606060606061 ns nil type "class") 21 22 (face completions-common-part) 22 23 (face completions-common-part) 23 24 (face completions-first-difference)) " <c>"
  #("javax.swing.text.rtf.RTFAttributes" 0 1 (completion-score 0.058823529411764705 ns nil type "class") 21 22 (face completions-common-part) 22 23 (face completions-common-part) 23 24 (face completions-first-difference)) " <c>"
  #("org.apache.tika.metadata.RTFMetadata" 0 1 (completion-score 0.05555555555555555 ns nil type "class") 25 26 (face completions-common-part) 26 27 (face completions-common-part) 27 28 (face completions-first-difference)) " <c>"
  #("com.sun.org.apache.xpath.internal.axes.RTFIterator" 0 1 (completion-score 0.04 ns nil type "class") 39 40 (face completions-common-part) 40 41 (face completions-common-part) 41 42 (face completions-first-difference)) " <c>"
  #("net.thisptr.jackson.jq.internal.functions.RTrimStrFunction" 0 1 (completion-score 0.034482758620689655 ns nil type "class") 42 43 (face completions-common-part) 43 44 (face completions-common-part) 44 45 (face completions-first-difference)) " <c>"
  #("net.snowflake.client.jdbc.internal.apache.tika.metadata.RTFMetadata" 0 1 (completion-score 0.029850746268656716 ns nil type "class") 56 57 (face completions-common-part) 57 58 (face completions-common-part) 58 59 (face completions-first-difference)) " <c>"
```

**Comment by dgutov** [comment]
Hi!

That sounds like a problem we/I fixed just recently in Eglot, see the complex definition of `eglot--dumb-tryc` here: https://git.savannah.gnu.org/cgit/emacs.git/tree/lisp/progmodes/eglot.el?h=emacs-30#n3149 and the corresponding report https://debbugs.gnu.org/72705 (you can also see it in the comments of the aforementioned PR).

So basically this can be fixed:
* In the `try-completion` method of the completion table, or
* In the completion style that is used.

For Eglot we went with the latter, but since Cider doesn't use a custom style perhaps the first option will work well. The place to try would be around the `complete-with-action` call at https://github.com/clojure-emacs/cider/blob/87b836f289d5e3935b515eaac2959bd2e1d3ed37/cider-completion.el#L217.

**Comment by dgutov** [comment]
If I'm reading the situation right, you should already have the same problem with `C-M-i` completion (which would show up with Corfu as well), where pressing `C-M-i` after `List` would insert the period.

The recent change in Company aims to make the "complete common" command more powerful -- with more flexible expansion -- but unfortunately that comes with a couple of `completion-at-point`'s downsides as well.

**Comment by dgutov** [comment]
Also see https://github.com/emacs-lsp/lsp-mode/pull/4544.

**Comment by alexander-yakushev** [comment]
Thank you for the pointers! I couldn't make it work through a completion table – it seems like my completion table is never called with `nil` for action (which signifies the `try-completion` op). So it seems like I would have to start using a custom completion style again.

I'll close this issue since, as you've pointed out, it's a wider issue with the default Emacs completion engine.

**Comment by dgutov** [comment]
Yes, sorry, apparently what the `flex` style does is first query for all completions (the `completion-substring--all-completions` call) and then processes the resulting list of strings (the `try-completion` calls in `completion-pcm--merge-try` don't go to the original table). So a completion style seems the way to go.

Please go ahead and ping me if you have further questions or problems adapting the style implementation. This is still a breaking change in company-mode's behavior, and I'd like to see all major completion providers onboard before tagging the next release.
