### ISSUE TITLE
Tag '1.0.2' not on master

### ISSUE THREAD

**Issue by manphiz** [company-mode/company-mode#1495]
It looks like that the `1.0.2` tag is not on master branch.  The tag has this warning.
```
This commit does not belong to any branch on this repository, and may belong to a fork outside of the repository.
```
Maybe it's on a branch that is not yet synced?

**Comment by dgutov** [comment]
Yeah, sorry about that. I fumbled with the tag originally, and had to update it.

Should be okay now.
