### ISSUE TITLE
git-gutter fringe disappears when company popup is shown

### ISSUE THREAD

**Issue by vjohansen** [company-mode/company-mode#1496]
After upgrading to 1.0.1 I have a gutter/fringe issue

I have git-gutter (0.92) installed and activated with 
 
    (global-git-gutter-mode)

In for example an emacs-lisp file

![image](https://github.com/user-attachments/assets/3c682d31-2f5a-44b8-98d2-2faa43b6333d)

The purple is from git-gutter to indicate changed lines

Typing *de* causes the left-most grey fringe/gutter to disappear

![image](https://github.com/user-attachments/assets/911368b7-6788-4df9-9b70-db52eac540fd)

Same thing happens for other major modes (markdown, typescript,..)

Saving the file causes the git-gutter fringe to return

**Comment by dgutov** [comment]
Hi!

Sorry, I'm unable to reproduce this. Do you have a step-by-step config?

Simply installing (and loading) git-gutter-fringe and enabling git-gutter-mode doesn't lead to the effect you've described.

You might also want to try [diff-hl](https://github.com/dgutov/diff-hl/) (sorry for the plug), but again, I'm not seeing the problem with git-gutter either.

**Comment by vjohansen** [comment]
ah, I though it would be easy to reproduce.

I have moved over to use **diff-hl** 👍
