### ISSUE TITLE
company-mode-clang: not completing when the whole function name is typed

### ISSUE THREAD

**Issue by xuhdev** [company-mode/company-mode#150]
For the following code:

``` c
#include <stdio.h>
int main(void)
{
    print
           ^
}
```

If I type `<M-X>company-complete`, it automatically completes `printf`, including the parameters, which is perfect.

However, if the code is:

``` c
#include <stdio.h>
int main(void)
{
    printf
            ^
}
```

It won't complete if I type `<M-X>company-complete`.

**Comment by dgutov** [comment]
Please try the `forced-completion-for-unique-match` branch. `M-x company-complete` should work there in this situation.
