### ISSUE TITLE
Improve candidates post-processing documentation

### ISSUE THREAD

**Issue by yugaego** [company-mode/company-mode#1502]
### Discussed in https://github.com/company-mode/company-mode/discussions/1500

<div type='discussions-op-text'>

<sup>Originally posted by **mandarm** November 29, 2024</sup>
Not really sure what's the best place for this suggestion..

The [Candidates Post-Processing](https://company-mode.github.io/manual/Backends.html#Candidates-Post_002dProcessing) section of the manual uses ```delete-consecutive-dups``` as an example that could be added to ```company-transformers```. OTOH, the docstring for ```company-transformers``` says

The first one [first function on the ```company-transformers``` list] gets passed the list of candidates, already sorted and without duplicates.

It appears then, that ```delete-consecutive-dups``` would not be a useful function to add to ```company-transformers```. If this understanding is correct, perhaps the manual could be modified suitably to avoid any confusion?</div>

**Comment by yugaego** [comment]
For reference, the related issues are #528 and #432. The [declared design choice](https://github.com/company-mode/company-mode/issues/528#issuecomment-222542471) in those cases is that

> We don't consider completions with different annotations to be duplicates.

**Comment by dgutov** [comment]
Thanks for summarizing!

I guess adding `delete-consecutive-dups` there might not be the best advice to make without additional clarification.

But could it be useful? Like you quote, completions with different annotations are not removed, even if the completion stings are the same (which seems like a good default behavior). And unless the backend overrides the sorting behavior (or the group uses the `:separate` keyword), string-equal completions are kept together in the resulting list.

So if the user is not happy with that design choice of ours and would prefer to retain just one instance of each (and doesn't want to hand-pick which one stays), adding `delete-consecutive-dups` to `company-transformers` can be a decent move to reach that goal. This function is pretty fast too, unlike some other options.
