### ISSUE TITLE
company has distorted completion popup with `fci-mode`

### ISSUE THREAD

**Issue by tuhdo** [company-mode/company-mode#180]
[fci-mode](http://www.emacswiki.org/emacs/FillColumnIndicator) creates a visual fill column to indicate the current fill column number.

When `company` creates a popup with `fci-mode` activated, it looks like this:

![company-fci-error](https://cloud.githubusercontent.com/assets/4818719/4174455/56181c78-3591-11e4-92ab-5533556ce4e1.gif)

It did not happen with company 0.8.2.

**Comment by jeaye** [comment]
I'm having this issue as well (with company-ycmd). Screenshots showing company's completion moving around:

http://jeaye.com/upload/data/emacs_right.png
http://jeaye.com/upload/data/emacs_center.png

**Comment by jeaye** [comment]
@dgutov I can verify that your workaround does work, for now. Thanks.

**Comment by majjoha** [comment]
It seems to solve the issue for me as well. Thank you, @dgutov.

**Comment by philiparvidsson** [comment]
Any progress on this? What can be done? Suggestions above do not solve it for me.

**Comment by dgutov** [comment]
No progress, and you should follow the linked issue in the Fill-Column-Indicator repo.

The workaround should still work, though.

**Comment by jtherrmann** [comment]
Was this recently fixed? I've had this problem for a while, just got around to researching it, found this discussion, went to implement the workaround but found that I was no longer having the issue. I'm using the latest commit for https://github.com/alpaker/Fill-Column-Indicator and https://github.com/company-mode/company-mode/commit/388eec511a7543d77a325dd68081e6e951f64d1f for company-mode.

**Comment by dgutov** [comment]
@jtherrmann It's still reproducible for me. :man_shrugging:

**Comment by jtherrmann** [comment]
@dgutov Interesting. I'll pay attention to see if it resurfaces.

**Comment by jtherrmann** [comment]
@dgutov Yep, it's back. I'll try the workaround when I have a chance.

**Comment by jtherrmann** [comment]
@dgutov The workaround seems to work for me, but even without it, I can't reliably reproduce this bug. I'm not sure of the exact conditions under which it occurs.

**Comment by y-ates** [comment]
@dgutov Thanks!

**Comment by dgutov** [comment]
Emacs 27 will be released _very soon now_.

And it includes `display-fill-column-indicator-mode` which doesn't conflict with this package. I recommend everyone switch to it.
