### ISSUE TITLE
Type a letter to select a candidate

### ISSUE THREAD

**Issue by fniessen** [company-mode/company-mode#188]
Hello,

To select one of the first 10 candidates, we now can press 'M-1' to 'M-0'. That's not the easiest key binding on a French keyboard as the figures must be "shifted". Hence, 'M-1' is for us pressing 'M-S-&'.

A better idea IMHO would be to use letters instead of figures... It could be the first 10 letters which aren't possible completions of the proposed words. For example, after typing "po":
- popup       a
- poids       b
- poignée     c
- point       f
- podio       g
- poetsen     h
- pointeur    j
- pointeurs   k
- poissons    l
- pointu      m

('d', 'e' and 'i' were not eligible)

Using letters has the added advantage that a lot of us can type them without looking at all at the keyboard. It'd be quicker, and never would imply using 'M-' nor 'S-'.

WDYT?

**Comment by yugaego** [comment]
I've thought over all the related information I could find, and it seems to me there's no need at all to implement anything new fundamentally.

Firstly,
For *a-la* `ace-jump-mode` behavior (the project itself is dead btw), simply use `isearch` with `hi-lock-mode` enabled.

Or even better, use `Company` provided by default filtering `M-C-s` or searching `C-s` (press a key binding and start typing letters of a desired term --> quite a "jump").


Secondly,
Related (old-ish) PR #859 made quick-access representation layer - aka `numbers` - customizable. PR author had additionally configured custom bindings (letters) to call `Company`'s  defaults of `M-[digit]`.

So I've quick-tested that the following *rough* example seems to be a working solution.

```
(defun my/company-quick-access-key (numbered)
  "Replace default behavior of `company--show-numbers' function.
This example lists Dvorak layout home row keys."
  (let ((value (mod numbered 10)))
    (format " %s"
            (cond ((eql value 1) "a") ; a a
                  ((eql value 2) "o") ; b s
                  ((eql value 3) "e") ; c d
                  ((eql value 4) "u") ; d f
                  ((eql value 5) "i") ; k g
                  ((eql value 6) "d") ; l h
                  ((eql value 7) "h") ; m j
                  ((eql value 8) "t") ; x k
                  ((eql value 9) "n") ; y l
                  (t "s")))))         ; z ;

(setq company-show-numbers-function #'my/company-quick-access-key)

(define-key company-active-map (kbd "M-a") (kbd "M-1"))
(define-key company-active-map (kbd "M-o") (kbd "M-2"))
(define-key company-active-map (kbd "M-e") (kbd "M-3"))
(define-key company-active-map (kbd "M-u") (kbd "M-4"))
(define-key company-active-map (kbd "M-i") (kbd "M-5"))
(define-key company-active-map (kbd "M-d") (kbd "M-6"))
(define-key company-active-map (kbd "M-h") (kbd "M-7"))
(define-key company-active-map (kbd "M-t") (kbd "M-8"))
(define-key company-active-map (kbd "M-n") (kbd "M-9"))
(define-key company-active-map (kbd "M-s") (kbd "M-0"))

```

Such configuration should fix all the listed use cases (in addition to `C-s`, `M-C-s` and `isearch` mentioned above).

@dgutov,
I've got some minor improvements (code and/or docs) on my mind that could be added to simplify setting up `M-[letters]`, so I can proceed, if that sounds fine overall.

(Back to #1103 initiated discussion: possible `M-[letter]` configuration promotion would signify that `number(s)` term usage is arguable. So it could be addressed with the just mentioned updates.)

**Comment by dgutov** [comment]
> (the project itself is dead btw)

https://github.com/abo-abo/avy is the contemporary replacement.

> Or even better, use Company provided by default filtering M-C-s or searching C-s (press a key binding and start typing letters of a desired term --> quite a "jump").

**Comment by dgutov** [comment]
@yugaego Thanks for the write-up.

> (the project itself is dead btw)

https://github.com/abo-abo/avy is the contemporary replacement. It should be able to use the approach I have described above, if someone indeed wants that workflow. But no packages have popped up in 6 years, so probably not really.

> Or even better, use Company provided by default filtering M-C-s or searching C-s (press a key binding and start typing letters of a desired term --> quite a "jump").

That might be too involved for repeated usage (as a replacement for quick access numbers). But FWIW I find the use of numbers to be too involved and context-switchy as well.

> So I've quick-tested that the following rough example seems to be a working solution.

Thank you, this should cover the straightforward approach.

Other requested workflows included using characters or numbers without modifiers if they for some reason don't appear in completions, with dynamic reassigning. I think something like that could be arranges using `pre-command-hook` and dynamic modification of the active keymap, but it doesn't seem like a good idea to me, as the behavior would be too unpredictable for a smooth typing flow.

> I've got some minor improvements (code and/or docs) on my mind that could be added to simplify setting up M-[letters], so I can proceed, if that sounds fine overall.

I don't know, would need to see the code. The above snippet looks easy enough, and it could probably be shortened using an alist.

> possible M-[letter] configuration promotion would signify that number(s) term usage is arguable. So it could be addressed with the just mentioned updates.

I'm still fine with both `number` and `quick-access` naming scheme. The latter does seem like the common term for this sort of thing.

**Comment by yugaego** [comment]
<small>For reference: [avy ace-jump vs isearch](http://ergoemacs.org/misc/ace_jump_avy_vs_isearch.html).</small>

>  ... using characters or numbers without modifiers ... it doesn't seem like a good idea to me, as the behavior would be too unpredictable for a smooth typing flow.

I totally agree.

> The above snippet looks easy enough, and it could probably be shortened using an alist.

Yes, that was one of the ideas, with **possibly** suggesting to customize just an alist, adding  `my/company-quick-access-key` functionality to the package. Or - otherwise - add such a snippet to a Wiki page.

> I'm still fine with both number and quick-access naming scheme.

I'll prepare a PR(s) with concrete suggestions (and possibly additional questions).

**Comment by dgutov** [comment]
> For reference: avy ace-jump vs isearch.

Some good points there. It's fairly popular, though, even if I (or you, IIUC) don't use it. And e.g. one thing that avy has over isearch is the latter only searches in the current buffer. The former considers all buffers visible in the current window. Or their visible parts anyway.

> Yes, that was one of the ideas, with possibly suggesting to customize just an alist, adding my/company-quick-access-key functionality to the package. Or - otherwise - add such a snippet to a Wiki page.

I was thinking a Wiki page would be best ("tips and tricks?"), but some code addition could also work.

> I'll prepare a PR(s) with concrete suggestions (and possibly additional questions).

Looking forward :+1:

**Comment by dgutov** [comment]
This has been merged (see the latest NEWS entry). Please test.

You still need to use a modifier, but can choose one among the options.

**Comment by fniessen** [comment]
Works perfectly. Thanks a lot!
