### ISSUE TITLE
Inserting completion in comint/shell buffer displayed but invisible to shell when evaluated 

### ISSUE THREAD

**Issue by Lompik** [company-mode/company-mode#189]
On my computer,  completions inserted from `company-mode` in comint/shell buffers are displayed on the screen but invisible to shell when evaluated. here's an example:

I have the following output using `eshell`: 

```
e:/MyPath $ ca 
```

Company-mode pop up and I select `cat`... sometimes it would change the face of of `cat` to be same as comint `$`.

```
e:/MyPath $ cat     "   hello"
    hello: command not found
```

Hitting history with `M-p`  returns

```
e:/MyPath $  "  hello"
```

Regards,
lompik

**Comment by Henry** [comment]
> N.B. company-capf doesn't work reliably in Eshell buffers for me anyway.

I have found the same, it works for a while and then stops completing and nothing I do gets it started again.  I studied the `company-capf ` and `pcomplete' code but could not fathom what is going wrong so I wrote a `company-pcomplete` backend based on the auto-complete code for `eshell` on the emacs wiki:
 
https://github.com/Henry/dot-emacs/blob/master/my-lisp/company-pcomplete.el

which is a bit of a hack but seems to work fine for commands, file names, environment variables etc.  I am sure it could be done better and more consistently but it may help people struggling with `company-mode` and `eshell`.

**Comment by dgutov** [comment]
Thanks. You might want to publish to MELPA eventually, if it does work noticeably better.

If you ever find out what the problem in `pcomplete-completion-at-point` is, I'm sure a lot of users would appreciate a fix in Emacs. Or at least a bug report with details.

**Comment by Henry** [comment]
I would be happy to publish to MELPA if it proves reliable.  I would also like to iron-out some of the details like using the `pcomplete` prefix method rather than `company-grab-symbol` which is the only way I could get it to work so far.

Finding and fixing the problem between `company-capf` and `pcomplete-completion-at-point ` would be the ideal solution but I have already spent a long time on this without success so I will have to pass it on.

**Comment by Henry** [comment]
I have updated `company-pcomplete` to use the `pcomplete` prefix, cleaned-up and simplified the code and tested with `eshell` and `org-mode` and it seems to be reliable.  I will run more tests over the next week or so and if all is well I will add documentation and look into publishing to MELPA.  Anyone interested in testing and providing feed-back please get the latest version from

https://github.com/Henry/dot-emacs/blob/master/my-lisp/company-pcomplete.el

**Comment by Stebalien** [comment]
> I have found the same, it works for a while and then stops completing and nothing I do gets it started again. 

It seems to be getting itself added to `completion--capf-misbehave-funs` (and thus ignored). However, I don't really understand *why* this happens or what it means.  Removing it from this list fixes it.

**Comment by dgutov** [comment]
@Stebalien Apparently, it returns a bad value at some point, see `completion--capf-wrapper`.

**Comment by Stebalien** [comment]
Ah. I figured out the (a?) problem (although I don't know the fix). When completing an elisp symbol written as `(some-elisp-`, eshell recursively calls `completion-at-point` (in `eshell-complete-lisp-symbol`, in `eshell-complete-parse-arguments`) and then cancels `pcomplete`.

@Henry That works great on eshell *except* when completing `(some-elisp-`. Unfortunately, I think the only fix for this is to fix eshell so it doesn't pull shenanigans like this.

**Comment by dgutov** [comment]
> I think the only fix for this is to fix eshell

If you have a good way to explain/reproduce this, please `M-x report-emacs-bug`.
