### ISSUE TITLE
set different faces for different backends

### ISSUE THREAD

**Issue by zhuzhongshu** [company-mode/company-mode#208]
AC could set different faces for different backends, how can  I do this with company?

**Comment by marcinant** [comment]
:+1:

**Comment by gse4me** [comment]
+1

**Comment by stardiviner** [comment]
@dgutov I have not checked out source code, but is it possible to have object-oriented inherit attributes. Let extra different company backends inherit from company-backend which has a face by default, then every extra different company backends can have faces like `company-python-face`, `company-robe-face`, `company-cider-face` etc ?

**Comment by dgutov** [comment]
It's not particularly hard to design or implement, I'm just not sure it's a good idea. Any examples from recent editors? Like Atom, for instance.

**Comment by stardiviner** [comment]
@dgutov . Yes. This can make use [all-the-icons](https://github.com/domtronn/all-the-icons.el) as annotations as possible.

**Comment by dgutov** [comment]
Using icon might be better in a way, but that's a different request.

And also, that would basically force all backend authors to come up with icons.

**Comment by stardiviner** [comment]
Can leave default icon empty for extra backends. No need to force it I think. Yes using icon is better.

**Comment by dgutov** [comment]
> No need to force it I think.

And yet, the backends without icons will look markedly worse than the ones with icons.

Note for later: a backend call also choose to show different icons for different completions, like here: https://code.visualstudio.com/docs/editor/intellisense#_types-of-completions

This might actually be more useful than distinguishing between backends.

**Comment by stardiviner** [comment]
I make a screenshot from CIDER (Clojure completion backend) with company-mode.
![company-mode annotations using icons](https://user-images.githubusercontent.com/378699/29848358-9e3a960e-8d52-11e7-980e-2c4eb80d96bd.png)
And here is my configuration:
```elisp
(setq cider-completion-annotations-alist
      `(("function" ,(all-the-icons-faicon "file-text-o" :face 'company-tooltip-annotation :v-adjust -0.05))
        ("macro" ,(all-the-icons-faicon "file-text-o" :face '(:background "white") :v-adjust -0.05))
        ))
```

**Comment by dgutov** [comment]
We have icons now.
