### ISSUE TITLE
youcomplete me vim behaviour: is possible??

### ISSUE THREAD

**Issue by cocodrino** [company-mode/company-mode#216]
Hi..I'm interested in know if is possible get a similar behaviour to vim autocompletion..in vim when I type I get a popup displaying the suggestions (but they are not enable yet) then I can press tab and choose the first suggestion, or I can press tab again and select the second suggestion, press again and I going iterating across the popup..when a suggestion is enable automatically is added, so I don't need confirm

This is pretty nice because I dont need move my fingers to the arrow keys and I dont need a key combination for change, is pretty fast...

**Comment by dgutov** [comment]
@cocodrino @alexmurray Please try the code snippet I posted in the neighboring issue: https://github.com/company-mode/company-mode/issues/246#issuecomment-68538735

**Comment by alexmurray** [comment]
@dgutov Yep that seems to work nicely - thanks!

**Comment by dgutov** [comment]
@alexmurray Good. Do you think this command should be added as-is? I.e. first tab expands to the common prefix, the following cycle. Or the first tab should also cycle if there's nothing to expand?

**Comment by alexmurray** [comment]
I think it is fine as it currently is but if you have an implementation of the second one I'd be happy to try it out to see which seems better.

**Comment by dgutov** [comment]
Here:

```emacs
(defun company-complete-common-or-cycle ()
  (interactive)
  (when (company-manual-begin)
    (let ((tick (buffer-chars-modified-tick)))
      (call-interactively 'company-complete-common)
      (when (eq tick (buffer-chars-modified-tick))
        (let ((company-selection-wrap-around t))
          (call-interactively 'company-select-next))))))

(define-key company-active-map [tab] 'company-complete-common-or-cycle)
(define-key company-active-map (kbd "TAB") 'company-complete-common-or-cycle)
```

**Comment by alexmurray** [comment]
It doesn't work for me - tab doesn't appear to do anything in this case...

**Comment by dgutov** [comment]
@alexmurray That's odd, works fine here (at least in emacs-lisp-mode). Are you using the latest MELPA version?

**Comment by angelic-sedition** [comment]
@Sarcasm It seems to me like @sooheon was referring to being able to tab through the original popup suggestions and have them expand not to the fuzzy matching.

@dgutov 
I think it would be nice looking to have to be able to insert while keeping the popup active, but like you say, it's not all that useful. Still to replace that sort of functionality, `(setq company-auto-complete t)` isn't the same. I'd also like be able to tab through the original popup and have the selected item expand but only when tab is pressed at least once (avoiding #246).

**Comment by dgutov** [comment]
> Still to replace that sort of functionality, (setq company-auto-complete t) isn't the same.

What exactly do you feel missing? `company-auto-complete` won't take effect if the popup was simply displayed automatically, and you haven't interacted with it (whether it's via pressing `TAB`, `M-n` or using other commands).

This will give you better visualization in most cases (but not when "fuzzy" matching is used, because that's hard to do in a sane way):

```emacs
(defun company-preview-if-explicit-action-frontend (command)
  (when (or (not (eq command 'post-command))
            (and
             (company-explicit-action-p)
             company-common
             (or (eq (company-call-backend 'ignore-case) 'keep-prefix)
                 (string-prefix-p company-prefix company-common))))
    (company-preview-frontend command)))

(setcar
 (memq 'company-preview-if-just-one-frontend company-frontends)
 'company-preview-if-explicit-action-frontend)
```

**Comment by angelic-sedition** [comment]
The difference from the vim completion plugins (neocomplete is the same) is that there isn't automatic completion even if there's only one suggestion. `company-auto-complete` will automatically expand the last highlighted item when the popup menu is accessed, but it also will automatically expand if there is only one option and no menu popup. For example, in a python file with argparse imported, if I type "arg" and then a space in a comment, it will expand when I don't want it to. I think it would be nice these two features of `company-auto-complete` decoupled. That would solve both this issue and #246 I think.

Apart from the fuzzy matching (which I haven't really used anyway), I like this way of visualizing the completion even better. Thanks!

**Comment by dgutov** [comment]
@angelic-sedition How about `(setq company-auto-complete 'company-explicit-action-p)`, then?

There's no difference in `company-auto-complete` logic between single-candidate and multiple-candidates cases, but its value can be a function which determines whether to go ahead.

**Comment by angelic-sedition** [comment]
That's just as good then. Thanks.

**Comment by dgutov** [comment]
Terrific. :)

And the original submitters of #246 and this issue don't participate in the discussions anymore, so let's consider them resolved.
