### ISSUE TITLE
Company hangs on large number of candidates:

### ISSUE THREAD

**Issue by tuhdo** [company-mode/company-mode#242]
To reproduce:

- Clone the linux source tree.
- Run `gtags` at project root.
- Open any C file inside the project root. run `company-gtags`.
- Wait the disk spinning for a while.
- After the candidates are displayed, keep scrolling down with arrow key until Emacs is hanged. This happens quick, but you should hold the arrow key for a while until it happens (like 5 or 10 or 20 seconds).

**Comment by dgutov** [comment]
> After the candidates are displayed, keep scrolling down with arrow key until Emacs is hanged.

You should test this in the current Emacs master. I still see GC pauses, but no freezes so far.
