### ISSUE TITLE
Don't Auto-complete When I Don't Mean to

### ISSUE THREAD

**Issue by Haroogan** [company-mode/company-mode#246]
I would like to keep the following settings everywhere:

```
(set 'company-auto-complete t)
(set 'company-idle-delay 0)
```

However, the problem is that when I type in comments and/or in plain text files I always get auto-completion when I don't need to. For example, typing word `be` and then hitting `SPC` may result in auto-completion of word `because`. This is quite annoying and that's indeed not the behavior I'm looking for.

As I see it, the issue stems from a very simple fact: when popup with completion candidates opens we immediately have the first candidate automatically selected for us and that's why it gets auto-completed according to `company-auto-complete-chars`. How about not selecting anything by default in the popup? Is there any option available for this or if not, then may I hope for the new feature?

By the way, it looks somewhat similar to #216.

**Comment by dgutov** [comment]
@PythonNut Here's an easy modification of the `company-complete` definition that should come close:

```emacs
(defun company-complete-common-or-cycle ()
  (interactive)
  (when (company-manual-begin)
    (if (eq last-command 'company-complete-common-or-cycle)
        (let ((company-selection-wrap-around t))
          (call-interactively 'company-select-next))
      (call-interactively 'company-complete-common))))

(define-key company-active-map [tab] 'company-complete-common-or-cycle)
(define-key company-active-map (kbd "TAB") 'company-complete-common-or-cycle)
```

What may or may not be a drawback: the first time it's called, it always does `company-complete-common`, even if there's no longer common prefix. On the pro side, it's predictable, on the con side, it can waste a keypress. It's not hard to change the definition to not do that: call `company-select-next` anyway if the value returned by `buffer-chars-modified-tick` doesn't change after calling the former function.

> We don't care about the candidates out-of-view that break the common prefix.

This, I think would be stupid. We should care, or it's too easy to miss a definition.

**Comment by PierreR** [comment]
Coming from AC I also have some difficulties to adapt my habit so I have tried the above function. Is it possible to add the last point from @PythonNut for reference ? 
`SPC` always terminates completion and inserts a space. Is there an option to do this ?

**Comment by dgutov** [comment]
@PierreR What exactly does "terminate" mean in that context?

**Comment by PierreR** [comment]
I would like `space` to do what the combination of `return + space` is doing: accept the highlight completion and insert a space.

**Comment by dgutov** [comment]
@PierreR `(setq company-auto-complete t)` will do that.

**Comment by dgutov** [comment]
The proposal, as originally stated, doesn't make a lot of sense to me. The subsequent discussion seems to have come to a conclusion.

Closing.

**Comment by Haroogan** [comment]
I am very sorry that I didn't participate in the issue lately. I'm very busy these days, and I don't have time to even tweak my Emacs. This issue is extremely important for me. Would it be possible to just let this issue float for some time until we both are willing to get back to discussion? Sorry for inconvenience, Dmitry.

**Comment by dgutov** [comment]
@Haroogan We can always reopen it later, if you have any fresh suggestions. But the current proposal looks like a non-starter: there are a lot of places in the code that assume that some candidate is selected.

**Comment by PythonNut** [comment]
@Haroogan If you want, we can still talk. I, personally, believe there are other solutions to your problem that can be used right now with no modifications to `company`. After all, having a blank first candidate is essentially the same as doing nothing with the current candidate unless you ask for it.

**Comment by amosbird** [comment]
@PythonNut Hi, that sounds like a good idea to wordaround this. How can I let `company` always generate one candidate at the top that is exactly the same of current input string? The purpose of doing this is to bypass the confliction of `yas-next-field` and `company-complete-selection` while still have the completion candidates showing as reference.
