### ISSUE TITLE
Add an option to display source of candidates in the menu

### ISSUE THREAD

**Issue by fniessen** [company-mode/company-mode#251]
(I've already discussed this a while ago with Dmitry, but am adding it now in the hope it will get done someday).

For debugging and/or optimization purpose (checking that candidates are ordered so that the most probable are presented at the top), it'd be good to have the possibility to enable an "extended view" of the menu where -- next to each candidate -- one could see:
- the backend used, and
- the specific set where it comes from (buffer/file name, etc.).

**Comment by dgutov** [comment]
I think the new "icons" feature provides a good enough substitute: while it doesn't show the exact backend (which would be fairly verbose), it indicates the types of completions, so one can distinguish between "smart" completions and words-in-buffers/snippets/ keywords.

When really needed, the backend of the currently selected completion can be glanced from the mode-line (at least by default; some alternative mode-line packages hide that info).

The `company-posframe` frontend (third-party one) also shows a list of backends at the bottom. Even if its current behavior does not show the exact info you need, it could should be easier to enhance. As a mode-line alternative, that is.
