### ISSUE TITLE
company-cmake.el: create candidates from project_name

### ISSUE THREAD

**Issue by redguardtoo** [company-mode/company-mode#270]
see #197, it occurred to me today that there could be a simpler design.

We don't need automatic way to find the project names. A user specified name is good enough
`company-cmake-project-names`, 

`project name` is the the name specified by cmake statement `project`, usually at the beginning of the CMakeLists.txt.

The actual project names could be created by executing shell command or hard coded string list. Anyway, it's user's setup. He could set up like this:

``` lisp
(setq company-cmake-project-names '("proj1" "proj2"))
```

The other key point is that cache, the cache will only store the constant items. the candidates created from project name will never go into the cache.

**Comment by dgutov** [comment]
Are those variables used a lot? Maybe it's not worth the complexity. The selective cache behavior you've mentioned looks kinda tricky to implement.

**Comment by Sarcasm** [comment]
For what it's worth, `PROJECT_NAME` is a CMake variable. If one is smart enough to make a shell command that return the project name, he should be able to refer to the CMake variables via the notation:

```cmake
${PROJECT_NAME}_FOO
```
Eventually company could provide special completions for prefixes like that `${PROJECT_NAME}_` and `${CMAKE_PROJECT_NAME}_`.

See http://www.cmake.org/Wiki/CMake_Useful_Variables

**Comment by dgutov** [comment]
> If one is smart enough to make a shell command that return the project name...

That seems like a good direction. There are some options here: http://stackoverflow.com/questions/8474753/get-cmake-variable

**Comment by Sarcasm** [comment]
Well instead of all this hook stuff, how about a file local variable `company-clang-project-name`.
Whether it's a hook, a directory local variable or anything else that set this up is left to the user.

**Comment by dgutov** [comment]
I don't see anything here about hooks.

And why make it customizable at all, if the backend can get the exact value via a shell command?

**Comment by Sarcasm** [comment]
I'm confused for some reasons I was sure the initial post talked about hooks. Excuse me for the disruption.

> And why make it customizable at all, if the backend can get the exact value via a shell command?

I would be interested in such command that works everywhere. You are on Windows, you use CMake to cross-compile a Linux project because you are working on an embedded project, then CMake generation won't work unless some arguments are specified. Also detecting the root CMakeLists.txt is tricky, it can be anywhere. I just thought it would be better if company was only taking care of allowing a customizable project name.

**Comment by dgutov** [comment]
> it would be better if company was only taking care of allowing a customizable project name.

Ok then, sounds good to me.

**Comment by Sarcasm** [comment]
I think, I'm not sure, that more than one project name can exist at a time (e.g. sub-projects). I guess @redguardtoo knows better than me, his initial proposal seems to be in the plural form.

**Comment by dgutov** [comment]
One could use buffer-local values, couldn't they?

The proposal by @redguardtoo sounds like the new var would be a `directory . project-name` alist (I personally dislike this approach), or a list of project names, which means false positives.

**Comment by Sarcasm** [comment]
> One could use buffer-local values, couldn't they?

That's what I had in mind.

> EDIT: Not sure how CMake works with sub-projects.

I guess we can ignore sub-projects, if it becomes necessary one could add another buffer local variable, which this time would be a list e.g: `company-cmake-sub-project-names`.

**Comment by dgutov** [comment]
No progress for some years now, but patch still welcome.
