### ISSUE TITLE
Template function object auto completion behavior

### ISSUE THREAD

**Issue by nawhtel** [company-mode/company-mode#271]
I don't know if I name it correctly by "template function object", but c++11 function like <i>make_shared</i> didn't have a right behavior when I try to auto complete it.
I think that it should be something like this:
<Code>
std::make_shared\<typename>(Arguments...)
</Code>
But what it gives back is:
<Code>
std::make_shared(Arguments...)
</Code>
the auto completion skips the template arguments and jumps directly to function arguments, I don't know if there is a variable to adjust it or this is clang's issue.

**Comment by dgutov** [comment]
Thanks for the report, turns out this side of template functions support in company-clang was only half-done. Will fix.
