### ISSUE TITLE
auto window-scrolling after completion list shows up

### ISSUE THREAD

**Issue by c02y** [company-mode/company-mode#272]
When I'm editing a file, if the completion list shows up, the text in the current window will always jump (sometime it will jump a few lines but mostly it will jump to the top of the window), after finishing typing or selecting the right candidate, it will jump back the original place, I got a gif to show what I mean.

![recorded](https://cloud.githubusercontent.com/assets/2135996/5641802/f689c2f8-9679-11e4-978d-551d8dbf039d.gif)

NOTE: this problem cannot be replicated very easily, even by myself, even in the same file. But when I'm editing a source code file or org file, this happens a lot, it's really annoying.

I don't know if it is caused by company itself or not but it only happens in company completion list, so I post the problem here.

If you need anything else, let me know.

---

**Update**:

After analyzing my whole `init.el`, this problem is caused by [sublimity](https://github.com/zk-phi/sublimity), already posted [an issue](https://github.com/zk-phi/sublimity/issues/21).

**Comment by dgutov** [comment]
> this problem is caused by sublimity, already posted an issue

Great, thanks for the analysis!

**Comment by codygman** [comment]
I had this issue with olivetti-mode as well in case others stumble upon this. I verified by turning off olivetti-mode and observing that the lines don't move or "shift".

**Comment by dgutov** [comment]
Nothing more actionable here, so closing.

Hopefully the mentioned modes have already fixed this problem on their side, or will do that soon-ish.
