### ISSUE TITLE
Error when searching a candidate that contains a digit

### ISSUE THREAD

**Issue by Sarcasm** [company-mode/company-mode#273]
Hello Dmitry,

I have a list of candidates like so:

* vec3
* vec4
* mat3
* mat4
* ivec3
* ivec4
* ...

I want to search in the long candidate list everything that contains `vec3` (should match `vec3` and `ivec3`).

I can search `vec` but as soon as I type the `3`, company triggers an error:

     Error in post-command-hook (company-post-command): (wrong-type-argument sequencep stop)

**Comment by dgutov** [comment]
Hi Guillaume,

I'm having trouble reproducing this. I think I saw it once, but after that, in every session and with every backend I've tried, searching for a number works fine. For instance, with this Lisp code:

```
(let (var1
      var2 var3
      mat3 mat4)
  v|)
```

initiating completion and typing `ec3` highlights the relevant portion of the third candidate.

**Comment by Sarcasm** [comment]
So I tried at home your example and while the first few times I had the feeling something wasn't right it looks like it worked properly the other times.

But today, re-testing at work (Emacs 24.3.1) it is still present.

With your example I get a different error when searching a digit, i.e: `ar1` or `1`, I get:

    Matching input is required

My example with company-irony is still producing `Wrong type argument: sequencep, stop`. I think something looks shady, do you have any tips to debug the company-mode post-command? To have something easier to debug?

**Comment by dgutov** [comment]
> the first few times I had the feeling something wasn't right

The might be because the interface is clunky and different from isearch.

> But today, re-testing at work (Emacs 24.3.1) it is still present.

Even starting with `emacs -Q`? I've tried that version, and haven't seen any difference.

> I think something looks shady, do you have any tips to debug the company-mode post-command?

`edebug-defun` works for me, but it's probably supported only starting with Emacs 24.4.

But you should probably look at `company-search-map` and see why `company-search-printing-char` isn't called. I suspect it might be related to input methods. You aren't using the keypad, are you?

**Comment by Sarcasm** [comment]
> Even starting with `emacs -Q`? I've tried that version, and haven't seen any difference.

Just tested with `emacs -Q`, and company version: ~/.emacs.d/elpa/company-20150102.1526/

> `edebug-defun` works for me, but it's probably supported only starting with Emacs 24.4.

Looks like it work in Emacs 24.3.1, just not sure how to debug this yet.

> You aren't using the keypad, are you?

Woopsy-doopsy. I am, non-keypad digit seems to work.

**Comment by dgutov** [comment]
AFAIK, debugger in post-command only started working in 24.4. In earlier versions, only print-debugging.

> I am, non-keypad digits work fine.

Then adding keypad bindigns to `company-search-map` would fix this. I'd like to investigate first why you got the error message about `stop`, though. Did that only happen with `company-irony`?

**Comment by Sarcasm** [comment]
It happens only with `company-irony`, `company-clang` doesn't exhibits this behavior. I'm surprised, I don't think I do anything *hacky* in `company-irony`.

**Comment by dgutov** [comment]
Indeed, it abides by the API, but does something unusual: `(company-irony 'prefix)` after `3` returns `stop` (IOW, you explicitly don't complete numbers). To reproduce:

Create a new line, type `M-x company-irony`, type `3`. See the same error.

Good to know, will fix that.

**Comment by Sarcasm** [comment]
I'm not sure to understand everything.

First, is that bad to not complete number? I know that I don't want to complete floats for example otherwise an extensive completion request is made when it doesn't make sense:

```cpp
float f = 3.| // <- don't want to trigger completion here
```

Until now, all irony-mode prefixes returned for completion are valid C++ identifiers `[a-zA-Z_][a-zA-Z_0-9]*`.

Do you think I need to fix something in company-irony?

Also I'm not sure to understand your fix, why was the prefix "interrogated" when I was in search mode? I trust your fixes, just curious.

A little bit off-topic, but would do you think that the search could filter the candidate list so that only things that matches are displayed? I can elaborate (maybe on another issue if that's not clear).

Anyway thank you for the fix! :)

**Comment by dgutov** [comment]
No problem, thanks for the report.

> Do you think I need to fix something in company-irony?

Nope, it's all fine. :)

> why was the prefix "interrogated" when I was in search mode? I trust your fixes, just curious

Pressing keypad was interpreted as `company-search-other-char`, which disabled the search mode and "replayed" the last event as input. That led to the new prefix being examined.

> do you think that the search could filter the candidate list

Apparently, we already have a command for this (`'company-filter-candidates`, bound to `C-M-s`). I'm looking at it right now, and it's broken. :( Right now, though, you can press `C-o` while in search mode, and that will filter out all non-matching candidates, as well as quite the search mode.

**Comment by Sarcasm** [comment]
Okay that's great, I will try to remember these.
Also glad to see that backspace has be bound, I thought it was a little bit weird without, very annoying to make a typo. :)

**Comment by dgutov** [comment]
> I thought it was a little bit weird without

Me too. I didn't use the search much, though, but maybe that'll change. The search mechanism is still a little peculiar: no wrapping, typing new characters always searches forward.

But filtering seems to work fine now. Please test when you have the chance.

**Comment by Sarcasm** [comment]
> Please test when you have the chance.

I tested at work and that works better now. No issue, quite happy to have learned about `C-o` too! :)
