### ISSUE TITLE
Error when trying to pop up the completion window over a sufficiently long `after-string` overlay at the end of buffer

### ISSUE THREAD

**Issue by jmickelin** [company-mode/company-mode#274]
I'm getting the following error when `company-mode` tries to show the completion window right before an overlay on `(point-max)` that has the `after-string` property containing more than one line:

```
Company: Front-end company-pseudo-tooltip-unless-just-one-frontend error "Invalid search bound (wrong side of point)" on command post-command
```

Steps to reproduce:

1. Run

    ```elisp
    (setq my-ov (make-overlay (point-max) (point-max) nil t t))
    (overlay-put my-ov 'after-string "~\n~\n~")
    ```

2. Put cursor on any line at most 10 lines before the end of buffer.
3. Try to type a prefix to a completion.

The error seems to be caused by the call to `(vertical-motion 1)` in `company-buffer-lines` reporting that it has moved more than `1` line forward, when the point actually only moved at most one line. This seems to be fixed by replacing `vertical-motion` with the functionally equivalent (?) function `(lambda (n) (- n (forward-line n)))`.

**Comment by dgutov** [comment]
Thanks, I see the error.

> replacing vertical-motion with the functionally equivalent (?) function (lambda (n) (- n (forward-line n)))

Alas, not equivalent: `forward-line` moves by physical lines, whereas `vertical-motion` uses the visual lines. And we want the latter.

**Comment by dgutov** [comment]
@jmickelin I've pushed a workaround. Please see if it helps with your package.

**Comment by dgutov** [comment]
Anyway, I can see it does.

The recent commit in `emacs-24` Emacs branch fixed a smaller glitch with the last buffer character being hidden in certain similar circumstances.

**Comment by jmickelin** [comment]
Thank you!
