### ISSUE TITLE
strange behavior of company-irony after update to 20150109

### ISSUE THREAD

**Issue by zhuzhongshu** [company-mode/company-mode#275]
For company version 20141216, everything works well. While when I update it to 20150109, I find company-irony cannot complete something such as std::vector and std::endl which it can handle in version 20141216. 
More specifically, I have to switch to another back-end and switch back to company-irony to find the candidates std::vector or std::endl. (for instance: company-irony->company-yasnippet->company-irony)
My back-ends configuration is (company-irony company-yasnippet), I use command company-other-backend to invoke the completion

**Comment by Sarcasm** [comment]
Just for the record, I do not have this issue. Can you try to with a minimal Emacs configuration (start with `emacs -Q`)?

**Comment by zhuzhongshu** [comment]
>Can you try to with a minimal Emacs configuration (start with emacs -Q)?

What should I do after I open emacs with emacs -Q?

**Comment by Sarcasm** [comment]
Load and configure company, irony and company-irony.

For example:

```el
;; for company
(add-to-list 'load-path "~/.emacs.d/elpa/company-20150109.2226/")
(require 'company)
(add-hook 'after-init-hook 'global-company-mode)

;; for irony
(add-to-list 'load-path "~/.emacs.d/elpa/irony-FILL_DATE...")
(require 'irony)
(add-hook 'c++-mode-hook 'irony-mode)
(add-hook 'c-mode-hook 'irony-mode)
(add-hook 'irony-mode-hook 'irony-cdb-autosetup-compile-options)

;; then company-irony
(add-to-list 'load-path "~/.emacs.d/elpa/company-irony-FILL_DATE...")
(require 'company-irony)
(eval-after-load 'company
  '(add-to-list 'company-backends 'company-irony))
```

There might be some typos but that is the idea.

If you save this to a file (`init-file.el`) you can do:

    emacs -Q -l init-file.el

**Comment by zhuzhongshu** [comment]
I tried your method and find std::vector/string can be completed while std::endl still cannot. When I type std::, the popup window appears and I can see endl as a candidate, but when I continue to type "end", the only candidate left is ends, and I can't type "l" any more(because I turn on the "require matching" option).

**Comment by Sarcasm** [comment]
Can you post your sample code? I can complete `std::endl` in my setup with this code:

```cpp
#include <vector>
#include <string>
#include <iostream>

void foo()
{
    std::vector<std::string> v;

    std::cout << "foo" << std::end|
}
```

`|` represents the cursor position.

**Comment by zhuzhongshu** [comment]
Could you please add next line in your init file and try again? On my computer this command may be cause the problem.
(custom-set-variables
 (company-transformers (quote (company-sort-by-occurrence))))
Or use my minimal configure as follow:

(add-to-list 'load-path "~/.emacs.d/elpa/company-20150112.41/")
(require 'company)
(add-hook 'after-init-hook 'global-company-mode)
(custom-set-variables
 '(company-transformers (quote (company-sort-by-occurrence))) )

;; for irony
(add-to-list 'load-path "~/.emacs.d/elpa/irony-20141217.1417")
(require 'irony)
(add-hook 'c++-mode-hook 'irony-mode)
(add-hook 'c-mode-hook 'irony-mode)
(add-hook 'irony-mode-hook 'irony-cdb-autosetup-compile-options)

;; then company-irony
(add-to-list 'load-path "~/.emacs.d/elpa/company-irony-20140629.1118")
(setq irony-additional-clang-options (quote ("-std=c++11" "-I/usr/include/Eigen/Eigen/")))
(add-hook 'c-mode-common-hook
          (lambda ()
            (set (make-local-variable 'company-backends)  (quote (company-irony
                                                                  company-yasnippet
                                                                  company-files)))))

**Comment by dgutov** [comment]
Thanks for the report. I can't reproduce the behavior described here exactly with the given examples, but I see something similar with my own example file, when `company-sort-by-occurrence`.

Apparently, the problem is with `company--process-candidates` mutating the list saved into cache. Will fix, sorry about that.

**Comment by dgutov** [comment]
It should work now. Thanks again!

**Comment by zhuzhongshu** [comment]
Yes, it works well now! Thanks!
