### ISSUE TITLE
company-complete-common-or-cycle function definition is void

### ISSUE THREAD

**Issue by SASDOE** [company-mode/company-mode#276]
In company-mode 0.8.8, I get this when trying to use ```company-complete-common-or-cycle``` 
```++-mode
[yas] Loading for `cc-mode', just-in-time: (lambda nil (yas--load-directory-1 (quote /home/de-dum_m/.emacs.d/elpa/yasnippet-20141223.303/snippets/cc-mode) (quote cc-mode)))!
[yas] Loading compiled snippets from /home/de-dum_m/.emacs.d/elpa/yasnippet-20141223.303/snippets/cc-mode
Loading vc-git...done
if: Symbol's function definition is void: company-complete-common-or-cycle
Making completion list... [2 times]
Company version: 0.8.8
Making completion list... [2 times]
ad-Orig-delete-backward-char: Text is read-only
Quit
if: Symbol's function definition is void: company-complete-common-or-cycle```

**Comment by dgutov** [comment]
Works for me.

How are you trying to use it?

**Comment by SASDOE** [comment]
Sorry was just about to edit comment, turns out I had an old load-path for the previous version of company-mode.

Sorry for the trouble, and cheers for the good work

**Comment by SASDOE** [comment]
What is it supposed to do though? If I get the completion popup and press tab once more, it does not cycle

**Comment by dgutov** [comment]
> I think it does not work with this

It won't: the global map has the lowest priority. When the popup is open, `company-active-map` is enabled, and it has a different binding for `tab`. So, using `company-complete-common-or-cycle` in the global tab binding is useless. Do this instead:

```emacs
(define-key company-active-map [tab] 'company-complete-common-or-cycle)
(define-key company-active-map (kbd "TAB") 'company-complete-common-or-cycle)
```

**Comment by SASDOE** [comment]
Incredible. Cheers works great.

**Comment by dgutov** [comment]
You're welcome!

**Comment by SASDOE** [comment]
Sorry to use this closed thread, but it seems that the keybinding set as such will quite often not do anything. `M-x company-complete-common` when in this situation will bring the popup though.

**Comment by dgutov** [comment]
It won't do anything then the popup is not displayed. Hence the name of the keymap we modify above: `company-active-map`.

You should keep your previous `tab-indent-or-complete` binding as well (but don't bother using `company-complete-common-or-cycle` inside it).
