### ISSUE TITLE
Issue when filtering completion candidates with East-Asian characters

### ISSUE THREAD

**Issue by KenetJervet** [company-mode/company-mode#277]
I'm using company-mode with elpy. Company-mode has no problem in listing candidates with East-Asian characters.
![image](https://cloud.githubusercontent.com/assets/1560189/5754427/9b02237a-9cd3-11e4-9b87-7cb5272dcfe6.png)

However, after typing in any Asian character that invalidates all candidates, company-mode stops filtering and displays **EVERYTHING**, but incorrectly:
![image](https://cloud.githubusercontent.com/assets/1560189/5754507/cf5bb810-9cd4-11e4-9cff-ea10f52be6fb.png)

And the ways to reproduce this bug are weird to me:
Either:
* type in an Asian character that invalidates all the candidates.
* type in an Asian character that has some matches. Stop the completion process (e.g. C-g) and start the completion again (e.g. M-x company-complete).

P.S. I tried with some greek alphabet and this bug still exists. So I assume the same problem exists for all non-latin characters.

**Comment by dgutov** [comment]
Thanks for the report, but please describe a scenario I can follow easily (how does one type Japanese on a GNU/Linux system?). I found some odd behavior, but I'm not sure if it's the problem you're having.

To set Elpy aside, please use `M-x company-dabbrev-code` or `M-x company-dabbrev` (in a text-mode file) to initiate completion.

> displays EVERYTHING, but incorrectly

What exactly is incorrect there?

**Comment by KenetJervet** [comment]
@dgutov 
Hi, after some more investigation, I can confirm it's an issue from Jedi (the Python autocompletion backend for elpy)

I'll report this issue to Jedi and make a reference to this. Is that okay?

**Comment by dgutov** [comment]
@KenetJervet Sure, thanks.
