### ISSUE TITLE
delete-backward-char not working during code completion

### ISSUE THREAD

**Issue by r4nt** [company-mode/company-mode#279]
I got this problem description from a colleague:
"""When the menu of completions is shown it would be
cool if delete-backward-char would still work.  In my base I have
delete-backward-char bound to C-h and it seems that when the menu is
shown C-h is temporarily bound to some function that looks for some
documentation."""

**Comment by Sarcasm** [comment]
You would have to remove the `C-h` binding in `company-active-map`:

Right now it's bound to the following:

```el
(define-key company-active-map (kbd "C-h") 'company-show-doc-buffer)
```

I think the following will remove the binding properly, I'm not 100% sure:

```el
(define-key company-active-map "\C-h" nil)
```

**Comment by dgutov** [comment]
Right. Thanks, Guillaume!
