### ISSUE TITLE
When company popup is flipped,  arrow keys should be flipped too

### ISSUE THREAD

**Issue by PythonNut** [company-mode/company-mode#282]
When `(setq company-tooltip-flip-when-above t)` is used and the popup is flipped, the commands that cycle candidates are not (e.g. `company-select-previous-or-abort`). When this is the case, the user must press <kbd>&lt;down&gt;</kbd> to select one candidate up, and <kbd>&lt;up&gt;</kbd> to select one candidate down.

This might also apply to <kbd>M-n</kbd>/<kbd>M-p</kbd>, but interpreting <kbd>M-n</kbd> as a `next` seems to be consistent (it always goes to the next candidate), while the arrow keys are far more directional in meaning.

**Comment by dgutov** [comment]
That's already been discussed in the issue where the variable was introduced: https://github.com/company-mode/company-mode/issues/116#issuecomment-44218868.

In short: doesn't fit the abstraction. Feel free to write and bind your own wrappers around `company-select-*` commands. The value to check is:

```el
(let ((ov company-pseudo-tooltip-overlay))
  (and ov (< (overlay-get ov 'company-height) 0)))
```
