### ISSUE TITLE
company-ispell: Args out of range:

### ISSUE THREAD

**Issue by oahziur** [company-mode/company-mode#284]
Hi,

I use `company-ispell` in `org-mode`. When I type something like `don'`, `test'` in my org buffer, company mode continuosly give me the error, and I have to use `C-g` to stop the process.

Here are the error messages:
```
Starting "look" process...
Company: An error occurred in post-command
Company: Front-end company-pseudo-tooltip-unless-just-one-frontend error "Args out of range: "Don", 4, 3" on command post-command
Starting "look" process...
Company: An error occurred in post-command
Company: Front-end company-pseudo-tooltip-unless-just-one-frontend error "Args out of range: "Don", 4, 3" on command post-command
Starting "look" process...
Company: An error occurred in post-command
Company: Front-end company-pseudo-tooltip-unless-just-one-frontend error "Args out of range: "Don", 4, 3" on command post-command
```

Thanks

**Comment by dgutov** [comment]
Thanks for the report, the problem is the `look` command doesn't filter on the quote character when it's the last one, so we end up with `Don` in suggested completions, and we can't handle completions shorter than the input.
