### ISSUE TITLE
Deprecate `keep-prefix` as the value of `ignore-case`, and move it into backends

### ISSUE THREAD

**Issue by dgutov** [company-mode/company-mode#285]
- It's ugly.
- We pretty much can't avoid duplicates doing things the current way, since we have differentiate between `don` and `Don` up until the prefix is replaced.
- The performance impact is likely to be small. If not, wait until we support `bounds` and return completions sans prefix.

**Comment by iquiw** [comment]
I am using it in 2 back-ends [1], [2]. I will update them not to use `keep-prefix`.

[1] https://github.com/iquiw/company-cabal
[2] https://github.com/iquiw/company-restclient

**Comment by dgutov** [comment]
@iquiw Thanks for the heads-up.

There's no hurry, but if you implement handling `keep-prefix` in backends first, please let me know if you see a performance regression on any real-life data.

**Comment by iquiw** [comment]
@dgutov Sure.
But these back-ends use `keep-prefix` information only for capitalizing completion result.
(e.g. "Cont" => "Content-Type", "cont" => "content-type")

So I think I need only a flag (declared by `defvar`) to indicate whether the first character of prefix is upper case or lower case, instead of simulating `keep-prefix` behavior.

Could you let me know whether you think the above flag approach is proper or not?

**Comment by dgutov** [comment]
A user option would be good, but it seems to be it will decide capitalization of the whole candidate strings, not just the part inside prefix. Maybe that's what you meant, though.

Depending on its value, `cont` would be expanded to `content-type` or `Content-Type`.

**Comment by iquiw** [comment]
> it seems to be it will decide capitalization of the whole candidate strings, not just the part inside prefix. Maybe that's what you meant, though.

Yes. It is the current behavior.
The behavior is useful when one needs to edit file that someone wrote in different style.

It seems better to have user option though.

**Comment by iquiw** [comment]
I gave up the flag approach since prefix is changed when completing common with `(ignore-case t)`.

I will try to modify candidates according to prefix, something like follows.
```emacs-lisp
(concat prefix (substring candidate (length prefix)))
```

**Comment by dgutov** [comment]
But that's two different approaches. With the user option, you can choose to always display headers lowercased or capitalized, independent of the typed prefix.

**Comment by iquiw** [comment]
My comment was not clear, sorry.

I like the current behavior and want to keep it as is even after removing `keep-prefix`.
So when I add the user option, it will have 3 choices: lowercase, capitalized or the current behavior (i.e. depend on the first character).

**Comment by dgutov** [comment]
I see now, that makes sense.

**Comment by dgutov** [comment]
It seems this change will have to wait a while. It doesn't play well with the built-in cache:

If `company-dabbrev` tries to return completions with "keep prefix" already applied, that still won't happen to those retrieved from cache, if they were saved for e.g. an empty prefix. And I don't see a generic way to "postprocess" entries retrieved from cache that would be friendly to grouped backends.

A solution would be to provide a "cache until the end of the current completion" macro that each backend that wants caching would wrap around its "find completions" logic. That should go well after the majority of backends transition to `completion-at-point-functions`.
