### ISSUE TITLE
company-filter-candidates not working

### ISSUE THREAD

**Issue by iquiw** [company-mode/company-mode#289]
With company v0.8.9, when typing a character after pressing "C-M-s", filter does not work.
It acts like just typing the character without "C-M-s".

I suppose the following is required in `company-filter-candidates`.
```emacs-lisp
(company-enable-overriding-keymap company-search-map)
```

**Comment by dgutov** [comment]
Good catch, thanks. `C-M-s` gets captured by Unity on my system, so I didn't test it as well as I could.
