### ISSUE TITLE
company-lighter is not customizable

### ISSUE THREAD

**Issue by milkypostman** [company-mode/company-mode#290]
I will try to write up a PR to fix this if I get time.

**Comment by dgutov** [comment]
Would you be fine with a defvar?

**Comment by milkypostman** [comment]
Isn't it already a defvar? Why not defcustom?

**Comment by dgutov** [comment]
Currently, its value is changed at runtime. The change I have in mind would make it use the mode-line format, like 3716acbb5529092fe7697c18f3a02e3919b02bfb did to `company-search-lighter`. I'll have to see if there are any performance concerns.

> Why not defcustom?

Would you make the user edit the mode-line format structure? With what `:type`?

**Comment by milkypostman** [comment]
I didn't originally understand your response but now I do. But I already tried to make my suggestion in #291 

Customizable variables are really no different than `defvar` except that the customize function can see them and present the UI. I am trying using customize as much as possible instead of `setq` lately and it's been OK. I think that startup is a bit faster and it doesn't have as many problems with variables that are unknown but still trying to be set. Meaning if you don't have a package loaded you can still have the variable set.
