### ISSUE TITLE
selection does not work correctly when filtering search 

### ISSUE THREAD

**Issue by roshanjames** [company-mode/company-mode#292]
I have an issue with selection and navigation in the dropdown after filtering a search. 

After [company-complete] I hit [C-s] and [C-o] to search with filtering. After the dropdown has been filtered to the choice I want if I hit the up or down arrow keys the dropdown switches back to its unfiltered form.  Similarly if I hit enter after filtering search results, the currently highlighted entry on the dropdown is not selected. 

I am on version 0.8.10-cvs.

**Comment by iquiw** [comment]
I would like to see `M-0`, `M-1`, ..., `M-9` bindings in company-search-map, too. :-)

**Comment by dgutov** [comment]
Thanks for the report, both issues should be fixed now.

@iquiw Also done.

**Comment by iquiw** [comment]
Thank you!

**Comment by roshanjames** [comment]
Thanks Dmitry. I just installed the latest and this works!
