### ISSUE TITLE
Search filtering does not persist

### ISSUE THREAD

**Issue by roshanjames** [company-mode/company-mode#293]
Can we have a way to make search filtering persist across different invocations of company-complete? Alternately, is it possible to have a single key stroke that is the equivalent of hitting both C-s and C-o?

**Comment by dgutov** [comment]
That key stroke is `C-M-s`. It might not work, though, if your desktop environment doesn't pass that key through to Emacs.

**Comment by roshanjames** [comment]
Thanks for your response. It turns out that Unity does indeed capture that key combination. 

I would like to use company-complete to get the dropdown (since I think the prefix based completion is indeed the right default behavior), and then I would like to hit a key combination (of my choosing) to do the equivalent of company-filter-candidates. Is there a way to remap the key combinations that become active after the dropdown has been displayed?

**Comment by dgutov** [comment]
Sure, you just modify that keymap:

```el
(eval-after-load 'company
  '(define-key company-active-map (kbd "C-o") 'company-filter-candidates))
```

**Comment by roshanjames** [comment]
That works. Thanks. I am not as keen on having filtering persist now that I have a keybinding that does what I want. Feel free to close this issue.

**Comment by dgutov** [comment]
No problem.
