### ISSUE TITLE
handling company-default-lighter

### ISSUE THREAD

**Issue by holomorph** [company-mode/company-mode#297]
Setting the custom value `company-lighter-base` to nil results in the lighter being a single empty space. I suppose `company-lighter` should handle whether `company-lighter-base` is empty.

I know I can just as well set `company-lighter` to nil.

As a side note, the version has been bumped and no tags have been pushed.

**Comment by dgutov** [comment]
> I suppose company-lighter should handle whether company-lighter-base is empty.

How exactly would you have it behave if the "lighter base" is a nil? I think the fact that that value is incompatible with the declared type (`string`) should be enough to tell the user not to do that.

> As a side note, the version has been bumped and no tags have been pushed.

Thanks for the reminder, will add.

**Comment by holomorph** [comment]
> How exactly would you have it behave if the "lighter base" is a nil?
Okay, empty string then.  If the base is empty, the whole lighter should be empty unless there's something to add to it, instead of being the single space in `company-lighter`

**Comment by dgutov** [comment]
I don't see how that follows. And what's the problem with setting `company-lighter` to nil?

**Comment by holomorph** [comment]
I figured the right thing to alter was the defcustom rather than the variable using it.  No problem setting `company-lighter` to nil. Feel free to close.

**Comment by dgutov** [comment]
If that will become a common practice, I'll make `company-lighter` a defcustom too. Like Flycheck does with `flycheck-mode-line`.

For now, closing. Thanks.
