### ISSUE TITLE
Company: Front-end company-pseudo-tooltip-unless-just-one-frontend error 

### ISSUE THREAD

**Issue by andyque** [company-mode/company-mode#298]
When I input some Chinese characters, if the completion candidates is very long, it will always give me this kind of error message in echo area.

```
Company: Front-end company-pseudo-tooltip-unless-just-one-frontend error "Args out of range: 0, 18" on command post-command
```

My company-mode version is 20140901.1425.

How could I get rid of this annoying error message?
Thanks.

**Comment by dgutov** [comment]
Please give an example of that Chinese input, including buffer contents (one which includes "very long" candidates).

**Comment by dgutov** [comment]
@andyque Hello?
