### ISSUE TITLE
Company complete doesn't play nice with YaSnippet c/c++ header snippet.

### ISSUE THREAD

**Issue by iMultiPlay** [company-mode/company-mode#300]
I asked the emacs stackexchange for help on this issue at this topic:
https://emacs.stackexchange.com/questions/7900/company-completion-within-yasnippet-snippet?noredirect=1#comment12441_7900

My configuration was:

(global-company-mode)

(global-set-key (kbd "C-SPC") 'company-complete)

(setq company-tooltip-limit 20)                      ; bigger popup window
(setq company-idle-delay .3)                         ; decrease delay before autocompletion popup shows
(setq company-echo-delay 0)                          ; remove annoying blinking
(setq company-begin-commands '(self-insert-command)) ; start autocompletion only after typing

and for yasnippet:

(yas-global-mode 1)

Thank you!

David

**Comment by dgutov** [comment]
You must have non-default company-mode backends and/or additional snippets enabled.

When I do `M-x company-complete` after `#include`, nothing happens. Even if I set `company-backends` to `'(company-yasnippet company-dabbrev-code)`, I don't get anything after typing `#include`.

**Comment by dgutov** [comment]
IOW, the configuration you've posted is incomplete.

**Comment by moonlite** [comment]
@iMultiPlay are you perhaps using [company-c-headers](https://github.com/randomphrase/company-c-headers) ?

**Comment by dgutov** [comment]
If so, this problem may be the same as https://github.com/randomphrase/company-c-headers/issues/6

**Comment by iMultiPlay** [comment]
I do have company-c-headers, so my issue is equal to the one posted by dgutov. Thank you all!
