### ISSUE TITLE
(Feature) Add a border to the menu

### ISSUE THREAD

**Issue by fniessen** [company-mode/company-mode#302]
Is it possible to get a 1px border line (eventually, whose color could be customized) around the menu?

Thanks!

**Comment by dgutov** [comment]
That's pretty much impossible. But I'll see about it when we have a GUI popup.

**Comment by fniessen** [comment]
I don't know if that's similar, but I was asking for that because Company-quickhelp does have such a border (see http://screencast.com/t/7jdNGc4DMluz).

**Comment by dgutov** [comment]
It uses a different mechanism (not an overlay).
