### ISSUE TITLE
Add a face for quick-access numbers

### ISSUE THREAD

**Issue by fniessen** [company-mode/company-mode#303]
Can you add a face for the quick-access numbers?  Right now, they're fontified in the default tooltip face, which is not as nice (see http://screencast.com/t/K9YwiWJa) when we want to have the "different part" of the candidates bolded.

Thanks in advance!

**Comment by dgutov** [comment]
Thanks, that's a good idea, but a bit awkward to implement right now.

I'll keep this in mind for later.
