### ISSUE TITLE
Can I user-defined some auto-fill word?

### ISSUE THREAD

**Issue by yu-yuxuan** [company-mode/company-mode#304]
I find when I write code of Makefile or something related with openmp. I cannot get some auto-fill words. So can I define mine in a text list that can be used? Thanks

**Comment by dgutov** [comment]
Yes: you can add an entry to `company-keywords-alist` for that major mode.

**Comment by yu-yuxuan** [comment]
Thanks
I add the following code to my el file

(add-to-list 'company-keywords-alist (cons 'Makefile-mode ".PHONY" "OBJECTS" "gfortran"))
(add-to-list 'company-keywords-alist (cons 'f90-mode "omp_lib" "!$omp" "omp_set_num_threads"))

**Comment by dgutov** [comment]
If it works fine, please close the issue.

**Comment by yu-yuxuan** [comment]
the code is not working, is there something wrong? Thanks
```
(add-to-list 'company-keywords-alist (cons 'Makefile-mode ".PHONY" "OBJECTS" "gfortran"))
(add-to-list 'company-keywords-alist (cons 'f90-mode "omp_lib" "!$omp" "omp_set_num_threads"))
```

**Comment by dgutov** [comment]
* The Makefile major mode is `makefile-mode`. Note the lower first letter.

* The second argument to `cons` should be a list. Try this instead:

    ```el
(add-to-list 'company-keywords-alist '(makefile-mode ".PHONY" "OBJECTS" "gfortran"))
```

* `f90-mode` already has some "keywords" configured. To add to that list, try:

    ```el
(add-to-list 'company-keywords-alist
             (cons 'f90-mode (nconc '("omp_lib" "!$omp" "omp_set_num_threads")
                                    (cdr (assq 'f90-mode company-keywords-alist)))))
```

**Comment by yu-yuxuan** [comment]
Thanks, it works partially
In the `makefile-mode`, I need to use `M-x company-keywords`. Not automatically pop up
But in f90-mode. It works great except for "!$omp"

**Comment by dgutov** [comment]
For `makefile-mode`:

```el
(add-hook 'makefile-mode-hook
          (lambda ()
            (setq-local company-backends '((company-capf company-keywords)))))
```

Regarding `!$omp` and, actually, `.PHONY`: they don't work, because `company-keywords` uses the current symbol as completion prefix, and `!` (in `f90-mode`), and `.` (in `makefile-mode`) are not considered part of a symbol. So you can simply add `PHONY` and `$omp` to respective lists instead, and enjoy slightly less precise completion.

**Comment by yu-yuxuan** [comment]
Thank you very much
