### ISSUE TITLE
How to know if completion for a specific backend is happening?

### ISSUE THREAD

**Issue by Sarcasm** [company-mode/company-mode#305]
Hi Dmitry,

I was wondering what is the best way (if there is a reliable one?) to know whether or not company completion is happening, more specifically I would like to know if a specific backend is running.

I think I have at my disposable some hooks:

* `company-completion-finished-hook`
* `company-completion-cancelled-hook`
* `company-completion-started-hook`

Or maybe simply check if `company-backend` contains my backend

Will any of this work in a reliable way?

**Comment by dgutov** [comment]
Hi Guillaume,

`company-backend` being equal to, or including, your backend should be a pretty reliable indicator.

These hooks are never passed the value of the current backend, so you'd have to check the aforementioned variable anyway.

What's the use case, though?

**Comment by Sarcasm** [comment]
> company-backend being equal to, or including, your backend should be a pretty reliable indicator.

Okay, thanks.

> What's the use case, though?

I'm still getting my head around that but it's for on-the-fly syntax check.

I have 2 sources for diagnostics:
1. I'm parsing the buffer and get some diagnostics.
2. I'm making a completion request and I get diagnostics along with the completion. This diagnostics may be different from `1.`, for example it will not say "hey there is an error at the symbol you are currently completing".

So what I would like to do is to use the completion diagnostics during completion, and normal diagnostics otherwise.

Does that sound reasonable to you?

I'm still deciding whether or not that is the proper way to go.

**Comment by dgutov** [comment]
Maybe skip checking if the completion is being performed, and look directly at some value that the completion function sets?

Even if your backend is current and completion is being performed, can you be reasonably sure that the diagnostic data is already fetched and up to date? You'd probably have to compare something with `buffer-chars-modified-tick` anyway.

**Comment by Sarcasm** [comment]
> Even if your backend is current and completion is being performed, can you be reasonably sure that the diagnostic data is already fetched and up to date?

Yes, that's the reason I would like to avoid making unnecessary, slightly wrong and costly parsing requests.

For completion, I do not use `buffer-chars-modified-tick` but I'm checking the current completion context, so one can type the candidate text and I will still consider the parsing for completion to be up-to-date (even though `buffer-chars-modified-tick` has changed).

For normal parsing I **do** check `buffer-chars-modified-tick`, completion is a special case.

**Comment by dgutov** [comment]
> Yes, that's the reason I would like to avoid making unnecessary, slightly wrong and costly parsing requests.

Okay, then this approach should be fine.

> I'm checking the current completion context

Could you explain what that consists of? That's something I could use later on in a different project.

**Comment by Sarcasm** [comment]
> Okay, then this approach should be fine.

Okay good, I will see how it goes.

> > I'm checking the current completion context
> Could you explain what that consists of? That's something I could use later on in a different project.

In my case I judged the completion context to the location of first non-whitespace character before completion prefix (https://github.com/Sarcasm/irony-mode/blob/f9a9350dcbe95cb7ca0b7e4fa3f2f1716de7c617/irony-completion.el#L119-L124). And I update this "context" in a post-command hook and when a request is made.

Not sure if that is something you will have a use for in your other project. :)

**Comment by dgutov** [comment]
> the location of first non-whitespace character before completion prefix

Hmm, I thought the context would live more server-side, but this sounds okay, too. Purely relying on the position of that character means missing out on new code that may suddenly appear in this file after the current line, or in other file (after doing `git reset`, for instance). But if you invalidate it after each completion is finished, that should be fine.

Thanks, it's something to consider.
