### ISSUE TITLE
input blocked while pop up is active, setting company-require-match has no effect

### ISSUE THREAD

**Issue by QiangF** [company-mode/company-mode#306]
I tried to set company-require-match to nil, but still I can't type in a un-matched word.
Thank you for your help.

**Comment by dgutov** [comment]
Works for me.

More details needed, please follow this instruction (but substitute company for yasnippet): https://github.com/capitaomorte/yasnippet/#important-note-regarding-bug-reporting

**Comment by QiangF** [comment]
Thank you sir. It must be with my configration, I will post back if I found out the issue.
