### ISSUE TITLE
Results of grouped backends are re-sorted even if sorted is t

### ISSUE THREAD

**Issue by cpitclaudel** [company-mode/company-mode#307]
Hi,

When using grouped backends, it seems that results are sorted regardless of the `sorted` flag of each backend. Is that true? Or am I doing something wrong?

Thanks.

**Comment by dgutov** [comment]
Pretty much. A single backend can declare that its completions are already sorted. But when we're collecting completions from several, we need to impose at least `some` ordering on them.

How would we decide, in the general case, whether to mix and sort the resulting list?

**Comment by cpitclaudel** [comment]
I see, thanks!

I think not sorting could be a good option; then the results would be listed in the order of the backends that produced them. Or the user could supply a sort function perhaps?

**Comment by cpitclaudel** [comment]
Another way would be to document the function `company-multi-backend-adapter`, as it seems to fit the bill: is there anything wrong with the following approach?

```elisp
(defun company-multi (command &optional arg &rest more-args)
  (interactive (list 'interactive))
  (pcase command
    (`sorted     t)
    (`duplicates nil)
    (_           (apply #'company--multi-backend-adapter
                        '(company-a company-b company-c)
                        command arg more-args))))
```

**Comment by dgutov** [comment]
> Or the user could supply a sort function perhaps?

One way to do that is to use `company-transformers`. You can look at `company-sort-by-backend-importance` for inspiration.

> is there anything wrong with the following approach?

Looks right. I'll have to think about it.

**Comment by cpitclaudel** [comment]
Thanks!

For the record and for other people looking at this thread, I ended up making all backends non-synchronous, and making the function above itself asynchronous. I was having trouble with mixing asynchronous and non-asynchronous backends, and the order in which I listed the backends also created some glitches. 

I don't think these problems are worthy of a bug report; I think they were on my side (I couldn't come up with a minimal repro).

**Comment by dgutov** [comment]
@cpitclaudel They could still be bugs in Company or Emacs (http://debbugs.gnu.org/19860 is a problem in a related area).

I can't claim that mixing sync and async backends has been tested thoroughly, so if you could produce a problem example that I can follow, that would be most welcome.

**Comment by cpitclaudel** [comment]
Thanks! I'll try. I experimented with your suggestion of post-sorting too, and I think it's actually better than coming up with a custom backend. Thanks for the tip!

**Comment by cpitclaudel** [comment]
I think this issue can be closed. I moved to using your suggestion of sorting the results using `company-transformers`; since they are tagged with the backend they came from, it's easy to re-separate them, and to resort-them in their original order. Adding the option to do no sorting (and instead just list completions in the order of the backends) might be good, but `company-transformers` looks like a reliable workaround.

Regarding async problems: I haven't run into those after moving back to a grouped backend, thanks to the suggestion of using `company-transformers`.

**Comment by dgutov** [comment]
Okay then. Closing for now.

**Comment by vspinu** [comment]
#402 adds a :sorted keyword to the grouped back-end.
