### ISSUE TITLE
Company: Front-end company-pseudo-tooltip-unless-just-one-frontend error "Args out of range: 0, 22" on command post-command

### ISSUE THREAD

**Issue by csdrane** [company-mode/company-mode#308]
Steps to reproduce:

1) Create new foo.clj
2) Write stub function 

```
(defn foo
  [])
```

Now type docstring

```
(defn foo
  "Receive from Coordinator da" 
  [])
```

Company should go into infinite loop after hitting the 'a' in the docstring.

**Comment by csdrane** [comment]
It actually appears that regardless of context that "da" -- with quotes to signify a string -- throws company into a loop.

**Comment by dgutov** [comment]
What does `(company-capf 'candidates "da")` return?

**Comment by csdrane** [comment]
Returns nil

**Comment by dgutov** [comment]
Hmm. What's the value of `company-backends`, then?

**Comment by csdrane** [comment]
```
company-backends is a variable defined in `company.el'.
Its value is (company-bbdb company-nxml company-css company-eclim company-semantic company-clang company-xcode company-ropemacs company-cmake company-capf
              (company-dabbrev-code company-gtags company-etags company-keywords)
              company-oddmuse company-files company-dabbrev)
```

**Comment by dgutov** [comment]
Going back to the first expression, does it return nil when point is after `da`? In the same context that you see the error?

**Comment by csdrane** [comment]
I'm actually not able to reproduce the error anymore.

However, within a .CLJ, if I write `da` on an empty line and call `(company-capf 'candidates "da")`, the answer is still nil. This happens whether it's in quotes or not.

**Comment by dgutov** [comment]
This likely means that the error was dependent on the contents of your buffers. To be clear, you weren't using CIDER at the time?

I've pushed a new commit (https://github.com/company-mode/company-mode/commit/e6ea77958ac7050a9bbc43bff54a77365924ad24) adding the command `company-diag`. Next time you see this problem, please use it and post the contents of the diagnostic buffer here.

**Comment by csdrane** [comment]
CIDER was loaded, but I also experienced the problem when editing emacs lisp elsewhere.

**Comment by dgutov** [comment]
Ok, good. Then it's unlikely to be the cause.

**Comment by dgutov** [comment]
@csdrane Any news here?

**Comment by csdrane** [comment]
Haven't spent as much time in cider lately, but no updates!

**Comment by dgutov** [comment]
Let me know if it comes back.
