### ISSUE TITLE
Add 'ido-restrict-to-matches' (C-space) functionality?

### ISSUE THREAD

**Issue by luciferasm** [company-mode/company-mode#313]
When filtering in ido, you can hit C-space ('ido-restrict-to-matches) and do a new filtering from the resulting subset of the last filtering. It's an extremely fast way of finding a candidate that is either otherwise long to type, or if you just remember some keywords for the desired candidate but do not remember the order of those keywords. Does this exist in company mode? (or maybe some even more clever solution where a filtered subset can be flex-searched without requiring flex-support from the backends)

**Comment by dgutov** [comment]
`C-o`?

**Comment by luciferasm** [comment]
C-o as in `company-search-toggle-filtering`? That only seems to toggle filtering on and off. In what way does that command mimic `ido-restrict-to-matches`?

**Comment by dgutov** [comment]
> C-o as in company-search-toggle-filtering?

Yep. You're right, it's not the same.

**Comment by dgutov** [comment]
Our internal organization is bit a different from Ido, though. There, when you want to undo that action, you just abort and invoke the command again.

Maybe make the search logic more flexible? The part where we take the input and convert it into matches can be made configurable, and, for instance, space delimited words could be translated into a regexp where they can go in any order. Or use flex-matching, copying a bit of logic from `ido-set-matches-1`.

**Comment by luciferasm** [comment]
I think your first suggestion (i.e. space delimited words translated to a any-order regexp) is best. It's basically how `ido-restrict-to-mathces` work. The effectiveness of  `ido-restrict-to-mathces` is the ability to **see** the result of each filtering/narrowing **before** deciding what the next filtering/narrowing should be. E.g. "I have a slight memory that the candidate has a 'foo' in it, but don't remember anything else..." *(typing 'foo' which presents all candidates that contain 'foo')* "-Oh, now I see a lot of 'foo-blah-blah-bar' candidates. Because of that, I now remember that it also contained 'bar'" *(typing 'bar' which presents all candidates that contain 'foo' and 'bar')* and so on. `ido-restrict-to-mathces` interactively guides you and your memory towards the goal, by presenting the filter result at each stage. I guess your first suggestion would work exactly like this, i.e. each keystroke (including the space delimiter) would interactively update the list.

I'm not a big fan of flex-matching since I suspect it will produce more false positives. The ability to say that I'm searching for a string that contains "foo" and "bar" in any order should result in much less candidates than what a flex algorithm would find when giving "foobar". But maybe I'm wrong about this?

**Comment by dgutov** [comment]
> The ability to say that I'm searching for a string that contains "foo" and "bar" in any order should result in much less candidates than what a flex algorithm would find when giving "foobar".

I'd say these approaches are orthogonal. With the new feature, one should be able to write a searcher function that uses flex, as well as takes the space-delimited words and puts them in any order.

That would be the slowest approach, though, CPU-wise.

**Comment by luciferasm** [comment]
I've never found a clear definition of what flex/fuzzy matching actually is. Sometimes it means an inserted wildcard between each typed char, and sometimes it means clever analysis with point systems that try to compensate for misspellings etc. Either way, it just seems that it could potentially produce more false positives, but you obviously have much more experience of this than me.

When using company-mode, I'm always in two successive modes:
1) I try to nail the desired candidate down to be visible on the list, by typing substrings from memory (e.g. "it was something with foo and something with bar").
2) When spotting the correct candidate on the list, I want to select it with as few key strokes and effort as possible (i.e. try to avoid arrow keys and modifiers, and just continue the touch typing flow).

Even if flex/fuzzy might be better, I'd definitely be satisfied with a more simple `ido-restrict-to-matches`-approach (i.e. space delimited words translated to an any-order regexp) if it's easier to implement and a faster approach CPU-wise. It would definitely speed up my work flow. BTW, is company-mode to be officially included in Emacs 25?

**Comment by dgutov** [comment]
> I've never found a clear definition of what flex/fuzzy matching actually is.

"flex" is the term used by Ido. It means a wildcard before every character. "fuzzy" is an umbrella term meaning virtually non-prefix matching method.

> it just seems that it could potentially produce more false positives, but you obviously have much more experience of this than me.

flx as used by Ido works fine for me. But it's amortized by the fact that it's only used when there are no prefix matches for the given input.

> Even if flex/fuzzy might be better, I'd definitely be satisfied with a more simple ido-restrict-to-matches-approach

Yes, I also think it will be a good default.

> BTW, is company-mode to be officially included in Emacs 25?

Probably, but it's not there yet. If not in 25.1, then in some later version.

**Comment by luciferasm** [comment]
> Yes, I also think it will be a good default.

It also seems like some sort of convention. Helm uses space and Ido uses C-space for this functionality.

> Probably, but it's not there yet. If not in 25.1, then in some later version.

Great news! I knew I bet on the right horse - company is really great! Do you think it's worth to implement this, and if yes, do you even have the time to do it?

**Comment by dgutov** [comment]
> Helm uses space and Ido uses C-space for this functionality.

Also: `M-x apropos`.

> Do you think it's worth to implement this, and if yes, do you even have the time to do it?

I will, hopefully soon enough. But it's not particularly hard to do. If you have Emacs copyright papers signed, maybe give it a try yourself. So far, I'm meaning to introduce a `company-search-regexp-function` which would convert the input string into the desired regexp.

**Comment by dgutov** [comment]
Sorry for the delay, you can try it out now.
