### ISSUE TITLE
strange behavior of company ycmd

### ISSUE THREAD

**Issue by zhuzhongshu** [company-mode/company-mode#314]
I use company-ycmd as the backend of C and C++. While when I type character such as :: and -> ,the completion begins automatically but I can't input any character because it always reminder me of "Matching input is required".  So I have to call company-ycmd manually.

**Comment by dgutov** [comment]
Please don't open the same issue in multiple places at once.

**Comment by zhuzhongshu** [comment]
Sorry for this, but I am not sure where the problem is, company or company-ycmd. How can I inform both you and the author of company-ycmd about the problem?

**Comment by dgutov** [comment]
Option 1: You report it there, and then see if the backend's author believes the problem is here.

Option 2: Use [mentions](https://github.com/blog/821).
