### ISSUE TITLE
Grouped async backends don't play well together

### ISSUE THREAD

**Issue by cpitclaudel** [company-mode/company-mode#315]
Hi there,

I think I have a minimal repro for the bug I alluded to earlier.

```elisp
(package-initialize)
(company-mode 1)

(defun bck1 (command &optional arg &rest ignored)
  (interactive (list 'interactive))
  (pcase command
    (`interactive (company-begin-backend 'bck1))
    (`prefix "")
    (`candidates (cons :async (lambda (callback) (funcall callback '("11" "12")))))))

(defun bck2 (command &optional arg &rest ignored)
  (interactive (list 'interactive))
  (pcase command
    (`interactive (company-begin-backend 'bck2))
    (`prefix "")
    (`candidates (cons :async (lambda (callback) (funcall callback '("21" "22")))))))

(defun bck3 (command &optional arg &rest ignored)
  (interactive (list 'interactive))
  (pcase command
    (`interactive (company-begin-backend 'bck3))
    (`prefix "")
    (`candidates (cons :async (lambda (callback) (funcall callback '("31" "32")))))))

(setq merged '(bck1 bck2 bck3))

(setq company-backends (list merged))

;; Call company-manual-begin on an empty line after this point

```

When I eval this code, and then call company-manual-begin on an empty line, I get `'21' '22' '31' '32'` but not `'11'` nor `'12'`:

![missing completions](http://i.imgur.com/wQtgBKS.png)

I'm not familiar enough with the code base to provide a patch; sorry about that. Quick experimentation seems to suggest that there is a problem with how results are merged (the series of `funcall`s in `company--merge-async`).

Can you reproduce this?

**Comment by dgutov** [comment]
I see it. Thanks for the repro!

**Comment by dgutov** [comment]
Please let me know of any further problems in this area.

**Comment by cpitclaudel** [comment]
Thanks a lot for the quick fix! This seems to work very smoothly.
I'd be curious to know what the problem was. A bit of debugging seemed to indicate that the car of the completions list was being overwritten, but I'd be curious to understand the changes you made!

Thanks again for the quick update :)

**Comment by dgutov** [comment]
No problem!

Basically, under certain conditions, the `pending` list items were were being added too late, which caused `finisher` to pass on the results multiple times (as it happened, the later results could overwrite the first one).

Asynchronous functions that use the callback immediately (instead of waiting, say, for a response from an external process) are pretty rare, and that's what triggered the bug.

**Comment by cpitclaudel** [comment]
Ah, I see, that's interesting! Thanks.
