### ISSUE TITLE
Negative prefix argument should cycle company-complete-common-or-cycle backwards

### ISSUE THREAD

**Issue by asmeurer** [company-mode/company-mode#316]
See the discussion at https://github.com/company-mode/company-mode/issues/68#issuecomment-77602328.

**Comment by dgutov** [comment]
Doesn't make much sense to me: `C-u <tab>` takes one keypress more than `S-<tab>`.

**Comment by dgutov** [comment]
Same for `M-- <tab>`.

**Comment by asmeurer** [comment]
It's not about keypresses. Interactive functions should do the right thing with prefix arguments. If this were done this way, then configuring a shift tab to reverse would be as simple as `(define-key company-active-map (kbd "<backtab>") '(company-complete-common-or-cycle -1))`. Right now, I have to redefine the function, as described in the comment I linked to above.

**Comment by dgutov** [comment]
Do you have an example of a similar command in Emacs core that behaves like that?

**Comment by asmeurer** [comment]
Random example: `indent-ridigely` (`C-x TAB`). A positive prefix argument N indents the region N spaces, a negative prefix argument -N dedents the region N spaces. 

In general, any interactive command that can be reversed is going to allow negative prefix arguments.

**Comment by dgutov** [comment]
All right, that makes sense.
