### ISSUE TITLE
Concatenate (no sorting) in group backends?

### ISSUE THREAD

**Issue by vspinu** [company-mode/company-mode#317]
I have a grouped backend of [two backends](https://github.com/emacs-ess/ESS/blob/master/lisp/ess-r-completion.el#L347-L384), one for arguments of a function (valid only within a function call) and one for all other objects.  I want that argument completions be shown before all other objects. I also don't want the arguments to be sorted, as they must appear in the declared order. 

The only solution that I see right now is to manually merge the two backends into one.

Any ideas? Thanks.

[related: #307]

**Comment by dgutov** [comment]
I suppose we could add a new keyword, to put in the "grouped backends" list.

You current main option is to use `company-transformers`, like described in the other issue.

**Comment by vspinu** [comment]
> I suppose we could add a new keyword, to put in the "grouped backends" list.

That would be awesome.

**Comment by cpaulik** [comment]
:+1 I think this would be a cool feature since it would basically feel like one backend is handing over to the next.

**Comment by cpaulik** [comment]
If other people find this. The feature basically exists already by setting `company-transformers` to use `company-sort-by-backend-importance`

**Comment by vspinu** [comment]
> The feature basically exists already by setting company-transformers to use company-sort-by-backend-importance

@dgutov, this is not the recommended way to deal with it, or is it?

While it works, it's rather hacky. The backends list must be `((backend-A :with backend-B) ..)` and then the local  `company-transformers` should be set to `company-sort-by-backend-importance`. 

I guess `company-transformers` is intended to be set by end users, right?

**Comment by vspinu** [comment]
Ok. This is straightforward to fix on company side.  Proposing a PR.

**Comment by dgutov** [comment]
> I guess company-transformers is intended to be set by end users, right?

Indeed. And `company-sort-by-backend-importance` only help to keep completions from two groups from intermixing, not keep completions from each backend together if there are more than two.

**Comment by dgutov** [comment]
@vspinu Please take a look at #513. I'm strongly considering adding a new keyword and removing `:sorted`.
