### ISSUE TITLE
prefix `(cons prefix N)` not honored in grouped backends

### ISSUE THREAD

**Issue by vspinu** [company-mode/company-mode#319]
For grouped backends, if the returned prefix is of the form `(prefix . N)` where `N` is a number, the backends are not triggered. This seems to happen only for grouped backends. If I interactively trigger a specific backend, it works as expected.  Somewhat surprisingly `(prefix . t)` works for grouped backend.

**Comment by dgutov** [comment]
Do you have a self-contained example for me to try?

**Comment by vspinu** [comment]
Here it is:

```

(defun company-test1 (command &optional arg &rest ignored)
  (interactive (list 'interactive))
  (cl-case command
    (interactive (company-begin-backend 'company-test1))
    (prefix (cons (company-grab-symbol) 1))
    (candidates (all-completions arg '("aaaaaaa" "aaabbbb" "aaacccc")))))

(defun company-test2 (command &optional arg &rest ignored)
  (interactive (list 'interactive))
  (cl-case command
    (interactive (company-begin-backend 'company-test2))
    (prefix (company-grab-symbol))
    (candidates (all-completions arg '("aaaxxxxxx" "aaayyyy" "aaazzzzz")))))

(setq-local company-backends '((company-test1 company-test2)))
```

No completion is triggered on "aaa". When each of the above backends is called separately,  they work. If you change the prefix of the first backend to `(cons (company-grab-symbol) t)` the grouped backend starts working as expected.

**Comment by dgutov** [comment]
> When each of the above backends is called separately, they work.

I'm sure that only because you invoke them explicitly: likewise, with this configuration `M-x company-complete-common` will show you completions. You won't get them displayed automatically, but you won't get them with `(setq-local company-backends '(company-test1))` automatically either, because of the returned prefix value.

So, we use the first non-nil value returned by any backend, in `company-minimum-prefix-length`. How would you have this behavior changed? Use the largest `cdr` value among the returned ones? What if backends return different strings, too? Will we use the first string, or the string with the highest virtual length?

**Comment by dgutov** [comment]
Why does one of your backends even return a value below `company-minimum-prefix-length` in its `prefix` cons?

**Comment by vspinu** [comment]
> but you won't get them with (setq-local company-backends '(company-test1)) automatically either

Hm ... indeed. I have missed that.

> How would you have this behavior changed? Use the largest cdr value among the returned ones? What if backends return different strings, too? Will we use the first string, or the string with the highest virtual length?

I was expecting in that particular case only `test1` backend to get activated after  1 character and `test2` to get activated after `company-minimum-prefix-length`.  Now, I am not sure this is possible by company's design, as completions are not recomputed after the menu has been popped.

> Why does one of your backends even return a value below company-minimum-prefix-length in its prefix cons?

This has to do with the [argument completion](https://github.com/emacs-ess/ESS/blob/master/lisp/ess-r-completion.el#L368-L407) to a function. I want both, the argument list of the current function and all other objects to be completed simultaneously, but arguments to be popped up earlier, maybe even after 0 chars. This is a common user request and I have a separate `ess-company-arg-prefix-length` to configure that length.

**Comment by dgutov** [comment]
> I was expecting in that particular case only test1 backend to get activated after 1 character and test2 to get activated after company-minimum-prefix-length.

That assigns a different meaning to the second value in the cons than its intended usage. It does not override the value of `company-minimum-prefix-length`. It overrides the prefix length which is used in the comparison.

> Now, I am not sure this is possible by company's design, as completions are not recomputed after the menu has been popped.

They sure are recomputed. They just might hit the cache if the backend does not disable it.

> I want both, the argument list of the current function and all other objects to be completed simultaneously, but arguments to be popped up earlier, maybe even after 0 chars.

I don't know if `-minimum-prefix-length` is a good mechanism for that.

Would you expect completions of all kinda to be displayed anyway if the user invokes completion manually?

**Comment by vspinu** [comment]
> It does not override the value of company-minimum-prefix-length. 

Ups. That's what I understood from the docs "Instead of a string, the back-end may return a cons where car is the prefix and cdr is used in `company-minimum-prefix-length' ". It doesn't seem to explain what "test" means.

> It overrides the prefix length which is used in the comparison.

Sorry. I don't quite follow what this means. 

> Would you expect completions of all kinda to be displayed anyway if the user invokes completion manually?

Yes, irrespective of the prefix's length. That's how `company-compete` and `company-complete-common` work right now.

**Comment by dgutov** [comment]
> It doesn't seem to explain what "test" means.

Can you try to imagine how `company-minimum-prefix-length` is used? That is its test. Implemented in `company--good-prefix-p`.

I'm open to suggestions for better wording.

> Sorry. I don't quite follow what this means.

The test compares two values. The prefix cdr, when present, replaces one of them in the comparison.

> Yes, irrespective of the prefix's length.

Ehh, this is problematic. I really don't want to have to call `company-explicit-action-p` in `company--multi-backend-adapter-candidates`, and return different results depending on it. Aside from not being pretty, this will conflict with our caching logic.

The whole idea behind `company-minimum-prefix-length` was not to initiate completion automatically too soon, because it can be slow when the prefix is short, and the user might not want to see the completion popup all the time. But if we're displaying the popup already, why not show all valid completions?

You're saying it's a common request, but it's the first time I've encountered someone who would want to do that. What are "function arguments" in the current context? Why not just sort the completions, so that the less likely ones go later?

**Comment by vspinu** [comment]
> Can you try to imagine how company-minimum-prefix-length is used? That is its
> test. Implemented in company--good-prefix-p.

Yes. I imagined, and the only intuitive test I could think of is exactly
the opposite of what `company--good-prefix-p` does. That is,

    if cdr < company-minimum-prefix-length then trigger the completion

or, in other words overwrite the company-minimum-prefix-length.

> I'm open to suggestions for better wording.

Now that I understand what `company--good-prefix-p` does, here is my
version of the doc:

  Instead of a string, the back-end may return a cons where car is the
  prefix and cdr is either t or a number to be compared against
  `company-minimum-prefix-length'.  If cdr is t the completion is
  started irrespective of the prefix length and the value of
  `company-minimum-prefix-length'. If cdr is a number greater or equal
  to `company-minimum-prefix-length' then the completion is allowed to
  start, otherwise not.

Here is the much simpler alternative if you would agree to revert the
meaning of cdr:

    Instead of a string, the back-end may return a cons where car is the
  prefix and cdr overwrites `company-minimum-prefix-length'.

 > But if we're displaying the popup already, why not show all valid
 > completions?

This could be, but it might be slow.  Functions have very few arguments
and just like eldoc, users want it faster than other completion. See the
screenshot at http://www.emacswiki.org/emacs/ess-ac1

Essentially, the problem is to have `company-minimum-prefix-length'
contextual. Inside of the function call, "cat(|)" in the screenshot, I
want to popup completions faster, even immediately after the opening
parenthesis. Outside of the function call, the completion should popup
later.

In any case, if this pattern is too much of a hustle, don't bother about
it. I will simply implement a joint backend and forgo grouped backends
altogether.

 > Why not just sort the completions, so that the less likely ones go
 > later?

Sure (that's the problem in #317). But this doesn't address the
contextual prefix length.

**Comment by dgutov** [comment]
> if cdr < company-minimum-prefix-length then trigger the completion

Whyyy?

If the variable defines the minimum length, then something should exceed its value for good stuff to happen. Not be below it.

**Comment by vspinu** [comment]
My mail was garbled by github formatting. Sorry.

>> if cdr < company-minimum-prefix-length then trigger the completion

> Whyyy?

You seem to be focusing on the general meaning of `company-minimum-prefix-length`. I am talking about the strict meaning of cdr in `(prefix . cdr)`.

I think it should be very clear what I meant from the two alternative definitions of `cdr` what I provided.

**Comment by vspinu** [comment]
BTW, in simple terms the current meaning of `cdr` is to "overwrite length of the prefix" which is rather strange construct IMO. But could be if it's properly documented. You probably had good reasons to implement it that way.

**Comment by dgutov** [comment]
> My mail was garbled by github formatting. Sorry.

Thanks. I've noticed the edit later.

> I think it should be very clear what I meant from the two alternative definitions of cdr what I provided.

I only see one. And "overwrite company-minimum-prefix-length" wouldn't look like

```
if cdr < company-minimum-prefix-length then trigger the completion
```

rather, it would be like:

```
if (length prefix) >= cdr then trigger the completion
```

Again, "something" should be equal to or exceed the "minimum".

> in simple terms the current meaning of cdr is to "overwrite length of the prefix" which is rather strange construct IMO

The original idea was if point is after something like `->foo`, then the value of prefix is `foo`, but we should use `->` in the prefix length comparison. Then, cdr would be 5.

Personally, I think it just over-complicates things. After `->` we usually either want to complete right away or not. So I've been considering to ignore the numeric value of the cdr, and automatically succeed the test if the prefix is a cons. IOW, only effectively support the value `t`.

> But could be if it's properly documented.

Hence my effort to make you understand its meaning. Why don't you suggest a better wording? How about "cdr is used instead of the prefix length in `company-minimum-prefix-length' test"?

> Sure (that's the problem in #317).

It will be resolved sooner or later. At least it's pretty clear what to do there.

**Comment by dgutov** [comment]
> Functions have very few arguments and just like eldoc, users want it faster than other completion.

I see. Looking at http://blog.moertel.com/posts/2006-01-20-wondrous-oddities-rs-function-call-semantics.html, R's calling convention is indeed too flexible to do any better static analysis.

Do you know how completion behaves in e.g. R Studio, in this situation?

>  I ant to popup completions faster, even immediately after the opening parenthesis. Outside of the function call, the completion should popup later.

Please clarify: do you want to pop up only named arguments quickly (and the values later), or in general quickly display completions when inside function call parens? The latter should be easy to implement.

> In any case, if this pattern is too much of a hustle, don't bother about it. I will simply implement a joint backend and forgo grouped backends altogether.

I don't know if you want to do that. Going this way, the joined backend would have to deal with the two caveats I mentioned: disable built-in company-mode cache, and behave differently depending on what `company-explicit-action-p` returns.

**Comment by vspinu** [comment]
> How about "cdr is used instead of the prefix length in `company-minimum-prefix-length' test"?

Yes. This is good. I would even make it more explicit "cdr is used in the comparison against  `company-minimum-prefix-length' instead of the actual prefix length". 

> Do you know how completion behaves in e.g. R Studio, in this situation?

In R studio, you have to hit tab each time you want a completion, and they show all completions at once. 

> Please clarify: do you want to pop up only named arguments quickly (and the values later), or in general quickly display completions when inside function call parens? The latter should be easy to implement.

Original idea was to go with the first scenario (only named arguments quickly) but as I have already said, it's not a big deal at all. So I would be completely happy with the scenario when all completions are popped together but have separate  prefix thresholds depending on the context.  One threshold for function call context and the other for everything else. 

I can implement this myself right now as simple as 

```
(if ess-company-arg-prefix-length
    (cons prefix (>= (length prefix)
                     ess-company-arg-prefix-length))
  prefix)
```

So I guess this issue is exhausted. Thanks.

**Comment by dgutov** [comment]
> This is good. I would even make it more explicit

Applied, thanks.

> I can implement this myself right now as simple as 

Right, that should work well for `company-R-args` when it's the current backend.

I think the problem remains when grouping is used. Either `company-R-objects` has to return nil when inside function call args, or `company-R-args` must come first. If `company-R-objects` comes first and returns a string, that value will be used.

If that's a problem, we can continue the discussion.
