### ISSUE TITLE
Can't chain completion using post-completion?

### ISSUE THREAD

**Issue by tsukimizake** [company-mode/company-mode#320]
Hello.

I'm trying to develop company-mode backend for [DCD](https://github.com/Hackerpilot/DCD).
As you can see in its [readme](https://github.com/Hackerpilot/DCD#note), DCD's function argument completion is a bit odd. It requires another completion request after symbol name completion.
To get along with this interface, I tried to call argument completion from normal completion's post-completion. Though it doesn't work.

```
(defun normal-completion (command &optional arg &rest ignored)
  (interactive (list 'interactive))
  (case command
    (interactive (company-begin-backend 'normal-completion))
    (prefix  "")
    (candidates
     '("foo"))
    (post-completion (company-begin-backend 'chained-completion))))

(defun chained-completion (command &optional arg &rest ignored)
  (interactive (list 'interactive))
  (case command
    (interactive (company-begin-backend 'chained-completion))
    (prefix (company-grab-symbol))
    (candidates
     '("foobar" "foobaz"))
    ))

```

Then, I tried this code snippet. I expected chained-completion executed automatically after normal-completion, but doesn't work like that.
This kind of chain is not supported?

**Comment by dgutov** [comment]
Indeed, it's not supported. And in the future, I can imagine supporting this feature in a different way, but probably not in `post-completion`. We'll see.

You can try to:

* Modify the `prefix` implementation to return `(prefix . t)` at least in the contexts when the user would expect the completion popup to be displayed immediately (they'll still have to wait `company-idle-delay`, or invoke `company-complete` manually).

* Wrap the `company-begin-backend` call in `(run-with-timer 0 nil (lambda () ...))`. This should work reasonable well, but I don't know how reliable that will be.

**Comment by tsukimizake** [comment]
Hmm.Thanks. I'll try your workarounds.

**Comment by tsukimizake** [comment]
Hmm.Thanks. I'll try your workarounds.
