### ISSUE TITLE
Add option to remove popup from company-quickhelp

### ISSUE THREAD

**Issue by rpglover64** [company-mode/company-mode#321]
Surprisingly, I found the quickhelp popup to be annoying, especially when it covers up most of the screen; I'm playing with decreasing the maximum line number. I noticed something interesting, though:

when it pops up, it also changes the *Help* buffer to the contents of the popup. I noticed that I like this behavior, since I can control the help buffer more directly, and I think it would be useful even if there was no popup. Unfortunately, turning off quickhelp prevents this from happening.

**Comment by dgutov** [comment]
> when it pops up, it also changes the Help buffer to the contents of the popup

That is, some could say, an unfortunate side-effect of `doc-buffer` implementation in `emacs-lisp-mode` only.

If you just want to reproduce this effect, you can create a new frontend (see `company-frontends`) that wouldn't do much other than call `(company-call-backend 'doc-buffer (nth company-selection company-candidates))` in its `post-command` handler.
