### ISSUE TITLE
Functionpointer-template inserts (*)

### ISSUE THREAD

**Issue by Dickby** [company-mode/company-mode#322]
I use ycmd with company-ycmd so I'm not shure if this is the right place to ask this question, just close this issue if not.
I use the company template system for C funcitons.
If I complete the name of a function-pointer the template inserts "(*)" in front of the args-template.
is there any way to avoid this?
Thanks

**Comment by dgutov** [comment]
Please post the output of `M-x company-diag` when called at that position. Maybe not the full output, but include the entry for the said function-pointer.

**Comment by Dickby** [comment]
Used backend: company-ycmd
Prefix: #("test" 0 1
  (fontified t face font-lock-type-face)
  1 2
  (fontified t face font-lock-type-face)
  2 3
  (fontified t face font-lock-type-face)
  3 4
  (fontified t c-type c-decl-id-start face font-lock-type-face))

Completions:
  #("test" 0 1 (meta "int test" return_type "int" kind "VARIABLE" extra_menu_info "int" detailed_info "int test
" menu_text "test" extra_data nil)) " -> int [var]"
  #("testPointer" 0 1 (meta "void (*)() testPointer" return_type "void (*)()" kind "VARIABLE" extra_menu_info "void (*)()" detailed_info "void (*)() testPointer
" menu_text "testPointer" extra_data nil)) "(*)() testPointer -> void (*)() [var]"

**Comment by dgutov** [comment]
Please use a Markdown code block, so that the asterisks are not interpreted as markup.

**Comment by dgutov** [comment]
Never mind.

**Comment by dgutov** [comment]
Hopefully, this will work now.
