### ISSUE TITLE
How to show the definition of function in minor buffer?

### ISSUE THREAD

**Issue by fenxian** [company-mode/company-mode#323]
I have a requirement which is to have a tip in minor buffer when I insert a function which may be have much parameters. This tip can give me function declaration include type and sort of parameters. I think those information can be showed in minor buffer just as locating at a function in popup window.

In current version, the required information can be showed in minor buffer before I typing or determing candidate. However, it will automatically dismiss when i determine it. You know, i will input parameters at this time. .. . but. .

I have tried many short keys and commands in company-mode. All are failed. 

![1](https://cloud.githubusercontent.com/assets/5669903/6635037/09e8aa1c-c99c-11e4-93b4-0d5f90ddb30a.gif)

**Comment by dgutov** [comment]
Normally, displaying function signatures in the echo area is the job of ElDoc. You should try a package that integrates with it, such as [c-eldoc](https://github.com/mooz/c-eldoc).

That would mean configuring the compilation flags in yet another place, unfortunately. But you can try [irony-mode](https://github.com/Sarcasm/irony-mode) with [irony-eldoc](https://github.com/ikirill/irony-eldoc) instead.
