### ISSUE TITLE
Error during redisplay

### ISSUE THREAD

**Issue by vspinu** [company-mode/company-mode#324]
I keep seeing this error somewhat stochasticaly:

```
Error during redisplay: (eval (if (consp company-backend) (company--group-lighter (nth company-selection company-candidates) company-lighter-base) (symbol-name company-backend))) signaled (args-out-of-range 0 0)
```
I cannot reproduce it by calling backends interactively, only in real usage in a grouped backend. It seems to always appear when I press `C-g` in the completion menu. Any ideas of what might going wrong or how to debug this? Thanks.

**Comment by dgutov** [comment]
Have you tried evaling the above expression?

At a guess, this might be related to the names of the backends of the group. Or if this mode-line spec gets evaluated in some conditions that never happen on my machine, because something calls `force-mode-line-update` at yours.

**Comment by dgutov** [comment]
Oh. It seems like `(nth company-selection company-candidates)` is nil when it's updated, but `company-backend` has some non-nil value. That shouldn't happen.

**Comment by vspinu** [comment]
This is what I get in `company lighter`:

```
company-backend:(company-R-args company-R-objects)
company-selection:0
company-candidates:nil
```
This seems to happen before `candidates` predicate is passed to the backends, only `prefix` then `ignore-case` then nothing. 

While I am edebugging the error is triggered every time the redisplay is called. So I guess you have to check for `company-candidates` to be non-nil, not just `company-backend`.

**Comment by dgutov** [comment]
Ok, thanks. Let's try it this way.

Let me know if it's not sufficient.

**Comment by vspinu** [comment]
> Let me know if it's not sufficient.

Yes. It seems to fix the issue. Thanks.
