### ISSUE TITLE
Why does asynchronous mode not work for company-ycmd

### ISSUE THREAD

**Issue by r4nt** [company-mode/company-mode#325]
Hi,

if I take a look at emacs-ycmd's company mode integration, it looks like it's already providing the completions asynchronously (via (cons :async (lambda (cb) (company-ycmd--get-candidates cb prefix)))))
https://github.com/abingham/emacs-ycmd/blob/master/company-ycmd.el

When I have a file where completions take a while to get (0.5 seconds or so) and there are lots of completions, company still completely hangs for me when I trigger it automatically on key-press.

Any help to debug this / speed it up would be greatly appreciated.

**Comment by dgutov** [comment]
You could start with posting an example I could reproduce. It shouldn't be too hard (I think) to create a basic project with ones file that include too many libraries, preferably ones available by default.

But the problem could as well be unsolvable on this end: even if completions are triggered asynchonously, this only saves Emacs from having to freeze while waiting for each response.

If each completion takes a long time, that means heavy load on the system (right?), so it shouldn't be too surprising to see the server to stop responding altogether after a while.

> I trigger it automatically on key-press

What does that mean?

**Comment by r4nt** [comment]
$ for i in $(seq 20000) ; do echo "int f$i() {}"; done > t.cc
$ emacs -nw t.cc

Go into any line and start typing. Emacs will hang for a while, after which suddenly all characters will appear.

I have:
(setq company-idle-delay 0)

**Comment by r4nt** [comment]
A pointer with ideas how to inject some debug traces to track down what the underlying problem is would already help me - note that I'm new to emacs / elisp; I played around a bit inserting "message" commands, but that didn't reveal too much.

**Comment by dgutov** [comment]
Thanks. I'll try the example.

> (setq company-idle-delay 0)

Augh. Whether there's a problem in company-mode is a question, but an obvious way to improve the sutuation is to increase the delay. With 0, you're bombarding the server with completion requests after every keypress. What happens to a website under heavy load when angry users keep mashing "reload"?

> ideas how to inject some debug traces to track down what the underlying problem

You can add some `message` calls to `company-ycmd--get-candidates`, for instance. `trace-function` would be a more advanced option.

**Comment by r4nt** [comment]
> (setq company-idle-delay 0)
> Augh. Whether there's a problem in company-mode is a question, but an obvious way to improve the sutuation is to increase the delay. With 0, you're bombarding the server with completion requests after every keypress. What happens to a website under heavy load when angry users keep mashing "reload"?

Given that the majority of the projects I work in have C++ code completion that is fast enough that this works really well, I think it'd make sense to put in some rate restriction so this doesn't completely kill the editing experience. YCM on vim definitely handles this well (@Valloric might have comments how he handles it)

> You can add some message calls to company-ycmd--get-candidates, for instance.

I did that, but it didn't show me anything that I could make sense of. I especially don't understand why emacs hangs (ctrl-g doesn't work) when I do that.

> trace-function would be a more advanced option.

Thanks, I'll look into that.

**Comment by dgutov** [comment]
> I think it'd make sense to put in some rate restriction so this doesn't completely kill the editing experience

The aforementioned variable is the "rate restriction". Anything else you're welcome to bring up at `emacs-ycmd` issue tracker.

**Comment by dgutov** [comment]
> I especially don't understand why emacs hangs (ctrl-g doesn't work) when I do that.

That sounds like a bug in company-mode, too.

**Comment by r4nt** [comment]
> The aforementioned variable is the "rate restriction". Anything else you're welcome to bring up at emacs-ycmd issue tracker.

Sure. My main question was whether there are some ideas / idioms on how emacs-ycmd might be providing its company-mode integration incorrectly...

**Comment by r4nt** [comment]
For what it's worth, I don't think rate-limiting will help - this already happens when I type a single character:
1. type: ab
2. wait until everything finished
3. type: c
The "c" shows up after a delay of ~2 seconds for me.

**Comment by dgutov** [comment]
So, is it the same if you increase the idle delay a bit?

**Comment by r4nt** [comment]
> So, is it the same if you increase the idle delay a bit?

Yep, but it requires to increase it quite a lot:
- at 0.1 it gets slightly better, leading to shorter hangs, but they're still noticable
- at 0.4-0.5 it gets bearable, but then the delay for the completion gets annoying

**Comment by dgutov** [comment]
When it freezes, which process hogs the most CPU?

**Comment by r4nt** [comment]
emacs --daemon hogs one core for 100%

**Comment by dgutov** [comment]
Well, at least for this example I get this ELP output:

```
json-encode                                       49          40.373922852  0.8239576092
json-encode-list                                  12          30.454752527  2.5378960439
json-encode-alist                                 9           30.45463016   3.3838477955
ycmd-get-completions                              3           10.515761361  3.5052537869
ycmd--request                                     5           10.504717434  2.1009434868
json-encode-string                                30          9.9188939140  0.3306297971
json-encode-char                                  927259      6.9621825919  7.508...e-06
json-encode-char0                                 927259      1.1932534209  1.286...e-06
ycmd-request-deferred                             5           0.263508196   0.0527016392
ycmd-request                                      5           0.263467947   0.0526935894
ycmd-request--curl                                5           0.263334671   0.0526669342
json-join                                         9           0.1421685389  0.0157965043
ycmd--standard-content-with-extras                3           0.0126280259  0.004209342
ycmd--standard-content                            3           0.0126114730  0.0042038243
json-read                                         90          0.0070623759  7.847...e-05
...
```

That's 0.8sec, on average, spent in `json-encode`. Try evaluating `(length (json-encode (ycmd--standard-content)))` in this buffer and see how long it takes (~3 second for me). This is the data that has to be generated before making the request.

So, the big file size is definitely a factor here. Do you have an example where the current file isn't huge? I guess it's allowed to include a huge header, but then ycmd needs some file with project options I'm not familiar with.

**Comment by Valloric** [comment]
> With 0, you're bombarding the server with completion requests after every keypress. 

Yes, please continue doing this. ycmd is designed to handle this just fine and this is how YCM (the Vim client to ycmd) does it. Works great.

If ycmd can't handle the load you're giving it, then that's a ycmd perf bug! In practice, this hasn't been much of an issue.

**Comment by dgutov** [comment]
> Yes, please continue doing this. ycmd is designed to handle this just fine

All right then. :)

It would be a laugh if this performance problem comes down entirely to slow built-in JSON serializer.

**Comment by Valloric** [comment]
> It would be a laugh if this performance problem comes down entirely to slow built-in JSON serializer.

I don't have data for elisp, but I do have data for Python (which is what YCM and ycmd are written in). [See my post here for details](https://plus.sandbox.google.com/+StrahinjaMarkovi%C4%87/posts/Zmr5uf2jCHm).

**Comment by r4nt** [comment]
@dgutov - the data is awesome - thanks so much for putting it together!

**Comment by dgutov** [comment]
@r4nt Hey, are you sure it's at all useful? Like I said, this example's problem is the huge current buffer. In all likelihood, @abingham can't do anything about that right away (short of working on optimizing Emacs's JSON package).

Is that the problem you have with the real project, very big individual files?

**Comment by r4nt** [comment]
@dgutov - well, optimizing the json package or just hand-crafting the json (it might be faster to just dump through an external json-encoder written in C) seems all plausible.

Yep, this happens when working on Clang/LLVM, which admittedly have some of the largest files I've ever worked in.

**Comment by dgutov** [comment]
@Valloric Thank you. The difference with Python is pretty staggering here: it can serialize a 300 kb string in about 2 ms, whereas the Emacs JSON implementation takes 400 ms.

I'm not sure Python's `json` lib is pure, though. Its `__init__.py` mentions "optional C
extension for speedups", and `encoder.py` includes lines such as `from _json import make_encoder as c_make_encoder`, which does not raise `ImportError` on my installation.

**Comment by abingham** [comment]
Python's "_json" is a compiled module on my system (OS X), so I assume it's that way everywhere. I'm open to trying any options to speed up json encoding, though I don't have time to do much personally right now.

**Comment by r4nt** [comment]
@abingham - if you have suggestions what we should try first, I might spend a couple of cycles on it...

**Comment by abingham** [comment]
@r4nt - I guess I would start by seeing if anyone else has faced/tackled this problem in emacs. Maybe there's some package that smooths over the whole problem of using an external program for JSON encoding when possible.

If nothing exists, then I'd do as you suggest and see about using some faster, external encoder. We could just provide a variable like `ycmd-external-json-encoder` which, if configured, should point to the program to use. 

We need to be careful, of course, to encode the buffer contents, not just the contents of the file on disk. So we might need to write out a temp file with the buffer contents to feed it into the encoder.

**Comment by r4nt** [comment]
@abingham - seems like looping through stdin/stdout of an external encoder should be straight-forward, no temp files needed? Are there platforms where this wouldn't work?

**Comment by dgutov** [comment]
I suspect that even the Emacs built-in encoder has some room for optimization. As evidence, here's a year-old post from some guy claiming to have improved the speed by the factor of 3 (with code): http://notmuchmail.org/pipermail/notmuch/2011/005328.html

I don't know why he hadn't submitted a patch to Emacs, though.

**Comment by dgutov** [comment]
> seems like looping through stdin/stdout of an external encoder should be straight-forward

It's not immediately obvious to me how to pipe an alist through an external process. Some intermediate encoding would be required.

**Comment by abingham** [comment]
@r4nt - There might be something simpler than temp files...I'm talking a bit off-the-cuff here. But as @dgutov points out, we have to consider not just the buffer contents but the other data as well. Maybe in the end fixing the elisp json code is simpler.

**Comment by dgutov** [comment]
Someone could also try https://github.com/skeeto/elisp-ffi, or just wait for the real FFI, which we'll have any year now.

**Comment by r4nt** [comment]
@dgutov - that, or we just do the encoding of the buffer, which is probably the only thing that matters in practice, and is basically glorified string escaping. 

$ time python -c 'import sys
import json
json.dump(sys.stdin.read(), sys.stdout)' < ~/src/llvm/tools/clang/lib/Driver/Tools.cpp > /dev/null

real    0m0.026s
user    0m0.015s
sys     0m0.009s

... outputs exactly what we need.

**Comment by dgutov** [comment]
@r4nt Okay, and how will you create the JSON structure needed for the request? With `replace-regexp-in-string`?

**Comment by r4nt** [comment]
@dgutov - just concatenate strings, escaping only the user-provided input via a call to this process instead of using json-encode?

**Comment by dgutov** [comment]
@r4nt You'd have to rewrite a bunch of functions in `emacs-ycmd`, but that seems a thing to try.

I wish someone tried to improve `json-encode-string`, though. Looking at the implementation (encode every char, then concatenate), it's hilariously ineffective.

**Comment by r4nt** [comment]
Yea, I'd like to try, but trying to write efficient code while learning a new language is usually bound to fail :)

**Comment by dgutov** [comment]
Gave it a quick try:

```el
(defun json-encode-big-string (str)
  (with-temp-buffer
    (insert str)
    (goto-char (point-min))
    (while (re-search-forward "[\"\\/\b\f\b\r\t]\\|[^ -~]" nil t)
      (replace-match (json-encode-char (char-after (match-beginning 0)))
                     t t))
    (format "\"%s\"" (buffer-string))))
```

Unfortunately, the speedup is not as big as I'd hoped (0.3s vs 0.5s). Binding `gc-cons-threshold` to a big value brings it down a bit more (0.25s), but that's still far from acceptable.

**Comment by dgutov** [comment]
http://debbugs.gnu.org/20154

**Comment by tuhdo** [comment]
@r4nt  I'm curious, but did you consider the alternative in Emacs rather than ycmd? i.e. `irony` (super easy to install) and `rtags`.

**Comment by r4nt** [comment]
@tuhdo - yes, but I don't think it makes much sense to support multiple backends that all serve the same purpose. At some point, one has to make a decision, and then go with the one that one deems has the highest chances of working cross-editor.
YCM supports vim and emacs, there's early work on sublime, and it supports Python, Go, Java and C++. I care about all those languages and all editors.

**Comment by ptrv** [comment]
@tuhdo I tried `irony` and `rtags` but they are much slower than `ycmd` on large projects. At work I am working on a large C++ project and both `irony` and `rtags` couldn't really handle the size of the project. Completion was really slow.

**Comment by dgutov** [comment]
@r4nt I've [pushed a patch](http://git.savannah.gnu.org/gitweb/?p=emacs.git;a=blobdiff;f=lisp/json.el;h=fb0f62c877794747d158bf378f7af3fabe87e9c2;hp=98974e67b7e304088c4baf21804b1df8b73bbd21;hb=a3b6c249e9757761404c1f7a57de4217dcc2e583;hpb=2a954e8aa6917572cbf9431f7b1a9ae19be18d7c) which improves JSON encoding performance by 7x or so. Please try building Emacs from master, or apply it to your local installation, and see if the performance is bearable now.

**Comment by dgutov** [comment]
The given example works reasonably quickly for me now, using the latest Emacs 25 build.

Not 100% smooth, but it should be much harder to make it hang.
