### ISSUE TITLE
Is there a front-end that can behave like auto-complete-mode?

### ISSUE THREAD

**Issue by jwiegley** [company-mode/company-mode#327]
My favorite feature of auto-complete is that it doesn't show me a list of candidates until I ask for one; rather, it shows what the expansion would look like using a subtle grey text to spell out the completed word within the buffer.  This way I see what I'll get by hitting TAB without seeing what the other possible completions are until I ask.

Is there any way to get this same functionality from a company-mode front-end?

**Comment by dgutov** [comment]
https://github.com/company-mode/company-mode/issues/87?

**Comment by jwiegley** [comment]
I think #123 addresses this.

**Comment by dgutov** [comment]
Cool.
