### ISSUE TITLE
*TAGS Overkill Completion

### ISSUE THREAD

**Issue by 3246251196** [company-mode/company-mode#329]
After trying CEDET/Semantic for over half a year I have finally decided that it is both too slow and inefficient. I am now trying Company Mode and really like what I see here.

I tried ETAGS. Now, when I have some parameter to a function that is a reference to a class eg:

void someFunction( someExternalClass& sec )
{
  sec.//things
}

I get a frontend view of all possible //things. The only issue is that it displays ALL the possible things. Well, I really just want a restrictive list of things that beling to someExternalClass.

I am guessing that *TAGS does not understand inheritance, so if someExternalClass is a derived class of someBaseExternalClass I could not get a listing from someBaseExternalClass public/protected methods?

It is such a shame that the TAGS method shows everything, if it would just show what I needed it would be great.

I tried CLANG and it worked perfectly for a small project, but causes issues when building for large projects.

**Comment by dgutov** [comment]
> I am guessing that *TAGS does not understand inheritance, so if someExternalClass is a derived class of someBaseExternalClass I could not get a listing from someBaseExternalClass public/protected methods?

That is correct. In short, a tags file is a simple dictionary of symbols.

> I tried CLANG and it worked perfectly for a small project, but causes issues when building for large projects.

You should try one of the third-party packages that provide more advanced integration with Clang (and retain information in memory between completions).

https://github.com/Sarcasm/irony-mode
https://github.com/AndersBakken/rtags
https://github.com/abingham/emacs-ycmd

All three have company-mode backends.

**Comment by 3246251196** [comment]
Thank you for your reply,

in the mean time - if anyone is interested in my failed attempt:

(This is the source code for Synergy - the application that allows mouse/keyboard use on other networked computers)

1. Download and unzip https://github.com/synergy/synergy/archive/master.zip
2. cd synergy-master/src
3. find . -name "*.h" -printf "%h\n" | uniq > .dir-locals.el
4. Massage the data so that I get a .dir-locals.el that looks like:
((nil . ((company-clang-arguments . (
                                     "-I/home/dir/to/synergy-master/src/cmd/synergys"
                                     "-I/home/dir/to/synergy-master/src/cmd/synergyp"
                                     ...)))))
5. emacs gui/src/main.cpp
6. M-g g 59
7. Type: app.commitData
8. Notice the clang error (at least, I get one)

This is using company-mode: elpa company-0.8.12
and Clang: Ubuntu clang version 3.0-6ubuntu3 (tags/RELEASE_30/final) (based on LLVM 3.0)
Target: x86_64-pc-linux-gnu
Thread model: posix

Xubuntu 12.04.5

As I say, time-being, I will test out those suggestions. Cheers.

**Comment by dgutov** [comment]
> Notice the clang error (at least, I get one)

I thought by "causes issues when building for large projects" you meant it's too slow. Please be more clear the next time.

> (require 'cc-mode)

You shouldn't ever need that.

> "-I/home/dir/to/synergy-master/src/cmd/synergys"

And here's your problem, I believe. Have you looked at how the compiler program actually gets called during the build process? I'm pretty sure "synergys" won't be in there.

Look at https://github.com/synergy/synergy/blob/master/src/cmd/synergys/XWindowsServerTaskBarReceiver.cpp. The `#include` statement uses a relative path starting with `synergys`. That means the headers search path must include its parent directory instead, which is `/home/dir/to/synergy-master/src/cmd/`.
