### ISSUE TITLE
Strange interactions with smartparens

### ISSUE THREAD

**Issue by cichli** [company-mode/company-mode#330]
I've found a couple of weird edge cases here and am having trouble tracking down the exact cause/which package is at fault.

If point is between two parentheses like this:
![screenshot 2015-03-21 11 25 29](https://cloud.githubusercontent.com/assets/1759291/6764853/66863c72-cfbd-11e4-9089-1d0f3330bb97.png)
then any invocation of `company-complete-common` will insert a new closing parenthesis:
![screenshot 2015-03-21 11 29 30](https://cloud.githubusercontent.com/assets/1759291/6764860/95dcccb6-cfbd-11e4-806c-7497c720d567.png)

Even more odd, starting with something like this:
![screenshot 2015-03-21 11 30 24](https://cloud.githubusercontent.com/assets/1759291/6764862/b1b47628-cfbd-11e4-891f-7c7dab7c762f.png)
then initiating completion with `company-complete` inserts a closing parenthesis:
![screenshot 2015-03-21 11 31 00](https://cloud.githubusercontent.com/assets/1759291/6764866/d1450994-cfbd-11e4-9476-148873315db8.png)
and then pressing `C-e` deletes the whole line after the point:
![screenshot 2015-03-21 11 34 57](https://cloud.githubusercontent.com/assets/1759291/6764878/54880e3c-cfbe-11e4-9dfe-0e75fabd351e.png)

Updating `company-complete-common` to the below fixes the problem, but is probably not the best solution (I guess the empty string check should perhaps go in `company--insert-candidate`, or the problem should be fixed in smartparens).

```emacs-lisp
(defun company-complete-common ()
  "Insert the common part of all candidates."
  (interactive)
  (when (company-manual-begin)
    (if (and (not (cdr company-candidates))
             (equal company-common (car company-candidates)))
        (company-complete-selection)
      (when (and company-common
                 (not (string= company-common "")))
        (company--insert-candidate company-common)))))
```

What do you think?

**Comment by cichli** [comment]
Oh, I should add, this is using `smartparens-strict-mode`.

**Comment by dgutov** [comment]
I'd say it's a smartparens problem, but inserting an empty string isn't a very useful thing to do anyway, so we might as well make the change here.

**Comment by cichli** [comment]
Thanks!
