### ISSUE TITLE
Where does a vanilla company-mode install get fundamental/text-mode completions from?

### ISSUE THREAD

**Issue by talexand** [company-mode/company-mode#331]
I took a look at the `customize-group` options for each of the available backends, but didn't see anything that might tell me. I have `ispell` installed (with default settings/offline dict), which I know `org-mode` falls back on for completion-at-point, but I'm surprised at how good/humorous the completion suggestions can be sometimes.

Just want to make sure nothing is going out to Google or somebody else for these results :)

**Comment by dgutov** [comment]
Have you looked at `company-dabbrev`? Where, by your conclusion, does it get the completions from? :)

**Comment by talexand** [comment]
It looks to me like it just searches other open buffers, which means that it's only echoing my own silly typing.

**Comment by dgutov** [comment]
Yep.

Well, I'm sure not everything the open buffers contain you've typed yourself. And many packages like to open and read files in background. When the buffer names don't follow the convention for "invisible buffers" (basically, the name starts with a space or an asterisk), `company-dabbrev` will search them too.

**Comment by talexand** [comment]
Thanks!
