### ISSUE TITLE
somthing wrong with 'company-clang--annotation'

### ISSUE THREAD

**Issue by zbelial** [company-mode/company-mode#332]
When completing with company-clang, an error message was reported, which looks like as following:

Company: An error occurred in post-command
Company: Front-end company-pseudo-tooltip-unless-just-one-frontend error "Company: Back-end company-clang error "Wrong type argument: stringp, nil" with args (annotation m_pSrcFileQueue)" on command post-command

After some exploration, I found the problem is in function company-clang--annotation, which invokes company-clang--annotation-1. But company-clang--annotation-1 may return nil, so (string-prefix-p "(*)" ann) will complain and then emit error.

**Comment by dgutov** [comment]
Thanks for the report.
