### ISSUE TITLE
Unwanted "Visit tags table (default TAGS)"

### ISSUE THREAD

**Issue by alxest** [company-mode/company-mode#333]
I use (global-company-mode).
Sometimes, this interactive command shows up in unwanted way.
I use helm-mode and it seems the function "company-capf" is called. (Without helm-mode, a file dialog appears and there is no function name written)
1) When I execute eshell, it appears almost whenever I type any character.
2) Execute "C-c C-b" (tuareg-eval-buffer) inside while Tuareg mode is on. Inside that Tuareg interactive buffer (*ocaml-toplevel*), when I type a digit and then semi-colon, it appears.
I temporarily add hook to disable company-mode in these modes.
Is it intended situation? Is there more proper way to deal with it?
Any advice is welcome, thank you.

**Comment by dgutov** [comment]
Apparently, somehow you have `tags-completion-at-point-function` in the local value of `completion-at-point-functions`, which should never happen, as long as the latter variable's value is only changed using the hook functions (such as `add-hook`). When it's only in the global value, we filter it out in `company--capf-data-real`.

To confirm it, `M-x describe-variable completion-at-point-function` in the buffers where you have this problem. The local value should end with `t`, but shouldn't include the tags completion function.

Then you should search for something like `(make-local-variable 'completion-at-point-functions)` in your installed packages. It doesn't guarantee bad behavior (`tern-mode` manages to work without this problem), but it's a good indicator.

**Comment by alxest** [comment]
Thanks for your reply.
Here is what I found.
Restart emacs -> problem disappeared. 
Variable was
~~~
completion-at-point-functions is a variable defined in `minibuffer.el'.
Its value is (tuareg-completion-at-point comint-completion-at-point t)

Local in buffer *ocaml-toplevel*; global value is 
(tags-completion-at-point-function)
~~~
However, sometimes its value suddenly changes to below
(I have experienced this only twice, and I cannot reproduce it...)
~~~
completion-at-point-functions is a variable defined in `minibuffer.el'.
Its value is
(tuareg-completion-at-point comint-completion-at-point tags-completion-at-point-function)

Local in buffer *ocaml-toplevel*; global value is 
(tags-completion-at-point-function)
~~~
It seems exactly what you've described was the problem.
I think tuareg-mode is concerned with this issue, not company-mode, so I will close this issue.
Thanks for your reply. ;)

**Comment by dgutov** [comment]
Probably not tuareg, it seems to do what's proper: https://github.com/ocaml/tuareg/blob/eab0dba22d027d07367b6037d073e66d49c81d4e/tuareg.el#L2036

Let me know if you find out the exact problem package.

**Comment by alxest** [comment]
Of course. Thanks a lot!

**Comment by dgutov** [comment]
You should try `grep completion-at-point-functions -r ~/.emacs.d/` (this will also scan the `elpa` directory), and see which packages use `make-local-variable` on it.

**Comment by alxest** [comment]
Below is the result.
~~~ sh
grep -n completion-at-point-functions -r /home/youngju.song/.emacs.d/ /dev/null
Binary file /home/youngju.song/.emacs.d/elpa/evil-20150318.1515/evil-ex.elc matches
/home/youngju.song/.emacs.d/elpa/evil-20150318.1515/evil-ex.el:227:    (make-variable-buffer-local 'completion-at-point-functions))
/home/youngju.song/.emacs.d/elpa/evil-20150318.1515/evil-ex.el:228:  (setq completion-at-point-functions
/home/youngju.song/.emacs.d/elpa/evil-20150318.1515/evil-ex.el:499:  the variable `completion-at-point-functions'. When FUNC is
/home/youngju.song/.emacs.d/elpa/evil-20150318.1515/evil-ex.el:564:    (setq completion-at-point-functions
/home/youngju.song/.emacs.d/elpa/tuareg-20150316.1247/tuareg.el:2036:  (add-hook 'completion-at-point-functions #'tuareg-completion-at-point nil t)
Binary file /home/youngju.song/.emacs.d/elpa/tuareg-20150316.1247/tuareg.elc matches
Binary file /home/youngju.song/.emacs.d/elpa/company-20150317.1206/company-capf.elc matches
/home/youngju.song/.emacs.d/elpa/company-20150317.1206/company.el:288:    (company-capf . "completion-at-point-functions")
/home/youngju.song/.emacs.d/elpa/company-20150317.1206/company-capf.el:1:;;; company-capf.el --- company-mode completion-at-point-functions back-end -*- lexical-binding: t -*-
/home/youngju.song/.emacs.d/elpa/company-20150317.1206/company-capf.el:45:  (cl-letf* (((default-value 'completion-at-point-functions)
/home/youngju.song/.emacs.d/elpa/company-20150317.1206/company-capf.el:50:                      (default-value 'completion-at-point-functions)))
/home/youngju.song/.emacs.d/elpa/company-20150317.1206/company-capf.el:51:             (data (run-hook-wrapped 'completion-at-point-functions
/home/youngju.song/.emacs.d/elpa/company-20150317.1206/company-capf.el:57:  "`company-mode' back-end using `completion-at-point-functions'."
Binary file /home/youngju.song/.emacs.d/elpa/company-20150317.1206/company.elc matches
/home/youngju.song/.emacs.d/eshell/history:127:grep completion-at-point-functions -r ~/.emacs.d/

Grep finished (matches found) at Mon Mar 30 01:35:42
~~~
Not exactly "make-local-variable", but the first line shows 
~~~
evil-ex.el:227:    (make-variable-buffer-local 'completion-at-point-functions))
~~~
Would it be related?

**Comment by dgutov** [comment]
Yep, if you do use Evil and not just have it installed, it's a likely cause of this problem.

**Comment by alxest** [comment]
Yes, I do use evil-mode, and I have very little customizations. (just rebinding a key)

**Comment by peterbecich** [comment]
Comment, when this action at point is enabled as described in this thread, and when editing through TRAMP, the performance issue is multiplied.
