### ISSUE TITLE
company-clang: leave function/method arguments unchanged instead of "arg0, arg1, ..."

### ISSUE THREAD

**Issue by ddovod** [company-mode/company-mode#336]
Suppose we have:
```
class Class
{
    void member(int count, float length, const std::vector<std::pair<int, float>>& params);
};
```
And we want to implement the Class::method. When the completion is made, we can see that the arguments are equal to the declaration ones:
```
void Class::member(int count, float length, const std::vector<std::pair<int, float>>& params)
```
But if we press TAB or just leave completed region, all arguments is renamed to arg0, arg1, and so on:
```
void Class::member(arg0, arg1, arg2) |
```
It would be better if the argгments remain unchanged after the completion (see XCode behavior, very handy).

Temp solution for me:
```
company-template.el
187 -                     (format "arg%d" counter) sig)
187 +                     (format "%s" sig) sig)
```

**Comment by dgutov** [comment]
> (see XCode behavior, very handy)

Where can I see it?

**Comment by ddovod** [comment]
https://raw.githubusercontent.com/burczyk/XcodeSwiftSnippets/master/assets/xcode-use-code-snippet.gif

Look at the NSLocalizwdString(...).
In this gif you can see the "snippet" feature, but XCode is completing cpp code similarly. If you will leave autocompletion region, "key", "value" and other parameters remains on their places.

**Comment by dgutov** [comment]
Snippet completion and code completion are not the same, though. If we just leave the values as they were, though, in a C-like language this will result in syntax error most of the time, if not always.

**Comment by ddovod** [comment]
But if we put arg0, arg1, argn instead of parameter declarations, we will get syntax errors as well.
The point is to give the user either leave the parameters content without any changes (we want to write implementation of the previously defined method) or change them in place. With the company default behavior only second case is achievable. And in my proposal we can use both of them.

**Comment by dgutov** [comment]
> But if we put arg0, arg1, argn instead of parameter declarations, we will get syntax errors as well.

But those are syntax errors of... different magnitude? Anyway, they're easier to go back and replace, compared to the full parameter declarations.

> we want to write implementation of the previously defined method

All right, that's a use case I haven't considered previously. It actually works for methods, but not for plain function definitions (I wonder why).

I'll make the change you've suggested, and we'll wait for any negative feedback.

Would it be better to pick between "replace" and "keep as-is" based on the current context? Would `::` preceding the function name be a good indicator?

**Comment by ddovod** [comment]
arg0, arg1 option:
http://ideone.com/kCwHlE

In my option:
http://ideone.com/5RPkYt

I am a c++ developer. Both errors for me are very similar. Both of them says that in the function call something is wrong.

:: is not very good indicator (static member functions are called like Class::method). If you have a mac os, just try the XCode completion style for c/c++ code. For me it's the most comfortable way i ever seen before. So I'm assured on 100% that people will find this completion method useful.
Thank you a lot, Dmitry, and do you speak russian?

**Comment by dgutov** [comment]
> Both errors for me are very similar. Both of them says that in the function call something is wrong.

The former version is a bit easier to understand, and to fix with a smaller number of keypresses. Further, not every user is necessarily an experienced C++ developer.

The benefits are not that big, I agree, but it's something to keep in mind.

> :: is not very good indicator (static member functions are called like Class::method)

So a static method call starts very similar to an instance method implementation? Augh.

> If you have a mac os, just try the XCode completion style for c/c++ code.

I don't. If there are no gifs/videos out you can link to, why not make a mini-screencast yourself?

> Thank you a lot, Dmitry, and do you speak russian?

Sure. But let's keep conversations here in English, so that anyone can read them.

**Comment by ddovod** [comment]
> So a static method call starts very similar to an instance method implementation? Augh.
Yes = ) And don't forget about functions inside namespaces

> But let's keep conversations here in English, so that anyone can read them.
No problem.

I am at the work now, so I'll record a screencast in evening today.

**Comment by ddovod** [comment]
Here is the xcodes' completion demonstration
https://www.dropbox.com/s/0nk192p9rvrrv92/xcode_completion.mp4?dl=0

**Comment by dgutov** [comment]
Wonderful, thanks!

The other differences in behavior (`tab` only jumping between the fields, `ret` entering the default value, keeping the template active when cursor leaves its bounds) can also be up for discussion, but I think the basic yasnippet behavior has become somewhat of a standard (and was probably inherited from TextMate snippets).
