### ISSUE TITLE
clang parse error

### ISSUE THREAD

**Issue by dzhwinter** [company-mode/company-mode#338]
failed with error 1:
/usr/bin/clang -fsyntax-only -Xclagn -code-completion-macros -x c++  -I/home/dzh/Downlaods/caffe/include/ -I/usr/local/include

It can not really parsing my project head file and get the right completetion.

I check your answer in #80 
but still not work.
emacs version is 24.3.1
os. ubuntu 14.04

**Comment by dzhwinter** [comment]
clang 3.4

**Comment by dgutov** [comment]
Take a look at https://github.com/company-mode/company-mode/issues/329#issuecomment-84350029 and my reply there.

**Comment by dgutov** [comment]
To clarify: `company-clang` does not parse your project settings. If you intend to use it with a non-trivial project, you'll need to set `company-clang-arguments` to an appropriate value, either manually or using some script, or a third-party package (like [cpputils-cmake](https://github.com/redguardtoo/cpputils-cmake/)).
