### ISSUE TITLE
company-dabbrev downcases surprisingly because case-replace has the opposite meaning

### ISSUE THREAD

**Issue by rneatherway** [company-mode/company-mode#339]
I had the same problem as #125 and #14, but in non-code buffers. I looked into the help and found that `company-dabbrev-downcase` means to keep the candidates as-is when it is `nil`, and it defaults to using the value of `case-replace`. However `case-replace` has the opposite meaning (keep as-is when it is non-`nil`). So I think there should be a `not` here: https://github.com/company-mode/company-mode/blob/master/company-dabbrev.el#L161

**Comment by dgutov** [comment]
> However case-replace has the opposite meaning (keep as-is when it is non-nil).

I think it's just a confusing docstring. It says:

> Non-nil means `query-replace' should preserve case in replacements.

But that means that when it's non-nil, the replacement string is modified to fit the case of the string it's replacing. In our case, the completion candidates are the potential replacement strings.

Anyway, the docstring `company-dabbrev-downcase` is pretty literal: use the value, not "the meaning", or "work similarly", or something like that. So it shouldn't be surprising either way.

**Comment by rneatherway** [comment]
I think it means the opposite of what you said. From the docstring for `query-replace`:

> Replacement transfers the case pattern of the old text to the new text, if \`case-replace' and
\`case-fold-search' are non-nil and FROM-STRING has no uppercase letters.

So if `case-replace` is non-nil, the casing of the replacement string is used. In the completion case where the candidates are our replacement strings, this is the behaviour I want, and I think it should be the default (as for `query-replace`). Would you agree?

> Anyway, the docstring company-dabbrev-downcase is pretty literal: use the value, not "the meaning", or "work similarly", or something like that. So it shouldn't be surprising either way.

I found it really confusing that it would use the value, but interpret it in the opposite way. If it interpreted the value the same way, then the default of `company-dabbrev-downcase` of `case-replace` would probably be better.

Don't get me wrong, I think this is a great piece of software, and I am very happy to see it actively developed so that I can use it over autocomplete. I would like to help improve it. I am planning to move the [F# intellisense support](https://github.com/fsharp/fsharpbinding/tree/master/emacs) over to use company mode based on my experience so far.

**Comment by dgutov** [comment]
> So if case-replace is non-nil, the casing of the replacement string is used.

Nope. The replacement string is the "new text", and it's being transferred the case pattern *to*. When "case-replace and case-fold-search are non-nil", it uses the casing of the original string.

Have you tried experimenting? Feel free to prove me wrong with a code snippet.

> I am planning to move the F# intellisense support over to use company mode based on my experience so far.

Glad to hear it. :)

**Comment by rneatherway** [comment]
Right, I now understand what you (and the docstring) mean. I do think that there is a difference here though. In the `query-replace` case, you have a complete word to use the casing of. In the `company-mode` case you have only a prefix and to downcase the rest seems pretty arbitrary. I'd like to suggest a change to the default behaviour such that given a candidate completion and a prefix, only the casing of the prefix in the candidate is adjusted, and the rest is left as it was.

**Comment by dgutov** [comment]
> I'd like to suggest a change to the default behaviour such that given a candidate completion and a prefix, only the casing of the prefix in the candidate is adjusted, and the rest is left as it was.

That sounds like it can be summed in a simpler fashion: "keep the prefix as-is, only replace the part of the symbol that comes after it". The `keep-prefix` value of `company-dabbrev-ignore-case` provides this behavior (but if you're actually using `company-dabbrev-code`, it has its own variable for this).

Overall, I agree that the downcasing behavior is not optimal. It's just that I haven't been able to design good alternative rules that I'd like, yet. See #133 for a previous discussion.

**Comment by rneatherway** [comment]
> That sounds like it can be summed in a simpler fashion: "keep the prefix as-is, only replace the part of the symbol that comes after it". The keep-prefix value of company-dabbrev-ignore-case provides this behavior (but if you're actually using company-dabbrev-code, it has its own variable for this).

Do you mean this is the behaviour if `company-dabbrev-downcase` is also `nil`? Then I would suggest changing the default of that varible to nil. I'll close this for now to avoid cluttering your issue tracker.

**Comment by dgutov** [comment]
> Do you mean this is the behaviour if company-dabbrev-downcase is also nil?

**Comment by rneatherway** [comment]
Yes, this is what I have been using, I just wanted to check as it sounded
like you meant it was independent.

**Comment by dgutov** [comment]
It is independent. What combination of settings works not how you'd expect?

**Comment by rneatherway** [comment]
I think we are talking at cross-purposes. I don't think preserving the case of the part of the candidate after the prefix is useful if it has already been lowercased.

**Comment by dgutov** [comment]
Maybe we are. I thought it was about these options being independent.

> preserving the case of the part of the candidate after the prefix is useful if it has already been lowercased

Sorry, this sounds like an oxymoron. If it's downcased, we already don't preserve its case. What situation are you referring to?

**Comment by rneatherway** [comment]
Yes, this is why I was confused. I interpreted your use of independent as "setting `company-dabbrev-ignore-case` gives the behaviour regardless (independent) of the value of `company-dabbrev-downcase`". I think we're on the same page now.

**Comment by ntc2** [comment]
These doc strings also make no sense to me, but setting `company-dabbrev-downcase` to `nil` solved my problem.
