### ISSUE TITLE
Wrong candidates are collected if prefix icludes '(:'

### ISSUE THREAD

**Issue by Alexander-Miller** [company-mode/company-mode#341]
This kind of prefix will oftentimes occur if you are editing a color theme. In a situation like '(:[POINT]' when I company-complete what should happen is that I get a list of candidates starting with ':', that is :height, :Tag, etc.
Instead company would say that no completions were found. Now that I have installed gut-gutter I instead receive a list of its methods, but those have their colon in the middle of the word, e.g. 'git-gutter:toggle', so those should not be listed at all.

This problem only occurs for this specific prefix and I've not encountered it anywhere else. Just adding a space to make '( :[POINT]' gives the correct results, so it's not an issue of context.

I am running company version 0.9.0-cvs and emacs 25.0.50.1, the latter built from source.
My company config can be found [here](https://github.com/Alexander-Miller/dotfiles/blob/master/.emacs.d/init/company.el).

**Comment by dgutov** [comment]
What backend? Is it `company-capf`? Does `C-M-i` show you the desired completions?

**Comment by Alexander-Miller** [comment]
`C-M-i` does not give the desired results, but neither does it give me options where the colon is in the middle of the word.

I did not install any lisp related packages ([here's the exact list](https://github.com/Alexander-Miller/dotfiles/blob/master/.emacs.d/init/packages.el)), so the backend should be whatever company comes with. 
I do not know how to see which backend is being used for a specific completion, but my current value of company-backends is:
 ((company-latex-commands company-math-symbols-latex company-math-symbols-unicode)
 (company-auctex-macros company-auctex-symbols company-auctex-environments)
 company-auctex-bibs company-auctex-labels company-ghc company-anaconda company-bbdb company-nxml company-css company-eclim company-semantic company-clang company-xcode company-cmake company-capf
 (company-dabbrev-code company-gtags company-etags company-keywords)
 company-oddmuse company-files company-dabbrev)

**Comment by dgutov** [comment]
> C-M-i does not give the desired results, but neither does it give me options where the colon is in the middle of the word

Then it must be a bug in Emacs. You should `M-x report-emacs-bug` and write a small reproduction scenario step-by-step.

> I do not know how to see which backend is being used for a specific completion

It's displayed in the mode-line during completion.

**Comment by Alexander-Miller** [comment]
>It's displayed in the mode-line during completion.

Funny how I never noticed that. Anyway, yes, the backend is company-capf.

I'll now rebuild emacs and then report back, other will probably want to know if the issue still persists. On this computer that'll take maybe an hour. Then I suppose the issue can be closed.

**Comment by dgutov** [comment]
> other will probably want to know if the issue still persists

It probably does: there hasn't been any major changes in `elisp-completion-at-point` lately.

**Comment by Alexander-Miller** [comment]
I've rebuilt and tested now, and you're right, the bug is still around.
I'll have a look at emacs' bugtracker and make a report there.
