### ISSUE TITLE
Invoke with tab

### ISSUE THREAD

**Issue by ephexeve** [company-mode/company-mode#343]
I am using Company mode with Emacs-ycmd, instead of enter, is there anyway I can complete it with tab? So it completes the suggestion?
Currently I have my tab binded to:
```
; bind company-select-next to tab
(eval-after-load 'company
  '(progn
     (define-key company-active-map (kbd "TAB") 'company-select-next)
     (define-key company-active-map [tab] 'company-select-next)))
;; (setq company-selection t) <-- this doesn't make sense -- Dmitry
(setq company-idle-delay 0)
```
This works for selecting the next completion, I would like to bind it so it also selects the completion suggestion.

For example:
```
int some_random_var = 0
some_<tab> = some_random_var
```

**Comment by dgutov** [comment]
Try binding `company-complete-common-or-cycle` instead.

**Comment by ephexeve** [comment]
@dgutov it worked like expected, thanks. 
Is there anyway to achieve the same action as this one? https://asciinema.org/a/19319 (vim using YouCompleteMe)
Using tab to navigate the completion and enter to select it or just type another character and it will keep the last selection?

**Comment by dgutov** [comment]
> type another character and it will keep the last selection

**Comment by dgutov** [comment]
> type another character and it will keep the last selection

Any character at all? No, we don't have this option. Maybe we should, but it looks unusual.

**Comment by unknownzerx** [comment]
@dgutov 
+1 for the action which @ephexeve has metioned. I feel comfortable with that.

It is the behavior same to auto-complete.el that

- press tab first to complete common
- then press tab again to complete all (select the first candidate)
  - but keep the candidates popup open
  - and press more tab to select other candidate

thus all I need to do is press tab several times and continue to edit. No more "RET" needed.

**Comment by aaronjensen** [comment]
I came here to file this issue as well. This is a very handy method of auto-completion in my experience. One you get used to it, having to press enter feels quite unnatural. I wouldn't agree w/ @unknownzerx's first bullet, however, so maybe it makes sense to have separate commands that people can bind on their own. 

My preference:

* as you type, menu shows with nothing selected
* tab selects and completes first but leaves menu open. 
* Repeated tab selects & completes next, shift tab selects and completes previous
* Any other key moves on and closes the window.

![acp](https://cloud.githubusercontent.com/assets/8588/12077700/359a9a96-b1a7-11e5-97ac-ff7375291e3a.gif)

**Comment by dgutov** [comment]
I don't understand this idea: "Any other key moves on and closes the window".

You can't type further, to narrow down the list of completions? If you type *any* character, the current completion will be selected?

It doesn't seem trivial to implement, but I could accept a patch.

**Comment by aaronjensen** [comment]
Once you've hit tab to select one, no. The idea is that you type until it is one of the top few then hit tab enough times to select it then keep typing. Part of what makes this work is good sources and good sorting, which is why I implemented https://github.com/aaronjensen/vim-recentcomplete which tends to do a really good job of knowing what I want to autocomplete (because chances are it's something I've typed before recently)

I'm super new to emacs still and haven't had a chance to learn much elisp, but if I get some time, maybe I could work on this. Could you point me or whoever else may be interested in working on this in the right direction?

**Comment by dgutov** [comment]
> Could you point me or whoever else may be interested in working on this in the right direction?

We've had some requests like this (you can search the issue tracker), but not from people who've contributed any significant amount of code.

**Comment by dgutov** [comment]
> Once you've hit tab to select one, no. The idea is that you type until it is one of the top few then hit tab enough times to select it then keep typing.

All right, the idea makes sense. Still, making it work like that might require non-trivial changes to the inner workings: especially making it easy to switch between the current approach and the suggested one.

**Comment by dgutov** [comment]
Come to think of it, maybe the solution could be more or less self-contained. And not too hard to implement.

You could create a new command which the user would bind to `TAB` in `company-active-map`. As soon as it's invoked, it takes over all input handling in a loop very similar to `company--electric-do`, dispatches `TAB` to "next line", `<backtab>` to "previous line", `keyboard-quit` to `company-abort` (I guess), and upon receiving any other input (maybe with some other exceptions? I dunno), performs completion using the current line, and calls `company--unread-last-input`.

Patch welcome!

**Comment by aaronjensen** [comment]
Thanks, I've been looking at this. One thing I'm not sure of yet is if there's an easy way to get company-mode's popup to be up w/o having a selection. That's one of the requirements--there is no initial selection, the first tab selects the first item. Thanks for the suggestions thus far!

**Comment by dgutov** [comment]
> there is no initial selection, the first tab selects the first item

That might be hard to do: a lot of places assume that current selection is present. However, the new command could track whether you've pressed `TAB` at least once, and if not, avoid inserting the selection into the buffer.

**Comment by aaronjensen** [comment]
@dgutov What do you think about an approach wherein we prepend either an empty candidate or the existing prefix as a candidate, and then somehow in `company-pseudo-tooltip-frontend` we don't render the option if it is blank/the prefix. It doesn't look like it'd be super easy to do this, but I'm still working to learn the code. Does that seem like a reasonable approach to you, at least for the problem of having "no selection"?

**Comment by dgutov** [comment]
@aaronjensen If you advise `company-pseudo-tooltip-frontend` to do something differently, why don't you just bind `company-selection` to `-1` as appropriate around it?

**Comment by marcinant** [comment]
@aaronjensen Could you please tell me what editor is visible on animated gif above? Is this Emacs?

You mentioned vim-recentcomplete. How does it compare to *company-statistics-mode*?

**Comment by aaronjensen** [comment]
@marcinant that's vim. [vim-recentcomplete](https://github.com/aaronjensen/vim-recentcomplete) sounds like it is similar to company-statistics-mode but it is completely different. vim-recentcomplete uses your recent git changes to populate autocomplete. It's not a sort, the idea behind it is that you often want to repeat things that you've typed recently, so it completes things you've added recently in your file (differences between your working copy and head, or recent changes--something like changes w/in the last half hour or so). TBH I've never had a better autocomplete experience than with it except for maybe visual studio in a statically typed language. I've been considering attempting to write a company backend the mimic it, but not sure when i'll find the time :smile:

**Comment by aaronjensen** [comment]
@dgutov I'll explore that, I'm not sure I've got my head wrapped around how that would solve for it just yet, but I'll see what I can do.

**Comment by aaronjensen** [comment]
@dgutov there's quite a bit going on that I don't understand, so every time I sit down to work on this I don't make it very far. The most recent snag is that I don't know what `company-tooltip-offset` does. It interferes w/ my ability to set `company-selection` to `-1` as it somehow gets set to -1 as well and decrements `company-selection` by it.

**Comment by dgutov** [comment]
> company-tooltip-offset

That's how much the user scrolled down the popup - like the number is the first visible line (which might, or might not, be selected). Indeed, the related logic might be a problem, I hadn't considered that.

**Comment by aaronjensen** [comment]
What about the idea of inserting a candidate that is the same as the prefix and just not rendering that line?

**Comment by dgutov** [comment]
Doesn't sound great to me, but if you manage to do that via advice--by all means, go ahead.

**Comment by aaronjensen** [comment]
It seems like the only way then would be a fairly large rewrite/reshuffle... but I'm still learning the codebase. I'm open to any other guidance/ideas.

**Comment by dgutov** [comment]
Maybe you'd get by with the first candidate being displayed as selected for now? It's just looks, after all.

**Comment by aaronjensen** [comment]
@dgutov here is what I have so far. It seems to work with my limited testing so far except for when I hit backspace without completing something, I get an error from `company-capf`:

```
Company: backend company-capf error "Nothing to complete" with args (annotation **company-no-selection**)
```

The naming of things probably isn't very good, I'm open to better naming for sure. 

Any suggestions about the approach or ideas on the nothing to complete error? 

Thanks again for your help so far.

**Comment by dgutov** [comment]
> Nothing to complete

This error apparently comes from some particular completion function. I tried your code in an Elisp, and didn't see it.

The code is a bit buggy (e.g. insertion can cut off a preceding char), but I'm sure you'll be able to polish it.

**Comment by aaronjensen** [comment]
> insertion can cut off a preceding char

What do you mean, how do I repro this?

**Comment by dgutov** [comment]
I was just playing around, and got into a couple of weird states by initiating completion, then pressing tab, or canceling, then backspacing, and doing it all over again. I have no time to do a repro right now, sorry.

**Comment by aaronjensen** [comment]
Awesome, thanks. I fixed a few bugs I could find based on your hints. The gist has been updated.

@ephexeve @unknownzerx if you're still interested, please give it a try and let me know if you hit any issues: https://gist.github.com/aaronjensen/a46f88dbd1ab9bb3aa22

**Comment by aaronjensen** [comment]
@dgutov I got rid of the extra placeholder candidate. I had to advise 3 functions to allow for a `company-selection` of `-1`: https://gist.github.com/aaronjensen/a46f88dbd1ab9bb3aa22#file-company-complete-cycle-el-L37-L57

What do you think I should do with this? Is there a way to integrate it into `company-mode` or should I publish it as its own package?

**Comment by neuromage** [comment]
@aaronjensen this is pretty cool. Thanks for doing this! But to get it to work properly, I also had to set the require match option to nil:

`(setq company-require-match nil)`

**Comment by aaronjensen** [comment]
@neuromage no problem. I don't really know what that flag does (mine was nil already). I'll set it to nil in the gist, thanks.

**Comment by dgutov** [comment]
> What do you think I should do with this? Is there a way to integrate it into company-mode or should I publish it as its own package?

I'd consider a patch. This UI looks pretty nice, but we should support the existing one as well. So the more smooth the integration of both styles is, the better.

The new code will also need tests, and probably a copyright assignment to FSF (if the patch changes >15 lines in a significant fashion).

In the meantime, I'd rather it lives in a gist; releasing it as a package seems awkward.

In the meantime,

**Comment by marcinant** [comment]
:+1:  This is cool. Please include this code in `company`.

**Comment by r39ex** [comment]
Registered on GitHub to tell you: Yes, please include this!

**Comment by dgutov** [comment]
Closing in favor of #526 because of its better description and search-ability.
