### ISSUE TITLE
Truncating long completions

### ISSUE THREAD

**Issue by cpitclaudel** [company-mode/company-mode#344]
Hi,

My company-coq plugin from time to time generates very long completions, which cause lines to wrap in the completion dialog. It would be nice to be able to do either or both of the following two thing:

* Specify (using a 'prettyprint argument to the engine, maybe?) how to display a candidate. This is not the same as returning that display value in 'candidate and using a post-action to convert back to the real value, since the text in the buffer would still be matched against the candidate, not the pretty-printed form. Ideally, the pretty printer would even allow for some formatting, for example italics or bold.

* Automatically truncate long candidates, so that they display better.

Thanks!
Clément.

**Comment by dgutov** [comment]
Wrap? That's surprising: truncation to the window width works well enough, as far as I've seen.

Could you post a screenshot and the `M-x company-diag` output?

Custom rendering would definitely be a harder approach.

**Comment by cpitclaudel** [comment]
The problem happens when there's a character on the line that's wider than the base character (math symbols for example). In the example posted it's a result of using `prettify-symbols-mode`.

![screenshot from 2015-04-28 21 10 45](https://cloud.githubusercontent.com/assets/8181630/7383311/2e563590-edeb-11e4-9bbe-e9dd1cc843c4.png)

company-diag gives me an error, possibly because I'm on Emacs 25:
```
Debugger entered--Lisp error: (void-function find-library-name)
  find-library-name("company")
  company-version()
  company-diag()
  funcall-interactively(company-diag)
  #<subr call-interactively>(company-diag record nil)
  ad-Advice-call-interactively(#<subr call-interactively> company-diag record nil)
  apply(ad-Advice-call-interactively #<subr call-interactively> (company-diag record nil))
  call-interactively(company-diag record nil)
  command-execute(company-diag record)
  execute-extended-command(nil "company-diag")
  ...
```

I didn't initially realize that the problem was due to `prettify-symbols-mode` though, so maybe this is one of these things that can't really get fixed in the current text-based popups scheme.

**Comment by dgutov** [comment]
> company-diag gives me an error, possibly because I'm on Emacs 25:

Sorry about that. Nothing to do with Emacs 25 (I'm using it as well), should work now.

**Comment by dgutov** [comment]
> maybe this is one of these things that can't really get fixed in the current text-based popups scheme

Maybe it is, but I can't say for sure yet. Could you give me an easy reproduction scenario?

**Comment by cpitclaudel** [comment]
Sure. Let me try to find a small example :)

**Comment by cpitclaudel** [comment]
Here's a pretty short repro:

```elisp
(company-begin-with '("Candidate with a pesky unicode character '…'" "Other"))
```

**Comment by cpitclaudel** [comment]
Also, I was wrong: It's not due to `prettify-symbols-mode`, but instead to the `meta containing a wide character (…).

**Comment by dgutov** [comment]
Can't reproduce, actually. Probably because my current font (Fire Mono) includes that character. And `(string-width "…")` evaluates to 1 here.

Could it be that you observe fallback to a different font (thus, with different dimensions)? Indeed, we really can't handle that.

**Comment by cpitclaudel** [comment]
Probably a different font, yes. Can you try with the following?

```elisp
(company-begin-with '("⊢⊤⊥→⇒λ∀∃∧∨¬≠⧺𝓝ℤℕℚℝ𝔹𝓟⟶α⤭" "Other"))
```

**Comment by dgutov** [comment]
Yup, I can see it with this example.

**Comment by dgutov** [comment]
At the moment I can only suggest to use a monospace font that includes all the symbols you're using.

**Comment by cpitclaudel** [comment]
That sounds like a fair restriction :) Thanks for the quick updates.
