### ISSUE TITLE
company-backend ask for interactive input Module name in for robe-mode.

### ISSUE THREAD

**Issue by stardiviner** [company-mode/company-mode#346]
I edit ruby code like this:

``` ruby
class Array
  def random_each_block
    shuffle.each do |el|
      yie| # yield el
    end
  end
end
```

Here is the screenshots:
![company-mode for ruby in org-babel 1](https://cloud.githubusercontent.com/assets/378699/7421966/8eb1b7a8-efbb-11e4-94bb-ead5bcf846fd.png)
![company-mode for ruby in org-babel 2](https://cloud.githubusercontent.com/assets/378699/7421967/8ec1891c-efbb-11e4-8b61-957f012e3d61.png)

The `|` is the point position.

The situation about company-mode:
1. show the list.
2. then I navigate down the popup menu.
3. when I navigate back to candidate `yield`, Emacs opened prompt in minibuffer
   `Module: {Fiber^ | Enumerator::Yielder | Proc}`  (I guess robe-mode [backend company-capf] is doing something, and missing the Module namespace or something else.)

Here is the output of `company-diag`

```
Emacs 25.0.50.1 (x86_64-unknown-linux-gnu) of 2015-04-20 on dark
Company 0.9.0-cvs

company-backends: (company-robe company-edbi company-irony company-capf company-yasnippet
              (company-gtags company-etags)
              company-keywords company-elisp
              (company-clang company-cmake)
              company-nxml company-css company-bbdb
              (company-dabbrev-code company-dabbrev company-abbrev)
              company-files)

Used backend: company-robe
Prefix: #("yie" 0 3
  (font-lock-fontified t src-block t fontified t font-lock-face nil face
                       (highlight-symbol-face)))

Completions:
  #("yieldreturn_tag" 0 15 (face font-lock-function-name-face)) #("(text)" 1 5 (face font-lock-variable-name-face))
  #("yieldparam_tag" 0 14 (face font-lock-function-name-face)) #("(text)" 1 5 (face font-lock-variable-name-face))
  #("yield_tag" 0 9 (face font-lock-function-name-face)) #("(text)" 1 5 (face font-lock-variable-name-face))
  #("yield" 0 5 (face font-lock-function-name-face)) #("(args...)" 1 8 (face font-lock-variable-name-face))
  #("yield" 0 5 (face font-lock-function-name-face)) #("(args...)" 1 8 (face font-lock-variable-name-face))
  #("yield" 0 5 (face font-lock-function-name-face)) #("(args...)" 1 8 (face font-lock-variable-name-face))
```

Emacs version: 25.0.50.1
company-mode: latest from github (install with el-get)

I guess this issue could be from robe-mode. But I'm not sure, so I post it here at first.

**Comment by dgutov** [comment]
Well, obviously it's not company-mode asking for the module name. It knows nothing about them.

I'm guessing you use `company-quickhelp`. Please update to its latest version, as well as the `robe` commit I've pushed just now.

**Comment by stardiviner** [comment]
still small isuee: void function `completing-read`.

```
(void-function completing-read)
  completing-read("Module: " (("Fiber" "Fiber" nil "yield" (("rest"))) ("Enumerator::Yielder" "Enumerator::Yielder" t "yield" (("rest"))) ("Proc" "Proc" t "yield" (("rest")))) nil t)
  company-robe--choose-spec(#("yield" 0 5 (face font-lock-function-name-face)))
  company-robe(doc-buffer #("yield" 0 5 (face font-lock-function-name-face)))
  apply(company-robe (doc-buffer #("yield" 0 5 (face font-lock-function-name-face))))
  company-call-backend-raw(doc-buffer #("yield" 0 5 (face font-lock-function-name-face)))
  apply(company-call-backend-raw (doc-buffer #("yield" 0 5 (face font-lock-function-name-face))))
  company--force-sync(company-call-backend-raw (doc-buffer #("yield" 0 5 (face font-lock-function-name-face))) company-robe)
  company-call-backend(doc-buffer #("yield" 0 5 (face font-lock-function-name-face)))
  company-quickhelp--doc(#("yield" 0 5 (face font-lock-function-name-face)))
  company-quickhelp--show()
  apply(company-quickhelp--show nil)
  timer-event-handler([t 0 0 500000 nil company-quickhelp--show nil idle 0])
```

But I can check out `completing-read`. weird.

**Comment by dgutov** [comment]
Err, works for me Have you tried restarting, reinstalling, etc?

**Comment by dgutov** [comment]
Scratch that. It definitely doesn't work for me either with enabled `company-quickhelp-mode`.

@expez, could you perform the override using the `completing-read-function`, instead of using `cl-letf` and `symbol-function`?

**Comment by expez** [comment]
```elisp
(let ((completing-read-function 'company-quickhelp--completing-read)
  ...)
```

and 

```elisp
(let ((completing-read-function #'company-quickhelp--completing-read)
  ...)
```

Doesn't actually work to override the `completing-read-function` temporarily.

**Comment by stardiviner** [comment]
@dgutov I've tried restart, and reinstalling, not work.
And see the updates, seems this problem is stacked.
Keep is open?
I have not figured why `completing-read` is void.

**Comment by dgutov** [comment]
@expez What code have you tried exactly? This works for me:

```el
(defun company-quickhelp--doc (selected)
  (let* ((completing-read-function #'company-quickhelp--completing-read)
         (doc-buffer (company-call-backend 'doc-buffer selected))
         (doc-and-meta (when doc-buffer
                         (company-quickhelp--doc-and-meta doc-buffer)))
         (truncated (plist-get doc-and-meta :truncated))
         (doc (plist-get doc-and-meta :doc)))
    (unless (string= doc "")
      (if truncated
          (concat doc "\n\n[...]")
        doc))))
```

However, the main problem with your current code turns out to be a typo: `company-quickhelp-completing-read` is missing a extra dash in the middle, hence the `void-function` error we're getting.

@stardiviner We'll keep the issue open until it's resolved.

**Comment by expez** [comment]
I've fixed the missing dash.  Thanks for letting me know!

**Comment by dgutov** [comment]
No problem. This should work now.

**Comment by ovy** [comment]
I want to revisit this, because ido-ubiquitous is too big of a hammer, and on the other hand ido is really smooth for robe, since the first choice is usually right. I think what needs to be done is override completion-read-function, but *only if default*. Since it would take me a little while to write & test this, could you comment on whether you'd accept it?

**Comment by dgutov** [comment]
> override completion-read-function, but only if default, solving this issue.

What's the end goal? When would you actually *want* to ask the user, from `company-quickhelp`?

> could you comment on whether you'd accept it?

Myself, probably not (as I don't understand the point). But `company-quickhelp` lives over there: https://github.com/expez/company-quickhelp

**Comment by ovy** [comment]
Sorry if this was unclear -- my goal has nothing to do with company or quickhelp. I just want to use ido for robe-mode, and it seems that the particular interaction in this issue was preventing you from doing the obvious thing to get that and you ended up disabling ido. I think we can make this work.

(Meanwhile, I went and moved the comment to the robe-mode repo, where the discussion really belongs)
