### ISSUE TITLE
company triggers tramp?

### ISSUE THREAD

**Issue by expez** [company-mode/company-mode#347]
I was trying to mention a redirect to `/login` in a docstring and then later in a commit message and in both cases a prompt from tramp appeared asking for a password for a host I haven't accessed in years.

Here's the seemingly relevant part of the stacktace:

```
  tramp-completion-file-name-handler(expand-file-name "/login.stud.ntnu.no:" "/home/expez/git/strom/.git/")
  file-directory-p("/login.stud.ntnu.no:")
  company-files--complete("/l")
  company-files(candidates "/l")
```

How can I get back to being able to write `/login` without fear?

**Comment by dgutov** [comment]
Could try try edebug-ging through `company-files--complete`, to see where this completion comes from?

**Comment by expez** [comment]
```elisp
(when (file-directory-p file)
          (push file directories))
```

This triggers it.  Specifically when `file` is `"login.stud.ntnu.no:"` (notice the trailing :).

**Comment by dgutov** [comment]
No, where does the name come from?

**Comment by expez** [comment]
from `company-files--completion-cache`

**Comment by dgutov** [comment]
You can `(setq company-files--completion-cache nil)` to invalidate it, and then try again.

**Comment by expez** [comment]
That didn't do it for me.  The unwanted entry was recreated by `company-files--directory-files` instead.

**Comment by dgutov** [comment]
Right. Where does the host name come from?

Is there a file in `.git` with that name?

**Comment by expez** [comment]
`(file-name-all-completions "/l" "/")` => `(login.stud.ntnu.no:")`

Called by `company-files--directory-files`

If I do `find-file` and navigate to `/` I get a bunch of completion suggestions for various other hosts too.

**Comment by dgutov** [comment]
Thank you, we should handle that case now.

**Comment by expez** [comment]
Thanks! :+1:
