### ISSUE TITLE
Is there a way to sort completions by usage frequency?

### ISSUE THREAD

**Issue by Malabarba** [company-mode/company-mode#348]
In some situations, I find myself repeatedly picking the 2nd or 3rd option available every time I'm performing a given completion.
Is there a way to have the most frequently completed symbols show up first in the list?

**Comment by dgutov** [comment]
Have you tried https://github.com/company-mode/company-statistics?

**Comment by Malabarba** [comment]
No I haven't! Thanks, I'll give it a try.
