### ISSUE TITLE
add doc for backends

### ISSUE THREAD

**Issue by stardiviner** [company-mode/company-mode#349]
some backends are easy to understand. like `company-yasnippet`, `company-clang` etc.

But I don't understand the `company-template` and `company-tempo`.

Can you add doc in `company-template.el` file, and `company-tempo` (maybe all files)?

**Comment by dgutov** [comment]
`company-template` is not a back-end (I've added a summary line).

`company-tempo` is a backend using the built-in tempo package, like its summary suggests. I don't use either. Feel free to try it out and suggest a better description.
