### ISSUE TITLE
Truncates highlighting of the current line and causes flicker when scrolling

### ISSUE THREAD

**Issue by scottjad** [company-mode/company-mode#353]
When company-mode shows completions it will cause highlighting of the current line (hl-line-mode) to end prematurely at the last character on the current line instead of the highlight extending to the edge of the window as it normally does.

Also, when scrolling the list of completions the highlighting of the current line will flicker (redisplay) on each scroll event.

Auto-complete-mode has neither of these issues.

I'm guessing this is a consequence of how the company popup is displayed and not easily solvable?

**Comment by scottjad** [comment]
The truncating only happens when the popup is displayed below the current line. The flicker happens regardless.

**Comment by scottjad** [comment]
Apparently the flickering only happens on global-hl-line-mode and not on hl-line-mode, and `(setq global-hl-line-sticky-flag t)` resolves the flickering (but at the cost of having a hl-line in inactive windows).

**Comment by dgutov** [comment]
> I'm guessing this is a consequence of how the company popup is displayed and not easily solvable?

It is.

> The flicker happens regardless.

I'm not exactly sure which flickering exactly you're referring to here (the said variable doesn't seem to change anything in that regard), but occasional flickering during redisplay seems to be currently unsolvable in Emacs. See this discussion: http://debbugs.gnu.org/cgi/bugreport.cgi?bug=16621#14

**Comment by scottjad** [comment]
On Sat, May 16 2015,Dmitry Gutov wrote:

> I'm not exactly sure which flickering exactly you're referring to here
> (the said variable doesn't seem to change anything in that regard),

The flickering is just on the hl-line overlay, not company popup. Flash
might be better term since it only redisplays once per scroll of the
company popup.

I think it is because with that sticky flag as nil (nil means the
hl-line overlay appears in just the current buffer) on pre- and
post-command-hook's hl-line unhighlights then rehighlights the current
line. Not sure why each scroll of the company popup would cause a
visible redisplay while the commands C-f along a line (each would invoke
pre- and post-command-hook) wouldn't cause anything visible. Also
auto-complete doesn't cause this flash, so there might be something more
to it.

Btw, I tried to reproduce with `emacs -q` and the first time I didn't
see the flash but every time after that I did (I couldn't figure out if
I loaded company/hl-line/etc slightly differently) so perhaps it won't
reproduce for you.

**Comment by dgutov** [comment]
Ok, I see it now. Thanks for the explanation. It's indeed a flash; the issue of flickering cursor is a separate one.

> Also auto-complete doesn't cause this flash, so there might be something more to it

Indeed. It seems the culprit here was `company-echo-metadata-frontend` (which auto-complete doesn't have a counterpart for). I've pushed an update that seems to take care of it.
