### ISSUE TITLE
company-yasnippet doesn't show candidates

### ISSUE THREAD

**Issue by Distopico** [company-mode/company-mode#354]
Hi, when I write any word that match with yasnippet don't show candidates in emacs 24.5 Gnu/Linux

**Comment by dgutov** [comment]
It's not in `company-backends` by default. Have you added it?

**Comment by Distopico** [comment]
My configuration

```lisp
;; Completion
;; Give a change to company-mode
(require 'company)
(add-hook 'after-init-hook 'global-company-mode)
(setq company-dabbrev-other-buffers t
      company-dabbrev-code-other-buffers t
      company-complete-number t
      company-show-numbers t
      company-minimum-prefix-length 2
      company-dabbrev-downcase nil
      company-dabbrev-ignore-case t
      company-idle-delay 0.2)

(defun add-pcomplete-to-capf ()
  (add-hook 'completion-at-point-functions 'pcomplete-completions-at-point nil t))
(add-hook 'org-mode-hook #'add-pcomplete-to-capf)

;; ;; Backends
(push '(company-semantic :with company-yasnippet) company-backends)

(add-hook 'emacs-lisp-mode-hook
          '(lambda ()
             (set (make-local-variable 'company-backends) (append company-backends '(company-elisp)))))
```

**Comment by dgutov** [comment]
This configuration means that completions will be shown only when `company-semantic` applies. I.e. when `semantic-mode` is on, and the current buffer has completions to offer.

If you simply type `M-x company-complete-common` after a whitespace, what completions do you see?

**Comment by Distopico** [comment]
show 'No completion found' why is the better way to turn on company-yasnippet in all modes?

**Comment by dgutov** [comment]
There's no easy way, unfortunately. You might have to add it to every backend that you anticipate will be used.

**Comment by Distopico** [comment]
ah ok, you show me a example? how add by 'mode'? thanks for you time

**Comment by dgutov** [comment]
There are a few options, none of which I particularly like. Check out these SE questions:

http://emacs.stackexchange.com/questions/10431/get-company-to-show-suggestions-for-yasnippet-names
http://emacs.stackexchange.com/questions/7908/how-to-make-yasnippet-and-company-work-nicer

**Comment by Distopico** [comment]
Thanks
