### ISSUE TITLE
Show python private methods last

### ISSUE THREAD

**Issue by sollidsnake** [company-mode/company-mode#355]
When using company with python, it shows the private methods first:
![agsep](https://cloud.githubusercontent.com/assets/1778350/7748974/e40e6464-ff9f-11e4-80d4-6765e7911a6a.png)

I believe they should be shown last by default, since they're useless if you're using an imported library, which is the most common case.

I'm not sure if this is related to company or the python backends themselves (anaconda or jedi), so please excuse me if I'm in the wrong place.

**Comment by dgutov** [comment]
If you're using a third-party backed, it should be reported to the backend.

But the solution you got in http://emacs.stackexchange.com/questions/12360/how-to-make-private-python-methods-the-last-company-mode-choices is perfectly adequate.

**Comment by sollidsnake** [comment]
Yeah actually it was me who posted that solution :)
I just believe it should be the default. I'll report to the backend then. Thanks

**Comment by sollidsnake** [comment]
Yeah, I just believe it should be the default. I'll report to the backend then. Thanks
