### ISSUE TITLE
Is there a way to prevent show-doc-buffer from scrolling to top?

### ISSUE THREAD

**Issue by cpitclaudel** [company-mode/company-mode#357]
`company-coq` could benefit from such a feature; the documentation of each option or command is part of a large file where boundaries between each command or option are not very clear. Users thus often want to scroll around to see the docs for related options.

Another case where this pops up (another mode that I'm working on) is when I don't have properly indexed documentation; in that case I know that there is going to be a section of the document about the particular keyword that I'm completing, and I can find an approximate location by looking for that keyword, but often the text before also matters. Ideally, I'd like to just be able to center the window around my best guess of what a relevant location in the docs is.

This could probably be implemented just like for the location option, right?

Thanks!

For reference, here's the offending snippet
```elisp
(defun company-show-doc-buffer ()
    ;; ...
    (company--electric-do
        ;; ...
        (with-current-buffer doc-buffer
          (goto-char (point-min)))
        ;; ...
```

**Comment by dgutov** [comment]
> in that case I know that there is going to be a section of the document about the particular keyword that I'm completing, and I can find an approximate location by looking for that keyword, but often the text before also matters

So, there's no way to reliably narrow the buffer around the relevant text? That would be one of the options.

> This could probably be implemented just like for the location option, right?

I guess so. Maybe `doc-buffer` could return a cons `(buffer . line)` that we'll use.

> For reference, here's the offending snippet

Does it work better for you if `(goto-char (point-min))` is commented out?

**Comment by cpitclaudel** [comment]
> So, there's no way to reliably narrow the buffer around the relevant text? That would be one of the options.

That's a good option, but no, not really, I guess what I'm really doing is slightly abusing the help function, which in most cases shows a precise, targeted help string (à la `emacs-lisp-mode` or `elpy`). 
  
> I guess so. Maybe `doc-buffer` could return a cons `(buffer . line)` that we'll use.

That would be great. (Wouldn't you want a point instead of a line, though?)

> Does it work better for you if `(goto-char (point-min))` is commented out?

Yes, removing the `goto-char` part solves the problem entirely.

Here is a small example if you want to experiment with this:

```elisp
(require 'company)

(defun long-doc-buffer (command &optional arg &rest ignored)
  (interactive (list 'interactive))
  (pcase command
    (`interactive (company-begin-backend 'long-doc-buffer))
    (`prefix (company-grab-symbol))
    (`candidates '("AAA"))
    (`doc-buffer (with-current-buffer (get-buffer-create "*company-documentation*")
                   (erase-buffer)
                   (dotimes (i 1000) (insert (format "%d\n" i)))
                   (goto-char (point-max))
                   (current-buffer)))))

;; `M-x long-doc-buffer' here, then `C-h' 
```

**Comment by dgutov** [comment]
Thanks. It seems the window-start value is the most fitting as the extra piece of information.

I've pushed a commit to `doc-window-start` branch, please see if it satisfies your needs.

**Comment by cpitclaudel** [comment]
The `doc-window-start` branch works very nicely, thanks Dmitry!

**Comment by dgutov** [comment]
Great, thanks for checking.

**Comment by cpitclaudel** [comment]
By the way, can you add a note here when you push the next stable release? I'll bump the dependency number in company-coq.

**Comment by dgutov** [comment]
No problem. But that might not happen for some time.
