### ISSUE TITLE
How to let company-dabbrev ignore numbers analysis

### ISSUE THREAD

**Issue by llcc** [company-mode/company-mode#358]
Company dabbrev backends always try to complete when I type numbers, which is really annoying. 
20
20001 -----------1
200111 ----------2

It is really a rare thing for a need of number completion. So can you give a option in company-dabbrev to regexp variable to ignore any completion of number start?

**Comment by dgutov** [comment]
You can filter all-number completions out later:

```el
(push (apply-partially #'cl-remove-if
                       (lambda (c) (string-match-p "\\`[0-9]+\\'" c)))
      company-transformers)
```

**Comment by llcc** [comment]
@dgutov 
Thanks for reply, but it seems do not work well.

**Comment by dgutov** [comment]
How?

**Comment by llcc** [comment]
It still popups the numbers completions.

**Comment by dgutov** [comment]
Have you evaluated the snippet in your Emacs session?

**Comment by llcc** [comment]
Yes, i did.

**Comment by llcc** [comment]
This is my company configuration.
``` lisp
(use-package company
  :ensure t
  :diminish ""
  :config
  (progn
    (add-hook 'org-mode-hook #'global-company-mode)
    (add-hook 'emacs-lisp-mode-hook #'company-mode)
    (bind-key "<tab>" 'company-complete-selection company-active-map)
    (setq-default pos-tip-background-color "khaki1")
    (bind-keys :map company-active-map
	       ("C-n" . company-select-nex)
	       ("C-p" . company-select-previous)
	       ("C-d" . company-show-doc-buffer)
	       ("<tab>" . company-complete))
    (setq company-idle-delay 0
          company-require-match nil
          ;;company-begin-commands '(self-insert-command)
          company-show-numbers t
	  company-tooltip-align-annotations t
	  company-tooltip-flip-when-above t
	  company-tooltip-margin 1
	  company-echo-delay 0
	  company-dabbrev-downcase nil
	  company-minimum-prefix-length 1
	  company-selection-wrap-around t
	  company-transformers '(company-sort-by-occurrence
				 company-sort-by-backend-importance)
	  company-backends '(company-capf
			     (company-dabbrev company-dabbrev-code company-keywords)
			     company-yasnippet))
    (push (apply-partially #'cl-remove-if
                       (lambda (c) (string-match-p "\\`[0-9]+\\'" c)))
      company-transformers)
    (add-to-list 'company-backends 'company-math-symbols-unicode)))
```

**Comment by dgutov** [comment]
Works for me, using most of your snippet.

Would you like to post a screencast, or something?

**Comment by llcc** [comment]
Thanks @dgutov. I screenshot a number completion.
![image](https://cloud.githubusercontent.com/assets/3996879/8021939/0d992416-0cef-11e5-9e22-c4784ca7e5f8.png)

**Comment by dgutov** [comment]
All these completions include a non-digit character. The regexp I posted only matches completions that consist solely of digit characters. So, only those get filtered out.

If that's not enough for you, you can remove either the "beginning of string" anchor from it, or both that and the "end of string" anchor as well.

**Comment by llcc** [comment]
@dgutov I never noticed about that no-digit character. Thanks, problem solved.

**Comment by dgutov** [comment]
You're welcome.

**Comment by cddesja** [comment]
I am having this same issue when dealing with iESS and I'm wondering how I can amend 

```elisp
(push (apply-partially #'cl-remove-if
                       (lambda (c) (string-match-p "\\`[0-9]+\\'" c)))
      company-transformers)
```
based on this suggestion:

> If that's not enough for you, you can remove either the "beginning of string" anchor from it, or both that and the "end of string" anchor as well.

I am finding it frustrating if I type `7 / 8` in iESS that for 8 I get suggestions like 8exifmm, 8??u, and so on. I don't want any suggestions if I start with a number.

Thanks for you help.

**Comment by dgutov** [comment]
The "beginning of string" anchor is ``\\` ``, and the "end of string" anchor is `\\'`. Does that clarify things?

**Comment by dgutov** [comment]
If you want to delete strings that begin with a number, but don't necessarily contain only numbers, then removing `\\'` from the regexp in the snippet should do the trick.
