### ISSUE TITLE
Company seems not to include words with hyphens in the autocompletion.

### ISSUE THREAD

**Issue by ReneFroger** [company-mode/company-mode#360]
### Setup:

GNU Emacs GUI version 24.4.51.1 (x86_64-w64-mingw32) 
[Compiled from Harroogan Emacs.](https://bitbucket.org/Haroogan/emacs-for-windows/)
Company Mode, using the latest version of Company from GitHub
Windows 7 x64 bit.
### Situation:

 Company seems do not include any words with hyphens.  This is bothering, especially with Elisp, where many functions have hyphens. 

For example, type in the scratch buffer `ThisIsAnExampleOfFooBar`
Okay, type `This` afterwards, and you see the same typed word as completion suggestion from Company. 

But what if you have it typed as `this-is-an-example-of-foobar`? If so, afther that, typing `this`, you get no completion suggestion from Company. Which is odd, because the completion suggestion works fine with `this_is_an_example_of_foobar`.

**Comment by dgutov** [comment]
What does `M-x company-diag` say?

**Comment by ReneFroger** [comment]
Output of `M-x company-diag` is saying me the following: 


```
Emacs 24.4.51.1 (x86_64-w64-mingw32) of 2014-11-10 on G75VW
Company 0.9.0-cvs

company-backends: ((company-bbdb :with company-yasnippet)
 (company-nxml :with company-yasnippet)
 (company-css :with company-yasnippet)
 (company-eclim :with company-yasnippet)
 (company-semantic :with company-yasnippet)
 (company-clang :with company-yasnippet)
 (company-xcode :with company-yasnippet)
 (company-cmake :with company-yasnippet)
 (company-capf :with company-yasnippet)
 (company-dabbrev-code company-gtags company-etags company-keywords :with company-yasnippet)
 (company-oddmuse :with company-yasnippet)
 (company-files :with company-yasnippet)
 (company-dabbrev :with company-yasnippet)
 (company-yasnippet :with company-yasnippet))

Used backend: (company-dabbrev :with company-yasnippet)

Prefix: ""
Completions:
  "Corral"
  "EHART"
  "keys"
  "bind"
  "hook"
  "setup"
  "hook"
  "updir"
  "backward"
  "delete"
  "completion"
  "define"
  "mode"
  "Keybindings"
  "keys"
  "bind"
  "defun"
  "2015"
  [.. shortened it here, list was too long..  ]
  "Beheer"
  "this"
  "example"
  "foobar"
  "this"

````

He is not seeing the typed `this-is-an-example-of-foobar`, which is currently in the buffer.

**Comment by dgutov** [comment]
So, does that happen inside a string? That's why `company-dabbrev` might be used, rather than `company-dabbrev-code`.

**Comment by ReneFroger** [comment]
Thanks for your help. No, the word is not inside a string. But I presume you got different - thus the expected - output than me?                                                                                                                                                                                                                Van: Dmitry GutovVerzonden: dinsdag 9 juni 2015 17:34Aan: company-mode/company-modeBeantwoorden: company-mode/company-modeCc: ReneFrogerOnderwerp: Re: [company-mode] Company seems not to include words with hyphens in the autocompletion. (#360)So, does that happen inside a string? That's why company-dabbrev might be used, rather than company-dabbrev-code.

—Reply to this email directly or view it on GitHub.

**Comment by dgutov** [comment]
Different output where? You haven't included example buffer contents.

**Comment by dgutov** [comment]
Ok, sorry. You have a scenario for the `*scratch*` buffer, but it doesn't play out the same way for me: the `company-capf` backend gets used, and it performs Lisp completion.

So, for input `this` I get 3 completions: `this-command`, and so on.

**Comment by ReneFroger** [comment]
That's right, I use the `*scratch*` buffer. 
So I'm wondering why I don't get autocomplete suggestion from company-mode when there is `this-is-an-example-of-foobar` in the buffer, and I type `this`.
On contrary, I get completion in the buffer `this_is_an_example_of_foobar` is mentioned.

It's unclear to me if you are facing the same issue, or it's only me?

**Comment by dgutov** [comment]
Two points:

* `company-dabbrev` is supposed to work this way, and return word completions, not symbols. If you don't like that, set `company-dabbrev-code-everywhere` to t, and it'll be used instead.

* `company-dabbrev-code` is used in modes that satisfy `company-dabbrev-code-modes`. Not sure why the php-mode you're using doesn't fit that. https://github.com/ejmr/php-mode/ derives from `c-mode`, and that, in turn, derives from `prog-mode`. Maybe you need to upgrade to the latest Emacs. Or add a new item to the aforementioned list.

**Comment by zzhjerry** [comment]
For whoever wondering why `company-dabbrev-code` isn't being used even after enabling `company-dabbrev-code-everywhere`, make sure you mode is also listed in `company-dabbrev-code-modes`

That's said, if you want to complete hyphen as part of word in `*scratch*` buffer whose major mode is `fundamental mode`, make sure `fundamental-mode` is listed.

**Comment by dgutov** [comment]
@zzhjerry That is, *if* your `*scratch*` uses `fundamental-mode`. Which it usually doesn't.
