### ISSUE TITLE
how to set company-minimum-prefix-length locally for a backend?

### ISSUE THREAD

**Issue by sewkokot** [company-mode/company-mode#361]
I'm trying to write a simple company-backend for which I would like to change the minimum-prefix-length.
How it can be done? The following does not work. Still the global prefix-length 3 is used.
```
(defun company-vlisp-backend (command &optional arg &rest ignored)
  (interactive (list 'interactive))

  (let  ((company-minimum-prefix-length 1))
	(case command
	  (interactive (company-begin-backend 'company-vlisp-backend))
	  (prefix (and (eq major-mode 'vlisp-mode)
				   (company-grab-symbol)))
	  (candidates
	   (remove-if-not
		(lambda (c) (string-prefix-p arg c))
		vlisp-cmds-list)))))
```

**Comment by dgutov** [comment]
You can't change the minimum prefix length, but you can return a cons in response to the `prefix` command, to say the current prefix is good enough. See the `company-backends` docstring for the format.

**Comment by sewkokot** [comment]
Thank, I have read the company-backends docstring and it seems that the text:

"...Instead of a string, the back-end may return a cons where car is the prefix
and cdr is used instead of the actual prefix length in the comparison
against `company-minimum-prefix-length'..."

can still be misleading for me as a non native speaker ;) I see it has already been discussed here
https://github.com/company-mode/company-mode/issues/319

**Comment by dgutov** [comment]
Misleading how? The quoted text is the result of the aforementioned discussion.

**Comment by sewkokot** [comment]
In my opinion, the part: 
'cdr is used instead of the actual prefix length in the comparison against `company-minimum-prefix-length' 
can be misleading because it may be concluded that 'cdr is compared against `company-minimum-prefix-length' which does not make sense. The usage case is that one wants to temporarly overrides the value set in `company-minimum-prefix-length' and the above text says about unnecessarly about comparison or test which is done in the code but the user does not need this detail here.
Why not make it simpler for example:
'cdr overrides temporarly the integer set in `company-minimum-prefix-length' 
I would welcome other users' opinion.

**Comment by dgutov** [comment]
> it may be concluded that 'cdr is compared againstcompany-minimum-prefix-length' which does not make sense

That is exactly the case. See the other discussion for the reasoning behind it.

**Comment by sewkokot** [comment]
Then I'm lost. So how to do the following: company-minimum-prefix-length is 3. I write a backend where I want to start automatic completion exeptionally after say 2 characters (prefix length 2?),
This is the code of may backend:
```
(defun vlisp-prefix ()
  (interactive)
  (and (eq major-mode 'vlisp-mode)
	   (company-grab-symbol-cons "" 2)))

(defun company-vlisp (command &optional arg &rest ignored)
  (interactive (list 'interactive))

  (cl-case command
	(interactive (company-begin-backend 'company-vlisp))
	(prefix (vlisp-prefix))
	(candidates
	 (remove-if-not
	  (lambda (c) (string-prefix-p arg c))
	  vlisp-cmds-list))))

(add-to-list 'company-backends 'company-vlisp)
```
Where should I put the value of 2, because my code does not work. It autocompletes after 1 character.

**Comment by sewkokot** [comment]
Finally I figured out how to do it
```
(setq vlisp-company-prefix-length 2)

(defun vlisp-prefix ()
  (interactive)
  (let ((prefix (company-grab-symbol)))
	(and (eq major-mode 'vlisp-mode)
		 (cons prefix (>= (length prefix)
						  vlisp-company-prefix-length)))))
```
Is there a better/simple way to do it?

**Comment by dgutov** [comment]
> Is there a better/simple way to do it?

Probably not.

> Still it is unclear how the number in 'cdr is interpreted or what is the usage case.

The use case is described here: https://github.com/company-mode/company-mode/issues/319#issuecomment-82380744
