### ISSUE TITLE
Pseudo-tooltip-frontend moving point when near eol

### ISSUE THREAD

**Issue by sooheon** [company-mode/company-mode#362]
Using `company-pseudo-tooltip-frontend` in an org buffer with `org-indent-mode` on, any time completion candidates pop up at or near end of line, the cursor's position on screen jumps irregularly. At its least annoying it will simply move the cursor position on screen (scrolling the buffer), at worst it will move the cursor to a different place in the file itself while I'm typing.

**Comment by dgutov** [comment]
Does it happen consistently? How does that look? Can you make a screencast, and/or describe the necessary steps?

**Comment by sooheon** [comment]
Here's a gif of the problem in action. I've actually disabled `org-indent-mode`, so `visual-line-mode` is actually the most likely suspect.

![company](https://cloud.githubusercontent.com/assets/302945/8113084/c8612db0-10a6-11e5-88db-2306a0bdd17c.gif)

Without visual line mode, the screen still jumps unnecessarily (it's not as if the tooltip needs space to display), but there isn't the more egregious cursor jump. 
![company2](https://cloud.githubusercontent.com/assets/302945/8113124/073b0074-10a7-11e5-8033-d3fc46c64ef3.gif)

**Comment by dgutov** [comment]
Thanks, I get the idea now, but I was still unable to reproduce this: "at worst it will move the cursor to a different place in the file itself while I'm typing".

Could you provide a step-by-step scenario to reproduce it, starting with `emacs -Q`?

And speaking of the smaller jumps, there doesn't seem to be any simple fix. If the preview is displayed inline, I guess the display engine will do the scrolling, to keep it in view.

**Comment by sooheon** [comment]
1. `brew install emacs --devel --with-cocoa`
2. `/usr/local/Cellar/emacs/24.5-dev/Emacs.app/Contents/MacOS/Emacs -Q` (bug only in gui emacs)
3. paste following into scratch buffer: https://gist.github.com/sooheon/97a62f433897b52da3d1#file-gistfile1-txt
4. eval the `load-files` (or equivalent) and `setq`
5. at the end of L11 locate string of hellos, there should be a trailing `h`. 
6. type `el`, pause for candidates to pop up, immediately type `l` and begin <backspacing>

![company3](https://cloud.githubusercontent.com/assets/302945/8123869/002f3a92-110c-11e5-98d5-f708da40d2c9.gif)

**Comment by fniessen** [comment]
FYI, I get the exact same type of problem in a .java file (that is, without org stuff, nor `visual-line-mode`).

I do have `indent-guide` and `fci-mode` disabled for the test.

My full (shared) config file is visible on https://github.com/fniessen/emacs-leuven.

**Comment by fniessen** [comment]
Side question -- How do you make those nice animated GIF?

**Comment by sooheon** [comment]
Yeah I guess its not limited to org-mode or visual-line-mode, though I havent been able to reproduce the point moving (only the buffer scrolling) without at least visual-line-mode. I made the gifs with licecap, just something I googled real quick, there may be better.

**Comment by dgutov** [comment]
@sooheon I haven't managed to reproduce this thus far. Possibly because I don't have access to a MacOS machine.

Step 1: Have you tried this scenario using the NS port instead?
Step 2: Why does the path say "24.5"? The installation command said `--devel`, doesn't than mean a development build? It should be 25-something.
Step 4: "eval the load-files (or equivalent) and setq" -- what?
Step 5: Ideally, this step would mention the window width (the text is laid out differently in my `emacs -Q`), though it's possible to reconstruct using the gif.
Step 6: Continue backspacing until when? What should I see?

**Comment by sooheon** [comment]
> Have you tried this scenario using the NS port instead?

What is NS port? a different port of emacs?

> Why does the path say "24.5"?

Version 25 is under `--HEAD` in homebrew:
```
--devel
	Install development version 24.5-dev
--HEAD
	Install HEAD version
```

> "eval the load-files (or equivalent) and setq" -- what?

Sorry this was unclear. My company-mode files, downloaded by package.el, are under those directories, so I eval'ed them using lines 5-6. Just mean you should do the equivalent and also set company to use the pseudo tooltip.

> window width
I assumed emacs -Q would start with identical window dimensions.

> Continue backspacing until when? 
The requirements are: 
1. you start typing `company-minimum-prefix-length` (3) short of screen width
2. you type the first 3 letters of a word which with completion candidates
3. you let the completion tooltip pop up, type one more letter, and then backspace

Immediately from the first backspace, you should notice that your point has moved, and is not deleting text in another location.

**Comment by dgutov** [comment]
> What is NS port? a different port of emacs?

Actually, it's not. Sorry, I'm not familiar with that stuff too well. The `--with-cocoa` switch installs exactly that port.

> Version 25 is under --HEAD in homebrew:

Ok. But there's no development version of 24.5 anymore (it's been released).

> I assumed emacs -Q would start with identical window dimensions.

Maybe in pixels? I don't know. But our default fonts seem to have different dimensions, hence the different number of columns.

> Immediately from the first backspace, you should notice that your point has moved, and is now deleting text in another location.

Thank you. I can reproduce this now. It's clearly an Emacs bug, so I'll have to file a bug report there.

**Comment by sooheon** [comment]
Ah, it's good that you know better how to escalate the bug report to emacs. Thank you. If you mention this there I'll follow along.

**Comment by dgutov** [comment]
http://debbugs.gnu.org/20847

**Comment by dgutov** [comment]
Hey folks, until we have a fix, this workaround works for me:

```el
(setq bidi-display-reordering nil)
```

**Comment by sooheon** [comment]
Works for me as well, the cursor still appears to move but point functions correctly.

**Comment by dgutov** [comment]
All right, it seems I've found a decent fix. Please report any further problems.

**Comment by fniessen** [comment]
Just to be clearly stated, we don't need anymore to set `bidi-display-reordering`?

**Comment by dgutov** [comment]
We don't.

**Comment by fniessen** [comment]
Thanks for this precising this.

**Comment by dgutov** [comment]
No problem!
