### ISSUE TITLE
web-mode and company-css: Cannot complete

### ISSUE THREAD

**Issue by bassu** [company-mode/company-mode#363]
Trying to enable css property completion on web-mode, yields no fruit. 

```
(add-hook 'web-mode-hook
            (lambda ()
              (set (make-local-variable 'company-backends) '(company-css))))
```
Here's the output of company-diag:
```
Emacs 24.5.1 (x86_64-apple-darwin14.3.0) of 2015-06-16
Company 0.9.0-cvs
company-backends: (company-css)
Used backend: company-css
Prefix: nil
Completions: none
```

**Comment by bassu** [comment]
Okay. I changed `derived-mode to `web-mode` at [L418](https://github.com/company-mode/company-mode/blob/master/company-css.el#L418) and byte-recompiled to fix it.
Isn't there another way to provide completions for other similar ad-hoc modes? Because if you look at it, web-mode is also the primary mode for CSS.

**Comment by dgutov** [comment]
You can pass several arguments (modes) to `derived-mode-p`. To make it more flexible, you can then move the list to a user option.

**Comment by bassu** [comment]
Hmm. Would you please mind adding `web-mode` into it in `master` cause it's very common these days?

**Comment by dgutov** [comment]
Oh, we're discussing `company-css`. Okay.

Is there something else I can check, aside from being in `web-mode`? I'm guessing you don't really need CSS completions outside of CSS blocks.

**Comment by bassu** [comment]
Yes sir!! When `web-mode` is enabled, it sets `web-mode-language-at-pos` to either `"css"` or `"html"` string. So, should check for `"css"`.

**Comment by bassu** [comment]
Also, I should have said "set to return", rather than "sets". Oops.

**Comment by dgutov** [comment]
All right, this should do it.

**Comment by bassu** [comment]
@dgutov Thanks. It works!
