### ISSUE TITLE
company-keywords read from major-mode?

### ISSUE THREAD

**Issue by fommil** [company-mode/company-mode#365]
I was just noticing that the keywords for various languages are hard-coded here

https://github.com/company-mode/company-mode/blob/master/company-keywords.el

but often the major mode already provides the list of keywords. Would it be possible to simply slurp the list from the mode?

In particular, I'd like to get `scala-mode` support automatically https://github.com/hvesalai/scala-mode2/blob/master/scala-mode2-syntax.el

**Comment by dgutov** [comment]
Maybe. How will this "simply" work exactly?

**Comment by fommil** [comment]
yeah, I was trying to find a common variable like `major-mode-keywords` but no such thing seems to exist. It would just be too simple if a `(valid-major-mode-keywords-at-point)` existed, right :smile:

I'll cross reference this to `scala-mode` and maybe the author will have some ideas.

**Comment by hvesalai** [comment]
Yeah, I don't think there is any standard way of doing this. The only "standard" emacs way to configure per buffer is to have a mode hook that the mode executes and that the user can then wire up to do the things he needs. In this case the mode hook could alter the effective keywords list.

**Comment by dgutov** [comment]
@hvesalai Yup. Or, if there are other packages interested in this list being available, we could standardize on a global variable. Maybe start that in the Emacs core, though.

**Comment by fommil** [comment]
one for the wishlist?
