### ISSUE TITLE
keywords for scala-mode

### ISSUE THREAD

**Issue by fommil** [company-mode/company-mode#367]
@hvesalai you wouldn't happen to have a definitive list would you?

**Comment by hvesalai** [comment]
The most complete list of keywords can be ofcourse found from the scala language specification http://www.scala-lang.org/files/archive/spec/2.11/01-lexical-syntax.html

```
abstract    case        catch       class       def
do          else        extends     false       final
finally     for         forSome     if          implicit
import      lazy        match       new         null
object      override    package     private     protected
return      sealed      super       this        throw
trait       try         true        type        val
var         while       with        yield
_    :    =    =>    <-    <:    <%     >:    #    @
```

**Comment by fommil** [comment]
awesome. I guess we can drop the funky characters and add the others to the completion list.

**Comment by dgutov** [comment]
2-3 character keywords are actually useful in certain contexts, so I just used the whole list, aside from the non-character keywords.

Thanks.

**Comment by fommil** [comment]
Thanks!
