### ISSUE TITLE
error in process sentinel: Args out of range: #<buffer *clang-output*>, 0, 1

### ISSUE THREAD

**Issue by zosy** [company-mode/company-mode#368]
.emacs 
emacs version: 3.14.5
os: debian 8.1 amd64
company-mode version 0.8.12(from elpa )

;;------------company-mode--------------------------------
(add-hook 'after-init-hook 'global-company-mode)
(setq company-idle-delay 0)
(setq company-minimum-prefix-length 3)
(setq company-clang-arguments '(
"-I/usr/include/gtk-3.0"
"-I/usr/include/glib-2.0"
"-I/usr/include/mariadb"
))
;----------------------------------------------------------------

my code  test.c:(include stdio.h gtk/gtk.h)
#include <stdio.h>
#include <gtk/gtk.h>
int main(int argc,char *argv[])
{
    GtkWidget *window;
    GtkWidget *label
}

errors:
error in process sentinel: company-clang--handle-error: Args out of range: #<buffer *clang-output*>, 0, 1
error in process sentinel: Args out of range: #<buffer *clang-output*>, 0, 1
Auto-saving...
error in process sentinel: company-clang--handle-error: Args out of range: #<buffer *clang-output*>, 0, 1
error in process sentinel: Args out of range: #<buffer *clang-output*>, 0, 1

Debugger entered--Lisp error: (args-out-of-range #<buffer *clang-output*> 0 1)
  buffer-substring-no-properties(1 0)
  (if (re-search-forward pattern nil t) (buffer-substring-no-properties (point-min) (1- (match-beginning 0))) (message "clang failed with error %d:\n%s" res cmd) (buffer-string))
  (let* ((buf (get-buffer-create company-clang--error-buffer-name)) (cmd (concat company-clang-executable " " (mapconcat (quote identity) args " "))) (pattern (format company-clang--completion-pattern "")) (err (if (re-search-forward pattern nil t) (buffer-substring-no-properties (point-min) (1- (match-beginning 0))) (message "clang failed with error %d:\n%s" res cmd) (buffer-string)))) (save-current-buffer (set-buffer buf) (let ((inhibit-read-only t)) (erase-buffer) (insert (current-time-string) (format "\nclang failed with error %d:\n" res) cmd "\n\n") (insert err) (setq buffer-read-only t) (goto-char (point-min)))))
  company-clang--handle-error(1 ("-fsyntax-only" "-Xclang" "-code-completion-macros" "-x" "c" "-I/usr/include/gtk-3.0" "-I/usr/include/glib-2.0" "-I/usr/include/mariadb" "-Xclang" "-code-completion-at=-:6:16" "-"))
  (if (eq 0 res) nil (company-clang--handle-error res args))
  (save-current-buffer (set-buffer buf) (if (eq 0 res) nil (company-clang--handle-error res args)) (company-clang--parse-output prefix objc))
  (let ((res (process-exit-status proc))) (save-current-buffer (set-buffer buf) (if (eq 0 res) nil (company-clang--handle-error res args)) (company-clang--parse-output prefix objc)))
  (funcall callback (let ((res (process-exit-status proc))) (save-current-buffer (set-buffer buf) (if (eq 0 res) nil (company-clang--handle-error res args)) (company-clang--parse-output prefix objc))))
  (if (string-match-p "hangup" status) nil (funcall callback (let ((res (process-exit-status proc))) (save-current-buffer (set-buffer buf) (if (eq 0 res) nil (company-clang--handle-error res args)) (company-clang--parse-output prefix objc)))))
  (closure ((process . #<process company-clang>) (buf . #<buffer *clang-output*>) (objc) (args "-fsyntax-only" "-Xclang" "-code-completion-macros" "-x" "c" "-I/usr/include/gtk-3.0" "-I/usr/include/glib-2.0" "-I/usr/include/mariadb" "-Xclang" "-code-completion-at=-:6:16" "-") (callback closure ((backend . company-clang) (pt . 112) (tick . 345) (win . #<window 3 on t.c>) (buf . #<buffer t.c>) (res . done) (c :async closure ((ignored) (arg . #("win" 0 3 ...)) (command . candidates) t) (cb) (company-clang--candidates arg cb)) (prefix . #("win" 0 3 (fontified t))) t) (candidates) (if (not (and candidates (eq res (quote done)))) (setq res candidates) (setq company-backend backend company-candidates-cache (list (cons prefix (company--preprocess-candidates candidates)))) (company-idle-begin buf win tick pt))) (prefix . #("win" 0 3 (fontified t))) t) (proc status) (if (string-match-p "hangup" status) nil (funcall callback (let ((res (process-exit-status proc))) (save-current-buffer (set-buffer buf) (if (eq 0 res) nil (company-clang--handle-error res args)) (company-clang--parse-output prefix objc))))))(#<process company-clang> "exited abnormally with code 1\n")

**Comment by dgutov** [comment]
Thank you for the report, should be fixed in master.

It won't get to GNU ELPA for a while, though, so you might have to install from MELPA to get it now.

**Comment by zosy** [comment]
thank you very much,it's works fine now. thanks again:)
