### ISSUE TITLE
wrap long completion candidates

### ISSUE THREAD

**Issue by TheJJ** [company-mode/company-mode#369]
sometimes, my function signatures are very long (template parameters, arguments). This messes up the completion popup, as it tries doing linewraps. better would be abbreviating the candidate to a "maximum length" and maybe enable horizontal scrolling.

**Comment by dgutov** [comment]
> better would be abbreviating the candidate to a "maximum length"

This is supposed to work already.

What's your Emacs version, Company version, and are you using it in the terminal?

Please post a step-by-step scenario to reproduce this.

**Comment by bassu** [comment]
This seems still like an issue. If window size is smaller in width, the completion tool tip should shrink or wrap itself, specifically when in `company-files`. 

For me, the only workaround seems to maximize the window or go full screen mode. 
On Emacs 24.5.1 and company 0.9.0-cvs.

#### Screenshot 

![screen shot 2015-06-24 at 5 22 30 am](https://cloud.githubusercontent.com/assets/977697/8320240/aa359b98-1a31-11e5-90d5-61a2fc815f32.png)

**Comment by bassu** [comment]
Ah never mind. In above screenshot, the issue only applies to `text-scale-mode`. If something can be done with it, I would be highly appreciative!

Otherwise, tooltip wrapping works pretty well, no matter the window size (tested even with 60x25). Good job :beers:

**Comment by dgutov** [comment]
Yeah, we don't properly support it. Since the problem is limited to `text-scale-mode`, let's mark it as duplicate for #299.
