### ISSUE TITLE
whitespace mode support

### ISSUE THREAD

**Issue by TheJJ** [company-mode/company-mode#370]
I reproduced my issue from #369, and it turns out the problem is my whitespace highlighting: My newlines are drawn as `¬`, which is not counted as an active line char, so the completion box is exactly one char too wide.

Also, note the `this->¬`, where the cursor at completion time is one char off:

![img](https://cloud.githubusercontent.com/assets/673543/8327101/1ffcbbde-1a66-11e5-9005-e9c9f028c153.png)

So, company needs to support `whitespace-mode` properly, especially newlines are the problem.

**Comment by dgutov** [comment]
Step-by-step scenario, please.

**Comment by TheJJ** [comment]
Uh, i have [whitespace mode](http://emacswiki.org/emacs/WhiteSpace), and `\n` gets displayed as `¬` for me. This char is drawn and takes one char-width of space, but is not counted in the line-length.

I have emacs 24.5, company 20150622.1706.

When the completion after typing `this->` starts, you can see in the screenshot, that the cursor is placed after the trailing `¬`, which is one char too far on the right.

The functions signatures are too long to fit, so the completion popup tries to take the whole buffer space, but, each line gets appended by `¬` to show the newline, so the popup gets wrapped because of this additional char.

Possible solutions:
* Take the highlighting-chars into account when calculating the popup width.
* Somehow disable the whitespace highlighting for all the popup drawing.

**Comment by dgutov** [comment]
Ok, thanks. Simply enabling `whitespace-mode` does it, although it uses `$` for newlines by default.

Option one turned out to be easy enough. Should be fixed now.
