### ISSUE TITLE
company-capf signals an error when it can't find any candidates

### ISSUE THREAD

**Issue by stsquad** [company-mode/company-mode#371]
I generally leave debug-on-error on to catch actual errors. However company-capf is spitting out:

    Debugger entered--Lisp error: (error "Company: Back-end company-capf error \"No items suitable for an index found in this buffer\" with args (candidates arm)")
      signal(error ("Company: Back-end company-capf error \"No items suitable for an index found in this buffer\" with args (candidates arm)"))
      error("Company: Back-end %s error \"%s\" with args %s" company-capf "No items suitable for an index found in this buffer" (candidates "arm"))
      #[257 "\302\303	\304!\300$\207" [(candidates "arm") company-backend error "Company: Back-end %s error \"%s\" with args %s" error-message-string] 6 "\n\n(fn ERR)"]((user-error "No items suitable for an index found in this buffer"))
      funcall(#[257 "\302\303	\304!\300$\207" [(candidates "arm") company-backend error "Company: Back-end %s error \"%s\" with args %s" error-message-string] 6 "\n\n(fn ERR)"] (user-error "No items suitable for an index found in this buffer"))
      company-call-backend-raw(candidates "arm")
      company--fetch-candidates("arm")
      company-calculate-candidates("arm")
      #[0 "\n\203	\nC\202\n\211\205\233\211@\3009\204\306!\203<9\2036\307N\310=\2046\307N?\205@\311!\205@\312!\202@\313\312\"\240\210\300\242\203\224\314\300\242!\203\216\315\300\242!\211\301\316\f!\240\210\301\242:\204w
    \203i\317\320!\210\301\242\310=\203\216\321\322!\210\202\216
    \203\300\242\323\301\242!\210\324\325\326 \"\210\327\330!\210\331\332\301\242\"\210A\266\202\202\n\207" [("arm") (nil) company-backend company-backends company-prefix company--manual-action functionp company-init t company-init-backend prefix company--multi-backend-adapter company--good-prefix-p company--prefix-str company-calculate-candidates message "No completion found" company-cancel unique company-update-candidates run-hook-with-args company-completion-started-hook company-explicit-action-p company-call-frontends show throw --cl-block-nil-- company--manual-prefix] 6 "\n\n(fn)"]()
          funcall(#[0 "\n\203	\nC\202\n\211\205\233\211@\3009\204\306!\203<9\2036\307N\310=\2046\307N?\205@\311!\205@\312!\202@\313\312\"\240\210\300\242\203\224\314\300\242!\203\216\315\300\242!\211\301\316\f!\240\210\301\242:\204w
    \203i\317\320!\210\301\242\310=\203\216\321\322!\210\202\216
    \203\300\242\323\301\242!\210\324\325\326 \"\210\327\330!\210\331\332\301\242\"\210A\266\202\202\n\207" [("arm") (nil) company-backend company-backends company-prefix company--manual-action functionp company-init t company-init-backend prefix company--multi-backend-adapter company--good-prefix-p company--prefix-str company-calculate-candidates message "No completion found" company-cancel unique company-update-candidates run-hook-with-args company-completion-started-hook company-explicit-action-p company-call-frontends show throw --cl-block-nil-- company--manual-prefix] 6 "\n\n(fn)"])
      company--begin-new()
      company--perform()
      #[0 "\301 \210\207" [company-candidates company--perform] 1 "\n\n(fn)"]()
      funcall(#[0 "\301 \210\207" [company-candidates company--perform] 1 "\n\n(fn)"])
      company-auto-begin()
      company-idle-begin(#<buffer kbuild.sh> #<window 1349 on kbuild.sh> 3200 732)
      apply(company-idle-begin (#<buffer kbuild.sh> #<window 1349 on kbuild.sh> 3200 732))
      byte-code("r\301\302H\303H\"\210)\301\207" [timer apply 5 6] 4)
      timer-event-handler([t 21899 53208 159452 nil company-idle-begin (#<buffer kbuild.sh> #<window 1349 on kbuild.sh> 3200 732) nil 918000])

When editing a shell script. This seems a little excessive as no candidates isn't an error case just something that should fail gracefully and quietly.

**Comment by dgutov** [comment]
Does `C-M-i` signal an error as well?

**Comment by stsquad** [comment]
Nope, you get a "user-error: No items suitable for an index found in this buffer" in your minibuffer echo/*Messages* though.

**Comment by dgutov** [comment]
That's pretty much the same. Please `M-x report-emacs-bug`, preferably after checking that the problem is still there in Emacs master.

**Comment by dgutov** [comment]
If the current completion function comes from the core, of course.

**Comment by stsquad** [comment]
It's not the same as it doesn't trigger an error signal (so no backtrace occurs when debug-on-error is enabled).

**Comment by dgutov** [comment]
It is the same, as far as `completion-at-point-functions` API is concerned.
