### ISSUE TITLE
face spacing of popup does not match the background

### ISSUE THREAD

**Issue by fommil** [company-mode/company-mode#372]
I might create some screengrabs for you to explain this one, unless you understand from the description.

Basically the line spacing between company-mode suggestions is slightly larger (by a couple of pixels) than my typical text lines. This means that the the text in my buffer, on the same line as where a suggestion appears, are resized.

The result is that when receiving suggestions, the buffer flickers a lot, which is quite distracting.

**Comment by dgutov** [comment]
I wouldn't mind a screenshot, but a how-to-reproduce scenario is more important.

**Comment by fommil** [comment]
I'm in `scala-mode` here with https://github.com/fommil/dotfiles/blob/master/.emacs.d/init.el#L489

```
  (set (make-local-variable 'company-backends)
                 '(ensime-company (company-keywords company-etags)))
```

here the `company-etags` is being used.

When I start typing, the text behind (i.e. the body of the `def filesChanging`) is expanding when completions appear and then returns to normal after a selection is accepted (not shown).

![before](https://cloud.githubusercontent.com/assets/1914041/8354811/e9ff7f16-1b42-11e5-8fad-d68e0ee2a222.png)

![after](https://cloud.githubusercontent.com/assets/1914041/8354812/ee9f786e-1b42-11e5-9fce-d11c9f7864df.png)

**Comment by fommil** [comment]
Also, this is the theme I'm using (jumping to the `company-mode` bits) https://github.com/fommil/darcula-theme-emacs/blob/master/darcula-theme.el#L139

**Comment by fommil** [comment]
oh bloody hell, never mind, I'm an idiot. My tooltips are using variable pitch.

**Comment by dgutov** [comment]
Cool. :)

It doesn't look like variable pitch, though. Maybe simply different font face or height?

**Comment by fommil** [comment]
yeah, my variable pitch font is also monospace, it's just a different size. Actually, all of `company-mode` now feels snappier.
