### ISSUE TITLE
Make `company-complete` work with keyboard macros

### ISSUE THREAD

**Issue by egarrulo** [company-mode/company-mode#374]
Right now, when `company-complete` inserts text during the recording of a keyboard macro, such text will not be inserted when running the macro.

Thanks for your attention.

**Comment by dgutov** [comment]
Steps to reproduce?

Works for me.

**Comment by egarrulo** [comment]
With Emacs 24.5:

- emacs -Q
- evaluate this code:

        (add-to-list 'load-path "~/site-lisp/company-mode/company-mode-0.8.12/")
        (require 'company)
        (company-mode)
        (define-key company-active-map (kbd "TAB")       #'company-complete)
        (define-key company-active-map (kbd "<tab>")     #'company-complete)

- F3
- type "read-"
- TAB
- TAB
- Company expands to "read--expression"
- F4
- F4
- Emacs inserts "read-" in the buffer

**Comment by dgutov** [comment]
Ok, I see that now, thanks.

But how would you propose this to be implemented? During interactive editing, you're relying on the popup appearing after the idle timeout, after you type `read-`. Yet when the macro is replayed, naturally it doesn't wait, completion is not initiated, there is no popup.

For the macro to work, try:

```
(global-set-key (kbd "C-c c") #'company-complete)
```

* F3
* type `re` (the prefix is short, completion does not start automatically)
* C-c c (to trigger completion manually)
* type `-b-f` (expansion to `read-buffer-function`), then TAB TAB
* F4

**Comment by egarrulo** [comment]
> For the macro to work, try:

Here it doesn't work: F4 inserts "re-b-f" (by the way, here "re-b-f" expands to "read-buffer-file-coding-system").

> But how would you propose this to be implemented?

What about an implementation of `company-complete` that pushes into the macro whatever expansion was performed? Of course, the user would want the same expansion later, and therefore running `company-complete` again might not work because its backends could choose a different completion in a different context. I don't know Emacs Lisp well enough to know whether this could be done.

**Comment by dgutov** [comment]
> Here it doesn't work

Did you omit the `TAB` binding in `company-active-map`? It's still needed.

> What about an implementation of company-complete that pushes into the macro whatever expansion was performed?

How and why would it do that? company-complete doesn't know anything about macros. Nor do I, to be honest.

**Comment by egarrulo** [comment]
> Did you omit the TAB binding in company-active-map? It's still needed.

I tried both with my custom bindings for TAB, and with only your custom binding for `C-c c`. Either way, it didn't affect the macro.  Are we sure that we are running the same version of Emacs?  Again, mine is 24.5.

> How and why would it do that?

I know Emacs Lisp much less than you, therefore I am even less qualified than you to say anything about "how", but about "why"... Because after having recorded a macro, an user would expect that anything that she has done, would be repeated by the macro, but this won't happen for completions by Company. It is a matter of usability. Instead, if she runs `company-complete` by accident -- and this is likely to happen, since she is used to rely on Company -- she must take care of undoing anything that `company-complete` has done, before continuing with the macro. But if such an user-friendly behaviour is tricky to implement, then let's just learn to ignore Company during macros.

**Comment by dgutov** [comment]
> Are we sure that we are running the same version of Emacs? Again, mine is 24.5.

To be honest, I'm using a `master` checkout. Haven't tried it in any release version yet.

**Comment by dgutov** [comment]
Well, it works the same in 24.4, FWIW.

**Comment by egarrulo** [comment]
I have investigated the issue and I infer that this feature cannot be implemented without changing Emacs.  While Company could detect whether a keyboard macro is running (by reading `defining-kbd-macro'), keyboard macro recording seems implemented at the C level, and thus it is inaccessible to Emacs Lisp packages.

**Comment by dgutov** [comment]
Yes, that's my understanding as well. However, if you invoke completion explicitly during the recording of the macro, that should be remembered.

**Comment by egarrulo** [comment]
Well, what if Company reminded users that they must start completion manually during a keyboard macro, if they want predictable behavior?  This could be achieved by providing a custom predicate to query before displaying the automatic completion menu.  Such a predicate could default to `(not defining-kbd-macro)'.  My understanding is that this wouldn't be bullet-proof, because backends could still provide different completions in different places, but it would be an improvement nonetheless.

By the way, your former completion example works now.  I swear that I followed the same steps, last time, and more than once.  WTF?  I will let you know if I manage to reproduce the unexpected behavior.

Thanks for your attention.

**Comment by dgutov** [comment]
> Such a predicate could default to `(not defining-kbd-macro)'.

Good idea, but I've simply added this condition directly. Let me know if there are particular considerations for the predicate to be customizable.

> By the way, your former completion example works now. I swear that I followed the same steps, last time, and more than once. WTF?

No idea. Maybe the `C-c c` binding was shadowed by some keymap, at some point?

**Comment by egarrulo** [comment]
You are a pragmatic guy ;)  Thank you for the fix.  For me, the only downside of not providing a custom predicate could be that users may think that Company is not working while recording a keyboard macro, unless this new behavior is documented somewhere.

> No idea. Maybe the C-c c binding was shadowed by some keymap, at some point?

I have found what was the problem: as I have written before, I was pressing F4 to run the macro right after the F4 that stopped the macro recording. In other words, I was running the macro right after a symbol, and this made `company-complete` fail.  This is an unlikely scenario.  Sorry for not having realized this before.

**Comment by dgutov** [comment]
> unless this new behavior is documented somewhere.

Yeah, but that's just a question of documentation, whether it'll be in the docstring of the custom predicate, or in one of the existing docstrings.

**Comment by egarrulo** [comment]
Case dismissed, then :)  Thanks again for your assistance.
