### ISSUE TITLE
Increase timeout for unit test `company-call-backend-forces-sync`

### ISSUE THREAD

**Issue by phst** [company-mode/company-mode#375]
Currently the unit test `company-call-backend-forces-sync` uses a timeout of 0.1 seconds. When running under continuous integration, this test can occasionally time out depending on machine load etc. I'd suggest to set the timeout much higher, e.g. to one second.

**Comment by dgutov** [comment]
What kind of continuous integration do you have in mind? So far it's run fine on Travis.

**Comment by dunn** [comment]
I see this pretty often on Travis' macOS workers, e.g.:
- https://travis-ci.org/dunn/homebrew-emacs/jobs/236694538#L1527
- https://travis-ci.org/dunn/homebrew-emacs/jobs/236226808#L1504
- https://travis-ci.org/dunn/homebrew-emacs/jobs/237771043#L1512 (bumped to 0.5)

**Comment by dgutov** [comment]
@dunn Did the last one fail anyway?

**Comment by dunn** [comment]
Yes; but bumping to 2 seconds got it passing.

**Comment by dgutov** [comment]
Is it only specific to OS X? The Travis builds routinely pass on Linux.

Do you also see that this value is too low during your own interactive usage?

**Comment by dunn** [comment]
> Is it only specific to OS X?

Yes, I've never seen this on linux.

> Do you also see that this value is too low during your own interactive usage?

I'm not sure; what sort of errors would I see?

**Comment by dgutov** [comment]
For instance, if you try `M-x company-complete` when an asynchronous backend is used (such as `company-clang`), it would take longer than expected, and maybe even timeout.

**Comment by dgutov** [comment]
Which variable's value did you have to increase, by the way? `company-async-timeout` is 2 already.

**Comment by dunn** [comment]
I changed it here
- https://github.com/company-mode/company-mode/blob/master/test/async-tests.el#L35
- https://github.com/company-mode/company-mode/blob/master/test/async-tests.el#L43

> For instance, if you try M-x company-complete when an asynchronous backend is used (such as company-clang), it would take longer than expected, and maybe even timeout.

Gotcha.  I've only noticed stalls with my own https://github.com/dunn/company-emoji, and that's not asynchronous.

**Comment by dgutov** [comment]
Thanks.

I could bump it to 0.5, but having to go as high as 2 is very weird. I'd like some explanation before doing that. Are the macOS workers under much heavier load than the GNU/Linux ones?

**Comment by dunn** [comment]
> Are the macOS workers under much heavier load than the GNU/Linux ones?

I doubt it; my guess is that this is just one of the places where Emacs on macOS has worse performance.
