### ISSUE TITLE
incompatible with darkroom-mode

### ISSUE THREAD

**Issue by fommil** [company-mode/company-mode#376]
Try going into `darkroom-mode` (available on MELPA) to edit an org-mode file or similar. Unfortunately, all the `company-mode` popups appear in random places on the screen instead of where I expect them to be.

Screenshot attached.
![2015-07-09-114245_1918x1078_scrot](https://cloud.githubusercontent.com/assets/1914041/8593450/b2ffb506-262f-11e5-9603-f42f56911eef.png)

**Comment by dgutov** [comment]
That's because it uses text-scale-mode. If you undo the zooming and increase the default face height instead, it should work fine.

See #299 for more information.

**Comment by capitaomorte** [comment]
@fommil, pasting your pm here

> Thank you for darkroom-mode!

> I discovered that it is incompatible with company-mode recently

>   https://github.com/company-mode/company-mode/issues/376

> and the author of company-mode said "That's because it uses
> text-scale-mode. If you undo the zooming and increase the default face
> height instead, it should work fine."

> I was wondering if you'd consider changing darkroom-mode to do as
> suggested, and sidestep the conflict.

I'm not sure this (yet) is a problem with `darkroom-mode`, text-scale-mode` or `company-mode`. 

Regarding the suggestion, I must wonder why it isn't incorporated into `text-scale-mode`, i.e. why it doesn't operate by increasing the default face height. Perhaps the drawbacks preventing it from doing so would possibly also apply to `darkroom-mode` and hinder it in some way.

I have read about 25% of http://debbugs.gnu.org/cgi/bugreport.cgi?bug=18493, it's a bit long and I don't have much time right now.

Perhaps @dgutov could shine some light on the subject.

**Comment by dgutov** [comment]
> I'm not sure this (yet) is a problem with darkroom-mode, text-scale-mode or company-mode.

You can say it's a problem of `company-mode`, because of the way we count columns and rows before rendering the overlay-based popup. Emacs doesn't provide an easy way to account for text-scale-mode there, and Eli argues that that wouldn't make sense. So we'd have to do some tricky arithmetics ourselves.

One could also look at it as a problem of `text-scale-mode`, but fixing it would force all windows to be scaled simultaneously. Right now they are scaled independently, which can be considered a feature.

**Comment by fommil** [comment]
Hmm, I'm not so sure `text-scale-mode` is entirely to blame. I swapped to `writeroom-mode` and `company-mode` renders things very weirdly as I get closer to the right of the screen when I'm using `buffer-face-mode`. It might even just be a `buffer-face-mode` / `company-mode` incompatibility.

**Comment by capitaomorte** [comment]
> One could also look at it as a problem of text-scale-mode, but fixing it would force all windows to be scaled simultaneously. 

This probably means that the same problem applies to `darkroom-mode`: changing the height of the default face would scale it up in all other windows and frames, right? That's a big no-no for my package, I think.

>  So we'd have to do some tricky arithmetics ourselves.

Despite being tricky, would it be possible to also make them correct? Or is there some fundamental problem preventing it?

**Comment by dgutov** [comment]
> Or is there some fundamental problem preventing it?

Nothing fundamental, AFAIK.
