### ISSUE TITLE
Python Completions list opens in new window

### ISSUE THREAD

**Issue by jonathanchu** [company-mode/company-mode#377]
When `company-mode` is enabled, if I start typing a Python function, right after I type "def ", (note the space following the function definition) a new split window opens with the `*Python Completions*` list in it.  Please see the attached screenshot to better describe this:

<img width="1220" alt="screenshot 2015-07-10 17 12 41" src="https://cloud.githubusercontent.com/assets/66164/8629299/0c11c424-2728-11e5-8b1a-4825d0489c00.png">

*Note: disabling `company-mode` fixes this and a Python Completions list does NOT open at all following the steps above.*

If I initiate `company-mode` completion manually with <kbd>m-x</kbd> `company-complete`, the company selection box appears and seems to be working as expected though.  Please see below:

<img width="1220" alt="screenshot 2015-07-10 17 21 18" src="https://cloud.githubusercontent.com/assets/66164/8629342/781990de-2728-11e5-8d44-e233ba30b990.png">

**My question is: is this expected behavior?**  If there are too many possible completions, would `company` force a new window to open with possible completions?  Or could it be another conflicting package?

Thanks!

**Comment by dgutov** [comment]
It's probably a bug in the major mode you're using for Python. Which one it is?

**Comment by jonathanchu** [comment]
It is `python-mode`:

```elisp
(require 'python-mode)
```

<img width="1068" alt="screenshot 2015-07-10 18 02 20" src="https://cloud.githubusercontent.com/assets/66164/8629910/e514e134-272d-11e5-8cfc-853bfcd7a7ab.png">

However, commenting out `(require 'python-mode)` seems to fix this, but I get another error: `Completion needs an inferior Python process running`.  

<img width="1028" alt="screenshot 2015-07-10 18 07 05" src="https://cloud.githubusercontent.com/assets/66164/8629954/837c9c54-272e-11e5-8b75-2f32366308f5.png">

Thanks for the quick reply and your help in debugging this!

**Comment by dgutov** [comment]
> However, commenting out (require 'python-mode) seems to fix this

Apparently, it's this one: https://launchpad.net/python-mode. You might want to file a bug about their completion function misbehaving (it doesn't conform to the `completion-at-point-functions` interface).

> but I get another error: Completion needs an inferior Python process running.

That's http://debbugs.gnu.org/cgi/bugreport.cgi?bug=18067, fixed in Emacs 24.4.

To see completions provided by the built-in `python-mode`, you need to launch the "inferior process" anyway, using `M-x run-python`. Alternatively, you can install a third-party package like `company-anaconda`.

**Comment by jonathanchu** [comment]
Ah!  Cheers for the help and guidance on this!

**Comment by evanrelf** [comment]
@jonathanchu If you don't mind me asking... What color theme are you using in that screenshot? It looks similar to Atom's One Dark theme.

**Comment by jonathanchu** [comment]
@evanrelf it is precisely that, great eye! :)  https://github.com/jonathanchu/atom-one-dark-theme  It's on MELPA, `atom-one-dark-theme`, if you want to give it a whirl.  Cheers! :beers:

**Comment by evanrelf** [comment]
@jonathanchu Thanks! :smile:
