### ISSUE TITLE
company do not complete words from local buffer

### ISSUE THREAD

**Issue by anquegi** [company-mode/company-mode#379]
Hi I have this configuration for ruby development

;; Files with the following extensions should open in ruby-mode
(add-to-list 'auto-mode-alist '("\\.rb$" . ruby-mode))
(add-to-list 'auto-mode-alist '("\\.rake$" . ruby-mode))
(add-to-list 'auto-mode-alist '("Rakefile$" . ruby-mode))
(add-to-list 'auto-mode-alist '("\\.gemspec$" . ruby-mode))
(add-to-list 'auto-mode-alist '("\\.ru$" . ruby-mode))
(add-to-list 'auto-mode-alist '("Gemfile$" . ruby-mode))

(require 'ruby-mode)
(require 'inf-ruby)

;; When folding, take these delimiters into consideration
(add-to-list 'hs-special-modes-alist
             '(ruby-mode
               "\\(class\\|def\\|do\\|if\\)" "\\(end\\)" "#"
               (lambda (arg) (ruby-end-of-block)) nil))

;; RVM support
(require 'rvm)
(rvm-use-default)

;; Cucumber
(require 'feature-mode)
(setq feature-use-rvm t) ;; Tell cucumber to use RVM
(setq feature-cucumber-command "cucumber {options} {feature}")
;; .feature files should open in feature-mode
(add-to-list 'auto-mode-alist '("\.feature$" . feature-mode))

;; Rspec
(require 'rspec-mode)
;; I want rspec instead of rake spec
(setq rspec-use-rake-when-possible nil)
;; Scroll to the first test failure
(setq compilation-scroll-output 'first-error)

;; Projectile mode
(require 'projectile)
(projectile-global-mode)
(setq projectile-completion-system 'grizzl)

;; Prevent emacs from adding the encoding line at the top of the file
(setq ruby-insert-encoding-magic-comment nil)

;; Functions to help with refactoring
(require 'ruby-refactor)
(add-hook 'ruby-mode-hook 'ruby-refactor-mode-launch)
;; Easily toggle ruby's hash syntax
(require 'ruby-hash-syntax)
;; Ruby rdoc helpers mostly
(require 'ruby-additional)
;; Helpers to deal with strings and symbols
(require 'ruby-tools)
;; Support for YARD
(require 'yard-mode)
(add-hook 'ruby-mode-hook 'yard-mode)
;; Support for running rspec tests
(require 'rspec-mode)

;; Turn on eldoc in ruby files to display info about the
;; method or variable at point
(add-hook 'ruby-mode-hook 'eldoc-mode)
;; Switch the compilation buffer mode with C-x C-q (useful
;; when interacting with a debugger)
(add-hook 'after-init-hook 'inf-ruby-switch-setup)

(add-hook 'ruby-mode-hook
          (lambda ()
            (hs-minor-mode 1) ;; Enables folding
            (modify-syntax-entry ?: "."))) ;; Adds ":" to the word definition

;; Start projectile-rails
(add-hook 'projectile-mode-hook 'projectile-rails-on)

;; robe autocompletion
(add-hook 'ruby-mode-hook 'robe-mode)
(global-company-mode t)
;;(push 'company-robe company-backends)
(eval-after-load 'company
  '(progn
     (push 'company-robe company-backends)
     (push 'company-inf-ruby company-backends)))

;;(add-hook 'robe-mode-hook 'ac-robe-setup)
;;(add-hook 'robe-mode-hook
;;          (lambda ()
;;            (add-to-list 'ac-sources 'ac-source-robe)
;;            (setq completion-at-point-functions '(auto-complete))))

(defadvice inf-ruby-console-auto (before activate-rvm-for-robe activate)
  (rvm-activate-corresponding-ruby))

things works well but for example, company completes well the method say_hello...

![captura de pantalla de 2015-07-15 13 23 28](https://cloud.githubusercontent.com/assets/2518346/8697442/4f35d79c-2af5-11e5-9926-7eed7ea3a766.png)

then I can see the methods in inf-ruby

![captura de pantalla de 2015-07-15 13 23 52](https://cloud.githubusercontent.com/assets/2518346/8697460/624831f4-2af5-11e5-999f-7d7b2b521a7d.png)

but when I make robe-start I can see ruby methods but not say_hello..

![captura de pantalla de 2015-07-15 13 24 04](https://cloud.githubusercontent.com/assets/2518346/8697487/a0169c5a-2af5-11e5-9c09-36dc01738bd2.png)

so here the problem after robe-start

![captura de pantalla de 2015-07-15 13 24 23](https://cloud.githubusercontent.com/assets/2518346/8697496/aec4a594-2af5-11e5-846d-d9c666401761.png)

If some body can help me, it will be good, thanks

**Comment by dgutov** [comment]
You're using [robe](https://github.com/dgutov/robe). Read the first part of its README.

In any case, this is not a `company-mode` issue.
