### ISSUE TITLE
Dark themes in terminal

### ISSUE THREAD

**Issue by romankrv** [company-mode/company-mode#380]
Need redesign color in dark themes in terminal. 
It's look like this. See attach
![screen shot 2015-07-22 at 1 01 40 pm](https://cloud.githubusercontent.com/assets/42733/8839775/bf991bf6-30e1-11e5-83c9-c63aa6207f08.png)

**Comment by dgutov** [comment]
I suppose; patches welcome.

But does Emacs even know that it's running in a dark-background terminal? The popup looks much better on a light background.

**Comment by romankrv** [comment]
It's problem on iTerm. It's probably conflict 256 color of the palette of iTerm and company.el color pallete.

**Comment by dgutov** [comment]
> 256 color

Right.

But what I mean is, you might not be able to just change the colors to look better on dark background. What does `frame-background-mode` evaluate to, in the above environment?

**Comment by romankrv** [comment]
Can you get me more detail or workflow how to deal with the  “frame-background-mode“ 
M-x frame-background-mode not much in my emacs

**Comment by dgutov** [comment]
`M-: frame-background-mode RET`

**Comment by romankrv** [comment]
not exist, can give me elisp code for that?

**Comment by dgutov** [comment]
What does not exist? This variable has been in Emacs for years.

What kind of code are you looking for?

**Comment by romankrv** [comment]
I try to find function as you said: frame-background-mode
but it only has - frame-set-background-mode

![screen shot 2015-07-24 at 5 45 32 pm](https://cloud.githubusercontent.com/assets/42733/8877075/3f978996-322c-11e5-8b85-29d737243d2c.png)

How to get frame-background-mode ?
Thanks

**Comment by Silex** [comment]
It's a variable.

**Comment by romankrv** [comment]
Yes, you are right, it exist. 
This variable has value 'nil' I checked it in iTerm(256 color app) and Term.app (16 color app) and both of them are equal 'nul'
That is it variable not use in.

Tell me please, Is your project (company-mode) not ready to work with 256 color palette?

Let's start to plan to change it. You agree? Because you are more the expert in your project then I. 

Thanks.

**Comment by dgutov** [comment]
@romankrv Does anything change, visually, if you customize that variable to `dark`?

**Comment by romankrv** [comment]
okay, I try it 
and report then

**Comment by ned2** [comment]
Leaving a comment here for those like me coming from a Google search for this problem. For me, the solution was changing my `TERM` environment variable from one that does not have full 256 bit color support (in my case it was set to `screen`) to one that does, like `xterm-256color` or `screen-256color` if using screen.

**Comment by dgutov** [comment]
@ned2 Thanks!

**Comment by ycz0926** [comment]
for someone find the answer, may you can try to add these code below:
```elisp
(custom-set-faces
 '(company-preview
   ((t (:foreground "darkgray" :underline t))))
 '(company-preview-common
   ((t (:inherit company-preview))))
 '(company-tooltip
   ((t (:background "lightgray" :foreground "black"))))
 '(company-tooltip-selection
   ((t (:background "steelblue" :foreground "white"))))
 '(company-tooltip-common
   ((((type x)) (:inherit company-tooltip :weight bold))
    (t (:inherit company-tooltip))))
 '(company-tooltip-common-selection
   ((((type x)) (:inherit company-tooltip-selection :weight bold))
    (t (:inherit company-tooltip-selection)))))
```

link is here: [https://github.com/nsf/gocode/tree/master/emacs-company](https://github.com/nsf/gocode/tree/master/emacs-company)
