### ISSUE TITLE
Help mostly not available in Clojure buffer

### ISSUE THREAD

**Issue by asampal** [company-mode/company-mode#381]
I'm seeing strange behavior from company, in Clojure buffers. First I should mention that completion (and the popup with candidates) is happening as expected, both in my `*cider-repl*` buffer and in the Clojure buffer.

The problem has to do with help; in the `*cider-repl*` buffer help is available for all candidates while in the Clojure buffer I can only get help for the prefix 'def'. Just to be clear, all the candidates are there (along with the annotations, but C-h shows 'No documentation available' for any other prefixes.

cider 20150722.216, cider-nrepl 0.10.0-SNAPSHOT, nREPL 0.2.10, clojure 1.7.0 on Windows 8.1 64 bit, Emacs 24.5.1.

**Comment by dgutov** [comment]
Are you sure it's not a CIDER bug?

**Comment by asampal** [comment]
No, I'm not - I'm just going down the chain :-) First I assumed it was an issue with company-quickhelp. @expez said it wasn't there and that he simply asks company for the documentation. So, I went to the next in line. Are you saying that this can't be a problem with company and that it must be a Cider issue?

**Comment by dgutov** [comment]
It very unlikely to be. Try it in emacs-lisp-mode buffer, for example.

**Comment by asampal** [comment]
Help works there - that points to Cider, unless the way company works in an Elisp buffer is somehow different than the way it works in a Clojure buffer.

**Comment by dgutov** [comment]
Let me know if CIDER points back here.
