### ISSUE TITLE
Slow input after typing use-package, because he is retrieving the contents of package archives. How to disable it?

### ISSUE THREAD

**Issue by ReneFroger** [company-mode/company-mode#387]
## Setup:
GNU Emacs GUI version 24.4.51.1 (x86_64-w64-mingw32) 
[Compiled from Harroogan Emacs.](https://bitbucket.org/Haroogan/emacs-for-windows/)
Company-mode, using the latest version of company-mode from MELPA
Windows 7 x64 bit.

## Situation:
Thanks for all the work with the Company mode! However, I have a issue. 

`[]` stands for the cursor. 

I notice when I'm typing `(use-package []` the input gets really slow. I notice in the minbuffer he is connecting to package archives like MELPA, ORG and GNU to get the contents. I need to wait around 15 seconds, before I can enter any character then wait 15 seconds again. 

Is there any way to disable that?

**Comment by dgutov** [comment]
Maybe ask at `use-package` issue tracker?

I can't think of any completion backend that would do something like that.

**Comment by kovrik** [comment]
Having the same issue.

When you have '(use-package ' form and start typing package name - it is trying to connect to all repos and fetch metadata (or something) and it becomes unbearably slow.

Disabling company-mode solves this issue.

**Comment by kovrik** [comment]
This is happening because of `company-capf` backend.

It looks like it is evaluating s-expr which it is trying to autocomplete, hence in case of use-package it triggers connection to all repos and fetching all metadata.

**Comment by kovrik** [comment]
This function appears to be the root cause (company-capf.el:44-54):
``` emacs
(defun company--capf-data-real ()
  (cl-letf* (((default-value 'completion-at-point-functions)
              ;; Ignore tags-completion-at-point-function because it subverts
              ;; company-etags in the default value of company-backends, where
              ;; the latter comes later.
              (remove 'tags-completion-at-point-function
                      (default-value 'completion-at-point-functions)))
             (data (run-hook-wrapped 'completion-at-point-functions
                                     ;; Ignore misbehaving functions.
                                     #'completion--capf-wrapper 'optimist)))
    (when (and (consp (cdr data)) (numberp (nth 1 data))) data)))
```
This happens when it is trying to evaluate `data`:
``` emacs
    (data (run-hook-wrapped 'completion-at-point-functions
                                     ;; Ignore misbehaving functions.
                                     #'completion--capf-wrapper 'optimist))
```

**Comment by dgutov** [comment]
> It looks like it is evaluating s-expr which it is trying to autocomplete, hence in case of use-package it triggers connection to all repos and fetching all metadata.

`company-capf` just delegates to `elisp-completion-at-point`, which performs macro expansion, to find the right completions.

It seems the key is here ("This happens at macro expansion time"): https://github.com/jwiegley/use-package/blob/master/use-package.el#L464-L472

Could you file a bug against `use-package`?

**Comment by kovrik** [comment]
@ReneFroger 
As a temporary fix: `(setq use-package-always-ensure nil)`

**Comment by ReneFroger** [comment]
@kovrik thanks, that solved my issue! Much appreciated!

However, the `use-package-always-ensure` checks if there is any missing package and then installs them. I found it confusing it's associated with company backend, which makes the input unbearable slow.

**Comment by kovrik** [comment]
@ReneFroger 
Yeah, I know, I use `use-package-always-ensure t` too, but as a temporary fix I set it to `nil` to get rid of this issue.
I'll wait what `use-package` guys will say :)

**Comment by dgutov** [comment]
> I found it confusing it's associated with company backend

There's no company backend associated with it. Like I said, the problem is doing too much during macro-expansion.

**Comment by npostavs** [comment]
> the problem is doing too much during macro-expansion.

There was some discussion about changing this in jwiegley/use-package#190, but it never reached a definitive conclusion.

**Comment by kovrik** [comment]
Any ideas on how to solve it?

**Comment by dgutov** [comment]
> Any ideas on how to solve it?

Conceptually, I would move the "ensure" code to the runtime phase (don't call it from the macro, expand the macro into the code that calls it). But John doesn't seem interested in working on that, so someone else would have to make that patch, probably.

I haven't migrated to `use-package` myself yet, so that person won't be me anytime soon.

**Comment by kovrik** [comment]
Created a pull request to fix this issue (see above).

**Comment by dgutov** [comment]
This has apparently been fixed.
