### ISSUE TITLE
First line in the popup is way off.

### ISSUE THREAD

**Issue by dxtr** [company-mode/company-mode#389]
Hi!
As the title says; the first line is a long way to the right. I had browsed around to see if I could find this issue already posted, but I can't find anything that I feel is related (I'm not using text scaling).

Here's an example in iTerm2:
![screen shot 2015-08-11 at 16 24 08](https://cloud.githubusercontent.com/assets/204705/9200005/f8b44ad2-4045-11e5-887f-da9382121bf9.png)

And here's an example from the GUI:
![screen shot 2015-08-11 at 16 29 20](https://cloud.githubusercontent.com/assets/204705/9200046/2cd93f20-4046-11e5-8a14-ce346e01db1c.png)

I'm on OSX 10.10.

**Comment by dgutov** [comment]
That's #180.
