### ISSUE TITLE
company-yasnippet don't be greedy

### ISSUE THREAD

**Issue by fommil** [company-mode/company-mode#390]
given that the operation to check if there is a valid yasnippet key available is pretty cheap, it would be really good if the `company-yasnippet` wasn't so greedy. I'm in a situation where I'd like to do this

```elisp
(set (make-local-variable 'company-backends)
                 '((ensime-company company-yasnippet)
                   (company-keywords company-etags company-yasnippet)))
```

but unfortunately that would mean that the second block (used when ENSIME is not available) would never kick in.

**Comment by dgutov** [comment]
Could you use `:with`? Like described in this backend's docstring.

**Comment by fommil** [comment]
hmm, thanks. That sort-of works. I get this error

```
Company: Back-end (ensime-company :with company-yasnippet) error "[yas] `yas-expand-snippet' needs properly setup `yas-minor-mode'" with args (post-completion flatspec)
```

which appears to be just noise. This doesn't happen if `yasnippet-company` is a normal non-`:with` backend.

I'm just now reading up on `:with`

```
The latter is the case for the `prefix' command.  But if the group contains
the keyword `:with', the back-ends after it are ignored for this command.
```

which is interesting. Do you think this is the right way to deal with this, or should the yasnippet just "do the right thing" for `prefix`? It still feels like `yasnippet` should be able to quite easily behave the right way for `prefix` and return `nil` when there are no possible completions for the current prefix.

**Comment by fommil** [comment]
I must admit, `:with` confuses me. I don't really fully understand what "the back-ends after it are ignored for this command". What command, `prefix`? Should that read "the backends after `:with` are not sent a `prefix` query"?

**Comment by dgutov** [comment]
> It still feels like yasnippet should be able to quite easily behave the right way for prefix and return nil when there are no possible completions for the current prefix.

* The `prefix` command is assumed to be fast, for instance, in `company-sort-by-occurrence`. I'm not sure searching through all available snippets is fast enough.

* This wouldn't help if there are, say, a couple applicable snippets, but you still want to see the completion from `company-etags`.

**Comment by dgutov** [comment]
> What command, prefix?

Yes, naturally.

> Should that read "the backends after :with are not sent a prefix query"?

This seems clearer, but the word "query" hasn't been used anywhere so far. Care to suggest a modified wording?

**Comment by fommil** [comment]
there are rarely more than a handful of snippets for a given mode, so I'm pretty sure this would be fast. If somebody has hundreds of snippets for a major mode, then perhaps they might want to look at skipping the call to `prefix`.

I don't know what you mean re: `company-etags`. Do you mean that everything after a `:with` will aggressively include completions for all the backends instead of stopping at the first one to return results?

I'm actually happy enough with `:with`, but the yasnippet warning in the minibuffer is incredibly annoying. Do you know which function is being called here? It isn't possible to do a `C-h k` to find out what `[tab]` is being as and why it is different for `:with company-yasnippet` than just plain `company-yasnippet`

**Comment by fommil** [comment]
I got a stacktrace

```
Debugger entered--Lisp error: (error "[yas] `yas-expand-snippet' needs properly setup `yas-minor-mode'")
  signal(error ("[yas] `yas-expand-snippet' needs properly setup `yas-minor-mode'"))
  error("[yas] `yas-expand-snippet' needs properly setup `yas-minor-mode'")
  yas-expand-snippet("import org.scalatest._\n\nclass `(file-name-sans-extension (buffer-name))` extends FlatSpec with Matchers {\n  \"`(file-name-sans-extension (buffer-name))`\" should \"$1\" in {\n    $0\n  }\n}" 306 314 nil)
  company-yasnippet(post-completion #("flatspec" 0 8 (yas-annotation "flatspec" yas-template [cl-struct-yas--template ...
```

**Comment by dgutov** [comment]
> then perhaps they might want to look at skipping the call to prefix

How would they do that?

> Do you mean that everything after a :with will aggressively include completions for all the backends instead of stopping at the first one to return results?

Not at all. I mean that if `company-yasnippet` is not after `:with`, you won't get completions from `company-etags`. Just the snippet completions, which is normally not what I want.

> but the yasnippet warning in the minibuffer is incredibly annoying. Do you know which function is being called here?

The backtrace say it all, feel free to check out the code, it's just a couple dozen lines.

I've never seen this error, with or without `:with`. Do you actually have `yas-minor-mode` enabled in the buffer in question?

**Comment by dgutov** [comment]
Hmm, it must be enabled, otherwise `(bound-and-true-p yas-minor-mode)` would return nil.

But how do you enable Yasnippet? Does it work for you otherwise, without Company?

**Comment by fommil** [comment]
Yeah it works fine. It also works if I don't use :with and yas is the last backend in the list.

This is when I typed something like flatsTAB and its matching flatspec snippet. I have unbound [tab] in the company bindings so I'm surprised it does *anything*.

**Comment by dgutov** [comment]
Do you get the same problem if you use `company-dabbrev-code` instead of `ensime-company`?

> I have unbound [tab] in the company bindings so I'm surprised it does anything.

You've unbound it in `company-active-map`? Did you unbind `TAB` as well?

**Comment by fommil** [comment]
What's the difference between [tab] and TAB?

**Comment by dgutov** [comment]
http://www.gnu.org/software/emacs/manual/html_node/elisp/Function-Keys.html

In short, we have to map both because Yasnippet does, because Org does. However, unbinding only `[tab]` might work for you, exactly because of that. I just asked for completeness.

Anyway, I haven't been able to reproduce your problem. Could you provide a minimal scenario, starting with zero configuration? Ideally, using only the built-in backends, so I don't have to install and configure ENSIME.

**Comment by fommil** [comment]
ENSIME doesn't require any setup actually, but you'd probably end up downloading lots of the scala universe to be able to get a project up and running (you'd only manually download the JDK and `sbt`, everything else is automatic). But point taken, I'll try to reproduce in a sandbox.

**Comment by fommil** [comment]
this might be an ensime bug, we're rebinding the `[tab]` to our own "complete falling back to indent" behaviour.

**Comment by fommil** [comment]
moving to ensime
