### ISSUE TITLE
Could you support multi-term to auto complete file name?

### ISSUE THREAD

**Issue by yu-yuxuan** [company-mode/company-mode#392]
One example is `cd .emacs.d` . When I use `M-x shel`l and type `cd .e`. It will show `cd .emacs.d`. But when I use multi-term. it didn't appear. Thank you.

**Comment by dgutov** [comment]
It works in `shell` because `shell-completion-vars` adds `comint-completion-at-point` to `completion-at-point-functions`.

For it to work in `term` or `multi-term`, `term-mode` will need to provide its own completion function. You can file that feature request using `M-x report-emacs-bug`.
