### ISSUE TITLE
[feature request] will company support cscope as backend like company-etags, company-gtags ?

### ISSUE THREAD

**Issue by stardiviner** [company-mode/company-mode#395]
As the title,
I checked out the source code of `company-etags.el` and `company-gtags`.
Found they are just some functions. But When I write a backend for `cscope` by referencing them.
I found it's hard for me, I don't know how to use cscope to query tag like gtags, so function `company-gtags--fetch-tags` does nto work for me, and cscope don't have similar options, Also I can't understand how `company-etags.el` work.

So I have to ask here, can you add cscope as backend for company?

**Comment by dgutov** [comment]
> I don't know how to use cscope to query tag like gtags

I don't see that ability either. And web search results (http://stackoverflow.com/questions/934233/cscope-or-ctags-why-choose-one-over-the-other, http://vim.1045645.n5.nabble.com/How-to-autocomplete-when-using-cscope-td1191302.html) suggest that cscope users use tag files for completion.

It seems that gtags may be the best of both worlds.

**Comment by stardiviner** [comment]
After checking out your given out links, I agree on your opinion.
