### ISSUE TITLE
Disable company in eshell when using TRAMP

### ISSUE THREAD

**Issue by PythonNut** [company-mode/company-mode#396]
File completion over TRAMP is often unusably slow. That said, `company` in general is a joy to use in eshell, so I'd really love to have it on by default and turn off only when in a remote directory.

Would this be feasible to implement?

_(Of course, making the completion asynchronous would be awesome too, but I don't know if that's reasonable to implement)_

**Comment by dgutov** [comment]
AFAICS, completion in Eshell is built-in. So this should either be a feature request for Emacs, or you could clear `completion-at-point-functions` in `eshell-mode-hook` if the buffer is remote, in your own config.

We have asynchronous completion, but it's something that the completion function must support. And it'll only help if the completion delays are within reasonable limit.

**Comment by PythonNut** [comment]
> So this should either be a feature request for Emacs, [...]

I'm not sure I follow you. Completion works fine in vanilla Emacs. It's the fact that `company` will try completion without being explicitly invoked, leading to freezes while typing. What Emacs feature am I requesting?

**Comment by dgutov** [comment]
If I understood you right, you asked to disable company entirely, not just idle completion.

Or was it the latter? If so, you're requesting something along the lines of completion functions being able to indicate to completion frameworks that idle completion is inadvisable in the given context.

You can handle this particular case in your init file by setting `company-idle-delay` to nil locally.

**Comment by PythonNut** [comment]
Okay, I've fixed this for myself. I suppose if anyone else runs into this, they can do the same.

**Comment by lafrenierejm** [comment]
@PythonNut Would you mind sharing what your fix was?

**Comment by nickenchev** [comment]
I'm confused about where the issue is with this one. If I disable company mode prior to starting to type in my remote eshell buffer, I get no freezes and all is well. Otherwise I get freezing as its trying to present me with completions. I know company will just present completions, and its the backend that is responsible for the eshell completions that is freezing, but I'm not sure which backend that actually is.

**Comment by dgutov** [comment]
It's a proxy for `completion-at-point-functions`, so you can look inside that hook.
