### ISSUE TITLE
Company mode & Jedi

### ISSUE THREAD

**Issue by MagisDing** [company-mode/company-mode#399]
Asked the question [here](https://github.com/davidhalter/jedi/issues/623#issuecomment-138132983)， I have installed company-jedi, and add
>(defun my/python-mode-hook ()
  (add-to-list 'company-backends 'company-jedi))

(add-hook 'python-mode-hook 'my/python-mode-hook)

to my init configuration. How to "create" the dependency correspondent between company-mode & jedi.

**Comment by syohex** [comment]
Please uninstall `jedi` package and retry.
And please use https://github.com/syohex/emacs-company-jedi/issues for `company-jedi` issues.

**Comment by dgutov** [comment]
Uninstall `jedi`.
