### ISSUE TITLE
Extract dropdown list functionality?

### ISSUE THREAD

**Issue by vspinu** [company-mode/company-mode#400]
There is a [dropdown-list.el](http://www.emacswiki.org/emacs/dropdown-list.el) out there which apparently was heavily inspired by the company code. Some packages (yas for instance) are already using that pacakge. 

Would you consider extracting this functinality and potentially merging with `dropdown-list`? Configuring two alternative backends for the same thing is rather inconvenient. 

Thanks.

**Comment by dgutov** [comment]
I've been reminded of an older issue: #287.

Closing as a duplicate.
