### ISSUE TITLE
company-yasnippet fallback?

### ISSUE THREAD

**Issue by vspinu** [company-mode/company-mode#401]
I would like to use `company` tooltip in  `yas` `yas-prompt-functions`. As per #400 yas relies on dropdown-list and doesn't provision for company's (a much nicer and more mature) dropdown.

The reason for `yas-prompt-function` in favor or `company-yasnipet` is that it offers a fallback mechanism. I can bind `yas-expand` to `M-SPC` which, in case of not candidates, will fall back on the default action. 

Is there a way to achieve such a fall back with company-yasnippet?

Thanks.

cc @capitaomorte

**Comment by dgutov** [comment]
Until the other issue is resolved, you might be able to implement a prompt function using `company-begin-with`.

`company-yasnippet` is unlikely to help here.

**Comment by vspinu** [comment]
> Until the other issue is resolved, you might be able to implement a prompt function using company-begin-with.

I actually just found a very simple and efficient setup of having both worlds:

```
(setq yas-prompt-functions '(yas-no-prompt))
(define-key yas-minor-mode-map (kbd "M-SPC") 'yas-expand)
(global-set-key (kbd "M-Y") 'company-yasnippet)
```

So I am not bothered with yas prompt at all and still have the company bound to a handy key. Perfect AFAIC.

This is more a yas feature request, so feel free to close this. I think #400 is way more important because of the potential use to many other packages besides yas.

**Comment by dgutov** [comment]
Okay. `company-yasnippet` is first and foremost a backend, so I wouldn't tackle special fallback behavior on top of it.

The other issue is indeed more important.
