### ISSUE TITLE
Semantic Breaks Multiple Backends

### ISSUE THREAD

**Issue by bvraghav** [company-mode/company-mode#403]
On a cpp file, if company-semantic works, no other backends feed completion to company

How to reproduce.
1. open `emacs -Q`
2. `M-x package-initialize`
    `M-x global-company-mode`
3. `find-file `
![company-issue-01](https://cloud.githubusercontent.com/assets/14331962/9936088/e3713686-5d77-11e5-8c31-60245f499962.png)
4. type `glfw` inside the buffer. Then `M-x company-complete`
![company-issue-02](https://cloud.githubusercontent.com/assets/14331962/9936181/5bf3ac24-5d78-11e5-933c-89c317658649.png)
WORKS (completes from words inside of the page)
5. type `this->setW` then `M-x company-complete`
![company-issue-03](https://cloud.githubusercontent.com/assets/14331962/9936233/8f67aff6-5d78-11e5-8a31-f61227e264af.png)
WORKS (completes from both gtags and words inside of page
6. `M-x semantic-mode`
    responds with `(Loading semantic/db-file...done)`
7. Repeat step 4
![company-issue-04](https://cloud.githubusercontent.com/assets/14331962/9936312/f33ea1a6-5d78-11e5-8dd1-896a989c8dad.png)
WORKS (completes using company-semantic. The values of completion suggest so)
8. Repeat step 5
    (No completion found)
9. At the same point i.e. `this->setW[*]`  (`[*]` represents cursor/point)
    `M-x company-gtags`
![company-issue-05](https://cloud.githubusercontent.com/assets/14331962/9936398/68acf708-5d79-11e5-89c7-82255ffaaab8.png)
![company-issue-06](https://cloud.githubusercontent.com/assets/14331962/9936401/6ac72a68-5d79-11e5-9993-232558189282.png)
WORKS (both completion and function-args work here)

I am not a seasoned emacs-user. However, this behaviour is of concern. I am presently using a workaround for the company-gtags using [C-tab] mapping. But that does not provide complete functionality. Moreover, there are real issues like local variable completion inside of a function etc. that I have to live with.

Any help shall be appreciated.

For the sake of formality, my dot-emacs has following entry for company setup
```elisp
;; Company Mode
(require 'company)
(setq-default company-idle-delay 0.2
	      company-minimum-prefix-length 3)
(push 'company-elisp company-backends)
(global-set-key [C-tab] 'company-gtags)
(add-hook 'after-init-hook 'global-company-mode)
```

**Comment by dgutov** [comment]
All seems to be working as intended on our side: enabling `semantic-mode` means that `company-semantic` gets used, and it comes before the group containing both `company-gtags` and `company-dabbrev-code`.

Semantic should be smart enough to complete the local variables, methods, etc, if it's properly configured (that's to the best of my knowledge: I haven't used it, or any C/C++ backend, much).

If you don't want it to be used, though, remove `company-semantic` from `company-backends`.
