### ISSUE TITLE
pseudo-tooltip interacts w/ org-indent-mode again

### ISSUE THREAD

**Issue by ilohmar** [company-mode/company-mode#404]
At some point the tooltip has started interacting badly again with the `line-prefix` set by `org-indent-mode`.  Steps to reproduce (recent self-compiled Emacs and github's company-mode) in `*scratch*` after `emacs -q -nw -L .`

```lisp
(progn
  (require 'company)
  (company-mode)
  (org-mode)
  (org-indent-mode))
t

* test1234

*** test6789

*** and here is where you COMPLETE:
    - some text
    - and more
```

[For anybody not using org-mode: The starred headlines and bullet items are created w/ `M-RET` and shifted w/ `M-<right>`.  Not that it should matter.]

When you go to the end of the COMPLETE line and enter "test", you get two suggestions.  The first tooltip line (only that one!) is shifted to the right by 4 spaces, including its original content "- some text".  Experiments in a larger buffer suggest the right-shift amount is `(length (get-text-property (point-at-bol) 'line-prefix))` (as per the line which is shifted).

**Comment by ilohmar** [comment]
Just remembered that this stuff is really similar to #24, even including the shift-amount expression...

**Comment by dgutov** [comment]
Hi Ingo,

Sorry about that, writing high-level tests for the popup is pretty much impossible, so regressions are bound to happen occasionally.

Should be fixed now.

**Comment by ilohmar** [comment]
Awesome, thank you.  I understand the testing problem...  If a problem is related to the company-mode/org-indent combination, I should usually notice it quickly after updating and will open an issue :)
