### ISSUE TITLE
company-idle-begin vs buffer-chars-modified-tick

### ISSUE THREAD

**Issue by expez** [company-mode/company-mode#406]
I've been puzzled by the occassional lack of completion in clojure buffers for some time now and finally decided to investigate.

Sometimes this line, in `company-idle-begin`

``` el
       (eq tick (buffer-chars-modified-tick))
```

is always false. When stepping through `company-idle-begin` in the debugger I can see that the difference between these two are several chars.  What on earth could be causing this?

```
company-diag

Emacs 24.5.1 (x86_64-w64-mingw32) of 2015-05-16 on KAEL
Company 0.9.0-cvs

company-backends: (company-robe company-restclient company-tern company-bbdb company-nxml company-css company-eclim company-semantic company-clang company-xcode company-cmake company-capf
              (company-dabbrev-code company-gtags company-etags company-keywords)
              company-oddmuse company-files company-dabbrev)

Used backend: company-capf
Prefix: "get-libspecs-from-f"
Completions:
  #("get-libspecs-from-file" 0 1 (ns "refactor-nrepl.ns.ns-parser" type "function" face (completions-common-part)) 1 19 (face (completions-common-part)) 19 20 (face (completions-first-difference))) " (refactor-nrepl.ns.ns-parser) <f>"
```

**Comment by dgutov** [comment]
That's an interesting question, but I'm not sure how I can answer.

Have you tried disabling all third-party minor modes, for instance?

**Comment by dgutov** [comment]
You can also try adding a logging function to `before-change-functions`, although if some modifications use `inhibit-modification-hooks`, they'll bypass that.

**Comment by expez** [comment]
What am I looking for in that logger?  When logging its two arguments, `beg` and `end` they seem entirely reasonable.  One logging event for each keypress and `(= beg end)`

**Comment by dgutov** [comment]
Well, you can call `(backtrace)` from it. And see if there's anything suspicious there. But probably not, since you only get one event per keypress.

**Comment by expez** [comment]
I doubt anyone is ever going to work on this.  FWIW completion, using company with CIDER, is working quite nicely now.

**Comment by dgutov** [comment]
If really necessary, we could add some manual solution for `aggressive-indent-mode` to integrate with Company, to clean up after itself, so to speak.
