### ISSUE TITLE
How to always enable some backends after added some new backends to `company-backends`?

### ISSUE THREAD

**Issue by stardiviner** [company-mode/company-mode#407]
I configured default `company-backends` like this:
```el
    (setq company-backends
          '((company-files          ; files & directory
             company-keywords       ; keywords
             company-capf           ; `completion-at-point-functions'
             company-yasnippet
             )
            (company-abbrev company-dabbrev)
            ))
```

And I add new backends to `company-backends` for a specific major mode like this:

```el
    (add-hook 'web-mode-hook
              (lambda ()
                (add-to-list (make-local-variable 'company-backends)
                             'company-nxml)
                (add-to-list (make-local-variable 'company-backends)
                             'company-web-html)
                (add-to-list (make-local-variable 'company-backends)
                             'company-css)
                ))
```

Then, when in web-mode buffer, the `company-backends` becomes:

    (company-web-slim company-web-jade company-css company-web-html company-nxml
                      (company-files company-keywords company-capf company-yasnippet)
                      (company-abbrev company-dabbrev))

You can see, at last, the `company-capf` and `company-yasnippet` is not available.
I hope to always enable `company-capf` and `company-yasnippet`.

Is there a way to archive this? I can&rsquo;t figure out a way. So ask for help here.

**Comment by dgutov** [comment]
You can use something like that:

```el
(make-local-variable 'company-backends)
(setq company-backends (copy-tree company-backends))
(setf (car company-backends)
      (append '(company-nxml company-web-html company-css) (car company-backends)))
```

All that inside `web-mode-hook`, of course. The code assumes that the first values is a list already. Note that you only need to call `make-local-variable` once, and you don't have to use its return value.

**Comment by stardiviner** [comment]
@dgutov Thanks for your help.

**Comment by dgutov** [comment]
> and can you add a more general macro code example to README

No macro needed, a function should do fine. But I'm not sure we can provide a universal one.

This should be solved in the future via a new `completion-at-point-functions` feature.

**Comment by stardiviner** [comment]
@dgutov wow, so exiting, that's really great feature. Thanks for your improve in advance.

**Comment by moyotar** [comment]
@dgutov 
In corresponding mode, I find there are two `company-clang` and two `company-gtags` in the backends which work if my config like this.
```
(setq company-backends
      '((company-files          ; files & directory
         company-keywords       ; keywords
         company-capf
         company-yasnippet
         )
        (company-abbrev company-dabbrev)
        ))
(dolist (hook '(c-mode-hook
				c++-mode-hook
				objc-mode-hook
				))
  (add-hook hook
			(lambda()
			  (make-local-variable 'company-backends)
			  (setq company-backends (copy-tree company-backends))
			  (setf (car company-backends)
					(append '(company-gtags company-clang)
							(car company-backends)))
			 ))
  )
```

**Comment by stardiviner** [comment]
That's because `c-mode-common-hook` I think.

**Comment by moyotar** [comment]
The value of `c-mode-common-hook` is nil. How to solve it?

**Comment by stardiviner** [comment]
Show your `company-backends` value

**Comment by moyotar** [comment]
Emacs 24.5.1 (i686-pc-mingw32) of 2015-04-11 on LEG570
Company 0.9.0

company-backends: ((company-gtags company-clang company-gtags company-clang company-files company-keywords company-capf company-yasnippet)
 (company-abbrev company-dabbrev))

Used backend: (company-gtags company-clang company-gtags company-clang company-files company-keywords company-capf company-yasnippet)

**Comment by stardiviner** [comment]
Might because of `irony-mode-hook` or somethings else.
Search `company-gtags` and `company-clang` over you Emacs configs and `MELPA` packages.

**Comment by moyotar** [comment]
Both of them are used only here over my config.

**Comment by stardiviner** [comment]
> Search company-gtags and company-clang over you Emacs configs and MELPA packages.

**Comment by moyotar** [comment]
No matter which backend I put in there, it will always be double when in corresponding mode. The same in python mode if I configure the way. So the problem may be not in `company-gtags` or `company-clang`.

**Comment by stardiviner** [comment]
That's weird. I don't know about that, can't help more.

**Comment by dgutov** [comment]
Try this:

```el
(add-hook 'c-mode-hook (lambda () (message "c-mode-hook")))
(add-hook 'c++-mode-hook (lambda () (message "c++-mode-hook")))
```

then create a temporary buffer and `M-x c-mode` or `M-x c++-mode`. After switching to `Messages` (`C-h e`), you can see that the hook has run twice.

I have no idea why, looks like a bug in CC Mode. You should probably report it.

And until it's fixed, you should be able to adapt the code to account for the bug.
