### ISSUE TITLE
Plain text auto-completion for text with underscore

### ISSUE THREAD

**Issue by feixia586** [company-mode/company-mode#408]
Hi, I think the auto-completion works wonderful most of the time, but I don't think it works for text with underscore in default setting. Is there any way that I configure it so that I can do auto-completion for plain text with underscore?

**Comment by dgutov** [comment]
Try this:

```el
(setq company-dabbrev-code-modes t
      company-dabbrev-code-everywhere t)
```

**Comment by feixia586** [comment]
Awesome! It works!
