### ISSUE TITLE
no completion candidates when use eclim

### ISSUE THREAD

**Issue by sac7e** [company-mode/company-mode#410]
Hi,
I just begin to use company-mode and I have a question about eclim: 
When in a java file, I have a List<E> variable. I expected that company would pop up the window of candidates(aka. the methods and variable of List class), but it didn't. 
I do not know how to do now.  Thank you.

**Comment by dgutov** [comment]
Do you have the Eclim daemon running?

Does `company-eclim-executable` point at something? If not, you'll need to customize it.

**Comment by sac7e** [comment]
I have no idea whether eclim daemon is running? does that mean I should install eclim from its github page?

No, `company-eclim-executable` is pointed to nil, but I don't know where to find the executable.

**Comment by dgutov** [comment]
> I have no idea whether eclim daemon is running?

If you haven't installed it, you should, while skipping the Vim-related steps. http://eclim.org/install.html

> I don't know where to find the executable

Usually inside the Eclipse directory.

**Comment by sac7e** [comment]
Thank you very much.
Another question, I have added another backend company-irony in backends list and it is indeed the first one in that list. But why clang always works before it? Even I use command `M-x company-begin-backend` to specify the backend I gonna use again, it still didn't work.

**Comment by dgutov** [comment]
The first "applicable" backend is used.

But I don't really understand your explanation. Try pasting the output of `M-x company-diag` here.

**Comment by sac7e** [comment]
![image](https://cloud.githubusercontent.com/assets/9028490/10235359/9c8b7716-6869-11e5-8562-3940e846322c.png)

**Comment by dgutov** [comment]
It's just text, you know. You could paste it.

Anyway, the short answer is, I don't know. Check out Irony's documentation (for both `company-irony` and `irony-mode`), and if it doesn't help, maybe ask the maintainer via his preferred feedback mechanism (probably by creating an issue).

**Comment by sac7e** [comment]
Hah, it is.

Anyway, thank you.
