### ISSUE TITLE
Buffer periodically hangs for few seconds when typing in remote file opened via tramp

### ISSUE THREAD

**Issue by deflexor** [company-mode/company-mode#412]
I guess some backend should be disabled ?

**Comment by dgutov** [comment]
Maybe.

Try removing elements from `company-backends`, one by one.

**Comment by dgutov** [comment]
Or type `M-x company-diag`, take the currently used backend, and see if removing it makes things better. If not, repeat. Then report here on all backends that give you trouble.

**Comment by dgutov** [comment]
No response, closing.
