### ISSUE TITLE
Duplicates in popup list when company-dabbrev-downcase is nil

### ISSUE THREAD

**Issue by transtone** [company-mode/company-mode#413]
same itme in list like this:

![image 1](https://cloud.githubusercontent.com/assets/46688/10448489/c09a5ea6-71bf-11e5-95bf-6ef3ece1fc94.png)

there are tow "subclass" in the list, how to merge it as one?

**Comment by dgutov** [comment]
What backend is this? Try `M-x company-diag`.

**Comment by transtone** [comment]
Emacs 25.0.50.1 (x86_64-w64-mingw32) of 2015-10-05 on KAEL
Company 0.9.0-cvs

company-backends: (company-bbdb company-nxml company-css company-eclim company-semantic company-clang company-xcode company-cmake company-capf
              (company-dabbrev-code company-gtags company-etags company-keywords)
              company-oddmuse company-files company-dabbrev)

Used backend: company-dabbrev
Prefix: #("main" 0 1
  (fontified t part-side jsx)
  1 2
  (fontified t part-side jsx)
  2 3
  (fontified t part-side jsx)
  3 4
  (fontified t part-side jsx))

Completions:
  "main"
  "main"
  "mainclass"
  "Mainclass"
  "mainclass"
  "Mainclass"
  "Mainclass"
  "mainclass"
  "Mainclass"
  "mainClassData"
  "mainClassData"
  "mainClassOptions"
  "mainClassData"
  "mainclass"
  "mainClass"
  "mainClass"
  "mainClass"
  "mainClass"
  "mainClassData"
  "mainClassOptions"
  "mainClass"
  "mainClassData"
  "mainClassData"
  "mainClassData"
  "mainClass"
  "mainClassData"

**Comment by dgutov** [comment]
Do you have any settings changed that relate to `company-dabbrev`? I can't reproduce it so far.

**Comment by transtone** [comment]
(setq company-dabbrev-downcase nil)
It's the only settings about company-dabbrev

**Comment by dgutov** [comment]
> this come's from web-mode

How? I don't see any mention of dabbrev in web-mode's code.

> (setq company-dabbrev-downcase nil)
It's the only settings about company-dabbrev

Could you give me an example file where that happens, then? Can you reproduce it without web-mode?

**Comment by transtone** [comment]
I test the other mode, the same thing happened.
The example file : https://gist.github.com/transtone/b1d1ade69cfb9f73357b

**Comment by dgutov** [comment]
Still don't see the problem. What do you have in `company-transformers`?

You should probably start from `emacs -Q` and add settings one by one, to see which triggers it.

The Company version you have installed is from MELPA, right?

**Comment by DogLooksGood** [comment]
Met the same problems. 
company-backends:  (company-dabbrev)

**Comment by transtone** [comment]
It's settings problome.
I use  
(setq company-dabbrev-downcase nil)

for downcase, but no one told me this settings must use with this one:

(setq company-dabbrev-ignore-case nil)

if company-dabbrev-ignore-case set to keep-prefix(default), it comes the problems above.

**Comment by dgutov** [comment]
Thanks for the details. Let's keep this open, then, to find a better solution.

> but no one told me this settings must use with this one

Maybe no one told you, but the `company-dabbrev-downcase` docstring recommends exactly this.

**Comment by moyotar** [comment]
![image](https://cloud.githubusercontent.com/assets/22092607/19631775/b33ab5c6-99d2-11e6-93fa-55fb8b34a34d.png)

I have this problem too. I know it's because `ycmd` and `company-keywords` work together. Is there some settings to make candidates unique? 

> Emacs 24.5.1 (i686-pc-mingw32) of 2015-04-11 on LEG570
> Company 0.9.0
> 
> company-backends: ((company-files company-keywords company-capf company-yasnippet company-ycmd)
>  (company-files company-keywords company-capf company-yasnippet)
>  (company-abbrev company-dabbrev))
> 
> Used backend: (company-files company-keywords company-capf company-yasnippet company-ycmd)
> 
> Prefix: #("ty" 0 2
>   (fontified t))
> 
> Completions:
>   #("typedef" 0 7 (company-backend company-keywords))
>   #("typedef" 0 7 (return_type "[ID]" company-backend company-ycmd)) " -> [ID]"

**Comment by dgutov** [comment]
@moyotar Why not remove `company-keywords` from the first group when `company-ycmd` is used? It seems to handle them already.

**Comment by agreselin** [comment]
I have the same issue. With this `init.el`,
```
(setq company-dabbrev-downcase nil)

(add-hook 'after-init-hook #'global-company-mode)
```
I get
![Screenshot from 2020-11-30 22-08-41](https://user-images.githubusercontent.com/22297948/100666094-bf075700-3358-11eb-851d-11325ffa9eb8.png)
With a capitalized prefix it's the same, only the completions are capitalized too.

`company-diag` returns
```
Emacs 27.1 (x86_64-redhat-linux-gnu) of 2020-08-21 on buildhw-x86-03.iad2.fedoraproject.org
Company 0.9.13

company-backends: (company-bbdb company-semantic company-cmake company-capf company-clang company-files
	      (company-dabbrev-code company-gtags company-etags company-keywords)
	      company-oddmuse company-dabbrev)

Used backend: company-dabbrev
Major mode: lisp-interaction-mode
Prefix: "lis"
Completions:
  "lisssp"
  "lisssp"
  "lisp"
  "Lisp"
```
