### ISSUE TITLE
In C++ completion, a redundant ":" is inserted before the parantheses

### ISSUE THREAD

**Issue by radupopescu** [company-mode/company-mode#414]
Using Emacs 24.5.1 on Mac OS X 10.11, company-mode 0.9.0-cvs (from MELPA). C++ completion is done with the company-ycmd backend, but I've noticed the same issue with company-clang, too, so I suspect it's not related to the backend.

Suppose I have a struct:
```c++
struct C
{
    int x() { return 1; }
};
```
then later I declare an instance of C:
`C c;`
Using the suggested completion for c.x (pressing ENTER) will insert:
`c.x:()`

I've noticed this today, but it's quite annoying. Please let me know what other information I should supply.
Thank you!

**Comment by dgutov** [comment]
Can't reproduce. When I press RET, it inserts `x()`, as expected.

Please try reproducing it starting with something like this:

```
~/Downloads/emacs-24.4/src/emacs -Q -L ~/.emacs.d/site-lisp/company -l company
```

**Comment by radupopescu** [comment]
I tracked down the problem and it's not in `company` itself. The issue was a conflict with `company-distel` which provides an optional frontend for the company. Using just the `company-distel` backend without the optional frontend works fine.

Thanks all for the work on `company`. It's really great.

**Comment by dgutov** [comment]
Thanks for investigating, and you're welcome!
