### ISSUE TITLE
Compatibility issue with cedet

### ISSUE THREAD

**Issue by KarthikNayak** [company-mode/company-mode#419]
When using company-mode with cedet (c-mode). It jumps the cursor to the definition of datatype when typing the initial characters of said datatype.  

From \*Messages\*  :
>Company: An error occurred in post-command
>Company: frontend company-pseudo-tooltip-unless-just-one-frontend error "Wrong type argument: number-or-marker-p, nil" on command post-command

Emacs config:
>(require 'company)
(require 'company-go)
(add-hook 'after-init-hook 'global-company-mode)
(add-to-list 'company-backends 'company-c-headers)
(setq company-idle-delay 0)
(add-to-list 'company-backends '(company-go))

>;;cedet
(load-file (concat user-emacs-directory "/cedet/cedet-devel-load.el"))
(load-file (concat user-emacs-directory "/cedet/contrib/cedet-contrib-load.el"))

**Comment by KarthikNayak** [comment]
Needless to say, this error only exists in the latest cedet versions, the built-in version has no problems. Not sure whether to report here.

**Comment by dgutov** [comment]
Can you reproduce the bug by pressing `C-M-i` in the same context?

**Comment by KarthikNayak** [comment]
@dgutov Yup! after typing two characters and pressing C-M-i (or typing the next character as previously stated) it jumps to the definition.

**Comment by dgutov** [comment]
> ...it jumps to the definition

And signals an error?

In that case, please report this to the upstream CEDET.

**Comment by KarthikNayak** [comment]
> completion-in-region: Assertion failed: (<= start (point)),

Sure will do :+1: Thanks
