### ISSUE TITLE
How To Let Company Complete Symblol?

### ISSUE THREAD

**Issue by zeka0** [company-mode/company-mode#420]
I'm using emacs 24.5 and it seems that it doesn't have the command 'semantic-ia-complete-symbol-menu'. So I turned to 'company' for help. The doc of company doesn't mention how to combine company with semantic. Is there any way that I can make the output of 'semantic-ai-complete-symbol' appear in company popup-bar?(i.e, complete symbol using company)

**Comment by dgutov** [comment]
What does `M-x company-semantic` show?

**Comment by zeka0** [comment]
Sorry for the delay.
In Java, I test 'this. '. it first shows 'can't complete at this point' then it shows one of the method of that class(no popup menu, and the completion is't complete).
In Cpp, I test 'this->'. It first shows 'can't complete at this point' then it displays 'Idle Service Error semantic-idle-summary-idle-funcion:"#<buffer matrix_base.h>-Wrong type argument: strings, ((\"list\"0 nil nil nil))"'.I tested semantic in my 'matrix_base.h' file.

**Comment by dgutov** [comment]
You should disable some `semantic-idle-` modes. Maybe all of them.

**Comment by zeka0** [comment]
I have disabled all of them. It(company-semantic) still shows that 'can't complete at the point'(I tested it in Java), so may be it's because company can't complete symbols like '.'  or '->'?

**Comment by dgutov** [comment]
Do you have `semantic-mode` enabled?

**Comment by dgutov** [comment]
But anyway, built-in Semantic has no Java support.

**Comment by zeka0** [comment]
It seems that you are right...(The e-mail I sent to you is partially wrong because semantic-complete-symbol did show completions, but the completions are not correct most of the times). It's really a pain to accommodate semantic in emacs24...

**Comment by dgutov** [comment]
If you want to play with CEDET (and especially if you use Java), you should try out its trunk.

Or rather wait a few weeks until CEDET development repo is merged into Emacs fully (because that's the plan), and then try an Emacs snapshot.

**Comment by zeka0** [comment]
Sadly

**Comment by stardiviner** [comment]
@zeka0 I want to configure Emacs for Java Development too, can you help me out? What's your email? I can contact you, I'm tring to use Eclim for Java completion.
