### ISSUE TITLE
Potentially inconsistent behaviour for backends using company-grab-symbol

### ISSUE THREAD

**Issue by Alexander-Miller** [company-mode/company-mode#421]
`company-grab-symbol` makes use of `(skip-syntax-backward "w_")` which may lead to
problems since the `~` character is not recognized as a symbol character in some
major modes, even when they are closely related (like prog- and
emacs-lisp-mode). This means that `company-grab-symbol` will return different
values for the same prefix, depending on the current major-mode (e.g. /foo/
instead of ~/foo/).

The vast majority of the time this makes no difference, and company
backends will work as intended. Problems will only occur when using grouped
backends which include backends that make use of `company-grab-symbol` to fetch
prefixes. The grouped backends will be returning different prefixes, causing later
backends not to contribute their completions. In own my own concrete case I thought that
my own custom backend, which was simply grabbing the content of my PATH, was somehow breaking `company-files`.

Unless there is some other company or 3rd party function simple custom backends ought to
be using (I've followed [this](http://sixty-north.com/blog/writing-the-simplest-emacs-company-mode-backend) tutorial) I think that this issue ought to be if not corrected, then at least documented somewhere (the docstring of `company-grab-symbol` is empty anyway) as this inconsistency came out of nowhere and was, at least for me, frustratingly difficult to pin down.

At any rate the problem can be solved by doing something like this:
`(modify-syntax-entry ?~ "_" fish-mode-syntax-table)`

company version is 0.9.0-cvs, emacs version 25.1.50.1 compiled from source not an hour ago.

**Comment by redguardtoo** [comment]
I got similar issue, in web-mode and css-mode, "-" should be part of prefix because css class name use it like "btn-default". A buffer local variable like "extra-characters-belonging-to-symbol" is useful

**Comment by dgutov** [comment]
> company-grab-symbol will return different
values for the same prefix, depending on the current major-mode (e.g. /foo/
instead of ~/foo/

Why, yes, the major modes are responsible for defining the appropriate notion of symbol in each respective language.

> some
major modes, even when they are closely related (like prog- and
emacs-lisp-mode)

`prog-mode` is just as related to `emacs-lisp-mode`, as it related to `ruby-mode`. Obviously, they're going to have very different syntax tables.

> Problems will only occur when using grouped
backends which include backends that make use of company-grab-symbol to fetch
prefixes. The grouped backends will be returning different prefixes, causing later
backends not to contribute their completions.

How? That makes no sense: if different backends call the same function, at the same buffer position, they must return the same result here.

And if some backends call `company-grab-symbol`, and some don't, well, no single change to that function can make sure that all backends return the same value.

> Unless there is some other company or 3rd party function simple custom backends ought to
be using

No backend really has to use it. It's just a good default option if a backend doesn't have any additional special requirements.

> At any rate the problem can be solved by doing something like this:

Indeed. And that's what you should normally do. If a major mode has a problem with symbol boundaries, it a good reason for a bug report.

**Comment by dgutov** [comment]
> I got similar issue, in web-mode and css-mode, "-" should be part of prefix because css class name use it like "btn-default".

Sounds like web-mode should make `-` a symbol constituent.

>  A buffer local variable like "extra-characters-belonging-to-symbol" is useful

That wouldn't help with certain other functionality in Emacs that also defaults to using the current symbol. `dabbrev-expand`, for example, or `find-tag`.

**Comment by Alexander-Miller** [comment]
>How? That makes no sense: if different backends call the same function, at the same buffer position, they must return the same result here.

They weren't calling the same function. Company's backends were doing as they always do, delivering correct results. Trouble started when I placed my own bachend, which used `company-grab-symbol` into a grouped backend ahead of others, my local `company-backends` value being something like `((company-shell-functions company-files))`. My backend would grab a different prefix than all the others making sure their completions were not being included.

>And if some backends call company-grab-symbol, and some don't, well, no single change to that function can make sure that all backends return the same value.

True, and any attempt would likely drown you in a sea of corner cases. I don't think this needs fixing either, everything is in fact working as intended, this issue is more or less a heads up for you and others who might have the same issue, rare as it is.

The actual problem here, I think, is one of mismatched expectations. Looking back it's obvious that major modes might have different ideas on what constitutes a symbol, but back when I started writing my backend I assumed I'd be getting back a symbol as it is defined by company and not the current major mode. Fortunately course this part is easily remedied: Add a doc string to the relevant grabbing functions explaining that different major modes have different ideas as to what constitutes a symbol and let the user deal with it as they see fit.

**Comment by dgutov** [comment]
> this issue is more or less a heads up for you and others who might have the same issue, rare as it is

All right, but there's nothing new in it, as far as I'm concerned. #422 is another related issue.

> Add a doc string to the relevant grabbing functions explaining that different major modes have different ideas as to what constitutes a symbol and let the user deal with it as they see fit.

All right, but where do I stop explaining? There's just one notion of symbol in Emacs, and it depends on the current syntax table.

Do I also explain that the notion of word used by `company-grab-word`, likewise depends on the current syntax table?

**Comment by dgutov** [comment]
I've added some basic docstrings.

**Comment by Alexander-Miller** [comment]
>Do I also explain that the notion of word used by company-grab-word, likewise depends on the current syntax table?

It's only 3 or 4 functions and all related, so I guess it couldn't hurt. I think something like 

>"If point is at the end of a symbol/word (as defined by the current major mode's syntax table), return it."

is enough to let people know where to start debugging, even if they don't know about major modes' syntax tables, like I did.

**Comment by dgutov** [comment]
> It's only 3 or 4 functions and all related, so I guess it couldn't hurt.

Sorry, that looks too redundant to me: there are many symbol-related functions out there, in the core and third-party code, that don't point out that symbols are defined by the syntax table.

I think a reminder like that would fit better in a manual (but we don't have one), or the [wiki page](https://github.com/company-mode/company-mode/wiki/Writing-backends), or the [article](http://sixty-north.com/blog/writing-the-simplest-emacs-company-mode-backend) you were referring to.

**Comment by dgutov** [comment]
The wiki is publicly editable, so please have a go at it.

**Comment by dgutov** [comment]
By the way, I've been thinking about the issue of different backends in a group returning different prefixes. We actually could try and handle that. #426 will be tracking it.

**Comment by Alexander-Miller** [comment]
Ah, I had completely forgotten about the wiki. You're right, it's a better place for such explanations. I'll make the appropriate edits today or tomorrow.
