### ISSUE TITLE
company-yasnippet does not complete for some characters

### ISSUE THREAD

**Issue by stardiviner** [company-mode/company-mode#422]
I have some snippets which key is `%`, `%%`, `%link_to`, etc.
I use in web-mode with `.yas-parents` has `rhtml-mode`.

I can expand those yasnippet snippets with `[Tab]`.

But company-yasnippet don&rsquo;t show candidates after `%`.

Here is the result of command `company-diag`:

    Emacs 24.5.1 (x86_64-unknown-linux-gnu) of 2015-09-10 on foutrelis
    Company 0.9.0-cvs
    
    company-backends: ((company-robe company-web-html company-tern company-css company-files company-keywords company-capf company-yasnippet)
     (company-abbrev company-dabbrev))
    
    Used backend: (company-robe company-web-html company-tern company-css company-files company-keywords company-capf company-yasnippet)
    
    Prefix: #("link" 0 1
      (block-side t face #1=(web-mode-block-face))
      1 2
      (block-side t face #1#)
      2 3
      (block-side t face #1#)
      3 4
      (block-side t block-end t face #1#))
    
    Completions: none

If this is not a problem in company-yasnippet, then how to add this for completing?

**Comment by dgutov** [comment]
It's a problem in `company-yasnippet`. Yasnippet supports different characters in snippets, and iterates between a few of them in `yas-key-syntaxes`, to see whether there's a trigger key before point.

`company-yasnippet--candidates` just looks for snippets with name that starts with the symbol-at-point, which can't include snippets with names starting with punctuation.

So I guess `company-yasnippet--candidates` should be fixed to be smarter about that, and maybe use the buffer's contents similarly to what Yasnippet does, instead of just filtering by its argument. The way to implement this is not entirely obvious to me right now, though.

**Comment by stardiviner** [comment]
I come up with one idea, Ruby source code have variable like instance variable `@@instance_variable`.
Seems company-mode can't complete it. I say you linked another relative issue. Is this same with that issue? If yes, I will create an issue to `enh-ruby-mode` to add this to syntax table.

**Comment by dgutov** [comment]
> Is this same with that issue?

It is similar, but if I understand what problem you're referring to ("company-mode can't complete it" is a shitty bug report; yes it can), you'll want `@` and `:` to be removed from the "symbol" syntax.

I have this planned for `ruby-mode`, but it'll have to be accompanied with changes to font-lock rules, SMIE tokenizer, and probably other places.

**Comment by stardiviner** [comment]
I see, Thanks. I found you have many things to do, I subscribe many of your github Emacs packages projects. Really feel sorry that I can't help you a little.
Anything you think I can help, I would like to help.

**Comment by dgutov** [comment]
> Anything you think I can help, I would like to help.

Most of the time I spend on Emacs lately happens in the core development. We could always use more contributors. If you're wondering where to start, feel free to ask on emacs-devel, or maybe search its archives first.

**Comment by stardiviner** [comment]
Gotcha.

**Comment by dgutov** [comment]
Please check out the branch `yas-key-syntaxes`. See if it solves your problem, and doesn't bring any new ones.

**Comment by dgutov** [comment]
It probably still doesn't handle `%` and `%%`, but `%link_to`, etc, should work.

**Comment by stardiviner** [comment]
It can work, why the candidates don't have `%`, but the meta info have `%`.
Will you merge this branch?

**Comment by dgutov** [comment]
> It can work

Does it work for all your snippets?

> It can work, why the candidates don't have %, but the meta info have %?

You might want to rephrase the question, or maybe add a picture. But the answer is probably "because it's needed for some things to work well".

> Will you merge this branch?

Not right away.

**Comment by dgutov** [comment]
I've pushed a variation to `yas-key-syntaxes-v2`. The version puts full keys into the popup, but if the key is not a symbol, you won't be able to type to narrow the list down.

Please test and see if you actually prefer this.

**Comment by dgutov** [comment]
And with the latest commit, narrowing down will usually work.

@stardiviner Let me know how you like it.

**Comment by stardiviner** [comment]
With the `yas-key-syntaxes-v2` and latest commit, it works as expected.
What symbol do you mean? All of my snippet keys are strings.

**Comment by dgutov** [comment]
> With the yas-key-syntaxes-v2 and latest commit, it works as expected.

Terrific. I'll merge it in a few days, unless you report and further problems.

> What symbol do you mean?

`%` belongs to the "punctuation" syntax class, so any key containing it cannot be a "symbol at point".

**Comment by stardiviner** [comment]
Thanks

**Comment by stardiviner** [comment]
@dgutov After more usage and test of branch `yas-key-syntaxes-v2`. I found `yas-key-syntaxes` branch is better. Even it don't have full key shown as candidates.
Because `v2` will break other completion too.
For example in Emacs Lisp code:
`eshll-` prefix, it will not show related candidates correctly. Because `-` is punctuation too.
I would prefer `yas-key-syntaxes`.
You're right, take more time on testing and usage.

**Comment by dgutov** [comment]
> I found yas-key-syntaxes branch is better. Even it don't have full key shown as candidates.

It has its own problem, unfortunately.

Have you tried `M-x company-yasnippet` after typing just `%`? I expect it should work in v2, but not in the first branch.

> eshll- prefix, it will not show related candidates correctly.

Could you post a screenshot with the problem?

**Comment by stardiviner** [comment]
Here is the screenshot:

http://i.imgur.com/xQco5nc.png

**Comment by dgutov** [comment]
> Here is the screenshot:

From what I see, the popup just lists the available snippets at point. And any completions go after them simply because of sorting. Isn't that what you want?

If you type `m`, the popup should include `eshell-mode`.

> Yes, v2 can work for %l. to complete %link_to.

And v1 doesn't?

**Comment by stardiviner** [comment]
I checked out the latest version `v2`.

company-yasnippet does complete after `-` as it does.
I prefer `v1` style. Because `v2` will confues me. like upper example.

And `v1` works too. As upper said. just don't show `%` in candidates. I can accpet this. After all, the meta info shows the snippet info.

**Comment by stardiviner** [comment]
Is it better to improve this syntax detect on majr-mode, then company-yasnippet can use that syntax table. Like `web-mode` recently added `-` as a part of prefix of completion.
https://github.com/fxbois/web-mode/pull/640

**Comment by dgutov** [comment]
> I checked out the latest version v2. Still same as the screenshot.

It was meant to fix snippet expansion, not how the popup looks.

> I prefer v1 style. Because v2 will confues me. like upper example.

You haven't addressed my previous comment.

> Is it better to improve this syntax detect on majr-mode?

You can't add `%` to the "symbol" syntax everywhere - that would be weird. You can avoid using it in snippets, though.

**Comment by stardiviner** [comment]
You previous comment?
You mean:
> > Yes, v2 can work for %l. to complete %link_to.

> And v1 doesn't?

Yes, v1 can work.

> You can't add % to the "symbol" syntax everywhere - that would be weird. You can avoid using it in snippets, though.

I see.

**Comment by dgutov** [comment]
> You mean:

I mean:

> From what I see, the popup just lists the available snippets at point. And any completions go after them simply because of sorting. Isn't that what you want?

> If you type m, the popup should include eshell-mode.

**Comment by stardiviner** [comment]
No, it's not what I expected.
Company-yasnippet should respect 'eshell-' as prefix, instead of '-'.
I think most of time tokens are separated by space in source code, some special character like . - : @ $ ? ( etc will be used at the begin or inside of key for the purpose of special indicate or separation. For example, I use '%link_to' as snippet key because I inherited rhtml snippets from web-mode, to differ it from html-mode snippets. So it's a kind of indicator. And examples like 'eshell-mode' in elisp and 'Module::' in Ruby is for separation.

This is what I think. I don't know whether it is correct.

**Comment by dgutov** [comment]
> Company-yasnippet should respect 'eshell-' as prefix, instead of '-'.

So in other words, you would say that `company-yasnippet` should only use key prefixes that are as long as the symbol at point, or longer? That makes a certain kind of sense, but documenting it is going to be awkward.

Try removing `"w"` from `yas-key-syntaxes` when using the v2 branch. It should have the desired effect.

Note that v1 by itself doesn't have the same effect: snippets for keys shorter than the current symbol are still included (as long as `"w"` is in `yas-key-syntaxes`), they're just sorted to the end of the popup.

**Comment by stardiviner** [comment]
This is awesome. Finally get what I want. works great.
Thank your for long time helping me.
Should we put this as a NOTE in README?

**Comment by dgutov** [comment]
> Finally get what I want.

To clarify, do you prefer the v2 branch now?

> Should we put this as a NOTE in README?

No, I think I'll simply hardcode the "as long as the current symbol" limitation, until someone complains.

**Comment by stardiviner** [comment]
@dgutov Yes, I think this result is prefect enough.

> No, I think I'll simply hardcode the "as long as the current symbol" limitation, until someone
> complains.

You're right, must someone will complains this.
What should I do?
If you can accept to add a new option to trigger this behavior.
Or I can download your `v2` version `company-yasnippet` to override default code.

**Comment by dgutov** [comment]
I've merged v2 to master, and added the "override" code on top of it. That should do it.

> What should I do?

Please switch to master and report any new problems.
