### ISSUE TITLE
Backend request: Dart

### ISSUE THREAD

**Issue by andreis** [company-mode/company-mode#423]
[](dartlang.org)

I'm new to both Emacs and Dart, but I might work on this myself if nobody wants/is able to do it.

**Comment by dgutov** [comment]
Dart completion support would probably be best implemented within [dart-mode](https://github.com/nex3/dart-mode).

Looking at the code, it doesn't mention `completion-at-point-functions`, but the docstring for `dart-enable-analysis-server` mentions completion, so using the analysis server should be good starting point to implementing a completion-at-point function.

**Comment by stardiviner** [comment]
+1

**Comment by sid-kurias** [comment]
FYI
Company mode for dart now exists  https://github.com/sid-kurias/company-dart.

For now though you will have to use the fork of dart-mode from https://github.com/sid-kurias/dart-mode, until all the changes get merged in.  Pull requests are pending.

The dart-mode fork supports formatting, goto definition and outlines via imenu.
