### ISSUE TITLE
Company-clang with objc

### ISSUE THREAD

**Issue by fxfactorial** [company-mode/company-mode#424]
I saw this closed issue, https://github.com/company-mode/company-mode/issues/130, and was wondering what the status of company-clang + objc was. 

Just sharing my experience...
   I've had it working correctly at times, I did get methods completing so I know its possible, but it was    very fragile and I've since lost that setup :( 

I've added extra company-clang-arguments, with "-F" "some paths" but I still get errors like 

```shell
In file included from <stdin>:2:
In file included from /System/Library/Frameworks/Foundation.framework/Headers/Foundation.h:8:
/System/Library/Frameworks/Foundation.framework/Headers/NSObjCRuntime.h:435:1: error: expected identifier or '('
@class NSString, Protocol;
^
/System/Library/Frameworks/Foundation.framework/Headers/NSObjCRuntime.h:437:19: error: unknown type name 'NSString'
FOUNDATION_EXPORT NSString *NSStringFromSelector(SEL aSelector);
                  ^
/System/Library/Frameworks/Foundation.framework/Headers/NSObjCRuntime.h:438:44: 
```

**Comment by dgutov** [comment]
The current status is probably accurately described by that other issue: I don't have a Mac (or intention to buy one), and so far no Apple device owner has been motivated enough to both file an issue *and* see it through.

I think `company-clang` provides the same level of support to C, C++ and Objective-C users: the user must set `company-clang-arguments` to the value appropriate for their project(s). The difference being that there are a couple of third-party packages out there that can compute and set this value automatically in C++/CMake based projects, and none that would do so for Objective-C, AFAIK.

If you show me a sample project that targets GNUStep, I can try to work out the necessary arguments.

Alternatively, try doing some work yourself: can you compile the file in question from the command line? What arguments do you use for that?

**Comment by fxfactorial** [comment]
@dgutov I fiddled with it some more and have it working. 

Will write up how to do this back here or in a blog post later. 

![screen shot 2015-11-27 at 6 04 02 pm](https://cloud.githubusercontent.com/assets/3036816/11449622/5c8ac5f0-9531-11e5-9b25-617811ec8978.png)

**Comment by dgutov** [comment]
> Will write up how to do this back here or in a blog post later.

Fantastic, thanks in advance.

**Comment by fxfactorial** [comment]
@dgutov sorry for delay: http://hyegar.com/2016/03/02/emacs-for-objc/

**Comment by dgutov** [comment]
Cool, I've added the link to the home page.

**Comment by jojojames** [comment]
Thanks for taking the time to write those instructions @fxfactorial.
The line "-std=c++11" causes clang completion errors for me. Removing it gets completion working with obj-c.

    (defun my/setup-osx-completion ()
        "Setting up semantic ios/osx completion.
    Used http://hyegar.com/2016/03/02/emacs-for-objc/ as baseline."
        (defvar xcode-base-path "/Applications/Xcode.app/Contents/Developer/Platforms/")
        (defvar ios-sdk-path "iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk")
        (defvar mac-sdk-path "MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk")
        (when (on-osx)
        (setenv "LC_CTYPE" "UTF-8")
        (my/company-set-clang-args
        `("-isysroot"
            ,(concat xcode-base-path ios-sdk-path)
            ;; ,(concat xcode-base-path mac-sdk-path)
            ;; "-std=c++11"
            "-I" "/usr/include/c++/4.2.1"))))

**Comment by cxa** [comment]
To avoid hard-coded path.

```elisp
(setq
 company-clang-executable
 (substring (shell-command-to-string "xcrun --find clang++") 0 -1)
 
 company-clang-arguments
 `("-isysroot"
   ;; If you target macOS
   ;; ,(substring (shell-command-to-string "xcrun --sdk macosx --show-sdk-path") 0 -1))
   ,(substring (shell-command-to-string "xcrun --sdk iphoneos --show-sdk-path") 0 -1))


 flycheck-c/c++-clang-executable
 (substring (shell-command-to-string "xcrun --find clang++") 0 -1)

 company-backends
 '(company-clang
   company-capf
   company-c-headers
   company-jedi))
```
