### ISSUE TITLE
Allow different backends in a group to return prefixes of different length

### ISSUE THREAD

**Issue by dgutov** [company-mode/company-mode#426]
And either adjust the completions somewhere inside `company--multi-backend-adapter`, or carry the necessary offsets through somehow, and use them when rendering the popup and inserting completions.

The latter should work faster, but will take more work to implement.

**Comment by dgutov** [comment]
Prefixes of different length are still not supported, but https://github.com/company-mode/company-mode/pull/1405 should cover most of the linked scenarios.

Though some friction will remain, most notably when combining `company-files` with other backends, and using that outside of strings/comments.

**Comment by ryanobjc** [comment]
When company-capf is in a group of backends, and you have LSP mode enabled, the prefix tends towards "" which means other backends lose any ability to provide context-sensitive advice.  eg: When I type ./ the terraform lsp sever will set the prefix to "" thus the files backend never does anything.  Grouping company-capf with lsp isn't giving me the results I want: context sensitive completion across a few different mechanisms.  LSP isn't the end-all of completion, and sometimes files or even dabbrev-code is more helpful.

With completion-at-point functions that can access LLM generation, we have a wide variety of completions now available to us, and not all of them will share the same prefix.  It would be nice to have a single UI completion list to see it all at once.  I'm sort of thinking how to bring emacs+company into feature parity with vs code for example.  Right now it seems like the completion system doesn't really support the kind of mixed suggestions with different prefixes.  I might be missing something, but I don't see any UX or philosophical reason why a completion framework couldn't offer multiple completions based on multiple prefixes - what am I missing?

**Comment by dgutov** [comment]
>  I might be missing something, but I don't see any UX or philosophical reason why a completion framework couldn't offer multiple completions based on multiple prefixes - what am I missing?

I mentioned a particular UX problem in https://github.com/company-mode/company-mode/issues/1260#issuecomment-980480084, but supporting it is better than not supporting, of course.

Anyway, it *is* coming, but as with most extensions of the backend protocol, I wanted to target multiple birds. And then other work came up, so we're still here. What makes this more difficult is really the LSP protocol, which doesn't actually plug into our backend protocol (or CAPF) properly. So it's also a question of remaining compatible with each LSP client's internal black magic, and hopefully even allowing to simplify it.

**Comment by dgutov** [comment]
It should work now.
