### ISSUE TITLE
Approximating auto-complete-mode behaviour

### ISSUE THREAD

**Issue by wasamasa** [company-mode/company-mode#427]
I did transition over from auto-complete-mode to company-mode and I'm sure I'm not the only one.  There's a number of differences between their behaviour, mostly with the way candidates are selected.

In auto-complete-mode hitting `TAB` inserts the first candidate and keeps the popup around.  Hitting `TAB` again highlights and inserts the next candidate.  You can then hit `SPC` to proceed typing the next word or `RET` for a newline or anything else.  Canceling the completion with `C-g` doesn't appear to be supported.

In company-mode hitting `TAB` inserts the common completion.  You can cycle the highlighted candidate with `M-n` and `M-p` and then insert it with `RET`.  Typing `SPC` would exit the mode, same goes for `C-g`.

The common recommendation to "fix" this is binding `company-complete-common-or-cycle` to `TAB`.  This alters the behaviour to `TAB` inserting the common completion first, then cycling as `M-n` would.  Two minor quips are still there though:

- It still doesn't insert the candidate at the place point is.  I started writing a command to insert the first candidate without finishing the completion in progress, but then it dawned on me that this would "break" completion as the currently inserted text is used to derive the prefix to pass to the completion backend.  You could of course hack around it, but I imagine the more elegant way to use an overlay previewing the text that would be inserted.  Whether this shall be an extension to the existing overlay popup code or belong to a separate frontend enabled along with it I'm less sure about.  Opinions?
- Hitting `SPC` will exit completion.  It would be nice to be able to bind it to a command that completes and inserts a space afterwards.  You could offer the same for `RET` in case anyone is missing that part of auto-complete-mode as well.  I remember a ticket asking for any self-inserting key to finishing completion, but that sounds like a bad idea to be fair, even if one could abort with `C-g`.  Thoughts on this?

**Comment by dgutov** [comment]
Hi again!

Personally, I'm content with the difference, and wouldn't prefer auto-complete-mode's behavior by default. But you can get close.

> In auto-complete-mode hitting TAB inserts the first candidate and keeps the popup around. Hitting TAB again highlights and inserts the next candidate.

I've worked on a patch around this area once. Considering the gymnastics  `ac-expand-string` has to perform, it's not my cup of tea.

> You could of course hack around it, but I imagine the more elegant way to use an overlay previewing the text that would be inserted.

Why don't you just replace `company-preview-if-just-one-frontend`, in `company-frontends`, with `company-preview-frontend`?

> It would be nice to be able to bind it to a command that completes and inserts a space afterwards.

I'm pretty sure writing a command like that and binding it is easy. But first, you might want to try customizing `company-auto-complete` to either of the non-nil values, and choose the elements of `company-auto-complete-chars` to your liking: one might prefer to not only have SPC trigger the insertion, but for both parens to do that too, as well as comma and period.

**Comment by wasamasa** [comment]
> Why don't you just replace company-preview-if-just-one-frontend, in company-frontends, with company-preview-frontend?

Ah nice, that does the trick.  After customizing my theme, it does blend in just right.

> But first, you might want to try customizing company-auto-complete to either of the non-nil values, and choose the elements of company-auto-complete-chars to your liking: one might prefer to not only have SPC trigger the insertion, but for both parens to do tha too, as well as comma and period.

Finally I know what this variable is for, I thought before it controls when to *start* auto-completion, not on what condition to complete the candidate.

Thank you for the help, I consider the question answered with this.  Perhaps a FAQ item or wiki entry or anything doc-like containing these hints would make sense.  While it's good that this information is recorded in a ticket, making it more prominent wouldn't hurt.

**Comment by dgutov** [comment]
No problem.

> Perhaps a FAQ item or wiki entry or anything doc-like containing these hints would make sense.

I'd be happy to accept a patch improving the relevant docstrings. And the wiki publicly editable, in case someone would like to write a longer guide.

**Comment by wasamasa** [comment]
I've added my tweaks to a wiki page now.

**Comment by dgutov** [comment]
Thanks! I don't understand this bit, though:

> it feels a bit weird that typing keys like SPC or RET won't insert the candidate and the key

Does `(setq company-auto-complete t)` change the behavior of RET in any way?

**Comment by wasamasa** [comment]
No.  Fixed.

**Comment by dgutov** [comment]
Thanks again.
