### ISSUE TITLE
how to dynaically modify company-backends

### ISSUE THREAD

**Issue by redguardtoo** [company-mode/company-mode#428]
```lisp
(defun toggle-company-ispell ()
  (interactive)
  (cond
   ((memq 'company-ispell company-backends)
    (setq company-backends (delete 'company-ispell 'company-backends))
    (message "company-ispell disabled"))
   (t
    (add-to-list 'company-backends 'company-ispell)
    (message "company-ispell enabled!"))))
```

I can add `company-ispell` by run `toggle-company-ispell`, but if I run `toggle-company-ispell` again, the company-mode does NOT work anymore.

company-0.8.12

**Comment by dgutov** [comment]
It's a bug in your code: replace `(delete 'company-ispell 'company-backends)` with `(delete 'company-ispell company-backends)`.

**Comment by redguardtoo** [comment]
Thanks.
