### ISSUE TITLE
Suggestions popup misplaced after text reflow using M-q

### ISSUE THREAD

**Issue by martinvlk** [company-mode/company-mode#431]
When I am typing text, I get the suggestions popup and at this moment I reflow the text with M-q, the popup no longer corresponds to the current editing position.

This alone would be fine, but the problem is that from then on the popup starts displaying in wrong position - disconnected from where I am currently typing.

**Comment by dgutov** [comment]
Please provide more details: what are the buffer contents, what's the cursor position?

**Comment by martinvlk** [comment]
The buffer is a Haskell source code file and I found the wrong position of the popup persists for existing file, e.g. it is wrong even after I stop/start emacs. Weird.

When I start a new Haskell buffer the popup shows fine.

Any ideas?

**Comment by dgutov** [comment]
> When I start a new Haskell buffer the popup shows fine.

Even if it has the same contents?

**Comment by martinvlk** [comment]
Yes, even if I copy/paste the complete contents from the bad buffer the suggestion box shows correctly in the new buffer.

**Comment by dgutov** [comment]
Seems like a conflict with some minor mode you're using. Does the bug occur often? Can you make a video?

Can you reproduce the problem if you start `emacs -Q` (without your customizations), then only add company-mode's directory to `load-path`, load and enable it, and then start editing the file in question?

**Comment by dgutov** [comment]
And maybe I should rephrase this: if you copy the buffer contents to the new buffer, and press `M-q`, does the bug also occur?

**Comment by martinvlk** [comment]
Oh, I just found what's the cause! It's the fill column indicator mode that's causing it - when I switch taht off the popup works fine.

Can this be avoided in any way?

**Comment by martinvlk** [comment]
Found this: https://github.com/alpaker/Fill-Column-Indicator/issues/54

**Comment by dgutov** [comment]
There's a workaround in the existing issue on this subject: #180.

**Comment by martinvlk** [comment]
Oh, that works around the problem - brilliant - thanks!
