### ISSUE TITLE
duplicates not removed when combining company-tern and company-dabbrev

### ISSUE THREAD

**Issue by aaronjensen** [company-mode/company-mode#432]
![ret](https://cloud.githubusercontent.com/assets/8588/11832800/613cf5b6-a371-11e5-9f81-704ffeff388d.gif)

When using:

```lisp
(setq-default company-backends-js2-mode '((company-tern :with company-dabbrev)))
```

`ret` autocompletes to `return`, `return`. I would expect that the duplicates would be stripped, am I missing something else?

I'm using spacemacs, here is my config: https://github.com/aaronjensen/dotfiles/blob/master/spacemacs

#### System Info
- OS: darwin
- Emacs: 24.5.1
- Spacemacs: 0.105.0
- Spacemacs branch: develop (rev. 78bdfd0)
- Distribution: spacemacs
- Layers:
```elisp
(better-defaults emacs-lisp markdown syntax-checking auto-completion erlang elixir git dash html org colors spacemacs-layouts osx github javascript react deft floobits ruby semantic unimpaired
                 (shell :variables shell-default-height 30 shell-default-position 'bottom)
                 (spell-checking :variables spell-checking-enable-by-default nil)
                 ranger)
```

**Comment by stardiviner** [comment]
I have this issue too.

**Comment by dgutov** [comment]
In this case, `company-tern` seems to return an empty string for annotation (as opposed to returning nil), so we end up comparing them, find them non-equal and keep both elements. We could fix that by explicitly replacing empty string annotations with nils.

However, is this the only case you find problematic? What about if an item returned by `company-tern` *does* have a non-empty annotation, and `company-dabbrev-code` returns the same method's name?

Can anybody think of a case when we want to keep both an item with annotation, and an item with the same name without annotation, in the combined list?

**Comment by aaronjensen** [comment]
I can't. It'd make sense to prefer the annotation, but ultimately 90% of the time I get an autocomplete dialog I just want to type the thing I was already thinking faster. The annotations don't do much for me--but this could be because most of my recent work has been in more dynamic languages.

**Comment by stardiviner** [comment]
I checked the used company backends with command `company-diag` for `ret` (which returns two `return`):
```
Completions:
  #1=#("return" 0 1 (isProperty :json-false isKeyword t depth 0 name #1#)) ""
  #("return" 0 6 (company-backend company-keywords))
```

**Comment by dgutov** [comment]
> the used company backends

The output is just as I expected.

**Comment by stardiviner** [comment]
Is there a way to distinguish them? I know put a symbol in popup menu behind meta annotation is a bad idea. But something like that can let user distinguish them out. Or use different color?

**Comment by stardiviner** [comment]
Maybe we don't need to distinguish at all, just leave them as it is now? or merge them?

**Comment by dgutov** [comment]
> Is there a way to distinguish them?

Do we really need that? In this example, that wouldn't be helpful at all, I think.

**Comment by dgutov** [comment]
> just leave them as it is now? or merge them?

Merging is probably not an option. But we can remove one of them from the list.

**Comment by stardiviner** [comment]
> But we can remove one of them from the list.
I agree on this. How to decide which one to remove?
I think remove the candiate which has less properties.
For example, if `return` which comes from `company-tern`, can access doc with `[F1]`. But `company-keywords` can't. (they both don't have meta annotation.)
This is what I think.

**Comment by aaronjensen** [comment]
Or you could go by grouping order. Prefer the first.

btw, the difference between `:with` and not `:with` is unclear to me (this is unrelated to this thread, I just thought I'd mention it)

**Comment by dgutov** [comment]
> Or you could go by grouping order. Prefer the first.

That would conflict the current algorithm of keeping lines that differ only in annotations.

> the difference between :with and not :with is unclear to me

I don't know what to do with that statement. `:with` is documented in `company-backends`, and there's been a few discussions about it, see #79.

**Comment by aaronjensen** [comment]
> That would conflict the current algorithm of keeping lines that differ only in annotations.

I'm ok w/ that, I don't see much use for seeing two that differ only by annotation, but I could be missing something--I'm rather new to emacs and company-mode.

> I don't know what to do with that statement. :with is documented in company-backends, and there's been a few discussions about it, see #79.

#79 was very helpful, thank you. I get it now. I think when I was first trying to understand it I didn't look far enough.

**Comment by aaronjensen** [comment]
aside: would it be the right thing to pull request company-tern to return `nil` instead of `""` for no annotation? /cc @proofit404

**Comment by proofit404** [comment]
@dgutov @aaronjensen If this fix is necessary I will correct my package.

**Comment by dgutov** [comment]
> would it be the right thing to pull request company-tern to return nil instead of "" for no annotation?

That would only fix this specific case, and not the more general one that I brought up.

**Comment by dgutov** [comment]
> I don't see much use for seeing two that differ only by annotation

If the backend provides snippet expansion for arguments, they usually differ in resulting snippets. So the user can pick the method signature he needs, press RET, and get the arguments placeholders inserted.

**Comment by aaronjensen** [comment]
> If the backend provides snippet expansion for arguments

Ah, that's the part i was missing. And I'm guessing from the docs that we can't actually tell if it provides snippets until after completion when it calls `post-completion`. 

My vote would still be to remove them, preferring to keep the completions from the first-most backends in the group. Perhaps it could be a configuration option to aggressively dedupe or not. Alternatively, the algorithm itself could be a configuration option.

I could probably customize this myself right now w/ `company-transformers`, yeah?

**Comment by dgutov** [comment]
> I could probably customize this myself right now w/ company-transformers, yeah?

Yup.

**Comment by aaronjensen** [comment]
Is it possible for me to know the order of `company-backends` within a `company-transformer`? It looks like I can tell if it is a `:with` one with `low-priority`, but I'm not sure how to see overall order.

**Comment by dgutov** [comment]
I don't understand the question. `company-backends` is a list, you can look at its contents.

`company-backend` is the currently used backend; it can also be a list if it's a grouped one.

**Comment by aaronjensen** [comment]
sorry, I misread `company-sort-by-backend-importance`... I've not written any elisp. I'll figure it out.

That said, once I have a function that does what I want, would we still want to make a change to `company-mode`? Maybe at least coercing `""` to `nil`?

**Comment by dgutov** [comment]
> Maybe at least coercing "" to nil? 

Removing items without annotations when there's matching items with annotations should take care of the bigger problem better.

**Comment by dgutov** [comment]
Please try it out.

**Comment by dgutov** [comment]
@proofit404 This takes are of the issue in a general way, but I suppose you might still want to return `nil` in those completions, for the users of `company-mode` who install from GNU ELPA (the stable version), or in case we end up reverting this change.

**Comment by aaronjensen** [comment]
Thanks @dgutov, this seems to work for the case I pointed out. I'll give it a shot and report back if anything is funny about it. Thanks again!

**Comment by dgutov** [comment]
It seems #509 describes a solid counter-example to the current solution: leaving just the completions with annotations may leave only the completion by `company-yasnippet`, and the user might get unhappy when the seemingly only choice is to press RET and get snippet expansion.

Thoughts, anyone?

@proofit404 If nobody suggests anything better, please update `company-tern` as discussed.

**Comment by mola-T** [comment]
I think under most of the situations, people want the choices the be 'merged'. Because for most of the backends, they served a single purpose: completion. People hope to get the best completion option.

`company-yasnippet` is quite special as it serves another purpose: expansion. Does it consider as a special case?

**Comment by stardiviner** [comment]
Yes, `company-yasnippet` is special to deal with.

**Comment by dgutov** [comment]
`company-yasnippet` is indeed special, but in time, people might create other backends where the `post-command` is not always desirable. I'm not happy about the idea of having to document the best practices in this case. How do you even phrase the distinction between these backends and others?

On the other hand, the dabbrev backends are pretty special as well, in that they don't add annotations, and people seem to like pairing them with "smarter" backends. Which seems like an odd choice: if your backend is clever enough to show method arguments in annotations, why doesn't it provide completion for local variables as well?

Doesn't Tern include local variables in completions? @aaronjensen Why did you feel the need to pair it with `company-dabbrev`?

**Comment by aaronjensen** [comment]
@dgutov it does, but often I want to autocomplete words from other buffers or even other functions in my buffer (like if I'm defining a new local variable that has the same name as other functions). It also seems like tern isn't perfect and misses things. 

It seems like anything that has a post completion should not be merged. If it were possible to tell that, then this would have a somewhat easy solution I think.

**Comment by proofit404** [comment]
Main purpose of autocomplete tools like tern is reduce variants list to the minimum number according to the context. Maybe you can use `M-/` for cases where you want all possible words from emacs session?

**Comment by dgutov** [comment]
> It seems like anything that has a post completion should not be merged. If it were possible to tell that, then this would have a somewhat easy solution I think.

It's not easy to tell with 100% effectiveness, but most of the time if a completion has an annotation, it also has `post-completion` logic (or adding it would be appropriate).

If we go by that indicator, you're agreeing with my suggestion to revert the current fix and just make sure to never return empty strings as annotations, in `company-tern` or any other backends.

**Comment by aaronjensen** [comment]
@proofit404 I like what `M-/` gives me much of the time, but I'd still prefer it lived in a menu like company. `M-/` doesn't show a menu, doesn't show it automatically, and doesn't provide a way to go backwards. It's not great, in short. 

A common situation where company-tern falls short is in react components. If you're using `React.createClass` there are several functions like `setState` that you wouldn't have in `this.se<completion>` that you would want. You can hippie expand for that, yeah, but I don't want to have the mental overhead of switching between the two completion modes. 

Another case is when defining variables, `const wh<completion>`. I think that company-tern should probably not claim to be able to complete variable names, maybe this is a bug worth filing there? 

> It's not easy to tell with 100% effectiveness, but most of the time if a completion has an annotation, it also has post-completion logic (or adding some would be appropriate).

What would post completion logic be for `company-tern`? I didn't think that an annotation necessarily meant post completion logic. Or are you suggesting removing the annotation from tern? I may have missed some of that conversation.

> If we go by that indicator, you're agreeing with my suggestion to revert the current fix and just make sure to never return empty strings as annotations, in company-tern or any other backends.

Yes, I'd be fine w/ that as long as that meant that company-tern and company-dabbrev would return nil for annotations and therefore be merged. I don't mind the tern annotations, but I don't think they add too much value either.

**Comment by dgutov** [comment]
@aaronjensen I think you should report bugs to Tern. About `const wh<completion>`, though, why would you expect any completion there? Nobody knows what your new variable will be called.

> What would post completion logic be for company-tern?

As usual: snippet expansion of the function arguments. Or just adding parens around point if the function has no arguments.

> I didn't think that an annotation necessarily meant post completion logic. Or are you suggesting removing the annotation from tern?

It might indeed not mean post-completion logic if an annotation says "variable" or "keyword". Maybe those kind of annotations should not be used. Or maybe we'd keep them and live with the inconsistency.

In any case, showing two lines that almost mean the same but where one of them has an annotation should be less jarring than showing two seemingly identical lines, both without annotations.

**Comment by aaronjensen** [comment]
> why would you expect any completion there? Nobody knows what your new variable will be called.

In a typical programming session I very often type the same words over and over again. It's common to reuse variable names, use a variable name that appeared somewhere in another file, etc. It's even more common to reuse things that have been added to the code base recently, which is why I wrote [vim-recentcomplete](https://github.com/aaronjensen/vim-recentcomplete), which looks at unstaged git changes and git changes within the last half hour or so to populate your auto-complete. Think about a situation where you add a class to a css file and then go back to the html or react jsx file and type the class name. This is very common in my day-to-day programming. I've said it before, but the combination of recentcomplete and localcomplete in vim I miss a lot when I'm in emacs. It was very fast and often shockingly accurate.

> As usual: snippet expansion of the function arguments. Or just adding parens around point if the function has no arguments. 

Got it

> In any case, showing two lines that almost mean the same but where one of them has an annotation should be less jarring than showing two seemingly identical lines, both without annotations.

Yeah, I can see this. Ideally the annotation wouldn't need to be a proxy for what a completion fully expands to, but I understand that it's the proxy we have.

**Comment by dgutov** [comment]
> Think about a situation where you add a class to a css file and then go back to the html or react jsx file and type the class name.

OK, I see. This is the situation I resort to `M-/` as well, like @proofit404 recently recommended. Alternatively, you could bind `company-other-backend` to a key and make sure that `company-dabbrev-code` will be tried after the current one.

Do recentcomplete or localcomplete get to handle several backends somehow? Do those support annotations and/or post-completion? The more features we have, the harder it is to combine them all is a sensible fashion, unfortunately.

> Yeah, I can see this. Ideally the annotation wouldn't need to be a proxy for what a completion fully expands to, but I understand that it's the proxy we have.

Good. It would be possible to have a yet-another backend command that just returns non-nil if it's doing something non-trivial in `post-completion`, but that seems very non-elegant. Maybe after we transition to `completion-at-point-functions` as the backend variable (in some indeterminate future), we could look at whether the extra properties include `:exit-function`. Or we could find a better predicate by then.

Or do it in a yet another different way. For instance, some users prefer to have completions from different backends in a merged group to be sorted separately, not mixed together. If that solves the current usability problem, we can add a new keyword similar to `:sorted`. Let's call it `:sort-separately`; `company--multi-backend-adapter` would then pre-sort completions returned by each backend but avoid mixing them. Atom's completion seems to work this way, as one example.

**Comment by aaronjensen** [comment]
> Alternatively, you could bind company-other-backend to a key and make sure that company-dabbrev-code will be tried after the current one.

That's an interesting idea, but it still interrupts flow more than just typing the word that I'm going for. 

> Do recentcomplete or localcomplete get to handle several backends somehow? Do those support annotations and/or post-completion?

recentcomplete and localcomplete are backends. I used them with neocomplete which does support several backends based on a priority system. It also supports annotations of sorts, and it has a snippet backend that I believe requires its own expansion binding--so no generic postcompletion function AFAIK.

> Maybe after we transition to completion-at-point-functions as the backend variable

I'm not familiar with this, would this allow candidates to return metadata like annotations or other info along with it instead of a separate backend function?



> some users prefer to have completions from different backends in a merged group to be sorted separately, not mixed together.

Sorting and merging is something I've thought about a lot, it's a tricky thing. Typically I have preferred what you describe here--prioritizing the backends and grouping the results with their backend. The example from recentcomplete shows this, R is recentcomplete, L is localcomplete, S, I don't remember, but it was a different engine.

![](https://camo.githubusercontent.com/c6ba956dd2dacf4b1830d0a207cbe238b6267c48/687474703a2f2f73637265656e73686f74732d647833372e73332e616d617a6f6e6177732e636f6d2f6d6f6e6f736e61702f303156696d5f2d5f76696d5f323031342d31302d31315f31372d31322d34332e706e67)

I could see a world where there was something smarter that would boost words that appeared in multiple backends, but I think that's too much complication for what we're trying to solve here. To make a long story short, `:sort-separately` sounds like it'd be a good addition.

**Comment by dgutov** [comment]
> would this allow candidates to return metadata like annotations or other info along with it instead of a separate backend function?

What do you mean by "separate backend function"?

> I could see a world where there was something smarter that would boost words that appeared in multiple backends

Boost and merge, you mean? One could implement something like that using `company-transformers`, at the cost of somewhat larger overhead.

> To make a long story short, :sort-separately sounds like it'd be a good addition.

OK, I'll work on that.

**Comment by proofit404** [comment]
@aaronjensen Can you test new company-tern version?

**Comment by aaronjensen** [comment]
> What do you mean by "separate backend function"?

Sorry, I meant additional backend command, as you mentioned. I was imagining that the backend candidates command returning a map of candidate information (text, annotation, has-non-trivial-post-completion?) would be better than having a "yet-another backend command". I just had a thought thought that maybe it's the way it is because you don't necessarily need all the annotations for all candidates, just the ones you may display, so it could be more efficient to do them at separate times.

> Boost and merge, you mean?

Yes, exactly.



> OK, I'll work on that.

Thanks!

**Comment by dgutov** [comment]
> I just had a thought thought that maybe it's the way it is because you don't necessarily need all the annotations for all candidates, just the ones you may display

That's the idea, yes. auto-complete does it the other way, and I think it may be responsible for some performance problems with large lists.

**Comment by dgutov** [comment]
@aaronjensen

> To make a long story short, :sort-separately sounds like it'd be a good addition.

I've moved this to a new issue, since the original report can be addressed without it.

The commit that "fixed" this issue is now reverted, but with `company-tern` behaving better now, the duplicates in question should get removed correctly. Please let me know if it's not the case. Meanwhile, closing.

**Comment by aaronjensen** [comment]
Ok, will do. Thank you @dgutov
