### ISSUE TITLE
Get company-dabbrev to access other buffers?

### ISSUE THREAD

**Issue by emacsomancer** [company-mode/company-mode#433]
I don't seem to be able to get companymode to look at other buffers for dabbrev completion. (Using plain non-company hippie expand, I can get with behaviour without issue.)

Below are relevant bits from my .emacs, including ```(setq company-dabbrev-other-buffers 'all)``` which I thought should produce this behaviour.

In Org-mode and LaTeX buffers is where I particularly want this behaviour.  

Do I have something else set that's blocking this?

````
(require 'company)
(global-company-mode)
(setq company-idle-delay 0)
(setq company-transformers '(company-sort-by-occurrence))

;; Add yasnippet support for all company backends
;; https://github.com/syl20bnr/spacemacs/pull/179
(defvar company-mode/enable-yas t
  "Enable yasnippet for all backends.")

(defun company-mode/backend-with-yas (backend)
  (if (or (not company-mode/enable-yas) (and (listp backend) (member 'company-yasnippet backend)))
      backend
    (append (if (consp backend) backend (list backend))
            '(:with company-yasnippet))))

(setq company-backends (mapcar #'company-mode/backend-with-yas company-backends))

(setq company-dabbrev-other-buffers 'all)

(setq company-dabbrev-time-limit 5)

(setq company-dabbrev-downcase nil)

(setq company-dabbrev-code-everywhere t)
````

**Comment by dgutov** [comment]
Customize `company-dabbrev-code-modes`.

`company-dabbrev-other-buffers` affects `company-dabbrev`, not `company-dabbrev-code`.

**Comment by emacsomancer** [comment]
Is there any way to do the equivalent of ```company-dabbrev-code-other-buffers```? I end up with lots of hypenated words that I actually want to be able to complete on.

(Also, even just using ```company-dabbrev``` with ```company-dabbrev-other-buffers 'all``` doesn't seem to look at *all* other buffers, as it doesn't seem to look at my mail buffers, whereas ```hippie-expand``` can.)

**Comment by dgutov** [comment]
> Is there any way to do the equivalent of company-dabbrev-code-other-buffers?

`company-dabbrev-code-modes`?

> even just using company-dabbrev with company-dabbrev-other-buffers 'all doesn't seem to look at all other buffers

`company-dabbrev-ignore-buffers`?

You know you can `M-x customize-group company RET`, right?

**Comment by emacsomancer** [comment]
Yes, I know about customize-group, it's just sometimes easier to group things together in .emacs.

```company-dabbrev-ignore-buffers``` was indeed the key.

tried to get dabbrev-code-like functionality by redefining ```company-dabbrev-char-regexp``` as ```"\\sw\\|\\s_"```, which almost works except for cases when a hyphen or underscore occurs before the first 4 chars. So it'll catch "column-number" but not "wh-words".

**Comment by dgutov** [comment]
> I know about customize-group, it's just sometimes easier to group things together in .emacs

I meant using `customize-group` to discover new options.

> tried to get dabbrev-code-like functionality...

Why? Have you tried `(setq company-dabbrev-code-modes t)` first?

**Comment by emacsomancer** [comment]
If do ```(setq company-dabbrev-code-modes t)``` in ```customize-groups``` the State field says "mismatch".

**Comment by dgutov** [comment]
You don't put that line anywhere; you evaluate it via `M-:`.

Or, better yet, open the Customize buffer for `company-dabbrev-code-modes`, and choose "All modes" in the dropdown (this will only work if you've installed the most recent version of this package, from MELPA).

**Comment by emacsomancer** [comment]
> You don't put that line anywhere; you evaluate it via M-:.
Well, I put it in .emacs, which has the same effect as evaluate via M-:.

As far as I can tell, this doesn't work in the version of company-mode in melpa-stable. I upgraded to the melpa(-unstable) and there it works. And that latest version also has ```company-dabbrev-code-other-buffers``` which I don't recall being in the -stable version. Setting those two things almost works.

Here's the scenario(s):

Setting:
```
(setq company-dabbrev-other-buffers 'all)
(setq company-dabbrev-code-everywhere t)
(setq company-dabbrev-code-other-buffers (quote all))
(setq company-dabbrev-code-modes t)
(setq company-dabbrev-ignore-buffers "nil")
```
Gives me dabbrev-code matching across some buffers (but not my mail buffers, for instance), but does get me hyphenated-words.

Setting:
````
(setq company-dabbrev-other-buffers 'all)
(setq company-dabbrev-code-other-buffers (quote all)) ;; irrelevant
(setq company-dabbrev-ignore-buffers "nil")
````
Gets me matching across all buffers (including mail), but no hyphenated words.

**Comment by dgutov** [comment]
> Well, I put it in .emacs, which has the same effect as evaluate via M-:.

That sounds right. I don't see where you can get "Mismatch" doing that, though.

> I upgraded to the melpa(-unstable) and there it works.

Yes, sorry, I don't always remember when an option was added or changed. But you didn't specify using MELPA Stable either.

> And that latest version also has company-dabbrev-code-other-buffers which I don't recall being in the -stable version.

This variable, however, has been there for years. And the possible value `all` did too.

You probably want these settings:

```el
(setq company-ddabbrev-code-everywhere t)
(setq company-dabbrev-code-modes t)
(setq company-dabbrev-code-other-buffers 'all)
(setq company-dabbrev-ignore-buffers "\\`\\'")
```

However, it still won't work ideally everywhere, because `company-dabbrev-code` provider completions for the "symbol at point". And in major modes where hyphen is not a symbol constituent, the symbol at point will only be the part after the hyphen.

**Comment by emacsomancer** [comment]
>  That sounds right. I don't see where you can get "Mismatch" doing that, though.

I tried with ```M-:``` and it still reported mismatch in ```customize-group```.

>Yes, sorry, I don't always remember when an option was added or changed. But you didn't specify using MELPA Stable either.

Sorry, I wasn't complaining, just trying to report.

> This variable, however, has been there for years. And the possible value all did too.

For some reason I didn't spot it before.

> However, it still won't work ideally everywhere, because company-dabbrev-code provider completions for the "symbol at point". And in major modes where hyphen is not a symbol constituent, the symbol at point will only be the part after the hyphen.

I'll probably stick with plain ```company-dabbrev``` then. But that brings me back to trying to reconfigure the regex for dabbrev.  If I redefine ```company-dabbrev-char-regexp``` as ```"\\sw\\|\\s_"```, this almost works except for cases when a hyphen or underscore occurs before the first 4 chars. So it'll catch "column-number" but not "wh-words". Would there be any better regex than this to use?

**Comment by dgutov** [comment]
`"\\(\\sw\\|\\s_\\)"` would be a better option. Or even `"\\(\\sw\\|\\s_\\|_\\|-\\)"`.

But `company-dabbrev` still uses `company-grab-word` to determine the boundaries of text to complete, so you'll get surprising results after typing a non-word character.

That should be fixable. The plan is:

* Change `company-dabbrev--make-regexp` so that grouping is not necessary.
* Use `company-dabbrev-char-regexp` when determining the completion prefix.

**Comment by dgutov** [comment]
Pushed some changes. Now both `\\sw\\|\\s_\\` and `\\sw\\|\\s_\\|[-_]\\` should work fine, please try it out.

**Comment by emacsomancer** [comment]
Updated to latest version.

```(setq company-dabbrev-char-regexp "\\(\\sw\\|\\s_\\|_\\|-\\)")``` seems to work fine.

Many thanks for your help!  This is an incredibly useful package, even more so now with this fine tuning.

**Comment by dgutov** [comment]
You're welcome!

**Comment by dgutov** [comment]
Note that you don't have to use parens there anymore; I changed that too.

**Comment by emacsomancer** [comment]
I'm still trying to tweak the regex def a bit. I really want words to be able to include hyphens and apostrophes, but not ampersands or other symbols or numbers etc, because then the match is too zealous and pulls in things that I'd never want.

**Comment by dgutov** [comment]
Does `\\s_` match ampersands in some buffers? Try removing that part, e.g. use `\\sw\\|[-_']`.

That would still match numbers; to avoid that, use e.g. `[a-z-_']`.

**Comment by emacsomancer** [comment]
Thanks. I'm trying out using ```[a-z-_'/]``` (realised I do want forward slashes) and it seems to be working well.
