### ISSUE TITLE
Company throws a fit on certain arguments of `add-to-list`

### ISSUE THREAD

**Issue by luxbock** [company-mode/company-mode#434]
Using the latest version of `company` off MELPA (20151208.134).

Steps for reproduction:

Starting Emacs with `-Q`, calling `M-x package-initialize` and `install-package company` and then typing the following:
`(add-to-list 'foo`

I get the following stacktrace:

```
  backtrace()
  #[257 "ÁÂ!Ã ÁÄÀ@#À" [(add-to-list (quote lisp--witness--lisp)) message "--------------------------------------------------" backtrace "Compiler-macro error for %S: %S"] 5 "

(fn ERR)"]((wrong-number-of-arguments (3 . 5) 2))
  funcall(#[257 "ÁÂ!Ã ÁÄÀ@#À" [(add-to-list (quote lisp--witness--lisp)) message "--------------------------------------------------" backtrace "Compiler-macro error for %S: %S"] 5 "

(fn ERR)"] (wrong-number-of-arguments (3 . 5) 2))
  macroexp--compiler-macro(#[1283 "¢À=
```
which I cut short for brevity as it goes on and on. It seems to happen for whatever I type after the third letter after the quote character.

**Comment by dgutov** [comment]
It's a bug in Emacs 24. Should be fixed in the current development tree.

**Comment by dgutov** [comment]
Thanks for the report anyway.

**Comment by luxbock** [comment]
Thanks. I updated to the latest version and the issue is gone.
