### ISSUE TITLE
wrong-type-argument stringp nil when no completion candidates

### ISSUE THREAD

**Issue by sooheon** [company-mode/company-mode#436]
Similart to #30. To reproduce, emacs -Q and require only company-mode, and type a nonsense string such as "zzz". Company errors as follows:
<img width="707" alt="screen shot 2015-12-21 at 4 29 46 pm" src="https://cloud.githubusercontent.com/assets/302945/11934082/0fc586e2-a800-11e5-9945-71f87c16ea2e.png">

**Comment by dgutov** [comment]
Yes, sorry about that.

It's been fixed a few hours ago, please wait for the next MELPA build and update.
