### ISSUE TITLE
Support for fontified candidates?

### ISSUE THREAD

**Issue by cpitclaudel** [company-mode/company-mode#437]
Hi Dmitry,

Thanks for adding support for window offsets to doc-buffer; I've integrated it to company-coq, and it's extremely convenient.

I'd like to suggest another feature. Do you have strong feelings against allowing a limited amount of fontification in candidates? For example, I use `company-mode` extensively to complete yasnippet snippets (functions ("tactics") in the Ltac programming language that comes with Coq are written in a very inconsistent domain-specific language, so it's convenient to see various forms with holes, and details about what goes in these holes):

![Snippet completion](https://raw.githubusercontent.com/cpitclaudel/company-coq/master/img/tactic-completion-doc.png)

(note the snippet arguments in `@{...}`.

Wouldn't it be much nicer if company had support for fontified candidates? Here's a quick draft of what it might look like:

![screenshot from 2015-12-23 20 02 59](https://cloud.githubusercontent.com/assets/8181630/11996803/8497b9b4-aa6b-11e5-8402-a4ce96ebbd41.png)

I looked at the codebase a bit, and it seems that the reasonable place to implement this would be `company-fill-propertize`: instead of calling `add-text-properties` on `line` to add a face (and thus loosing the existing `faces` on the completion candidates), one could use `add-face-text-property`:

```elisp
(add-face-text-property 0 width '(inherit company-tooltip)
                        nil line)
(add-face-text-property margin common '(inherit company-tooltip)
                        nil line)
```

Of course one wouldn't want to unconditionally enable this (as candidates are sometimes obtained by just calling `buffer-substring` instead of `buffer-substring-no-properties`). We could add a type of command to backends maybe? Or the face property that company uses could be a `company-face` instead of `face` (not unlike `font-lock-face`, though `company-fill-propertize` would merge the `company-face` property with the tooltip face before inserting the text in the buffer)

What do you think? Thanks for your work on `company`!

**Comment by stardiviner** [comment]
Looks good.

**Comment by dgutov** [comment]
Hi Clément,

The feature sounds good.

I see you've already addressed my biggest reservation (completions coming from buffers). Adding a new backend command (like `post-render`) would be easiest from my side, but that would make backends responsible for how candidates are rendered in one particular frontend, which is not ideal, semantically.

Using `company-face` seems to be the next-easiest option. Should we allow the backend author to override the foreground or background colors this way, too?

Note: we'll use `font-lock-append-text-property` instead of `add-face-text-property` for compatibility with Emacs < 24.4.

**Comment by cpitclaudel** [comment]
Yay! I'm glad you like the feature, and I'm excited about using it in company-coq. I wasn't aware of `font-lock-append-text-property`, but it looks great.

One other option might be a boolean backend option `keep-faces`. Or maybe something more general such as `kept-text-properties`, which would tell company which properties of the candidates to keep or to erase. But `company-face` also sounds great to me, and maybe its good to keep this feature limited so that when we get GUI popups some of these can be supported there too.

I don't have strong opinions foregrounds and backgrounds. On the one hand I can't really imagine cases where overriding the background of the popup would be good, but on the other I trust that backend authors would probably make the right decisions.

Thanks again!

**Comment by dgutov** [comment]
Looking at the README in company-coq, you seem to be working on some kind of advanced magic. I'd be remiss not so support that. ;-)

> One other option might be a boolean backend option keep-faces.

That would work, but it has the same drawback as `post-render`: a backend would control how some _specific_ frontend works. That feels bad to me, somehow.

> Or maybe something more general such as kept-text-properties

Are there other text properties we might want to control that way?

> On the one hand I can't really imagine cases where overriding the background of the popup would be good, but on the other I trust that backend authors would probably make the right decisions.

We either allow overriding both foreground and background, or prohibit both. OK, let's go with the permissive option, for now.

**Comment by dgutov** [comment]
Pushed, please try it out. I'm going to keep it undocumented for now.

Thinking more about the subject, a good reason to implement this via a backend command instead, would be to defer the necessary backend logic until the last moment, and use it only as required, so that you have to apply `company-face` only to 10 strings or so at a time, instead of having to do that for all completions. Which I can imagine could be slower. Would you be able to take advantage of this optimization, or will you have to produce that information for all candidates in advance anyway?

Or if we use a backend command, which strings will we be allowed to pass to it? Should it be able to handle any rendered string as produced for display in any frontend (pseudo-popup, preview, echo, echo-strip-common)? Or will it take unmodified candidate and annotation strings instead?

**Comment by cpitclaudel** [comment]
Great, thanks a lot! I'll try it very soon.

> Would you be able to take advantage of this optimization, or will you have to produce that information for all candidates in advance anyway?

I could definitely take advantage of it, but it wouldn't be performance-critical for me: I already do some conversions and annotations while generating candidates, so I could just as well add the extra fontification at the same time (and even that is me being lazy: these conversions could be done once and for all and cached).

> Or if we use a backend command, which strings will we be allowed to pass to it? Should it be able to handle any rendered string as produced for display in any frontend (pseudo-popup, preview, echo, echo-strip-common)? Or will it take unmodified candidate and annotation strings instead?

Rendered strings sound a bit scary :) Could the backend call happen just before the frontend receives the string, so that the backend would get an occasion to propertize candidates just before they get fed to the frontend?

This is awesome work Dmitry, many thanks!

**Comment by dgutov** [comment]
> I could definitely take advantage of it

Good! So you'll simply add underlines for words that follow spaces and aren't keywords?

> but it wouldn't be performance-critical for me

I guess not. Still, it makes sense to plan for backends where it might be.

> Could the backend call happen just before the frontend receives the string, so that the backend would get an occasion to propertize candidates just before they get fed to the frontend?

Yup, that's the other option. We can call the command `pre-render`, and it'll take two arguments (`str` `annotation-p`). And if it returns nil, the default implementation will strip the string of the `face` property.

**Comment by cpitclaudel** [comment]
>> I could definitely take advantage of it
> Good! So you'll simply add underlines for words that follow spaces and aren't keywords?

More or less :) I'll detect things that are snippet like by regexp-matching for `@{...}`.

>> but it wouldn't be performance-critical for me
> I guess not. Still, it makes sense to plan for backends where it might be.

>> Could the backend call happen just before the frontend receives the string, so that the backend would get an occasion to propertize candidates just before they get fed to the frontend?
> Yup, that's the other option. We can call the command pre-render, and it'll take two arguments (str annotation-p). And if it returns nil, the default implementation will strip the string of the face property.

I think I might like this option better :) In particular because it allows one to take advantages on text properties already present on the string to fontify it. I use text properties extensively to keep information about candidates as I pass them to and receive them from `company (for example, I tag them with a `company-coq-snippet` property which I read back in `post-command` to insert the snippet, and with various bites of information to sort them).

**Comment by cpitclaudel** [comment]
Just tried it! It works beautifully (and it looks great)

![screenshot from 2015-12-26 18 53 30](https://cloud.githubusercontent.com/assets/8181630/12007377/10102a16-ac02-11e5-9d71-24c14e4647dc.png)

**Comment by dgutov** [comment]
So you found a use for changing the foreground color as well?

I fear that allowing to do that too easily we'll make life harder for certain groups of users (who will find that your chosen color of black doesn't work on their white-on-black color palette, for instance), and for theme authors who will have to also customize faces introduced by each new clever backend author.

**Comment by cpitclaudel** [comment]
No no, black is the default color :) It's just that company is highlighting fuzzy matches for `applyin` in red, but the normal color of popup text is black. Or did I misunderstand your question?

**Comment by dgutov** [comment]
Oh, I see. :) My bad, I haven't used a dark theme in a while, and forgotten the alternative popup colors.

**Comment by dgutov** [comment]
I've pushed the alternative approach to the branch `pre-render-backend-command`, please try it out.

It seemed simpler initially, but having to use `font-lock-prepend-text-property` in `company-fill-propertize`, to retain the properties set by the backend, led to changes in the faces hierarchy: what we did before using inheritance, is now achieved by setting `face` to a list of values.

I do like the result, but it might break some themes, or allow them to work with the latest version, but not with the current stable. Let's see if that happens. It also might break some non-conforming backends, because this is the first backend command that takes two arguments.

**Comment by dgutov** [comment]
@cpitclaudel Sorry, have you checked out the alternative branch by now?

**Comment by cpitclaudel** [comment]
Still working on it, sorry! Probably in a few minutes.

**Comment by dgutov** [comment]
No problem, just wanted to make sure we're on the same page: your latest commit that references this issue came after I pushed that branch, and it uses the feature (`company-face`) that we're backing out of.

**Comment by cpitclaudel** [comment]
Ok, just had a quick look with precomputed fontification: works great :) (amusingly, in that case, the backend just returns the same string for `pre-render` as it was passed). I'll try with on-the-fly fontification.

**Comment by cpitclaudel** [comment]
On-the-fly fontification works great too :) :+1:

**Comment by dgutov** [comment]
Thanks for checking. I'll take it to mean that the changes in faces haven't brought up any surprises on your side either. Will merge in a bit.

**Comment by cpitclaudel** [comment]
Indeed, everything looked fine on my end. Many thanks for implementing this new feature, and doing it so quickly!
