### ISSUE TITLE
Inifinite loop when driving company from macros

### ISSUE THREAD

**Issue by cpitclaudel** [company-mode/company-mode#439]
Hi there,

I'm trying to automatically generate screenshots of company-coq, and it's turning out to be harder than I thought :) I essentially want to automate the task of opening a Coq-mode buffer, setting the right variable, inserting some text, and taking a screenshot.

Everything is working mostly fine for regular examples, but when company is involved things get trickier. Here's a minimal example that runs in emacs -Q, with no need for anything related to `company-coq`:

```elisp
(package-initialize)
(toggle-debug-on-quit)
(global-set-key (kbd "<C-return>") #'company-manual-begin)

(with-current-buffer (get-buffer-create "*LOOP*")
  (set-window-buffer nil (current-buffer))
  (emacs-lisp-mode)
  (company-mode)
  (insert "(def")
  (execute-kbd-macro (kbd "<C-return> C-h")))
```

Running this snippet (e.g. with `emacs -Q --load example.el`) hangs emacs, as the `execute-kbd-macro` call never returns.

Investigating further shows that the `'doc-buffer` command of the backend gets called repeatedly by company: indeed, after waiting for a few seconds and pressing C-g, the *Messages* buffer contains:

```
Type C-x 1 to delete the help window. [279 times]
```

Is there a way to avoid this loop? Or am I doing something wrong?

Thanks!

**Comment by dgutov** [comment]
Hi!

It seems the problem is in `company--electric-do`: it uses `read-key-sequence-vector`, which returns an empty vector during macro execution, instead of waiting for input (dunno why). And we want to wait for the next key, so that as soon as the user calls an unexpected command, the documentation buffer gets hidden.

This works for me:

```el
(with-current-buffer (get-buffer-create "*LOOP*")
  (set-window-buffer nil (current-buffer))
  (emacs-lisp-mode)
  (company-mode)
  (insert "(def")
  (push (aref (kbd "C-h") 0) unread-command-events)
  (push (aref (kbd "<C-return>") 0) unread-command-events))
```

**Comment by cpitclaudel** [comment]
Hi Dmitry,

Thanks for the diagnostic! Setting `unread-command-events` does fix this problem, but it creates another one: there doesn't seem to be a way to tell emacs "process all input now" (the closest to this is `execute-kbd-macro`), so the effects of the keys that I pushed into `unread-command-events` are not visible until my entire script exits. That doesn't work, because I need to take multiple screenshots (see https://raw.githubusercontent.com/cpitclaudel/company-coq/experimental/img/smart-intros.gif for an example of an automatically generated screencast).

The only way to get this to work using `unread-command-events` seems to be to run whatever remains of the script as a lambda passed to `run-with-timer`. This kind of monad transformation is fine for simple snippets, but when I tried to apply it to the code I have everything became a horrible mess of macro expansions :/

Is there a way that I overlooked to get Emacs to process unread events before continuing with a script, except for sending the events through `execute-kbd-macro`?

**Comment by dgutov** [comment]
Unless you know how to make `read-key-sequence-vector` work during macro execution, maybe create your own copy of `company-show-doc-buffer` that will work without electric loop? You'll have to choose how you're going to hide the new buffer after.

**Comment by cpitclaudel** [comment]
> maybe create your own copy of company-show-doc-buffer that will work without electric loop?

That is actually a very good suggestion :) Thanks!
