### ISSUE TITLE
company error with company-tern

### ISSUE THREAD

**Issue by chenxs110** [company-mode/company-mode#441]
this error log.
Company: An error occurred in post-command
Company: frontend company-pseudo-tooltip-frontend error "Company: backend (company-tern :with company-yasnippet) error "Wrong number of arguments: (1 . 2), 3" with args (pre-render React nil)" on command post-command

**Comment by proofit404** [comment]
@chenxs110 This is company-tern problem, will fix ASAP.

**Comment by dgutov** [comment]
This should work now.

**Comment by proofit404** [comment]
I'm sorry I forgot to report here that fix was already released.
