### ISSUE TITLE
Wrong type argument: listp, pcomplete-completions-at-point

### ISSUE THREAD

**Issue by hpdeifel** [company-mode/company-mode#443]
I updated to the latest melpa version today and now get this error on every key-press in org-mode buffers. The backtrace says it occurs in `company--capf-workaround `.

I'm using emacs 24.5.1

**Comment by dgutov** [comment]
Do you have `(setq completion-at-point-functions 'pcomplete-completions-at-point)` anywhere, by any chance?

**Comment by hpdeifel** [comment]
Such a line was indeed part of my `org-mode` hook. Interesting that this did work at all.

Since the error was on my part, I'm closing the issue.

**Comment by dgutov** [comment]
It's *kind of* supported, actually. Like `run-hooks` docstring says, a hook variable can be set to just a function. But this is fairly uncommon.

Thanks for confirming, will fix soon.
