### ISSUE TITLE
new faces recently?

### ISSUE THREAD

**Issue by fommil** [company-mode/company-mode#444]
I've noticed that in the last few weeks you've introduced some new rules regarding the faces, it looks like you're now not showing the common parts of completion options.

This doesn't work so well in Scala and Java (via ENSIME) where the completions are often all the same and the difference is really in the namespace of the thing that is being imported. The result is basically that the selector disappears.

Is there any way to turn off this new behaviour? I tried looking through the commit logs to see what could have done this, but I didn't see anything relevant.

FYI, the relevant parts of my theme are https://github.com/fommil/darcula-theme-emacs/blob/master/darcula-theme.el#L140-L146

```elisp
 '(company-tooltip ((t (:inherit 'mode-line))))
 '(company-scrollbar-bg ((t (:inherit 'mode-line-inactive))))
 '(company-scrollbar-fg ((t (:inherit 'tooltip))))
 '(company-tooltip-selection ((t (:inherit 'highlight))))
 '(company-tooltip-common ((t (:inherit 'mode-line))))
 '(company-tooltip-common-completion ((t (:inherit 'mode-line))))
 '(company-tooltip-annotation ((t (:inherit 'mode-line))))
```

**Comment by dgutov** [comment]
It's https://github.com/company-mode/company-mode/commit/5bfbb05108a3f1f4482d4f3a55236359ced07c6a. The relevant part of that change is that the faces don't inherit that much from each other. Instead, they obtain priority from their placement in the `face` property value (which is now a list).

I'll take a look, thanks.

**Comment by dgutov** [comment]
But FWIW, the common part highlights just fine in the default theme.

**Comment by fommil** [comment]
I'd be able to add a new rule for the common part in my theme, but I don't know what face it has.

**Comment by fommil** [comment]
(when I do a `C-u C-x =` the company popup disappears)

**Comment by dgutov** [comment]
> company-tooltip-common-completion

No such face. What if you change that to `company-tooltip-common-selection`?

**Comment by fommil** [comment]
hold on, is this `company-tooltip-common-completion` and its a theme bug?

**Comment by dgutov** [comment]
`company-tooltip-common-selection` is only used in the currently selected line, so probably not. If I understand your complaint correctly.

**Comment by dgutov** [comment]
> (when I do a C-u C-x = the company popup disappears)

When the popup is displayed, you can evaluate `(overlay-get company-pseudo-tooltip-overlay 'company-display)`, and see the whole display string in the `*Messages*` buffer. But it's pretty messy.

**Comment by fommil** [comment]
sweet! Thanks for the speedy response, it was a bug in my theme. Uploading to MELPA now.

**Comment by fommil** [comment]
https://github.com/fommil/darcula-theme-emacs/commit/c479af16c3d2f8091e5c144be4620d1fd08252fc

**Comment by fommil** [comment]
also thought I'd add a wee bit of emphasis on the common part, that's a pretty nice feature :wink:

**Comment by dgutov** [comment]
Glad you resolved it. :bowtie:
