### ISSUE TITLE
annotation is drawn on top of selection color in popup

### ISSUE THREAD

**Issue by ptrv** [company-mode/company-mode#445]
Since commit 5bfbb05108a3f1f4482d4f3a55236359ced07c6a the annotation is drawn on top of selection marker.

Before commit:
![company-mode_popup](https://cloud.githubusercontent.com/assets/49775/12078427/1e5c444a-b212-11e5-9815-656f877e0fa7.png)

After commit:
![company-mode_popup2](https://cloud.githubusercontent.com/assets/49775/12078428/2b6cf7e2-b212-11e5-9d1b-ed72d21da1cc.png)

The screenshots are made with `company-ycmd` but I could reproduce the same with `company-clang`.

I am using Emacs 25.0.50.17

**Comment by dgutov** [comment]
Don't you think that the selection face should only change the background? The annotation face, in my opinion, should only set the foreground.

**Comment by dgutov** [comment]
And if the selection face changes the foreground, shouldn't the annotation face override it? It still makes sense to show where the annotation it, even in the currently selected completion.

**Comment by ptrv** [comment]
On the first sight it might be ok for the selection face to only change the the background, but the selection background color might not work with the annotation foreground color. I think an annotation selected face is also needed.

In my screenshots (zenburn theme) for example, I can image the annotation foreground not beeing readable enough on selection background.

**Comment by dgutov** [comment]
I can add `company-tooltip-annotation-selection` face, no problem.

But in the above example, if the annotation face gets a darker background, the result should have higher contrast. Which is usually more readable (until your eyes get tired, of course).

**Comment by ptrv** [comment]
I meant, that in the example the orange is not as good as the white color on selection background.

**Comment by dgutov** [comment]
I mean, how? If orange is good on grey background, it would only be easier to discern on the black one. The tastefulness of color combinations notwithstanding.

Either way, working on adding the face now.

**Comment by ptrv** [comment]
Ok, cool. Let's see how this will work (and look). Thanks!

**Comment by dgutov** [comment]
Pushed to the `company-tooltip-annotation-selection` branch. Does it work for you?

**Comment by ptrv** [comment]
Works perfectly.

Added the new face in zenburn and use the foreground color of annotation face and background color of selection face.

![company-mode_popup3](https://cloud.githubusercontent.com/assets/49775/12079314/482c49c4-b234-11e5-9e53-7a6ff5c9aa22.png)

**Comment by dgutov** [comment]
Great! Pushed to master.

Like mentioned, it would work the same if the theme didn't modify/set the background color of `company-tooltip-annotation` at all, but I guess that kind of change might be harder to do in some themes.
