### ISSUE TITLE
Make semantic backend display (and insert) function arguments

### ISSUE THREAD

**Issue by Gei0r** [company-mode/company-mode#448]
Hi,

when using the clang backend, company shows and inserts the function arguments. It even differentiates between overloaded versions of the same function/method:

![clang](https://cloud.githubusercontent.com/assets/16615274/12208037/90cf9dce-b64a-11e5-82fa-6e31d816fc6e.png)

Semantic only considers and inserts the function name (not the arguments):

![semantic](https://cloud.githubusercontent.com/assets/16615274/12208058/aed60a9c-b64a-11e5-8937-2be524630aee.png)

**Is it possible to get company-clang's behaviour for company-semantic?** I'd be willing to help in the implementation although I'm not terribly experienced in elisp, semantic or company.

**Comment by dgutov** [comment]
I don't have too much experience with either, so here's a question: if you've used both backends for some time, do their annotations usually match? Or at least have similar format.

If yes, then copying this behavior should be easy.

**Comment by Gei0r** [comment]
What exactly do you mean by "their annotations"? Do you mean their completion candidates?

Otherwise, how do I display them?

**Comment by dgutov** [comment]
Argument lists as displayed in the popup. These are annotations.

**Comment by Gei0r** [comment]
Unfortunately, semantic doesn't display arguments at all. The two screenshots above are the candidates from the same position.

**Comment by dgutov** [comment]
Right. But in this case it could be because it fails to keep track of overloaded functions (one `doSth` has an argument, and another doesn't).

In my tests, `company-semantic` does show arguments, at least for stdlib functions.

**Comment by Gei0r** [comment]
Oh, you're right. It "only" misses the overload.

**Comment by dgutov** [comment]
:)

It might be a problem in the backend, not Semantic itself. I'll look into it as well.

**Comment by dgutov** [comment]
It should work now. Please test.

**Comment by Gei0r** [comment]
Works. Thank you :+1:
