### ISSUE TITLE
Should company-call-backend-raw really capture user-errors?

### ISSUE THREAD

**Issue by cpitclaudel** [company-mode/company-mode#449]
Hi there,

`company-call-backend-raw` currently captures any error thrown by completion backends, and shows them with more information. This is a very convenient feature, especially when debugging an error on someone else's machine.

There is one case where it might be appropriate to raise the original error, however: when the code signaled a `user-error`, it's probably that it did want to forward the error to the user.

For example, in `company-coq`, some completions shouldn't be used before the prover is started. I could hide them, but that would diminish discoverability. Instead, I want them to always be available, but I want to signal a `user-error` if they are used at the wrong time. At the moment, the `user-error` is displayed thus:

```
company-call-backend-raw: Company: backend company-coq-master-backend error "Please start the prover before using smart completions" with args (post-completion intros! (guess names))
```

It would be nice if company let it through, so the user only saw

```
Please start the prover before using smart completions
```

What do you think?

**Comment by dgutov** [comment]
Hi Clément,

Generally speaking, backends aren't supposed to raise errors at all: `company-semantic` doesn't complain if `semantic-mode` is not on, and `company-clang` complains only once that there's no Clang executable in the system, they just pass the control to the following backends. Admittedly, the latter error could use a better notification mechanism, but I don't know which.

Are you're 100% sure that your users will never want to skip starting the prover and just use `company-dabbrev-code`, say, for a quick edit? If so, I suppose the request makes sense.

I wouldn't mind reviewing a patch. Apparently you'll have to rethrow `user-error`, catch it somewhere up the stack, and show the error message. The necessary code might turn out to be rather inelegant.

**Comment by cpitclaudel** [comment]
Indeed, the use case is a bit specific; it's not the backend so much as a candidate that's raising the error. The idea is that there are three candidates A B and C, but only A and B are really valid; C can be displayed, the `meta` and `doc-buffer` properties are interesting, but inserting it would require a call to a background process that's not running,

For that particular pattern, it would be nice if the error that the code raises when the entry is inserted wasn't caught and reformatted by company.

Does that make more sense?

**Comment by dgutov** [comment]
Hmm, so you don't even want to abort completion, but show the error and continue going?

Why not, say, show the necessary diagnostic information in the return values of `meta` and `doc-buffer` of C? If the background process is running, the user will see the desired info. If not--"Please start the prover".

Or is C invalid, and shouldn't be in the list at all in this situation? I'm not clear on this, from the description.

**Comment by cpitclaudel** [comment]
> Hmm, so you don't even want to abort completion, but show the error and continue going?

I do want to abort it: the way it works right now is fine; the only thing that would change would be that  *Please start the prover before using smart completions* would be displayed instead of *company-call-backend-raw: Company: backend company-coq-master-backend error "Please start the prover before using smart completions" with args (post-completion intros! (guess names))*

> Why not, say, show the necessary diagnostic information in the return values of meta and doc-buffer of C? If the background process is running, the user will see the desired info. If not--"Please start the prover".

That could be a nice idea; but there are more complex conditions being checked in the post-command, and these are not entirely predictable.

> Or is C invalid, and shouldn't be in the list at all in this situation? I'm not clear on this, from the description.

C is invalid in this context, but I want users to be aware of it. In a few other cases, C looks valid, but will fail for reasons that I can't really predict.

Generally speaking, I see the post-command as happening after company has completed its job, more or less; errors in the post-command won't affect company much, if at all, so it's not obvious to me that they should be caught and wrapped by company (that approach is of course perfectly fine for candidates, prefixes, etc; these commands are not expected to fail).

**Comment by dgutov** [comment]
> I do want to abort it: the way it works right now is fine; the only thing that would change would be that

Sorry, I don't understand. Abort the completion (hide the popup, disable company-active-map, etc), or not?

> C is invalid in this context, but I want users to be aware of it.

Aware of C, or aware of the prover not running?

> Generally speaking, I see the post-command as happening after company has completed its job, more or less; errors in the post-command won't affect company much, if at all

* Most of the work company-mode does happens in post-command-hook (see `company-post-command`).

* If a function in `post-command-hook` raises an error (i.e. doesn't catch all errors), Emacs removed that function from the hook.

**Comment by cpitclaudel** [comment]
Urgh, I used the wrong term: I meant `company`'s `post-completion`, not Emacs' `post-command`.

>> I do want to abort it: the way it works right now is fine; the only thing that would change would be that
>
> Sorry, I don't understand. Abort the completion (hide the popup, disable company-active-map, etc), or not?

When the error happen there's no popup anymore: the user has already made a choice by picking a candidate. The error is raised by the backend when company calls its `post-completion`.

>>  C is invalid in this context, but I want users to be aware of it.
>
> Aware of C, or aware of the prover not running?

Of C



>> Generally speaking, I see the post-command as happening after company has completed its job, more or less; errors in the post-command won't affect company much, if at all
>
> Most of the work company-mode does happens in post-command-hook (see company-post-command).
>
> If a function in post-command-hook raises an error (i.e. doesn't catch all errors), Emacs removes that function from the hook.

I'm really sorry for that mistake; I meant post-completion :/

**Comment by dgutov** [comment]
Can't the `post-completion` handler use `message` instead of `user-error`? Do we erase the current message somewhere right after?

**Comment by cpitclaudel** [comment]
Here's a rough draft of a what a patch would look like:

```diff
@@ -894,8 +894,11 @@ matches IDLE-BEGIN-AFTER-RE, return it wrapped in a cons."
       (if (functionp company-backend)
           (apply company-backend args)
         (apply #'company--multi-backend-adapter company-backend args))
-    (error (error "Company: backend %s error \"%s\" with args %s"
-                  company-backend (error-message-string err) args))))
+    (error
+     (if (and (eq (car args) 'post-completion) (eq (car err) 'user-error))
+         (signal (car err) (cdr err))
+       (error "Company: backend %s error \"%s\" with args %s"
+              company-backend (error-message-string err) args)))))
```

**Comment by cpitclaudel** [comment]
> Can't the post-completion handler use message instead of user-error? Do we erase the current message somewhere right after?

I think so, but I'm not entirely sure. Let me check.

**Comment by cpitclaudel** [comment]
I think we do erase the message:

```elisp
(defun message-in-post (command &optional arg &rest ignored)
  "Message in post-completion."
  (interactive (list 'interactive))
  (pcase command
    (`interactive (company-begin-backend 'message-in-post))
    (`prefix "")
    (`candidates (list "a" "b" "c"))
    (`post-completion (message "Oops"))))
```

**Comment by cpitclaudel** [comment]
That being said I can indeed move that logic into company-coq, though it's not perfect (https://github.com/cpitclaudel/company-coq/commit/d44658cd9a0ae39d31a2354eb786773b30b0849c)

**Comment by dgutov** [comment]
Yeah, one more timer usually helps. ;)

> Here's a rough draft of a what a patch would look like:

Have you tried it out? It seems we erase that message because `company-cancel` calls `(company-echo-cancel t)` at the end.

Catching `user-error` after that, or globally saving the error message to show at the end... neither seems perfect to me either.

**Comment by cpitclaudel** [comment]
>> Here's a rough draft of a what a patch would look like:
>
> Have you tried it out? It seems we erase that message because company-cancel calls (company-echo-cancel t) at the end.

Yup, seems to work fine for me with this example backend at least:

```
(defun message-in-post (command &optional arg &rest ignored)
  "Message in post-completion."
  (interactive (list 'interactive))
  (pcase command
    (`interactive (company-begin-backend 'message-in-post))
    (`prefix "")
    (`candidates (list "a" "b" "c"))
    (`post-completion (user-error "Oops"))))
```

**Comment by dgutov** [comment]
Indeed, its works, because the error bubbles up after the `unwind-protect` in `company-cancel`. Still, I can't say that I'm fond of special-casing `post-completion` in `company-call-backend-raw` like that.

It seems I can make `message` work in `post-completion` work rather cheaply. Please take a look.

**Comment by cpitclaudel** [comment]
Works perfectly, thanks!
