### ISSUE TITLE
company-clang doesn't work for c++11 style

### ISSUE THREAD

**Issue by phamhm** [company-mode/company-mode#452]
I noticed that company-clang will fail to autocomplete for *auto* variable: 

```c++
auto v1 = std::vector<int> {};
v1.   <= will issue the error "clang failed with error 1"
```

When I modify the company-clang.el directly to add in **-std=c++11**, the code above will auto complete. 

```Lisp
(defsubst company-clang--build-complete-args (pos)
  (append '("-fsyntax-only" "-Xclang" "-code-completion-macros" "-std=c++11")
```

Is there a way to add the flag in my init file instead of direct modifying of company-clang.el?

**Comment by syohex** [comment]
How about following configuration ?

```lisp
(custom-set-variables
 '(company-clang-arguments '("-std=c++11")))
```

**Comment by phamhm** [comment]
that works very well, thank you so much.

**Comment by dgutov** [comment]
:+1:
