### ISSUE TITLE
Pressing `C-h` isn't always sufficient to show the doc buffer

### ISSUE THREAD

**Issue by cpitclaudel** [company-mode/company-mode#454]
Hey Dmitry,

Given the following example, pressing <kbd>M-x c-h-twice RET C-h</kbd> shows the doc buffer. Pressing <kbd>C-w</kbd> after that shows the location buffer as expected. However, pressing <kbd>C-h</kbd> again after that doesn't do anything; one needs to press it twince for te doc buffer to appear. IOW, the key sequence to toggle between location buffer and docs buffer is <kbd>C-w C-h C-h C-w C-h C-h C-w C-h C-h</kbd> etc.

```elisp
(defun c-h-twice (command &optional arg &rest ignored)
  (interactive (list 'interactive))
  (pcase command
    (`interactive (company-begin-backend 'c-h-twice))
    (`prefix "")
    (`candidates (list "a" "b" "c"))
    (`doc-buffer (company-doc-buffer "Docs"))
    (`location (cons (company-doc-buffer "Location") 1))))
```

Is this expected? Did I do something wrong? This happens in Emacs 25.

**Comment by dgutov** [comment]
I see it too. It happens, in part, because `C-h` is a poor choice for this command. If you change the binding of `company-show-doc-buffer` in `company-active-map` to, say, `C-d`, switching back and forth will work as expected.

With `f1` used, apparently the `read-key-sequence-vector` call in `company--electric-do` waits for you to press another key instead of returning `[f1]` to be interpreted in the current keymap.

There might be a solution to this, but I'd prefer if we simply picked a different binding for this command. And then somehow made `C-h k` work even when `company-active-map` is active.

Regarding the binding, though, I'm not sure what to pick: `C-d` is easy, but the user might want to use `forward-delete` even when the popup is displayed.

**Comment by cpitclaudel** [comment]
Indeed, changing the binding works :) Is Emacs treating C-h specially?

I do like that binding though; if only because it's easy to memorize. In addition to looking into alternatives, maybe we could look into why Emacs is special-casing C-h?

It would be nice to be able to run C-h k  in company's active map, but that's not excessively useful, insofar as it wont give you all possible keys; meanwhile, the documentation of company-mode does :)

**Comment by dgutov** [comment]
> In addition to looking into alternatives, maybe we could look into why Emacs is special-casing C-h?

I'll take a patch. :)

**Comment by dgutov** [comment]
> Is Emacs treating C-h specially?

You can look at the echo area at that time. It says `f1 (Type ? for further option)-`.

**Comment by cpitclaudel** [comment]
Cool, thanks for the pointers. I'll look into it!

**Comment by cpitclaudel** [comment]
I'm confused by Emacs' behaviour here. Can you make sense of the fact that the following trick fixes the problem?

```elisp
(emacs-lisp-mode)

(defvar c-h-map
  (let ((keymap (make-sparse-keymap)))
    (define-key keymap (kbd "C-h") '(lambda () (interactive)))
    keymap))

(define-minor-mode c-h-mode
  "Captures C-h."
  :keymap c-h-map)

(company-mode)

;; At this point two presses are needed on C-h

(c-h-mode)

;; At this point a single press on C-h is enough
```

**Comment by cpitclaudel** [comment]
This is really surprising. When company calls read-key-sequence-vector, Emacs waits for a full (non-prefix) sequence. It looks for that sequence using the `active_maps` function in `keyboard.c`. That function calls `current_active_maps`, which in turn calls `current_minor_maps`, which does take into account the `emulation_alists` set by company. I don't see why it doesn't find the `C-h` that company registers.

**Comment by dgutov** [comment]
> I don't see why it doesn't find the C-h that company registers.

I don't have any idea either. `C-h` is a kind of special prefix, but that's all I can remember seeing on the mailing lists. I haven't read the respective C code.
