### ISSUE TITLE
Small error in `company--posn-col-row`?

### ISSUE THREAD

**Issue by cpitclaudel** [company-mode/company-mode#455]
Hey Dmitry,

I've had reports of users running into issues when pasting text into an Emacs 24 tty buffer with company enabled (which I guess is not too surprising, given that pasting without bracketed paste support is a nightmare).

The issue manifests itself as follows: user paste test, and company spills out a large number of messages saying 

```
Company: An error occurred in post-command
Company: Front-end company-pseudo-tooltip-unless-just-one-frontend error "Wrong type argument: number-or-marker-p, nil" on command post-command
```

Here's a backtrace, obtained thanks to the magic of https://lists.gnu.org/archive/html/emacs-devel/2010-07/msg01410.html:

```
Debugger entered--Lisp error: (wrong-type-argument number-or-marker-p nil)
  1+(nil)
  (company-pseudo-tooltip-show (1+ (cdr col-row)) col company-selection)
  (let* ((col-row (company--col-row pos)) (col (- (car col-row) column-offset))) (if (< col 0) (progn (setq col 0))) (company-pseudo-tooltip-show (1+ (cdr col-row)) col company-selection))
  company-pseudo-tooltip-show-at-point(21070 3)
  company-pseudo-tooltip-frontend(post-command)
  company-pseudo-tooltip-unless-just-one-frontend(post-command)
  funcall(company-pseudo-tooltip-unless-just-one-frontend post-command)
  (let ((frontend (car --dolist-tail--))) (funcall frontend command) (setq --dolist-tail-- (cdr --dolist-tail--)))
  (while --dolist-tail-- (let ((frontend (car --dolist-tail--))) (funcall frontend command) (setq --dolist-tail-- (cdr --dolist-tail--))))
  (let ((--dolist-tail-- company-frontends)) (while --dolist-tail-- (let ((frontend (car --dolist-tail--))) (funcall frontend command) (setq --dolist-tail-- (cdr --dolist-tail--)))))
  (progn (let ((--dolist-tail-- company-frontends)) (while --dolist-tail-- (let ((frontend (car --dolist-tail--))) (funcall frontend command) (setq --dolist-tail-- (cdr --dolist-tail--))))))
  ad-Orig-company-call-frontends(post-command)
  (with-no-warnings (ad-Orig-company-call-frontends command))
  (setq ad-return-value (with-no-warnings (ad-Orig-company-call-frontends command)))
  (condition-case err (setq ad-return-value (with-no-warnings (ad-Orig-company-call-frontends command))) ((debug error) (signal (car err) (cdr err))))
  (let (ad-return-value) (condition-case err (setq ad-return-value (with-no-warnings (ad-Orig-company-call-frontends command))) ((debug error) (signal (car err) (cdr err)))) ad-return-value)
  company-call-frontends(post-command)
  #[0 "`\232\204\f
```

This seems to come from this code:

```elisp
(defun company--posn-col-row (posn)
  (let ((col (car (posn-col-row posn)))
        ;; `posn-col-row' doesn't work well with lines of different height.
        ;; `posn-actual-col-row' doesn't handle multiple-width characters.
        (row (cdr (posn-actual-col-row posn))))
    (when (and header-line-format (version< emacs-version "24.3.93.3"))
      ;; http://debbugs.gnu.org/18384
      (cl-decf row))
    (cons (+ col (window-hscroll)) row)))
```

Indeed the docs of `posn-actual-col-row` say:

```
Return nil if POSITION does not contain the actual position; in that case
‘posn-col-row’ can be used to get approximate values.
```

Here's a repro; my Emacs didn't like too much the many error messages, so it complained, well, graphically:

![screenshot from 2016-01-13 02 19 20](https://cloud.githubusercontent.com/assets/8181630/12287634/1843dc3a-b99c-11e5-981d-9499672426e1.png)

* emacs -Q -nw
* Eval the following in a clean buffer:
```
(defun duplicator (command &optional arg &rest ignored)
  (interactive (list 'interactive))
  (pcase command
    (`interactive (company-begin-backend 'duplicator))
    (`prefix (company-grab-word))
    (`candidates (list (concat arg arg) (concat arg arg arg)))))

(company-mode)
(setq company-backends '(duplicator))
(setq company-idle-delay 0)
```
* Paste the following (right click -> paste)
```
AAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAA
```

On my machine, this causes some sort of infinite loop that spams the minibuffer with error messages. Pressing C-g enthusiastically does make it end after a while.

Can I help diagnose this further?

**Comment by dgutov** [comment]
Hi Clement,

Thanks for the report. I've pushed a change that gets rid of the error.

The long paste, however, ends up inserting far more text than I expected (though not the gibberish you have on the screenshot). Probably because it contains newlines, and those end up being interpreted as `RET` by company-mode, and the backend doubles the input each time? Not sure what to do about that. In any case, bracketed paste doesn't seem to work in my terminal.

> Here's a backtrace, obtained thanks to the magic of

What did you end up doing? `company-call-frontends` uses `condition-case-unless-debug`, so I'd think it would be enough to just enable debug-on-error.

Note that setting `company-idle-delay` to 0 is basically asking for trouble: you'd get the same performance with 0.01, but no problems like this one.

**Comment by cpitclaudel** [comment]
Thanks Dmitry!

The fix works great.

> The long paste, however, ends up inserting far more text than I expected (though not the gibberish you have on the screenshot). Probably because it contains newlines, and those end up being interpreted as RET by company-mode, and the backend doubles the input each time? Not sure what to do about that. In any case, bracketed paste doesn't seem to work in my terminal.

I think your analysis is right, and I don't think there's anything we can do about it. Hopefully bracket paste will become more common and everything will be fine.

> What did you end up doing? company-call-frontends uses condition-case-unless-debug, so I'd think it would be enough to just enable debug-on-error.

I don't think `debug-on-error` would be enough, as the debugger usually doesn't start for errors in post-command hooks; or does it?

> Note that setting company-idle-delay to 0 is basically asking for trouble: you'd get the same performance with 0.01, but no problems like this one.

Thanks for pointing this out, that's a very good point. Indeed, changing that setting fixes everything :)

I'm in favor of calling this fixed now :)

**Comment by dgutov** [comment]
> as the debugger usually doesn't start for errors in post-command hooks; or does it?

It usually does, since 24.4 or so. But we have to use `condition-case-no-debug` inside the hook, so that if `debug-on-error` is off, the error is caught instead.

> I'm in favor of calling this fixed now :)

:boom:

**Comment by cpitclaudel** [comment]
> It usually does, since 24.4 or so. But we have to use condition-case-no-debug inside the hook, so that if debug-on-error is off, the error is caught instead.

Ah, I see! I was using 24.3 for testing, since my other Emacs (25) didn't have the issue thanks to bracketed paste.

Thanks again for the quick fix!
