### ISSUE TITLE
(wrong-type-argument sequencep t) in `company-update-candidates`

### ISSUE THREAD

**Issue by cpitclaudel** [company-mode/company-mode#456]
Hi Dmitry,

I ran into another issue while doing automated testing of `company-coq`, but I haven't got a repro yet:

```
Debugger entered--Lisp error: (wrong-type-argument sequencep t)
  company-update-candidates(t)
  company--search-update-predicate("")
  company-search-mode(0)
  company-cancel(unique)
  company--begin-new()
  company--perform()
  company-auto-begin()
  company-manual-begin()
  funcall-interactively(company-manual-begin)
  call-interactively(company-manual-begin nil nil)
  command-execute(company-manual-begin)
```

I'll update this report when I have a repro. Does the backtrace make sense to you?

**Comment by cpitclaudel** [comment]
Here's a repro:

```
(defun test-backend (command &optional arg &rest ignored)
  (interactive (list 'interactive))
  (pcase command
    (`interactive (company-begin-backend 'test-backend))
    (`prefix (company-grab-word))
    (`candidates (list "nsum"))))

(setq-local company-backends '(test-backend))
```

Then type `nsu`, wait for a completion, and type the final `m`

**Comment by dgutov** [comment]
Seems to be a side-effect from the fix for #449. :( Will look into rewriting it in a different way.

**Comment by cpitclaudel** [comment]
Aww, sorry about that :/ Thanks for all your efforts Dmitry. I was already impressed by the quality of `company-mode`, but I'm even more impressed by your qualities as the maintainer.

**Comment by dgutov** [comment]
Thank you for the kind words, but really, for the last year and more I've only been giving this project minor amount of attention, due to other commitments/priorities. Hence the stalling wishlist issue, and the lack of tests which could have caught this bug automatically.

**Comment by cpitclaudel** [comment]
I must be lucky then :) The one cool feature that I wanted was implemented in less than a week ^^

**Comment by dgutov** [comment]
Well, to be fair, `pre-render` took relatively moderate effort, compared to what extracting popup.el-like package will, or making snippet expansion work for a sole-and-complete candidate.
