### ISSUE TITLE
`company-files` fails in python mode because of`dabbrev` settings in elpy

### ISSUE THREAD

**Issue by vspinu** [company-mode/company-mode#463]
In python-mode with elpy  the following list doesn't allow for file completions:
 
```
(setq-local company-backends '((company-dabbrev-code company-gtags company-etags company-keywords)
					                  company-oddmuse company-files company-dabbrev))
```
I tracked it down to `company-dabbrev-code` because the following works:

```
(setq-local company-backends '((company-gtags company-etags company-keywords) 
							   company-oddmuse company-files company-dabbrev))
````

The problem comes from the `t` value of `company-dabbrev-code-everywhere` which a very helpful elpy sets [here](https://github.com/jorgenschaefer/elpy/blob/master/elpy.el#L3178-L3180).

While I can fix this myself,  my question is whether `company-files` should have higher priority than tags by default? AFAIC it should be very much up front the list.

cc @jorgenschaefer

**Comment by dgutov** [comment]
You mean have it come in an element before the dabbrev-code, etags, and keywords group?

How sure are we that in all contexts where `company-files` applies, the user won't want to use a completion from etags or dabbrev-code instead?

I know that `company-files` is in a disadvantageous position, but I've been hesitant to promote it because it's less universal than one might expect. For instance, it seems less powerful than the built-in completion-file-name-table, and I don't exactly know why `completion--file-name-table` is different, but `company-files` definitely doesn't do that. Or see `comint--complete-file-name-data`, which also uses `completion-table-with-quoting`.

**Comment by vspinu** [comment]
> How sure are we that in all contexts where company-files applies, the user won't want to use a completion from etags or dabbrev-code instead?

`company-files` has quite a restrictive prefix (`company-files--grab-existing-name`). It's hard to imagine a use case when one would need a tag with all those restrictions. In any case it's a small price to pay IMO.

Currently, if backend's prefix matches, the completion chain is not getting to the next backend even if it doesn't produce any completions. Isn't this too restrictive for synchronuous backends?  

> For instance, it seems less powerful than the built-in completion-file-name-table, 

How do you know that? Do you have use cases when company-files fail except those peculiar tramp prefixes? 

I am personally very happy with `company-files` and haven't experienced problems with it so far, nor on local, nor on remote machines.

**Comment by dgutov** [comment]
> company-files has quite a restrictive prefix (company-files--grab-existing-name).

It's a tricky prefix, as well. I wonder if it has any undiscovered slow cases.

> In any case it's a small price to pay IMO.

Ok, let's try it out.

> Do you have use cases when company-files fail except those peculiar tramp prefixes?

It fails with peculiar tramp prefixes? I don't get to use it much, because it don't get to write file names with any regularity. `completion-file-name-table` does look more complex, and apparently also more optimized (see "Brute-force speed up" comment there).

> Currently, if backend's prefix matches, the completion chain is not getting to the next backend even if it doesn't produce any completions.

It's a question of semantics (which I've answered many times in this issue tracker already). If I write a function call, and I have a decent backend for the current language, and I make a mistake in the name, I _don't_ want completion to fail over to sloppy backends like dabbrev, which can show word-based completions, and hide my mistake until later.

**Comment by dgutov** [comment]
> I am personally very happy with company-files and haven't experienced problems with it so far

What kinds of files do you use it with, by the way?

**Comment by vspinu** [comment]
> It fails with peculiar tramp prefixes?

Actually not quite. Things like "/ssh:machine:~/" don't work only if there is no open connection. They do work otherwise.  

> What kinds of files do you use it with, by the way?

Standard local and remote files, simlinked or not. All of them work as expected, admitedlly unbearably slow on remotes :( 

> does look more complex, and apparently also more optimized (see "Brute-force speed up" comment there).

I see a couple of places when one can achieve a speedup:

 - This [`company-files--connected-p`](https://github.com/company-mode/company-mode/blob/ada2ede3ec75235ef0a6721e526b2fc94284093e/company-files.el#L77) seems to be redundant. If parent directory is "connected" then it's children should be and the check for parent has been done in `company-files--grab-existing-name` during the prefix match.

- You are right about this [`file-directory-p`](https://github.com/company-mode/company-mode/blob/ada2ede3ec75235ef0a6721e526b2fc94284093e/company-files.el#L79). It's very slow because it checks for actual directories and simlinks. I think it's safe to replace it with brute force check for ending "/", just as `completion-file-name-table` does it.

- This [children lookup](https://github.com/company-mode/company-mode/blob/ada2ede3ec75235ef0a6721e526b2fc94284093e/company-files.el#L81) is super expensive on remotes. I propose to drop this loop on remotes and maybe even on locals with > 100 directories in it. Not having children is a small price to pay for considerable speedup. 

- this [check](https://github.com/company-mode/company-mode/blob/ada2ede3ec75235ef0a6721e526b2fc94284093e/company-files.el#L85) can be done once.

- this [caching](https://github.com/company-mode/company-mode/blob/ada2ede3ec75235ef0a6721e526b2fc94284093e/company-files.el#L74) could be better by including caching for parent directories. It's a very common situation when you change /aaa/bbb/cc, to /aaa/bbb within the same edit. No need to re-fetch /aaa/bbb for the second time if you already been there.

What do you think? I can propose a pull if you like the idea.

**Comment by dgutov** [comment]
> Things like "/ssh:machine:~/" don't work only if there is no open connection.

Is that unexpected? https://github.com/company-mode/company-mode/issues/301

> Standard local and remote files, simlinked or not. All of them work as expected, admitedlly unbearably slow on remotes :( 

I meant, what files you write those file name is? In my work, I usually don't reference files on the current file system. Or if I do (in the import statements), those references don't start with `./` or `/`.

> This company-files--connected-p seems to be redundant.

The prefix can be local, and only some of the completions might be remote: https://github.com/company-mode/company-mode/issues/347 This check is probably not particularly expensive anyway.

> I propose to drop this loop on remotes and maybe even on locals with > 100 directories in it. Not having children is a small price to pay for considerable speedup. 

Sounds good to me. I'm not sure why we insert the children in the first place. Maybe @nschum would like to comment on that.

> this caching could be better by including caching for parent directories. It's a very common situation when you change /aaa/bbb/cc, to /aaa/bbb within the same edit.

Do you propose to make the cache an alist? That could be fine, but it'll also increase the odds of the cache getting stale.

> What do you think? I can propose a pull if you like the idea.

Sure, please go ahead.

**Comment by vspinu** [comment]
> I meant, what files do you write those file names in? 
Mostly with R, loading files from csv or serialized binaries for data analytics or sourcing code files.

> The prefix can be local, and only some of the completions might be remote: #347 

I see. This part still could be optimized a bit by checking only for directories. Or it could be dropped completely if you decide to drop children completion altogether.

> I'm not sure why we insert the children in the first place.

Sometimes it's useful if the children directory has few files. I can surely leave without it.

> Do you propose to make the cache an alist? 

Yes. A very small one. You keep cache as long as you edit the same path. If you turn to a new path the whole cache is invalidated.

**Comment by dgutov** [comment]
> This part still could be optimized a bit by checking only for directories.

It could. But is the check actually expensive enough for us to worry about it?

> Or it could be dropped completely if you decide to drop children completion altogether.

I'd prefer not to drop it without @nschum signing off on that, but your initial suggestion regarding it seems very appealing.

> You keep cache as long as you edit the same path. If you turn to a new path the whole cache is invalidated.

Sounds good.

**Comment by vspinu** [comment]
> But is the check actually expensive enough for us to worry about it?

Maybe not. I will benchmark these functions on a small remote.

> I'd prefer not to drop it without @nschum signing off on that, 

There is actually a good reason for having it right now because of the #464.

**Comment by vspinu** [comment]
> Ok, let's try it out.

An alternative would be to move `company-dabbrev-code` at the end, just before `company-dabbrev`.

**Comment by dgutov** [comment]
> An alternative would be to move company-dabbrev-code at the end, just before company-dabbrev.

That would be something elpy could do.

(Gotta run now.)

**Comment by nschum** [comment]
> I'm not sure why we insert the children in the first place. Maybe @nschum would like to comment on that.

I don't remember a specific reason. Having the whole file tree available would be ideal, of course, (for search and such). I probably considered one level to be a reasonable performance tradeoff.

I did not think about remote files at all. :) I also didn't have an SSD in early 2009. Today I would probably have added a very low time limit and tried to get as much of the tree as possible. That might even get me the whole tree on an SSD, maybe one level on the local network and zero children over the internet.

But I wouldn't mind seeing it dropped, either.

**Comment by dgutov** [comment]
> Having the whole file tree available would be ideal, of course, (for search and such).

Emacs's completion tables have a somewhat elegant answer for that, using the notion of "boundaries". When the completion table supports it (`completion-file-name-table` does): the user can type `/u/l/c`, and Emacs will match every path segment separately (and merge the results from different directories).

But another reason why `company-files` listing files in subdirectories is handy, it also resolves the problem of continuing the input past the immediate subdirectories: for remote paths, like currently implemented at my request, after the user picks a directory, they might have to type `/` to see the completion window again.
