### ISSUE TITLE
issues with `company-files`

### ISSUE THREAD

**Issue by vspinu** [company-mode/company-mode#464]
There are some issues with directory completions on my system:

- the completions of directories are often not proposed with trailing "/". That means you need to type it yourself. 
- when you complete such a directory and type "/" you don't get the completions. The funny part is that if you delete trailing "/" and type it again you start getting the completions. 
- sometimes directories do have trailing "/" and if you complete that directory, company-files is not auto-restarted, so that you need to type initial letters, or delete / and re-type it again.

I am looking into these inconsistencies right now.

**Comment by dgutov** [comment]
> the completions of directories are often not proposed with trailing "/". That means you need to type it yourself

Sometimes you want to type the directory name with a slash, sometimes not. Isn't that right?

The inconsistencies, of course, deserve investigation.

> sometimes directories do have trailing "/" and if you complete that directory, company-files is not auto-restarted

That's more or less by design: if you pick a completion, company-mode remembers the current position as "done", and doesn't try to initiate completion automatically on it. Not to mention that the `this-command` is not `self-insert-command` at that time. Generally, in order not to exit completion, you'd have to use `company-complete-common` there (and even that command could exit completion if there's just one option).

**Comment by vspinu** [comment]
> The inconsistencies, of course, deserve investigation.

I am fixing this. It comes from two distinct paths that company-files--directory-files can take. One returns slashes another one not. 

We can achieve quite some optimization by dropping `file-directory-p` and checking for trailing slash. So I am now always return directories with slash. 

> Sometimes you want to type the directory name with a slash, sometimes not. Isn't that right?

I don't think so. It never matters. All readers are smart enough to recognize a directory irerspective of the slash.

>  Generally, in order not to exit completion, you'd have to use company-complete-common 

Hm. Do you say that it's not possible currently to re-initialize the completion programaticaly? The problem is that if you don't have children, you don't have a common part.

**Comment by vspinu** [comment]
BTW, I don't think this [check](https://github.com/company-mode/company-mode/blob/ada2ede3ec75235ef0a6721e526b2fc94284093e/company-files.el#L59) is a right way to go.

It effectively doubles the completion time. For my remote's home dir with only 40 files this check takes 0.2 seconds. Of course we can try to optimize it out, but I doubt its usefulness in the first place. I am getting loads of junk from dabbrev if it gets through:

![company](https://cloud.githubusercontent.com/assets/1363467/12702217/319baf84-c822-11e5-86ba-c928b602ca99.png)

**Comment by dgutov** [comment]
Which check is that? Line 59 is empty.

**Comment by dgutov** [comment]
> Do you say that it's not possible currently to re-initialize the completion programaticaly?

I suppose, you can, with a timer... Let's not do that in an official backend.

If the directories don't end with a slash, the user should be able to complete one of them, then type `/`, and see the completion initiated automatically again. If that doesn't happen, it's a bug somewhere.

**Comment by vspinu** [comment]
> Which check is that? Line 59 is empty.

[line 57](https://github.com/company-mode/company-mode/blob/ada2ede3ec75235ef0a6721e526b2fc94284093e/company-files.el#L57) Sorry, got the link from wrong branch.

**Comment by dgutov** [comment]
Yeah, ok, I think we can remove it.

> For my remote's home dir with only 40 files this check takes 0.2 seconds.

I imagine these 0.2 seconds don't really depend on the number of files, as much as on the round-tip time to your server.

**Comment by vspinu** [comment]
>  imagine these 0.2 seconds don't really depend on the number of files

I think that's roughly a lower bound, but there is clearly a variable cost depending on the amount of data returned:

 - 30 files -> .18 sec
 - 300 files -> .38 sec
 - 2500 files -> .7 sec

**Comment by dgutov** [comment]
That's.. unexpected. One would think that listing 270 files more wouldn't incur that much extra overhead when calling `ls` on the remote system, or when transmitting its output.

**Comment by vspinu** [comment]
Yes. That a bit strange. If anything I would expect a linear time, but it seems to be logarithmic.

I have updated the patch in light of what we discussed.

**Comment by dgutov** [comment]
> I have updated the patch in light of what we discussed.

Thanks. I'm waiting on the "run the same check for each parent directory" change before merging.

It would be better if you didn't rebase so much, or even kept each change in separate commit: right now GitHub hides the previous comments in the conversation, and I can't grasp at a glance what changes between the versions. Please consider that for the future.

**Comment by vspinu** [comment]
>  I'm waiting on the "run the same check for each parent directory" change before merging.

That's already [there](https://github.com/vspinu/company-mode/commit/ca447ec37f20b51edd21d1515d2dce170160148e#diff-8f44bd601a089348cac7a663271390e3R86)

> and I can't grasp at a glance what changes between the versions.

Ok. I will get keep that in mind. I thought that the code is small enough not to bother with that.

**Comment by dgutov** [comment]
> That's already there

Thanks. Me missing that should be an illustration of the drawbacks of rebase. :)

With that change, I expected to see the code return to being closer to its earlier shape. But it's okay either way.

Could you take care of the sorting change? Directories first, children later.

**Comment by dgutov** [comment]
This one looks taken care of.
