### ISSUE TITLE
When the asynchronous candidates result returned, how to check if the last completion was cancelled in the callback?

### ISSUE THREAD

**Issue by netjune** [company-mode/company-mode#467]

**Comment by dgutov** [comment]
Why?

I can understand if you wanted to be able to cancel the request if its result is not needed anymore, but why would you need to know if the result is used when you already have the necessary data?

**Comment by netjune** [comment]
Because it set company-candidates-cache, the following completion (using another backend) will use the candidates in company-candidates-cache and won't fetch candidates from the new backend.
In this case, company-calculate-candidates will finally return nil and there is no completion for user.

Backends I use: company-clang, company-dabbrev-code.
Version of the company mode: 0.8.12.

**Comment by dgutov** [comment]
Do you set `company-candidates-cache` manually from the backend? Why?

**Comment by dgutov** [comment]
Or do you just use the existing backends?

Please describe how to reproduce the problem set by step.

**Comment by netjune** [comment]
I use the exsting backends. We can test it with a c++ file. Contents as the following:
`int test_func(void *arg)
{
	int long_name_var = 1;

	std::
		long_
`
(1) At end of line 5: It triggered completion with company-clang. Before the callback was called, I inserted a newline char (or quickly deleted the contents of the line with my custom command delete-to-beginning-of-line which is bind to a key).
(2) Then I inserted  "long_" (as line 6). There was no completion.

I debugged it. The reason may be as the following:
In (1), company-candidates-cache was set by the callback for company-clang after I inserted the newline char. Here company-clang will do nothing(no prefix here), but the value of company-candidates-cache was keeped.
In (2), it triggered completion with company-dabbrev-code. Then, company-candidates-cache was used (by company-calculate-candidates) and finally no candidates was found. So there was no completion for user.

**Comment by dgutov** [comment]
Thanks, I'll look into it. Any idea why `company-dabbrev-code` was used at all here, though?

**Comment by netjune** [comment]
Oh, I forgot something. I modified company-clang. Let it return nil instead of 'stop when no prefix.
I think this will be more usefull.

**Comment by dgutov** [comment]
What does the code look like?

**Comment by dgutov** [comment]
Please post the full diff or the whole modified definition.

**Comment by netjune** [comment]
--- company-mode-0.8.12/company-clang.el        2015-03-05 00:58:18.000000000 +0800
+++ company-clang.el    2016-02-10 13:27:03.000000000 +0800
@@ -318,7 +318,9 @@
                  buffer-file-name
                  company-clang-executable
                  (not (company-in-string-or-comment))
-                 (or (company-clang--prefix) 'stop)))
+                                ;; return nil to use other backends
+                 ;; (or (company-clang--prefix) 'stop)))
+                 (or (company-clang--prefix))))
     (candidates (cons :async
                       (lambda (cb) (company-clang--candidates arg cb))))
     (meta       (company-clang--meta arg))

**Comment by netjune** [comment]
(or (company-clang--prefix) 'stop)))   ==>  (or (company-clang--prefix))))

**Comment by dgutov** [comment]
Thanks. (I've removed the redundant message.)

**Comment by dgutov** [comment]
This might be fixed now.

Note that your scenarios are still unlikely to work:

* If on step 1 you simply insert a newline, the resulting code will be invalid, and you should expect no completions (even if Clang might recover, in certain conditions).
* If on step 2 you call `yank` to insert `_long`, the will be no automatic completion unless `yank` is in `company-begin-commands`.

But please try it out anyway.

**Comment by netjune** [comment]
It is OK now. Thank you.

**Comment by dgutov** [comment]
:sunny:
