### ISSUE TITLE
Completion dialog appearance issues with AUCTeX

### ISSUE THREAD

**Issue by souvik1997** [company-mode/company-mode#468]
When the company-mode completion dialog pops up as I'm typing, the text position changes depending on the contents of the buffer.

Example:
<img width="482" alt="screen shot 2016-02-07 at 3 00 51 pm" src="https://cloud.githubusercontent.com/assets/1762088/12875265/d91fcaa4-cdab-11e5-8bae-7408c9f19759.png">

Notice how the lines that begin with `\section*` cause the text in the completion dialog to be shifted to the right.

**Comment by geraldus** [comment]
Isn't it because of different font families and weights are used in sections?
As far as I know company's popup is just an overlay, not a "separate" floating thing.  I think you'll see same results with any proportional (non-monospaced) font even with equal height.

**Comment by souvik1997** [comment]
Is there some way to "reset" the font families/weights in the overlay?

**Comment by dgutov** [comment]
There are no magical solutions for this. See #207.
