### ISSUE TITLE
company.el can't be byte-compiled?

### ISSUE THREAD

**Issue by netjune** [company-mode/company-mode#469]
I compiled it. Then the company mode does not work with the backend company-clang. 
Error message:
error in process sentinel: funcall: Symbol's value as variable is void: res
error in process sentinel: Symbol's value as variable is void: res

**Comment by dgutov** [comment]
Which version of Emacs did you compile it in?

**Comment by netjune** [comment]
Emacs 24.5 on linux(x86_64)

**Comment by dgutov** [comment]
OK. How did you compile it, exactly?

**Comment by netjune** [comment]
In emacs, M-x byte-compile-file, then choose the file(company.el).

**Comment by dgutov** [comment]
Was company.el loaded beforehand?

**Comment by netjune** [comment]
I just compiled company.el using the command "emacs -batch -f batch-byte-compile company.el". Then the company mode worked well with the backend company-clang.

**Comment by dgutov** [comment]
Right. And I tried compiling it using `M-x byte-compile-file` from a running instance of a development snapshot. That also worked well. So I'm wondering which scenario leads to the problem.

It's probably a bug in Emacs 24.5's byte-compiler, though.

**Comment by dgutov** [comment]
No further info, closing.
