### ISSUE TITLE
Incorporate parts of company-css into Emacs

### ISSUE THREAD

**Issue by notetiene** [company-mode/company-mode#470]
Hi,
after pointing on emacs-devel@gnu.org that company-css has css context aware completion, Stefan Monnier, one of major contributors to css-mode, advised that we include some part of company-css into css-mode.

However, to be part of Gnu Emacs, the copyright must be [assigned to FSF](http://www.gnu.org/licenses/why-assign.html). Since there's only three contributors on GitHub (maybe more?) listed, I ask them if they would be interested in assigning the copyright of their work to FSF.

Please read http://www.gnu.org/licenses/why-assign.html for more information.

@nschum, @dgutov & @bbatsov 

Of course, any contributors to company-mode can express their views on that.

**Comment by bbatsov** [comment]
Me and @dgutov have already signed the FSF agreement.

**Comment by dgutov** [comment]
And @nschum too.

@notetiene company-mode is in GNU ELPA. Among other things, that means that the copyright assignment question is already resolved. But thanks for staying vigilant. ;-)

**Comment by notetiene** [comment]
@nschum I forgot it was in GNU ELPA. I usually use MELPA since it's more updated. Also it's nice to know where you code is going.
