### ISSUE TITLE
Manually start company complete in an elisp function?

### ISSUE THREAD

**Issue by ailisp** [company-mode/company-mode#472]
I wrote an issue about auto convert `.` to `->` a month ago. And I find a efficient way to do it by using company-ycmd backend, it can check whether current symbol is a pointer. However, how to manually start company in an elisp function such as:
```
(defun ycmd--magic-dot-handle-get-type-success (result)
  "Handle a successful GetType request for determing whether it is a pointer"
  (-when-let (msg (assoc-default 'message result))
    (if (string-match "\\\*" msg)
        (insert "->")
      (insert "."))))
```
I have tried `company-complete` as well as some other functions in `company.el` and add this function to `company-begin-commands` list but these seem don't work. Thank you.

**Comment by dgutov** [comment]
> However, how to manually start company in an elisp function such as

You're not supposed to. It's company that chooses when to initiate completion, not the other way around.

Instead, the backend should replace `.` with `->` in `post-completion`, if the appropriate completion has been inserted.

**Comment by wushuaibuaa** [comment]
Fzgadhdsushhzzhhzhzzhzyxgxggydyhshddhdh

On Saturday, February 13, 2016, Dmitry Gutov <notifications@github.com>
wrote:

> However, how to manually start company in an elisp function such as
>
> You're not supposed to. It's company that chooses when to initiate
> completion, not the other way around.
>
> Instead, the backend should replace . with -> in post-completion, if the
> appropriate completion has been inserted.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/company-mode/company-mode/issues/472#issuecomment-183686151>
> .
>


-- 
-- 
\\\|///
                \\  - -  //
                 (  @ @  )
┏━━━━━━━━━oOOo-(_)-oOOo━┓
┃吴 帅
┃北京航空航天大学自动化学院机械电子工程系
┃北京市学院路37号
┃邮编：100191
┃电话：13810037133
┃传真：010-82339238
┃E-mail：ws.horton@gmail.com
┗━━━━━━━━━ oooO━-(   )━┛
                 (   )   ) /
                  \ (   (_/
