### ISSUE TITLE
company-dabbrev gives irrelevant candidates

### ISSUE THREAD

**Issue by geraldus** [company-mode/company-mode#474]
Example:
type `as` and invoke `M-x company-begin-backend company-dabbrev`.  In candidates list I see following irrelevant entities: `askell`, `askell2010`, `askfailure`, `askvalue`.  All of them wrong because they come from following abbrevs in other buffers `Haskell`, `Haskell2010`, `TaskFailure`, `TaskValue`, that is first capital letter magically omitted and rest part is downcased.  Manual invocations of `dabbrev-expand` <kbd>M-/</kbd> yields only valid expansions.  I have default global values of `dabbrev-case-fold-search`, `dabbrev-case-distinction` and `dabbrev-case-replace`.

I spotted this issue while editing haskell cabal file, but it persists in other buffers too.

`company-mode` from MELPA.
Emacs version 25.0.91.1

**Comment by dgutov** [comment]
> In candidates list I see following irrelevant entities: askell, askell2010, askfailure, askvalue.

I've never seen anything like this. How do I reproduce this? Do I just install `haskell-mode` and enter a few identifiers in a buffer in this mode?

> rest part is downcased

Downcasing itself is expected. Customize `company-dabbrev-downcase` (also see the other variables in its group).

> I have default global values of dabbrev-case-fold-search, dabbrev-case-distinction and dabbrev-case-replace.

Those don't have any effect on `company-dabbrev`, because it doesn't reuse the dabbrev machinery (that seems unfeasible).

**Comment by geraldus** [comment]
@dgutov I think haskell-mode is not required, let me make few tests.

**Comment by geraldus** [comment]
I just have tested this in scratch buffer in stable Emacs 24.5.1:
+ type `TestName`
+ type `BestFriend`
+ type `es`
+ invoke dabbrev backend `(company-begin-backend #'company-dabbrev)`
This gives me `estfriend` and `estname` candidates.

**Comment by dgutov** [comment]
I see it now, thanks. It's a regression from the fix for #433.

**Comment by dgutov** [comment]
It should work now.

**Comment by geraldus** [comment]
Great!  Thanks!
