### ISSUE TITLE
Delay execution of the candidates callback

### ISSUE THREAD

**Issue by sid-kurias** [company-mode/company-mode#475]
I have written auto-completion for the Dart language using company mode. https://github.com/sid-kurias/company-dart. It works with a caveat. 

In order to obtain the candidates for completion I have to invoke the dart analysis server. I do that as follows...

`(candidates
     (cons :async
           (lambda (callback)
	     (dart--get-completions callback))))`

Now the call to dart--get-completions invokes the analysis server. The analysis server does not respond with the candidates. Instead it responds with an ID. This ID is the id of an event which  the analysis server will subsequently send. That event has the completion candidates.

What this translates to is that once the call is made to the analysis server, the dart--get-completions function returns (after registering another routine to handle the event). This triggers the company mode completion. At this point I could still be waiting for the event from the analysis server that holds the candidates, so that I can invoke the callback. To get this to work I have to ensure that the dart--get-completions function waits for sometime before it exits. Here is the code

     (defun dart--get-completions ( callback)
       (dart--analysis-server-send
         "completion.getSuggestions"
        `((file . ,(buffer-file-name))
           (offset . ,(point)))
        (lambda (response)
          (dart--register-for-completion-event response callback)))
        ;; Company mode expects the candidates to be ready as soon as this routine
        ;; exits. The analysis server sends the candidates information via a
        ;; subsequent notification. Wait 100ms to receive and process that
        ;; notification.
        (sleep-for 0 100))

Is there another way of getting this to work, other than sleeping?

**Comment by dgutov** [comment]
Can you save `callback` to some variable, and use it later when the analysis server generates the required event? You can have a second variable to hold the value of ID corresponding to the most recent completion request, to be able to ensure that the saved callback does correspond to the completion which resulted in a completion event you receive.

**Comment by sid-kurias** [comment]
Well I do that. Rather than saving the callback as a variable, I pass it around. The relevant code is below. This works well. However it is still dependent on the sleep-for at the end of dart--get-completions.

What I believe is happening is that company mode "completes" - perhaps completes or returns is more accurate - under one of three circumstances
  1. The callback is specifically invoked.
  2.  The function marked as async ( i.e. dart--get-completions) returns.
  3. A timeout occurs

In the case of dart point 2 happens before 1. At which point there are no candidates to display. To prevent this I explicitly wait by calling sleep-for. Now everything works just fine (as long as the routine sleeps for a long enough interval). 

My understanding - perhaps incorrect - is that returning from dart--get-completions is equivalent to timing out i.e. there are no candidates to display. Except the dart analysis server is in the process of sending those candidates.

My question is whether there is a cleaner(??) way of doing this, rather than having to call sleep? Assuming that my understanding is correct; is there a way that company mode reacts only when points 1 and 3 occur and not react when point 2 happens.

BTW my async timeout is set to 2 seconds and increasing that does not seem to have any effect.

     (defun dart--register-for-completion-event (response callback)
       (-when-let* ((result-assoc (assoc 'result response))
  	            (id-assoc (assoc 'id result-assoc))
  	            (raw-id (cdr id-assoc))
  	            (id (string-to-number raw-id)))
         (push (cons id
  	     	(lambda (resp)
  		       (-when-let* ((candidates (dart--company-prepare-candidates
  			     		    resp)))
  		         (funcall callback candidates))))
  	       dart--analysis-completion-callbacks)))

**Comment by sid-kurias** [comment]
perhaps the title is misleading, 

 _ignore return from routine registered as candidates callback in company-backend_ may be more appropriate.

**Comment by dgutov** [comment]
> In the case of dart point 2 happens before 1

That's normal. Take a look at `company-clang` for an example of a small-ish backend using the async convention.

> To prevent this I explicitly wait by calling sleep-for.

You could just as well use the synchronous convention, then.

Anyway, if you don't manage to get it working, please describe what tools I should install to be able to test it.

**Comment by sid-kurias** [comment]
Couldn't get it to work without the sleep. To reproduce the issue.

1. Download and install Dart SDK.  https://www.dartlang.org/downloads/
2. Download a sample project. This one will work just fine... https://github.com/dart-lang/shelf.git
3. in the project directory execute "pub get". This should get all the dependencies
4. Download dart-mode. You need this fork https://github.com/sid-kurias/dart-mode.git. 
    The README tells you how to set it up.
5. Get company-dart. https://github.com/sid-kurias/company-dart.git
   The README tells you how I have set it up.
6.Open lib/src/request.dart, or any other file. Wait a second or two for the analysis server to start
7. Try to use autocompletion. For example on line 219 of request.dart you could type path. and see if  autocomplete kicks in. If it doesn't you may have to increase the sleep-for in company-dart. It should work and so will calling M-x company-dart
8. Remove the sleep-for. You should not see any autocompletion. 

Thanks

**Comment by dgutov** [comment]
> in the project directory execute "pub get". This should get all the dependencies

Note that I had to add `/usr/lib/dart/bin/` to `PATH` first.

> Open lib/src/request.dart, or any other file. Wait a second or two for the analysis server to start

Sorry, I'm just getting an error at this point:

```
Debugger entered--Lisp error: (json-readtable-error)
  signal(json-readtable-error nil)
  json-read()
  json-read-from-string("Unhandled exception:")
  (closure ((buf-lines "Unhandled exception:" "Load Error for \"file:///usr/bin/snapshots/analysis_server.dart.snapshot\": Error loading file:///usr/bin/snapshots/analysis_server.dart.snapshot:" "  FileSystemException: Cannot open file, path = '/usr/bin/snapshots/analysis_server.dart.snapshot' (OS Error: No such file or directory, errno = 2)" "#0      _asyncLoadErrorCallback (dart:_builtin:155)" "#1      _asyncLoadError (dart:_builtin:566)" "#2      _handleLoaderReply (dart:_builtin:383)" "#3      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)" "") (buf . #<buffer dart-analysis-server<4>>) (string . "Unhandled exception:\nLoad Error for \"file:///usr/bin/snapshots/analysis_server.dart.snapshot\": Error loading file:///usr/bin/snapshots/analysis_server.dart.snapshot:\n  FileSystemException: Cannot open file, path = '/usr/bin/snapshots/analysis_server.dart.snapshot' (OS Error: No such file or directory, errno = 2)\n#0      _asyncLoadErrorCallback (dart:_builtin:155)\n#1      _asyncLoadError (dart:_builtin:566)\n#2      _handleLoaderReply (dart:_builtin:383)\n#3      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)\n") (das . [cl-struct-dart--analysis-server #<process dart-analysis-server> #<buffer dart-analysis-server<4>>]) cl-struct-dart--analysis-server-tags t) (s) (dart-info (concat "Received: " s)) (json-read-from-string s))("Unhandled exception:")
  mapcar((closure ((buf-lines "Unhandled exception:" "Load Error for \"file:///usr/bin/snapshots/analysis_server.dart.snapshot\": Error loading file:///usr/bin/snapshots/analysis_server.dart.snapshot:" "  FileSystemException: Cannot open file, path = '/usr/bin/snapshots/analysis_server.dart.snapshot' (OS Error: No such file or directory, errno = 2)" "#0      _asyncLoadErrorCallback (dart:_builtin:155)" "#1      _asyncLoadError (dart:_builtin:566)" "#2      _handleLoaderReply (dart:_builtin:383)" "#3      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)" "") (buf . #<buffer dart-analysis-server<4>>) (string . "Unhandled exception:\nLoad Error for \"file:///usr/bin/snapshots/analysis_server.dart.snapshot\": Error loading file:///usr/bin/snapshots/analysis_server.dart.snapshot:\n  FileSystemException: Cannot open file, path = '/usr/bin/snapshots/analysis_server.dart.snapshot' (OS Error: No such file or directory, errno = 2)\n#0      _asyncLoadErrorCallback (dart:_builtin:155)\n#1      _asyncLoadError (dart:_builtin:566)\n#2      _handleLoaderReply (dart:_builtin:383)\n#3      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)\n") (das . [cl-struct-dart--analysis-server #<process dart-analysis-server> #<buffer dart-analysis-server<4>>]) cl-struct-dart--analysis-server-tags t) (s) (dart-info (concat "Received: " s)) (json-read-from-string s)) ("Unhandled exception:" "Load Error for \"file:///usr/bin/snapshots/analysis_server.dart.snapshot\": Error loading file:///usr/bin/snapshots/analysis_server.dart.snapshot:" "  FileSystemException: Cannot open file, path = '/usr/bin/snapshots/analysis_server.dart.snapshot' (OS Error: No such file or directory, errno = 2)" "#0      _asyncLoadErrorCallback (dart:_builtin:155)" "#1      _asyncLoadError (dart:_builtin:566)" "#2      _handleLoaderReply (dart:_builtin:383)" "#3      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)"))
  -map((closure ((buf-lines "Unhandled exception:" "Load Error for \"file:///usr/bin/snapshots/analysis_server.dart.snapshot\": Error loading file:///usr/bin/snapshots/analysis_server.dart.snapshot:" "  FileSystemException: Cannot open file, path = '/usr/bin/snapshots/analysis_server.dart.snapshot' (OS Error: No such file or directory, errno = 2)" "#0      _asyncLoadErrorCallback (dart:_builtin:155)" "#1      _asyncLoadError (dart:_builtin:566)" "#2      _handleLoaderReply (dart:_builtin:383)" "#3      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)" "") (buf . #<buffer dart-analysis-server<4>>) (string . "Unhandled exception:\nLoad Error for \"file:///usr/bin/snapshots/analysis_server.dart.snapshot\": Error loading file:///usr/bin/snapshots/analysis_server.dart.snapshot:\n  FileSystemException: Cannot open file, path = '/usr/bin/snapshots/analysis_server.dart.snapshot' (OS Error: No such file or directory, errno = 2)\n#0      _asyncLoadErrorCallback (dart:_builtin:155)\n#1      _asyncLoadError (dart:_builtin:566)\n#2      _handleLoaderReply (dart:_builtin:383)\n#3      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)\n") (das . [cl-struct-dart--analysis-server #<process dart-analysis-server> #<buffer dart-analysis-server<4>>]) cl-struct-dart--analysis-server-tags t) (s) (dart-info (concat "Received: " s)) (json-read-from-string s)) ("Unhandled exception:" "Load Error for \"file:///usr/bin/snapshots/analysis_server.dart.snapshot\": Error loading file:///usr/bin/snapshots/analysis_server.dart.snapshot:" "  FileSystemException: Cannot open file, path = '/usr/bin/snapshots/analysis_server.dart.snapshot' (OS Error: No such file or directory, errno = 2)" "#0      _asyncLoadErrorCallback (dart:_builtin:155)" "#1      _asyncLoadError (dart:_builtin:566)" "#2      _handleLoaderReply (dart:_builtin:383)" "#3      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)"))
  (let ((json-lines (-map (function (lambda (s) (dart-info (concat "Received: " s)) (json-read-from-string s))) (-filter (function (lambda (s) (not ...))) (-butlast buf-lines))))) (-each json-lines (quote dart--analysis-server-handle-msg)))
  (let ((buf-lines (split-string (buffer-string) "\n"))) (delete-region (point-min) (point-max)) (insert (-last-item buf-lines)) (let ((json-lines (-map (function (lambda (s) (dart-info ...) (json-read-from-string s))) (-filter (function (lambda ... ...)) (-butlast buf-lines))))) (-each json-lines (quote dart--analysis-server-handle-msg))))
  (save-current-buffer (set-buffer buf) (goto-char (point-max)) (insert string) (let ((buf-lines (split-string (buffer-string) "\n"))) (delete-region (point-min) (point-max)) (insert (-last-item buf-lines)) (let ((json-lines (-map (function (lambda ... ... ...)) (-filter (function ...) (-butlast buf-lines))))) (-each json-lines (quote dart--analysis-server-handle-msg)))))
  (progn (save-current-buffer (set-buffer buf) (goto-char (point-max)) (insert string) (let ((buf-lines (split-string (buffer-string) "\n"))) (delete-region (point-min) (point-max)) (insert (-last-item buf-lines)) (let ((json-lines (-map (function ...) (-filter ... ...)))) (-each json-lines (quote dart--analysis-server-handle-msg))))))
  (if (buffer-live-p buf) (progn (save-current-buffer (set-buffer buf) (goto-char (point-max)) (insert string) (let ((buf-lines (split-string (buffer-string) "\n"))) (delete-region (point-min) (point-max)) (insert (-last-item buf-lines)) (let ((json-lines (-map ... ...))) (-each json-lines (quote dart--analysis-server-handle-msg)))))))
  (let ((buf (progn nil (or (progn nil (and (vectorp das) (>= ... 3) (memq ... cl-struct-dart--analysis-server-tags) t)) (signal (quote wrong-type-argument) (list (quote dart--analysis-server) das))) (aref das 2)))) (if (buffer-live-p buf) (progn (save-current-buffer (set-buffer buf) (goto-char (point-max)) (insert string) (let ((buf-lines (split-string ... "\n"))) (delete-region (point-min) (point-max)) (insert (-last-item buf-lines)) (let ((json-lines ...)) (-each json-lines (quote dart--analysis-server-handle-msg))))))))
  dart--analysis-server-process-filter([cl-struct-dart--analysis-server #<process dart-analysis-server> #<buffer dart-analysis-server<4>>] "Unhandled exception:\nLoad Error for \"file:///usr/bin/snapshots/analysis_server.dart.snapshot\": Error loading file:///usr/bin/snapshots/analysis_server.dart.snapshot:\n  FileSystemException: Cannot open file, path = '/usr/bin/snapshots/analysis_server.dart.snapshot' (OS Error: No such file or directory, errno = 2)\n#0      _asyncLoadErrorCallback (dart:_builtin:155)\n#1      _asyncLoadError (dart:_builtin:566)\n#2      _handleLoaderReply (dart:_builtin:383)\n#3      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)\n")
  (closure ((instance . [cl-struct-dart--analysis-server #<process dart-analysis-server> #<buffer dart-analysis-server<4>>]) (buffer . #<buffer dart-analysis-server<4>>) (process . #<process dart-analysis-server>) cl-struct-dart--analysis-server-tags t) (_ string) (dart--analysis-server-process-filter instance string))(#<process dart-analysis-server> "Unhandled exception:\nLoad Error for \"file:///usr/bin/snapshots/analysis_server.dart.snapshot\": Error loading file:///usr/bin/snapshots/analysis_server.dart.snapshot:\n  FileSystemException: Cannot open file, path = '/usr/bin/snapshots/analysis_server.dart.snapshot' (OS Error: No such file or directory, errno = 2)\n#0      _asyncLoadErrorCallback (dart:_builtin:155)\n#1      _asyncLoadError (dart:_builtin:566)\n#2      _handleLoaderReply (dart:_builtin:383)\n#3      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)\n")
```

**Comment by sid-kurias** [comment]
that is a bug. will report it.
I guess I get around it by setting the following in my init.el

        (setq dart-executable-path "/usr/lib/dart/bin/dart")

**Comment by dgutov** [comment]
Same error. It's not like it fails to find the `dart` executable.

It's failing to find the analysis server, and it's looking inside `/usr/bin/snapshots/`, for some reason.

**Comment by sid-kurias** [comment]
I had a closer look at the issue. And now I have enough information to file a good bug report :-)
The path to the snapshot is derived from the path to the dart executable. Your dart executable is under /usr/lib/dart/bin and it looks for the snapshot directory under this directory. Unfortunately there seem to be two issues
1. I am using an ubuntu derivative.  When the package manager installs the software it creates a link to /usr/bin/dart. So it finds the dart executable there, but not the analysis server, since no link is created for the analysis server. Removing this link (/usr/bin/dart) may help. It did not in my case, because of the next point.
2. There is something about the way emacs-path and PATH interact. I could get emacs to recognize the right path only after adding PATH to my .pam_environment file - I run emacs in daemon mode. Then everything works fine if /usr/lib/dart/bin/dart is before /usr/bin/dart.
3. I am not certain why setting the dart-executable-path did not work for you. However...
To simplify things for you, I have hard coded the path to the dart executable to /usr/lib/dart/bin/dart, in the enclosed files. Please use both of them, since some modifications were made to both dart-mode and company-dart. 
Sorry about all these issues.


 

    On Sunday, February 28, 2016 12:58 AM, Dmitry Gutov <notifications@github.com> wrote:
 

 Same error. It's not like it fails to find the dart executable.It's failing to find the analysis server, and it's looking inside /usr/bin/snapshots/, for some reason.—

**Comment by dgutov** [comment]
> To simplify things for you, I have hard coded the path to the dart executable to /usr/lib/dart/bin/dart, in the enclosed files.

The attachment didn't come through, because apparently GitHub comments don't work like that.

> I am using an ubuntu derivative.

I'm using Ubuntu 15.10, the off-the-shelf version. Anyway, after setting the necessary values, I got the analysis server to start. Also note that you might not have to hardcode the values:

```
(file-truename "/usr/bin/dart")
"/usr/lib/dart/bin/dart"
```

**Comment by dgutov** [comment]
Observation 1: you're not using `company-grab-symbol-cons` correctly:

```diff
diff --git a/company-dart.el b/company-dart.el
index 04d190d..b4a1547 100644
--- a/company-dart.el
+++ b/company-dart.el
@@ -105,17 +105,13 @@ Argument RESPONSE parsed data received from the analysis server."
   (--when-let (get-text-property 0 'docComplete s)
     (company-doc-buffer it)))
 
-(defun dart--company-prefix ()
-  (let ((dart-symbol (company-grab-symbol-cons "\\." 1)))
-    (if (consp dart-symbol) t nil)))
-
 ;;;###autoload
 (defun company-dart (command &optional arg &rest ignored)
   (interactive (list 'interactive))
   (case command
     (interactive (company-begin-backend 'company-dart))
-    (prefix (if (and (derived-mode-p 'dart-mode)
-		     (dart--company-prefix)) "" nil))
+    (prefix (and (derived-mode-p 'dart-mode)
+                 (company-grab-symbol-cons "\\." 1)))
     (candidates
      (cons :async
 	   (lambda (callback)
```

Observation 2: you're calling the callback from the wrong buffer (specifically, from the analysis server buffer). It must be called from the file buffer the user is editing (I'm adding a note to the documentation right now). You can apply this patch for debugging:

```diff
diff --git a/company.el b/company.el
index 51aad7b..f6618d0 100644
--- a/company.el
+++ b/company.el
@@ -1186,6 +1186,10 @@ can retrieve meta-data for them."
                    company-candidates-cache
                    (list (cons prefix
                                (company--preprocess-candidates candidates))))
+             (message "buf %s win %s tick was %s is %s pt was %s is %s"
+                      (current-buffer) (selected-window)
+                      tick (buffer-chars-modified-tick)
+                      pt (point))
              (unwind-protect
                  (company-idle-begin buf win tick pt)
                (unless company-candidates
```

Apparently, you should save the reference to the buffer, and use it with `with-current-buffer` when calling the callback.

Three: there's no point in keeping the global `dart--company-callback` variable. Just thread it through `dart--get-completions`:

```diff
diff --git a/company-dart.el b/company-dart.el
index 04d190d..de6e357 100644
--- a/company-dart.el
+++ b/company-dart.el
@@ -64,7 +64,7 @@ Argument RESPONSE contains the candidates, documentation, parameters to be displ
      completions)))
 
 
-(defun dart--register-for-completion-event (response)
+(defun dart--register-for-completion-event (response callback)
   "Register for the event that the analysis server will send.
 
 Argument RESPONSE parsed data received from the analysis server."
@@ -76,10 +76,10 @@ Argument RESPONSE parsed data received from the analysis server."
   		(lambda (resp)
   		  (-when-let* ((candidates (dart--company-prepare-candidates
   					    resp)))
-  		    (funcall dart--company-callback  candidates))))
+  		    (funcall callback candidates))))
   	  dart--analysis-server-callbacks)))
 
-(defun dart--get-completions ()
+(defun dart--get-completions (callback)
   "Ask the analysis server for suggestions."
 
   (dart--analysis-server-send
@@ -87,7 +87,7 @@ Argument RESPONSE parsed data received from the analysis server."
    `((file . ,(buffer-file-name))
      (offset . ,(point)))
    (lambda (response)
-     (dart--register-for-completion-event response)))
+     (dart--register-for-completion-event response callback)))
 
   ;; Company mode expects the candidates to be ready as soon as this routine
   ;; exits. The analysis server sends the candidates information via a
@@ -119,8 +119,7 @@ Argument RESPONSE parsed data received from the analysis server."
     (candidates
      (cons :async
 	   (lambda (callback)
-	     (setq dart--company-callback callback)
-	     (dart--get-completions))))
+             (dart--get-completions callback))))
     (duplicates t)
     (doc-buffer (dart--completion-doc arg))
     (meta (dart--completion-meta arg))))
```

It doesn't seem strictly necessary in this case, but you probably should [enable lexical-binding](http://irreal.org/blog/?p=628) in `company-dart.el` sooner rather than later.

**Comment by dgutov** [comment]
To sum up, try this:

```diff
diff --git a/company-dart.el b/company-dart.el
index 04d190d..bbe917a 100644
--- a/company-dart.el
+++ b/company-dart.el
@@ -1,4 +1,4 @@
-;;; company-dart.el
+;;; company-dart.el -*- lexical-binding: t -*-
 
 ;; Author: Sidart Kurias
 ;; Version: 0.01
@@ -64,7 +64,7 @@ Argument RESPONSE contains the candidates, documentation, parameters to be displ
      completions)))
 
 
-(defun dart--register-for-completion-event (response)
+(defun dart--register-for-completion-event (response callback buffer)
   "Register for the event that the analysis server will send.
 
 Argument RESPONSE parsed data received from the analysis server."
@@ -76,10 +76,11 @@ Argument RESPONSE parsed data received from the analysis server."
   		(lambda (resp)
   		  (-when-let* ((candidates (dart--company-prepare-candidates
   					    resp)))
-  		    (funcall dart--company-callback  candidates))))
+                    (with-current-buffer buffer
+                      (funcall callback candidates)))))
   	  dart--analysis-server-callbacks)))
 
-(defun dart--get-completions ()
+(defun dart--get-completions (callback buffer)
   "Ask the analysis server for suggestions."
 
   (dart--analysis-server-send
@@ -87,13 +88,8 @@ Argument RESPONSE parsed data received from the analysis server."
    `((file . ,(buffer-file-name))
      (offset . ,(point)))
    (lambda (response)
-     (dart--register-for-completion-event response)))
-
-  ;; Company mode expects the candidates to be ready as soon as this routine
-  ;; exits. The analysis server sends the candidates information via a
-  ;; subsequent notification. Wait 200ms to receive and process that
-  ;; notification.
-  (sleep-for 0 200))
+     (dart--register-for-completion-event response callback buffer)))
+  )
 
 
 (defun dart--completion-meta (s)
@@ -114,13 +110,12 @@ Argument RESPONSE parsed data received from the analysis server."
   (interactive (list 'interactive))
   (case command
     (interactive (company-begin-backend 'company-dart))
-    (prefix (if (and (derived-mode-p 'dart-mode)
-		     (dart--company-prefix)) "" nil))
+    (prefix (and (derived-mode-p 'dart-mode)
+                 (company-grab-symbol-cons "\\." 1)))
     (candidates
      (cons :async
 	   (lambda (callback)
-	     (setq dart--company-callback callback)
-	     (dart--get-completions))))
+             (dart--get-completions callback (current-buffer)))))
     (duplicates t)
     (doc-buffer (dart--completion-doc arg))
     (meta (dart--completion-meta arg))))
```

**Comment by dgutov** [comment]
And observation 4: the argument lists should not be included in the candiate strings. Use `annotation` for that.

**Comment by sid-kurias** [comment]
Wow, thank you. This is a goldmine of information. Thank you for having a look.

I made the changes as you suggested and everything works fine.  No more sleep-for :-)

Thank you once again.

**Comment by dgutov** [comment]
You're welcome!
