### ISSUE TITLE
company-elisp does not detect (require ...)

### ISSUE THREAD

**Issue by Wilfred** [company-mode/company-mode#477]
company-elisp is generally very smart, but it doesn't recognise require expressions. If | is point, then:

```lisp
(require '|)
```

would ideally complete known packages rather than any elisp symbol.

**Comment by dgutov** [comment]
`company-elisp` has been deprecated since Emacs 24.4.

Please file this feature request against Emacs and its built-in completion, which we delegate to through `company-capf`.

**Comment by Wilfred** [comment]
Thanks, I'll follow up upstream.

Should `company-elisp` be marked as deprecated in the code?

**Comment by dgutov** [comment]
> Should company-elisp be marked as deprecated in the code?

Maybe. So far, it's been mentioned only in NEWS. And in `company-backends` definition, of course.
