### ISSUE TITLE
C++11 Keywords

### ISSUE THREAD

**Issue by spaceotter** [company-mode/company-mode#478]
Some new C++11 keywords are missing from company-keywords. You can see a list of them here: http://en.cppreference.com/w/cpp/keyword

**Comment by dgutov** [comment]
The "since C++11" ones?

**Comment by spaceotter** [comment]
That's correct. Also "final" and "override" might be considered keywords as well for the purpose of completion.

**Comment by dgutov** [comment]
Added, thanks for the report.
