### ISSUE TITLE
Troubleshooting stuck backend

### ISSUE THREAD

**Issue by egarrulo** [company-mode/company-mode#479]
Hello,

I am getting this error in a Java source file:

    Company: backend (company-dabbrev-code company-gtags company-etags company-keywords) error "File /home/egarrulo/Downloads/fish-2.1.2/TAGS does not exist" with args (candidates Str)

My understanding is that `company-etags` is stuck with a `TAGS` file that does not exist anymore.  If this is indeed the case, do you know how I could fix it?

`company-version` is `"0.9.0-cvs"`.

Thank you.

**Comment by dgutov** [comment]
Have you tried restarting Emacs?

**Comment by egarrulo** [comment]
Yes.  Thanks to `apropos-value`, I have determined that the variable that was causing the problem was `tags-table-list`.  I have deleted its content and now everything is working.  However, I thought that the backend that was causing the error would have been the first item in the list, but this was not the case for `company-etags`.  Why so?  This time, it was easy to guess the faulty backend, but in other cases, troubleshooting may be trickier.

**Comment by dgutov** [comment]
> However, I thought that the backend that was causing the error would have been the first item in the list, but this was not the case for company-etags.

You mean `company-etags` is not the first in the list? Well, this drawback in error reporting is a consequence of how we work with grouped backends. It doesn't seem like figuring out the problematic backend should've been hard in this case, so addressing that issue doesn't seem pressing.

> apropos-value

That's a cool command. :smile:
