### ISSUE TITLE
How to disable tooltips in comments?

### ISSUE THREAD

**Issue by abo-abo** [company-mode/company-mode#480]
I see there's `company-in-string-or-comment` in company.el. Is there an option to turn off the popup when that function returns true?

I'm in `python-mode` if it makes a difference.

**Comment by dgutov** [comment]
Each backend decides the context where it is active. Type `M-x company-diag` to find the currently used backend.

**Comment by abo-abo** [comment]
I got:

    Used backend: company-dabbrev
    
Should I just disable that one if I want no tooltips in comments?

**Comment by dgutov** [comment]
I suppose so. However, it's the main backend for completion in text modes, where there is no notion of comments. So you might want to re-add in buffer-local values of `company-backends`, in e.g. `text-mode-hook`, `message-mode-hook` and so on.
