### ISSUE TITLE
Company-dabbrev drastically slower

### ISSUE THREAD

**Issue by duerrp** [company-mode/company-mode#482]
Hi all,

After updating from company-company-20160206.308 to company-20160228.1705, the completion is suddenly unusably slow in a large (and gpg encrypted) `org-mode` file. Debug-on-quit points to `company-dabbrev`...

Rolling back the company package to the previous version fixes the issue.
Thanks in advance for your help!

**Comment by dgutov** [comment]
Thanks for the report.

Is the performance better in a large, but not encrypted, file? I.e., does encryption have any effect I need to look into?

**Comment by duerrp** [comment]
Sorry for the delay. I tried with the same file (~8000 lines) unencrypted, and the encryption makes no difference. With the previous version of company, completion works without noticeable delay, with the new version, my cursor is blocking when I start entering a word.

**Comment by dgutov** [comment]
I've pushed a change, which should yield an improvement, making it honor `company-dabbrev-time-limit` more precisely. You should also be able to customize that variable to a lower value, and see even lower latency.

If that doesn't help enough, please evaluate `(benchmark 1 '(company-dabbrev 'candidates ""))` in a problem buffer, and tell me the number it reports.

**Comment by duerrp** [comment]
@dgutov Thanks! Now it's reasonably fast again. The benchmark yields: `Elapsed time: 0.114515s`

**Comment by dgutov** [comment]
> Elapsed time: 0.114515s

That sound about right, with the default time limit value. Thanks for checking.
