### ISSUE TITLE
An error occurred in auto-begin - error "Args out of range: "", 1, 0" with args (prefix)

### ISSUE THREAD

**Issue by srustamo** [company-mode/company-mode#489]
I have this in my `init.el`, which was working OK until the latest update, but now I get the subject error:

    (defun add-pcomplete-to-capf ()
    (add-hook 'completion-at-point-functions 'pcomplete-completions-at-point nil t))

    (add-hook 'org-mode-hook #'add-pcomplete-to-capf)
    
    (add-hook 'org-mode-hook
          (lambda ()
            (setq-local company-backends '((company-capf company-dabbrev company-dabbrev-code     company-files :with company-yasnippet)))))
    (setq company-dabbrev-code-ignore-case 'keep-prefix)

**Comment by dgutov** [comment]
The latest update of what?

What does `M-x company-diag` show?

**Comment by srustamo** [comment]
Updated `company-mode` from  company-20160211.520 to company-20160311.448 (melpa).

`M-x company-diag` in an org-buffer (in which the error occurs) shows:

    Emacs 24.5.1 (x86_64-apple-darwin13.4.0) of 2015-05-01 on srmbp.local
    Company 0.9.0-cvs

    company-backends: ((company-capf company-dabbrev company-dabbrev-code company-files :with     company-yasnippet))

    Used backend: (company-capf company-dabbrev company-dabbrev-code company-files :with company-yasnippet)

    Prefix: "log"
    Completions:
     #("log" 0 3 (company-backend company-dabbrev))
    #("log" 0 3 (company-backend company-dabbrev))
    #("log" 0 3 (company-backend company-dabbrev))
    #("log" 0 3 (company-backend company-dabbrev))
    #("log" 0 3 (company-backend company-dabbrev))
    #("log" 0 3 (company-backend company-dabbrev))
    #("log" 0 3 (company-backend company-dabbrev))
    #("log" 0 3 (company-backend company-dabbrev))
    #("log" 0 3 (company-backend company-dabbrev))
    #("log" 0 3 (company-backend company-dabbrev))
    #("log" 0 3 (company-backend company-dabbrev))
    #("log" 0 3 (company-backend company-dabbrev))
    #("log" 0 3 (company-backend company-dabbrev))
    #("log" 0 3 (company-backend company-dabbrev))
    #("log" 0 3 (company-backend company-dabbrev))
    #("log" 0 3 (company-backend company-dabbrev))
    #("logs" 0 4 (company-backend company-dabbrev))
    #("log" 0 3 (company-backend company-dabbrev))
    #("log" 0 3 (company-backend company-dabbrev))
    #("log" 0 3 (company-backend company-dabbrev))
    #("logs" 0 4 (company-backend company-dabbrev))
    #("logs" 0 4 (company-backend company-dabbrev))
    #("log" 0 3 (company-backend company-dabbrev))
    #("log" 0 3 (company-backend company-dabbrev))
    #("log" 0 3 (company-backend company-dabbrev))
    #("log" 0 3 (company-backend company-dabbrev))
    #("log" 0 3 (company-backend company-dabbrev))
    #("log" 0 3 (company-backend company-dabbrev))
    #("log" 0 3 (company-backend company-dabbrev))
    #("log" 0 3 (company-backend company-dabbrev))
    #("log" 0 3 (company-backend company-dabbrev))
    #("log" 0 3 (company-backend company-dabbrev))
    #("log" 0 3 (company-backend company-dabbrev))
    #("log" 0 3 (company-backend company-dabbrev))

**Comment by dgutov** [comment]
Please `M-x toggle-debug-on-error` and then `M-x company-complete-common`, to obtain the error backtrace, and post it here.

**Comment by srustamo** [comment]
The error in the original buffer (org-mode) does not show up now (after a restart), but also no candidates from all open buffers are shown as completions candidates (only from within the buffer). The subject error still occurs in org-mode's capture buffer. 

Here's [backtrace](https://gist.github.com/srustamo/675847e69a4b76d1c165).

**Comment by srustamo** [comment]
Rolled back to  company-20160211.520. 

It seems that the word "log" chokes up the completion.

*Messages* buffer:

`Company: An error occurred in auto-begin
Company: backend (company-capf company-dabbrev company-dabbrev-code company-files :with company-yasnippet) error "Wrong type argument: char-or-string-p, nil" with args (prefix)`


Here's what `company-diag` shows in the problem org buffer. As you can see, there are more candidates, from other open buffers. 

    `Emacs 24.5.1 (x86_64-apple-darwin13.4.0) of 2015-05-01 on sr.local
    Company 0.9.0-cvs
    
    company-backends: ((company-capf company-dabbrev company-dabbrev-code company-files :with company-yasnippet))
    
    Used backend: (company-capf company-dabbrev company-dabbrev-code company-files :with company-yasnippet)
    
    Prefix: "log"
    Completions:
      #("log" 0 3 (company-backend company-dabbrev))
      #("logs" 0 4 (company-backend company-dabbrev))
      #("logia" 0 5 (company-backend company-dabbrev))
      #("logicmatters" 0 12 (company-backend company-dabbrev))
      #("logic" 0 5 (company-backend company-dabbrev))
      #("logic" 0 5 (company-backend company-dabbrev))
      #("logicmatters" 0 12 (company-backend company-dabbrev))
      #("logic" 0 5 (company-backend company-dabbrev))
      #("log" 0 3 (company-backend company-dabbrev))
      #("log" 0 3 (company-backend company-dabbrev))
      #("logs" 0 4 (company-backend company-dabbrev))
      #("log" 0 3 (company-backend company-dabbrev))
      #("log" 0 3 (company-backend company-dabbrev))
      #("logspot" 0 7 (company-backend company-dabbrev))
      #("logspot" 0 7 (company-backend company-dabbrev))
      #("log" 0 3 (company-backend company-dabbrev))
      #("logspot" 0 7 (company-backend company-dabbrev))
      #("logspot" 0 7 (company-backend company-dabbrev))
      #("log" 0 3 (company-backend company-dabbrev))
      #("log" 0 3 (company-backend company-dabbrev))
      #("log" 0 3 (company-backend company-dabbrev))
      #("log" 0 3 (company-backend company-dabbrev))
      #("log" 0 3 (company-backend company-dabbrev))
      #("log" 0 3 (company-backend company-dabbrev))
      #("log" 0 3 (company-backend company-dabbrev))
      #("logy" 0 4 (company-backend company-dabbrev))
      #("log" 0 3 (company-backend company-dabbrev))
      #("logical" 0 7 (company-backend company-dabbrev))
      #("log" 0 3 (company-backend company-dabbrev))
      #("log" 0 3 (company-backend company-dabbrev))
      #("log" 0 3 (company-backend company-dabbrev))
      #("log" 0 3 (company-backend company-dabbrev))
      #("logo" 0 4 (company-backend company-dabbrev))
      #("logical" 0 7 (company-backend company-dabbrev))
      #("log" 0 3 (company-backend company-dabbrev))
      #("log" 0 3 (company-backend company-dabbrev))
      #("log" 0 3 (company-backend company-dabbrev))
      #("log" 0 3 (company-backend company-dabbrev))
      #("log" 0 3 (company-backend company-dabbrev))
      #("logic" 0 5 (company-backend company-dabbrev))
      #("log" 0 3 (company-backend company-dabbrev))
      #("log" 0 3 (company-backend company-dabbrev))
      #("log" 0 3 (company-backend company-dabbrev))
      #("log" 0 3 (company-backend company-dabbrev))
      #("log" 0 3 (company-backend company-dabbrev))
      #("log" 0 3 (company-backend company-dabbrev))
      #("log" 0 3 (company-backend company-dabbrev))
      #("log" 0 3 (company-backend company-dabbrev))
      #("log" 0 3 (company-backend company-dabbrev))
      #("log" 0 3 (company-backend company-dabbrev))
      #("log" 0 3 (company-backend company-dabbrev))
      #("logspot" 0 7 (company-backend company-dabbrev))
      #("logspot" 0 7 (company-backend company-dabbrev))
      #("log" 0 3 (company-backend company-dabbrev))
      #("logs" 0 4 (company-backend company-dabbrev))
      #("logs" 0 4 (company-backend company-dabbrev))
      #("log" 0 3 (company-backend company-dabbrev))
      #("log" 0 3 (company-backend company-dabbrev))
      #("log" 0 3 (company-backend company-dabbrev))
      #("logic" 0 5 (company-backend company-dabbrev))
      #("logic" 0 5 (company-backend company-dabbrev))
      #("log" 0 3 (company-backend company-dabbrev))
      #("log" 0 3 (company-backend company-dabbrev))
      #("log" 0 3 (company-backend company-dabbrev))
      #("log" 0 3 (company-backend company-dabbrev))
      #("logy" 0 4 (company-backend company-dabbrev))
      #("log" 0 3 (company-backend company-dabbrev))
      #("log" 0 3 (company-backend company-dabbrev))
      #("log" 0 3 (company-backend company-dabbrev))
      #("log" 0 3 (company-backend company-dabbrev))
      #("log" 0 3 (company-backend company-dabbrev))
      #("logs" 0 4 (company-backend company-dabbrev))
      #("logue" 0 5 (company-backend company-dabbrev))
      #("logic" 0 5 (company-backend company-dabbrev))
      #("log" 0 3 (company-backend company-dabbrev))
      #("log" 0 3 (company-backend company-dabbrev))
      #("logies" 0 6 (company-backend company-dabbrev))
      #("logy" 0 4 (company-backend company-dabbrev))
      #("logy" 0 4 (company-backend company-dabbrev))
      #("logy" 0 4 (company-backend company-dabbrev))
      #("logy" 0 4 (company-backend company-dabbrev))
      #("logy" 0 4 (company-backend company-dabbrev))
      #("logy" 0 4 (company-backend company-dabbrev))
      #("logy" 0 4 (company-backend company-dabbrev))
      #("logy" 0 4 (company-backend company-dabbrev))
      #("logies" 0 6 (company-backend company-dabbrev))
      #("logies" 0 6 (company-backend company-dabbrev))
      #("log" 0 3 (company-backend company-dabbrev))
      #("logic" 0 5 (company-backend company-dabbrev))
      #("log" 0 3 (company-backend company-dabbrev))
      #("log" 0 3 (company-backend company-dabbrev))
      #("log" 0 3 (company-backend company-dabbrev))
      #("log" 0 3 (company-backend company-dabbrev))
      #("logodust" 0 8 (company-backend company-dabbrev))
      #("log" 0 3 (company-backend company-dabbrev))
      #("log" 0 3 (company-backend company-dabbrev))
      #("log" 0 3 (company-backend company-dabbrev))
      #("log" 0 3 (company-backend company-dabbrev))
      #("logs" 0 4 (company-backend company-dabbrev))
      #("log" 0 3 (company-backend company-dabbrev))
      #("log" 0 3 (company-backend company-dabbrev))
      #("log" 0 3 (company-backend company-dabbrev))
      #("log" 0 3 (company-backend company-dabbrev))
      #("log" 0 3 (company-backend company-dabbrev))
      #("log" 0 3 (company-backend company-dabbrev))
      #("log" 0 3 (company-backend company-dabbrev))
      #("log" 0 3 (company-backend company-dabbrev))
      #("logo" 0 4 (company-backend company-dabbrev))
      #("logspot" 0 7 (company-backend company-dabbrev))
      #("log" 0 3 (company-backend company-dabbrev))
      #("log" 0 3 (company-backend company-dabbrev))
      #("log" 0 3 (company-backend company-dabbrev))
      #("log" 0 3 (company-backend company-dabbrev))
      #("log" 0 3 (company-backend company-dabbrev))
      #("logspot" 0 7 (company-backend company-dabbrev))
      #("log" 0 3 (company-backend company-dabbrev))
      #("logspot" 0 7 (company-backend company-dabbrev))
      #("log" 0 3 (company-backend company-dabbrev))
      #("logy" 0 4 (company-backend company-dabbrev))
      #("logy" 0 4 (company-backend company-dabbrev))
      #("log" 0 3 (company-backend company-dabbrev))
      #("log" 0 3 (company-backend company-dabbrev))
      #("log" 0 3 (company-backend company-dabbrev))
      #("log" 0 3 (company-backend company-dabbrev))
      #("logic" 0 5 (company-backend company-dabbrev))
      #("logic" 0 5 (company-backend company-dabbrev))
      #("logical" 0 7 (company-backend company-dabbrev))
      #("logic" 0 5 (company-backend company-dabbrev))
      #("logic" 0 5 (company-backend company-dabbrev))
      #("logic" 0 5 (company-backend company-dabbrev))
      #("logic" 0 5 (company-backend company-dabbrev))
      #("logos" 0 5 (company-backend company-dabbrev))
      #("logo" 0 4 (company-backend company-dabbrev))
      #("log" 0 3 (company-backend company-dabbrev))
      #("log" 0 3 (company-backend company-dabbrev))
      #("log" 0 3 (company-backend company-dabbrev))
      #("log" 0 3 (company-backend company-dabbrev))
      #("log" 0 3 (company-backend company-dabbrev))
      #("logic" 0 5 (company-backend company-dabbrev))
      #("logical" 0 7 (company-backend company-dabbrev))
      #("log" 0 3 (company-backend company-dabbrev))
      #("log" 0 3 (company-backend company-dabbrev))
      #("logic" 0 5 (company-backend company-dabbrev))
      #("log" 0 3 (company-backend company-dabbrev))
      #("log" 0 3 (company-backend company-dabbrev))
      #("logs" 0 4 (company-backend company-dabbrev))
      #("logue" 0 5 (company-backend company-dabbrev))
      #("logic" 0 5 (company-backend company-dabbrev))
      #("log" 0 3 (company-backend company-dabbrev))
      #("logic" 0 5 (company-backend company-dabbrev))
      #("logic" 0 5 (company-backend company-dabbrev))
      #("logs" 0 4 (company-backend company-dabbrev))
      #("logy" 0 4 (company-backend company-dabbrev))
      #("logy" 0 4 (company-backend company-dabbrev))
      #("logy" 0 4 (company-backend company-dabbrev))
      #("logy" 0 4 (company-backend company-dabbrev))
      #("log" 0 3 (company-backend company-dabbrev))
      #("log" 0 3 (company-backend company-dabbrev))
      #("log" 0 3 (company-backend company-dabbrev))
      #("log" 0 3 (company-backend company-dabbrev))
      #("log" 0 3 (company-backend company-dabbrev))
      #("log" 0 3 (company-backend company-dabbrev))
      #("logy" 0 4 (company-backend company-dabbrev))
      #("log" 0 3 (company-backend company-dabbrev))
      #("log" 0 3 (company-backend company-dabbrev))
      #("log" 0 3 (company-backend company-dabbrev))
      #("log" 0 3 (company-backend company-dabbrev))
      #("log" 0 3 (company-backend company-dabbrev))
      #("log" 0 3 (company-backend company-dabbrev))
      #("log" 0 3 (company-backend company-dabbrev))
      #("log" 0 3 (company-backend company-dabbrev))
      #("log" 0 3 (company-backend company-dabbrev))
      #("log" 0 3 (company-backend company-dabbrev))
      #("log" 0 3 (company-backend company-dabbrev))
      #("log" 0 3 (company-backend company-dabbrev))
      #("log" 0 3 (company-backend company-dabbrev))
      #("log" 0 3 (company-backend company-dabbrev))
      #("log" 0 3 (company-backend company-dabbrev))
      #("log" 0 3 (company-backend company-dabbrev))
      #("log" 0 3 (company-backend company-dabbrev))
      #("log" 0 3 (company-backend company-dabbrev))
      #("logbook" 0 7 (company-backend company-dabbrev))
      #("logbook" 0 7 (company-backend company-dabbrev))
      #("log" 0 3 (company-backend company-dabbrev))
      #("log" 0 3 (company-backend company-dabbrev))
      #("log" 0 3 (company-backend company-dabbrev))
      #("log" 0 3 (company-backend company-dabbrev))
      #("log" 0 3 (company-backend company-dabbrev))
      #("log" 0 3 (company-backend company-dabbrev))
      #("log" 0 3 (company-backend company-dabbrev))
      #("log" 0 3 (company-backend company-dabbrev))
      #("log" 0 3 (company-backend company-dabbrev))
      #("log" 0 3 (company-backend company-dabbrev))
      #("log" 0 3 (company-backend company-dabbrev))
      #("log" 0 3 (company-backend company-dabbrev))
      #("log" 0 3 (company-backend company-dabbrev))
      #("log" 0 3 (company-backend company-dabbrev))
      #("log" 0 3 (company-backend company-dabbrev))
      #("log" 0 3 (company-backend company-dabbrev))
      #("log" 0 3 (company-backend company-dabbrev))
      #("log" 0 3 (company-backend company-dabbrev))
      #("log" 0 3 (company-backend company-dabbrev))
      #("log" 0 3 (company-backend company-dabbrev))
      #("logger" 0 6 (company-backend company-dabbrev))
      #("log" 0 3 (company-backend company-dabbrev))
      #("logic" 0 5 (company-backend company-dabbrev))
      #("logic" 0 5 (company-backend company-dabbrev))
      #("logic" 0 5 (company-backend company-dabbrev))
      #("log" 0 3 (company-backend company-dabbrev))
      #("log" 0 3 (company-backend company-dabbrev))
      #("log" 0 3 (company-backend company-dabbrev))
      #("log" 0 3 (company-backend company-dabbrev))
      #("login" 0 5 (company-backend company-dabbrev))
      #("login" 0 5 (company-backend company-dabbrev))
      #("login" 0 5 (company-backend company-dabbrev))
      #("login" 0 5 (company-backend company-dabbrev))
      #("login" 0 5 (company-backend company-dabbrev))
      #("log" 0 3 (company-backend company-dabbrev))
      #("login" 0 5 (company-backend company-dabbrev))
      #("log" 0 3 (company-backend company-dabbrev))
      #("log" 0 3 (company-backend company-dabbrev))
      #("log" 0 3 (company-backend company-dabbrev))
      #("login" 0 5 (company-backend company-dabbrev))
      #("log" 0 3 (company-backend company-dabbrev))
      #("log" 0 3 (company-backend company-dabbrev))
      #("log" 0 3 (company-backend company-dabbrev))
      #("log" 0 3 (company-backend company-dabbrev))
      #("log" 0 3 (company-backend company-dabbrev))
      #("log" 0 3 (company-backend company-dabbrev))
      #("log" 0 3 (company-backend company-dabbrev))
      #("log" 0 3 (company-backend company-dabbrev))
      #("log" 0 3 (company-backend company-dabbrev))
      #("logspot" 0 7 (company-backend company-dabbrev))
      #("log" 0 3 (company-backend company-dabbrev))
      #("log" 0 3 (company-backend company-dabbrev))
      #("log" 0 3 (company-backend company-dabbrev))
      #("log" 0 3 (company-backend company-dabbrev))
      #("log" 0 3 (company-backend company-dabbrev))
      #("log" 0 3 (company-backend company-dabbrev))
      #("log" 0 3 (company-backend company-dabbrev))
      #("logy" 0 4 (company-backend company-dabbrev))
      #("log" 0 3 (company-backend company-dabbrev))
      #("log" 0 3 (company-backend company-dabbrev))
      #("logies" 0 6 (company-backend company-dabbrev))
      #("log" 0 3 (company-backend company-dabbrev))
      #("log" 0 3 (company-backend company-dabbrev))
      #("logic" 0 5 (company-backend company-dabbrev))
      #("login" 0 5 (company-backend company-dabbrev))
      #("login" 0 5 (company-backend company-dabbrev))
      #("log" 0 3 (company-backend company-dabbrev))
      #("log" 0 3 (company-backend company-dabbrev))
      #("log" 0 3 (company-backend company-dabbrev))
      #("logged" 0 6 (company-backend company-dabbrev))
      #("log" 0 3 (company-backend company-dabbrev))
      #("log" 0 3 (company-backend company-dabbrev))
      #("login" 0 5 (company-backend company-dabbrev))
      #("log" 0 3 (company-backend company-dabbrev))
      #("log" 0 3 (company-backend company-dabbrev))
      #("log" 0 3 (company-backend company-dabbrev))
      #("logon" 0 5 (company-backend company-dabbrev))
      #("log" 0 3 (company-backend company-dabbrev))
      #("log" 0 3 (company-backend company-dabbrev))
      #("log" 0 3 (company-backend company-dabbrev))
      #("login" 0 5 (company-backend company-dabbrev))
      #("log" 0 3 (company-backend company-dabbrev))
      #("log" 0 3 (company-backend company-dabbrev))
      #("log" 0 3 (company-backend company-dabbrev))
      #("log" 0 3 (company-backend company-dabbrev))
      #("login" 0 5 (company-backend company-dabbrev))
      #("log" 0 3 (company-backend company-dabbrev))
      #("log" 0 3 (company-backend company-dabbrev))
      #("log" 0 3 (company-backend company-dabbrev))
      #("log" 0 3 (company-backend company-dabbrev))
      #("log" 0 3 (company-backend company-dabbrev))
      #("log" 0 3 (company-backend company-dabbrev))
      #("log" 0 3 (company-backend company-dabbrev))
      #("log" 0 3 (company-backend company-dabbrev))
      #("log" 0 3 (company-backend company-dabbrev))
      #("log" 0 3 (company-backend company-dabbrev))
      #("log" 0 3 (company-backend company-dabbrev))
      #("log" 0 3 (company-backend company-dabbrev))
      #("log" 0 3 (company-backend company-dabbrev))
      #("log" 0 3 (company-backend company-dabbrev))
      #("log" 0 3 (company-backend company-dabbrev))
      #("log" 0 3 (company-backend company-dabbrev))
      #("log" 0 3 (company-backend company-dabbrev))
      #("logspot" 0 7 (company-backend company-dabbrev))
      #("logspot" 0 7 (company-backend company-dabbrev))
      #("log" 0 3 (company-backend company-dabbrev))
      #("log" 0 3 (company-backend company-dabbrev))
      #("log" 0 3 (company-backend company-dabbrev))
      #("log" 0 3 (company-backend company-dabbrev))
      #("log" 0 3 (company-backend company-dabbrev))
      #("log" 0 3 (company-backend company-dabbrev))
      #("log" 0 3 (company-backend company-dabbrev))
      #("log" 0 3 (company-backend company-dabbrev))
      #("log" 0 3 (company-backend company-dabbrev))
      #("log" 0 3 (company-backend company-dabbrev))
      #("log" 0 3 (company-backend company-dabbrev))
      #("logy" 0 4 (company-backend company-dabbrev))
      #("logy" 0 4 (company-backend company-dabbrev))
      #("log" 0 3 (company-backend company-dabbrev))
      #("log" 0 3 (company-backend company-dabbrev))
      #("log" 0 3 (company-backend company-dabbrev))
      #("loginwindow" 0 11 (company-backend company-dabbrev))
      #("logd" 0 4 (company-backend company-dabbrev))
      #("logind" 0 6 (company-backend company-dabbrev))
      #("loginwindow" 0 11 (company-backend company-dabbrev))
      #("logd" 0 4 (company-backend company-dabbrev))
      #("logind" 0 6 (company-backend company-dabbrev))
      #("logd" 0 4 (company-backend company-dabbrev))
      #("logd" 0 4 (company-backend company-dabbrev))
      #("logd" 0 4 (company-backend company-dabbrev))
      #("logind" 0 6 (company-backend company-dabbrev))
      #("loginwindow" 0 11 (company-backend company-dabbrev))
      #("logd" 0 4 (company-backend company-dabbrev))
      #("log" 0 3 (company-backend company-dabbrev))
      #("log" 0 3 (company-backend company-dabbrev))
      #("log" 0 3 (company-backend company-dabbrev))
      #("log" 0 3 (company-backend company-dabbrev))
      #("log" 0 3 (company-backend company-dabbrev))
      #("log" 0 3 (company-backend company-dabbrev))
      #("logic" 0 5 (company-backend company-dabbrev))
      #("logic" 0 5 (company-backend company-dabbrev))
      #("logic" 0 5 (company-backend company-dabbrev))
      #("logic" 0 5 (company-backend company-dabbrev))
      #("logic" 0 5 (company-backend company-dabbrev))
      #("logic" 0 5 (company-backend company-dabbrev))
      #("logic" 0 5 (company-backend company-dabbrev))
      #("logic" 0 5 (company-backend company-dabbrev))
      #("logic" 0 5 (company-backend company-dabbrev))
      #("log" 0 3 (company-backend company-dabbrev))
      #("logspot" 0 7 (company-backend company-dabbrev))
      #("logic" 0 5 (company-backend company-dabbrev))
      #("logic" 0 5 (company-backend company-dabbrev))
      #("logic" 0 5 (company-backend company-dabbrev))
      #("log" 0 3 (company-backend company-dabbrev))
      #("log" 0 3 (company-backend company-dabbrev))
      #("log" 0 3 (company-backend company-dabbrev))
      #("log" 0 3 (company-backend company-dabbrev))
      #("log" 0 3 (company-backend company-dabbrev))
      #("log" 0 3 (company-backend company-dabbrev))
      #("log" 0 3 (company-backend company-dabbrev))
      #("log" 0 3 (company-backend company-dabbrev))
      #("log" 0 3 (company-backend company-dabbrev))
      #("log" 0 3 (company-backend company-dabbrev))
      #("logspot" 0 7 (company-backend company-dabbrev))
      #("log" 0 3 (company-backend company-dabbrev))
      #("log" 0 3 (company-backend company-dabbrev))
      #("log" 0 3 (company-backend company-dabbrev))
      #("log" 0 3 (company-backend company-dabbrev))
      #("log" 0 3 (company-backend company-dabbrev))
      #("log" 0 3 (company-backend company-dabbrev))
      #("log" 0 3 (company-backend company-dabbrev))
      #("log" 0 3 (company-backend company-dabbrev))
      #("log" 0 3 (company-backend company-dabbrev))
      #("logs" 0 4 (company-backend company-dabbrev))
      #("logs" 0 4 (company-backend company-dabbrev))
      #("log" 0 3 (company-backend company-dabbrev))
      #("log" 0 3 (company-backend company-dabbrev))
      #("log" 0 3 (company-backend company-dabbrev))
      #("log" 0 3 (company-backend company-dabbrev))
      #("log" 0 3 (company-backend company-dabbrev))
      #("log" 0 3 (company-backend company-dabbrev))
      #("log" 0 3 (company-backend company-dabbrev))
      #("log" 0 3 (company-backend company-dabbrev))
      #("log" 0 3 (company-backend company-dabbrev))
      #("log" 0 3 (company-backend company-dabbrev))
      #("log" 0 3 (company-backend company-dabbrev))
      #("log" 0 3 (company-backend company-dabbrev))
      #("logspot" 0 7 (company-backend company-dabbrev))
      #("log'ах" 0 6 (company-backend company-dabbrev))
      #("log" 0 3 (company-backend company-dabbrev))
      #("log" 0 3 (company-backend company-dabbrev))
      #("log" 0 3 (company-backend company-dabbrev))
      #("log" 0 3 (company-backend company-dabbrev))
      #("log" 0 3 (company-backend company-dabbrev))
      #("log" 0 3 (company-backend company-dabbrev))
      #("log" 0 3 (company-backend company-dabbrev))
      #("log" 0 3 (company-backend company-dabbrev))
      #("log" 0 3 (company-backend company-dabbrev))
      #("logs" 0 4 (company-backend company-dabbrev))
      #("log" 0 3 (company-backend company-dabbrev))
      #("log" 0 3 (company-backend company-dabbrev))
      #("log" 0 3 (company-backend company-dabbrev))
      #("logs" 0 4 (company-backend company-dabbrev))
      #("logging" 0 7 (company-backend company-dabbrev))
      #("log" 0 3 (company-backend company-dabbrev))
      #("loglevel" 0 8 (company-backend company-dabbrev))
      #("log" 0 3 (company-backend company-dabbrev))
      #("log" 0 3 (company-backend company-dabbrev))
      #("log" 0 3 (company-backend company-dabbrev))
      #("logotutorial" 0 12 (company-backend company-dabbrev))
      #("logo" 0 4 (company-backend company-dabbrev))
      #("logo" 0 4 (company-backend company-dabbrev))
      #("logo" 0 4 (company-backend company-dabbrev))
      #("logo" 0 4 (company-backend company-dabbrev))
      #("log" 0 3 (company-backend company-dabbrev))
      #("logy" 0 4 (company-backend company-dabbrev))
      #("logy" 0 4 (company-backend company-dabbrev))
      #("logy" 0 4 (company-backend company-dabbrev))
      #("log" 0 3 (company-backend company-dabbrev))
      #("log" 0 3 (company-backend company-dabbrev))
      #("log" 0 3 (company-backend company-dabbrev))
      #("log" 0 3 (company-backend company-dabbrev))
      #("logic" 0 5 (company-backend company-dabbrev))
      #("logy" 0 4 (company-backend company-dabbrev))
      #("logbook" 0 7 (company-backend company-dabbrev))
      #("logic" 0 5 (company-backend company-dabbrev))
      #("logbook" 0 7 (company-backend company-dabbrev))
`

**Comment by dgutov** [comment]
Does the error go away if you revert https://github.com/company-mode/company-mode/commit/c357d5acf7f1cc685fd89b3dccb1d72e0f96886b?

Do you have a fuller scenario to reproduce it, step by step? I don't see the error with a new capture file.

**Comment by dgutov** [comment]
By the way, you also seem to be using the `company-sort-by-occurrence` transformer. If all else fails, you can `(setq company-transformers nil)`.

**Comment by srustamo** [comment]
Let me try what you suggested. 

Meanwhile, I'm more concerned about not having all open buffers as candidates sources in the `company-20160320.543`. All things equal, `company-20160211.520` includes all open buffers as candidates, whilst the former does not.

**Comment by dgutov** [comment]
That's not true, it still uses all buffers. But, like before, there is a time limit on collecting candidates, which, depending on the number of buffers you have open and their sizes, can cut off some buffers from consideration.

Since bdf6b22, though, the process of collecting the candidates has become somewhat slower. That seems to be a necessary outcome of making `company-dabbrev-char-regexp` a `defcusom` (which it has been for years), see the related issues.

**Comment by dgutov** [comment]
Feel free to prove me wrong, of course.

**Comment by dgutov** [comment]
@srustamo Any news?

**Comment by srustamo** [comment]
Sorry, I'm tied up with work, feel free to close this issue, I hope I can
reopen it when I get a bit of time to investigate it.
