### ISSUE TITLE
Question: how toggle company-mode with $ prefix?

### ISSUE THREAD

**Issue by AbyChan** [company-mode/company-mode#490]
company-mode can not toggle when prefix is "$", anybody help me?

**Comment by dgutov** [comment]
What major mode?

Anyway, see https://www.emacswiki.org/emacs-test/EmacsSyntaxTable.

**Comment by AbyChan** [comment]
(modify-syntax-entry ?| "\$")
??
I try and I can not success.. T-T

**Comment by dgutov** [comment]
Sorry, you seem to be very new to Emacs.

Please direct your question to [ESE](http://emacs.stackexchange.com/).

**Comment by AbyChan** [comment]
thank you
