### ISSUE TITLE
how to company function name in lua mode?

### ISSUE THREAD

**Issue by yinchunlong** [company-mode/company-mode#493]
My test step:
1.  (add-hook 'lua-mode-hook 'company-mode)
2. use command : gtags --gtagslabel=ctags to generate tag database.
3. calling company-gtags manually

But it's not working. 
Is there anyone can help me to config company-mode for lua-mode.

**Comment by dgutov** [comment]
Doesn't work how? Shows no completions at all?

**Comment by stardiviner** [comment]
@yinchunlong There is an repo called `company-lua` [https://github.com/ptrv/company-lua](company-lua). But it is not in MELPA yet.

**Comment by yinchunlong** [comment]
@dgutov Only  complete function and keyword which in the Editing file, not through tag database.

**Comment by yinchunlong** [comment]
@stardiviner ok, i will test it. thanks.

**Comment by dgutov** [comment]
@yinchunlong Does ctags parse your project fine? Try using it by itself first (run `ctags -R -e`). Does it generate a `TAGS` file with all your definitions?

**Comment by yinchunlong** [comment]
@dgutov ![image](https://cloud.githubusercontent.com/assets/11457359/14349977/1569880c-fcf9-11e5-94a7-4f45133518ec.png)
it generate a TAGS.

**Comment by dgutov** [comment]
OK. The contents of that file seem problematic, though.

If you type `cla`, do you get `classafterlistener` in completions?

**Comment by yinchunlong** [comment]
when i type cla, i get nothing

**Comment by dgutov** [comment]
After running `gtags --gtagslabel=ctags`, right?

**Comment by yinchunlong** [comment]
![image](https://cloud.githubusercontent.com/assets/11457359/14350191/68dffd1c-fcfa-11e5-9a6b-85061ef8c9c6.png)
still can't complete

**Comment by dgutov** [comment]
All right, thanks. I'll take a look.

**Comment by yinchunlong** [comment]
i use spacemacs in windows, here is my config file:
![qq 20160407200409](https://cloud.githubusercontent.com/assets/11457359/14350455/f57f4fe2-fcfb-11e5-8308-8eb6842cf007.png)
![qq 20160407200420](https://cloud.githubusercontent.com/assets/11457359/14350456/f581913a-fcfb-11e5-935c-7387872bc3d6.png)

then i use command : gtags --gtagslabel=ctags to generate tag database in the root of my project.
then i type any function name in a lua file, it can't complete.
 but i can jump to define, through the tag database.
if i miss something, plese tell me.
thank you very much.

**Comment by dgutov** [comment]
Sorry, I have it a try, but haven't managed to make it work either. What I can tell from this, though, is that simply calling `gtags --gtagslabel=ctags` is not enough, you at least need a properly edited `~/.globalrc` which adds Lua as a language to parse, as well as instructs to use `ctags` for that (see https://github.com/leoliu/ggtags/wiki/Install-Global-with-support-for-exuberant-ctags for some mention of that).

You should ask at [emacs.SE](http://emacs.stackexchange.com/) or [ggtags's issue tracker](https://github.com/leoliu/ggtags/issues).

If all else fails, just generate a TAGS file with `ctags -e`, and it will be used for completion.

**Comment by redguardtoo** [comment]
Why not just use ctags directly? then place .ctags into $HOME (https://gist.github.com/redguardtoo/b12ddae3b8010a276e9b) and `ctags -e -R`. company-etags.el should work without setup.

**Comment by yinchunlong** [comment]
@redguardtoo 
i use your "~/.ctags" file , but it not work.

**Comment by redguardtoo** [comment]
@yinchunlong  send me your lua code to chenbin.sh AT gmail
