### ISSUE TITLE
Changing minimum-prefix-length per mode?

### ISSUE THREAD

**Issue by jojojames** [company-mode/company-mode#494]
Is there a way to change the prefix length depending on mode?
I've tried something like this (below), but doesn't seem to work upon buffer re-entry.

``  ;; changing prefix lengths depending on mode
  (defun set-company-min-prefix-length (len)
    (setq company-minimum-prefix-length len))

  (add-hook 'eshell-mode-hook (apply-partially #'set-company-min-prefix-length 5))
  (add-hook 'term-mode-hook (apply-partially #'set-company-min-prefix-length 5))
  (add-hook 'prog-mode-hook (apply-partially #'set-company-min-prefix-length 1))
``

**Comment by dgutov** [comment]
`set-company-min-prefix-length` needs to use `make-local-variable`.

**Comment by jojojames** [comment]
Thanks, works.
