### ISSUE TITLE
completions with full-width characters

### ISSUE THREAD

**Issue by holomorph** [company-mode/company-mode#495]
Hi. When there are full-width characters in the completion candidates, I find that the popup gets badly formatted in that the width is not always the same.  There seems to be a lot of code carefully considering the display width of characters; so far I have had no luck finding the cause.  Further, in a terminal, full-width characters appear to be getting prepended with NBSP (displayed as underscore).

FWIW, I encountered this completing a docstring in elisp. I can only guess the colon was full-width: don't know the origin of that completion.
![eg](https://cloud.githubusercontent.com/assets/2336816/14270036/28263cda-fab8-11e5-9a39-6099c20e268a.png)

A contrived example in elisp from emacs -nw -Q:

```
(package-initialize)
(company-mode)
(defun hello-world ())
(defun hello-ゟ ())
```

![mwe](https://cloud.githubusercontent.com/assets/2336816/14270046/371a41e6-fab8-11e5-8434-f705c0dfd62d.png)

This is on emacs 5283593 (master, 20 March).  Reproducible for me in company from GNU ELPA and company-mode master. Oh, and FWIW `(string-width "ゟ")` does indeed return 2.

**Comment by dgutov** [comment]
Hi!

Overall, it's a known issue, see #207.

> Further, in a terminal, full-width characters appear to be getting prepended with NBSP (displayed as underscore).

It's not an NBSP, it's a somewhat random character I've used that's usually displayed as a very narrow piece of whitespace, see `company--clean-string`. It causing problems in non-graphical mode is new to me. I'll try to look for a better solution.

Do you use Emacs primarily in the terminal?

**Comment by holomorph** [comment]
Dang, didn't find #207.

> Do you use Emacs primarily in the terminal?

Yes. I'm generally using a vte3 based one called termite; however it's shown as an underscore in xterm as well, apparently.  Thanks for the clues, I'll read the other issue(s) as well.
