### ISSUE TITLE
Company and provided features.

### ISSUE THREAD

**Issue by dschrempf** [company-mode/company-mode#497]
Hello

thank you for this great package.  I realized that `company` does not provide completion for provided features in Emacs Lisp.  I.e., if I have in a Lisp file:
    (provide 'feature)
then I cannot complete `feature`.  If this should work normally, please correct me.

Best,
Dominik

**Comment by dgutov** [comment]
It does not. Completing `provide` argument doesn't sounds very useful to me anyway, but if you want this, try `M-x report-emacs-bug`.

`company-mode` delegates Emacs Lisp completion to the built-in functionality.

**Comment by dschrempf** [comment]
I am sorry, I think I misphrased my question.  I meant that if a feature `feature` is provided somewhere, then it is not completed when I require it somewhere else.  I think this is very useful and it is definitely parsed by semantic so I thought that it should work.  Thanks, Dominik.

**Comment by dgutov** [comment]
All right, that makes more sense, but my answer remains the same if you're using `company-capf` for Emacs Lisp (which I think everybody does).

I don't know if it's feasible to use `company-semantic` for completion in Elisp buffers, but probably not.
