### ISSUE TITLE
Release 0.9

### ISSUE THREAD

**Issue by bbatsov** [company-mode/company-mode#498]
A lot of time has passed since company 0.8. Seems to me it's time for a new release.

**Comment by dgutov** [comment]
Maybe you're right. I was hoping to solve at least a couple of the major problems that we all know about before it, but never found the time.

**Comment by bbatsov** [comment]
I've learned that it's better to do small releases often, than try to stuff a ton of features that end up delaying a release significantly. :-) Anyways, up to you.

**Comment by dgutov** [comment]
Looks like it's about ready. I'll make the release in a couple of days if nothing crops up.

**Comment by bbatsov** [comment]
Sounds good!

On Monday, 20 June 2016, Dmitry Gutov <notifications@github.com> wrote:

> Looks like it's about ready. I'll make the release in a couple of days if
> nothing crops up.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/company-mode/company-mode/issues/498#issuecomment-227038438>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAGVyiaasH-7O706qX1-pG4cTFVVqPvjks5qNfsZgaJpZM4IGkYh>
> .
>


-- 
Best Regards,
Bozhidar Batsov

http://www.batsov.com

**Comment by redguardtoo** [comment]
Finally! Thanks!

**Comment by dgutov** [comment]
> Can you add documentation about tweaking company-backends on your home page?

What kind of documentation? If you mean the information from the `company-backends` docstring, then it could be in the manual. But someone will have to write it first.

**Comment by redguardtoo** [comment]
at home page, maybe  inside section "see also", many people don't know they can tweak `company-backends`,

**Comment by dgutov** [comment]
Really?

> To see or change the list of enabled back-ends, type M-x customize-variable RET company-backends.

> To customize other aspects of its behavior, type M-x customize-group RET company.

**Comment by redguardtoo** [comment]
I think users need some friendly hint that they could tweak `company-backends` sometimes (maybe including a simple sample). Some people just don't know `company-backends` exist.

**Comment by dgutov** [comment]
I wouldn't say no if someone were to contribute a good tutorial.

Anyway, doing the release now. :rocket:
