### ISSUE TITLE
Symbol's function definition is void: global-company-mode

### ISSUE THREAD

**Issue by cyrus-and** [company-mode/company-mode#5]
I've added `(global-company-mode)` to my `.emacs` and I get that error on startup. Everything works fine when I manually eval that function or when I issue `M-x global-company-mode`.

company-mode is installed from GNU ELPA.

`M-x emacs-version`:

```
GNU Emacs 24.3.1 (x86_64-unknown-linux-gnu, GTK+ Version 2.24.10) of 2013-03-24 on andrea
```

**Comment by zhzw3889** [comment]
I meet the  same problem. And after adding these three line in .emacs ,ti works too.

**Comment by tangrammer** [comment]
👍 thanks!
