### ISSUE TITLE
How to works with multiple backends

### ISSUE THREAD

**Issue by kangjianbin** [company-mode/company-mode#500]
Hi all,

I want to use company for c-mode with  '(company-ycmd company-gtags).
I want company to try company-ycmd first, if there is no candidate, then try company-gtags
How ever I found that only company-ycmd was selected and company-gtags never called.
My configuration is:
```lisp
(defun my-c-mode-ycmd-hook ()
  (ycmd-mode t)
  (setq company-auto-complete t)
  (setq company-minimum-prefix-length 3)
  (setq company-backends
        '(company-c-headers company-ycmd company-gtags)))
```
Is there any mistake in my configuration?

Another question: For 'company-auto-complete',  can I use only 'company-ycmd'?

Thanks for your great work.

**Comment by dgutov** [comment]
https://github.com/Wilfred/company-try-hard/ could be a partial answer.
