### ISSUE TITLE
company-select-next-or-abort got Wrong type argument

### ISSUE THREAD

**Issue by futurist** [company-mode/company-mode#501]
When add below line,

````
  (define-key company-mode-map "\C-n" 'company-select-next-or-abort)
````

after press C-n, the error popup:

> Wrong type argument: number-or-marker-p, nil

Is this the wrong usage?

I want to map C-n, C-p only when there's company candidates popup, if no popup, then do normal action. This is the way auto-complete, which is very convenient.

Or is there any other way to do this?

**Comment by dgutov** [comment]
Try using `company-active-map` instead.

**Comment by futurist** [comment]
Oh, tested it's worked!

What's the different between `company-active-map` and `company-mode-map` ?

Should always use the first one?

**Comment by dgutov** [comment]
> company-active-map

See its docstring.

> Should always use the first one?

For this purpose, yes.
