### ISSUE TITLE
proposal: add undo-boundary for <space>/SPC key

### ISSUE THREAD

**Issue by futurist** [company-mode/company-mode#502]
I've configured below code and found it's handy when selecting wrong candidate:

```lisp
  (define-key company-active-map (kbd "<SPC>") 
    '(lambda()(interactive) 
        (insert " ") (undo-boundary) (company-complete-selection)))
```

So when sometimes you don't want completing, but you've selected it using `SPC`, just `undo` to get what you want.

Please estimate whether it's maybe a new feature for `company`

Thanks!

**Comment by dgutov** [comment]
Hi!

Please try this patch out:

```diff
diff --git a/company.el b/company.el
index 23ed09a..a06b777 100644
--- a/company.el
+++ b/company.el
@@ -1428,6 +1428,7 @@ from the rest of the backends in the group, if any, will be left at the end."
       ;; auto-complete
       (save-excursion
         (goto-char company-point)
+        (undo-boundary)
         (let ((company--auto-completion t))
           (company-complete-selection))
         nil))

```

It adds undo boundary when `company-auto-complete` is used.

**Comment by futurist** [comment]
after try I think it's better to avoid the `undo` action. Since there's so many keys like <kbd>.</kbd> and <kbd>=</kbd>, etc. will trigger the first candidate accidentally, can some option to avoid this? I mean only certain key can complete the current candidate, other keys will abort silently.

**Comment by dgutov** [comment]
Sure: customize `company-auto-complete-chars`.

**Comment by futurist** [comment]
Yes, it's worked! thank you!
