### ISSUE TITLE
Can I set up a buffer search whitelist for dabbrev?

### ISSUE THREAD

**Issue by JunnanZ** [company-mode/company-mode#504]
Customizing `company-dabbrev-other-buffers` can only make `company` search for all other buffers or buffers with the same major mode. And I can also ignore buffers whose names match specific regex. However, can I make it search only buffers with specific name or modes? Setting up a whitelist instead of ignoring some buffers. Or can I make it search only buffers in a specific folder? Something like that.

**Comment by dgutov** [comment]
I suppose we can allow `company-dabbrev-ignore-buffers` to be a predicate function that takes a buffer as an argument. Would that be enough?

**Comment by JunnanZ** [comment]
@dgutov Thanks for your reply! However, I'm not very familiar with elisp, so would you mind elaborating on that predicate function thing? An example would be really nice :)

**Comment by dgutov** [comment]
A predicate is a function that returns a boolean value. Or a value that the callers are expected to interpret as boolean anyway. It's not an Elisp-specific concept.

The different conditions you've given as examples hint at writing various predicates. If you're not comfortable with Elisp yet, maybe you should get familiar with it first (there are tutorials, as well as several places where you can ask general Emacs questions), and then get back to this discussion.

**Comment by JunnanZ** [comment]
@dgutov Ah, I think I misunderstood you in my last comment and thought I can write something like right now to customize the filter. So are you suggesting that you can change how `company-dabbrev-ignore-buffers` works in `company-mode`?

**Comment by dgutov** [comment]
Yup. It would be a relatively small change.

**Comment by JunnanZ** [comment]
That would be great!

**Comment by dgutov** [comment]
Please see if this patch does what you're asking. Do you know how to apply it?

```diff
diff --git a/company-dabbrev.el b/company-dabbrev.el
index 3a533d5..63886aa 100644
--- a/company-dabbrev.el
+++ b/company-dabbrev.el
@@ -41,8 +41,10 @@ buffers with the same major mode.  See also `company-dabbrev-time-limit'."
                  (const :tag "All" all)))
 
 (defcustom company-dabbrev-ignore-buffers "\\`[ *]"
-  "Regexp matching the names of buffers to ignore."
-  :type 'regexp)
+  "Regexp matching the names of buffers to ignore.
+Or a predicate function that returns non-nil for such buffers."
+  :type '(choice (regexp :tag "Regexp")
+                 (function :tag "Predicate")))
 
 (defcustom company-dabbrev-time-limit .1
   "Determines how many seconds `company-dabbrev' should look for matches."
@@ -137,14 +139,16 @@ This variable affects both `company-dabbrev' and `company-dabbrev-code'."
                                                   ignore-comments)))
     (when other-buffer-modes
       (cl-dolist (buffer (delq (current-buffer) (buffer-list)))
-        (with-current-buffer buffer
-          (when (if (eq other-buffer-modes 'all)
-                    (not (string-match-p company-dabbrev-ignore-buffers
-                                         (buffer-name)))
-                  (apply #'derived-mode-p other-buffer-modes))
-            (setq symbols
-                  (company-dabbrev--search-buffer regexp nil symbols start
-                                                  limit ignore-comments))))
+        (unless (if (stringp company-dabbrev-ignore-buffers)
+                    (string-match-p company-dabbrev-ignore-buffers
+                                    (buffer-name buffer))
+                  (funcall company-dabbrev-ignore-buffers buffer))
+          (with-current-buffer buffer
+            (when (or (eq other-buffer-modes 'all)
+                      (apply #'derived-mode-p other-buffer-modes))
+              (setq symbols
+                    (company-dabbrev--search-buffer regexp nil symbols start
+                                                    limit ignore-comments)))))
         (and limit
              (> (float-time (time-since start)) limit)
              (cl-return))))

```

**Comment by JunnanZ** [comment]
Yeah, I applied the patch and wrote a simple function to test it, something like this:

    (defun company-dabbrev-ignore-notbib-buffers (buffer)
      "ignore all buffers other than *.bib"
      (not (string-match-p "\\.bib"
	    	       (buffer-name buffer))))
    (setq company-dabbrev-ignore-buffers 'company-dabbrev-ignore-notbib-buffers)

However, it didn't work and said:

> Company: backend company-dabbrev error "Wrong type argument: stringp, company-dabbrev-ignore-notbib-buffers" with args (candidates xxx)

I just learned some basic elisp and I couldn't find what's wrong after hours of googling :(. Would you mind taking a look? Thanks.

**Comment by dgutov** [comment]
How did you apply the patch? Did you re-evaluate the changed function?

**Comment by JunnanZ** [comment]
Ahh, no, I thought it will auto re-evaluate itself. I just opened the patch in `diff-mode` and applied it. After re-evaluating them, it worked! But I have to evaluate those changed function every time I open emacs? Or do I have to do something more?

**Comment by dgutov** [comment]
> But I have to evaluate those changed function every time I open emacs?

In general, you'd just need to recompile the file (with `M-x byte-compile-file`), at least if it's already compiled (`.elc` is present). Or remove the `.elc` file (which might make it work a little bit slower).

Anyway, if the patch does what you needed, I'll just push it to `master`.

**Comment by JunnanZ** [comment]
Recompiling did the trick! Thanks for your patience:)

**Comment by dgutov** [comment]
Thanks for testing!
