### ISSUE TITLE
Don't use *Help* when showing help

### ISSUE THREAD

**Issue by hrehfeld** [company-mode/company-mode#505]
If I'm looking at the documentation for something while I'm typing code, I don't want my completion to mess with the *Help* buffer that I'm looking at.

**Comment by dgutov** [comment]
I agree, but it should be a bug report toward Emacs core. The code doing that is situated there (`elisp--company-doc-buffer`). Bonus points for attaching a patch together with the bug report.

**Comment by hrehfeld** [comment]
OK, too bad, sorry for the complain ;-)
