### ISSUE TITLE
a question about company-dabbrev--search-buffer

### ISSUE THREAD

**Issue by tumashu** [company-mode/company-mode#507]
hello, i want to know why company-dabbrev--search-buffer search two times, before pos and after pos, for sort reason?  why we don't just search from point-min?

**Comment by tumashu** [comment]
i use this function in chinese-pyim, i need to know the reason

**Comment by dgutov** [comment]
Because we want to prioritize the matches right above point. We even might not get to the beginning of the buffer if it's huge enough.

**Comment by tumashu** [comment]
thanks very much
