### ISSUE TITLE
Popups flickers with asynchronous backend and caching disabled

### ISSUE THREAD

**Issue by Yevgnen** [company-mode/company-mode#510]
Hi,

Thanks for the awesome package !

I find that what when grouping a asynchronous backend with other backends, the company candidate menu flashes quite often each time I type a single char. This behavior is not occurred with manual completion.Details can be found in [https://github.com/syohex/emacs-company-jedi/issues/16](https://github.com/syohex/emacs-company-jedi/issues/16)

In my opinion, grouping backends is still quite useful even the 'main backend' works fine in most situations. So, if I want to use auto completion and grouping backends, is it possible or will it be difficult to fix this ?

Any help will be appreciated :)

**Comment by dgutov** [comment]
Thanks for the report, it's a somewhat known problem, see also #337 and the linked discussion.

When there is a grouped backend in a group, the whole group works asynchronously. If at least one of the backends in it disables caching, the caching is disabled, again, for the whole group.

The async+no-cache combination currently leads to flickering.

**Comment by dgutov** [comment]
Should work better now. Also see #654 for some related comments (and the end).
