### ISSUE TITLE
Candidates of company-mode

### ISSUE THREAD

**Issue by zosy** [company-mode/company-mode#512]
the candidates  right border cannot be aligned

OS:centos 7
emacs :24.31
company-mode: up to date

**Comment by dgutov** [comment]
Do you have a screenshot?

**Comment by zosy** [comment]
https://github.com/zosy/zosy.github.com/blob/master/images/company-mode-scr.png

**Comment by zosy** [comment]
@dgutov thanks for replay,here the screenshot.
[https://github.com/zosy/zosy.github.com/blob/master/images/company-mode-scr.png](url)

**Comment by dgutov** [comment]
OK, I see.

You'll need to use a monospaced font. The overlay-based popup rendering that we use isn't compatible with proportional fonts.

**Comment by zosy** [comment]
@dgutov i changed the font, it's work fine now,thanks:)
