### ISSUE TITLE
Add backend group keyword to keep completions from backends separate

### ISSUE THREAD

**Issue by dgutov** [company-mode/company-mode#513]
See https://github.com/company-mode/company-mode/issues/432#issuecomment-217753127 for the background.

I'm thinking the keyword can be called simple `:separate`, and make the `:sorted` keyword unnecessary. If a group contains `:separate`, completions from different backends are kept separate, in the order in which the backends are specified in the group. Within each backend, the completions would be sorted (or not) depending on whether the backend specifies `sorted`.

**Comment by dgutov** [comment]
Note: using this approach, we won't remove duplicates (entries with the same string value and annotation) coming from different backends if there's more than one completion from each backend.

Using transformers would be preferable in this respect.

**Comment by aaronjensen** [comment]
Would you not remove duplicates because it would be expensive? It would be strongly preferred to remove duplicates.

**Comment by vspinu** [comment]
Isn't this just a linguistic change? I do like :separate better than :sorted, but it looks that what you have in mind is what :sorted already does, particularly not removing duplicates.

**Comment by dgutov** [comment]
> Would you not remove duplicates because it would be expensive?

It might. Currently, we have a nice linear search that removes consecutive duplicates in the list after it's sorted. It also fetches annotations lazily, only after it sees two equal strings (and then remembers the fetched annotations).

To remove the duplicates without sorting everything, and to keep the above property, it seems the best we could do is: save the unsorted list, copy it to a new one, sort the copy, walk through the copy, find the duplicates and put every removal into a hash table (using `eq`), and then go through the saved unsorted list and remove the elements that are present in the hash table. That's doable, but might be an overkill.

> I do like :separate better than :sorted, but it looks that what you have in mind is what :sorted already does, particularly not removing duplicates.

It's close, but `:separate` would sort the completions within each chunk (as long as the respective backend doesn't declare `sorted`). That seems more appropriate.
