### ISSUE TITLE
`company-complete` conflicts with `company-template-forward-field` with TAB

### ISSUE THREAD

**Issue by demon386** [company-mode/company-mode#515]
I use company-go, and by default it will use `company-template` to insert parenthese and arguments after completing. In this state, if I want to complete another function inside the parenthese, "TAB" will invoke `company-template-forward-field` instead of `company-complete` (as I use "TAB" for completion).

**Comment by dgutov** [comment]
Yup. Keymap assigned via an overlay always takes priority. We should consider assigning `company-active-map` via an overlay as well.

Someone should take a stab at this. See `auto-complete` for an example.
