### ISSUE TITLE
company-mode + company-yasnippet + alchemist-company reproducible hang/100% cpu usage

### ISSUE THREAD

**Issue by aaronjensen** [company-mode/company-mode#516]
I'm on Emacs 25 OS X

From `emacs -Q`: 

```
(require 'package)
(add-to-list 'package-archives
             '("melpa" . "https://melpa.org/packages/"))
(package-initialize)

;; For some reason I didn't need this w/ emacs -Q
;; (unless (package-installed-p 'company-mode)
;;  (package-install 'company-mode))

(unless (package-installed-p 'alchemist)
  (package-install 'alchemist))

(unless (package-installed-p 'yasnippet)
  (package-install 'yasnippet))

(add-hook 'elixir-mode-hook
          (lambda ()
            (company-mode)
            (alchemist-mode)
            (setq company-backends '((alchemist-company :with company-yasnippet)))))
```

Then `C-x C-f test.ex`

Then type, one character at a time, pausing for auto completion:

```elixir
Enum.sort_
```

It should hang when you type the `_`. This is when it goes from multiple results to 1.

Multiple `C-g` will usually get you out of it after some time.

**Comment by dgutov** [comment]
Thanks for the report, I see this too. Still looking into the main cause of the freeze, but one problem here is that `alchemist-company-serve-candidates-to-callback` calls `alchemist-company-callback` with a list that looks like `(nil "Enum.sort_by")`. It's apparently caused by this line:

```el
(-insert-at 0 company-prefix candidates)
```

@tonini Could you avoid doing that? `company-prefix` is nil here (it probably gets assigned a bit later), but the line doesn't make much sense to me either way.

**Comment by aaronjensen** [comment]
@dgutov @tonini I believe that is related to https://github.com/tonini/alchemist.el/issues/212 and it'd be great if that line was blown away, it's bothersome. It was intended to [prevent `end` from autocompleting to something else](https://github.com/tonini/alchemist.el/issues/181) which required people to hit `esc` before enter. Of course, this isn't actually a problem for me because I use https://github.com/company-mode/company-mode/issues/343#issuecomment-196028651 (and I've been using smartparens, which adds the `end` for me, but I may stop because it's buggy)

**Comment by dgutov** [comment]
Indeed, it doesn't seem like it should be solved in Alchemist's backend. The solution that I personally prefer is to add `company-keywords` to the same group, but ideas welcome (in a separate issue). This would require adding Elixir's keywords to `company-keywords-alist`, though.

**Comment by dgutov** [comment]
> The solution that I personally prefer is to add company-keywords to the same group

Or just hardcode the list of keywords inside Alchemist, and add the matching ones to the completions list.

**Comment by dgutov** [comment]
> Still looking into the main cause of the freeze

Basically, it happened because `(car nil)` evaluates to nil. I've added an assertion that should make this kind of problem more obvious.

**Comment by aaronjensen** [comment]
Thanks for tracking it down. I'm curious how it ultimately led to a spin.

I'm more curious as to why the `company-prefix` is  `nil` in this case. Why wouldn't it be `sort_`?

**Comment by dgutov** [comment]
> I'm curious how it ultimately led to a spin.

Infloop in `company--strip-duplicates`. The last element (nil) was equal to `(car nil)`. `(equal str str2)` returned t, and the inner loop continued indefinitely. I suppose we can add a `(not (null ...))` in there, but assert should work even better.

> I'm more curious as to why the company-prefix is nil in this case.

`company--begin-new` sets it a bit later than the backend is called for the first time. We don't really expect it to be used in backends.

**Comment by dgutov** [comment]
...and the reason it's necessary to group with `company-yasnippet` to reproduce, is because the latter declares `no-cache`. Which gets propagated to the whole group, with the current `company--multi-backend-adapter` implementation.

**Comment by aaronjensen** [comment]
ah, looks like the `no-cache` was added in https://github.com/company-mode/company-mode/issues/422. I don't understand that entire thread/why it was added exactly, but it explains some of the company performance I had seen (I was wondering why it seemed like it didn't cache...) for now, I will disable `company-yasnippet`. Thanks!

Hopefully @tonini will have some time to fix the cause in alchemist.el.

**Comment by dgutov** [comment]
This is complicated stuff. In the long run, looks like it'd be better if each backend performed its own caching and invalidation.

**Comment by tonini** [comment]
Hi,

Sorry for my late responds about this issue. I removed the wrong usage of `company-prefix` for now -> https://github.com/tonini/alchemist.el/commit/5968c0bde26342aa7a09940c4d5598e0e232c0c3

@aaronjensen could you give this a try and test it again?

**Comment by aaronjensen** [comment]
@tonini it's working for me, thanks!

**Comment by aaronjensen** [comment]
@dgutov what would you like me to do w/ this issue? It was fixed upstream in alchemist and you introduced the assert, so is there anything left for `company-mode` to do here? I'm happy to have it closed. Thanks for tracking it down.

**Comment by dgutov** [comment]
Looks fixes. Thanks all.
