### ISSUE TITLE
Expand completions as you cycle through them?

### ISSUE THREAD

**Issue by ZzAntares** [company-mode/company-mode#517]
Hello, new company user here, so far the experience has been great, however I was wondering if is there a way to make company completion expand the completion candidate as I cycle through the completion candidates, if I keep pressing `TAB` it will replace current word with the next completion candidate, I never have to choose a completion using `RET` since the completion has been expanded earlier I just keep typing.

A gif will explain it better:
![autocompletion](https://cloud.githubusercontent.com/assets/3653680/15452231/facfc30e-1fac-11e6-961e-9c99ec4d7497.gif)

I am so used to this that selecting the completion with `RET` feels like a waste of time :grin:

Is there any setting I could add to make it behave like this? I did try `company-complete-common-or-cycle` but only completes to the common part (as the name implies duh).

Thanks for the help.

**Comment by dgutov** [comment]
Thanks for the nice gif. We've discussed this before, see #343. It also contains a gist implementing this, or something close.

**Comment by ZzAntares** [comment]
Thanks I'll stay tuned to when this will be doable thing.
