### ISSUE TITLE
Company found no clang executable

### ISSUE THREAD

**Issue by rdotdk** [company-mode/company-mode#518]
Hi, I'm using ```Ubuntu 14.04```. Installing clang through package manager gives the clang executable with filename ```clang-3.5```. But the company mode doesn't recognize this and reports that clang executable not found. I have done a workaround by creating symlink for clang.
```
lrwxrwxrwx 1 root root 18 May 22 17:11 /usr/bin/clang -> /usr/bin/clang-3.5*

```
After this the company mode detects clang and works. However i think it should work even if the clang executable name is clang-3.5. Thanks.

**Comment by dgutov** [comment]
There's something wrong with your installation. Here `/usr/bin/clang` is a part of the `clang` package:

```
~ $ which clang
/usr/bin/clang
~ $ ls -l /usr/bin/clang
lrwxrwxrwx 1 root root 25 Feb 12 14:42 /usr/bin/clang -> ../lib/llvm-3.8/bin/clang*
~ $ dpkg -S /usr/bin/clang
clang: /usr/bin/clang
~ $ dpkg -S /usr/lib/llvm-3.8/bin/clang
clang-3.8: /usr/lib/llvm-3.8/bin/clang
~ $ apt show clang
Package: clang
Version: 1:3.8-33ubuntu3
Priority: optional
Section: universe/devel
Source: llvm-defaults (0.33ubuntu3)
Origin: Ubuntu
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Original-Maintainer: LLVM Packaging Team <pkg-llvm-team@lists.alioth.debian.org>
Bugs: https://bugs.launchpad.net/ubuntu/+filebug
Installed-Size: 28.7 kB
Depends: clang-3.8 (>= 3.8~)
Breaks: clang-3.2, clang-3.3, clang-3.4 (<< 1:3.4.2-7~exp1), clang-3.5 (<< 1:3.5~+rc1-3~exp1)
Replaces: clang (<< 3.2-1~exp2), clang-3.2, clang-3.3, clang-3.4 (<< 1:3.4.2-7~exp1), clang-3.5 (<< 1:3.5~+rc1-3~exp1)
Download-Size: 3,210 B
APT-Manual-Installed: yes
APT-Sources: http://ubuntu.unitedcolo.de/ubuntu xenial/universe amd64 Packages
Description: C, C++ and Objective-C compiler (LLVM based)
 Clang project is a C, C++, Objective C and Objective C++ front-end
 for the LLVM compiler. Its goal is to offer a replacement to the GNU Compiler
 Collection (GCC).
 .
 Clang implements all of the ISO C++ 1998 and 2001 standards and also provides
 a partial support of C++1y.
 .
 This is a dependency package providing the default clang compiler.
```

But creating a symlink isn't necessary either way. You can just as well customize `company-clang-executable`.

**Comment by rdotdk** [comment]
Hi @dgutov. Thanks for the quick reply. Before creating symlink i tried customizing the ```company-clang-executable``` to ```/usr/bin/clang-3.5```, but it throws ``` custom-variable-mark-to-save: Symbol's value as variable is void: /usr/bin/clang-3\.5```. Installing ```clang-3.5``` package doesn't produce ```clang``` file in ```/usr/bin```. Instead if ```clang``` is installed using ```sudo apt install clang```, it creates ```/usr/bin/clang``` file.

**Comment by dgutov** [comment]
> i tried customizing the company-clang-executable to /usr/bin/clang-3.5, but it throws custom-variable-mark-to-save

That works just fine here. Maybe create a screencast on how you're doing that, and also specify your Emacs version.

> Instead if clang is installed using sudo apt install clang, it creates /usr/bin/clang file.

Why not do that?

**Comment by rdotdk** [comment]
I do it by ```M-x``` ```customize variable``` -> ```company-clang-executable``` and enter ```/usr/bin/clang-3.5``` in the text box and click ```save and apply```.

Emacs version : ```GNU Emacs 25.1.50.2 (i686-pc-linux-gnu, GTK+ Version 3.10.8) of 2016-04-25```

Installing package clang gives clang version 3.4 and installing clang-3.5 installs the clang version 3.5.

**Comment by dgutov** [comment]
> enter /usr/bin/clang-3.5 in the text box and click save and apply

"Apply and Save". Works fine here in Emacs built both from `emacs-25` and from `master`.

> Installing package clang gives clang version 3.4 and installing clang-3.5 installs the clang version 3.5.

Sorry, you're right. Then you should figure out while customizing fails.

**Comment by rdotdk** [comment]
I've enabled ```toggle-debug-on-error```, this is what i get

```
Debugger entered--Lisp error: (void-variable /usr/bin/clang-3\.5)
  eval(/usr/bin/clang-3\.5)
  custom-variable-mark-to-save((custom-variable :documentation-shown t :custom-state modified :tag "Company Clang Executable" :value company-clang-executable :custom-form mismatch :custom-magic (custom-magic :args (nil) :parent #0 :indent 0 :children ((choice-item :help-echo "Change the state of this item." :format "%[%t%]" :button-prefix widget-push-button-prefix :button-suffix widget-push-button-suffix :mouse-down-action widget-magic-mouse-down-action :tag " State " :parent #1 :indent 0 :button-overlay #<overlay from 256 to 263 in *Customize Option: Company Clang Executable*> :from #<marker (moves after insertion) at 256 in *Customize Option: Company Clang Executable*> :to #<marker at 263 in *Customize Option: Company Clang Executable*>)) :from #<marker (moves after insertion) at 253 in *Customize Option: Company Clang Executable*> :to #<marker at 343 in *Customize Option: Company Clang Executable*> :buttons nil :value nil) :buttons ((custom-group-link :args nil :value company-clang :tag "Company Clang" :parent #0 :indent 0 :button-overlay #<overlay from 384 to 397 in *Customize Option: Company Clang Executable*> :from #<marker (moves after insertion) at 384 in *Customize Option: Company Clang Executable*> :to #<marker at 397 in *Customize Option: Company Clang Executable*>) (documentation-string :args nil :value "Location of clang executable." :indent 3 :visibility-widget custom-visibility :parent #0 :doc-overlay #<overlay from 343 to 375 in *Customize Option: Company Clang Executable*> :buttons nil :from #<marker (moves after insertion) at 343 in *Customize Option: Company Clang Executable*> :to #<marker at 376 in *Customize Option: Company Clang Executable*>) (custom-magic :args (nil) :parent #0 :indent 0 :children ((choice-item :help-echo "Change the state of this item." :format "%[%t%]" :button-prefix widget-push-button-prefix :button-suffix widget-push-button-suffix :mouse-down-action widget-magic-mouse-down-action :tag " State " :parent #2 :indent 0 :button-overlay #<overlay from 256 to 263 in *Customize Option: Company Clang Executable*> :from #<marker (moves after insertion) at 256 in *Customize Option: Company Clang Executable*> :to #<marker at 263 in *Customize Option: Company Clang Executable*>)) :from #<marker (moves after insertion) at 253 in *Customize Option: Company Clang Executable*> :to #<marker at 343 in *Customize Option: Company Clang Executable*> :buttons nil :value nil) (custom-visibility :args nil :value t :help-echo "Hide the value of this option." :on "Hide" :off "Show" :on-glyph "down" :off-glyph "right" :action custom-toggle-hide-variable :parent #0 :indent 0 :suppress-face t :button-overlay #<overlay from 203 to 207 in *Customize Option: Company Clang Executable*> :from #<marker (moves after insertion) at 203 in *Customize Option: Company Clang Executable*> :to #<marker at 207 in *Customize Option: Company Clang Executable*>)) :documentation-indent 3 :comment-widget (custom-comment :parent #0 :value "" :indent 0 :from #<marker at 376 in *Customize Option: Company Clang Executable*> :to #<marker at 376 in *Customize Option: Company Clang Executable*>) :children ((sexp :button-face custom-variable-button-face :format "%v" :tag "company-clang-executable" :parent #0 :value "nil" :indent 0 :field-overlay #<overlay from 234 to 252 in *Customize Option: Company Clang Executable*> :from #<marker (moves after insertion) at 252 in *Customize Option: Company Clang Executable*> :to #<marker at 253 in *Customize Option: Company Clang Executable*>) (custom-comment :parent #0 :value "" :indent 0 :from #<marker at 376 in *Customize Option: Company Clang Executable*> :to #<marker at 376 in *Customize Option: Company Clang Executable*>)) :from #<marker (moves after insertion) at 203 in *Customize Option: Company Clang Executable*> :to #<marker at 398 in *Customize Option: Company Clang Executable*> :comment-shown nil))
  widget-apply((custom-variable :documentation-shown t :custom-state modified :tag "Company Clang Executable" :value company-clang-executable :custom-form mismatch :custom-magic (custom-magic :args (nil) :parent #0 :indent 0 :children ((choice-item :help-echo "Change the state of this item." :format "%[%t%]" :button-prefix widget-push-button-prefix :button-suffix widget-push-button-suffix :mouse-down-action widget-magic-mouse-down-action :tag " State " :parent #1 :indent 0 :button-overlay #<overlay from 256 to 263 in *Customize Option: Company Clang Executable*> :from #<marker (moves after insertion) at 256 in *Customize Option: Company Clang Executable*> :to #<marker at 263 in *Customize Option: Company Clang Executable*>)) :from #<marker (moves after insertion) at 253 in *Customize Option: Company Clang Executable*> :to #<marker at 343 in *Customize Option: Company Clang Executable*> :buttons nil :value nil) :buttons ((custom-group-link :args nil :value company-clang :tag "Company Clang" :parent #0 :indent 0 :button-overlay #<overlay from 384 to 397 in *Customize Option: Company Clang Executable*> :from #<marker (moves after insertion) at 384 in *Customize Option: Company Clang Executable*> :to #<marker at 397 in *Customize Option: Company Clang Executable*>) (documentation-string :args nil :value "Location of clang executable." :indent 3 :visibility-widget custom-visibility :parent #0 :doc-overlay #<overlay from 343 to 375 in *Customize Option: Company Clang Executable*> :buttons nil :from #<marker (moves after insertion) at 343 in *Customize Option: Company Clang Executable*> :to #<marker at 376 in *Customize Option: Company Clang Executable*>) (custom-magic :args (nil) :parent #0 :indent 0 :children ((choice-item :help-echo "Change the state of this item." :format "%[%t%]" :button-prefix widget-push-button-prefix :button-suffix widget-push-button-suffix :mouse-down-action widget-magic-mouse-down-action :tag " State " :parent #2 :indent 0 :button-overlay #<overlay from 256 to 263 in *Customize Option: Company Clang Executable*> :from #<marker (moves after insertion) at 256 in *Customize Option: Company Clang Executable*> :to #<marker at 263 in *Customize Option: Company Clang Executable*>)) :from #<marker (moves after insertion) at 253 in *Customize Option: Company Clang Executable*> :to #<marker at 343 in *Customize Option: Company Clang Executable*> :buttons nil :value nil) (custom-visibility :args nil :value t :help-echo "Hide the value of this option." :on "Hide" :off "Show" :on-glyph "down" :off-glyph "right" :action custom-toggle-hide-variable :parent #0 :indent 0 :suppress-face t :button-overlay #<overlay from 203 to 207 in *Customize Option: Company Clang Executable*> :from #<marker (moves after insertion) at 203 in *Customize Option: Company Clang Executable*> :to #<marker at 207 in *Customize Option: Company Clang Executable*>)) :documentation-indent 3 :comment-widget (custom-comment :parent #0 :value "" :indent 0 :from #<marker at 376 in *Customize Option: Company Clang Executable*> :to #<marker at 376 in *Customize Option: Company Clang Executable*>) :children ((sexp :button-face custom-variable-button-face :format "%v" :tag "company-clang-executable" :parent #0 :value "nil" :indent 0 :field-overlay #<overlay from 234 to 252 in *Customize Option: Company Clang Executable*> :from #<marker (moves after insertion) at 252 in *Customize Option: Company Clang Executable*> :to #<marker at 253 in *Customize Option: Company Clang Executable*>) (custom-comment :parent #0 :value "" :indent 0 :from #<marker at 376 in *Customize Option: Company Clang Executable*> :to #<marker at 376 in *Customize Option: Company Clang Executable*>)) :from #<marker (moves after insertion) at 203 in *Customize Option: Company Clang Executable*> :to #<marker at 398 in *Customize Option: Company Clang Executable*> :comment-shown nil) :custom-mark-to-save)
  #[257 "\300\301\"\302>\205
```

**Comment by dgutov** [comment]
Sorry, that doesn't tell me what went wrong. Try starting with `emacs -Q`.

**Comment by rdotdk** [comment]
FYI, evaluating ``` (setq company-clang-executable "/usr/bin/clang-3.5") ``` in the scratch buffer works and doesn't throw any error.

**Comment by dgutov** [comment]
Yes. But both ways work for me.

**Comment by rdotdk** [comment]
I'm getting the same error log if i try with emacs -Q. I've used the following elisp code in scratch to load company-mode.
```
(require 'package)
(setq package-enable-at-startup nil)
(add-to-list 'package-archives '("melpa" . "https://melpa.org/packages/"))
(package-initialize)
(require 'use-package)
(use-package company)
(global-company-mode 1)
```

Debugger entered--Lisp error: (void-variable /usr/bin/clang-3\.5)
  eval(/usr/bin/clang-3\.5)
  custom-variable-set((custom-variable :documentation-shown t :custom-state modified :tag "Company Clang Executable" :value company-clang-execu$
  widget-apply((custom-variable :documentation-shown t :custom-state modified :tag "Company Clang Executable" :value company-clang-executable :$
  #[257 "\300^A\301\"\302=\205^M^@\303^A\304\"\207" [widget-get :custom-state modified widget-apply :custom-set] 4 "\n\n(fn CHILD)"]((custom-va$
  mapc(#[257 "\300^A\301\"\302=\205^M^@\303^A\304\"\207" [widget-get :custom-state modified widget-apply :custom-set] 4 "\n\n(fn CHILD)"] ((cus$
  custom-command-apply(#[257 "\300^A\301\"\302=\205^M^@\303^A\304\"\207" [widget-get :custom-state modified widget-apply :custom-set] 4 "\n\n(f$
  Custom-set((push-button :tag " Apply " :help-echo "Apply settings (for the current session only)." :action Custom-set :button-overlay #<overl$
  widget-apply((push-button :tag " Apply " :help-echo "Apply settings (for the current session only)." :action Custom-set :button-overlay #<ove$
  widget-apply-action((push-button :tag " Apply " :help-echo "Apply settings (for the current session only)." :action Custom-set :button-overla$
  Custom-newline(260)
  funcall-interactively(Custom-newline 260)
  call-interactively(Custom-newline nil nil)
  command-execute(Custom-newline)

**Comment by rdotdk** [comment]
Just builded and installed emacs from git. The issue is reproducible. ``` GNU Emacs 25.1.50.1 (i686-pc-linux-gnu, GTK+ Version 2.24.23) of 2016-05-22
```

**Comment by dgutov** [comment]
1. Is there a line in your Custom file (your init file, by default) mentioning `company-clang-executable`?

2. What if you try it without `use-package`?

**Comment by rdotdk** [comment]
I don't have any customization for ``` company-clang-executable ``` in my [init file](https://github.com/rdotdk/.emacs.d/blob/master/init.el).

I am able to reproduce the issue without ``` use-package``` with the following code in ``` emacs -nw -Q ```
```
(require 'package)
(setq package-enable-at-startup nil)
(add-to-list 'package-archives '("melpa" . "https://melpa.org/packages/"))
(package-initialize)

(require 'company)
(global-company-mode 1)
```

**Comment by dgutov** [comment]
What does `M-x company-version` say? Do you have the latest installed?

What if you define a similar new variable, like:

```el
(defcustom foo-bar-executable
  (executable-find "sh")
  "Location of sh executable."
  :type 'file)
```

...and try to customize it? Do you see the same problem?

**Comment by rdotdk** [comment]
Company version ``` Company version: 0.9.0-cvs ```. Customizing ``` foo-bar-executable ``` with value ```/usr/bin/clang-3.5 ``` works.

**Comment by dgutov** [comment]
Okay then. Please try this:

1. Remove the first four lines (the ones containing the word "package") from your example.
2. Use `(add-to-list 'load-path "~/.emacs.d/elpa/company-xxx.yyy")` instead (with the correct directory).

If the example works then, the culprit could be one of the packages you have installed. You could try finding it using `M-x rgrep` in `~/.emacs.d/elpa`, searching for `company-clang-executable`.

**Comment by rdotdk** [comment]
I'm able to reproduce the issue with the following code. It throws the same error on ```customize-variable```.
```
(add-to-list 'load-path "~/.emacs.d/elpa/company-20160514.1750")

(require 'company)
(global-company-mode 1)
```

**Comment by dgutov** [comment]
I've tried it out with `GNU Emacs 25.1.50.14 (x86_64-unknown-linux-gnu, GTK+ Version 3.18.9) of 2016-05-24` (and the exact same version of company), and still can't reproduce.

Sorry, I have no idea what else to try. Maybe `make clean && ./autogen.sh && ./configure && make` again?

**Comment by rdotdk** [comment]
@dgutov I have three different versions of emacs installed in my system and i am able to reproduce the issue with all the versions of emacs. I don't think re-installing will fix this issue. For now I'll customize the variable in ``` init file ``` using ``` (setq company-clang-executable "/usr/bin/clang-3.5") ```. Thanks for your time. Much appreciated.

**Comment by dgutov** [comment]
> I have three different versions of emacs installed in my system and i am able to reproduce the issue with all the versions of emacs. I don't think re-installing will fix this issue.

Fair enough. One last thing you could do, I guess, is to try reinstalling the `company` package. Maybe the contents of its installation directory got corrupted somehow?

Anyway, using `setq` sounds good to me.

**Comment by rdotdk** [comment]
> Fair enough. One last thing you could do, I guess, is to try reinstalling the company package. Maybe the contents of its installation directory got corrupted somehow?

No luck. I'll stick with ```setq```. Thanks

**Comment by WarpspeedSCP** [comment]
When I try `customize-variable` on `company-clang-executable`, it says

`Symbol's value as variable is void: /usr/bin/clang-3\.8`.

Any fixes?

**Comment by WarpspeedSCP** [comment]
When I try `customize-variable` on `company-clang-executable`, it says

`Symbol's value as variable is void: /usr/bin/clang-3\.8`.

Any fixes?

*EDIT* nvm, I fixed it.
