### ISSUE TITLE
company--create-lines causes an error if annotation contains a newline

### ISSUE THREAD

**Issue by stakemori** [company-mode/company-mode#520]
For some backends, annotation contains a newline. And if `company-tooltip-align-annotations` is non-`nil` and annotation contains a newline, then `company--create-lines` raise an error in Emacs 25.0.94. 

I guess this is because `(comment-string-strip STR BEFOREP AFTERP)` returns `nil` if `STR` contains a newline (e.g. (comment-string-strip "foo\nbar" t nil) returns `nil`). I would suggest replacing `comment-string-strip` by `string-trim-left` or some equivalent code. Thanks.

**Comment by dgutov** [comment]
> For some backends, annotation contains a newline.

How about you just don't do that?

**Comment by stakemori** [comment]
> How about you just don't do that?

O.K. I will contact the author of the backend.

**Comment by dgutov** [comment]
Thanks.

**Comment by stakemori** [comment]
I have just made a [new pull request](https://github.com/proofit404/company-anaconda/pull/21). Please feel free to close this issue.
