### ISSUE TITLE
Why is C-w disabled in company mode

### ISSUE THREAD

**Issue by GuillaumeLeclerc** [company-mode/company-mode#521]
Hello,

when I'm in company-mode I'm not able to use the C-w do delete word behind cursor. How can I re-enable this ? 

Thank you

**Comment by GuillaumeLeclerc** [comment]
I tried doing this: `(define-key company-mode-map "\C-w" nil)` and it does not seem to work. C-w still trigger the original "show source" feature. Do I absolutely have to fork company-mode unbind this shortcut ?

**Comment by syohex** [comment]
I suppose you should set `company-active-map` instead of `company-mode-map`.

**Comment by GuillaumeLeclerc** [comment]
It works thanks !
