### ISSUE TITLE
Ignore certain directories in company-files?

### ISSUE THREAD

**Issue by ksrb** [company-mode/company-mode#522]
Specifically is there a way to remove directories like the .git folder from the list of results?

**Comment by dgutov** [comment]
Hi!

Supposedly, you would customize `completion-ignored-extensions`, but `.git/` is already there, and it doesn't work. See debbugs.gnu.org/23631.

**Comment by dgutov** [comment]
And apparently Emacs works as designed. I'll see about implementing this inside `company-files`.
