### ISSUE TITLE
company-semantic attempts to uncompress and parse tons of .el.gz files

### ISSUE THREAD

**Issue by sooheon** [company-mode/company-mode#525]
If I have company-mode and semantic mode turned on in an elisp file without any further customisation, typing within a comment will sometimes block input, and I will get a load of messages that look like this:

```
uncompressing mode-local.el.gz...done
Parsing mode-local.el.gz (LL)...done
uncompressing calc-aent.el.gz...done
Parsing calc-aent.el.gz (LL)...done
uncompressing mh-buffers.el.gz...done
File elpa/auto-compile-20160424.418/auto-compile.el added to project /Users/sooheon/.emacs.d/ cache.
Parsing auto-compile.el (LL)...done
uncompressing mh-inc.el.gz...done
uncompressing mh-print.el.gz...done
Parsing mh-print.el.gz (LL)...done
Parsing lispy-tags.el (LL)...done
File elpa/magit-20160528.2140/magit-utils.el added to project /Users/sooheon/.emacs.d/ cache.
Parsing magit-utils.el (LL)...done
uncompressing rmail.el.gz...done
Parsing rmail.el.gz (LL)...done
uncompressing comint.el.gz...done
Parsing comint.el.gz (LL)...done
uncompressing mule-diag.el.gz...done
Parsing mule-diag.el.gz (LL)...done
uncompressing titdic-cnv.el.gz...done
Parsing titdic-cnv.el.gz (LL)...done
```

I'm not sure how to reproduce it exactly, but it happens consistently enough when editing comments in elisp in my .emacs.d. I've sort of inferred that company completion and semantic seem to cause this, though I can't be sure (without 100% reproduction). What is this behaviour, and how can I stop it from happening while typing?

**Comment by dgutov** [comment]
You should probably report this to the Semantic mailing list. But it does what it says: parses Elisp files.

To stop it from happening, either disable `semantic-mode`, or remove `company-semantic` from `company-backends`, or both.

**Comment by jcf** [comment]
Hi @dgutov, @sooheon,

Forgive my ignorance, but how do I remove `company-semantic` from `company-backends`? I've tried the following even though I don't think it's correct:

``` emacs-lisp
;; Before, no mention of company-semantic.
ELISP> company-backends
((company-files company-capf)
 (company-dabbrev-code company-gtags company-etags company-keywords)
 company-files company-dabbrev)

;; Try to delete anyway in case I'm missing something.
ELISP> (delete 'company-semantic company-backends)

;; Looks the same as before, which isn't surprising.
ELISP> company-backends
((company-files company-capf)
 (company-dabbrev-code company-gtags company-etags company-keywords)
 company-files company-dabbrev)
```

I have to wait several seconds when typing comments and/or docstrings in Emacs Lisp files, which doesn't appear to be a `company-semantic-mode`:

``` emacs-lisp
ELISP> company-semantic-modes
(c-mode c++-mode jde-mode java-mode)
```

Getting this fixed would make my day. 😄

**Comment by dgutov** [comment]
> how do I remove company-semantic from company-backends?

https://www.emacswiki.org/emacs/ListModification

Or use the Customize interface.

> Emacs Lisp files, which doesn't appear to be a company-semantic-mode

It seems Semantic does its thing anyway. It doesn't just start working when Company asks it for completions.

**Comment by sooheon** [comment]
Yeah, because the lag happened after I typed leading letters, I thought company was requesting it, but it's semantic alone that causes it.

**Comment by ninjarai4** [comment]
I've been having this problem too, and after doing some digging I found out you could send SIGUSR2 to emacs to have it print a current stack trace.
I did this while semantic was hanging the interface and this is what I got:
    
    
    Debugger entered--entering a function:
    * file-exists-p("/home/aaron/.emacs.d/layers/+completion/auto-completion/packages.el")
      #[(obj tag) "\306\211\211A@)	*=\203\307\202%\310\211\211A@)	*=\205%\311\312\211@)!\3131:\314\n\"0\202?\314!)\211\203J\315!\204QB\202\330\316\317\"\203p\320!\321P\315!\204p\315\322P!\203p\322P\323!\211\205}\324!\205\215\325\211@)\"\326\204\235\202\315\326\211\203\302@\327\"\203\271A\211\204\250*\204\315@\205\327B,+\207" [tag class type sym err file function defun variable defvar intern (error) symbol-file file-exists-p string-match "\\.elc" file-name-sans-extension ".el" ".gz" semanticdb-file-table-object semanticdb-get-tags semanticdb-find-tags-by-name-method nil semantic-tag-similar-p obj tab alltags newtags match T --dolist-tail--] 4 "Convert one TAG, originating from Emacs OBJ, into standardized form.\nIf Emacs cannot resolve this symbol to a particular file, then return nil."]([eieio-class-tag--semanticdb-table-emacs-lisp [eieio-class-tag--semanticdb-project-database-emacs-lisp unbound semanticdb-table-emacs-lisp nil (#0)] emacs-lisp-mode nil nil unbound nil] ("auto-completion/post-init-smartparens" function nil nil nil))
      apply(#[(obj tag) "\306\211\211A@)	*=\203\307\202%\310\211\211A@)	*=\205%\311\312\211@)!\3131:\314\n\"0\202?\314!)\211\203J\315!\204QB\202\330\316\317\"\203p\320!\321P\315!\204p\315\322P!\203p\322P\323!\211\205}\324!\205\215\325\211@)\"\326\204\235\202\315\326\211\203\302@\327\"\203\271A\211\204\250*\204\315@\205\327B,+\207" [tag class type sym err file function defun variable defvar intern (error) symbol-file file-exists-p string-match "\\.elc" file-name-sans-extension ".el" ".gz" semanticdb-file-table-object semanticdb-get-tags semanticdb-find-tags-by-name-method nil semantic-tag-similar-p obj tab alltags newtags match T --dolist-tail--] 4 "Convert one TAG, originating from Emacs OBJ, into standardized form.\nIf Emacs cannot resolve this symbol to a particular file, then return nil."] [eieio-class-tag--semanticdb-table-emacs-lisp [eieio-class-tag--semanticdb-project-database-emacs-lisp unbound semanticdb-table-emacs-lisp nil (#0)] emacs-lisp-mode nil nil unbound nil] ("auto-completion/post-init-smartparens" function nil nil nil))
      semanticdb-normalize-one-tag([eieio-class-tag--semanticdb-table-emacs-lisp [eieio-class-tag--semanticdb-project-database-emacs-lisp unbound semanticdb-table-emacs-lisp nil (#0)] emacs-lisp-mode nil nil unbound nil] ("auto-completion/post-init-smartparens" function nil nil nil))
      semanticdb-strip-find-results((([eieio-class-tag--semanticdb-table-emacs-lisp [eieio-class-tag--semanticdb-project-database-emacs-lisp unbound semanticdb-table-emacs-lisp nil (#2)] emacs-lisp-mode nil nil unbound nil] ("ansi-color-faces-vector" variable nil nil nil) ("avy--overlays-lead" variable nil nil nil) ("artist-calculate-new-char" function (:arguments ("last-coord" "new-coord")) nil nil) ("aya-create-with-newline" variable nil nil nil) ("ada-xref-get-obj-dir-field" function nil nil nil) ("anzu--cons-mode-line" function (:arguments ("arg1")) nil nil) ("ange-ftp-wait-not-busy" function (:arguments ("proc")) nil nil) ("anzu--isearch-query-replace-common" function (:arguments ("arg1" "arg2")) nil nil) ("ada-previous-package" function (:user-visible-flag (interactive nil)) nil nil) ("ahs-default-symbol-regexp" variable nil nil nil) ("archive-lzh-summarize" function (:arguments ("&optional" "start")) nil nil) ("ac-update-greedy" function (:arguments ("&optional" "force")) nil nil) ("antlr-beginning-of-rule" function (:user-visible-flag (interactive "p") :arguments ("&optional" "arg")) (:filename "/usr/share/emacs/25.1/lisp/progmodes/antlr-mode.el.gz") nil) ("ange-ftp-file-attributes" function (:arguments ("file" "&optional" "id-format")) nil nil) ("ada-file-of" function (:arguments ("identlist")) nil nil) ("ada-case-exception-substring" variable nil nil nil) ("ange-ftp-bs2000-short-filename-regexp" variable nil nil nil) ("avy-word-punc-regexp" variable nil nil nil) ("ad-activate" function (:user-visible-flag (interactive (byte-code "\301\302!D\207" [current-prefix-arg ad-read-advised-function "Activate advice of"] 2)) :arguments ("arg1" "&optional" "arg2")) nil nil) ("ad-add-advice" function (:arguments ("arg1" "arg2" "arg3" "arg4")) nil nil) ("add-face-text-property" function (:arguments ("arg1" "arg2" "arg3" "&optional" "arg4" "arg5")) nil nil) ("autoarg-kp-mode-hook" variable nil (:filename "/usr/share/emacs/25.1/lisp/autoarg.el.gz") nil) ("ange-ftp-root-dir-p" function (:arguments ("dir")) nil nil) ("archive-ar-extract" function (:arguments ("archive" "name")) nil nil) ("ac-handle-post-command" function nil nil nil) ("aggressive-indent-stop-here-hook" variable nil nil nil) ("ahs-chrange-display" function (:user-visible-flag (interactive nil)) (:filename "/home/aaron/.emacs.d/elpa/auto-highlight-symbol-20130313.243/auto-highlight-symbol.el") nil) ("activate-mark-hook" variable nil nil nil) ("appt-display-message" function (:arguments ("string" "mins")) nil nil) ("antlr-superclasses-glibs" function (:arguments ("supers" "classes")) nil nil) ("allout-recent-prefix-beginning" variable nil nil nil) ("auto-insert" function (:user-visible-flag (interactive nil)) nil nil) ("archive-maybe-update" function (:arguments ("unchanged")) nil nil) ("alert-growl-notify" function (:arguments ("info")) nil nil) ("allout-stringify-flat-index" function (:arguments ("flat-index" "&optional" "context")) nil nil) ("allout-mode-deactivate-hook" variable nil nil nil) ("anzu--last-search-state" variable nil nil nil) ("avy--de-bruijn" function (:arguments ("arg1" "arg2")) nil nil) ("artist-ellipse-remove-0-fills" function (:arguments ("fill-info")) nil nil) ("archive-desummarize" function nil nil nil) ("ange-ftp-bs2000-filename-prefix-regexp" variable nil nil nil) ("ad-compile-function" function (:arguments ("arg1")) nil nil) ("ad-recover" function (:user-visible-flag (interactive (byte-code "\301\302\303\304\305$!C\207" [obarray intern completing-read "Recover advised function: " nil t] 6)) :arguments ("arg1")) nil nil) ("ad-advice-definition" function (:arguments ("arg1")) nil nil) ("advice--tweak" function (:arguments ("arg1" "arg2")) nil nil) ("avl-tree--stack-reverse--cmacro" function (:arguments ("arg1" "arg2")) (:filename "/usr/share/emacs/25.1/lisp/emacs-lisp/avl-tree.el.gz") nil) ("anzu--query-prompt" function (:arguments ("arg1" "arg2" "arg3" "arg4")) nil nil) ("anzu--construct-position-info" function (:arguments ("arg1" "arg2" "arg3")) nil nil) ("auto-hscroll-mode" variable nil nil nil) ...)) name)
      semantic-analyze-find-tags-by-prefix(#("a" 0 1 (fontified t face font-lock-doc-face)))
      semantic-analyze-possible-completions-default([eieio-class-tag--semantic-analyze-context (3864 . 3865) (#("a" 0 1 (fontified t face font-lock-doc-face))) (variable) nil [eieio-class-tag--semantic-scope-cache [eieio-class-tag--semanticdb-table [eieio-class-tag--semanticdb-project-database "/home/aaron/.spacemacs.d/" semanticdb-table nil (#2)] emacs-lisp-mode (("dotspacemacs/layers" function nil nil #<overlay from 123 to 3705 in init.el>) ("dotspacemacs/init" function nil nil #<overlay from 3707 to 15548 in init.el>) ("dotspacemacs/user-init" function nil nil #<overlay from 15550 to 15899 in init.el>) ("dotspacemacs/user-config" function nil nil #<overlay from 15901 to 20501 in init.el>) ("custom-set-variables" code nil nil #<overlay from 20618 to 22747 in init.el>) ("custom-set-faces" code nil nil #<overlay from 22748 to 22987 in init.el>)) nil [eieio-class-tag--semanticdb-find-search-index #2 (#2 [eieio-class-tag--semanticdb-table-emacs-lisp [eieio-class-tag--semanticdb-project-database-emacs-lisp unbound semanticdb-table-emacs-lisp nil (#5)] emacs-lisp-mode nil nil unbound nil]) [eieio-class-tag--semanticdb-typecache nil nil nil ([eieio-class-tag--semantic-scope-cache #2 ("dotspacemacs/init" function nil nil #<overlay from 3707 to 15548 in init.el>) nil nil nil nil nil nil nil nil])]] ([eieio-class-tag--semantic-scope-cache #2 ("dotspacemacs/init" function nil nil #<overlay from 3707 to 15548 in init.el>) nil nil nil nil nil nil nil nil]) "init.el" #<buffer init.el> t 22986 22991 (22533 13171 689224 413000) nil nil] ("dotspacemacs/init" function nil nil #<overlay from 3707 to 15548 in init.el>) nil nil nil nil nil nil nil nil] #<buffer init.el> ((error #("Cannot find definition for \"a\"" 28 29 (face font-lock-doc-face fontified t))))] nil)
      semantic-analyze-possible-completions([eieio-class-tag--semantic-analyze-context (3864 . 3865) (#("a" 0 1 (fontified t face font-lock-doc-face))) (variable) nil [eieio-class-tag--semantic-scope-cache [eieio-class-tag--semanticdb-table [eieio-class-tag--semanticdb-project-database "/home/aaron/.spacemacs.d/" semanticdb-table nil (#2)] emacs-lisp-mode (("dotspacemacs/layers" function nil nil #<overlay from 123 to 3705 in init.el>) ("dotspacemacs/init" function nil nil #<overlay from 3707 to 15548 in init.el>) ("dotspacemacs/user-init" function nil nil #<overlay from 15550 to 15899 in init.el>) ("dotspacemacs/user-config" function nil nil #<overlay from 15901 to 20501 in init.el>) ("custom-set-variables" code nil nil #<overlay from 20618 to 22747 in init.el>) ("custom-set-faces" code nil nil #<overlay from 22748 to 22987 in init.el>)) nil [eieio-class-tag--semanticdb-find-search-index #2 (#2 [eieio-class-tag--semanticdb-table-emacs-lisp [eieio-class-tag--semanticdb-project-database-emacs-lisp unbound semanticdb-table-emacs-lisp nil (#5)] emacs-lisp-mode nil nil unbound nil]) [eieio-class-tag--semanticdb-typecache nil nil nil ([eieio-class-tag--semantic-scope-cache #2 ("dotspacemacs/init" function nil nil #<overlay from 3707 to 15548 in init.el>) nil nil nil nil nil nil nil nil])]] ([eieio-class-tag--semantic-scope-cache #2 ("dotspacemacs/init" function nil nil #<overlay from 3707 to 15548 in init.el>) nil nil nil nil nil nil nil nil]) "init.el" #<buffer init.el> t 22986 22991 (22533 13171 689224 413000) nil nil] ("dotspacemacs/init" function nil nil #<overlay from 3707 to 15548 in init.el>) nil nil nil nil nil nil nil nil] #<buffer init.el> ((error #("Cannot find definition for \"a\"" 28 29 (face font-lock-doc-face fontified t))))])
      semantic-analyze-completion-at-point-function()
      completion--capf-wrapper(semantic-analyze-completion-at-point-function optimist)
      run-hook-wrapped(completion--capf-wrapper semantic-analyze-completion-at-point-function optimist)
      company--capf-data-real()
      company--capf-data()
      company-capf(prefix)
      apply(company-capf prefix)
      company--force-sync(company-capf (prefix) company-capf)
      company--multi-backend-adapter((company-capf :with company-yasnippet) prefix)
      company--begin-new()
      company--perform()
      company-auto-begin()
      company-idle-begin(#<buffer init.el> #<window 3 on init.el> 2372 3865)
      apply(company-idle-begin (#<buffer init.el> #<window 3 on init.el> 2372 3865))
      timer-event-handler([t 22533 24123 159140 nil company-idle-begin (#<buffer init.el> #<window 3 on init.el> 2372 3865) nil 904000])
      read-event(nil t 3)
      sit-for(3)
      flyspell-check-word-p()
      flyspell-post-command-hook()

This seems to indicate to me that company-capf is responsible, not company-semantic.
It also seems to indicate that this is being triggered by flyspell's sit-for(3) call, which makes sense, since for me this bug only occurs when editing a string or comment and stops when flyspell is turned off.
It also seems strange to me that company-capf(prefix) is causing all of this decompressing and parsing of el.gz files, but I haven't read much of company's code so I might be misunderstanding what the meaning of prefix is in this case.
I hope some of this information helps.

**Comment by ninjarai4** [comment]
Actually it looks like I spoke too soon, disabling flyspell did not fix the problem, it just changed the bottom of my stack trace to
    
    company-auto-begin()
    company-idle-begin(#<buffer init.el> #<window 3 on init.el> 2982 16235)
    apply(company-idle-begin (#<buffer init.el> #<window 3 on init.el> 2982 16235))
    timer-event-handler([t 22533 29686 944927 nil company-idle-begin (#<buffer init.el> #<window 3 on init.el> 2982 16235) nil 328000])

**Comment by dgutov** [comment]
> This seems to indicate to me that company-capf is responsible, not company-semantic or semantic by itself.

Semantic is still responsible. In newer Emacs, it adds its functions to `completion-at-point-functions` (which is, by itself, fine), and that's why it's used by `company-capf`.

**Comment by ninjarai4** [comment]
>Semantic is still responsible. In newer Emacs, it adds its functions to completion-at-point-functions (which is, by itself, fine), and that's why it's used by company-capf.

Looks like you're right. I was able to circumvent the issue without having to disable company-mode or semantic mode by placing the following in my init.el:
    
    (with-eval-after-load 'semantic
        (cl-delete-if (lambda (x) (string-match-p "^semantic-" (symbol-name x))) completion-at-point-functions))

**Comment by ninjarai4** [comment]
Correcting the code in my previous comment:
    
    (with-eval-after-load 'semantic
        (add-hook semantic-mode-hook
                  (lambda ()
                    (cl-delete-if (lambda (x)
                                    (string-prefix-p "semantic-" (symbol-name x)))
                                  completion-at-point-functions))))

Without the add-hook it won't always work.

**Comment by sooheon** [comment]
Thank you @ninjarai4, this resolves the issue for me.

**Comment by autosquid** [comment]
@ninjarai4 will normal completions be affected with your fix?

**Comment by dgutov** [comment]
@autosquid You either live with Semantic doing what it does (parsing files), report the problem if it parses too much or too often, or live without most of Semantic's features, including completion.

**Comment by CatrielD** [comment]
I've had this problem for a long time ... just discovered the culprit, google it and finded this post.

@ninjarai4  answer might cripple the semantic-* autocompletion.

you can check the funcions in completion-at-point-functions and **advice them**. There is a little bit of code that tells us if we're in a comment or string, that I found [here](http://ergoemacs.org/emacs/elisp_determine_cursor_inside_string_or_comment.html).

First define a function:

```
(defun semantic-completion-advice (adviced-f)
           "Check if POINT it's inside a string or comment before calling semantic-analyze-completion-at-point-function"
           (if (or (inside-string-q) (inside-comment-q)) 
                     (not (message "Oleeee! do not call function, we're inside a string or comment!")) 
                     (apply adviced-f)))
```
and then tell to the emacs advice system, that it should be "around" the problematic funcion:
```
(advice-add 'semantic-analyze-completion-at-point-function :around #'semantic-completion-advice)
```

this receives a function as parámeter so it can call it if appropriate.

some aditionals remarks:
* I debug this problem with profile-start profile-report funcitons. It was plain obvious with their help.
* I have more than a semantic-* function in completion-at-point-functions; you can use the approach of @ninjarai4  but to advice them, not remove them
* A more elegant function would use (unless )  in the predicate and not clutter the minibuffer with an useless msg; but it's good to debug.

**Comment by vv111y** [comment]
@CatrielD Solves that problem, but these errors occur:

```
Company: An error occurred in auto-begin
Symbol’s function definition is void: inside-string-q
```
```
Company: backend (company-capf :with company-yasnippet) error "Symbol’s function definition is void: inside-string-q" with args (prefix)
```

autocomplete is works inconsistently

**Comment by CatrielD** [comment]
@vv111y Hi, sorry for the delay, I was out.

Emacs it's telling you that *inside-string-q* symbol it isn't bound to anything, and that's means that you need to import / copypaste the code for those two functions (*inside-string-q* and *inside-comment-q")

I did not show them for clarity and brevity sake, but you can find them there:

**http://ergoemacs.org/emacs/elisp_determine_cursor_inside_string_or_comment.html
Just copy the definition of (*inside-string-q* and *inside-comment-q*) somewhere in your init.el and it should work.**

The rest of the code that I write, only puts them **around** a function that it's invoked every time company-mode auto completion takes place, so it adds a tiny bit of logic, it says:  hey, if point (the cursor) it's at a string or comment, I do not want any auto completion to take place. That will work always except that you use some grammatic corrector for natural language, then you'll need to modify it for something more fine-grained.

Sorry I should have made myself clearer, before.

Cheers

**Comment by cjk** [comment]
I found this thread because I started having problems with company-completion in Org-buffers (only!).
Typing intermittently gets stuck in org-mode buffers, only hitting C-g a couple of times resumes typing.

I was googling for answers but closest I could find was this thread.

**Comment by dgutov** [comment]
@cjk You could try `M-x toggle-debug-on-quit` before reproducing the problem and hitting `C-g`. The backtrace might show where the code spends its time.

**Comment by cjk** [comment]
@dgutov Thanks for the hint - will do and report back once the behaviour reappears.

**Comment by dgutov** [comment]
Is it better with `flyspell-mode` disabled?

**Comment by cjk** [comment]
Tried without flyspell, but still hangs, here is the stacktrace:

``` elisp
Debugger entered--Lisp error: (quit)
  re-search-backward("\\(?:\\(?:^\\| \\)[^ ]*?\\(\\(?:[[:word:]_:@.-]+\\)*\\)\\)\\=" 78218 t)
  looking-back("\\(?:^\\| \\)[^ ]*?\\(\\(?:[[:word:]_:@.-]+\\)*\\)" 78218)
  company-grab("\\(?:^\\| \\)[^ ]*?\\(\\(?:[[:word:]_:@.-]+\\)*\\)" 1 78218)
  company-grab-line("\\(?:^\\| \\)[^ ]*?\\(\\(?:[[:word:]_:@.-]+\\)*\\)" 1)
  company-dabbrev--prefix()
  company-dabbrev(prefix)
  apply(company-dabbrev prefix)
  company--force-sync(company-dabbrev (prefix) company-dabbrev)
  company--multi-backend-adapter((company-dabbrev :with company-yasnippet) prefix)
  apply(company--multi-backend-adapter (company-dabbrev :with company-yasnippet) prefix)
  company-call-backend-raw(prefix)
  apply(company-call-backend-raw prefix)
  company--force-sync(company-call-backend-raw (prefix) (company-dabbrev :with company-yasnippet))
  company-call-backend(prefix)
  company--occurrence-predicate()
  #f(compiled-function (candidate) #<bytecode 0x4e00cd5>)("vice")
  cl-delete(nil ("VIEWS" "VIM-users:" "VIS" "VIS-500er" "VIS-Parameter" "VIS-Prod" "VIS-Service" "Vibrationen:" "Victor:" "Video" "Video-Protokoll" "Viele" "Viele:" "Vielen" "Vielleicht" "Vielversprechend" "Vielversprechend:" "View" "Viewer" "Vimperator-ähnliche" "Viola" "Virtual" "Visitors:" "Visual" "VisualSearch.js" "Visualisieren" "Visualisierung" "Visualisierung:" "Visualisierungen" "vibrations-invisible-to-the-human-eye-shot-at-1000-frames-per-second" "vice" "vice-versa." "video" "video-movies" "video-transcoding-scripts" "videos" "viel" "viele" "vielen" "vieler" "vielfältiger" "vielleicht" "vielversprechendsten" "vier" "vieron" "vierteljährlichen" "vierzehn" "view" "view:" "viewing" "viewpage.action" "viewport:" "views:" "viewtopic.php" "vikkikanhaua" "vimeo" "vimeo.com" "vimium" "violations:" "virgin" "virtual_server" "virtualization" "virtualized" "virtuellen" "vis" "visible-bell" "visit" "visit." "visited" "visiting" "visjs.org" "visual" "visual-line-mode" "visualisieren" "visualization" "visualization:" "visualizing" "visualsearch") :if #f(compiled-function (candidate) #<bytecode 0x4e00cd5>))
  apply(cl-delete nil ("VIEWS" "VIM-users:" "VIS" "VIS-500er" "VIS-Parameter" "VIS-Prod" "VIS-Service" "Vibrationen:" "Victor:" "Video" "Video-Protokoll" "Viele" "Viele:" "Vielen" "Vielleicht" "Vielversprechend" "Vielversprechend:" "View" "Viewer" "Vimperator-ähnliche" "Viola" "Virtual" "Visitors:" "Visual" "VisualSearch.js" "Visualisieren" "Visualisierung" "Visualisierung:" "Visualisierungen" "vibrations-invisible-to-the-human-eye-shot-at-1000-frames-per-second" "vice" "vice-versa." "video" "video-movies" "video-transcoding-scripts" "videos" "viel" "viele" "vielen" "vieler" "vielfältiger" "vielleicht" "vielversprechendsten" "vier" "vieron" "vierteljährlichen" "vierzehn" "view" "view:" "viewing" "viewpage.action" "viewport:" "views:" "viewtopic.php" "vikkikanhaua" "vimeo" "vimeo.com" "vimium" "violations:" "virgin" "virtual_server" "virtualization" "virtualized" "virtuellen" "vis" "visible-bell" "visit" "visit." "visited" "visiting" "visjs.org" "visual" "visual-line-mode" "visualisieren" "visualization" "visualization:" "visualizing" "visualsearch") :if #f(compiled-function (candidate) #<bytecode 0x4e00cd5>) nil)
  cl-delete-if(#f(compiled-function (candidate) #<bytecode 0x4e00cd5>) ("VIEWS" "VIM-users:" "VIS" "VIS-500er" "VIS-Parameter" "VIS-Prod" "VIS-Service" "Vibrationen:" "Victor:" "Video" "Video-Protokoll" "Viele" "Viele:" "Vielen" "Vielleicht" "Vielversprechend" "Vielversprechend:" "View" "Viewer" "Vimperator-ähnliche" "Viola" "Virtual" "Visitors:" "Visual" "VisualSearch.js" "Visualisieren" "Visualisierung" "Visualisierung:" "Visualisierungen" "vibrations-invisible-to-the-human-eye-shot-at-1000-frames-per-second" "vice" "vice-versa." "video" "video-movies" "video-transcoding-scripts" "videos" "viel" "viele" "vielen" "vieler" "vielfältiger" "vielleicht" "vielversprechendsten" "vier" "vieron" "vierteljährlichen" "vierzehn" "view" "view:" "viewing" "viewpage.action" "viewport:" "views:" "viewtopic.php" "vikkikanhaua" "vimeo" "vimeo.com" "vimium" "violations:" "virgin" "virtual_server" "virtualization" "virtualized" "virtuellen" "vis" "visible-bell" "visit" "visit." "visited" "visiting" "visjs.org" "visual" "visual-line-mode" "visualisieren" "visualization" "visualization:" "visualizing" "visualsearch"))
  company-sort-by-occurrence(("VIEWS" "VIM-users:" "VIS" "VIS-500er" "VIS-Parameter" "VIS-Prod" "VIS-Service" "Vibrationen:" "Victor:" "Video" "Video-Protokoll" "Viele" "Viele:" "Vielen" "Vielleicht" "Vielversprechend" "Vielversprechend:" "View" "Viewer" "Vimperator-ähnliche" "Viola" "Virtual" "Visitors:" "Visual" "VisualSearch.js" "Visualisieren" "Visualisierung" "Visualisierung:" "Visualisierungen" "vibrations-invisible-to-the-human-eye-shot-at-1000-frames-per-second" "vice" "vice-versa." "video" "video-movies" "video-transcoding-scripts" "videos" "viel" "viele" "vielen" "vieler" "vielfältiger" "vielleicht" "vielversprechendsten" "vier" "vieron" "vierteljährlichen" "vierzehn" "view" "view:" "viewing" "viewpage.action" "viewport:" "views:" "viewtopic.php" "vikkikanhaua" "vimeo" "vimeo.com" "vimium" "violations:" "virgin" "virtual_server" "virtualization" "virtualized" "virtuellen" "vis" "visible-bell" "visit" "visit." "visited" "visiting" "visjs.org" "visual" "visual-line-mode" "visualisieren" "visualization" "visualization:" "visualizing" "visualsearch"))
  company--transform-candidates(("VIEWS" "VIM-users:" "VIS" "VIS-500er" "VIS-Parameter" "VIS-Prod" "VIS-Service" "Vibrationen:" "Victor:" "Video" "Video-Protokoll" "Viele" "Viele:" "Vielen" "Vielleicht" "Vielversprechend" "Vielversprechend:" "View" "Viewer" "Vimperator-ähnliche" "Viola" "Virtual" "Visitors:" "Visual" "VisualSearch.js" "Visualisieren" "Visualisierung" "Visualisierung:" "Visualisierungen" "vibrations-invisible-to-the-human-eye-shot-at-1000-frames-per-second" "vice" "vice-versa." "video" "video-movies" "video-transcoding-scripts" "videos" "viel" "viele" "vielen" "vieler" "vielfältiger" "vielleicht" "vielversprechendsten" "vier" "vieron" "vierteljährlichen" "vierzehn" "view" "view:" "viewing" "viewpage.action" "viewport:" "views:" "viewtopic.php" "vikkikanhaua" "vimeo" "vimeo.com" "vimium" "violations:" "virgin" "virtual_server" "virtualization" "virtualized" "virtuellen" "vis" "visible-bell" "visit" "visit." "visited" "visiting" "visjs.org" "visual" "visual-line-mode" "visualisieren" "visualization" "visualization:" "visualizing" "visualsearch"))
  company--postprocess-candidates(("VIEWS" "VIM-users:" "VIS" "VIS-500er" "VIS-Parameter" "VIS-Prod" "VIS-Service" "Via" "Vibrationen:" "Victor:" "Video" "Video-Hosting" "Video-Protokoll" "Videoplayer" "Viele" "Viele:" "Vielen" "Vielleicht" "Vielversprechend" "Vielversprechend:" "View" "Viewer" "Vimeo" "Vimperator-ähnliche" "Viola" "Virtual" "Visitors:" "Vista" "Visual" "VisualSearch.js" "Visualisieren" "Visualisierung" "Visualisierung:" "Visualisierungen" "Vivian" "via" "vibrations-invisible-to-the-human-eye-shot-at-1000-frames-per-second" "vice" "vice-versa." "video" "video-movies" "video-transcoding-scripts" "videos" "viel" "viele" "vielen" "vieler" "vielfältiger" "vielleicht" "vielversprechendsten" "vier" "vieron" "vierteljährlichen" "vierzehn" "view" "view:" "viewing" "viewpage.action" "viewport:" "views:" "viewtopic.php" "vikkikanhaua" "vimeo" "vimeo.com" "vimium" "violations:" "virgin" "virtual_server" "virtualization" "virtualized" "virtuellen" "vis" "visible-bell" "visit" "visit." "visited" "visiting" "visjs.org" "visual" "visual-line-mode" "visualisieren" "visualization" "visualization:" "visualizing" "visualsearch"))
  company-calculate-candidates("Vi")
  company--begin-new()
  company--perform()
  company-auto-begin()
  company-idle-begin(#<buffer todo-cjk-work.org> #<window 7 on *Backtrace*> 10024 88727)
  apply(company-idle-begin (#<buffer todo-cjk-work.org> #<window 7 on *Backtrace*> 10024 88727))
  timer-event-handler([t 23274 52146 959342 nil company-idle-begin (#<buffer todo-cjk-work.org> #<window 7 on *Backtrace*> 10024 88727) nil 250000])
  read-event(nil t 0.2)
  sit-for(0.2 0 no-redisplay)
  key-chord-input-method(100)
```
Should I disable key-chord-mode as well? :smile: 
Again, this happens only in org-mode buffers, which is strange , can't detect it in the trace. Oh, I have company-childframe enabled, will try without and report back if it makes a difference.

**Comment by dgutov** [comment]
What's your value of `company-dabbrev-char-regexp`? Is not the default, is it?

**Comment by cjk** [comment]
You're right, it was `"[[:word:]_:@.-]+"` for some reason. OK, I changed it back to the default and on first try couldn't reproduce the hangs.
Will keep watching it and post back / investigate further if it should re-appear.

But thanks for your advice so far, this was very helpful for me! :1st_place_medal:

**Comment by zhenlei** [comment]
it seems that there is something wrong with semantic, with code of @ninjarai4  or disable semantic will fix it.

**Comment by cdfa** [comment]
Why is this closed? All I have seen in this thread are workarounds and I have only had success with @ninjarai4 's solution. (@CatrielD 's version did tell me it wasn't calling the function, but still started compressing) The workaround that does work seems to make most features (including autocompletion) unusable. Please reopen and actually fix this!

**Comment by noctuid** [comment]
@cdfa It was closed because it's an issue with Semantic not Company.

**Comment by cdfa** [comment]
My apologies, I hadn't seen this was a different repo.

**Comment by dgutov** [comment]
Semantic is wholly different project.
