### ISSUE TITLE
Autoload for company-capf

### ISSUE THREAD

**Issue by marcinlos** [company-mode/company-mode#527]
It seems all the backends have autoloads, except for `company-capf`. Is there a specific reason for this?

**Comment by dgutov** [comment]
No particular reason. It works either way, as long as the backend's name is the same as the name of the containing file.

**Comment by marcinlos** [comment]
Thanks for the answer. The way it is done , unless you try to `:bind` it using `use-package` (granted, probably not the most common thing to do) - in this case, `use-package` autoloads it from `company.el`, which is obviously a bad idea. Workaround is easy, it just stood out as a minor inconsistency, hence my question. If there is no technical reason for not doing this, perhaps it would be beneficial to add it for sake of consistency?

By the way, thanks for developing this awesome tool :)

**Comment by dgutov** [comment]
Sorry, why would you `:bind` it?

> use-package autoloads it from company.el

That sounds like a bug..?

No particular reasons not to add it, but I don't understand the reasons to add it so far either.

**Comment by marcinlos** [comment]
Yeah, there is hardly a reason to `:bind` this particular backend. As for the behavior of `use-package`, `:bind`-ing a function results in attempt to ensure it will be loaded. If it is not already bound, `use-package` attempts to load it from the file with name same as the package name. It effectively executes the following code before loading `company`:
```
(unless
      (fboundp 'company-capf)
    (autoload
      (function company-capf)
      "company" nil t))
```
I suppose the rationale is that it's the best thing to try without analyzing the actual files inside the package to find the right one.

**Comment by dgutov** [comment]
OK. So, what made you ask this question in the first place?

**Comment by marcinlos** [comment]
Curiosity, mostly. I noticed that `:bind`-ing `company-capf` it seems to break it, unlike other backends, and investigation uncovered lack of autoload to be the reason, so I was curious if there's something deeper behind it. It's not something I need "fixed", so now that I got an answer, this can be closed - thanks.
