### ISSUE TITLE
Best approach to merge dabbrev with other backends.

### ISSUE THREAD

**Issue by jojojames** [company-mode/company-mode#528]
I'm trying to get a list of candidates when merging backends together without duplicates trying several approaches.

Example code:
       (defun supersupersupersuper)
       sup| <-- cursor

1.
company-backends: ((company-dict :with company-yasnippet company-dabbrev-code)
 (company-bbdb :with company-yasnippet company-dabbrev-code)
 (company-nxml :with company-yasnippet company-dabbrev-code)
 (company-css :with company-yasnippet company-dabbrev-code)
 (company-eclim :with company-yasnippet company-dabbrev-code)
 (company-semantic :with company-yasnippet company-dabbrev-code)
 (company-clang :with company-yasnippet company-dabbrev-code)
 (company-xcode :with company-yasnippet company-dabbrev-code)
 (company-cmake :with company-yasnippet company-dabbrev-code)
 (company-capf :with company-yasnippet company-dabbrev-code)
 (company-files :with company-yasnippet company-dabbrev-code)
 (company-dabbrev-code company-gtags company-etags company-keywords :with company-yasnippet)
 (company-oddmuse :with company-yasnippet company-dabbrev-code)
 (company-dabbrev :with company-yasnippet company-dabbrev-code))

Used backend: (company-capf :with company-yasnippet company-dabbrev-code)

Prefix: stop
Completions: none

completes supersupersupersuper fine but results in duplicates for other candidate lists.

2. 
company-backends: (company-capf company-dabbrev-code)

Used backend: company-capf
Prefix: stop
Completions: none

company-capf seems to come first which results in no completion.

3. 
company-backends: (company-dabbrev-code company-capf)

Used backend: company-dabbrev-code
Prefix: stop
Completions: none

company-dabbrev-code now comes first, supersupersuper completes fine but I seemingly lose completions from company-capf

Some other possibly relevant configuration I have around dabbrev.
  (setq company-dabbrev-downcase nil)
  (setq company-dabbrev-ignore-case t) ; default is keep-prefix

Wondering what the right approach here is.

**Comment by dgutov** [comment]
Why not `((company-capf company-dabbrev-code))`?

**Comment by jojojames** [comment]
I end up getting duplicates with either of these.

company-backends: ((company-dabbrev-code company-capf))

Used backend: (company-dabbrev-code company-capf)

or

company-backends: ((company-capf company-dabbrev-code))

Used backend: (company-capf company-dabbrev-code)

**Comment by dgutov** [comment]
> I end up getting duplicates with either of these.

In which circumstances?

**Comment by jojojames** [comment]
Same backend (company-capf company-dabbrev-code)
<img width="1057" alt="screenshot 2016-05-30 11 46 57" src="https://cloud.githubusercontent.com/assets/1227856/15656459/5b17b6da-265c-11e6-98ea-3c9c45bc0a5e.png">
<img width="1057" alt="screenshot 2016-05-30 11 47 11" src="https://cloud.githubusercontent.com/assets/1227856/15656463/65bac7a8-265c-11e6-89a9-0add5cfb3994.png">

**Comment by dgutov** [comment]
OK, so this is about annotations. We don't consider completions with different annotations to be duplicates. See the discussion in #432.

**Comment by jojojames** [comment]
Thanks, I'll have a look at company-transformers to see if I can cull out the dabbrev values.

**Comment by dgutov** [comment]
You can use `delete-consecutive-dups` with sufficiently recent Emacs.

**Comment by tshu-w** [comment]
@jojojames I'm having the same problem. would you mind sharing company-transformers function?

**Comment by dsedivec** [comment]
For the benefit of others, I just whipped this up to remove duplicate candidates, ignoring annotations.  It has been working for me for the last five minutes so I'm super-confident that it's completely correct.

https://github.com/dsedivec/dot-emacs-d/blob/master/recipes/company-remove-duplicates-ignoring-annotations.el

**Comment by jojojames** [comment]
@tshu-w I must've missed your message (for 4 years :D), I wrote this awhile back when I created the topic.

```
(defun j-company-remove-dabbrev-dups-keep-order (candidates)
    "Loop over CANDIDATES and remove duplicate candidates if they belong to
  `company-dabbrev' or `company-dabbrev-code'."
    (let ((hash (make-hash-table :test 'equal :size (length candidates)))
          (new-list nil))
      (dolist (candidate candidates)
        (let ((stripped-candidate (substring-no-properties candidate))
              (candidate-backend (get-text-property 0 'company-backend candidate)))
          (cond
           ;; Candidate is `company-yasnippet', always push this.
           ((eq (get-text-property 0 'company-backend candidate)
                'company-yasnippet)
            (push candidate new-list))
           ;; Candidate has not been seen.
           ((not (gethash stripped-candidate hash))
            (puthash stripped-candidate candidate hash)
            (push candidate new-list))
           ;; Candidate has been seen.
           ;; `company-dabbrev' or `company-dabbrev-code' is the candidate.
           ((or candidate-backend
                (eq candidate-backend 'company-dabbrev-code)
                (eq candidate-backend 'company-dabbrev))
            t)
           ;; Candidate has been seen but is not `company-dabbrev'
           ;; or `company-dabbrev-code'.
           (:seen-but-candidate-not-dabbrev
            ;; If the candidate in the hash table is dabbrev, replace it.
            ;; Otherwise, we are fine with duplicates as long as the backends
            ;; are meaningful.
            (let* ((hash-candidate (gethash stripped-candidate hash))
                   (hash-backend (get-text-property
                                  0 'company-backend hash-candidate)))
              (if (or hash-backend
                      (eq hash-backend 'company-dabbrev)
                      (eq hash-backend 'company-dabbrev-code))
                  (progn
                    (setcar
                     (nthcdr
                      (cl-position hash-candidate new-list :test 'eq)
                      new-list)
                     candidate)
                    (puthash stripped-candidate candidate hash)
                    t)
                ;; Only need one candidate in the hash table.
                (push candidate new-list)))))))
      (reverse new-list)))
```

There may be some custom logic to get it to behave how I wanted but I've been using that for a few years now.

I dont think I ever tried delete-consecutive-dups but that may be a better solution. Mine is working for me so `dontfixwhatsnotbroke`. :)

**Comment by otavioschwanck** [comment]
i know its old but i have will share a function that alsos dont run when have more than 200 candidates:

(defun remove-company-duplicates (candidates)
  "Order the snippets / text depending of priority. CANDIDATES: Company candidates."
  (if (< (length candidates) 200)
      (let* ((new-list '()))

    (dolist (candidate candidates)
      (let ((stripped-candidate (substring-no-properties candidate)))
        (if (and (not (-contains? (mapcar 'substring-no-properties new-list) stripped-candidate)))
            (push candidate new-list))))
    (reverse new-list))) candidates)
