### ISSUE TITLE
Company breaks inferior-python mode

### ISSUE THREAD

**Issue by djeis97** [company-mode/company-mode#529]
See https://github.com/syl20bnr/spacemacs/issues/6194, however this can be reproduced with a blank emacs config and calling company-complete.

To summarize, calling company-complete on an indented line in the inferior-python buffer confuses python, causing it to claim the indented line was unexpected.

Steps to reproduce, starting from a blank emacs config:
1. install company
2. launch a python interpreter (run-python)
3. Activate company-mode
4. Enter this code, calling company-complete (to force at least one call) sometime in the middle of the second line:
```
for i in range(10):
  if i < 5:
    print(i)
```
After hitting enter on the second line, python will report an unexpected indent error. This error does not occur if the call to company-complete is omitted (and the completer is never called in the background).

The frustrating part of this is that it does not happen every time, and sometimes (I'm assuming this is when the completer is being called in the background) it happens without me calling company-complete at all. So far, I've had the most regular reproduction when calling company-complete between the 5 and : of the second line.

**Comment by dgutov** [comment]
Can you reproduce it my pressing `C-M-i` instead, without `company-mode` enabled at all?

**Comment by djeis97** [comment]
Yes, which I would assume means that this is actually an issue with emacs itself? Or, at least, inferior-python mode?

**Comment by dgutov** [comment]
Yes, I would say so. Please `M-x report-emacs-bug`.

**Comment by dgutov** [comment]
Thanks.

(http://debbugs.gnu.org/23678)
