### ISSUE TITLE
Put `<return>` as `company-auto-complete-chars`

### ISSUE THREAD

**Issue by magicdirac** [company-mode/company-mode#530]
How to put `<return>` as one of the `company-auto-complete-chars`?
so that I can unbind <return> from `company-active-map`
```
(require 'bind-key)
(with-eval-after-load 'company
    (unbind-key "RET" company-active-map) 
    (unbind-key "<return>" company-active-map)
)
```
The benefit is that I will get normal `<return>` functionality when I press `<return>`, unless I have interacted with company explicitly, then it will insert the choice I chose with this setting
```
(setq company-auto-complete 'company-explicit-action-p)
```

**Comment by dgutov** [comment]
> `company-auto-complete-chars` ... can also be a function, which is called with the new input and should return non-nil if company should auto-complete.

This seems like the best available option for that.

**Comment by magicdirac** [comment]
Hi, can you help me how to do it with a function. 

I try to add <return> as a character to `company-auto-complete-chars`, that simplify does not work.
```(add-to-list 'company-auto-complete-chars ?\r)```

**Comment by dgutov** [comment]
Something like this

```el
(defun my-return-p (input)
  (eq ?\n (string-to-char input)))

(setq company-auto-complete-chars #'my-return-p)
```

But it seems to have a fatal problem: it inserts a newline afterwards. Which is expected for `company-auto-complete` in the normal case, but not here. Probably.

**Comment by magicdirac** [comment]
you are so cool, it works. 
Thank you very much!

**Comment by dgutov** [comment]
OK, if that's what you wanted.

**Comment by unhammer** [comment]
Is there no simple way to get RET/<return> to complete *only* on explicit-action-p but *without* inserting a newline?

**Comment by dgutov** [comment]
@unhammer You can define a new command and bind it.

**Comment by magicdirac** [comment]
```
 (define-key company-active-map (kbd "<return>")
    #'(lambda () (interactive)
        (progn (if (company-explicit-action-p)
                   (company-complete)
                 (call-interactively
                  (lookup-key (current-global-map)
                              (kbd "RET")))
                 ))))
  (define-key company-active-map (kbd "RET")
    #'(lambda () (interactive)
        (progn (if (company-explicit-action-p)
                   (company-complete)
                 (call-interactively
                  (lookup-key (current-global-map)
                              (kbd "RET")))
                 ))))
```

**Comment by dgutov** [comment]
@magicdirac Good example. Notes:

* No need to quote the lambdas.
* You define a names function and bind it, so that you don't have the same anonymous definition twice.

**Comment by magicdirac** [comment]
```
                  (lookup-key (current-global-map)
                              (kbd "<return>")))
```
The first one I tried to look up `"<return>"`, it does not work. I do not know why.
And then I changed to `"RET"`

**Comment by dgutov** [comment]
Those are different keys. `<returns>` maps to `RET` when unbound, but not vice versa.

The global map likely has only a binding for `RET`.

**Comment by unhammer** [comment]
If RET is bound by a minor mode, maybe 

`(let ((company-mode nil))
             (or (key-binding (kbd "<return>"))
                   (key-binding (kbd "RET")))
        )`
is more general.

Ideally, one could go from `last-command-event` directly to whatever keybinding it has, but I couldn't get that to work; it seems binding to "<return>" gives the symbol `'return` while binding to "RET" gives  `13`, no idea if there's a function that can translate into whatever would be called by the same key. But this is way beyond my use-case :)

**Comment by dgutov** [comment]
> If RET is bound by a minor mode, maybe ... is more general

I think so.

> Ideally, one could go from last-command-event directly to whatever keybinding it has, but I couldn't get that to work

Have you tried `(key-binding (this-command-keys))`?

**Comment by magicdirac** [comment]
The issue, from my point of view, is that only company-mode recognizes `<return>`
so that look up this key-binding in all other maps returns nil.

the setting is
```
  (defun my-company-active-return ()
    (interactive)
    (if (company-explicit-action-p)
        (company-complete)
      (call-interactively
       (key-binding (this-command-keys))
       )))
  (define-key company-active-map (kbd "<return>") #'my-company-active-return)
  (define-key company-active-map (kbd "RET") #'my-company-active-return)
```
and in company active map press `Enter` will get this debug message
```
Debugger entered--Lisp error: (wrong-type-argument commandp nil)
  call-interactively(nil)
  (if (company-explicit-action-p) (company-complete) (call-interactively (key-binding (this-command-keys))))
  my-company-active-return()
  funcall-interactively(my-company-active-return)
  call-interactively(my-company-active-return nil nil)
  command-execute(my-company-active-return)
```
However, if I unbind `<return>` from `company-active-map`, then `Enter` works.

**Comment by magicdirac** [comment]
`(key-binding (this-command-keys))`
This would return `nil` if `<return>` is bound in `company-active-map`.
However, if you unbind `<return>` from `company-active-map`, then it will translate to `RET` and everything works fine.
Maybe we should not define `<return>` at all. I do not see any advantage to have a seperate `<return>` binding, as all global modes translate it to `RET`

**Comment by dgutov** [comment]
We've had the `<return>` binding because `autopair` had it, but [apparently not anymore](https://github.com/joaotavora/autopair/issues/31).

So OK, let's try removing it.

Too bad we can't do so with `tab` as well, because `org-mode` binds it.

**Comment by ackalker** [comment]
@dgutov I'm afraid that's going to be tough (especially in the case of SLIME, which will have to consider breakage of expected behaviour of lots of heavily invested users), as I'm just another user. Why not hold off on the change until the other packages have dropped their 'double' bindings? Or are you trying to force their hand?

**Comment by dgutov** [comment]
> Why not hold off on the change until the other packages have dropped their 'double' bindings?

When do you estimate that might happen? And what would cause them to?

> Or are you trying to force their hand?

I suppose I am, now that you brought the problem to my attention.

Anyway, could you please report the issues, and we'll see how it goes from here, depending on the responses.

**Comment by ackalker** [comment]
I'm sorry, but I think you're fighting an uphill struggle here, it takes only a single (minor) mode out of the dozens out there to bind `<return>` and break completion selection.
 Why not control the binding of  `<return>` with a customizable variable with default value `t`?

**Comment by dgutov** [comment]
> I'm sorry, but I think you're fighting an uphill struggle here

That's not the way to convince me.

> Why not control the binding of <return> with a customizable variable with default value t?

Any user can re-add the binding in their own init script even without such a variable.

**Comment by dgutov** [comment]
Actually, maybe I can avoid having this argument by applying the syntax table via an overlay, and fixing an old issue along with it.

Please stand by.

**Comment by dgutov** [comment]
> applying the syntax table via an overlay

It doesn't seem to help with the problem in question, sorry.

On the brighter side, `auto-complete` also seems to have stopped binding `[return]` over a year ago: https://github.com/auto-complete/auto-complete/commit/81fd9211cb8a2d86533cbe8c8c65baf6409ebb26

So the hill can't be too high.

**Comment by dgutov** [comment]
I've reverted that change because of #530, sorry @magicdirac.

Going against Org this way would indeed be difficult.

**Comment by magicdirac** [comment]
@dgutov  cool, brother. I will then keep <return> re-binding.
