### ISSUE TITLE
Bug for `company-next-page` and `company-previous-page`

### ISSUE THREAD

**Issue by magicdirac** [company-mode/company-mode#533]
I just noticed that these two functions do not behave the way their name suggest.

I think they have two bugs related. 

they do not really scroll one page. How much it can scroll highly depends on at what postion your currently selection is. 
For example, saying we are showing candidates from 1 to 10 and my selection is 1(at the top), when I call next page, I suppose it will show candidates from 11 to 20. But this function only give me from 2 to 11. and move the current selection at the bottom rather than top.  it only scrolls one line not one page,
also it can not leave the selection position unchanged. if my currently selection is on the 5th of the showing candidates, I hope this will try best to keep that position.

another bug related to this function is that by scrolling pages, user may miss the last page. By adding company-tooltip-limit to current selection, the result might bigger than the total number of candidates, and then it will roll back to the beginning. so that you would never see the last page. This is a very annoying bug, users do not expect to miss the candidates by scrolling pages.

```
(defun company-next-page ()
  "Select the candidate one page further."
  (interactive)
  (when (company-manual-begin)
    (company-set-selection (+ company-selection
                              company-tooltip-limit))))
```
```
(defun company-previous-page ()
  "Select the candidate one page earlier."
  (interactive)
  (when (company-manual-begin)
    (company-set-selection (- company-selection
                              company-tooltip-limit))))
```

**Comment by dgutov** [comment]
At first, yes (if you current selection was at the beginning of the tooltip). But repeated invocations will scroll by whole pages.

This command only moves the current selection. The scroll offset is updated minimally so that the selection is still visible. Is that a problem?

**Comment by magicdirac** [comment]
I do not know how I can convince you that there is really a bug there.
as you can see, I only have 18 candidates. this is all the candidates I need to scroll through.
![candidates](https://cloud.githubusercontent.com/assets/19415738/15804519/86337ad0-2ad9-11e6-8dbb-1f41c93e85f1.png)

Now, the below is a gif image showing what you will get in tooltip by keep calling `company-next-page`. there are time to time the page never move and you miss the candidates of last page. Even though you might get one or two new candidates by scroll through all the pages, this is due to the shift of one by first scrolling. and you see that I can never be able to get the last candidate, never, ever.  
![page-down](https://cloud.githubusercontent.com/assets/19415738/15804520/8633722e-2ad9-11e6-9c9f-f7fc74becfa8.gif)

**Comment by dgutov** [comment]
> I do not know how I can convince you that there is really a bug there.

I don't know either. So far, the person who asked for this (@tuhdo) seems content with the current behavior. If you want a radically different one, you can implement your own paging commands.

> Now, the below is a gif image showing what you will get in tooltip by keep calling company-next-page.

Is it? It seems like you're alternating between `company-next-page` and `company-previous-page`.

And even so, I don't understand how you'd jump to the second visible line by calling `company-previous-page`.

**Comment by magicdirac** [comment]
> Is it? It seems like you're alternating between company-next-page and company-previous-page.
No, For the whole gif animation *only* *`company-next-page`* was called. 
The jumping is due to round back.  

when you are at candidate 11, (tooltip shows candidate 2 to 11) call next-page would get candidate 11+10=21, however, we only have 18 candidates, so it will round back to 21-18 = 3. it will jump to candidate three, however, because we have scroll one line by previous command, the candidate 3 is the second one on screen.
that's why it look like you are calling `company-previous-page`. 
1->11->3(11+10-18)->13->5->15->7->17->9->1->

star indicate current candidate selection. from left to right, each column means the next state after calling `company-next-page`
```
|    | 1+10 | 11+10-18 | 3+10 | 13+10-18 | 5+10 | 15+10-18 | 7+10 | 17+10-18 | 9+10-18 |
|----+------+----------+------+----------+------+----------+------+----------+---------|
| *1 |    2 |        2 |    4 |        4 |    6 |        6 |    8 |        8 |      *1 |
|  2 |    3 |       *3 |    5 |       *5 |    7 |       *7 |    9 |       *9 |       2 |
|  3 |    4 |        4 |    6 |        6 |    8 |        8 |   10 |       10 |       3 |
|  4 |    5 |        5 |    7 |        7 |    9 |        9 |   11 |       11 |       4 |
|  5 |    6 |        6 |    8 |        8 |   10 |       10 |   12 |       12 |       5 |
|  6 |    7 |        7 |    9 |        9 |   11 |       11 |   13 |       13 |       6 |
|  7 |    8 |        8 |   10 |       10 |   12 |       12 |   14 |       14 |       7 |
|  8 |    9 |        9 |   11 |       11 |   13 |       13 |   15 |       15 |       8 |
|  9 |   10 |       10 |   12 |       12 |   14 |       14 |   16 |       16 |       9 |
| 10 |  *11 |       11 |  *13 |       13 |  *15 |       15 |  *17 |       17 |      10 |
|----+------+----------+------+----------+------+----------+------+----------+---------|
|    |      |          |      |          |      |          |      |          |         |
```

**Comment by dgutov** [comment]
Ah, okay. So you've set `company-selection-wrap-around` to t.

**Comment by magicdirac** [comment]
Actually setting `company-selection-wrap-around` to t, user might miss candidates from last page.
The worst case I can think about is that with `company-selection-wrap-around` to t, you will only be able to get 11 candidates out of 20 and leave the last 9 unaware to the user.
the dynamic table is below.
```
|    | 10+1 | 11+10-20 |
|----+------+----------|
| *1 |    2 |       *1 |
|  2 |    3 |        2 |
|  3 |    4 |        3 |
|  4 |    5 |        4 |
|  5 |    6 |        5 |
|  6 |    7 |        6 |
|  7 |    8 |        7 |
|  8 |    9 |        8 |
|  9 |   10 |        9 |
| 10 |  *11 |       10 |
|    |      |          |
```
However, set `company-selection-wrap-around` to nil can get the last page but you need call one or two more time next page.

In this gif, I show what I mean.
I **only** use **`company-next-page`** to interact with tooltips.  
First I set `company-selection-wrap-around` to `t`, you can see my current candidates loop between 1 and 11, leave candidates 12 to 20 unknown. (BUG)
then I set  `company-selection-wrap-around` to `nil`, then I can actually see the second page, but need call **`company-next-page`** **TWICE** instead of ONCE.
![new](https://cloud.githubusercontent.com/assets/19415738/15807363/6f1228b4-2b2a-11e6-8426-2f04084a5b8b.gif)

**Comment by dgutov** [comment]
Please try this out:

```diff
diff --git a/company.el b/company.el
index 443e638..02e14e7 100644
--- a/company.el
+++ b/company.el
@@ -1942,15 +1942,23 @@ With ARG, move by that many elements."
   "Select the candidate one page further."
   (interactive)
   (when (company-manual-begin)
-    (company-set-selection (+ company-selection
-                              company-tooltip-limit))))
+    (if (and company-selection-wrap-around
+             (= company-selection (1- company-candidates-length)))
+        (company-set-selection 0)
+      (let (company-selection-wrap-around)
+        (company-set-selection (+ company-selection
+                                  company-tooltip-limit))))))
 
 (defun company-previous-page ()
   "Select the candidate one page earlier."
   (interactive)
   (when (company-manual-begin)
-    (company-set-selection (- company-selection
-                              company-tooltip-limit))))
+    (if (and company-selection-wrap-around
+             (zerop company-selection))
+        (company-set-selection (1- company-candidates-length))
+      (let (company-selection-wrap-around)
+        (company-set-selection (- company-selection
+                                company-tooltip-limit))))))
 
 (defvar company-pseudo-tooltip-overlay)
 
```

> you need call one or two more times to see the second page

That will remain true.

**Comment by magicdirac** [comment]
Thank you!
