### ISSUE TITLE
company-clang completion not offered?

### ISSUE THREAD

**Issue by ledbettj** [company-mode/company-mode#534]
I'm trying to get company set up and working nicely for C development with the clang backend.

I have two issues/questions, both evident in the gif below:
1. When I get to a struct member, completion doesn't offer any suggestions unless I then delete and re-type the `.`:
2. Does company-clang not do idle completion like in other modes?  I expect when I type `int f = po` that I should see some completion options, but I don't see anything unless I manually trigger `company-complete`.

I'm sure that this is something dumb that I've misconfigured or I'm trying to do something the wrong way.  Feedback appreciated :).

![emacs](https://cloud.githubusercontent.com/assets/805358/15828543/bd936922-2bdd-11e6-8588-88dcaa0e9211.gif)

``` elisp
(use-package company :ensure t
  :config
  (setq-default company-lighter-base "Ⓒ")
  (setq-default company-show-numbers          1)
  (setq-default company-idle-delay            0) ; start completion immediately
  (setq-default company-minimum-prefix-length 1) ; start completion after 1 character.
  (setq-default company-tooltip-align-annotations t)
  (global-company-mode 1))
```

`company-clang-begin-after-member-access` is set to the default `t`.

Company version: `20160522.1835`. from MELPA.

**Comment by ledbettj** [comment]
Surprisingly both of these cases seem to work as expected when running emacs in a terminal instead of graphical mode.

**Comment by dgutov** [comment]
Works fine here in graphical mode.

> Surprisingly both of these cases seem to work as expected when running emacs in a terminal instead of graphical mode.

This sounds like the kind of problems that people see from time to time with the OS X ports of Emacs: subtle differences in behavior where you would expect none. It could be our bug, of course, but you should try to `M-x report-emacs-bug` first.

Speaking of misconfiguration, the "start completion immediately" setting value won't do your CPU/battery any favors. Try raising it to `0.05` at least. That might also work around this bug.

`company-clang` is different from most other backends in that it uses the async backend interface, and it calls the completion process in the background asynchronously.

**Comment by ledbettj** [comment]
@dgutov  -- I wasn't able to reproduce either on my Linux machine at home with the same company version (although different Emacs version), so it's possible it's an Emacs/OS X or Emacs 25 issue, but likely not a company-mode problem.  

Thanks (again) for the help!

**Comment by dgutov** [comment]
> or Emacs 25 issue

I'm on Emacs 25, so...

Anyway, do try `(setq company-idle-delay 0.05)`.

**Comment by ledbettj** [comment]
Yup, should have mentioned tweaking the delay (even up to 3 seconds) and waiting didn't seem to make a difference.  I'm building 25 on my Linux machine now to see if I can reproduce, then I'll see about filing a bug tomorrow with any additonal info.

**Comment by charshep** [comment]
I know this is old but I have the same problem with idle completion on OS X/emacs 25.1.1. In my case idle completion works initially but then something happens where it stops working. Restart emacs, and it works again. I have not identified yet what it is that correlates with idle completion failing to work.

**Comment by dgutov** [comment]
@charshep You might want to examine the contents of `post-command-hook` and how they change over time. Also, whether there are any errors in `*Messages*`.

**Comment by charshep** [comment]
Thanks. Still investigating but it looks like something is causing company-idle-delay to get unset.

**Comment by Pouya-moh** [comment]
I have similar issue with emacs 26, clang-8 on Ubuntu 18.04. One difference is that I do use irony as well.

**Comment by dgutov** [comment]
@Pouya-moh You should probably report that to company-irony.
