### ISSUE TITLE
abbrev could not work with company

### ISSUE THREAD

**Issue by yuandaxing** [company-mode/company-mode#535]
hi all:
  below is my emacs settings:
  company-backends is a variable defined in `company.el'.
Its value is (company-abbrev company-c-headers company-bbdb company-nxml company-css company-eclim company-clang company-xcode company-cmake company-capf company-files
                (company-dabbrev-code company-gtags company-etags company-keywords)
                company-oddmuse company-dabbrev)

below is my abbrev setting:
(setq-default abbrev-mode t)
(setq save-abbrevs t)

(define-abbrev-table 'global-abbrev-table
  '(
    ("afaict" "as far as I can tell" nil 1)
    ("btw" "by the way" nil 3)
    ("wether" "whether" nil 5)
    ))

when I type "afaic"  company do not give me the abbrev candidate as auto-company give me?
if i type "afaict" then "C-x ' ", it could expand correctly.

**Comment by dgutov** [comment]
That's not how you enable `abbrev-mode`.

> Use the command ‘abbrev-mode’ to change this variable

Then it works for me.

**Comment by yuandaxing** [comment]
I do know is it work right?
when i type "afa", then it give me "afaict", then i type "enter", then i get "afaict"
I use describe-mode to check that abbrev-mode is on.
