### ISSUE TITLE
Project management: need some feedback before issuing pull req

### ISSUE THREAD

**Issue by tplass** [company-mode/company-mode#536]
I made a number of changes to the company-nxml backend (fixes + features).  

However, since I am new to Github and this project, I hesitate to barge in with a pull request but would rather like to receive some guidance on how to proceed.  This includes also the "FSF paperwork" as the changes very likely amount to being "legally significant".

Thanks, 
Thomas

**Comment by dgutov** [comment]
A pull request sounds fine, but, depending on which fixes and feature you're planning to include, you should check out the current Emacs master and its nxml mode. And maybe port the new features without equivalents to there, too. We're planning to deprecate `company-nxml` starting with Emacs 26 or so.

Regarding the FSF paperwork, if you haven't done so, please follow these instructions: http://orgmode.org/cgit.cgi/org-mode.git/plain/request-assign-future.txt

**Comment by tplass** [comment]
Well, the changes for completion in the current nXML master look like they would still benefit from an external framework like company.

While sometimes going in the same direction as my added features for company-nxml, nXML still doesn't make the most of its schema awareness, still requires non-necessary keystrokes and - frankly - I prefer a popup with candidates over a columned list in a split window.

Altough nXML's author is one of my heroes, I doubt that the approach he takes is at all fixeable.  Funnily enough, nxml-completion-hook still gets declared, but is never run...

Also, if company-xml is a dead end, then it's probably best left alone as it is.  If you think differently, then I'm still happy to submit my changes.

Thomas

**Comment by dgutov** [comment]
> nXML still doesn't make the most of its schema awareness, still requires non-necessary keystrokes

Sounds like you have a good idea what to contribute there? ;-)

> frankly - I prefer a popup with candidates over a columned list in a split window

You will still have Company's popup. It will use `company-capf` from then on.

> Altough nXML's author is one of my heroes, I doubt that the approach he takes is at all fixeable.

I'm fairly sure the original author hasn't touched nXML's codebase in quite a while.

> Also, if company-xml is a dead end, then it's probably best left alone as it is. If you think differently, then I'm still happy to submit my changes.

I think you should. Emacs 26 is still a long way off, and a lot of users will stay on 24 and 25 even after it's released.

**Comment by tplass** [comment]
Done.

If this works out favourably, maybe jclark could be persuaded to invigorate the old hook as an alternative to the now built-in completion.

**Comment by dgutov** [comment]
Why?

**Comment by tplass** [comment]
Why having alternatives? Hooks are good because the allow for more configurability.

**Comment by dgutov** [comment]
Built-in completion uses `completion-at-point-functions`. It's a hook.

**Comment by tplass** [comment]
Sorry for the confusion.  "Built-in" as in
nxml-mode-now-has-its-own-built-in-schema-aware-completion
which is _added_ to completion-at-point-functions:

`(add-hook 'completion-at-point-functions #'rng-completion-at-point nil t)`

I haven't investigated but does this mean I can add a company backend
to override the above?

**Comment by dgutov** [comment]
You can add *a* backend to override it, yes.

**Comment by dgutov** [comment]
https://github.com/company-mode/company-mode/pull/537
