### ISSUE TITLE
Another misalignment issue

### ISSUE THREAD

**Issue by litanlitudan** [company-mode/company-mode#538]
I tried to use the fixed-width font Inconsolata, but the problem still exists.

Any solution to this?
![screen shot 2016-06-08 at 9 51 13 pm](https://cloud.githubusercontent.com/assets/4970420/15916743/c7b4d62e-2dc3-11e6-8064-4907fe60fc5b.png)

Thank you very much.

**Comment by dgutov** [comment]
The font that the screenshot shows is not fixed-width. There's something missing in your config.

**Comment by litanlitudan** [comment]
Yeah, I changed the theme and the issue goes away.
Thanks.
