### ISSUE TITLE
Capf error with malformed lets and defuns

### ISSUE THREAD

**Issue by cpitclaudel** [company-mode/company-mode#540]
Typing the following in `*scratch*`, and adding text to the `abc` part, causes one error per added character:

``` elisp
(defun test abc)
```

```
Company: backend company-capf error "Wrong type argument: listp, elisp--witness--lisp" with args (candidates abcd)
Company: backend company-capf error "Wrong type argument: listp, elisp--witness--lisp" with args (candidates abcde)
Company: backend company-capf error "Wrong type argument: listp, elisp--witness--lisp" with args (candidates abcdef)
```

This is due to improper syntax, but it would be nice to swallow the error, wouldn't it? It's not clear to me whether this should be fixed in `company` or upstream though.

**Comment by dgutov** [comment]
Can you repro it with `C-M-i`?

**Comment by cpitclaudel** [comment]
Yup

**Comment by dgutov** [comment]
To the upstream it is, then!

It doesn't look serious enough for us to paper over in company-capf.
