### ISSUE TITLE
company-complete only if prefix?

### ISSUE THREAD

**Issue by unhammer** [company-mode/company-mode#541]
Currently, calling `company-complete` will try completing even if not having typed anything (by let-binding company-minimum-prefix-length to 0 inside `company-manual-begin`). I suppose this is handy if you have bigram-based or type-hole-filling backends or something, but most backends seem to require a prefix to give anything useful – is there a function that can do the equivalent of checking company-minimum-prefix-length without actually performing completion? Currently I have the following in order to have TAB do completion on prefixes and indenting otherwise:
```
  (defun company-complete-when-prefix ()
    "Insert the common part of all candidates or the current selection.
The first time this is called, the common part is inserted, the second
time, or when the selection has been changed, the selected candidate is
inserted."
    (interactive)
    (if (progn (company-assert-enabled)
               (setq company--manual-action t)
               (unwind-protect
                   (or company-candidates
                       (company-auto-begin))
                 (unless company-candidates
                   (setq company--manual-action nil))))
        (if (or company-selection-changed
                (eq last-command 'company-complete-common))
            (call-interactively 'company-complete-selection)
          (call-interactively 'company-complete-common)
          (setq this-command 'company-complete-common))
      (call-interactively #'indent-for-tab-command)))
  (define-key company-mode-map [tab] 'company-complete-when-prefix)
  (define-key company-mode-map (kbd "TAB") 'company-complete-when-prefix)
```

**Comment by dgutov** [comment]
> but most backends seem to require a prefix to give anything useful

That's odd. I've only seen `completion-at-point-functions` behave this way (some of them). Most backends should return meaningful results.

Even so, why is this a problem for you? If you're calling `company-complete` manually, you can just as well spot that the prefix is empty, and avoid doing that.

**Comment by unhammer** [comment]
Well, after hitting TAB I might want to e.g. define a new variable name. If a backend can do that for me, I should probably start looking for a new job :-) 

The problem is just that I had to more or less redefine all of `company-complete` in order to re-use company's own checking for when there is a prefix-at-point; I'd prefer to just do ```
(if (company-prefix-at-point) 
    (company-complete) 
  (call-interactively #'indent-for-tab-command))
```

**Comment by dgutov** [comment]
> Well, after hitting TAB I might want to e.g. define a new variable name

Why did you press TAB, then?

**Comment by unhammer** [comment]
To indent. E.g. point is at beginning of line, and I want to go forward to the right indentation spot to start typing a new variable name.
Say point is at `|` in
```
fun bar =
    frobnicate bar
    where
         frobnicate = smudge
|
```
and I want to get it to look like 

```
fun bar =
    frobnicate bar
    where
         frobnicate = smudge
         |
```
I would like to hit TAB to get that to happen. Then I type 

```
fun bar =
    frobnicate bar
    where
         frobnicate = smudge
         smudge = fu|
```
and hit TAB – now I want it to start offering me completions right away, without having to wait for the idle time. I already have 
```
  (define-key company-active-map [tab] 'company-complete-selection)
  (define-key company-active-map (kbd "TAB") 'company-complete-selection)
```
so if there are multiple choices, it's just another TAB.

**Comment by dgutov** [comment]
OK then, you should be able to use `(looking-at "\\_>")` to choose what to do, like shown here:

https://www.emacswiki.org/emacs/CompanyMode#toc10

**Comment by unhammer** [comment]
Ah, thought company had a more complicated check for prefixness, guess that solves it for me :-)

**Comment by dgutov** [comment]
It does, but this is probably good enough.

**Comment by clemera** [comment]
@dgutov 

Is there any way to manually invoke completion with `company-complete` and get completions without prefix? In elisp buffers I sometimes want to search for a symbol without having typed anything, is that possible?

**Comment by dgutov** [comment]
I'm afraid that won't work with `elisp-completion-at-point`: it want a non-empty prefix. You could file a feature request with Emacs, though (shouldn't be hard to fix).

**Comment by clemera** [comment]
I see, thanks!
