### ISSUE TITLE
Bad interaction with orgtbl-mode (return key)

### ISSUE THREAD

**Issue by tofgarion** [company-mode/company-mode#543]
Hello,

I use company-mode with mu4e to complete contact names. I also use orgtbl-mode in message-mode. Since commit e357eb6 where the [return] binding has been removed from company-active-map, I cannot select candidates when completing addresses in composition buffer. Adding

```emacs-lisp
(define-key company-active-map [return] 'company-complete-selection)
```

in my config file solves the problem. This seems to be a problem with orgtbl-mode, because when disabling orgtbl in message-mode, the problem disappears.

Is it possible to reintroduce the [return] binding in company-active-map?

I use org-plus-contrib-20160620 and company-0619.1916, both from MELPA.

Thanks in advance,

Christophe

**Comment by dgutov** [comment]
Org strikes again, *sigh*.

Thanks for the reminder (I think I've seem `orgtbl-mode` mentioned before).
