### ISSUE TITLE
company candidate  go out of form when meet the chinese charactors

### ISSUE THREAD

**Issue by zosy** [company-mode/company-mode#544]
company candidate  go out of form when meet the Chinese charactors, how can i fix it ?thanks.
![screenshot at 2016-06-23 12 55 09](https://cloud.githubusercontent.com/assets/3468935/16292263/5f215fac-38d5-11e6-9981-f7889e4d3763.png)

**Comment by magicdirac** [comment]
I would suggest you install [chinese-fonts-setup](https://github.com/tumashu/chinese-fonts-setup)

**Comment by dgutov** [comment]
If your characters are not monospace, yes, popup will look like that. There's no solution, so far. And several existing issues files on this subject.
