### ISSUE TITLE
Strange interaction between flyspell-prog-mode and company-mode

### ISSUE THREAD

**Issue by cpitclaudel** [company-mode/company-mode#545]
There's a weird interaction between company-mode and flyspell-prog-mode. With the .emacs file posted below, macro execution is orders of magnitude slower than without it. Concretely, running 

```elisp
(kmacro-exec-ring-item `(,(make-string 1000 ?a) 0 "%d") nil)
```

Takes close to 10 seconds, instead of being instantaneous when `flyspell-prog-mode` isn't added to `prog-mode-hook`.

To make the mix even more surprising, you can enable `aggressive-indent-mode` by @Malabarba; then each character that the macro inserts causes a redisplay.

```elisp
(add-hook 'prog-mode-hook #'flyspell-prog-mode)
(package-initialize)
(setq-default company-idle-delay 0)
(global-company-mode)
;; (add-hook 'emacs-lisp-mode-hook #'aggressive-indent-mode)
```

The culprit is `(setq company-idle-delay 0)`; still, the problem only pops up when `flyspell-prog-mode` is enabled, which hints at an actual issue, maybe?

Also, @malabarba, do you know why adding  `aggressive-indent-mode` causes redisplays?

**Comment by dgutov** [comment]
> the problem only pops up when flyspell-prog-mode is enabled

Because `flyspell-mode` works in `post-command-hook`? Anyway, I don't see a lot of difference with it being enabled or disabled. Both cases take about 1 second here.

**Comment by cpitclaudel** [comment]
Did you try the init file that I posted, or did you just enable flyspell-prog-mode? If the latter, can you try with that init file?

**Comment by dgutov** [comment]
The latter. Tried that init script now, and yes, now I see it.

The profiler results look like this:

```
- command-execute                                                7768  87%
 - call-interactively                                            7768  87%
  - funcall-interactively                                        7581  85%
   - eval-expression                                             7523  84%
    - eval                                                       7523  84%
     - kmacro-exec-ring-item                                     7523  84%
      - execute-kbd-macro                                        7479  84%
       - flyspell-post-command-hook                              7245  81%
        - flyspell-check-word-p                                  7059  79%
         - sit-for                                               7011  78%
          - input-pending-p                                      7007  78%
           - timer-event-handler                                 7007  78%
            - apply                                              7007  78%
             - company-idle-begin                                7003  78%
              - and                                              7003  78%
               - if                                              7003  78%
                - company-auto-begin                             7003  78%
                 - and                                           7003  78%
                  - let                                          7003  78%
                   - condition-case                              7003  78%
                    - progn                                      7003  78%
                     + company--perform                          7003  78%

```

**Comment by cpitclaudel** [comment]
Cool, thanks for trying it.

**Comment by dgutov** [comment]
So, to add more clarity, without `(setq-default company-idle-delay 0)`, `sit-for` probably wouldn't be calling `company-idle-begin`.

**Comment by cpitclaudel** [comment]
Ah, I see! Hmmm. Let's close this then? I'd still be curious to hear from @malabarba why aggressive-indent-mode causes redisplays.

Also, maybe we should put a warning in the docstring of company-idle-delay that says that 0 is not a good value to use? It's [not entirely uncommon](https://github.com/search?utf8=%E2%9C%93&q=company-idle-delay&type=Code&ref=searchresults) for people to use `0`, apparently, and (as you pointed out to me a while ago) it causes plenty of problems.

**Comment by dgutov** [comment]
Maybe we should just silently replace `0` with `0.01` when it's used...

**Comment by Malabarba** [comment]
@cpitclaudel Aggressive-indent-mode does call `redisplay` inside an after-command-hook, but that should happen only if there's no input. Maybe I need to add a tiny `sit-for` in there to allow for the macro input to actually arrive. Could you try evaluating the following to see if things get better?

```

(defun aggressive-indent--indent-if-changed ()
  "Indent any region that changed in the last command loop."
  (when aggressive-indent--changed-list
    (save-excursion
      (save-selected-window
        (unless (or (run-hook-wrapped 'aggressive-indent--internal-dont-indent-if #'eval)
                    (aggressive-indent--run-user-hooks))
          (while-no-input
            (sit-for 0.01 t)
            (redisplay)
            (aggressive-indent--proccess-changed-list-and-indent)))))))
```

You can try playing around with that `0.01` too.

**Comment by dgutov** [comment]
> silently replace 0 with 0.01

This is done now.

**Comment by cpitclaudel** [comment]
@dgutov Thanks!
@Malabarba That fixes the redisplay issue, indeed :)
