### ISSUE TITLE
company-cancel shoud remove company-tooltip-timer

### ISSUE THREAD

**Issue by sickHamm** [company-mode/company-mode#546]
https://github.com/company-mode/company-mode/pull/524

**Comment by dgutov** [comment]
Any particular scenario where this is a problem?

**Comment by sickHamm** [comment]
@dgutov 
when not-interactive abort company (wouldn't run pre-command-hook)  will throw error.
```Error running timer `company-pseudo-tooltip-unless-just-one-frontend-with-delay': (wrong-type-argument number-or-marker-p nil)```

**Comment by sickHamm** [comment]
And more logical; abort company will cancel all company-related timer.

**Comment by dgutov** [comment]
Thanks, this should do it.
