### ISSUE TITLE
Wrong type argument error if company-backends is changed after company-mode is enabled (and the new value contains company-clang whereas the old one didn't)

### ISSUE THREAD

**Issue by netjune** [company-mode/company-mode#552]
mode: c-mode
backends: (setq company-backends '((company-clang company-dabbrev-code) company-dabbrev))
version: 0.9.0 and the master

======= error message: =======
Company: An error occurred in auto-begin
Wrong type argument: number-or-marker-p, nil

**Comment by netjune** [comment]
company-backends's value was modified after company mode  be loaded. Maybe some backends were not loaded properly?

But it is ok when no groups are used:
(setq company-backends '(company-clang company-dabbrev-code))

**Comment by dgutov** [comment]
How do you get to that error message?

**Comment by netjune** [comment]
1. In .emacs: (setq company-backends '(company-dabbrev)) (require 'company)
2. start emacs
3. open a c file and enable company-mode
4. M-: (setq company-backends '((company-clang company-dabbrev-code) company-dabbrev))
5. insert something to trigger completion
6. error message

**Comment by netjune** [comment]
But it is ok when no groups are used (in 4):
(setq company-backends '(company-clang company-dabbrev-code))

**Comment by dgutov** [comment]
OK, thanks. I see the error, thanks.

**Comment by dgutov** [comment]
@netjune Is this problem urgent for you?

It's caused by our failure to `init` grouped backends on-the-fly (in `company--begin-new`).

**Comment by netjune** [comment]
> @netjune Is this problem urgent for you?
Not very.

**Comment by dgutov** [comment]
This should work now. Thanks again for the report.
