### ISSUE TITLE
unexpected completion item list

### ISSUE THREAD

**Issue by netjune** [company-mode/company-mode#553]
mode: c-mode
backends: (setq company-backends '((company-clang company-dabbrev-code)))
other setting: (setq company-minimum-prefix-length 3)
version: 0.9.0 and above

1. create a c-mode buffer
2. yank the following code into buffer
3. goto end of buffer(after "st"), insert the char '.' to trigger completion
4. all symbols in the buffer is in the compeletion item list

-------------------------------
struct st_test
{
	int long_name_var1;
	int long_name_var2;
};

void test()
{
	struct st_test st;

	st

**Comment by dgutov** [comment]
What did you expect?

**Comment by netjune** [comment]
I expect all items in completion list be A+B.
A: all items when (setq company-backends '(company-clang)). 2
B: all items when (setq company-backends '(company-dabbrev-code)). 0
A+B=2+0=2.

But it is not. Too many items in B(I guess).

**Comment by dgutov** [comment]
> B: all items when (setq company-backends '(company-dabbrev-code)). 0

What does that mean? Do you not get any completions with `company-dabbrev-code` alone? That's not what I'm seeing here.

**Comment by netjune** [comment]
Yes. I set company-minimum-prefix-length to 3. So after '.' there is no completions, because it is not a symbol-char.

**Comment by dgutov** [comment]
OK, so your problem is that with `company-dabbrev-code` you get no idle compeltion after `st.`. And with `company-clang`, you do.

This is working as expected. See the description of `prefix` in `company-backends`. Also try `M-x company-complete-common` to see how many completions the current backend actually returns.

**Comment by netjune** [comment]
My problem:
A. (setq company-backends '(company-clang)). The completion items are as expected (2 items).
B. (setq company-backends '(company-dabbrev-code)). The completion items are also as expected (0 items because company-minimum-prefix-length is 3).
C. (setq company-backends '((company-clang company-dabbrev-code))). The completion items are NOT as expected (A + all symbol in buffer). 

A and B is right. C is not. C != A + B.

The problem seems to be that: company-minimum-prefix-length is ignored In C case.

**Comment by dgutov** [comment]
Go to step B and type `M-x company-complete-common`. There will be completions.

**Comment by netjune** [comment]
In B, there should be no completions because company-minimum-prefix-length is 3.
Command company-complete-common ignores company-minimum-prefix-length?

**Comment by dgutov** [comment]
Like its docstring says, `company-minimum-prefix-length` only affects *idle* completion.

To put it differently, it affects whether the completion tooltip is displayed. Not how many completions a backend returns.

**Comment by netjune** [comment]
I understand now.

At that point, company first checks company-clang. It passes the prefix check. So company completion starts. Then it activates all backends in the same group and gathers their candidates, without checking company-minimum-prefix-length.

But I would it to check company-minimum-prefix-length or I will need to modify company-abbrev-code and more backends like that.

**Comment by dgutov** [comment]
Maybe you could manage that with only adding an advice to e.g. `company--multi-backend-adapter-candidates`.

I could consider this as a feature request if more people wanted it, but so far you're the first, IIRC.

**Comment by netjune** [comment]
OK. I will try. Thank you.

**Comment by dgutov** [comment]
Check out the latest master, the behavior should be improved.
