### ISSUE TITLE
How to disable automatic completion, but allow completion to be invoked manually?

### ISSUE THREAD

**Issue by taquangtrung** [company-mode/company-mode#554]
Hi,

I would like to ask if it is possible to disable the automatic completion feature of the company-mode?

The reason I want to disable it is to reduce the burden on Emacs, and only invoke completion manually when necessary. However, I tried to google for the answer but do not know how to do it. The only relevant feature that I can find out is to increase the delay time, or set the bound on the prefix-length of the word before completion.

Thanks you for considering this issue!

**Comment by dgutov** [comment]
`M-x describe-variable RET company-idle-delay RET`.
