### ISSUE TITLE
Wrong number of arguments at company-complete-common-or-cycle

### ISSUE THREAD

**Issue by neosilver-gk** [company-mode/company-mode#555]
I try to set 
```
(let ((map company-active-map))
(define-key map (kbd "<tab>") 'company-complete-common-or-cycle)
(define-key map (kbd "S-<tab>") 'company-complete-common-or-cycle "-1"))
```
and get an error with "Wrong number of arguments"

even if I set
`(define-key map (kbd "S-<tab>") 'company-complete-common-or-cycle "1")`
I get the same error

I thought I can give an optional argumen to change the direction. 
see commit [5e107fd](https://github.com/company-mode/company-mode/commit/5e107fd39629c82ef5c29b549852c2fbda578aaa)

**Comment by dgutov** [comment]
> (define-key map (kbd "S-<tab>") 'company-complete-common-or-cycle "-1")

That's invalid Elisp, `define-key` doesn't accept extra arguments.

The aforementioned commit adds the ability to pass an extra argument to the command. Either with prefixing the call with `M-<number>`, or by passing the value from another function.

Without extra bindings or functions, to cycle back, type `M-- TAB` (meta minus tab).

**Comment by neosilver-gk** [comment]
Thx,
I'm a noob in Elisp and the aim of my question was to find a solution for my keybinding, not to use an other. If I get it right, I still have to use this [#68 (comment)](https://github.com/company-mode/company-mode/issues/68#issuecomment-77602328) or just
```
(define-key map (kbd "S-<tab>") 'company-select-previous)
```

**Comment by dgutov** [comment]
Yes. But you can write a much smaller implementation for `company-complete-common-or-previous-cycle`.
