### ISSUE TITLE
sometimes no completion

### ISSUE THREAD

**Issue by netjune** [company-mode/company-mode#556]
Sometimes threre is no completion when there should be.

It just happened when I edit the following c code:

```
#include <stdio.h>
#inclu
```

No completion at the end of the code.

M-x company-diag:

```
Emacs 24.5.50.2 (x86_64-pc-linux-gnu) of 2016-03-18 on linux
Company 0.9.0

company-backends: ((company-irony-c-headers company-irony)
 company-dabbrev-code company-dabbrev company-capf)

Used backend: (company-irony-c-headers company-irony)

Prefix: ("inclu" . t)

Completions: none
```

But after excuting "company-complete-common", completion menu popups as expected (4 items from company-irony).
company-mode was always on.

**Comment by netjune** [comment]
How does this happen?

Now the problem disappeared magically. Completion can popup automaticlly and works well as usual now.
But the result of "company-diag" is the same as the above.

**Comment by dgutov** [comment]
You're using two third-party backends. Maybe it's a problem in company-mode, but most likely, the problem is in one of them.

Do you have a solid reproduction scenario? Does it occur when the backends are not grouped, and only one of them is used?

**Comment by netjune** [comment]
It seems that I have to save the newly created buffer(no file on disk before saving) before completion can popup. Maybe this is required by the first two backends.

Completion can popup now. But company-diag still returns "Completions: none".

**Comment by dgutov** [comment]
Please let me know when you have more information.

**Comment by netjune** [comment]
OK.
