### ISSUE TITLE
company-dabbrev-code couldn't work  behind company-capf

### ISSUE THREAD

**Issue by sickHamm** [company-mode/company-mode#557]
company-dabbrev-code, company-dabbrev  (maybe all backends) couldn't work when position behind company-capf  in `company-backends`. company-capf don't have any candidate.

**Comment by sickHamm** [comment]
emacs -Q
https://raw.githubusercontent.com/sickHamm/images/master/demo2.gif

**Comment by dgutov** [comment]
No backend works when behind another active backend. Whether backend is active, is determined by the return value of `prefix`, no whether it returns any candidates for a given position.

**Comment by sickHamm** [comment]
thanks,  I have learned.
and just another question, why place company-capf front of company-dabbrev-code default ?

**Comment by dgutov** [comment]
Because if it was later, you'd have the same problem in reverse, in every buffer where `company-dabbrev-code` works.

`company-capf` is supposed to give better results than `company-dabbrev-code`, but that obviously depends on each completion function.

**Comment by sickHamm** [comment]
I think the `:with` is what I looking for.  Is company-backends like below, will active  company-dabbrev-code only when company-capf activing ? and If  company-capf  don't active, company wouldn't
active company-dabbrev-code, but active company-files.
`((company-capf :with company-dabbrev-code) company-files)`
> 
Group of back-ends can now contain keyword :with, which makes all back-ends after it to be skipped for prefix calculation.

**Comment by dgutov** [comment]
Right.

**Comment by yugaego** [comment]
See also discussion in #142.
