### ISSUE TITLE
company-file a little too aggressive at attempting expansion of * character

### ISSUE THREAD

**Issue by stsquad** [company-mode/company-mode#558]
As noted in [on the Emacs Stack Exhange](http://emacs.stackexchange.com/questions/24681/eshell-cannot-insert/24710#24710) and in [bug report](https://github.com/syl20bnr/spacemacs/issues/6635) opening a shell and typing * leads to it being deleted. It seems the _company-files_ completion should probably not remove the * unless completion options have been offered.

**Comment by dgutov** [comment]
Why do you think `company-files` is at fault?

**Comment by TheBB** [comment]
I can reproduce the problem with `company-capf` as the sole backend, so it's likely not company's fault.

**Comment by dgutov** [comment]
It's http://debbugs.gnu.org/cgi/bugreport.cgi?bug=18951. And see #218.

You're welcome to try your hand at fixing it, everyone.

**Comment by stsquad** [comment]
@dgutov I removed the company-files backend and the problem went away. However the capf problem remains if you explicitly hit TAB from a * character. I guess there may be a relation between the two.

**Comment by stsquad** [comment]
Is there a relation between capf and company-files? Removing company-capf also fixes the auto-deletion of * so could it be that capf sets something up that company-files then follows through on?

**Comment by dgutov** [comment]
Do you group them?

**Comment by dgutov** [comment]
Do you group them?

**Comment by TheBB** [comment]
No, they're not grouped.

**Comment by dgutov** [comment]
> I removed the company-files backend and the problem went away

What are the exact scenarios?

I open the shell, evaluate `(setq-local company-backends '(company-capf))`, just type `*`, and the idle completion eats it right away. When does this not happen?

**Comment by stsquad** [comment]
@dgutov in that case the completion doesn't eat the * until I hit TAB. 

    M-x eshell
    Welcome to the Emacs shell
    ~/mysrc/elisp.git $ (list company-backends)
    ((company-bbdb company-nxml company-css company-clang company-cmake company-capf company-files
               (company-dabbrev-code company-gtags company-etags company-keywords)
               company-oddmuse company-dabbrev company-irony))
    ~/mysrc/elisp.git $ *
    
Gets magically eaten without pressing anything

    ~/mysrc/elisp.git $ (delete 'company-files company-backends)
    (company-bbdb company-nxml company-css company-clang company-cmake company-capf
                  (company-dabbrev-code company-gtags company-etags company-keywords)
                  company-oddmuse company-dabbrev company-irony)
    ~/mysrc/elisp.git $ (list company-backends)
    ((company-bbdb company-nxml company-css company-clang company-cmake company-capf
                   (company-dabbrev-code company-gtags company-etags company-keywords)
                   company-oddmuse company-dabbrev company-irony))
    ~/mysrc/elisp.git $ *
    
Doesn't get eaten until I hit TAB

**Comment by dgutov** [comment]
@stsquad It gets eaten automatically in both cases here. Emacs 25, recent build.

**Comment by stsquad** [comment]
I'm running Emacs-25 tip and Emacs 24-stable on the two machines I tested it on. I'll see if I can narrow down any other factors.
