### ISSUE TITLE
Setting company-dabbrev-code-everywhere seems to have no effect

### ISSUE THREAD

**Issue by arronmabrey** [company-mode/company-mode#559]
Given a `ruby-mode` scratch buffer containing:

```ruby
# foo_bar_baz
foo
```

And given the following setting company configuration
```elisp
(setq company-dabbrev-code-everywhere t)
```
When I try to use company to auto complete `foo` into `foo_bar_baz` I don't get any completions.

I would expect setting the `company-dabbrev-code-everywhere` flag to allow `company-dabbrev-code` to search through comments, but it seems to not have any effect.

Here is the output of `company-diag`

```
Emacs 24.5.1 (x86_64-apple-darwin15.2.0) of 2015-12-24 on arron-imac.local
Company 0.9.0-cvs

company-backends: (company-robe
 (company-dabbrev-code company-gtags company-etags company-keywords)
 company-files company-dabbrev)

Used backend: (company-dabbrev-code company-gtags company-etags company-keywords)

Prefix: #("foo" 0 3
  (fontified t))

: none
```

**Comment by dgutov** [comment]
Hi!

Thanks for the report. This should work now.
