### ISSUE TITLE
Documentation popup in non-GUI Emacs

### ISSUE THREAD

**Issue by computersarecool** [company-mode/company-mode#561]
Just to confirm as mentioned in #138  there is no support for the documentation pop-ups while using a non window-system Emacs in company mode, correct?

Is  it correct that Company-quick help does not allow pop-ups in Emacs without a window system?

**Comment by dgutov** [comment]
It is correct.

And [company-quickhelp](https://github.com/expez/company-quickhelp) is a separate package, not part of `company-mode`.
