### ISSUE TITLE
Ignore permission denied errors

### ISSUE THREAD

**Issue by Stebalien** [company-mode/company-mode#563]
Currently, when company-files tries to recurse into an unreadable directory, it spits out, for example,

```
Company: backend company-files error "Opening directory: permission denied, /lost+found/" with args (candidates /)
```

And then fails to show any completions. Instead, it should just ignore this directory (show it but not recuse into it) and move on.

**Comment by dgutov** [comment]
Thanks for the report, it should work now.

**Comment by Stebalien** [comment]
Thanks!
