### ISSUE TITLE
Support completion of LaTeX labels

### ISSUE THREAD

**Issue by swarnendubiswas** [company-mode/company-mode#565]
I am not sure whether company currently supports completing label names in LaTeX. If not, it would be extremely useful to add support for such an feature. For example, `ac-tex-ref` provides similar functionality.

**Comment by dgutov** [comment]
See the LaTeX entry here: https://github.com/company-mode/company-mode/wiki/Third-Party-Packages

**Comment by swarnendubiswas** [comment]
Thanks, I am aware of those packages and use them. But the use case that I am talking about is slightly different. I am not talking about LaTeX commands, but rather the labels using macros like `\cite{a-seminal-paper}`, `\label{chap1:introduction}`, etc. At present, it seems that the linked packages do not provide completion for those labels such as chap1:introduction and a-seminal-paper.

**Comment by dgutov** [comment]
Have you tried reporting that to company-auctex?

**Comment by swarnendubiswas** [comment]
Thanks, will do so.
