### ISSUE TITLE
Disable completion when line is just indent

### ISSUE THREAD

**Issue by mmauger** [company-mode/company-mode#566]
I find company-mode popping up completion with seemingly random contents when it is triggered at either the beginning of the line or on an all empty line.

The most common occurrence is when I am using using 'company-indent-or-complete-common' and I'm at the indent column already, then I get, what for me is a meaningless company menu.

This may not be a universal need, but having the ability to filter out completion is situations dictate.

**Comment by dgutov** [comment]
You ask for completions - you get the ones that are available. Whether this is desirable or not, depends on the user and on the backend in use.

> The most common occurrence is when I am using using 'company-indent-or-complete-common' and I'm at the indent column already, then I get, what for me is a meaningless company menu.

You can write your own command with modified logic (should be trivial). Or simply try `indent-or-complete` from https://www.emacswiki.org/emacs/CompanyMode#toc10.
