### ISSUE TITLE
Filtering candidates breaks company-tooltip-selection-face

### ISSUE THREAD

**Issue by AndreaOrru** [company-mode/company-mode#567]
Steps to reproduce:

1. Start completion
2. Filter with C-M-s
3. Move up and down through the filtered candidates
4. The selected candidate isn't highlighted

<img width="290" alt="1" src="https://cloud.githubusercontent.com/assets/3673952/17815146/f5856678-662a-11e6-8fc7-392549f4ec66.png">

I would expect "null" to be highlighted in blue for all the results that match, and the current selected candidate to be highlighted (like, the all line). 

<img width="241" alt="1" src="https://cloud.githubusercontent.com/assets/3673952/17815294/93014b4c-662b-11e6-8594-3e75db23436b.png">

Is this intended?

**Comment by dgutov** [comment]
Works fine here. Have you tried it with the default theme?

**Comment by dgutov** [comment]
> and the current selected candidate to be highlighted

That won't happen because we highlight the search match on the current line, if present. And the filtering mode guarantee that all currently visible candidates have matches.

**Comment by AndreaOrru** [comment]
Ok. Any way to change this behaviour?

**Comment by dgutov** [comment]
It's pretty much hardcoded in `company-fill-propertize`.

I don't understand why you don't see the matches highlighted, though.

**Comment by AndreaOrru** [comment]
Oh, the second screenshot is just an example of what I'd like to obtain.

It seems more natural to me for ALL the matching substrings on ALL the lines to be shown in blue - and the current selected line to be highlighted as a whole.

**Comment by dgutov** [comment]
But only in the filtering mode?

**Comment by AndreaOrru** [comment]
No, the search mode as well.

Look, I just hacked a quick solution:
<img width="272" alt="1" src="https://cloud.githubusercontent.com/assets/3673952/17816161/a55b4e6a-662f-11e6-8ded-d4537688ef9a.png">
It's not perfect (I have to work on the background of the matched substring), but it gives the idea. I can make a pull request to enable this as a feature once I'm done.

**Comment by dgutov** [comment]
Have you tested the new behavior with the default theme?

**Comment by AndreaOrru** [comment]
Yes.

<img width="272" alt="1" src="https://cloud.githubusercontent.com/assets/3673952/17816356/aefcfb98-6630-11e6-90c7-48f48c84f064.png">

By default search and line highlight have the same color, but that can be changed easily.

What are your thoughts?

**Comment by dgutov** [comment]
> By default search and line highlight have the same color

That's the problem I was thinking of. Care to propose a different color? And also for the dark-background version.

**Comment by AndreaOrru** [comment]
If you'd like to have this as the default behaviour, I can play around and find a nice combination and report back ;)

**Comment by dgutov** [comment]
I'd probably be fine with it, as long as the result is not too in-your-face.

**Comment by dgutov** [comment]
And the change should be in the search face, because it's used less frequently. So it'll have the theme authors more leeway to adapt.

**Comment by AndreaOrru** [comment]
I added a customizable company-tooltip-search-selection face.

<img width="267" alt="bright" src="https://cloud.githubusercontent.com/assets/3673952/17821605/63914d2a-664a-11e6-9382-952f87ca4078.png">
<img width="250" alt="dark" src="https://cloud.githubusercontent.com/assets/3673952/17821608/6679fe74-664a-11e6-9154-9de841f8d542.png">

**Comment by dgutov** [comment]
Regarding picture 2, not a fan of "inverse video" for the new face. If the popup is dark-on-light, then all faces should fit that.

And regarding the orange, might there be some other color we could reuse? Preferably to highlight via the background, like we do now.

**Comment by AndreaOrru** [comment]
I'm not a big fan of highlight via background. That would be really in you face and probably wouldn't look good on the selected line. But I'm happy to try.

I agree that the "inverse video" is suboptimal.

**Comment by AndreaOrru** [comment]
<img width="249" alt="bright" src="https://cloud.githubusercontent.com/assets/3673952/17832005/c12a4f8a-66f0-11e6-8b8e-86e245e0342f.png">
<img width="285" alt="dark" src="https://cloud.githubusercontent.com/assets/3673952/17832006/c2e00f2c-66f0-11e6-9b60-bddafb4d9a98.png">

This really is the simplest solution. Both _search_ and _search-selection_ inherit from _highlight_.
If you like it I'll add updated tests to the pull request. ;)

**Comment by dgutov** [comment]
I think it looks fine, and normally search matches are highlighted via background (e.g. isearch in Emacs, or plain search in Firefox). Another option for the highlighting face would be `isearch`.

**Comment by AndreaOrru** [comment]
`isearch` is purple though. Way too much. I'd keep it this way.

**Comment by dgutov** [comment]
Squashed and pushed. Thanks!

(Also note that recent NEWS entries are at the top).
