### ISSUE TITLE
global should use "-T" option to goes through all the tag files listed in GTAGSLIBPATH

### ISSUE THREAD

**Issue by redguardtoo** [company-mode/company-mode#570]
just memo.
Since this is real minor fix, I pushed directly.

c353c71 global goes through all the tag files listed in GTAGSLIBPATH (Chen Bin)

**Comment by dgutov** [comment]
Thanks. Does that fix #405?

**Comment by redguardtoo** [comment]
ye s

**Comment by dgutov** [comment]
Please close it then.
