### ISSUE TITLE
Popup blanks out part of the fringe

### ISSUE THREAD

**Issue by endofunky** [company-mode/company-mode#574]
The popup appears to blank out part of the fringe when completing. Tried to find several fixes and even used a minimal `.emacs` file but it still seems to happen. The image below has indicators from `diff-hl` but I assume this might happen with other indicators as well:

![img](https://cloud.githubusercontent.com/assets/88799/18032925/c9412b76-6d0d-11e6-8bb7-9d4cbdd80a06.png)

**Comment by endofunky** [comment]
Here's a minimal `.emacs` file that seems to cause this issue as well for me:

```emacs-list
(package-initialize)
(fringe-mode)
(evil-mode t)
(global-company-mode t)

(setq company-idle-delay 0.2)
(setq company-minimum-prefix-length 2)

(global-diff-hl-mode t)
(require 'diff-hl-flydiff)
(diff-hl-flydiff-mode t)
```

**Comment by dgutov** [comment]
Alas, there's no easy fix.

See e.g. https://github.com/company-mode/company-mode/issues/417.

**Comment by dgutov** [comment]
And #471.

**Comment by endofunky** [comment]
Ok fair enough. Just tried it with `auto-complete-mode` and it doesn't seem to have that issue, so might switch back until `company-mode` has a solution for it.

**Comment by dgutov** [comment]
Yes, it uses the one-overlay-per-line approach for rendering the popup. I wouldn't say one or the other is necessarily better. popup.el has its own share of rendering bugs.
