### ISSUE TITLE
company-minimum-prefix-length isn't taken into account when backspacing

### ISSUE THREAD

**Issue by Stebalien** [company-mode/company-mode#578]
When backspacing over a word (or moving over it using the cursor), `company-minimum-prefix-length` isn't taken into account. This can make backspacing in latex _very_ slow as all commands start with `\` (so I have `company-minimum-prefix-length` set to 2). That is, with `|` as the cursor, starting with `\alp|` and then backspacing to `\|` causes company to try to auto-complete _all_ latex commands. It doesn't take too long for small documents but can be a problem at the end of large documents (why?).

**Comment by dgutov** [comment]
What is your sequence of commands exactly?

Can you reproduce this with one of the built-in backends, like `company-dabbrev`?

**Comment by dgutov** [comment]
What does `M-x company-diag` say?

**Comment by Stebalien** [comment]
> What is your sequence of commands exactly?

Type `\l` and then backspace with company enabled (using the `company-auctex-symbols` backend).

> Can you reproduce this with one of the built-in backends, like company-dabbrev?

No. Only `company-auctex-symbols`. However, I assume the choice to offer completions is up to company, not the individual backend (although `company-auctex-symbols` should probably be faster but that's not specifically what this bug report is about).

> What does M-x company-diag say?

After backspacing, I get (`company-minimum-prefix-length` is 2):

```
Emacs 24.5.1 (x86_64-unknown-linux-gnu) of 2016-06-05 on bistromath
Company 0.9.0

company-backends: (company-auctex-symbols)

Used backend: company-auctex-symbols
Prefix: ("" . t)

Completions: none
```

**Comment by dgutov** [comment]
> No.

Then it's a problem with the individual backend. Please report it there. And indeed:

> After backspacing, I get: ...

If you get `("" . t)` in that context only after backspacing, that's the thing the backend author should fix.
