### ISSUE TITLE
Help with configuring completion in C code

### ISSUE THREAD

**Issue by keitaro78** [company-mode/company-mode#579]
Hello,
i use emacs GNU Emacs 24.5.1, i install company for auto-completion for my code in C.
I just did M-x list-packages and install company and add in my .emacs : 

`(add-hook 'after-init-hook 'global-company-mode)`

but when i wrote basicall function like for or do while or whatever i don't see the autocompletion, no choice pop-up.
Did i fail something in the configuration ?

When i check in emacs the company-mode is on.
Thx for your help

**Comment by dgutov** [comment]
What are the buffer contents, and what exactly do you expect to see?

**Comment by keitaro78** [comment]
Oh by exemple i try a very simple C code like a for loop with a printf like that : 
by exemple for autocompletion i was exepted that for the for or printf when i wrote it that emacs suggests me and show the parameter of the different fonctions but during all the code i just write it by hand no suggestion at all. Is it normal ?
Thx for your help
#include <string.h>
#include <stdio.h>
int main(int argc, char *argv[])
{
int compteur;
for (compteur = 0 ; compteur < 10 ; compteur++)
{
    printf("Salut les Zeros !\n");
}
}

**Comment by dgutov** [comment]
What are the buffer contents at the exact moment when do you expect to see completions? And where is the cursor at that moment?

Do you have Clang installed?

**Comment by keitaro78** [comment]
Hello,
yes i have clang install (clang version 3.8.0-2ubuntu4)
by exemple at the for i exepected a completion but there is nothing, not text pop up.
in my emacs line when i see the name of my code with lines and columns, it was written the time and (C/l hs company abbrev)
Thx for your help

**Comment by dgutov** [comment]
Where is the cursor at that moment?

**Comment by keitaro78** [comment]
the cursor was on just after the "r" or for when i was typing but even if the cursor is after o (before i finish typing for it doesn't auto-complete.
I wrote all my code from scratch i never see any pop-up or auto completion.
When does the auto-completion supposed to pop up ?

**Comment by dgutov** [comment]
So, do you want keyword completion (completion incomplete keywords to their full names)? Or snippet expansion as well? If it's the latter, you might want to look at [yasnippet](https://github.com/joaotavora/yasnippet).

In the Emacs world, when we talk about completion, it's usually the parts that the user has to remember, and not the basic syntax of the language. So you should expect to see completions for function names, local or imported. `for`, `while` and `do` are not functions, though. These are keywords.

**Comment by keitaro78** [comment]
Oh i see,
usually for auto complete variables in my codes i do M+/.
And yes i would like to have something that told to me the parameter and there type (prototype of the function) when i am calling it.
I thought that company does it.
Thx

**Comment by dgutov** [comment]
It does when you're typing.

When you type `set`, don't you see the popup with four options, all of them displaying the arguments list?

**Comment by keitaro78** [comment]
That is right it work for set !
But why it doesn't work for malloc etc ?

**Comment by dgutov** [comment]
It does. You have to `#include <stdlib.h>` first, though.

**Comment by keitaro78** [comment]
that is true sorry for those stupid questions and thx for you help.
So it works for all the functions atm.
Does that work with our personnal headers and functions too ?
My problem is solved after that should i edit.change the title ?
Thx again for your help

**Comment by dgutov** [comment]
> Does that work with our personnal headers and functions too ?

Why not? But you might have to let Clang know where to find them, by customizing `company-clang-arguments`.

> change the title ?

Sure. What will the new title be?

**Comment by keitaro78** [comment]
>  But you might have to let Clang know where to find them, by customizing company-clang-arguments.
We need to create this file in ~/emacs.d/elpa/company-0.9.0 ?

> Sure. What will the new title be?

Oh just to put a [solved] before the origin title to say that the issue is fixed.

And thx to you for all your help

**Comment by dgutov** [comment]
> Oh just to put a [solved] before the origin title to say that the issue is fixed.

We have the "close" button for that. 😄

> And thx to you for all your help

No problem.
