### ISSUE TITLE
Allow async backends to use candidate results for previous, but prefix matching callbacks calls

### ISSUE THREAD

**Issue by aaronjensen** [company-mode/company-mode#580]
Let's say you set `company-idle-delay` very low, like `0` and use an `async` backend. You then type a few characters like `ite`. The `it` may set off an async candidate call and then the `ite` will set off an async candidate call. Likely the `it` call will return first, but since both the `tick` and `pos` have been modified, `company-idle-begin` will discard this result and wait for the callback of the last prefix.

This means that for a cacheable backend, the "cacheability" is of no benefit if one types faster than the backend can return. Idealy, the result for `it` would come back, and even if I had made it all the way to `ite` or `item` it would display the completion results, filtered down with `all-completions`, of course.

I'm not sure of the best place to do this or if there are any dragons so I wanted to get your input on it before submitting anything.

Thanks!

**edit** A natural extension of this is that we do not even ask the backend for `ite` if we know the backend is cacheable and `it`'s result is still pending. This would prevent quite a bit of work I would guess.

**Comment by dgutov** [comment]
Hey Aaron,

Thanks for digging into this issue, but I don't think the pull request should be merged, for reasons below:

1. It complicates the async logic, whereas the current one isn't so great (see #337 and #510, for example). And I'm not sure how extensively the existing logic will need to be changed, for fix those two issues.

2. Caching should migrate into each individual backend. This is something Stefan brought up a while ago. As one example, this approach can speed up the dabbrev backends (by maintaining per-buffer caches). But in the end, there will be no `no-cache` property in the backend. Of course, we can still provide helpers for the common case.

3. The same logic you have offered here can be implemented in each individual backend. It could become even simpler, because it won't have to deal with the general case. The proposed change isn't too big anyway. Likewise, we could offer helpers doing this in the future, but I wouldn't hurry with that because of item 1.

4. Setting `company-idle-delay` to 0 is a terrible, terrible choice. 😃 Very few backends are prepared to deal with this kind of load in non-trivial projects. Maybe `ycmd` is the only one that does, so far.

**Comment by aaronjensen** [comment]
> Caching should migrate into each individual backend. 

This makes sense.
 
> The same logic you have offered here can be implemented in each individual backend. It could become even simpler, because it won't have to deal with the general case. The proposed change isn't too big anyway. Likewise, we could offer helpers doing this in the future, but I wouldn't hurry with that because of item 1.

I could try implementing this in `company-flow`. I'd guess I'd have to maintain a list of processes and the prefixes they're running against or something like that. Or maybe a global list of callbacks along w/ the prefixes they're waiting for. Any way, I could figure something out, it'd just be a shame to not let other backends benefit from the change.


> And finally, setting company-idle-delay to 0 is a terrible, terrible choice. 😃 Very few backends are prepared to deal with this kind of load in non-trivial projects. Maybe ycmd is the only one that does, so far.

Yes, it only works for async backends and it only works with these changes. They obviously wouldn't be able to handle the load if it was hitting every keypress. 0 is how autocomplete seems to work in other text editors, there's no need to stop typing to start to get suggestions. Granted, they have better threading so all backends may be async by default. The reality is that autocomplete is of limited use to me because I can often type faster than it completes and it interrupts flow to either pause and wait for a list of words that may not be what I want.

**Comment by dgutov** [comment]
> Any way, I could figure something out, it'd just be a shame to not let other backends benefit from the change.

Yes, but "other editors" provide and a lot of users prefer fuzzy completion. That requires giving up on the built-in caching anyway.

> I'd guess I'd have to maintain a list of processes and the prefixes they're running against or something like that. Or maybe a global list of callbacks along w/ the prefixes they're waiting for.

A buffer-local variable holding the details of the last request will probably be enough.

> 0 is how autocomplete seems to work in other text editors, there's no need to stop typing to start to get suggestions. Granted, they have better threading so all backends may be async by default.

There might be something to learn there, actually. I don't imagine that e.g. VS Code relies on JavaScript's threading features.

> The reality is that autocomplete is of limited use to me because I can often type faster than it completes and it interrupts flow to either pause and wait for a list of words that may not be what I want.

Unfortunately, I'm in a similar situation. But still, completion is *really* useful when you don't know what to type. In that situation, waiting a little shouldn't hurt.

**Comment by aaronjensen** [comment]
> A buffer-local variable holding the details of the last request will probably be enough.

I tried it out here, seems to work. I may rework it to be a higher order function that you can wrap function returned in the async cons cell from candidates with. Then, when ready we could pull it over here.

https://github.com/aaronjensen/company-flow/pull/2/files?w=1

> Unfortunately, I'm in a similar situation. But still, completion is really useful when you don't know what to type. In that situation, waiting a little shouldn't hurt.

If it's fast enough and accurate enough it's super useful, especially with the tab to complete and keep typing stuff I added. It'd require all the backends to be async (no dabbrev, but it could be replaced w/ something more powerful.)

> There might be something to learn there, actually. I don't imagine that e.g. VS Code relies on JavaScript's threading features.

tbh I don't know how electron and therefore atom/vs code work, I just know they're super fast and almost never stutter.

> Yes, but "other editors" provide and a lot of users prefer fuzzy completion. That requires giving up on the built-in caching anyway.

Is that really a conflict w/ caching? If your prefix length is 2 and you start your async call at 2 and cache that result with the fuzzy filter applied you can still apply fuzzing to the cache result.

**Comment by aaronjensen** [comment]
A second take, I like this method much more. Would you be interested in porting this as a helper function to `company-mode`? 

https://github.com/aaronjensen/company-flow/commit/54b489c16315184d189daa4ec229bdba799a7f34

It could possibly even be used on every async backend automatically if they have caching enabled. 

The one thing I'm not sure about is if it'd be safe for `company-flow--debounce-state` to be a single var for all backends at once. I don't know how multiple simultaneous async backends works.

**Comment by dgutov** [comment]
> A second take, I like this method much more. Would you be interested in porting this as a helper function to company-mode?

It's cute, but it still relies on the current semantics of async calls (which might also change). And since it assumes prefix matching (uses `all-completions`), it won't be universal. I'll hold off on incorporating it, at least until we see more demand.

> The one thing I'm not sure about is if it'd be safe for company-flow--debounce-state to be a single var for all backends at once. I don't know how multiple simultaneous async backends works.

Yes, single var will be a problem in that case. Grouped-backend async dispatches to all async backends using the same interface.

**Comment by dgutov** [comment]
> It'd require all the backends to be async (no dabbrev, but it could be replaced w/ something more powerful.)

Replaced with what? IIUC, it would preclude implementing backends entirely in Elisp. And we can't access contents of all buffers from an external process.

Although if we make Emacs *send* each buffer to an external process, after even change... I'm not sure I like this idea, though. We already have one `ycmd`. :)

> Is that really a conflict w/ caching? If your prefix length is 2 and you start your async call at 2 and cache that result with the fuzzy filter applied you can still apply fuzzing to the cache result.

It kind of is. Fuzzy matching goes hand-in-hand with sorting, because it tends to produce a lot of matches, and otherwise the irrelevant ones will too often be at the top.

We could apply regexp-based filtering like `a.*b.*c`, but we can't find and use the sorting algorithm that's appropriate for the given backend/language/environment.

**Comment by aaronjensen** [comment]
> It's cute, but it still relies on the current semantics of async calls (which might also change). And since it assumes prefix matching (uses all-completions), it won't be universal. I'll hold off on incorporating it, at least until we see more demand.

cute? 😄  I understand. fwiw, given the current interface it's probably hard for 3rd party backend authors to do things right. Looking at alchemist, they store the callback in a global which means that they just call the latest callback regardless, even if it's w/ previous completions. Obviously this isn't catastrophic, but it's not correct.

I'd love to see something more like flycheck has. Creating an async checker is so easy in flycheck it's nuts. You don't have to think about anything, just provide a command and a parsing function (the parsing dsl is quite nice too), it handles all the process calls. This is super nice and makes the checkers small and easy to write. I wrote 3 of them before I even attempted this company backend.

> Yes, single var will be a problem in that case. Grouped-backend async dispatches to all async backends using the same interface.

I guess it'd need to be a map then or something. 

> Replaced with what? IIUC, it would preclude implementing backends entirely in Elisp. And we can't access contents of all buffers from an external process.

For one, this: https://github.com/aaronjensen/vim-recentcomplete I'm thinking about porting it to company, just not sure when I'll have the time. Using keywords taken from recent git history is amazing. Not being able to search through buffers is unfortunate though. I'm guessing it can't be done w/ emacsclient because the server is single threaded, yeah?

> Although if we make Emacs send each buffer to an external process, after even change... I'm not sure I like this idea, though. We already have one ycmd. :)

Ohh.. I finally looked at `ycmd`, very interesting. I may have to try it out. Do you use it?



> Fuzzy matching goes hand-in-hand with sorting

Yeah, this is why I tend not to like it. I prefer sorting by other heuristics like how recently it was added (usually based on what backend it came from)

> It kind of is. Fuzzy matching goes hand-in-hand with sorting, because it tends to produce a lot of matches, and otherwise the irrelevant ones will too often be at the top.

I think I see. If each backend had its own cache it could sort as it wanted to.

**Comment by dgutov** [comment]
> fwiw, given the current interface it's probably hard for 3rd party backend authors to do things right. Looking at alchemist, they store the callback in a global which means that they just call the latest callback regardless, even if it's w/ previous completions.

`company-clang` is async, and it doesn't do that. I wish more people did higher-order function manipulations in Elisp.

> I'd love to see something more like flycheck has. Creating an async checker is so easy in flycheck it's nuts.

I don't know about that. Using macros comes with its own problems (e.g. versioning).

> I guess it'd need to be a map then or something.

That's one option. Alternatively, I'd make it take the variable symbol as an argument.

> Using keywords taken from recent git history is amazing.

That sounds interesting, although not exactly what dabbrev does. Does Git fetch those keywords quickly?

> Ohh.. I finally looked at ycmd, very interesting. I may have to try it out. Do you use it?

I don't, so far. I think it's most popular among C++ programmers (even though it supports several languages now).

> I prefer sorting by other heuristics like how recently it was added

Personally, I've been missing fuzzy completion in my Ruby work lately. Maybe I'm just getting lazy.

> I think I see. If each backend had its own cache it could sort as it wanted to.

Yes, but usually the sorting logic would reside in the external (background) process. So it's hard to keep the cache in Elisp.

**Comment by aaronjensen** [comment]
> company-clang is async, and it doesn't do that. I wish more people did higher-order function manipulations in Elisp.

Yeah, I'm not saying they're all wrong, I'm just saying it's easy to get wrong. And yes, a higher order function that was built-in that helped people do the right thing would be helpful. It wouldn't need to be a macro, though that does make it easy (not simple).

> I don't know about that. Using macros comes with its own problems (e.g. versioning).

Yeah, I don't have enough experience to speak to this. I can only speak to my experience of writing backends for both. The fact that I ended up borrowing some code from flycheck and other company backends says a lot whereas I only really had to understand configuration to write a flycheck checker. Like I said above, easier, not simpler, but easy can help encourage contributions. Flycheck also has the tendency to take more checkers under its own umbrella than company does with backends, so that's just a very different policy. Maybe the fact that most of them are just configuration (they tend to resist allowing more complicated checkers) makes this work better. 

> That sounds interesting, although not exactly what dabbrev does. 

No, it's not. vim-localcomplete was the closest to dabbrev. I used multiple backends combined.

My priority order in vim was:

1. Things changed and unsaved in this buffer
2. Any uncommitted changes in my repo
3. Anything committed in the last hour
4. Anything in any other buffer and/or in my project directory

> Does Git fetch those keywords quickly?

Very. Try:

```
git --no-pager diff --diff-filter=AM --no-color `git log -1 --before="1 hour ago" --format=%H HEAD` 2>/dev/null \
| grep '^+\s*..' 2>/dev/null \
| grep -v '+++ [ab]/' 2>/dev/null \
| sed 's/^+//' 2>/dev/null
```

You can replace "1 hour ago" with "1 day ago" or whatever you want. 

In recentcomplete I kept a running cache updated in the background and just used whatever was latest. I didn't need it to be up to the second for most of it (the recent changes in the buffer was up to the second, but that is super fast)

> Personally, I've been missing fuzzy completion in my Ruby work lately. Maybe I'm just getting lazy.

It's funny, every time I've tried fuzzy finding I always end up going back for one reason or another. I felt like it broke flow, but that's probably because I was so used to typing the symbol instead of the initials of the symbol. It'd be great if good sorting was also combined w/ fuzzy finding so you could at least use it for refining. Pretty tricky though :/

> Yes, but usually the sorting logic would reside in the external (background) process. So it's hard to keep the cache in Elisp.

Great point.

**Comment by dgutov** [comment]
> And yes, a higher order function that was built-in that helped people do the right thing would be helpful. It wouldn't need to be a macro, though that does make it easy (not simple).

IIUC, the higher order function you proposed would only handle caching for them, and only if the backend allows this kind of cache. It won't solve the general case.

> The fact that I ended up borrowing some code from flycheck and other company backends says a lot whereas I only really had to understand configuration to write a flycheck checker.

Flycheck checkers are simpler by design anyway (both because because they only have to do a couple of things, and the way to do that is strictly codified). So it's likely to remain the better source for learning the basics, even if it didn't have the advantage of more expansive documentation.

On the flip side, `auto-complete` provides macros to define completion sources, and nevertheless, people praised `company-mode`'s backend definitions for readability in comparison.

> Very. Try:

That's 60-100ms here. Not too bad, but probably requires caching.

> It's funny, every time I've tried fuzzy finding I always end up going back for one reason or another. I felt like it broke flow, but that's probably because I was so used to typing the symbol instead of the initials of the symbol.

Does it also happen with fuzzy algorithms available in e.g. Vim? When using flx, I've been consistently annoyed that it doesn't score very near matches high enough.

**Comment by dgutov** [comment]
See the comment in the PR.
