### ISSUE TITLE
Documentation: Difference between auto complete and idle complete

### ISSUE THREAD

**Issue by wol81** [company-mode/company-mode#582]
I just start using company-mode in the context of Javascript completion, and have a problem with understanding, what the difference between auto complete and idle complete is.  I did a M-x customize-group company, and had a look on the documentation of both.  I also tried to find some hints in company.el, and did some tests based on a simple test backend.  But I couldn't trigger any difference between both, even after activating auto-complete.

So: What is the intended behaviour / the intended workflow when using (1) auto completion and (2) idle completion?  I would be glad about some piece of documentation, that explains and compares the supposed behaviour of both.

Or do I miss some source of documentation?

**Comment by dgutov** [comment]
I'm hoping the docstrings for `company-idle-delay` and `company-auto-complete` explain the difference adequately.

**Comment by dgutov** [comment]
Should we rename `company-auto-complete` to `company-auto-finish`?

**Comment by wol81** [comment]
Am 2016-11-23 um 00:50 schrieb Dmitry Gutov:
> Should we rename |company-auto-complete| to |company-auto-finish|?

First, sorry for my silence regarding the hint you gave end of September 
- after I filed the question, the topic somehow left my attention...

You wrote:
> I'm hoping the docstrings for company-idle-delay and company-auto-complete explain the difference adequately.

Those docstrings are according to 
https://github.com/company-mode/company-mode/blob/master/company.el:

> (defcustom company-idle-delay .5
>   "The idle delay in seconds until completion starts automatically.
> The prefix still has to satisfy `company-minimum-prefix-length' before that
> happens.  The value of nil means no idle completion."

and

> (defcustom company-auto-complete nil
>   "Determines when to auto-complete.
> If this is enabled, all characters from `company-auto-complete-chars'
> trigger insertion of the selected completion candidate.
> This can also be a function."

So, when doing idle completion it waits the company-idle-delay until it 
does something (assuming the user doesn't interrupt).

Does auto completion do the same for certain chars, but without a delay, 
i.e. is it supposed to start completion immediately once one enters one 
of the chars from company-auto-complete-chars?

I.e. is the difference:
idle = complete after the configured delay, for all chars entered
auto = complete immediately, only for the list of configured chars

Well, the question wether you should rename company-auto-complete, I 
honestly cannot answer it right now.  I can say that what I wanted to do 
works more or less like I expect, but I felt to be unable to trigger the 
difference between auto and idle completion.

Thanks for your attention,

Wolfgang

**Comment by dgutov** [comment]
> Does auto completion do the same for certain chars, but without a delay, i.e. is it supposed to start completion immediately once one enters one of the chars from company-auto-complete-chars?

No, it does not. Instead it only works when completion is already in progress (the popup is visible), and, when certain characters are typed, inserts the currently selected completion in the buffer, and the said character, after it.

**Comment by wol81** [comment]
Am 2016-11-23 um 10:45 schrieb Dmitry Gutov:
>     Does auto completion do the same for certain chars, but without a
>     delay, i.e. is it supposed to start completion immediately once one
>     enters one of the chars from company-auto-complete-chars?
>
> No, it does not. Instead it only works when completion is already in
> progress (the popup is visible), and, when certain characters are typed,
> inserts the currently selected completion in the buffer, and the said
> character, after it.

Ah, thank you, now it is clear.  I always assumed that auto completion 
is an alternative that completely replaces idle completion by something 
that works somewhat different - so I thought I need to choose between 
idle and auto completion.  Thus, I totally missed what you write above.

I tried, and it works for me as you describe.

Wolfgang

**Comment by dgutov** [comment]
It does look ambiguous. So the question stands: "should `company-auto-complete` be renamed?"

Opinions from all users are welcome.

**Comment by yugaego** [comment]
Follow-up: `company-auto-complete` was renamed to `company-auto-commit`. See #1005 for more details.
