### ISSUE TITLE
is there reason returning `sole` instead of `exact` for :exit-function?

### ISSUE THREAD

**Issue by yuutayamada** [company-mode/company-mode#583]
Hello, thank you for maintaining this super convenient package.

I have a little question about this commit: 0cdcd07
It seems you intentionally changed :exit-function's behavior for company-capf.
But, according to the emacs' document (https://github.com/emacs-mirror/emacs/blob/emacs-24/lisp/minibuffer.el#L1707), I think it should use `exact` instead of `sole` because when company-mode's third party developers try to implement :exit-function, they need deferent implementation for `exact` and `sole`. (for `completion-at-point-functions` and `company-capf`)

or am I missing something? (I'm new to implement company-capf, so sorry if
I missing something)

I'm trying to add function, which is same functionality as :post-completion using the :exit-function, but is it wrong idea?

EDIT: added last sentence

**Comment by dgutov** [comment]
Hi!

Unfortunately, I don't recall the exact reason, but it might be this:

* The documentation doesn't exactly describe the difference between these options clearly.
* `exact` does not seem to be used much in the Emacs source code. For instance, `shell--command-completion-data` uses an exit-function that only cares about values `sole` and `finished`. Same in `makefile-completions-at-point`. And some other functions only care about `finished` (e.g. `comint--complete-file-name-data`). So returning `exact` isn't useful for them.

**Comment by yuutayamada** [comment]
> exact does not seem to be used much in the Emacs source code. ...

seems like we can't change 'sole -> 'exact if company-mode supports
those functions...

Thanks for your reply. I understood your design choice.

But let me write my problem in case if you care:

I tried to make [nim-mode](https://github.com/nim-lang/nim-mode)'s capf funciton and I could easily implement it.

But, when I made sure exit-function, the behavior doesn't match against
`completion-at-point`. (I'm triying to add `()` when the completion
result was function)

So, I put `message` function to my exit-function to check difference.

In the below state:

![screenshot from 2016-09-13 15-30-48](https://cloud.githubusercontent.com/assets/1082473/18604858/f8273bf4-7c37-11e6-965a-0713ea3c66ae.png)

I chose `format` to complete then I saw `sole` in message buffer.

But, when I call `completion-at-point` at same point (after `for`),
I saw `exact` in message buffer. (the `for` was completed to `format`)

So, I think currently supporting exit-function for both `company-capf`
and `completion-at-point` need some effort. (I was misunderstanding
that it was ok if I implement same way as completion-at-point when
I implemented company-capf for nim-mode)

**Comment by dgutov** [comment]
> (I was misunderstanding
that it was ok if I implement same way as completion-at-point when
I implemented company-capf for nim-mode)

The big idea is that you should be able to do that.

What if your exit-function handles `sole` and `exact` the same way?

**Comment by yuutayamada** [comment]
> What if your exit-function handles sole and exact the same way?

I think this way would work in my case, but I'm really not sure
whether the `completion-at-point` return `sole`. (I compared the
difference between `shell--command-completion-data` and
nim-mode's capf function, but both were using `complete-with-action`
internally...)

**Comment by dgutov** [comment]
> but I'm really not sure whether the completion-at-point return sole.

AFAICS, it happens in `minibuffer-force-complete` (`lisp/minibuffer.el`, line 1282).
