### ISSUE TITLE
`keep-prefix' value of `ignore-case' interacts badly with grouping

### ISSUE THREAD

**Issue by c02y** [company-mode/company-mode#584]
![64-14_12dead](https://cloud.githubusercontent.com/assets/2135996/18609305/800558c6-7cc4-11e6-87b7-9c7209d1dc76.png)

See the problem, I type **gsk**, the first candidate is a yasnippet, the others are created by company-capf, but all of them are begun with gsk not the real one, it is fine if I hit Enter or TAB on the yasnippty, it will insert it the right one, but not the others, for example, if you choose the second one, it will insert "gsks-save-killed-list" not the real one "gnus-kill-save-kill-buffer".

This is my company-backends:

```
(setq company-backends
      '(
        (
         company-files
         company-dabbrev
         company-keywords
         company-capf
         company-yasnippet
         )
        (company-abbrev company-dabbrev)
        ))
```

After I comment out line by line, I found that this is caused by "company-dabbrev", other backends are working fine with "company-capf". But if I disable "company-dabbrev", company won't complete any words existed inside the buffer.

**Comment by dgutov** [comment]
Hi! Thanks for the report.

Would

```el
(setq company-dabbrev-ignore-case t)
```

be an adequate workaround for you?

**Comment by c02y** [comment]
Yes, it works as expected now, wonder why this important variable is not mentioned in the documentation.

Actually, I'm working on how to configure the best grouped company-backends for different major modes, although having been using company-mode for over one year (already got a configuration long time ago), but recently realized it was not working as I expected, and started looking for the official documentation about how to configure it and found nothing useful.

For example
in emacs-lisp-mode, words in buffers, yasnippet, elisp(company-capf), etc., sorted in this order in the droplist

in c/c++-mode, words in buffers, yasnippet, the name(variable, function, struct etc.), etc,.

in org-mode, words in buffers,  yasnippet, etc,

in latex-mode, words in buffers, yasnippet, latex-environment, etc.

If I insert and "/", it should use company-files as the primary backend.

In above examples, there will be a default company-backends for all the major modes when company-mode is enabled, there will be different configuration for a specific minor mode.

    (setq company-backends
      '(
        (
         company-files
         company-dabbrev
         company-keywords
         company-capf
         company-yasnippet
         )
        (company-abbrev company-dabbrev)
        ))
    (add-hook 'emacs-lisp-mode-hook
		  (lambda ()
			(set (make-local-variable 'company-backends)
				 (append company-backends
						 '((
							company-elisp
							))))))

But I cannot make the company-elisp work, there always are such problems, the two backends won't work well for a specific major mode.

No documentation or examples.

**Comment by dgutov** [comment]
> wonder why this important variable is not mentioned in the documentation

It's in the `Company Dabbrev` section of `M-x customize-group company`, which is _the_ documented way to configure things. Anyway, it's a workaround for a bug I haven't been aware until now. Not a well-known course of action.

I could answer the rest of your message, but it's irrelevant to this issue. Please either post it to StackExchange, or Reddit. Or at least create a separate issue.

**Comment by c02y** [comment]
`(setq company-dabbrev-ignore-case t)` is not perfect, if I set this, the candidate will all be lower case, for example, I got a function name like FunctionName, the candidate in droplist will be functionname and I'm not gonna choose it from the list since it is not right.

Is there perfect way that company supports both fuzzy matching and right upper-lower cases?

**Comment by dgutov** [comment]
@c02y I have re-read the question now, and it's probably too late, but you might want to try setting `company-dabbrev-downcase` to `nil`. Or use `company-dabbrev-code` instead. Not sure about fuzzy matching, most built-in backends don't.

**Comment by c02y** [comment]
Thanks, I'm using Spacemacs now, it is set `company-dabbrev-downcase` to `nil` and use `company-dabbrev-code` (I haven't read the code carefully though)
