### ISSUE TITLE
Disable company meta when eldoc is using the minibuffer?

### ISSUE THREAD

**Issue by et2010** [company-mode/company-mode#588]
I was writing a new language mode with company backend and eldoc support. Everything works fine, except that in certain senario, the company meta message will interrupt the message (multi-line doc) created by eldoc.

Is there a canonical way to disable company meta when eldoc is taking control of  the minibuffer?  Thanks.

**Comment by dgutov** [comment]
How would we determine if that's something we want to do?

Suppose we're typing out an argument in a method call. The eldoc describes the method, but the meta string is pertaining to the value we're choosing for the current argument. It seems more important in this case, doesn't it?

**Comment by et2010** [comment]
Yes, it is true that current behavior is good in most situations, but in some unusual cases, maybe temporarily disabling the meta message is a more appropriate choice. 

In my case,  since the eldoc message is very long, the size of minibuffer is maxed. And when I'm typing a new keyword (that have only one possible candidate), the minibuffer will change to its original size to show the meta message, and change back to max size within a second. The size changing issue bothers me a lot especially when I type fast, and when this is happening, I found that the meta message is of little or no use either since it only lasts less than a second.

**Comment by dgutov** [comment]
> in some unusual cases, maybe temporarily disabling the meta message is a more appropriate way

Since you're the author of the eldoc-function, and the backend, would you be fine with making that choice yourself? When the meta should not be used, return `nil` from the backend.

The patch to support this on the company-mode's side should be simple:

```diff
diff --git a/company.el b/company.el
index d46e96a..64d29c0 100644
--- a/company.el
+++ b/company.el
@@ -3008,9 +3008,8 @@ Delay is determined by `company-tooltip-idle-delay'."
   (when getter
     (setq company-echo-last-msg (funcall getter)))
   (let ((message-log-max nil))
-    (if company-echo-last-msg
-        (message "%s" company-echo-last-msg)
-      (message ""))))
+    (when company-echo-last-msg
+      (message "%s" company-echo-last-msg))))
 
 (defun company-echo-show-soon (&optional getter)
   (company-echo-cancel)
@@ -3083,7 +3082,7 @@ Delay is determined by `company-tooltip-idle-delay'."
             "}")))
 
 (defun company-echo-hide ()
-  (unless (equal company-echo-last-msg "")
+  (when (equal company-echo-last-msg (current-message))
     (setq company-echo-last-msg "")
     (company-echo-show)))
 
```

**Comment by et2010** [comment]
Thanks for your advice, I've figured it out. It is actually pretty trivial. Sorry for wasting your precious time.

**Comment by et2010** [comment]
Sorry, I was wrong. It is not trivial at all. After applying the patch, and forcing the meta function to return nil. it still happens.

**Comment by dgutov** [comment]
What are you doing when it "still happens"?

Try also evaluating this:

```el
(eldoc-add-command #'company-select-next)
(eldoc-add-command #'company-select-previous)
```

That will make ElDoc work after `M-n` and `M-p`.

**Comment by dgutov** [comment]
I've pushed a fix which should stop it from interfering at least when `meta` returned from the backend is empty.

That doesn't address all possible scenarios (we could try to resolve the interference in a different way, e.g. when meta is not empty, try to show it through eldoc's mechanism, as long as we can ensure that eldoc does get displayed).

I'll defer that to #797, though.
