### ISSUE TITLE
candidates are transformed into lowercase

### ISSUE THREAD

**Issue by stardiviner** [company-mode/company-mode#589]
``` python
import cv2

cv2.imread
```

The candidates like `cv2.IMREAD_ANYCOLOR` will becames to `cv2.imREAD_ANYCOLOR` when I typing `cv2.im`. candidates should match case insensitive. but should not changed when inputted and showing.

**Comment by dgutov** [comment]
What does `M-x company-diag` say?

**Comment by stardiviner** [comment]
Here is the command `company-diag` output:
```
Emacs 26.0.50.1 (x86_64-unknown-linux-gnu) of 2016-10-05 on dark
Company 0.9.0

company-backends: ((elpy-company-backend :with company-yasnippet)
 company-files
 (company-capf :with company-yasnippet)
 company-dabbrev-code company-abbrev company-keywords)

Used backend: (elpy-company-backend :with company-yasnippet)

Prefix: (#("im" 0 2
   (fontified t))
 . t)

Completions: none
```

**Comment by dgutov** [comment]
And the major mode is?

**Comment by dgutov** [comment]
Anyway, you should report this to elpy.

**Comment by stardiviner** [comment]
Here is my screenshot.
And my major-mode is `python-mode`.

![elpy-issue](https://cloud.githubusercontent.com/assets/378699/19138440/cfe74de2-8bae-11e6-8e43-4a62380bb75f.png)
