### ISSUE TITLE
variable storing candidates changed unexpectedly

### ISSUE THREAD

**Issue by et2010** [company-mode/company-mode#590]
### Description: 
Open a new buffer with following sample backend activated, try to make the first completion, eg. `geometry polygon`, then use `describe-variable` on `sample-completion`, it shows that `sample-completion` has been changed to following value:

`("geometry rotate" "geometry set" "geometry tessellate" "geometry translate" "geometry triangulate")`

_**Comparing with its initial value, it can be seen that some elements of the original list are missing.**_

I'm not sure if this is caused by company or by my settings, but I did try it on stock emacs and still got the same result. I've spent several hours to debug this but can't find the cause behind this.

 _**Any help will be appreciated, thanks!**_

### OS
emacs 24.5, archlinux

### Source Code
Here is the backend to reproduce this issue:

```elisp
(require 'dash)
(require 'company)

(defconst sample-completions
  '("geometry rotate" "geometry edge" "geometry set" "geometry translate" "geometry import" "geometry generate" "geometry delete" "geometry tessellate" "geometry export" "geometry node" "geometry group" "geometry triangulate" "geometry copy" "geometry list" "geometry explode" "geometry polygon"))

(defun company-sample-candidates (prefix)
  (cl-remove-if-not
   (lambda (c) (string-prefix-p prefix c))
   sample-completions))

(defun company-sample-prefix ()
  (and (eq major-mode 'text-mode)
       (not (company-in-string-or-comment))
       (--if-let (when (or (looking-at "\\_>")
                           (looking-back " " (- (point) 1)))
                   (save-match-data
                     (let ((line (buffer-substring-no-properties
                                  (line-beginning-position)
                                  (point))))
                       (string-match "\\`[ \t]*\\([a-zA-Z_][a-zA-Z0-9_]*\\( \\| [a-zA-Z_][a-zA-Z0-9_]*\\)?\\'\\)" line)
                       (match-string 1 line))))
           (if (looking-back " " (- (point) 1))
               (cons it t)
             it)
         'stop)))

(defun company-sample-backend (command &optional arg &rest ignored)
  (interactive (list 'interactive))

  (cl-case command
    (interactive (company-begin-backend 'company-sample-backend))
    (prefix (company-sample-prefix))
    (candidates (company-sample-candidates arg))))

(add-to-list 'company-backends 'company-sample-backend)

(provide 'company-sample)
```

**Comment by et2010** [comment]
### First completion
![11](https://cloud.githubusercontent.com/assets/11584902/19163540/f6f3843e-8c2e-11e6-9f25-9f75d1a04801.PNG)

### Second completion
![22](https://cloud.githubusercontent.com/assets/11584902/19163547/0056c8c4-8c2f-11e6-82fc-8de07ff3cede.PNG)

**Comment by dgutov** [comment]
Hi!

What happens is, `cl-remove-if-not` can return the original list unchanged if all its elements satisfy the predicate. And it does so in this scenario.

But then, `company--preprocess-candidates` alters it destructively with `sort`, and the constant's value becomes broken. You can fix that by making sure to make a copy of the list first:

```el
(defun company-sample-candidates (prefix)
  (cl-delete-if-not
   (lambda (c) (string-prefix-p prefix c))
   (copy-sequence sample-completions)))
```

Maybe we should make a copy inside `company--preprocess-candidates`, to be on the safe side. But usually the list of completions returned by the backend is transient. Not sure if the added safety in the uncommon case would be worth the overhead (on longer lists).

**Comment by dgutov** [comment]
That happens to this particular list because all elements in it start with "geometry". So there's nothing to filter out, and `cl-remove-if-not` does not create a copy.

**Comment by et2010** [comment]
That list used to be part of a longer list which contains elements not starting with "geometry", but same thing happens to that list and the missing elements are the same.

**Comment by dgutov** [comment]
With the other list, the problem must be starting earlier, when the prefix is shorter.

**Comment by et2010** [comment]
This is strange to me. Is there a way to debug this or should I just leave it behind?

**Comment by dgutov** [comment]
If my solution works for that other list as well, then there's not much left to debug.

Here's how it might also happen:

```el
(setq l '(1 2))
(eq (cl-remove-if-not (lambda (v) (= v 2)) l) (cdr l)) => t
```

Basically, `cl-remove-if-not` tries to minimize copying when it can. If all your matching elements are at the end, the problem occurs to that tail of the list.

**Comment by et2010** [comment]
Thanks for the explanation and the insight of `cl-remove-if-not`. Indeed, the list above is at the end of the other list.
