### ISSUE TITLE
Problem with company-ispell 

### ISSUE THREAD

**Issue by Enrico68** [company-mode/company-mode#591]
Hello,
I am trying to use `company-ispell` with italian language. When I type I get only english words completion. If I want to use the italian language I need to explicitly call the command. I post a [screen](http://imgur.com/a/n8eIh), and sorry for my english !

**Comment by dgutov** [comment]
`company-ispell` is not in `company-backends` by default. You need to customize the latter to use it.

**Comment by Enrico68** [comment]
Thanks @dgutov  , sorry for this superficial question. I think we can close it
