### ISSUE TITLE
smart partial fuzzy completion for candidates

### ISSUE THREAD

**Issue by stardiviner** [company-mode/company-mode#594]
This is an feature request. This function will help user get the exact candidate when they can't remember the first some characters.

For example, there are all available candidates for prefix:

    Object.

It has all completion candidates like this:

    - hello
    - ellocate
    - name
    - amend
    - behavior
    - vioret

You can see some candidates has some string in common.

If user type string like this:

    Object.am

It should complete candidates for `name` and `amend`.

**Comment by dgutov** [comment]
See #47 and https://github.com/PythonNut/company-flx.
