### ISSUE TITLE
How to handle module prefixes?

### ISSUE THREAD

**Issue by jhonnyseven** [company-mode/company-mode#595]
I could not find anything related, sorry if this is duplicate:

How to get company complete symbols prefixed with something? For example if I import do-foo from module m with prefix m: and want m:do- give completions.

The colon is a valid symbol character.

I think there should be a buffer local way to customize company-grab-symbol or something.

Any hints would be helpful. Thanks.

**Comment by dgutov** [comment]
And you want company-mode to know which module which symbols have been imported from?

**Comment by jhonnyseven** [comment]
Of course not.

I am just looking for a way to provide my own company-grab-symbol.

**Comment by dgutov** [comment]
The easiest way to solve this should be to make `:` a non-symbol character in those buffers. Similarly to ruby-mode:

```el
    (modify-syntax-entry ?: "'" <xxx-mode-table>)
```

Or you could use `company-dabbrev` and customzie `company-dabbrev-char-regexp`.

**Comment by jhonnyseven** [comment]
I think I'm happy with modifying the syntax table. This was for scheme, and the semicolon is not used too much anyways.

Thank you.
(You can close this issue.)

**Comment by dgutov** [comment]
You're welcome.

> (You can close this issue.)

You could, too.
