### ISSUE TITLE
During complete I can't input 't'

### ISSUE THREAD

**Issue by Qquanwei** [company-mode/company-mode#596]
![image](https://cloud.githubusercontent.com/assets/9263655/19551946/511178fc-96e0-11e6-97cf-9bdf91ff24eb.png)
I disable company-mode that's no this problem

**Comment by dgutov** [comment]
Is that an effect of `company-require-match`?

**Comment by scottgrayson** [comment]
I have this same problem.

my `company-require-match` is set to `nil` I also tried 'never'

what other info can help with debugging? @dgutov

**Comment by dgutov** [comment]
@scottgrayson As usual, step-by-step reproduction scenario starting with `emacs -Q -L ~/.emacs.d/elpa/company-xyz -l company` would be best.

**Comment by scottgrayson** [comment]
I was changing keybinds incorrectly
```
(with-eval-after-load 'company
  (define-key company-active-map (kbd "tab") nil)
```
(kdb "tab") is incorrect I assume. I no longer need this, so I removed it
