### ISSUE TITLE
company-clang offers no completion for function names in global scope

### ISSUE THREAD

**Issue by DeepWalter** [company-mode/company-mode#602]
Hi, I'm writing c code using company-clang for completion but find that completion is not offered for function names in global scope:
<img width="1276" alt="screen shot 2016-10-25 at 10 49 52" src="https://cloud.githubusercontent.com/assets/14358521/19671393/02863532-9aa1-11e6-9477-c29a31f0e9c0.png">
Here is what `company-diag` says:
<img width="1276" alt="screen shot 2016-10-25 at 10 50 12" src="https://cloud.githubusercontent.com/assets/14358521/19671436/4dabf592-9aa1-11e6-9d58-d078c527f75e.png">

But completion is offered **inside** the function block:
<img width="1276" alt="screen shot 2016-10-25 at 10 50 30" src="https://cloud.githubusercontent.com/assets/14358521/19671469/8c1b21b8-9aa1-11e6-9b20-c503fcfaf7d8.png">
Here is the diag-info:
<img width="1276" alt="screen shot 2016-10-25 at 10 50 43" src="https://cloud.githubusercontent.com/assets/14358521/19671488/ad9d8dc6-9aa1-11e6-85f6-3f933a46381f.png">

Here is my configuration for company-mode:

    (use-package company
     :init
     (global-company-mode 1)
     :config
     (delete 'company-semantic company-backends)
     (setq company-show-numbers 1)
     (setq company-minimum-prefix-length 2)
     (setq company-tooltip-limit 10)
     (setq company-tooltip-flip-when-above t)
     (setq company-idle-delay 0.2))
 
I've no idea why this happens, can anyone help me?

**Comment by dgutov** [comment]
If you see `foo` among completions in some contexts but not others, then apparently it's what `clang -code-completion-at` does.

It only offers completion for function calls, but not when writing the signature. Take a look inside `*clang-output*` buffer if you're curious.
