### ISSUE TITLE
company-indent-or-complete-common is broken in shell-mode

### ISSUE THREAD

**Issue by cpitclaudel** [company-mode/company-mode#605]
To reproduce:

* `(define-key comapny-active-map (kbd "TAB") 'company-indent-or-complete-common)`
* `M-x shell`
* `cd /h`, `M-x company-manual-begin`, `<tab>`

Instead of inserting the first result (`/home`), Emacs inserts a tab character.

This is due to `indent-for-tab-command` inserting a tab, despite `tab-always-indent`.  Is that a bug in `indent-for-tab-command`?

**Comment by dgutov** [comment]
> Is that a bug in indent-for-tab-command?

Maybe it is. Or maybe the notion of indentation just doesn't apply there.

But how would we figure out that the inserted tab was not the result of an indentation function?

**Comment by cpitclaudel** [comment]
> But how would we figure out that the inserted tab was not the result of an indentation function?

Not sure what you mean :/ I think I could open an Emacs bug report, and maybe we'll learn about a better to check whether indentation can happen at the current point; would that help?

**Comment by dgutov** [comment]
Maybe we could blacklist some values of `indent-line-function`. Like `indent-relative`, in this case.

**Comment by dgutov** [comment]
Like:

```diff
diff --git a/company.el b/company.el
index d46e96a..ce5a652 100644
--- a/company.el
+++ b/company.el
@@ -2104,6 +2104,9 @@ With ARG, move by that many elements."
   (cond
    ((use-region-p)
     (indent-region (region-beginning) (region-end)))
+   ((memq indent-line-function
+          '(indent-relative indent-relative-maybe))
+    (company-complete-common))
    ((let ((old-point (point))
           (old-tick (buffer-chars-modified-tick))
           (tab-always-indent t))

```

**Comment by cpitclaudel** [comment]
This would work :) Assuming that the behavior we're seeing isn't indicative of an issue with the semantics of `tab-always-indent`, then this is a pragmatic solution.

**Comment by dgutov** [comment]
> the behavior we're seeing isn't indicative of an issue with the semantics of tab-always-indent

That value means `indent-line-function` is called. And that function, in this case, inserts a tab. Not much to be done here, I think.

**Comment by cpitclaudel** [comment]
Ok.  Your patch looks perfect then :)

**Comment by dgutov** [comment]
Does this command work fine in e.g. `haskell-mode`, by the way? IIRC, indentation is also unstable there.

**Comment by cpitclaudel** [comment]
It doesn't: tab cycles through indentation :/.

**Comment by dgutov** [comment]
Should we do something about that as well? I'm open to suggestions.

**Comment by dgutov** [comment]
Hmm, we could look at the value of `electric-indent-inhibit`.

**Comment by cpitclaudel** [comment]
This would be nice too… but I'm not sure how (nor what the semantics would be: under which conditions would be want to complete, rather than cycling through indentation?)

**Comment by dgutov** [comment]
Umm... maybe always? I haven't thought this through. :)

Let's leave it aside for now.

**Comment by dgutov** [comment]
Or maybe not. Consider: `text-mode` uses `indent-relative` as its `indent-line-function`.

Should we also make `company-indent-or-complete-common` always complete there, and never indent?

**Comment by cpitclaudel** [comment]
I think so, but I wonder if other people will come up with other use cases :/ Could we maybe make the `'(indent-relative indent-relative-maybe)` list from your patch above into a defcustom?

**Comment by dgutov** [comment]
> I think so

What differentiates those indentation functions from Haskell's? Is it the fact that they add whitespace *inside* a line, not just at indentation? 

> Could we maybe make the list from your patch above into a defcustom?

I'd rather wait until people ask. And anyway, it's not hard to copy and define one's own version of this command.

**Comment by cpitclaudel** [comment]
> What differentiates those indentation functions from Haskell's? Is it the fact that they add whitespace inside a line, not just at indentation? 

Probably.  Is there a way we can revert the indentation function's changes after the fact, though?  If so, we could check whether the function actually re-indented (i.e. changed the number of spaces at the beginning of the line), and if not run completion.

> I'd rather wait until people ask. And anyway, it's not hard to copy and define one's own version of this command.

Excellent point; thanks.

**Comment by dgutov** [comment]
> Is there a way we can revert the indentation function's changes after the fact, though?

Maybe using undo (that might underact badly with things like `undo-tree`, though). Or by parsing the undo history.

> If so, we could check whether the function actually re-indented

That definitely sounds like parsing the undo history.

> and if not run completion

And what if the indentation function only added spaces in the middle of the line? I fear this is still a valid use case, since those functions do that.

Anyway, there's probably not too many of indentation functions like that, and a blacklist might work almost as well.

**Comment by cpitclaudel** [comment]
> Anyway, there's probably not too many of indentation functions like that, and a blacklist might work almost as well.

Yeah; that's probably safer.

**Comment by cpitclaudel** [comment]
Thanks!
