### ISSUE TITLE
Syntax highlighting in doc popup

### ISSUE THREAD

**Issue by Pireax** [company-mode/company-mode#608]
Hello,
Would it be possible to have syntax highlighting in the tooltip?

**Comment by dgutov** [comment]
What kind of syntax highlighting?

**Comment by dgutov** [comment]
Ah, in the documentation. We already support it when displaying the documentation buffer.

But if you talking about a popup, you better ask about it at the source: https://github.com/expez/company-quickhelp

**Comment by Pireax** [comment]
I'll do that, thanks.
