### ISSUE TITLE
JavaScript string completion lowercase

### ISSUE THREAD

**Issue by peteyy** [company-mode/company-mode#611]
When used with variable completion it works fine but when I try to insert something into strings I only get the lowercase versions. I'm not aware of how things work but I assume different backend is used for strings because they tend to be natural language most of the time.

Probably ispell backend issue?

Issue captured:
![image](https://cloud.githubusercontent.com/assets/7130689/20260196/d6d83bf2-aa58-11e6-93da-23c34ed06717.png)

Working example on variable completion:
![image](https://cloud.githubusercontent.com/assets/7130689/20260280/2ead4d36-aa59-11e6-81cc-b89a6b7f1910.png)

company-diag output:
```
Emacs 25.1.1 (x86_64-apple-darwin16.1.0) of 2016-11-11 on Peters-MacBook-Pro.local
Company 0.9.0

company-backends: (company-bbdb company-nxml company-css company-eclim company-semantic company-clang company-xcode company-cmake company-capf company-files
              (company-dabbrev-code company-gtags company-etags company-keywords)
              company-oddmuse company-dabbrev)

Used backend: (company-dabbrev-code company-gtags company-etags company-keywords)

Prefix: stop
Completions: none
```

**Comment by dbarros** [comment]
@peteyy Any luck in finding an answer to this?

**Comment by dgutov** [comment]
I expect the `company-diag` output above is not accurate. I.e. the command was invoked when point is outside of a string.
