### ISSUE TITLE
How to define a company candidate

### ISSUE THREAD

**Issue by eflanigan00** [company-mode/company-mode#612]
I'm trying to call (defun company-quickhelp--doc (selected) from the position my cursor is on.
I need to create a selected which I think is a company-candidate.
The goal is that I could press a key while over a variable or function to show the help in popup or pos-tip

**Comment by dgutov** [comment]
I'm not sure you can do that easily, but if you want to try, you'll at least need `company-candidates` and `company-selection` assigned. `company-candidates` is a list of strings, `company-selection` is an integer.

However, to get the documentation command to work, you also need `company-backend` set to a function that adheres to the backend API. Or at least the `doc-buffer` command that is used here.

**Comment by eflanigan00** [comment]
I'm a beginner with elisp and I don't know the design of company.
But this is what I'm thinking. I want to use company and the activated backend(s) to get the docstring.
I've seen this work with company-quickhelp.

Then I can display the docstring in whichever way I want to. 

Simple elisp would be great to start:

    (setq company-candidates "message")
    (setq company-selection 1)
    (message (company-quickhelp--doc (nth 0 company-candidates)))

I think this is where I'm failing:
    (let* ((doc (company-call-backend 'doc-buffer selected))

**Comment by dgutov** [comment]
> (setq company-selection 1)

That's not a list.

And you haven't set `company-backend`.

> I'm a beginner with elisp

You might want to come to this project later, then.

**Comment by eflanigan00** [comment]
Sorry copy past error
    (setq company-candidates '("message"))

Shouldn't the backend be set already because I'm in an el file (or whatever file I'm in)?

**Comment by dgutov** [comment]
Not really. A specific backend is picked anew every time completion starts.

**Comment by eflanigan00** [comment]
I will leave you alone, if you think of an easy way to return the doc string using company I'd be interested
    (setq company-backend 'company-elisp)
    (setq company-candidates '("message"))
    (setq company-selection 1)
    (message (company-quickhelp--doc (nth 0 company-candidates)))

**Comment by dgutov** [comment]
```el
(let ((company-backend 'company-elisp)
      (company-candidates '("message"))
      (company-selection 0))
  (company-show-doc-buffer))
```

`company-quickhelp--doc` is defined in a different package (I don't have it installed).

**Comment by eflanigan00** [comment]
Thank you. I will take your advice and try to learn more lisp before taking on these things.
