### ISSUE TITLE
Popup deformed after splitting window

### ISSUE THREAD

**Issue by moyotar** [company-mode/company-mode#615]
```
OS: win10
GNU Emacs 24.5.1 (i686-pc-mingw32) of 2015-04-11 on LEG570
Company version: 0.9.0
```
At first, there‘s only one window.
![image](https://cloud.githubusercontent.com/assets/22092607/20618782/f7c1e5b2-b32b-11e6-85b4-6e5456135de5.png)

After I typed `C-x 3` to split window. A bug happened.
![image](https://cloud.githubusercontent.com/assets/22092607/20618854/53cee1c0-b32c-11e6-84d7-f653d424e11e.png)

I don't know whether it exists or not in the newest release 0.9.2. Because I had used `el-get` to update it and it's still the version of 0.9.0.

**Comment by dgutov** [comment]
Sorry about the considerable wait. Should be fixed now in master. Thanks!
