### ISSUE TITLE
Support for sql-interactive-mode

### ISSUE THREAD

**Issue by arkhan** [company-mode/company-mode#617]
Hello,

It's posible to add native support for sql-mode like:
http://emacs.stackexchange.com/questions/26365/is-there-a-company-backend-for-completion-in-sql-interactive-mode

**Comment by dgutov** [comment]
The fellow in the answer should make it a `completion-at-point-function` element and contribute it to Emacs. It will also work in `company-mode`.

**Comment by agzam** [comment]
I've tried using `company-tabnine` for sql-mode, it's not too bad. I'd like to find a way to make it work in sql-interactive mode.
