### ISSUE TITLE
Is there anyway to combine ycmd result with gtags?

### ISSUE THREAD

**Issue by kangjianbin** [company-mode/company-mode#619]
Hi All,

I want to use company-gtags to find candidates first, then if '.' or '->' is typed, use ycmd to find candidates.
Is it possible?
I tried to put gtags and ycmd in the same group, but there are too many candidates when typed '.'.

Thanks,
Jianbin

**Comment by dgutov** [comment]
You can group, and you can write your own backend (the API is fairly simple) that would dispatch to one or the other.

**Comment by kangjianbin** [comment]
Thanks. I switched to irony-mode, and modify `company-iony-prefix` to
```elisp
(defun company-irony-prefix ()
  "Prefix-command handler for the company backend."
  (and buffer-file-name
       (or (not (company-in-string-or-comment))
           nil)
       (or (and (looking-back "\\(\\.\\|->\\|::\\|/\\)[_a_zA-Z0-9 \t]*")
                (company-grab-symbol-cons "\\.\\|->\\|::\\|/" 2))
           nil)))
```
It works well. Looks like this functon works on ycmd too.
