### ISSUE TITLE
company-clang always No completion found

### ISSUE THREAD

**Issue by glowingboy** [company-mode/company-mode#620]
hi, i am new to company.
when i setup the company, and want to use it.
there are always:
```
No completion found
user-error: Cannot complete at point
```

here is my init setup:

```
(require 'cc-mode)
(require 'company)
(add-hook 'after-init-hook 'global-company-mode)
(setq company-backends (delete 'company-semantic company-backends))
(define-key c-mode-map [(tab)] 'company-complete)
(define-key c++-mode-map [(tab)] 'company-complete)
(setq company-clang-executable "/usr/bin/clang-3.8")
```

and i also found, when i want to exit the emacs, i found compay-clang still running(have a active buffer, shown in process list):
`company-clang   run     *clang-output*  /dev/pty1    /usr/bin/clang-3.8 -fsyntax-only -Xclang -code-completion-macros -x c++ -I/cygdrive/e/lua/include -I/usr/include -Xclang -code-completion-at=-:28:5 -`

btw, i use this setup(almost the same, such as include path) for auto-complete-clang, and it works fine.

**Comment by glowingboy** [comment]
i seems that company-clang have been running into a loop, because when i try to close the *clang-output* buffer, it always left a message which is "Buffer "*clang-output*" has a running process; kill it? (yes or no) ".
and the more important is that there is nothing in that buffer.

**Comment by dgutov** [comment]
Can you compare the actual commands that `auto-complete-clang` runs, against what we call?

**Comment by dgutov** [comment]
> when i try to close the clang-output buffer, it always left a message which is "Buffer "clang-output" has a running process

That's means that the latest Clang call still isn't finished.

**Comment by juergenhoetzel** [comment]
I also encountered this (Cygwin) issue and fixed it by setting `process-connection-type` to `nil` in #621 

See related Magit fix: [We need process-connection-type to be nil on cygwin](https://github.com/magit/magit/commit/2acc8be62357015205123fa7f1a7b4e9f3ef3891)

**Comment by dgutov** [comment]
@glowingboy Does that fix it for you?

**Comment by dgutov** [comment]
Shouldn't the Cygwin port itself handle this?

**Comment by juergenhoetzel** [comment]
> Shouldn't the Cygwin port itself handle this?

You mean fixing the *PTY* emulation  issues in Cygwin/Emacs? I don't know if this is an issue in Emacs/Cygwin or Cygwin itself. There are already multiple *PTY* related bug reports for Emacs/Windows.

Because we don't need any job control feature and  pipes are also more efficient/robust than PTYs I would prefer the just use Pipes and thus avoid the PTYs related issues.

**Comment by glowingboy** [comment]
> Does that fix it for you?
yes, it is. 
you guys really do me a great favor. thanks a lot@juergenhoetzel , @dgutov
