### ISSUE TITLE
Checking Emacs version repeatedly is slow

### ISSUE THREAD

**Issue by raxod502** [company-mode/company-mode#622]
Here is some code from [`company.el`](https://github.com/company-mode/company-mode/blob/5e49ddf3d2fe8baf1eff12383df2c6dc5ead9ef7/company.el#L2581):

```
(defun company--window-width ()
  (let ((ww (window-body-width)))
    ;; Account for the line continuation column.
    (when (zerop (cadr (window-fringes)))
      (cl-decf ww))
    (unless (or (display-graphic-p)
                (version< "24.3.1" emacs-version))
      ;; Emacs 24.3 and earlier included margins
      ;; in window-width when in TTY.
      (cl-decf ww
               (let ((margins (window-margins)))
                 (+ (or (car margins) 0)
                    (or (cdr margins) 0)))))
    (when (and word-wrap
               (version< emacs-version "24.4.51.5"))
      ;; http://debbugs.gnu.org/19300
      (cl-decf ww))
    ;; whitespace-mode with newline-mark
    (when (and buffer-display-table
               (aref buffer-display-table ?\n))
      (cl-decf ww (1- (length (aref buffer-display-table ?\n)))))
    ww))
```

I was debugging a problem that was causing `company-mode` to lag my Emacs a lot, and the profiler output showed that `version<` in this function accounted for 15% of the processing time in `post-command-hook`.

It seems like this kind of checking should be done statically, not in a function that can be called many times per second.

I can make a pull request, but I thought I would report the issue first, in case I massively misunderstand things (which happens fairly often).

**Comment by dgutov** [comment]
Please try evaluating this: `(benchmark 100 (version< "24.3.1" emacs-version))`.

**Comment by raxod502** [comment]
In a fresh Emacs, I get `0.001734s`. But in a problem buffer, I get `3.266578s`.

**Comment by dgutov** [comment]
> Here are full profiling results from a problem buffer

Thanks. That's rather weird, but it's a sampling profiler, so the results might be imprecise.

Is there anything else in particular you can tell about the problem buffer?

> But in a problem buffer, I get 3.266578s.

Even without `company-mode` enabled? Can you reproduce that situation from scratch somehow, for a proper bug report to the core?

**Comment by raxod502** [comment]
Indeed, it is very puzzling. Unfortunately, I have not figured out how to reliably produce a problem buffer from a fresh Emacs. But once there is one, it seems to be there to stay.

I disabled all minor modes, reset to `fundamental-mode`, called `ad-restore-normality`, and set the `mode-line-format` to `nil`, but the benchmark continued to report 3--4 seconds.

Then I tried

```
(mapc 'unload-feature features)
```

which killed my Emacs. Next time I find a problem buffer, I will see if I can make more progress on figuring out what's going on.

**Comment by dgutov** [comment]
> Next time I find a problem buffer, I will see if I can make more progress on figuring out what's going on.

If you can't, but the problem buffers keep turning up, you can file a bug anyway. Maybe some of the developers will have a better suggestions how to debug.

**Comment by dgutov** [comment]
> I disabled all minor modes, reset to fundamental-mode, called ad-restore-normality, and set the mode-line-format to nil, but the benchmark continued to report 3–4 seconds.

Did `timer-list` have a lot of elements maybe?

**Comment by raxod502** [comment]
OK, so I'm going to admit complete and utter incompetence here. The root cause of this problem was that I accidentally completely disabled GC in my Emacs about a month ago.

I'm closing this issue, because I don't think there's anything sane that could be done in `company-mode` to prevent this "problem".
