### ISSUE TITLE
Memory Leak When Company is Enabled

### ISSUE THREAD

**Issue by Shinmera** [company-mode/company-mode#623]
I've noticed that in recent months Emacs started to massively accumulate memory over a couple of hours of use. It goes up to 10 Gigabytes, despite me not having many buffers open, or doing much out of the ordinary. It also starts to slow down to an absolute crawl, at which point typing a single key takes more than a second to show up. This only happens when I have company enabled.

I'm not sure what to do to track down a more specific cause of the leak. Any pointers for this would be appreciated immensely. Since it takes a rather long while to notice whether the leak is actually really in effect while using Emacs normally, I can't feasibly just test lots of different configurations, though.

Here are the settings from my [dotfiles](https://github.com/Shinmera/.emacs) that are are directly relevant to company:

```elisp
(require 'company)
(require 'slime-company)

(company-quickhelp-mode 1)
(setq company-quickhelp-delay 0.5)
(add-hook 'after-init-hook 'global-company-mode)

(define-key company-active-map (kbd "<up>") 'company-select-previous)
(define-key company-active-map (kbd "<down>") 'company-select-next)
(define-key company-active-map (kbd "\C-n") 'company-select-next)
(define-key company-active-map (kbd "\C-p") 'company-select-previous)
(define-key company-active-map (kbd "\C-d") 'company-show-doc-buffer)
(define-key company-active-map (kbd "M-.") 'company-show-location))
```

I'll be happy to try out a few things if anyone has an idea on how to proceed.

**Comment by dgutov** [comment]
Have you tried a bare configuration? Just `emacs -Q` plus `company-mode`? Does it have a similar effect over a couple of hours?

If you `M-x report-emacs-bug`, you might get some better suggestions toward investigating the leak.

**Comment by Shinmera** [comment]
I haven't tried that, since it makes emacs rather cumbersome to use for my work. I'll see what I can do, though.

**Comment by dgutov** [comment]
This isn't going anywhere, closing.
