### ISSUE TITLE
semantic-idle has been replaced with semantic/idle

### ISSUE THREAD

**Issue by tarsius** [company-mode/company-mode#626]
In Emacs v25.1 `semantic-idle.el` has been replaced with `semantic/idle.el`. The feature provided by that library is `semantic/idle`, but `company-mode` still requires `semantic-idle`.

**Comment by dgutov** [comment]
Which usage do you mean? In `company-semantic-doc-or-summary`?

**Comment by tarsius** [comment]
Uh, I am sorry, I did not notice that you try both names already.
