### ISSUE TITLE
company-mode conflicts with ergoemacs

### ISSUE THREAD

**Issue by alexei28** [company-mode/company-mode#631]
Windows 7 (64 bit)
Emacs ver. 24.5, package "ergoemacs".
I success installed package "company" from Elpa repo by list-package.
In my init.el I add:

`(add-hook 'after-init-hook 'global-company-mode)`

After restart Emacs (comple-mode is enabled) I open any .el file. And when enter some elisp code, e.g. 
`(let`

nothing happend. Not show any complete candidates. Also I add this code in init.el
`(require 'company)
(company-mode t)
(add-hook 'after-init-hook 'global-company-mode)`

but this it alsh not help me.

**Comment by dgutov** [comment]
I'm not sure if we have any conflicts with `ergoemacs`, but try removing (or disabling) it first, and see if that helps.

**Comment by alexei28** [comment]
Yes, you are right. If I uninstall package "ergoemacs" then package "company-mode" success work!

**Comment by dgutov** [comment]
Please report it to ergoemacs, then.

**Comment by alexei28** [comment]
I've already done it.

**Comment by CyberShadow** [comment]
Ergoemacs issue: https://github.com/ergoemacs/ergoemacs-mode/issues/447

Could this and https://github.com/company-mode/company-mode/issues/645 have the same root cause? I see that Ergoemacs also sets `overriding-terminal-local-map`.

**Comment by mattfidler** [comment]
That is true that ergoemacs-mode sets `overriding-terminal-local-map` if it is already set.  It basically looks up the equaivlent emacs keys and trys to remap them to ergoemacs-mode keys.  It shouldn't cause any issues for company mode.  

For me, company-mode and ergoemacs-mode works, by the way.

**Comment by dgutov** [comment]
Indeed, thanks for reminder @CyberShadow.

**Comment by alexei28** [comment]
I solved the problem globally. I  completely refused ErgoEmacs. And use pure Emacs. And no problem with any package (incluse company-mode) . All work fine.

**Comment by mattfidler** [comment]
It is likely that #645 fixed ergoemacs-mode as well.
