### ISSUE TITLE
company-yasnippet stops popup for other completion (e.g. clang)

### ISSUE THREAD

**Issue by oracleyue** [company-mode/company-mode#632]
I found out that once I put `company-yasnippet` in the backends, once it fails (having nothing to complete), it will stop `company` show other completions automatically.
```(add-to-list 'company-backends 'company-yasnippet);```

For example, in cpp file, when I type `std::string str; str.`, it won't show any candidates. Once remove it from the backends list, everything works.
(Well, note that, when adding it in the backends list, it completes yasnippet correctly.)

Currently, my compromised solution is binding it to a different key.

**Comment by dgutov** [comment]
Please read its docstring.

**Comment by oracleyue** [comment]
@dgutov Ha, okay, "shadow" means stopping showing all other candidates, when yas has no completion. All right. I have read it, that's why I bound it to a new key.
Mmm, interesting. I thought it would just show too many meaningless yas "key"s, instead of blocking others. Let me check the codes.
Anyway, obviously I posted an invalid issue. Thanks!

**Comment by dgutov** [comment]
> "shadow" means stopping showing all other candidates

Stopping all backends after it from being used.

Maybe it's not the ideal word here. Please feel free to suggest a better one.
