### ISSUE TITLE
tab-indent-or-complete kills Helm TAB keybind..anyway to fix that?

### ISSUE THREAD

**Issue by zeltak** [company-mode/company-mode#634]
Hi!

i have been using company over the last few weeks and really enjoying it!

one issue i noticed today is that if i assign TAB to the `tab-indent-or-complete` function following the company wiki it kills TAB use in helm (since it tries to complete in helm). 

Anyone know how to workaround this issue?

thx!

Z

**Comment by dgutov** [comment]
> i assign TAB to the tab-indent-or-complete

That would depend on which keymap you assign it in.

> Anyone know how to workaround this issue?

Helm guys might.

**Comment by zeltak** [comment]
> That would depend on which keymap you assign it in.

thx yeah its set for global mode currently

```(global-set-key [tab] 'tab-indent-or-complete)```

ill ask in the helm github site

thx

Z

**Comment by dgutov** [comment]
> thx yeah its set for global mode currently

Don't do that, then. Set it in `company-active-map`.

**Comment by zeltak** [comment]
thx @dgutov appriciate the help

so i tried changing the line to this

```(define-key company-active-map (kbd "tab") 'tab-indent-or-complete)```

it does fix the helm issue yet this dosent know tab complete when im in an org buffer. i do see the company popup but where before tab worked now it does nothing

any clue?

thx

Z

**Comment by dgutov** [comment]
Yes, create a binding for `[tab]` as well. Then please go to an Org mailing list and let them know that you are unhappy about that hassle. They make this worse for everyone.

**Comment by zeltak** [comment]
haha :) ok will do so :)

i did add the [tab] key as well but still cant get it to work. it dosent work in the scratch buffer as well.

current lines

```
(define-key company-active-map (kbd "tab") 'tab-indent-or-complete)
(define-key company-active-map (kbd "[tab]") 'tab-indent-or-complete)
```

thx again!

Z

**Comment by dgutov** [comment]
```
(define-key company-active-map [tab] 'tab-indent-or-complete)
```

Just look at the definition of `company-active-map`.

**Comment by zeltak** [comment]
sorry for being annoying with this yet i cant get it to work :).

ive tried differnt bind methods for the `company-active-map` with no real success. i have tried

```

(with-eval-after-load 'company
  (define-key company-active-map (kbd "tab") #'tab-indent-or-complete)
  (define-key company-active-map (kbd "[tab]") #'tab-indent-or-complete)
)
```

which results in this 

```
 
(keymap (91 keymap (116 keymap (97 keymap (98 keymap (93
 . tab-indent-or-complete))))) (116 keymap (97 keymap (98
 . tab-indent-or-complete))) (19 . company-search-candidates) (23
 . company-show-location) (8 . company-show-doc-buffer) (f1
 . company-show-doc-buffer) (9 . company-complete-common) (tab
 . company-complete-common) (13 . company-complete-selection) (return
 . company-complete-selection) (up-mouse-3 . ignore) (up-mouse-1
 . ignore) (mouse-3 . company-select-mouse) (mouse-1
 . company-complete-mouse) (down-mouse-3 . ignore) (down-mouse-1
 . ignore) (remap keymap (scroll-down-command . company-previous-page)
 (scroll-up-command . company-next-page)) (up
 . company-select-previous-or-abort) (down
 . company-select-next-or-abort) (7 . company-abort) (27 keymap (57
 . company-complete-number) (56 . company-complete-number) (55
 . company-complete-number) (54 . company-complete-number) (53
 . company-complete-number) (52 . company-complete-number) (51
 . company-complete-number) (50 . company-complete-number) (49
 . company-complete-number) (48 . company-complete-number) (19
 . company-filter-candidates) (112 . company-select-previous) (110
 . company-select-next) (27 keymap (27 . company-abort))))
```

i have also tried the 

```(define-key company-active-map [tab] 'tab-indent-or-complete)``` method with same results

thank you for your patience

Z

**Comment by dgutov** [comment]
Have you tried

```lisp
(with-eval-after-load 'company
  (define-key company-active-map (kbd "tab") #'tab-indent-or-complete)
  (define-key company-active-map [tab] #'tab-indent-or-complete)
)
```

?

**Comment by zeltak** [comment]
yes just tried it now with no success, any other things i can try?

**Comment by dgutov** [comment]
Try `(kbd "TAB")`. Uppercase.

**Comment by zeltak** [comment]
hmm that didnt work either

**Comment by dgutov** [comment]
Sorry, I suggested the wrong keymap. And you were using a wrong command. This should work:

```lisp
(with-eval-after-load 'company
  (define-key company-mode-map (kbd "TAB") #'company-indent-or-complete-common)
  (define-key company-mode-map [tab] #'company-indent-or-complete-common)
)
```

**Comment by zeltak** [comment]
hmm that dosent work either :) (btw all of the above codes do fix the helm issue)

also see the helm correspondence that also dosent seem to solve the issue

https://github.com/emacs-helm/helm/issues/1677#issuecomment-275392556

..ill understand if you give up l-) ..sorry to bother with this :))

thx

Z

**Comment by dgutov** [comment]
> hmm that dosent work either :)

It worked for me, locally.

Oh well.

**Comment by dgutov** [comment]
> (btw all of the above codes do fix the helm issue)

Then Thierry is probably off the hook, and you just need to figure out why my last one doesn't work for you.

**Comment by zeltak** [comment]
ok just to update all, i *finally* got it working with this code

```

 (with-eval-after-load 'company
   (define-key company-mode-map (kbd "C-i") #'company-indent-or-complete-common)
 )
```

thx you so much for the help and effort, its much appreciated!

best

Z

**Comment by dgutov** [comment]
Please evaluate:

```lisp
(equal (kbd "TAB") (kbd "C-i"))
```

Does that return t?

**Comment by zeltak** [comment]
yes it does

best

Z

**Comment by dgutov** [comment]
Then

```lisp
(define-key company-mode-map (kbd "TAB") #'company-indent-or-complete-common)
```

must work just as well.
