### ISSUE TITLE
With company-dabbrev-downcase == nil duplicated suggestion.

### ISSUE THREAD

**Issue by gavenkoa** [company-mode/company-mode#635]
With:

    (setq company-dabbrev-downcase nil)
    (setq company-backends '(company-dabbrev))

and words:

    ZzzEmacs  <-- Upper Z/E
    Zzzemacs  <-- Upper Z
    zzzEmacs  <-- Upper E
    zzzemacs

if I typed "zzz" I get duplicated completion:

    zzzEmacs  <-- Upper E
    zzzemacs
    zzzEmacs  <-- Upper E
    zzzemacs

`M-x company-diag`:

    Prefix: "zzz"
    Completions:
      "ZzzEmacs"  <-- Upper Z/E
      "Zzzemacs"  <-- Upper Z
      "zzzEmacs"  <-- Upper E
      "zzzemacs"

Should be an option that control if there is need to match prefix despite case.

Or at least completion shouldn't adjust case for prefix during display and substitution or filter out duplications based on same case in prefix part.

**Comment by dgutov** [comment]
Have you looked at #413?

**Comment by gavenkoa** [comment]
OK, I didn't read the doc for `company-dabbrev-downcase`. It mentioned the:

    (setq company-dabbrev-ignore-case nil)

or any other then `keep-prefix`.
