### ISSUE TITLE
How to tell where the completion candidates come from?

### ISSUE THREAD

**Issue by amosbird** [company-mode/company-mode#636]
Is there a way to display the actual used backend's name after each completion candidate?

**Comment by dgutov** [comment]
It's shown in the mode line.

**Comment by amosbird** [comment]
Hmm, I don't see it. Are there any specific settings to be turned on?

**Comment by dgutov** [comment]
Are you using vanilla Emacs?

**Comment by amosbird** [comment]
no, spacemacs.

**Comment by dgutov** [comment]
OK, then please see 

https://github.com/syl20bnr/spacemacs/#documentation
and
https://github.com/syl20bnr/spacemacs/#getting-help
