### ISSUE TITLE
Complete functions without argument list

### ISSUE THREAD

**Issue by amosbird** [company-mode/company-mode#638]
Sometimes when changing function names, it triggers completion with unwanted argument list. Is there a completion action that ignores such list? i.e,  complete `function foo(i int)` as `foo` instead of `foo(i int)`.

**Comment by dgutov** [comment]
You're probably talking about the `company-clang` backend.

While we could add a separate command to do that (not sure which keys to use, though), how about the expansion code checks whether there is an opening paren right after the currently inserted symbol, and if so, abort argument insertion?

In some languages, like JavaScript, that could lead to false negatives, but not in C or C++, AFAIK.

**Comment by amosbird** [comment]
Well, it's `company-ycmd` I'm using in `golang` and `c++`. I think a separate command is better, and we can leave other heavy lifting stuff to user configurations.

**Comment by dgutov** [comment]
Support we add a command, what binding would you use?

**Comment by dgutov** [comment]
Regarding Go, could my proposal lead to false negatives there? Or do you just want to complete method name without arguments sometimes?

**Comment by amosbird** [comment]
> Suppose we add a command, what binding would you use?

I'm using `Ctrl-L` to complete. I plan to use `Alt-L` to do function name completion.

> Regarding Go, could my proposal lead to false negatives there? Or do you just want to complete method name without arguments sometimes?

sometimes

**Comment by amosbird** [comment]
I did some hacking. It works pretty well :smiley:
```
;TODO: complete stops yas mode
(with-eval-after-load 'company
    (defun ab/company-complete (ofun &rest args)
      (if (string= evil-state "insert")
          (progn
            (save-excursion
              (insert " "))
            (apply ofun args)
            (save-excursion
              (delete-char 1)))
        ;; prevent company pop up in modes other than INSERT
        (company-cancel)
        ))

    (advice-add 'company--perform :around #'ab/company-complete)

    (defun ab/symbol-suffix ()
      (interactive)
      (let ((beg (point))
            (char (char-after)))
        (if (or (= char ?-) (memq (get-char-code-property char 'general-category)
                                  '(Ll Lu Lo Lt Lm Mn Mc Me Nl)))
            (save-excursion
              (forward-symbol 1)
              (buffer-substring beg (point))
              )
          (string char))
        )
      )

    ;; suppose candidates are trimmed without arguments by backend
    ;; or else we need
    ;; (new-candidate
    ;;  (let ((pos (s-index-of "(" candidate)))
    ;;    (if pos (s-left pos candidate)
    ;;      candidate)
    ;;    )
    ;;  )
    (defun ab/company-insert (ofun candidate)
      (let* (
             (suffix (ab/symbol-suffix))
             )
        (if (s-suffix? suffix candidate)
            (delete-region (point) (+ (point) (length suffix)))
          )
        (if (string= (kbd "C-i") (this-command-keys))
            (setq company-ycmd-insert-arguments nil)
          (setq company-ycmd-insert-arguments 't)
          )
        (apply ofun (list candidate))
        )
      )
    (advice-add 'company--insert-candidate :around #'ab/company-insert)
    (define-key company-active-map (kbd "C-i") 'company-complete-selection)
)
```
