### ISSUE TITLE
Trigger completion when backspacing

### ISSUE THREAD

**Issue by amosbird** [company-mode/company-mode#639]
Currently this only works when the completion candidates list is visible. If the list becomes empty after input additional characters, further backspacing will not trigger completion.

**Comment by dgutov** [comment]
> If the list becomes empty after input additional characters

That probably means that completion has been aborted.

Try a different value of `company-require-match` (so it's harder to input a wrong character), or add your backspace command to `company-begin-commands`.

**Comment by amosbird** [comment]
Thanks!

**Comment by asdyjd** [comment]
how to  add your backspace command to 'company-begin-commands'

**Comment by dgutov** [comment]
`C-h k <backspace>` to find out which command it's bound to.

**Comment by cyrus-and** [comment]
@dgutov is there a reason why the suggested solution doesn't work with `backward-kill-word` and `kill-line` or I'm doing something wrong here?

**Comment by dgutov** [comment]
@cyrus-and Same here. Not sure what's the exact reason. Feel free to file a new issue.
