### ISSUE TITLE
How do I make TAB insert the current completion?

### ISSUE THREAD

**Issue by frankie8518** [company-mode/company-mode#640]
*Sorry for don't know how to post an issue correctly and my poor English,
 If there are somewhere goes wrong /can do better, please give me a chance to apologize and fix it next time

I would like to  use TAB to tell company mode's pop menu I want to apply this suggestion
I try for many 4 way of confiquration, and get 1 hint.

way1. from How to Setup emacs irony-mode in Ubuntu-12.04 
[https://gist.github.com/soonhokong/7c2bf6e8b72dbc71c93b](url)
-----> only let me can use tab to activate pop menu when it won't auto pop (when company-idle-delay nil)
```
;; ==========================================
;; (optional) bind TAB for indent-or-complete
;; ==========================================
(defun irony--check-expansion ()
(save-excursion
  (if (looking-at "\\_>") t
    (backward-char 1)
    (if (looking-at "\\.") t
      (backward-char 1)
      (if (looking-at "->") t nil)))))
(defun irony--indent-or-complete ()
"Indent or Complete"
(interactive)
(cond ((and (not (use-region-p))
            (irony--check-expansion))
       (message "complete")
       (company-complete-common))
      (t
       (message "indent")
       (call-interactively 'c-indent-line-or-region))))
(defun irony-mode-keys ()
"Modify keymaps used by `irony-mode'."
(local-set-key (kbd "TAB") 'irony--indent-or-complete)
(local-set-key [tab] 'irony--indent-or-complete))
(add-hook 'c-mode-common-hook 'irony-mode-keys)
```

way2. from emacs wiki
[https://www.emacswiki.org/emacs/CompanyMode](url)
---> just don't work
```
(defun complete-or-indent ()
    (interactive)
    (if (company-manual-begin)
        (company-complete-common)
      (indent-according-to-mode)))
```
or
```
 (defun indent-or-complete ()
    (interactive)
    (if (looking-at "\\_>")
        (company-complete-common)
      (indent-according-to-mode)))
```
way3.from stack exchange
[http://emacs.stackexchange.com/questions/13286/how-can-i-stop-the-enter-key-from-triggering-a-completion-in-company-mode](url)
---> get error when loading init.el  
> Symbol's value as variable is void: keySymbol's value as variable is void: key
```
;;; Prevent suggestions from being triggered automatically. In particular,
  ;;; this makes it so that:
  ;;; - TAB will always complete the current selection.
  ;;; - RET will only complete the current selection if the user has explicitly
  ;;;   interacted with Company.
  ;;; - SPC will never complete the current selection.
  ;;;
  ;;; Based on:
  ;;; - https://github.com/company-mode/company-mode/issues/530#issuecomment-226566961
  ;;; - http://emacs.stackexchange.com/a/13290/12534
  ;;; - http://stackoverflow.com/a/22863701/3538165
  ;;;
  ;;; See also:
  ;;; - http://emacs.stackexchange.com/a/24800/12534
  ;;; - http://emacs.stackexchange.com/q/27459/12534

  ;; <return> is for windowed Emacs; RET is for terminal Emacs
  (dolist (key '("<return>" "RET"))
    ;; Here we are using an advanced feature of define-key that lets
    ;; us pass an "extended menu item" instead of an interactive
    ;; function. Doing this allows RET to regain its usual
    ;; functionality when the user has not explicitly interacted with
    ;; Company.
    (define-key company-active-map (kbd key)
      `(menu-item nil company-complete
                  :filter ,(lambda (cmd)
                             (when (company-explicit-action-p)
                               cmd)))))
  (define-key company-active-map (kbd "TAB") #'company-complete-selection)
  (define-key company-active-map (kbd "SPC") nil)

  ;; Company appears to override the above keymap based on company-auto-complete-chars.
  ;; Turning it off ensures we have full control.
  (setq company-auto-complete-chars nil)
```

way4. from company mode's issue #94
[https://github.com/company-mode/company-mode/issues/94](url)
```
(define-key company-mode-map [remap indent-for-tab-command]
  'company-indent-for-tab-command)

(setq tab-always-indent 'complete)

(defvar completion-at-point-functions-saved nil)

(defun company-indent-for-tab-command (&optional arg)
  (interactive "P")
  (let ((completion-at-point-functions-saved completion-at-point-functions)
        (completion-at-point-functions '(company-complete-common-wrapper)))
    (indent-for-tab-command arg)))

(defun company-complete-common-wrapper ()
  (let ((completion-at-point-functions completion-at-point-functions-saved))
    (company-complete-common)))
```

hint. get from company-mode's issue above
---> but don't know how to apply
Just a note for any future wanderers of the internet that we can now bind **company-indent-for-tab-command** to tab. Should work better than the workaround posted above.

[note]
I use **Irony-mode** and **company-Irony** **company-irony-c-headers**
this is my confiquration part for company-mode from my Completion.el and Irony.el
Completion.el
```

;;********
;; enable
;;********
 (require 'company)
(add-hook 'after-init-hook 'global-company-mode)
;;*******************
;; confiqure company
;;*******************
;; company-idle-delay:company delay until suggestions are shown
;;     (nil will cause completion menu don't pop automatically)
;; company-transformers...: weight by frequency
 
(setq company-idle-delay              0
      company-minimum-prefix-length   2
      company-show-numbers            t
      company-tooltip-limit           20
      company-dabbrev-downcase        nil
      company-transformers '(company-sort-by-occurrence)
      company-dabbrev-other-buffers   t
      )

;;**************************
;; Load as a grouped backend
;;**************************
;; company-irony-c-header : It must be loaded after irony-mode, while the backend should be grouped with company-irony, and before it. (so I try to put company-yasnippet into the group, and finally integrated yasnippet into completion pop menu!!!!!!!)
;; caution!!! company-yasnippet overlap company-mode in global
(eval-after-load 'company
  '(add-to-list
    'company-backends '( company-irony-c-headers company-irony company-yasnippet)))
```
Irony.el
```
;; =============
;; company mode
;; =============
(add-hook 'c++-mode-hook 'company-mode)
(add-hook 'c-mode-hook 'company-mode)
;; replace the `completion-at-point' and `complete-symbol' bindings in
;; irony-mode's buffers by irony-mode's function
(defun my-irony-mode-hook ()
  (define-key irony-mode-map [remap completion-at-point]
    'irony-completion-at-point-async)
  (define-key irony-mode-map [remap complete-symbol]
    'irony-completion-at-point-async))
(add-hook 'irony-mode-hook 'my-irony-mode-hook)
(add-hook 'irony-mode-hook 'irony-cdb-autosetup-compile-options)
;; (optional) adds CC special commands to `company-begin-commands' in order to
;; trigger completion at interesting places, such as after scope operator
;;     std::|
(add-hook 'irony-mode-hook 'company-irony-setup-begin-commands)
```
my emacs confiquration
[https://github.com/frankie8518/Emacs_super_configuration](url)

Is there any good solution or suggestion for Tab to select and apply the options in pop-out menu?

**Comment by dgutov** [comment]
Do you want TAB to apply the current completion, or for Return to stop doing that? Or both?

**Comment by frankie8518** [comment]
If the question means whether I want to use TAB/Return to apply the choosed suggestion on the pop menu, I
prefer that TAB  do this job and Return  can use to insert a newline,i.e. I want both. 
But It's ok for me to just have TAB to apply choosed suggestion on the menu.

**Comment by dgutov** [comment]
> have TAB to apply choosed suggestion on the menu

Then bind it to `company-complete-selection` in `company-active-map`. Do you know how to do that?

**Comment by frankie8518** [comment]
Yes it works great. Thank you very much.
BTW, could I ask how to modify `company-complete-number` in order to type 1~10 to activate it instead of using `M-<digit>`?

**Comment by dgutov** [comment]
No need to change the command, just set up the bindings in the same keymap.

**Comment by frankie8518** [comment]
Got it .Thank you very much

**Comment by frankie8518** [comment]
Got it. Thank you very much.

**Comment by CodeSwimBikeRunner** [comment]
The other story references this one, this story references the other story. What does the configuration look like for the emacs illiterate?

**Comment by rirze** [comment]
> The other story references this one, this story references the other story. What does the configuration look like for the emacs illiterate?

@CodeSwimBikeRunner 
If you're using straight to install and maintain your packages use this:
```lisp
:bind (:map company-active-map ("<tab>" . company-complete-selection))
```

**Comment by driden** [comment]
@rirz

> > The other story references this one, this story references the other story. What does the configuration look like for the emacs illiterate?
> 
> @CodeSwimBikeRunner If you're using straight to install and maintain your packages use this:
> 
> ```lisp
> :bind (:map company-active-map ("<tab>" . company-complete-selection))
> ```

Thanks for this! I've been trying to create the same binding using general.el and just couldn't get it to work. 
This did!

**Comment by yeahai** [comment]
在 Emacs 中
TAB: 这通常指的是物理 Tab 键的按键事件。在 Emacs 的键绑定中，它直接映射到您键盘上的 Tab 键。
<tab>: 这是一个更通用的表示，用于指代产生 Tab 字符的任何键或键组合。这种表示方式的目的是在不同的环境（比如图形界面和命令行界面）中提供一致的行为。
这种区分的存在是因为不同的环境（例如图形界面与终端界面）可能以不同的方式处理键盘输入。例如，在某些终端环境中，物理 Tab 键可能不会被解释为 TAB，而是以其他方式传递。因此，使用 <tab> 可以提供一种更可靠的方式来确保在任何环境下都能捕获到 Tab 键的事件。

ok,我使用这个<tab>更改失败，后面我找了很久，替换为TAB则是可以成功
(with-eval-after-load 'company
  (define-key company-active-map (kbd "TAB") 'company-complete-selection)
  (define-key company-active-map (kbd "<tab>") 'company-complete-selection))
这是我的代码，使用最后一行则是无效。

**Comment by dgutov** [comment]
Yeah, you really have to bind both if something in your environment already does that. E.g. at some point Org used both `TAB` and `<tab>`, but it thankfully stopped doing that.
