### ISSUE TITLE
Support for remote files via TRAMP for the gtags backend

### ISSUE THREAD

**Issue by jeberger** [company-mode/company-mode#642]
Issue #462 added support for remote files in the clang backend. Can something similar be done for the gtags backend?

Looks like replacing `call-process` with `process-file` on line 69 does the trick.

**Comment by dgutov** [comment]
Done!

**Comment by jeberger** [comment]
The fix only works if the value of `company-gtags-executable` is the same for local and remote buffers. I'm not sure of the best way to have different values. Currently I'm using this modified function:
```lisp
(defun company-gtags--fetch-tags (prefix)
  ;; Remember the local value of company-gtags-executable
  (let ((gtags-executable company-gtags-executable))
    (with-temp-buffer
      (let (tags)
        (when (= 0 (process-file gtags-executable nil
                                 ;; "-T" goes through all the tag files listed in GTAGSLIBPATH
                                 (list (current-buffer) nil) nil "-xGqT" (concat "^" prefix)))
          (goto-char (point-min))
          (cl-loop while
                   (re-search-forward (concat
                                       "^"
                                       "\\([^ ]*\\)" ;; completion
                                       "[ \t]+\\([[:digit:]]+\\)" ;; linum
                                       "[ \t]+\\([^ \t]+\\)" ;; file
                                       "[ \t]+\\(.*\\)" ;; definition
                                       "$"
                                       ) nil t)
                   collect
                   (propertize (match-string 1)
                               'meta (match-string 4)
                               'location (cons (expand-file-name (match-string 3))
                                               (string-to-number (match-string 2)))
                               )))))))

```

With the following snippet to set the correct value as a local variable for remote files:
```lisp
(add-hook
  'find-file-hook
  (lambda ()
    (when (file-remote-p default-directory)
      (set (make-local-variable 'company-gtags-executable) "global"))))
```

The problem is that simply setting a local value for `company-gtags-executable` in tramp buffers does not work because `company-gtags--fetch-tags` creates a temp buffer, which takes the global value. Hence the `let` binding to remember the local value before switching to the temp buffer.

**Comment by dgutov** [comment]
Does you have its executable with different names locally and remotely?

**Comment by dgutov** [comment]
Michael described a solution in #462 which should work in Emacs 26. Not sure how we'd use it while retaining support for previous versions, though.

In the meantime, you should probably just advise `company-gtags--fetch-tags`, and let-bind `company-gtags-executable` globablly to an appropriate value in there.

**Comment by jeberger** [comment]
> In the meantime, you should probably just advise `company-gtags--fetch-tags`, and let-bind `company-gtags-executable` globally to an appropriate value in there.

That's more or less what I'm doing, except that:
- I'm making `company-gtags-executable` into a buffer-local variable,
- and I'm let-binding `gtags-executable` and using that in my modified `company-gtags--fetch-tags`, because when I tried let-binding `company-gtags-executable` in an advice the call to `with-temp-buffer` restored the global value.

**Comment by dgutov** [comment]
> when I tried let-binding company-gtags-executable in an advice the call to with-temp-buffer restored the global value

That seems unlikely. let-binding does not create a local value. Try evaluating these:

```el
(defvar a 1)

(let ((a 2))
  (with-temp-buffer
    a))
```

**Comment by jeberger** [comment]
I meant that I used the `find-file-hook` I mentioned earlier to create a local value, then I tried to use the let-binding to put the local value in the global one for the call to `company-gtags--fetch-tags`:

```el
(add-hook
  'find-file-hook
  (lambda ()
    (when (file-remote-p default-directory)
      (set (make-local-variable 'company-gtags-executable) "global"))))

(defun jmb/company-gtags--fetch-tags (fun &rest r)
  (let ((company-gtags-executable company-gtags-executable))
       (apply fun r)))

(advice-add #'company-gtags--fetch-tags
            :around
            #'jmb/company-gtags--fetch-tags)
```

And that didn't work because apparently the let-binding worked on the local value, and `with-temp-buffer` restored the global one.

Note that:
- The modified `company-gtags--fetch-tags` I posted earlier works for me until company-gtags supports my use case.
- I think the right way to go is to allow `company-gtags-executable` to work as a local variable. I'm just not sure if the changes I made to `company-gtags--fetch-tags` are the best way to do it, or if there is some better way to preserve local values in a call to `with-temp-buffer`.

**Comment by dgutov** [comment]
> I meant that I used the find-file-hook I mentioned earlier to create a local value

I'm saying that I don't think this is necessary for your case. You might as well call `file-remote-p` every time, it's not slow.

**Comment by jeberger** [comment]
True, that works too. I initially thought of using `tramp-find-executable` (to be consistent with the default value for `company-gtags-executable`), which would have been slower. But for my particular use case, I can hardcode the value into the advice.

**Comment by dgutov** [comment]
> I initially thought of using tramp-find-executable

In that case, you could set a different (new) variable to a local value in `find-file-hook`, and in the advice, bind `company-gtags-executable` to that value.
