### ISSUE TITLE
`company-complete` with `company-clang` not working inside functions

### ISSUE THREAD

**Issue by christopherdumas** [company-mode/company-mode#644]
I'm running Emacs 25.1, (from the emacsformacosx.com website). I set up my emacs using the instructions from http://tuhdo.github.io/c-ide.html, and it works great except for one thing: Inside a function, company-clang uses only default completions (system variables, global macros, etc.), and namespace-level completions for things like the standard library. Meanwhile, when outside anything, it completes intelligently for my project too. For example:

If my cursor is the `-!-`:
```cpp
// Constructor for the Player class, FYI
character::Player::Player(races::Race r) : race(r), inventory(r.starting_inventory)
{
    ...
    utils::-!-
}
...
```
then it will give me random, unintelligent completions. BTW, `utils` is a namespace that I define in `../lib/utils.hpp` and include just above this code snippet.

However, when it is here (my cursor is again `-!-`):
```cpp
// Constructor for the Player class, FYI
character::Player::Player(races::Race r) : race(r), inventory(r.starting_inventory)
{
    ...
}
utils::-!-
...
```
It gives me intelligent completions complete with argument types. 

In addition, both
```cpp
// Constructor for the Player class, FYI
character::Player::Player(races::Race r) : race(r), inventory(r.starting_inventory)
{
    ...
}
std::-!-
...
```
and
```cpp
// Constructor for the Player class, FYI
character::Player::Player(races::Race r) : race(r), inventory(r.starting_inventory)
{
    ...
    std::-!-
}
...
```
give intelligent autocompletion suggestions.

Here is my .dir-locals.el if that helps:
```
((nil . ((company-clang-arguments . ("-I/Users/christopherdumas/AlchemySphere/cpp/include"
                                     "-I/Users/christopherdumas/AlchemySphere/cpp/lib"
                                     "-L/Users/christopherdumas/AlchemySphere/cpp/lib"
                                     "-I/Users/christopherdumas/AlchemySphere/cpp/generators"
                                     "-I/Users/christopherdumas/AlchemySphere/cpp/objects"
                                     "-I/Users/christopherdumas/AlchemySphere/cpp/nouns")))))
```

**Comment by dgutov** [comment]
@christopherdumas Hi!

Do you have a small example project for me to experiment in, where this problem can be reproduced?

**Comment by christopherdumas** [comment]
Here's the project I'm using: https://github.com/christopherdumas/LMS

**Comment by christopherdumas** [comment]
I still have not figured this out after intensive research. I'm having to deal with no contextual autocompletion, which is fine, but it would be nice to have it working.

**Comment by dgutov** [comment]
> Here's the project I'm using: https://github.com/christopherdumas/LMS

Are you sure? This one seems to be written entirely in Python, not C++.

**Comment by christopherdumas** [comment]
Sorry! I fixed the problem. Also, look at the cpp-port branch of my project. That's where my c++ is.

**Comment by dgutov** [comment]
Great!

> I fixed the problem.

Do you think the issue you were having might be of interest to other users?

**Comment by christopherdumas** [comment]
Not really. I realized that I needed to restart Emacs after setting up and starting company for the first time.

**Comment by dgutov** [comment]
All right. I'm not sure how a restart is supposed to help exactly, but maybe something in your configuration needs that.

**Comment by christopherdumas** [comment]
Probably.
