### ISSUE TITLE
`company-mode` stops working with non-nil `overriding-local-terminal-map`

### ISSUE THREAD

**Issue by CyberShadow** [company-mode/company-mode#645]
With `emacs -Q`, in the scratch buffer:

```elisp
(add-to-list 'load-path "~/.emacs.d/elpa/company-20170218.1913/")
(require 'company)
(global-company-mode)

;; Observe that company-mode now works as expected

(setq overriding-terminal-local-map (make-sparse-keymap))

;; company-mode's auto-completion and company-complete both stop working
```

Note that `overriding-terminal-local-map` is `nil` before we set it to an empty keymap, so it's not like we're clobbering any company keybinds.

**Comment by dgutov** [comment]
Thanks for the report.

@nschum, do you recall why ddf7cb15 added a check against `overriding-terminal-local-map` in `company--should-complete`? Was it intended to screen against a particular kind of buffers?

Simply removing it seems to work okay.

**Comment by dgutov** [comment]
All right, let's try it.
