### ISSUE TITLE
Error in python-inferior-mode 

### ISSUE THREAD

**Issue by muahah** [company-mode/company-mode#646]
## Issue
Company throws an error when using completion in python-inferior-mode if `company-sort-by-occurences` is activated.

## Test case
In `python-inferior-mode` :
```python
toto = "toto"
>>> toto.split()   # here `company-complete-common` works
['toto']
>>> toto.spl       # here it throws an error
```

## Source
`company-capf` use `python-shell-completion-at-point` for `python-inferior-mode`. `python-shell-completion-at-point` does not allow completion elsewhere than in the prompt (because of the use of `python-util-comint-last-prompt`, which return the position of the last prompt).
Or, `company-sort-by-occurence` tries to use completion on the same symbol elsewhere in the shell buffer, provoking an error in `python-shel-completion-at-point` : 
```
Debugger entered--Lisp error: (error "Invalid search bound (wrong side of point)")
  re-search-backward("[[:space:]]\\|[([{]\\|[])}]\\|\\(?:[^\"'\\]\\|\\=\\|\\(?:[^\\]\\|\\=\\)\\\\\\(?:\\\\\\\\\\)*[\"']\\)\\(?:\\\\\\\\\\)*\\(\\(?:\"\"\"\\|'''\\|[\"']\\)\\)" #<marker at 1577 in *Python[test.py]*> t 1)
  python-shell-completion-at-point()
  completion--capf-wrapper(python-shell-completion-at-point optimist)
  run-hook-wrapped(completion--capf-wrapper python-shell-completion-at-point optimist)
  company--capf-data-real()
  company--capf-data()
  company-capf(prefix)
  apply(company-capf prefix)
  company-call-backend-raw(prefix)
  apply(company-call-backend-raw prefix)
  company--force-sync(company-call-backend-raw (prefix) company-capf)
  company-call-backend(prefix)
  company--occurrence-predicate()
cl-delete-if()
  company-sort-by-occurrence((#("toto.split(" 0 8 (face (completions-common-part)) 8 9 (face (completions-first-difference))) #("toto.splitlines(" 0 8 (face (completions-common-part)) 8 9 (face (completions-first-difference)))))
  company--transform-candidates((#("toto.split(" 0 8 (face (completions-common-part)) 8 9 (face (completions-first-difference))) #("toto.splitlines(" 0 8 (face (completions-common-part)) 8 9 (face (completions-first-difference)))))
  company--postprocess-candidates((#("toto.split(" 0 8 (face (completions-common-part)) 8 9 (face (completions-first-difference))) #("toto.splitlines(" 0 8 (face (completions-common-part)) 8 9 (face (completions-first-difference)))))
  company-calculate-candidates("toto.spl")
  company--begin-new()
  company--perform()
  company-auto-begin()
  company-manual-begin()
  company-complete-common()
  funcall-interactively(company-complete-common)
  call-interactively(company-complete-common nil nil)
  command-execute(company-complete-common)
```

## company-diag
Emacs 25.1.1 (x86_64-unknown-linux-gnu) of 2017-02-07 on arojas
Company 0.9.2

company-backends: ((company-auctex-macros company-auctex-symbols company-auctex-environments)
 company-auctex-bibs company-auctex-labels company-bbdb company-nxml company-css company-eclim company-semantic company-clang company-xcode company-cmake company-capf company-files
 (company-dabbrev-code company-gtags company-etags company-keywords)
 company-oddmuse company-dabbrev)

Used backend: company-capf
Prefix: ""
Completions: none

## Possible workaround
For the moment, I overwrote `python-util-comint-last-prompt` to return the current line beginning position.

**Comment by dgutov** [comment]
It's the same as #549. Thanks.
