### ISSUE TITLE
Company-mode prints tons of jibberish when accidentally completing without any prefix in GDB

### ISSUE THREAD

**Issue by dmalyuta** [company-mode/company-mode#648]
Emacs 24.5.1
Ubuntu 14.04

When I am in gdb-many-windows mode, I type into the gdb comint console:
```
(gdb) print foo(<CURSOR_LOCATION>)
```
where <CURSOR_LOCATION> is where I place the cursor. I accidentally hit Shift+Space (my keybinding for `company-complete`) at this cursor location (where there is no prefix to use for finding completion candidates) and Emacs suddenly becomes irresponsive, because company mode is going through all completion candidates at this point. If I hit Ctrl+G, instead of cancelling the completion company begins to print what I suppose are the completion candidates it is looking for - there are TONS (and most of which that I have no idea where they came from) and it takes about 2 minutes for company to finish printing these candidates. Here's a sample:
```
<MORE BEFORE>
print foo(vtable for Iex::EnobufsExc
print foo(vtable for Iex::EnodataExc
print foo(vtable for Iex::EnodevExc
print foo(vtable for Iex::EnoentExc
print foo(vtable for Iex::EnoexecExc
print foo(vtable for Iex::EnolckExc
print foo(vtable for Iex::EnolinkExc
print foo(vtable for Iex::EnomemExc
print foo(vtable for Iex::EnomsgExc
print foo(vtable for Iex::EnonetExc
print foo(vtable for Iex::EnopkgExc
print foo(vtable for Iex::EnoprotooptExc
print foo(vtable for Iex::EnospcExc
print foo(vtable for Iex::EnosrExc
print foo(vtable for Iex::EnostrExc
print foo(vtable for Iex::EnosysExc
print foo(vtable for Iex::EnotblkExc
print foo(vtable for Iex::EnotconnExc
print foo(vtable for Iex::EnotdirExc
print foo(vtable for Iex::EnotemptyExc
print foo(vtable for Iex::EnotnamExc
print foo(vtable for Iex::EnotsockExc
print foo(vtable for Iex::EnottyExc
print foo(vtable for Iex::EnotuniqExc
print foo(vtable for Iex::EnxioExc
print foo(vtable for Iex::EopnotsuppExc
print foo(vtable for Iex::EoverflowExc
print foo(vtable for Iex::EpermExc
print foo(vtable for Iex::EpfnosupportExc
print foo(vtable for Iex::EpipeExc
print foo(vtable for Iex::EprotoExc
print foo(vtable for Iex::EprotonosupportExc
print foo(vtable for Iex::EprototypeExc
print foo(vtable for Iex::ErangeExc
print foo(vtable for Iex::EremchgExc
print foo(vtable for Iex::EremoteExc
print foo(vtable for Iex::EremoteioExc
print foo(vtable for Iex::ErestartExc
print foo(vtable for Iex::ErofsExc
print foo(vtable for Iex::ErrnoExc
print foo(vtable for Iex::EshutdownExc
print foo(vtable for Iex::EsocktnosupportExc
print foo(vtable for Iex::EspipeExc
print foo(vtable for Iex::EsrchExc
print foo(vtable for Iex::EsrmntExc
print foo(vtable for Iex::EstaleExc
print foo(vtable for Iex::EstrpipeExc
print foo(vtable for Iex::EtimeExc
print foo(vtable for Iex::EtimedoutExc
print foo(vtable for Iex::EtoomanyrefsExc
print foo(vtable for Iex::EtxtbsyExc
print foo(vtable for Iex::EucleanExc
print foo(vtable for Iex::EunatchExc
print foo(vtable for Iex::EusersExc
print foo(vtable for Iex::ExdevExc
print foo(vtable for Iex::ExfullExc
print foo(vtable for Iex::InputExc
print foo(vtable for Iex::IoExc
print foo(vtable for Iex::LogicExc
print foo(vtable for Iex::MathExc
print foo(vtable for Iex::TypeExc
print foo(vtable for IlmThread::Mutex
print foo(vtable for IlmThread::Semaphore
print foo(vtable for IlmThread::Task
<MORE AFTER>
```

My `init.el` can be found [here](https://github.com/dmalyuta/dotfiles/blob/master/.emacs.d/init.el) and company-related stuff starts at [line 152](https://github.com/dmalyuta/dotfiles/blob/master/.emacs.d/init.el#L152):
```
(use-package company
    ;; complete anything
    :ensure t
    :bind
    (("<S-SPC>" . company-complete)
     ("M-n" . company-select-next)
     ("M-p" . company-select-previous))
    :init
    ;;(add-hook 'after-init-hook 'global-company-mode)
    (add-hook 'c-mode-common-hook 'company-mode)
    (add-hook 'emacs-lisp-mode-hook 'company-mode)
    (add-hook 'comint-mode-hook 'company-mode)
    ;;(add-hook 'sh-mode-hook 'company-mode)
    ;;(add-hook 'python-mode-hook 'company-mode)
    :config
    ;; set timeout to 10 seconds
    (setq company-async-timeout 10)
    ;; Cancel selections by typing non-mathcing characters
    (setq company-require-match 'never)
    ;; Minimum length of word to start completion
    (setq company-minimum-prefix-length 10)
    ;; Autocomplete only when I explicitly mean to
    (setq company-auto-complete nil)
    (set 'company-idle-delay 1)
    (setq company-auto-select-first-candidate nil)
    )
```
In the gdb comint console, only raw company-mode is enabled (so I guess the presence of company-irony is irrelevant for my problem).

I do not know why I am unable to cancel the accidental `company-complete` call with Ctrl+G?

## Desired behavior

I am able to abort the accidental call to `company-complete`.

**Comment by dgutov** [comment]
What happens if you disable `company-mode` and press `C-M-i` at the target position instead?

**Comment by dmalyuta** [comment]
Exactly the same thing happens! I guess you know what the problem is then?

**Comment by dgutov** [comment]
Sorry, I only know where to send you in this case. :)

The way to go is to `M-x report-emacs-bug`. Completion behaving like this is a bug in Emacs.

**Comment by dgutov** [comment]
But let's clarify a couple of things: if you press `C-M-i`, completion takes a long time as well, then you press `C-g`, and you see all this output?

If GDB really takes this much time to generate the completions, there might be little that can be done. Worst case, we can make sure that `C-g` in that context doesn't do anything until GDB has finished returning the completions.

**Comment by dgutov** [comment]
Since the completions look weird, it might even be a bug in GDB. But let's report it to Emacs first, most core developers should know whether to redirect you.

**Comment by dmalyuta** [comment]
Ok, so it is nothing related to company mode? Because `C-M-i` for me is calling `complete-symbol` while `S-<SPC>` is calling `company-complete` - so why then does a problem with `complete-symbol` (which I don't call with `S-<SPC>`) appear when I call `company-complete`?

To your second post: in the Emacs gdb comint shell I connect to a remote application (`target remote`) and when I run the program, break and do the actions in my original post, the behavior is identical when doing `C-M-i` (with `company` disabled or enabled, either way) as when doing `M-x company-complete` - Emacs freezes and nothing happens for 2 minutes while the completions are being parsed, or I press C-g and it all gets dumped into the comint shell. Note that when I press `C-M-i` just at the beginning of the gdb prompt (i.e. `(gdb) <CURSOR_LOCATION>`) then only 100 candidate completions show for the gdb actions and it is really fast.

**Comment by dmalyuta** [comment]
Here I found what I think is an [identical issue](https://lists.gnu.org/archive/html/bug-gnu-emacs/2010-01/msg00609.html). What do you make of it?

**Comment by dgutov** [comment]
> Ok, so it is nothing related to company mode?

Indeed.

> why then does a problem with complete-symbol (which I don't call with S-<SPC>) appear when I call company-complete?

Because reimplementing completion for every situation inside Company is untenable, and we have learned to delegate to the generic completion code. Which is almost always a good thing.

> nothing happens for 2 minutes while the completions are being parsed

This is the core of the problem. Either it's a bug in GDB (which would need to be reported, then probably worked around anyway), or in the parsing code, or something else that could be improved in Emacs. I'm not well-equipped to really say which it is.

> Note that when I press C-M-i just at the beginning of the gdb prompt (i.e. (gdb) <CURSOR_LOCATION>) then only 100 candidate completions show for the gdb actions and it is really fast.

That might hint at this being a GDB bug. But, again, I can be wrong.

> Here I found what I think is an identical issue.

Have you tried GDB 6.3.50 or newer? [bug#5404](https://debbugs.gnu.org/cgi/bugreport.cgi?bug=5404) is marked as fixed, so it's either fixed in GDB that's newer than what you have, or you can file a new bug.

**Comment by dmalyuta** [comment]
I have GDB 7.7.1. Upgrading to 7.12.1 solves the issue, because the new version works around this exact problem by defining a `max-completions` (customizable) cap on how many completions GDB outputs. See [here](http://stackoverflow.com/questions/20933946/gdb-freezing-when-print-variables-with-tab-completion). Thanks for being quick to help.
