### ISSUE TITLE
autoload company-other-backend?

### ISSUE THREAD

**Issue by Sarcasm** [company-mode/company-mode#651]
I was wondering if it would make sense to add an autoload for company-other-backend?
I think some people may want to bind it in their config, and the autoload is necessary to make the symbol known without loading company-mode, no?

**Comment by dgutov** [comment]
But when do you need it known, though?

By the time you'll use that key binding, `company-mode` will have to be enabled, and so `company` will have to be loaded.

**Comment by Sarcasm** [comment]
Right, I kind of thought about it...Thanks for making me think harder.
