### ISSUE TITLE
Truncating 'meta strings

### ISSUE THREAD

**Issue by cpitclaudel** [company-mode/company-mode#652]
Hi,

Emacs has a variable `message-truncate-lines` that prevents calls to `message` from growing the minibuffer.  Should there be a way to bind it around company's call to `message` when displaying `meta` annotations?

The rationale is that it isn't always easy to truncate a meta string to make it fit exactly: for example, if it contains symbols like `∀` or `⟶`, truncating by length isn't enough.  Setting message-truncate-lines is much simpler.

There are a few ways to do this:

* Add a backend command
* Let meta return a cons instead of a single string
* Add a customizable variable:

```elisp
(defcustom company-meta-truncate nil
  "When non-nil, ensure that 'meta annotations never grow the minibuffer."
  :type 'boolean
  :package-version '(company . "0.9.3"))

(defun company-echo-show (&optional getter)
  (when getter
    (setq company-echo-last-msg (funcall getter)))
  (let ((message-log-max nil))
    (if company-echo-last-msg
        (let ((message-truncate-lines company-meta-truncate))
          (message "%s" company-echo-last-msg))
      (message ""))))
```

I have a small preference for the second solution.  What do you think?

**Comment by dgutov** [comment]
1. Backend command to delegate echoing? Sounds complicated, there are basically only two ways of doing it.

2. Why cons? Like you said, there's no good way to truncate the string before displaying.

Option 3 looks best to me, it will even allow the backends to ditch some relevant code. Any arguments against?

**Comment by cpitclaudel** [comment]
2. I was thinking of something returning something like `("this long string should really not resize the minibuffer" . t)` instead of just `"this long string should really not resize the minibuffer"`.  I guess the difference between 2 and 3 is whether we view this as a user option or as a backend option. 

It makes a bit more sense to me as a backend option, since typically the truncation is already being done by the backends.  But in fact the two could coexist (that is, we could have both a customizable variable, and a way for backends to signal truncation, just like we have a minimum prefix length and a way for backends to bypass it).

**Comment by dgutov** [comment]
> It makes a bit more sense to me as a backend option, since typically the truncation is already being done by the backends.

I don't see how "double truncation" would hurt. Not performance-wise, right?

> that is, we could have both a customizable variable, and a way for backends to signal truncation

Would we really need a way for a backend to say "no, actually disable truncation", like we have with with `require-match`?

**Comment by cpitclaudel** [comment]
> > It makes a bit more sense to me as a backend option, since typically the truncation is already being done by the backends.

> I don't see how "double truncation" would hurt. Not performance-wise, right?

Sorry, I wasn't clear.  I meant that, in the current state of company-mode, each backend decides whether the `meta` string should be truncated.  Since we're considering extending company with the capability to display truncated string, it seems logical to let backends opt into this feature (and frop their own code that achieved roughly the same result).

Another way to clarify: as a backend author, I might never want the minibuffer to expand.  If there's just a defcustom, I can't do that.

>> that is, we could have both a customizable variable, and a way for backends to signal truncation

> Would we really need a way for a backend to say "no, actually disable truncation", like we have with with require-match?

I'm not sure :) (Just to clarify, though, I was suggesting that the default be to obey the user option (or if we don't add one to not truncate) and that backends be allowed to request truncation, even if the option isn't set).

**Comment by dgutov** [comment]
I think we'll just do it the simpler way: have the user option which defaults to `t` (which means truncate). If the user chooses to change it (not sure why), they can pick the affected backends by setting the new value locally in some major (or minor) mode's hook.

We can add backend-based dispatch later, if so desired.

But AFAIR `meta` was never supposed to be multiline (minibuffer jumping is just too annoying).

**Comment by cpitclaudel** [comment]
> I think we'll just do it the simpler way: have the user option which defaults to t (which means truncate). If the user chooses to change it (not sure why), they can pick the affected backends by setting the new value locally in some major (or minor) mode's hook.

Ok. Want a patch? :)

**Comment by dgutov** [comment]
Sure!
