### ISSUE TITLE
Quickly delete unwanted arguments

### ISSUE THREAD

**Issue by amosbird** [company-mode/company-mode#657]
As mentioned here abingham/emacs-ycmd#408 , how can I quickly delete unwanted arguments that auto completed by some backends.
 A completion of python's print function looks like this,
```
    print(value, ..., sep=' ', end='\n', file=sys.stdout, flush=False)
```
afaik, yasnippet supports `ctrl-d` to delete them one by one.

**Comment by dgutov** [comment]
Would you expect the comma and space following the deleted argument to be deleted as well?

That part would be the least trivial.

**Comment by amosbird** [comment]
Yeah, something like this will do,
```
print(value, |..., sep=' ', end='\n', file=sys.stdout, flush=False)

print(value, |sep=' ', end='\n', file=sys.stdout, flush=False)

print(value, |end='\n', file=sys.stdout, flush=False)

print(value, |file=sys.stdout, flush=False)

print(value, |flush=False)

print(value)|
```
The last one is a bit different IMO.

**Comment by dgutov** [comment]
> afaik, yasnippet supports ctrl-d to delete them one by one

Do you have an example of a package that uses Yasnippet this way? Or of a snippet that works like this, with function arguments.

**Comment by amosbird** [comment]
I'm not aware of a package using this. Here is how Yasnippet does,
```
(defun yas-skip-and-clear-or-delete-char (&optional field)
  "Clears unmodified field if at field start, skips to next tab.

Otherwise deletes a character normally by calling `delete-char'."
  (interactive)
  (let ((field (or field
                   (and yas--active-field-overlay
                        (overlay-buffer yas--active-field-overlay)
                        (overlay-get yas--active-field-overlay 'yas--field)))))
    (cond ((and field
                (not (yas--field-modified-p field))
                (eq (point) (marker-position (yas--field-start field))))
           (yas--skip-and-clear field)
           (yas-next-field 1))
          (t
           (call-interactively 'delete-char)))))

```

**Comment by dgutov** [comment]
Thanks, the code is nice, but it doesn't tell me enough. In particular, how would one construct a Yasnippet template for function arguments, for it to behave like you're asking?

**Comment by amosbird** [comment]
It works for every snippet like this one,
```
# -*- mode: snippet -*-
# name: function
# key: func
# --
function $1 -d "$2"
  $0
end
```

**Comment by dgutov** [comment]
Does `C-d` delete the comma in this case?

**Comment by dgutov** [comment]
> Well, I'm not sure how to handle the comma easily.

Never mind, then. The commas are the reason for my question, how to extend the `company-template` to handle them best.

**Comment by ptrv** [comment]
Maybe #660 could be a starting point for this feature? The patch is done really quickly so I did not check whether it is robust enough but could be the starting point for discussion. It implements the feature by just extending `company-template-forward-field` with the ability to delete the template, because we have all information for the region to delete there. We delete all character which we would jump over when using `TAB`. In the case of the last template arguments we just delete the bounds of the last overlay.

**Comment by dgutov** [comment]
@amosbird Please try it out.

**Comment by amosbird** [comment]
Great! Thanks.
