### ISSUE TITLE
clang failed with error 1

### ISSUE THREAD

**Issue by physnchips** [company-mode/company-mode#659]
I recently installed Ubuntu 16.04, and previously had an emacs setup using company that was working with the same code on 14.04, so I don't know if it's a new install issue or something else that worked for my set in Ubuntu 14.04 that isn't working now (note: I did fresh install, not an upgrade). My guess is a path issue, but I'm not so familiar with lisp or company mode that I really know where to look. Also, big kudos to everyone that the previous install worked so seamlessly.

Anyway, on to the error: if I try to complete a variable my own class (after typing .) or even something from the std library (after typing the second semicolon in std::) I get the error message
clang failed with error 1:
/usr/bin/clang -fsyntax-only -Xclang -code-completion-macros -x c++ -Xclang -code-completion-at=-:43:1

Some maybe helpful info is:
user@user:~$ which clang
/usr/bin.clang

user@user:~$ clang --version
clang
clang version 3.8.0-2ubuntu4 (tags/RELEASE_380/final)
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin

user@user:~$ dpkg -S /usr/bin/clang
clang: /usr/bin/clang

user@user:~$ dpkg -S /usr/lib/llvm-3.8/bin/clang
clang-3.8: /usr/lib/llvm-3.8/bin/clang

**Comment by dgutov** [comment]
You probably need to set up `company-clang-arguments` for your project.

But look in the buffer `*clang-error*`.

**Comment by physnchips** [comment]
Great, that solves the class completion -- my .dir-locals.el from old linux project got lost in transfer and being newbie I forgot I had ever needed arguments. Also, I don't get an error for the std:: completion anymore but it seems that classes from std (such as vector, map, etc.) don't show up in completion box -- not sure if they ever did.
