### ISSUE TITLE
Non-prefix completion wrong candidate list

### ISSUE THREAD

**Issue by SuJiKiNen** [company-mode/company-mode#661]
I have written a simple backend,that completion by prefix length,3 character return one list,longer than 3 charcter return the other one,but when type 4 character,only the first perform is right,I have set (no-cache t),so  does anything I missed?
my code can find [here](https://github.com/SuJiKiNen/company-3shots-expand).
here is a result preview.
![test](https://cloud.githubusercontent.com/assets/6788956/24888766/2290f594-1e98-11e7-9d51-651c69cd7160.gif)

**Comment by dgutov** [comment]
See #590.
