### ISSUE TITLE
completion align error

### ISSUE THREAD

**Issue by YuSuu** [company-mode/company-mode#662]
```
Emacs 25.1.1 (x86_64-unknown-linux-gnu) of 2017-02-08 on arojas
Company 0.9.3

company-backends: (company-jedi company-anaconda elpy-company-backend company-bbdb company-nxml company-css company-eclim company-clang company-xcode company-cmake company-files
	      (company-dabbrev-code company-gtags company-etags company-keywords)
	      company-oddmuse company-dabbrev)

Used backend: company-jedi
Prefix: ""
```
![one](https://cloud.githubusercontent.com/assets/16498050/25056084/35e40aba-2199-11e7-8403-8f47e605d0d8.png)
![two](https://cloud.githubusercontent.com/assets/16498050/25056085/36b10ed4-2199-11e7-91b7-dbe2f98e0b11.png)

ehh..actually , i can also meet this kind align error at some other places,
is it a bug or my setting prorblem?

**Comment by dgutov** [comment]
It's your fonts. The chinese characters are not the same width as the latin ones.

**Comment by YuSuu** [comment]
@dgutov thanks for your instant reply!
