### ISSUE TITLE
no path autocompletion after  equal sign "=" 

### ISSUE THREAD

**Issue by vakosel** [company-mode/company-mode#665]
I am trying to configure a i3blocks.conf file  which uses scripts to show widgets in the status bar in i3 wm.
The command that is doing that is  :    command=/path/to/script.
So i opened the .i3blocks.conf file  and tried to edit it . No autocompletion immediately after  equial = sign.
.When i leave a space between equal sign and the path, ie the ~ or / ,  autocompletion of the path is working . 
To clear this out
command=/auto/complete/path/NOT WORKING (no space)
command= /auto/complete/path/WORKING  but then conf file is not working ! lol  (space)
A very nice guy quicknir in spacemacs gitter reproduced that . Major mode was Conf(unix)

Thanks in advance

**Comment by dgutov** [comment]
Indeed, that's how `company-files--regexps` has worked until now.

I've made it allow this specific case. If any significant false positives arise, however, we'll have to introduce a variable, for each major mode (or probably users) to provide a buffer-local value.
