### ISSUE TITLE
Moving code from auto-complete to company

### ISSUE THREAD

**Issue by CeleritasCelery** [company-mode/company-mode#666]
I have been using [plsense](https://github.com/aki2o/emacs-plsense) for Perl completion which uses auto-complete.el as a completion framework. I want to move it to company-mode. Are there any guides that show how to move code from one to the other or show a comparison between the two?

**Comment by Silex** [comment]
https://github.com/company-mode/company-mode/wiki/Switching-from-AC

:wink:

**Comment by dgutov** [comment]
@Silex That doesn't describe how to migrate from one backend API to the other, though.

@CeleritasCelery Check this out: https://gist.github.com/dgutov/5225670

To be clear, I don't recommend using this code, just reading it. It's better to write the backend manually.

Also see the `company-backends` docstring.

**Comment by mattiasb** [comment]
If possible, I'd try to convert the code to use `completion-at-point-functions`, that way Company will work out of the box, plus you get support for other completion alternatives like the built-in `completion-at-point` and [ido-at-point](katspaugh/ido-at-point).

**Comment by dgutov** [comment]
Indeed, that's a good option. As long as you don't need asynchronous invocations or non-prefix completion (or are fine with using `company-flx` for the latter).

**Comment by CeleritasCelery** [comment]
Do `completion-at-point-functions` have to explicitly triggered?

**Comment by dgutov** [comment]
`company-capf` handles interfacing with them.
