### ISSUE TITLE
company-mode does not start auto-completion when inside of string

### ISSUE THREAD

**Issue by stardiviner** [company-mode/company-mode#669]
Here is an org-mode babel src block:

 #+BEGIN_SRC clojure
 ;;; the | means the cursor point position
 ;;; this works
 (loo|
  [x ]
  (prn x))

 ;;; this works too
 (loo| )

 ;;; this does not work, I need to manually start `company-complete`.
 ;;; seems when there are string after point, company-mode can't auto complete.
 (loo| [x ]
       (prn x))
 #+END_SRC

**Comment by dgutov** [comment]
Do you expect completion to `looks`? It works for me in all three cases.

**Comment by stardiviner** [comment]
I tested with minimal init config, yes, by default company-mode works as expected. Seems issue on my configs. Will bisect my config. Please don't close this issue for now. I will update this issue.

**Comment by stardiviner** [comment]
I tried to bisect my init files. Have not found the config which caused this behavior. Bisect all my init files is time spending, I wander is there other ways to find info about this like `company-diag`? I've already checked out `company-diag` which don' give out useful info.

**Comment by dgutov** [comment]
> I've already checked out company-diag which don' give out useful info.

What does it show?

**Comment by stardiviner** [comment]
I run `company-diag` on code:
```clojure
(loo [x]
     (print "hello"))
```
Get the following output:
```
Emacs 26.0.50 (x86_64-pc-linux-gnu) of 2017-05-19 on dark
Company 0.9.3

company-backends: (company-files
 (company-capf :with company-yasnippet)
 (company-keywords :with company-dabbrev-code)
 company-abbrev company-bibtex)

Used backend: (company-capf :with company-yasnippet)

Prefix: "loo"
Completions:
  #("loop" 0 1 (ns "clojure.core" type "macro" face #1=(completions-common-part)) 1 3 (face #1#) 3 4 (face (completions-first-difference))) " (clojure.core) <macro>"
  #("loom.derived" 0 1 (ns nil type "namespace" face #1=(completions-common-part)) 1 3 (face #1#) 3 4 (face (completions-first-difference))) " <ns>"
  #("loom.dataflow" 0 1 (ns nil type "namespace" face #1=(completions-common-part)) 1 3 (face #1#) 3 4 (face (completions-first-difference))) " <ns>"
  #("loom.compliance-tester" 0 1 (ns nil type "namespace" face #1=(completions-common-part)) 1 3 (face #1#) 3 4 (face (completions-first-difference))) " <ns>"
```

**Comment by dgutov** [comment]
Yep, looks correct. Not sure what could be going wrong.

**Comment by dgutov** [comment]
Do you see the same problem in `clojure-mode`?
