### ISSUE TITLE
company-mode conflit with emmet-mode

### ISSUE THREAD

**Issue by liuchong** [company-mode/company-mode#671]
> When I'm editing a HTML file, such as type a "p", will pop out a list "p param picture plaintext...", so I cannot type tab to insert a "<p></p>" via emmet-mode, anybody have the same problem? Is there a solution on this, or there is something wrong of my config or usage? Thanks a lot!

above as just copied from:
https://github.com/syl20bnr/spacemacs/issues/8893

Thanks!

**Comment by dgutov** [comment]
From what I can tell of the issue, it's working as intended. Completion begins according the your configured settings, and yes, as soon as that happens, `TAB` does something other than expanding Emmet templates.

**Comment by liuchong** [comment]
ok, thanks
