### ISSUE TITLE
Redefining shortcuts in company-active-map

### ISSUE THREAD

**Issue by mtourne** [company-mode/company-mode#672]
Let's say I want to change from M-<number> to C-<number> for company since M-<n> is already used in my OS.

This works perfectly well if emacs is already loaded :
```
;;; use C-<n> instead of M-<n> shortcuts
  (dotimes (i 10)
    (define-key company-active-map (read-kbd-macro (format "C-%d" i))
      'company-complete-number))
```

But since company is initialized this way `(add-hook 'after-init-hook 'global-company-mode)` this will Fail if I put it in my .emacs

I've tried putting the conf into an after-init-hook as well, but it fails.

```
;;; after init hook for C-<n> shortcut
(setq company-show-numbers t)
(defun setup_company_macro ()
  (dotimes (i 10)
    (define-key company-active-map (read-kbd-macro (format "C-%d" i))
      'company-complete-number))
  )
;; run macro setting after this (add-hook 'after-init-hook 'global-company-mode)
;; ie: in a after-init-hook as well.
(add-hook 'after-init-hook 'setup_company_macro)
```

**Comment by dgutov** [comment]
How does it fail?

Anyway, try using `eval-after-load` or `with-eval-after-load` (if your Emacs is recent enough) instead.

**Comment by toothbrush** [comment]
I'm having the same issue, actually (and i'd also like to remap to `C-n` and `C-p`, incidentally).

I've tried the following:

```Elisp
(eval-after-load 'company-mode
  '(progn
     (define-key company-active-map (kbd "C-n") 'company-select-next)
     (define-key company-active-map (kbd "C-p") 'company-select-previous)))
```

But it doesn't seem to have any effect.  What am i missing?

**Comment by dgutov** [comment]
@toothbrush

Try `(eval-after-load 'company` instead of `(eval-after-load 'company-mode`.

**Comment by toothbrush** [comment]
Hey there, sorry it took me so long to respond @dgutov!  You were right of course about using `'company` – i still had trouble making it work with Evil mode (some weird conflict).  In case someone else needs it, here's what i eventually have which works, for posterity:

```Elisp
(with-eval-after-load 'evil
  (with-eval-after-load 'company
    (define-key evil-insert-state-map (kbd "C-n") nil)
    (define-key evil-insert-state-map (kbd "C-p") nil)
    (evil-define-key nil company-active-map (kbd "C-n") #'company-select-next)
    (evil-define-key nil company-active-map (kbd "C-p") #'company-select-previous)))
```

Hope that's useful to someone out there! 🙌
