### ISSUE TITLE
Missing keywords in C/C++ sets?

### ISSUE THREAD

**Issue by dgiglio** [company-mode/company-mode#673]
Hi,
Trying to use company-mode for C/C++ i've noticed it doesn't auto complete some preprocessor keywords like `#include` and `#define`. So, after a brief investigation I've discovered that in the company-keywords-alist defined in company-keyword.el these words are missing in the corresponding sets.

How can I contribute to fix this issue?

**Comment by dgutov** [comment]
Are you sure `company-keywords` is being used in your situation?

**Comment by dgiglio** [comment]
Quite sure, as a counter example if I write one of the words included in those sets Emacs suggests me the correct completion.

**Comment by dgutov** [comment]
> if I write one of the words included in those sets Emacs suggests me the correct completion

So you are not using `company-clang`?

> I can provide screenshots if needed.

The output of `M-x company-diag`, please.

**Comment by dgiglio** [comment]
> So you are not using `company-clang`?

Absolutely not, I prefer to use semantic, since I've customized Emacs to work in windows as a front-end of the MS compiler cl.exe

> The output of `M-x company-diag`, please.

Here you go:

Emacs 25.1.1 (x86_64-pc-linux-gnu) of 2017-04-23 on trouble
Company 0.9.3

company-backends: (company-c-headers company-bbdb company-nxml company-css company-eclim company-clang company-xcode company-cmake company-capf company-files
                   (company-dabbrev-code company-gtags company-etags company-keywords)
                   company-oddmuse company-dabbrev)

Used backend: company-clang
Prefix: ""
Completions:
  "volatile"
  "void"
  "unsigned"
  "unix"
  "union"
  "struct"
  "static"
  "signed"
  "short"
  "restrict"
  "long"
  "linux"
  "int"
  "inline"
  "float"
  "extern"
  "enum"
  "double"
  "const"
  "char"
  "_Pragma"
  "_Nullable"
  "_Null_unspecified"
  "_Nonnull"
  "_LP64"
  "_Imaginary"
  "_Complex"
  "_Bool"
  "__x86_64__"
  "__x86_64"
  "__WINT_WIDTH__"
  "__WINT_UNSIGNED__"
  "__WINT_TYPE__"
  "__WCHAR_WIDTH__"
  "__WCHAR_TYPE__"
  "__WCHAR_MAX__"
  "__VERSION__"
  "__USER_LABEL_PREFIX__"
  "__unix__"
  "__unix"
  "__UINTPTR_WIDTH__"
  "__UINTPTR_TYPE__"
  "__UINTPTR_MAX__"
  "__UINTPTR_FMTx__"
  "__UINTPTR_FMTX__"
  "__UINTPTR_FMTu__"
  "__UINTPTR_FMTo__"
  "__UINTMAX_WIDTH__"
  "__UINTMAX_TYPE__"
  "__UINTMAX_MAX__"
  "__UINTMAX_FMTx__"
  "__UINTMAX_FMTX__"
  "__UINTMAX_FMTu__"
  "__UINTMAX_FMTo__"
  "__UINTMAX_C_SUFFIX__"
  "__UINT_LEAST8_TYPE__"
  "__UINT_LEAST8_MAX__"
  "__UINT_LEAST8_FMTx__"
  "__UINT_LEAST8_FMTX__"
  "__UINT_LEAST8_FMTu__"
  "__UINT_LEAST8_FMTo__"
  "__UINT_LEAST64_TYPE__"
  "__UINT_LEAST64_MAX__"
  "__UINT_LEAST64_FMTx__"
  "__UINT_LEAST64_FMTX__"
  "__UINT_LEAST64_FMTu__"
  "__UINT_LEAST64_FMTo__"
  "__UINT_LEAST32_TYPE__"
  "__UINT_LEAST32_MAX__"
  "__UINT_LEAST32_FMTx__"
  "__UINT_LEAST32_FMTX__"
  "__UINT_LEAST32_FMTu__"
  "__UINT_LEAST32_FMTo__"
  "__UINT_LEAST16_TYPE__"
  "__UINT_LEAST16_MAX__"
  "__UINT_LEAST16_FMTx__"
  "__UINT_LEAST16_FMTX__"
  "__UINT_LEAST16_FMTu__"
  "__UINT_LEAST16_FMTo__"
  "__UINT_FAST8_TYPE__"
  "__UINT_FAST8_MAX__"
  "__UINT_FAST8_FMTx__"
  "__UINT_FAST8_FMTX__"
  "__UINT_FAST8_FMTu__"
  "__UINT_FAST8_FMTo__"
  "__UINT_FAST64_TYPE__"
  "__UINT_FAST64_MAX__"
  "__UINT_FAST64_FMTx__"
  "__UINT_FAST64_FMTX__"
  "__UINT_FAST64_FMTu__"
  "__UINT_FAST64_FMTo__"
  "__UINT_FAST32_TYPE__"
  "__UINT_FAST32_MAX__"
  "__UINT_FAST32_FMTx__"
  "__UINT_FAST32_FMTX__"
  "__UINT_FAST32_FMTu__"
  "__UINT_FAST32_FMTo__"
  "__UINT_FAST16_TYPE__"
  "__UINT_FAST16_MAX__"
  "__UINT_FAST16_FMTx__"
  "__UINT_FAST16_FMTX__"
  "__UINT_FAST16_FMTu__"
  "__UINT_FAST16_FMTo__"
  "__UINT8_TYPE__"
  "__UINT8_MAX__"
  "__UINT8_FMTx__"
  "__UINT8_FMTX__"
  "__UINT8_FMTu__"
  "__UINT8_FMTo__"
  "__UINT8_C_SUFFIX__"
  "__UINT64_TYPE__"
  "__UINT64_MAX__"
  "__UINT64_FMTx__"
  "__UINT64_FMTX__"
  "__UINT64_FMTu__"
  "__UINT64_FMTo__"
  "__UINT64_C_SUFFIX__"
  "__UINT32_TYPE__"
  "__UINT32_MAX__"
  "__UINT32_FMTx__"
  "__UINT32_FMTX__"
  "__UINT32_FMTu__"
  "__UINT32_FMTo__"
  "__UINT32_C_SUFFIX__"
  "__UINT16_TYPE__"
  "__UINT16_MAX__"
  "__UINT16_FMTx__"
  "__UINT16_FMTX__"
  "__UINT16_FMTu__"
  "__UINT16_FMTo__"
  "__UINT16_C_SUFFIX__"
  "__tune_k8__"
  "__TIMESTAMP__"
  "__TIME__"
  "__STDC_VERSION__"
  "__STDC_UTF_32__"
  "__STDC_UTF_16__"
  "__STDC_HOSTED__"
  "__STDC__"
  "__SSE_MATH__"
  "__SSE__"
  "__SSE2_MATH__"
  "__SSE2__"
  "__SIZEOF_WINT_T__"
  "__SIZEOF_WCHAR_T__"
  "__SIZEOF_SIZE_T__"
  "__SIZEOF_SHORT__"
  "__SIZEOF_PTRDIFF_T__"
  "__SIZEOF_POINTER__"
  "__SIZEOF_LONG_LONG__"
  "__SIZEOF_LONG_DOUBLE__"
  "__SIZEOF_LONG__"
  "__SIZEOF_INT__"
  "__SIZEOF_INT128__"
  "__SIZEOF_FLOAT__"
  "__SIZEOF_DOUBLE__"
  "__SIZE_WIDTH__"
  "__SIZE_TYPE__"
  "__SIZE_MAX__"
  "__SIZE_FMTx__"
  "__SIZE_FMTX__"
  "__SIZE_FMTu__"
  "__SIZE_FMTo__"
  "__SIG_ATOMIC_WIDTH__"
  "__SIG_ATOMIC_MAX__"
  "__SHRT_MAX__"
  "__SCHAR_MAX__"
  "__REGISTER_PREFIX__"
  "__PTRDIFF_WIDTH__"
  "__PTRDIFF_TYPE__"
  "__PTRDIFF_MAX__"
  "__PTRDIFF_FMTi__"
  "__PTRDIFF_FMTd__"
  "__PRAGMA_REDEFINE_EXTNAME"
  "__POINTER_WIDTH__"
  "__ORDER_PDP_ENDIAN__"
  "__ORDER_LITTLE_ENDIAN__"
  "__ORDER_BIG_ENDIAN__"
  "__NO_MATH_INLINES"
  "__NO_INLINE__"
  "__MMX__"
  "__LP64__"
  "__LONG_MAX__"
  "__LONG_LONG_MAX__"
  "__llvm__"
  "__LITTLE_ENDIAN__"
  "__linux__"
  "__linux"
  "__LINE__"
  "__LDBL_MIN_EXP__"
  "__LDBL_MIN__"
  "__LDBL_MIN_10_EXP__"
  "__LDBL_MAX_EXP__"
  "__LDBL_MAX__"
  "__LDBL_MAX_10_EXP__"
  "__LDBL_MANT_DIG__"
  "__LDBL_HAS_QUIET_NAN__"
  "__LDBL_HAS_INFINITY__"
  "__LDBL_HAS_DENORM__"
  "__LDBL_EPSILON__"
  "__LDBL_DIG__"
  "__LDBL_DENORM_MIN__"
  "__LDBL_DECIMAL_DIG__"
  "__k8__"
  "__k8"
  "__is_identifier"
  "__INTPTR_WIDTH__"
  "__INTPTR_TYPE__"
  "__INTPTR_MAX__"
  "__INTPTR_FMTi__"
  "__INTPTR_FMTd__"
  "__INTMAX_WIDTH__"
  "__INTMAX_TYPE__"
  "__INTMAX_MAX__"
  "__INTMAX_FMTi__"
  "__INTMAX_FMTd__"
  "__INTMAX_C_SUFFIX__"
  "__INT_MAX__"
  "__INT_LEAST8_TYPE__"
  "__INT_LEAST8_MAX__"
  "__INT_LEAST8_FMTi__"
  "__INT_LEAST8_FMTd__"
  "__INT_LEAST64_TYPE__"
  "__INT_LEAST64_MAX__"
  "__INT_LEAST64_FMTi__"
  "__INT_LEAST64_FMTd__"
  "__INT_LEAST32_TYPE__"
  "__INT_LEAST32_MAX__"
  "__INT_LEAST32_FMTi__"
  "__INT_LEAST32_FMTd__"
  "__INT_LEAST16_TYPE__"
  "__INT_LEAST16_MAX__"
  "__INT_LEAST16_FMTi__"
  "__INT_LEAST16_FMTd__"
  "__INT_FAST8_TYPE__"
  "__INT_FAST8_MAX__"
  "__INT_FAST8_FMTi__"
  "__INT_FAST8_FMTd__"
  "__INT_FAST64_TYPE__"
  "__INT_FAST64_MAX__"
  "__INT_FAST64_FMTi__"
  "__INT_FAST64_FMTd__"
  "__INT_FAST32_TYPE__"
  "__INT_FAST32_MAX__"
  "__INT_FAST32_FMTi__"
  "__INT_FAST32_FMTd__"
  "__INT_FAST16_TYPE__"
  "__INT_FAST16_MAX__"
  "__INT_FAST16_FMTi__"
  "__INT_FAST16_FMTd__"
  "__INT8_TYPE__"
  "__INT8_MAX__"
  "__INT8_FMTi__"
  "__INT8_FMTd__"
  "__INT8_C_SUFFIX__"
  "__INT64_TYPE__"
  "__INT64_MAX__"
  "__INT64_FMTi__"
  "__INT64_FMTd__"
  "__INT64_C_SUFFIX__"
  "__INT32_TYPE__"
  "__INT32_MAX__"
  "__INT32_FMTi__"
  "__INT32_FMTd__"
  "__INT32_C_SUFFIX__"
  "__INT16_TYPE__"
  "__INT16_MAX__"
  "__INT16_FMTi__"
  "__INT16_FMTd__"
  "__INT16_C_SUFFIX__"
  "__INCLUDE_LEVEL__"
  "__has_warning"
  "__has_include_next"
  "__has_include"
  "__has_feature"
  "__has_extension"
  "__has_declspec_attribute"
  "__has_builtin"
  "__has_attribute"
  "__GXX_RTTI"
  "__GXX_ABI_VERSION"
  "__GNUC_STDC_INLINE__"
  "__GNUC_PATCHLEVEL__"
  "__GNUC_MINOR__"
  "__GNUC__"
  "__gnu_linux__"
  "__GCC_HAVE_SYNC_COMPARE_AND_SWAP_8"
  "__GCC_HAVE_SYNC_COMPARE_AND_SWAP_4"
  "__GCC_HAVE_SYNC_COMPARE_AND_SWAP_2"
  "__GCC_HAVE_SYNC_COMPARE_AND_SWAP_1"
  "__GCC_ATOMIC_WCHAR_T_LOCK_FREE"
  "__GCC_ATOMIC_TEST_AND_SET_TRUEVAL"
  "__GCC_ATOMIC_SHORT_LOCK_FREE"
  "__GCC_ATOMIC_POINTER_LOCK_FREE"
  "__GCC_ATOMIC_LONG_LOCK_FREE"
  "__GCC_ATOMIC_LLONG_LOCK_FREE"
  "__GCC_ATOMIC_INT_LOCK_FREE"
  "__GCC_ATOMIC_CHAR_LOCK_FREE"
  "__GCC_ATOMIC_CHAR32_T_LOCK_FREE"
  "__GCC_ATOMIC_CHAR16_T_LOCK_FREE"
  "__GCC_ATOMIC_BOOL_LOCK_FREE"
  "__FXSR__"
  "__FLT_RADIX__"
  "__FLT_MIN_EXP__"
  "__FLT_MIN__"
  "__FLT_MIN_10_EXP__"
  "__FLT_MAX_EXP__"
  "__FLT_MAX__"
  "__FLT_MAX_10_EXP__"
  "__FLT_MANT_DIG__"
  "__FLT_HAS_QUIET_NAN__"
  "__FLT_HAS_INFINITY__"
  "__FLT_HAS_DENORM__"
  "__FLT_EVAL_METHOD__"
  "__FLT_EPSILON__"
  "__FLT_DIG__"
  "__FLT_DENORM_MIN__"
  "__FLT_DECIMAL_DIG__"
  "__FINITE_MATH_ONLY__"
  "__FILE__"
  "__ELF__"
  "__DECIMAL_DIG__"
  "__DBL_MIN_EXP__"
  "__DBL_MIN__"
  "__DBL_MIN_10_EXP__"
  "__DBL_MAX_EXP__"
  "__DBL_MAX__"
  "__DBL_MAX_10_EXP__"
  "__DBL_MANT_DIG__"
  "__DBL_HAS_QUIET_NAN__"
  "__DBL_HAS_INFINITY__"
  "__DBL_HAS_DENORM__"
  "__DBL_EPSILON__"
  "__DBL_DIG__"
  "__DBL_DENORM_MIN__"
  "__DBL_DECIMAL_DIG__"
  "__DATE__"
  "__COUNTER__"
  "__CONSTANT_CFSTRINGS__"
  "__clang_version__"
  "__clang_patchlevel__"
  "__clang_minor__"
  "__clang_major__"
  "__clang__"
  "__CHAR_BIT__"
  "__CHAR32_TYPE__"
  "__CHAR16_TYPE__"
  "__BYTE_ORDER__"
  "__BIGGEST_ALIGNMENT__"
  "__BASE_FILE__"
  "__ATOMIC_SEQ_CST"
  "__ATOMIC_RELEASE"
  "__ATOMIC_RELAXED"
  "__ATOMIC_CONSUME"
  "__ATOMIC_ACQUIRE"
  "__ATOMIC_ACQ_REL"
  "__amd64__"
  "__amd64"

**Comment by dgiglio** [comment]
A note: in my linux-box I've both installed llvm+clang and gcc, but I'd like to force the use of the semantic backend, since my plan is to use Emacs as a front-end for the MS compiler cl.exe.
Is it possible?

**Comment by dgutov** [comment]
> but I'd like to force the use of the semantic backend

Yes, by removing `company-clang` from `company-backends. Try `M-x company-semantic` and see if it already provides completion for `#include`.

While it's there, there's no point in adding `include` to the keywords list. On the other hand, `clang` provides completions for preprocessor directives, we just need to learn to parse them.

**Comment by dgiglio** [comment]
> Try `M-x company-semantic` and see if it already provides completion for `#include`.

`Cannot complete at point`

**Comment by dgutov** [comment]
> Cannot complete at point

Is `semantic-mode` on? You need to perform the usual configuration for this backend to work.

**Comment by dgiglio** [comment]
Same as above if not worse:

Emacs 25.1.1 (x86_64-pc-linux-gnu) of 2017-04-23 on trouble
Company 0.9.3

company-backends: (company-c-headers company-bbdb company-nxml company-css company-eclim company-semantic company-clang company-xcode company-cmake company-capf company-files
                   (company-dabbrev-code company-gtags company-etags company-keywords)
                   company-oddmuse company-dabbrev)

Used backend: company-semantic
Prefix: #("incl" 0 4
  (fontified t face font-lock-preprocessor-face c-in-sws t))

Completions: none

**Comment by dgutov** [comment]
Okay, so... If you want this completion from `company-semantic`, you'll have to file a report to the Semantic guys. Probably email this mailing list: https://lists.sourceforge.net/lists/listinfo/cedet-semantic

Otherwise, I think your best choice would be to ask `company-c-headers` author to handle it, not `company-keywords` (which is really something you'd try last because it has no syntax awareness).

**Comment by dgiglio** [comment]
Ok, but please tell me if it's a missing feature, I had already configured auto-complete as a front-end for semantic and I was quite satisfied. I'm doing this experiment with company just to figure out if it could be a better alternative for me.
Many thanks for your time.

**Comment by dgutov** [comment]
I'm saying there's not much I can do on the company-mode side if you are not using `company-clang`. "missing feature" is in the eye of the beholder.

> I had already configured auto-complete as a front-end for semantic and I was quite satisfied.

Did it complete `#include`?

**Comment by dgiglio** [comment]
> "missing feature" is in the eye of the beholder.

:-D

>> I had already configured auto-complete as a front-end for semantic and I was quite satisfied.

> Did it complete #include?

It does, but now that you make me think about it I should investigate on which sources it relies on, the incremental dictionary or the syntax parser.

**Comment by dgutov** [comment]
> I should investigate on which sources it relies on

Thanks in advance.

auto-complete does rely more heavily on merging all applicable sources (that's a choice in defaults, not really in big difference in design). As a result, it offers more completions, generally less precise ones.

We can add `#include` and friends to `company-keywords`, and you can group it with a backend of your choice. But I'm saying adding support in a smarter backend should get you better results.

**Comment by fredericfrances** [comment]
hello ,

I've implemented company-c-preprocessor for doing that mostly based on company-keywords and company-c-headers.

Source can be found here:
https://github.com/fredericfrances/company-c-preprocessor

**Comment by dgutov** [comment]
@fredericfrances Sorry about no answer at that time. We can discuss adding this -- but I think most C/C++ users default to the eglot/lsp-mode backends these days. But I'm open to discussion.

This particular issue, though, seems to have been exhausted.
