### ISSUE TITLE
Freeze with intermittent network drives

### ISSUE THREAD

**Issue by willtalmadge** [company-mode/company-mode#675]
If I have mounted samba shares and the network connection to those shares stalls, company mode will lock up emacs.

For example, I have some network shares mounted inside of /mnt
If I type '/m' emacs will freeze. Once the network connectivity is restored and I type '/m' I see all of the expected autocomplete options, like /mnt and its subfolders.

**Comment by dgutov** [comment]
What would you expect it to do? It accesses the filesystem to find completions. The filesystem is slow, so it waits.

You can type `C-g` (once, or three times in difficult cases) to abort the current command or timer function.
