### ISSUE TITLE
Missing CSS Grid 

### ISSUE THREAD

**Issue by fxfactorial** [company-mode/company-mode#676]

**Comment by dgutov** [comment]
?

**Comment by dgutov** [comment]
Try using Emacs 26 and removing `company-css` from `company-backends`.

**Comment by fxfactorial** [comment]
Okay, got `GNU Emacs 26.0.50 (build 3, x86_64-apple-darwin16.4.0, NS appkit-1504.81 Version 10.12.3 (Build 16D32))` and never had company-css for company-backends, still no completion for CSS grid

**Comment by dgutov** [comment]
Emacs 26 does contain Grid completions. `M-x company-capf` should show them.

But if the UI doesn't work well, not much I can do. You should file bug reports, though.

**Comment by fxfactorial** [comment]
@dgutov  Are you saying then that on 26 I should not use company-css and just use company-capf?

**Comment by dgutov** [comment]
Yup!

It does have a problem currently (http://debbugs.gnu.org/cgi/bugreport.cgi?bug=27392), but we'll fix that soon-ish.
