### ISSUE TITLE
(wrong-type-argument integerp 0.0) on completions

### ISSUE THREAD

**Issue by DrPyser** [company-mode/company-mode#677]
I get `(wrong-type-argument integerp 0.0)` whenever company tries for a completion(either automatically or when I ask for it).

Here's the debugger trace:

```
Debugger entered--Lisp error: (wrong-type-argument integerp 0.0)
  company--create-lines(0 10.0)
  company-pseudo-tooltip-show(4 1 0)
  company-pseudo-tooltip-show-at-point(151 4)
  company-pseudo-tooltip-frontend(post-command)
  company-call-frontends(post-command)
  company-post-command()
  company-idle-begin(#<buffer *scratch*> #<window 3 on *scratch*> 21 151)
  apply(company-idle-begin (#<buffer *scratch*> #<window 3 on *scratch*> 21 151))
  timer-event-handler([t 22852 33528 646290 nil company-idle-begin (#<buffer *scratch*> #<window 3 on *scratch*> 21 151) nil 436000])
```
I cleaned up my init file so that it only contains the necessary and the `(require 'company)` call.

**Comment by dgutov** [comment]
What does `M-x company-diag` say?

**Comment by DrPyser** [comment]
```Emacs 25.1.91.1 (x86_64-unknown-linux-gnu) of 2017-01-27 on drpyser.localdomain
Company 0.9.3

company-backends: (company-bbdb company-nxml company-css company-eclim company-semantic company-clang company-xcode company-cmake company-capf company-files
	      (company-dabbrev-code company-gtags company-etags company-keywords)
	      company-oddmuse company-dabbrev)

Used backend: company-capf
Prefix: "log"
Completions:
  #("log" 0 3 (face (completions-common-part)))
  #("logBase" 0 3 (face (completions-common-part)) 3 4 (face (completions-first-difference)))
  #("logistic" 0 3 (face (completions-common-part)) 3 4 (face (completions-first-difference)))
```

**Comment by dgutov** [comment]
Thanks. Which minor mode is this? Did you install any third-party package for completion?

Is the bug triggered by some particular buffer contents?

**Comment by DrPyser** [comment]
The error seems to happen in any major mode(lisp-mode in scratch buffer, fundamental mode, haskell mode), and the buffer content doesn't seem to matter either.

I'm going to try uninstalling/reinstalling some packages in case one of them broke something.

**Comment by dgutov** [comment]
> in case one of them broke something

**Comment by dgutov** [comment]
> in case one of them broke something

Yeah, that might be the case. You can launch `emacs -Q -L path/to/company` to test that theory. Then you evaluate `(require 'company)` and `(global-company-mode)` in the newly opened session and try to reproduce the problem.

**Comment by DrPyser** [comment]
With nothing else but company mode installed(all packages deleted, init file not loaded, package manually initialized inside emacs...), I still seem to have the same issue.

By the way, I'm on Fedora 24, and my emacs version is `GNU Emacs 25.1.91.1`.

**Comment by DrPyser** [comment]
And again following your instructions, same problem, same debugger trace.

**Comment by dgutov** [comment]
> and my emacs version is GNU Emacs 25.1.91.1

Thanks. That's usually printed on the first line of `company-diag` output, though.

OK, I'll push out a new minor release soon-ish, and we can try this again. I don't recall any similar problems being reported recently, but it's better to be on the same page.

**Comment by dgutov** [comment]
BTW, where did you get Emacs 25.1.91.1 from? Is that an older development snapshot of Emacs 25.2?

**Comment by DrPyser** [comment]
Ok, thanks. I've had other issues with other modes and basic functionalities(like copying selection), so maybe it's my emacs version that's buggy.

**Comment by DrPyser** [comment]
It's the Fedora's repository version.

**Comment by dgutov** [comment]
In that case, you should probably report this to Fedora. Do you mean [25.0.94](https://fedora.pkgs.org/24/fedora-i386/emacs-25.0.94-1.fc24.i686.rpm.html), though? Either way, it's not a release version. Distributing it to users seems unwise.

Fedora Updates has 25.2, though: https://fedora.pkgs.org/24/fedora-updates-i386/emacs-25.2-2.fc24.i686.rpm.html

**Comment by DrPyser** [comment]
Yes, that's the package version I have, and yet emacs gives me the version I posted. I'm going to try with the version from the git repository.

**Comment by DrPyser** [comment]
Found the root of the problem: I had a "phantom" emacs installation(the 25.1.91.1), I'm not sure where it came from. I deleted it, and now it seems to work. Sorry for the bother.

**Comment by DrPyser** [comment]
(And thanks for the help)
