### ISSUE TITLE
Not able to get documentation when pressing F1

### ISSUE THREAD

**Issue by hisnawi** [company-mode/company-mode#679]
I have the following packages installed: 
Company
Irony
company-irony
flycheck
flycheck-irony

Everything works except showing documentation for C/C++ functions. I keep getting "no documentation available". Where do I start with the debug?

**Comment by dgutov** [comment]
Look at the mode-line and see which backend is used.

**Comment by dgutov** [comment]
It seems you got your answer on Reddit: https://www.reddit.com/r/emacs/comments/6ke0bj/not_able_to_get_documentation_when_pressing_f1_in/djld7ug/?st=j4jng8re&sh=81c400fd
