### ISSUE TITLE
emacs response slow when in double quotes for C/C++

### ISSUE THREAD

**Issue by thisEric** [company-mode/company-mode#680]
I am not sure it's company issue or backends', I am working on C/C++ project, using emacs-ycmd as backends, but I found when I type in double quotes, the emacs response very slow, for example:
`std::string name= "Hello, world"`
when I type "Hello world", it will take long time for emacs to response, it looks like trying to auto complete the string, is there any way to disable the auto completion in some customized circumstance, such as in "" or in comments, it's not necessary to trigger the auto completion, thanks

**Comment by dgutov** [comment]
When you are in double quotes, try `M-x company-diag` and post the output here, please.

**Comment by thisEric** [comment]
thanks, @dgutov , the used backend in this case is company-dabbrev , I tried with removing this backend, and it won't block me now, great thanks.
