### ISSUE TITLE
Automatic completion popups not appearing in sharp-mode

### ISSUE THREAD

**Issue by nathanvy** [company-mode/company-mode#682]
### Problem:  
Not sure what the technical term for this is, but the little menu that comes up with completion options is supposed to do so automatically as per the website:

>Completion will start automatically after you type a few letters.

However in my emacs (emacs 25.2, macOS X 12.5), when using csharp-mode and omnisharp as the backend, I do not have automatic suggestions.

What works:  Completion itself actually works, but only if I manually invoke`M-x company-complete`.  The problem seems to be the automatic triggering.

### Steps to reproduce:
1. Open C# file
2. `M-x omnisharp-start-omnisharp-server`
3. `M-x company-mode`
4.  Attempt to write code

### Expected result:
Automatic code completion suggestions

### Actual result:
Code completion only when manually invoking `M-x company-complete`

**Comment by dgutov** [comment]
What does `M-x company-diag` say?

**Comment by nathanvy** [comment]
Wow, apologies.

I changed nothing whatsoever, and when I went to check `company-diag` it's now working.
