### ISSUE TITLE
Completion list shifted to the right with native line numbering

### ISSUE THREAD

**Issue by jjwest** [company-mode/company-mode#685]
Hi.

When using the new native line-numbering I noticed the completion list has started to become 
shifted to the right. Visual: http://i.imgur.com/J8EQznW.png

Is this a compatibility issue with the native line-numbers or perhaps a setting that I'm missing?

Thanks

**Comment by dgutov** [comment]
Please update to the latest Emacs snapshot, and the latest company-mode.

**Comment by jjwest** [comment]
I am using todays snapshot and company-mode 0.9.4. Is there a later version?

**Comment by dgutov** [comment]
Nope. With these versions, if I just `M-x display-line-numbers-mode`, the popup is positioned fine.

Is there a particular setting that breaks it?

**Comment by jjwest** [comment]
Not that I have found. I've tested running with `emacs -Q` with the following configuration:

```emacs-lisp
(add-hook 'prog-mode-hook (lambda () (setq-local display-line-numbers 'relative)))

(use-package company
  :ensure t
  :diminish company-mode
  :preface
  (defun my/company-abort-and-newline ()
    (interactive)
    (company-abort)
    (newline-and-indent))
  :bind (("C-." . company-complete)
	 :map company-active-map
	 ("<C-return>" . my/company-abort-and-newline)
	 ("<tab>" . nil))
  :init
  (add-hook 'prog-mode-hook #'company-mode)
  :config
  (general-define-key "C-." 'company-complete)
  (general-define-key :states '(normal insert)
		      "C-." 'company-complete)
  (setq company-idle-delay 0
	company-minimum-prefix-length 2
	company-tooltip-align-annotations t
	company-require-match nil))

```
But the problem persists.

**Comment by dgutov** [comment]
How do you use `use-package` from `emacs -Q`?

**Comment by jjwest** [comment]
Sorry, forgot the following preface:

```emacs-lisp
(require 'package)
(add-to-list 'package-archives '("melpa" . "https://melpa.org/packages/"))
(package-initialize)

;; Bootstrap use-package
(unless (package-installed-p 'use-package)
  (package-refresh-contents)
  (package-install 'use-package))

```

**Comment by dgutov** [comment]
Any way to repro without me having to install `use-package`? And are all of these settings actually required?

Does it happen in some files but not others?

**Comment by jjwest** [comment]
I tried this minimal setup:

```emacs-lisp
(require 'package)
(add-to-list 'package-archives '("melpa" . "https://melpa.org/packages/"))
(package-initialize)

(require 'company)
(add-hook 'prog-mode-hook #'company-mode)
(add-hook 'prog-mode-hook (lambda () (setq-local display-line-numbers 'relative)))
```

It happens in all files.

**Comment by dgutov** [comment]
What if you replace the first three lines with launching Emacs as `emacs -Q -L ../path/to/company`?

`package-initialize` loads all packages' autoloads. They might interfere somehow.

Also, what's your OS?

**Comment by jjwest** [comment]
Using `emacs -Q -L .../path/to/company` did not make a difference.
I'm using Ubuntu 16.04.

**Comment by dgutov** [comment]
I just did a full rebuild of Emacs from master, and couldn't reproduce. Ubuntu 16.10 here.

Make you can try and do the same. If it still doesn't help, please write to emacs-devel or https://debbugs.gnu.org/cgi/bugreport.cgi?bug=27427 for further advice.

**Comment by jjwest** [comment]
Will do. Thanks! :-)
