### ISSUE TITLE
Question: Customizing the row height?

### ISSUE THREAD

**Issue by azer** [company-mode/company-mode#687]
Is it possible to increase the size of a row in company-mode ? If no, it'd be great.

**Comment by dgutov** [comment]
You mean the popup? It's rendered using an overlay, so it's not at all possible, sorry.

**Comment by azer** [comment]
@dgutov I mean the rows in the popup, line height on the other words

**Comment by dgutov** [comment]
Right. Impossible, with the current rendering method.
