### ISSUE TITLE
Add init hook.

### ISSUE THREAD

**Issue by wasamasa** [company-mode/company-mode#69]
I want to customize `company` keybindings which apparently can only be done after it's loaded. Since I'm not using the global mode for this, I'd prefer to be able to use something like `company-mode-hook` instead of relying on `eval-after-load`.

**Comment by shawnLeeZX** [comment]
Just come across this issue by Googling. Tried to add:

```cl
(eval-after-load 'company '(local-set-key (kbd "C-c C-f") 'company-files))
```

But it seems not to work.

Use the hook:
```cl
(add-hook 'company-mode-hook (lambda ()
                               (local-set-key (kbd "C-c C-f") 'company-files)
                               ))
```

then it works.

Could not figure out why ... They both should work right?

**Comment by dgutov** [comment]
@shawnLeeZX No. `eval-after-load` makes a given form run once, after the package in questions has been loaded.

Using `add-hook`, you make the lambda run each time `company-mode` is entered. Which is at least once per buffer.

**Comment by dgutov** [comment]
@shawnLeeZX The first form is better, but use `define-key` instead of `local-set-key`. When the form is evaluated, `company-mode-map` is not the current local map.
