### ISSUE TITLE
The contents of minibuffer disappear when company mode's menu appears 

### ISSUE THREAD

**Issue by mgoldenbe** [company-mode/company-mode#692]
The problem appears in Emacs 24.5.1 with graphics interface. Here is the code that shows the problem:

```
(package-initialize)
(require 'company)
(require 'cl-lib)

(defun my-backend
    (command &optional arg &rest ignored)
  (interactive (list 'interactive))
  (let ((my-completions '("option-1" "option-2" "option-3" "option-4" "option-5")))
    (cl-case command
      (interactive (company-begin-backend 'my-backend))
      (prefix (and t ;(eq major-mode 'fundamental-mode)
		   (company-grab-symbol)))
      (candidates
       (cl-remove-if-not
	(lambda (c) (string-prefix-p arg c))
	my-completions)))))

(defun my-minibuffer-mode()
  (company-mode 1))

(defun my-read-query()
  (interactive)
  (let ((company-backends (copy-sequence company-backends))
	(minibuffer-local-map (copy-sequence minibuffer-local-map))
	(minibuffer-setup-hook (copy-sequence minibuffer-setup-hook))
	(resize-mini-windows 'grow-only))
    (add-to-list 'company-backends 'my-backend)
    (define-key minibuffer-local-map (kbd "TAB") 'my-backend)
    (add-hook 'minibuffer-setup-hook 'my-minibuffer-mode)
    (read-from-minibuffer "Prompt:\n")))
```
When my-read-query is run, something is entered in the minibuffer and `TAB` is pressed, the menu appears, while the current contents of the minibuffer disappear (either partly or completely). It looks like the minibuffer does not grow enough and its contents are scrolled beyond visibility...

**Comment by dgutov** [comment]
It seems to grow enough after several `TAB` presses. But we do not control the minibuffer growth behavior.

You can report it to Emacs, if you want. `M-x report-emacs-bug`.

**Comment by mgoldenbe** [comment]
Well, I am guessing that the minibuffer decides on the proper width in a straightforward way based on the number of rows used by the contents of the minibuffer, which includes the menu. So, it would seem that the way the menu is displayed is responsible for the issue...

**Comment by dgutov** [comment]
Why does it have the correct size in the end, then?

**Comment by mgoldenbe** [comment]
I do not have enough knowledge of the workings of how the menu is displayed. Note, however, that the same question can be asked by a developer of Emacs: if you think that the minibuffer is responsible, then how do you explain that it has the correct size in the end?

**Comment by dgutov** [comment]
There have been some minibuffer-related changes in Emacs 28 (still in development). If anyone's still seeing this problem, I recommend try compile Emacs from `master`.
