### ISSUE TITLE
Warnings when compiling company mode in emacs 25.2.1

### ISSUE THREAD

**Issue by yogin25** [company-mode/company-mode#695]
I just get the last update of compay from melpa (company-20170817.332) and when compiling the company mode i get two warnings:

1 - company-nxml.el:106:24:Warning: looking-back called with 1 argument, but
    requires 2-3

2 - company.el:837:1:Warning: Unused lexical variable ‘display-line-numbers’

Best regards

**Comment by dgutov** [comment]
Thanks!
