### ISSUE TITLE
Question on the variable name that controls the font face

### ISSUE THREAD

**Issue by oracleyue** [company-mode/company-mode#696]
Could you tell me which variable in company-mode control the font face (the dark-red letters) circled in the following figure? I want to fix it under my theme. However, I failed to locate the variable. Many thanks!

![eg](https://user-images.githubusercontent.com/5046605/29469432-85b2dc80-8448-11e7-813a-ce9eac3edc15.png)

**Comment by dgutov** [comment]
`company-tooltip-annotation`, probably. It's a face definition, not a variable.

**Comment by oracleyue** [comment]
@dgutov  It is this name! Thanks a lot!!
