### ISSUE TITLE
Narrowing is cancelled when quitting company completion

### ISSUE THREAD

**Issue by ilupin** [company-mode/company-mode#698]
In a narrowing buffer (e.g. ```M-x narrow-to-region```) where company mode and flyspell are enabled, quitting the company completion by ```C-g``` will cancel the narrowing.

The problem disappears when flyspell is turned off.

**Comment by dgutov** [comment]
Company itself doesn't do anything with narrowing. Not sure how this happens.

**Comment by ilupin** [comment]
Indeed the problem is irrelevant to company. I can confirm it is caused by flyspell now.
