### ISSUE TITLE
Error in auto-begin

### ISSUE THREAD

**Issue by parhamdoustdar** [company-mode/company-mode#699]
Hi,

I've tried using company with eclim and `company-go`, but whenever I invoke `M-x company-complete`, I get an error saying:

```
Company: An error occurred in auto-begin
Specified program for new process is a directory
```

In an effort to pinpoint this, I tried grepping through the code, but I couldn't find anything.

Am I doing something wrong here? I haven't customized any variables at all. I'm just running `company-mode` with `company-go` also installed.

**Comment by parhamdoustdar** [comment]
Sorry, I used the debugging functionality of Emacs and figured it was being caused by an advice added by another package. I'll close this.

**Comment by ragb** [comment]
@parhamdoustdar  would it be emacspeak-company? I'm getting the same error.

**Comment by parhamdoustdar** [comment]
Yes. Here is how you can fix this:
- Make sure Emacs has access to your path. If not, use the `exec-path-from-shell` package to set it up.
- Do `M-x customize-variable RET emacspeak-play-program RET`
- Then set the variable value to `afplay`. Set and save.
- Enjoy!

**Comment by ragb** [comment]
Thanks, I fixed it be removing the play calls but this fixes it properly.
