### ISSUE TITLE
Company backend development questions

### ISSUE THREAD

**Issue by CeleritasCelery** [company-mode/company-mode#700]
I am writing a company backend for Perl (original thread at #666 ) and everything seems to be working accept for the fact that the completion candidates are being polluted between files. For example if File A has `$foa`, `$fob`, and `$foc` and file B has `$fod`, `$foe`, and `$fof`. When I try to complete in File B after using File A I get all 6 variables instead of only the ones instanited in File B. I have looked the candidate list my server provides and it is correct (i.e. has only `$fod`, `$foe`, and `$fof`). Is this expected behavior for Company? Is there a way to disable this behavior?

edit: If it's relevant, I am developing this in Spacemacs.

**Comment by dgutov** [comment]
You can invoke `M-x company-diag` to see which backend will be used at the current buffer position, and which completions it returns.

**Comment by CeleritasCelery** [comment]
Perfect! That is just what I was looking for! It showed me that there were cases where my prefix was nil and other backends were being activated. However this raised another question. The other backends would automatically provide the popup after I reached `company-minimum-prefix-length` However my backend doesn't do that, I have to manually call it. Is there something that I am missing here? `company-diag` shows that my backend is being used and that the prefix and completion are correct, it just doesn't autotrigger.

**Comment by dgutov** [comment]
> my backend doesn't do that, I have to manually call it. Is there something that I am missing here?

Is it in `company-backends`? Preferably near the front.

**Comment by dgutov** [comment]
And make sure the effective prefix length (if you're returning a cons) satisfies `company-minimum-prefix-length`. That should be it, really.

**Comment by CeleritasCelery** [comment]
Thanks you. So I tracked down the problem, it is because I am using `:async` to generate the candidates. Does `:async` not support idle completion, or am I just implementing it wrong? Here is what it looks like 

```elisp
(defun company-plsense (command &optional arg &rest ignored)
  (interactive (list 'interactive))
  (cl-case command
    (interactive (company-begin-backend 'company-plsense))
    (init (plsense--open-file (buffer-file-name (current-buffer))))
    (prefix (company-plsense-prefix))
    (candidates (cons :async
                      (lambda (callback)
                        (company-plsense-candidates callback arg))))))

(defun company-plsense-candidates (callback prefix)
  (plsense--server-request
   (concat "assist " prefix)
   (lambda (x resp)
     (funcall callback
              (let ((static-prefix (replace-regexp-in-string "[^->$@%&/]*\\'" "" prefix)))
                (--map (concat static-prefix it)
                       (split-string (replace-regexp-in-string "\n>\\s-\\'" "" resp) "\n" t)))))))
```
I am using `lexical-binding:t` as well. When I change it from asynchronous to synchronous, idle completion works fine. I was looking at the doc string and I saw this under  Asynchronous backends "That call must happen in the same buffer as where completion was initiated".  Does this mean I need to do something special?

**Comment by dgutov** [comment]
I see the problem now, thank you. Using `:async` for `prefix` is fairly pointless, because company will wait until the callback is triggered anyway (so the execution is synchronous), but if it's easier for you to use code-wise, let's fix that support.

**Comment by CeleritasCelery** [comment]
I am using `:async` for `candidates`, not `prefix`. Or is there something I am not understanding?

**Comment by dgutov** [comment]
`company-plsense-prefix` doesn't return an `:async` cons?

**Comment by dgutov** [comment]
In that case, I'm having difficulties reproducing the problem.

**Comment by CeleritasCelery** [comment]
No it just uses regex to grab the prefix. No server interaction. `candidates` returns an `:async` cons.

**Comment by dgutov** [comment]
Could you post a small backend that exhibits the problem, and doesn't require installing `plsense`?

**Comment by CeleritasCelery** [comment]
Sure thing. Let me put something together.

**Comment by CeleritasCelery** [comment]
So it turns out in the process of trying to replicate the problem I figured it out 😄. As I suspected, the requirement "That call must happen in the same buffer as where completion was initiated" was important. Turns out that the Emacs built-in `tq` library has a `with-current-buffer` form wrapping its callback convention. Once I wrapped the callback to company in my own buffer scope everything worked fine. Thank you for time and patience.

**Comment by dgutov** [comment]
Great!

> requirement "That call must happen in the same buffer as where completion was initiated" was important

Naturally, it is, or it wouldn't be in the description. Though normally, you don't have to do anything special for it.

If this is going to be a problem for many people, maybe the callback could with the `with-current-buffer` itself...
