### ISSUE TITLE
when set no-cache t,async backend blocking user's input

### ISSUE THREAD

**Issue by SuJiKiNen** [company-mode/company-mode#701]
I'm writing a async backend,I found that I type some characters and wait a little for async backend return ,and then I keep typing,it will have some seriously stuck to keep typing,it seems that company call async backend immedately without a timer,when I remove my backend setting  `(no-cache t)`,this phenomenal were gone,so is this a bug?

**Comment by dgutov** [comment]
> it seems that company call async backend immedately without a timer

Sure, why not? It only waits for `company-idle-delay` when the completion has not been entered yet.

> when I remove my backend setting (no-cache t),this phenomenal were gone

Sure: company doesn't call your backend again anymore, it just uses the completions from cache. Hence the lower CPU usage.

**Comment by SuJiKiNen** [comment]
> Sure, why not? It only waits for company-idle-delay when the completion has not been entered yet.


I think it should call with a timer,since the backend is a async one,with or without cache.

what I need to do cache thing is that when the input is same,(same input,same output),so if I type more the cache shouldn't use,unless I delete the characters I typed.it's non-prefix matching,so cache usually lose some canididates if backend don't re-calculate candidates with current prefix.

**Comment by dgutov** [comment]
> I think it should call with a timer,since the backend is a async one

I don't see why. The extra pauses will make it too slow for most users, and thus more annoying to use.

> what I need to do cache thing is that when the input is same,(same input,same output)

Is repeating the same input really a frequent use case? I'd imagine users normally type new letters. So caching only that would not really change the perceived speed of the backend.

You can implement that kind of cache yourself, though, inside the `candidates` backend command handler.

**Comment by SuJiKiNen** [comment]
> I don't see why. The extra pauses will make it too slow for most users, and thus more annoying to use.

I mean not calling the backend too much times,only when I stop typing,and wait enough idle time,it should call once.

let's say that,if I'm in progressing typing `abcdefg`
where I in `c`,stop and wait for the backend reply,then I keep typing till `g`,
the backend call at point `d`,`e`,`f ` shouldn't be cancel?only at point `g`,I stop type,and wait,the backend should be called.

> Is repeating the same input really a frequent use case? I'd imagine users normally type new letters. So caching only that would not really change the perceived speed of the backend.

so I don't have a good strategy to do the cache thing.

**Comment by dgutov** [comment]
> only when I stop typing

That already happens, AFAICS.

> and wait enough idle time

And that has the "too slow" problem that I mentioned above. How much idle time is "enough"?

You can try modifying `company--fetch-candidates` to try putting the `company-idle-begin` call in it inside an idle timer, and see how it works for you.

**Comment by dgutov** [comment]
Async works a bit differently now, so this discussion is outdated.
