### ISSUE TITLE
Sharing completion code and implementations between Emacs/Vim/ other editors ?

### ISSUE THREAD

**Issue by MarcWeber** [company-mode/company-mode#703]
I started a new project I called editor-cells:
https://github.com/MarcWeber/editor-cells

I wondered why the hell each editor is always ruling his own thing for common features such as completions, goto definition and similar easy language related features.

Is anybody interested in helping me writing the Emacs glue code so that I can integrate with company-mode?

**Comment by dgutov** [comment]
How is it different from Language Server Protocol?

**Comment by dgutov** [comment]
Too much vimscript, too little explanation.
