### ISSUE TITLE
Company complete in git-commit-mode sourced from magit-diff-mode

### ISSUE THREAD

**Issue by blaenk** [company-mode/company-mode#704]
By default, in Magit, when one goes to create a commit, or edit a commit, etc., it shows two windows: the top one is where you type the commit message (git-commit-mode) and the bottom one shows a magit-diff of the changes. This is amazing because it lets you review the changes in order to form a better commit message.

One thing I often find myself doing is that I want to reference a function or variable that is present in the diff, and I always find myself having to scroll the diff buffer to bring that thing into view to make sure that I spell it correctly (especially for longer names).

I was thinking it would be amazing if we could somehow get company or one of its backends to use that diff buffer as a source to complete in the commit message buffer.

Is there any way at all to accomplish this? Or would it require the creation of a separate backend? Would it be feasible?

**Comment by dgutov** [comment]
Try adding both major modes to `company-dabbrev-code-modes`, maybe.

**Comment by blaenk** [comment]
It turns out that the commit message buffer is actually text-mode, git-commit-mode is only a minor mode. I couldn't find a way to make company-dabbrev-code-modes apply to when a minor-mode is active.

It does seem to work when I do this:

``` elisp
company-dabbrev-code-modes t
company-dabbrev-code-other-buffers 'all
company-dabbrev-code-everywhere t
```

But it seems like a sledge-hammer approach; it seems to end up using company-dabbrev-code everywhere, as the variable says. Do you think there might be a more fine-grained solution to this? Or is there a better way I should be doing this in general?

I tried by putting `company-dabbrev-code` at the beginning of the `company-backends` list when the git-commit buffer is created (for which [`git-commit-setup-hook`](https://magit.vc/manual/magit/Editing-commit-messages.html) exists). `company-diag` does show it at the front, but it still says the backend used is `company-abbrev`. I guess it's because it checks to make sure it's a mode that's inside the `code-modes` variable:

``` elisp
    (prefix (and (or (eq t company-dabbrev-code-modes)
                     (apply #'derived-mode-p company-dabbrev-code-modes))
                 (or company-dabbrev-code-everywhere
                     (not (company-in-string-or-comment)))
                 (or (company-grab-symbol) 'stop)))
```

If I add `text-mode` then it'll also apply to all other modes that derive from `text-mode` right, which I don't really want. Perhaps something I can do is add an advice to filter the arguments so that if the minor mode `git-commit-mode` is enabled, then set locally bind `company-dabbrev-code-modes` to `t`?

**Comment by dgutov** [comment]
I see two different approaches:

* Lobby for the message buffer to have a dedicated major mode, then see my previous message.

* Set `company-dabbrev-code-modes` to a buffer-local value inside `git-commit-mode-hook`. Setting it to `'(text-mode magit-diff-mode)` should do the trick.

**Comment by blaenk** [comment]
Ah yeah, your second point is simpler and clearer than an advice.

It deliberately doesn't have a dedicated major mode, so I guess there's no point in lobbying for it:

> git-commit-mode is a minor mode that is only used to establish the above key bindings. This allows using an arbitrary major mode when editing the commit message. It’s even possible to use a different major mode in different repositories, which is useful when different projects impose different commit message conventions.

I guess another hack would be to create my own mode for that? I feel like a buffer-local value is much simpler though. I'll try that.

**Comment by blaenk** [comment]
I forgot to report back. It turned out that the buffer was actually being ignored, I think, because its name is of the form `*magit-diff: reponame`, so I also `setq-local` a custom ignore function:

``` elisp
(defun my--company-dabbrev-ignore-except-magit-diff (buffer)
  (let ((name (buffer-name)))
    (and (string-match-p "\\`[ *]" name)
         (not (string-match-p "\\*magit-diff:" name)))))

(defun my--git-commit-setup-hook ()
  (setq-local fill-column 72)

  (setq-local company-dabbrev-code-modes '(text-mode magit-diff-mode))
  (setq-local company-dabbrev-ignore-buffers
              #'my--company-dabbrev-ignore-except-magit-diff))

(add-hook 'git-commit-setup-hook #'my--git-commit-setup-hook)
```

With the above setup, it seems like I can now complete in the commit message buffer sourced from the diff buffer, such as function names.

If there's anything I'm doing wrong or if there's a better way, I'm all ears.

Thanks for the pointers!

**Comment by dgutov** [comment]
Great! This looks about like what I expected. Good thinking on `company-dabbrev-ignore-buffers`.

Maybe this kind of integration could be made more obvious for users, but I don't immediately see how.

**Comment by Sarcasm** [comment]
Wow, this is exactly a feature I wanted, but never tried to do it, thanks @blaenk for doing it!

I had to add something to the hook to get it working, maybe you already have it somewhere else in your config:

```diff
(defun my--git-commit-setup-hook ()
  (setq-local fill-column 72)

  (setq-local company-dabbrev-code-modes '(text-mode magit-diff-mode))
+ (setq-local company-dabbrev-code-other-buffers 'all)
  (setq-local company-dabbrev-ignore-buffers
              #'my--company-dabbrev-ignore-except-magit-diff))
```

**Comment by blaenk** [comment]
Ah you're right, I forgot to include that. I have mine set to `'code` though. You can check it's docstring to tell the difference.

**Comment by Sarcasm** [comment]
Oh, that's why `magit-diff-mode` is in `company-dabbrev-code-modes`, I guess I will use code as well then. :)
