### ISSUE TITLE
how can I fix the popup width of completion

### ISSUE THREAD

**Issue by amosbird** [company-mode/company-mode#705]
https://la.wentropy.com/5Cy4.webm

**Comment by dgutov** [comment]
Fix meaning make the scrollbar visible on the right? Or limit it to a much smaller width?

**Comment by dgutov** [comment]
Does `(company--window-width)` return an appropriate value in that window?

**Comment by amosbird** [comment]
>  Fix meaning make the scrollbar visible on the right? Or limit it to a much smaller width?

fix it to a sensible width would be fine.

`(company--window-width)`  is 158

**Comment by Sarcasm** [comment]
Oh, I also was wondering about this too.
What troubled me is that the popup can reduce in size.
I can understand it can grows when we see that the candidates width has increased with the new candidates.
But it would be nice to avoid shrinking IMHO.

**Comment by dgutov** [comment]
There is `company-tooltip-minimum-width` option already. We can add a `-maxiumum-` option too. But the popup would still grow and shrink between these two values (if they are different), to accommodate the contents.

In this case, however, I'm first of all worried about the popup not fitting in the window at all. @amosbird Is this just a fragment of the screen? If the window continues on the right, good.

**Comment by amosbird** [comment]
yeah, it's a partial screencast. the popup never across the buffer's left or right margin.

**Comment by dgutov** [comment]
You can try e.g. `(setq company-tooltip-maximum-width 70)` now.

**Comment by amosbird** [comment]
great! thanks.
