### ISSUE TITLE
company-complete always returns 'no completion found'.

### ISSUE THREAD

**Issue by dwrz** [company-mode/company-mode#707]
I can't seem to get company-mode to work, and am having difficulty figuring out how to setup up and enable it correctly.

Currenly, there are no popups, and ```company-complete``` always returns ```No completion found```. I get that output if I also run the command for a specific backend, like ```company-ispell``` and ```company-tern```.

I'm on ```Emacs 25.2.1``` and Arch Linux x86_64. ```company-version``` is 0.9.4.

Following is my config, which I'm guessing is the source of the problem:
```
 '(company-auto-complete nil)
 '(company-backends
   (quote
    (company-ispell company-tern company-emoji company-abbrev company-bbdb company-nxml company-css company-eclim company-semantic company-clang company-xcode company-cmake company-capf company-files
		    (company-dabbrev-code company-gtags company-etags company-keywords)
		    company-oddmuse company-dabbrev)))
 '(company-idle-delay 0)
 '(company-minimum-prefix-length 2)
```
...
```
 '(global-company-mode t)
```
Any suggestions or insights on getting started?

**Comment by dgutov** [comment]
Yup: `M-x company-diag`.

**Comment by dwrz** [comment]
Thank you! Here's the output:

```Emacs 25.2.1 (x86_64-unknown-linux-gnu) of 2017-07-15 on arojas
Company 0.9.4

company-backends: (company-ispell company-tern company-emoji company-abbrev company-bbdb company-nxml company-css company-eclim company-semantic company-clang company-xcode company-cmake company-capf company-files
		(company-dabbrev-code company-gtags company-etags company-keywords)
		company-oddmuse company-dabbrev)

Used backend: company-abbrev
Major mode: js2-mode
Prefix: #("fun" 0 3
  (fontified t help-echo "missing ; after statement" cursor-sensor-functions
	     (js2-echo-error)))

Completions: none
```
```
Emacs 25.2.1 (x86_64-unknown-linux-gnu) of 2017-07-15 on arojas
Company 0.9.4

company-backends: (company-ispell company-tern company-emoji company-abbrev company-bbdb company-nxml company-css company-eclim company-semantic company-clang company-xcode company-cmake company-capf company-files
		(company-dabbrev-code company-gtags company-etags company-keywords)
		company-oddmuse company-dabbrev)

Used backend: company-abbrev
Major mode: org-mode
Prefix: #("inq" 0 3
  (fontified t))

Completions: none
```
I'm not sure why the used backend is ```company-abbrev```. I tried running ```company-begin-backend```, then selecting a backend, but it seemed to make no difference.

**Comment by dgutov** [comment]
About `company-ispell`, you likely don't have the necessary program (normally `look`) or a dictionary installed.

And `company-tern` requires `tern`, and `tern-mode` to be enabled.

**Comment by dwrz** [comment]
Thanks again!

I'm able to run ```ispell``` in Emacs, as well as change between dictionaries. It's also installed on my OS. I'm not sure about ```look```, but I'll ***look*** into that.

I have ```tern``` installed via npm, and have the appropriate Emacs packages as well.

Could there be anything else?

**Comment by dgutov** [comment]
> Still, company-ispell is not working

Try edebug-ing `company-ispell-available`. `M-x find-function`, then `M-x edebug-defun`, then try calling the backend directly.

**Comment by dwrz** [comment]
Thanks! I got a backtrack and a help message.

The backtrace seems to confirm your diagnosis: ```message "Company: ispell-look-command not found"```. I can post the entire contents of the backtrace, if that's helpful.

The help message:
```
nil’s value is nil

Documentation:
Not documented as a variable.
```
I tried running ```ispell-complete-word```, which outputted ```lookup-words error: No plain word-list found at systemdefault locations. Customize 'ispell-alternate-dictionary to set yours.```

I went to customize that variable, and strangely enough, it had been edited (outside of customize), even though I cloud not find a reference in ```init.el```. It's now set to the default ```/usr/share/dict/words```, which appears to be a dictionary file.

However, it looks like I am still getting the same debug output.

Not sure if it matters, but ```which look``` yields ```/usr/bin/look```.

**Comment by dgutov** [comment]
> I got a backtrack

I'm confused. With edebug, you should be able to step through the function's execution. And with some determination, find out exactly where it fails.

**Comment by dwrz** [comment]
My apologies, and thanks again for your patience!

I tried following your instructions again, and it looks like I'm getting a fat arrow at line 50 on in ```company-ispell.el```: 
```
  (when (eq company-ispell-available 'unknown)
```
After which I get ```Cannot complete at point```. 

Is this the output you expected?

**Comment by dgutov** [comment]
Did you step through with Space?

**Comment by dwrz** [comment]
I've ended up not having to -- after a system reboot, everything just started working. I'm not sure why, but thank you again for your time, company-mode, and teaching me what to do next time. :smiley:

**Comment by cactail** [comment]
Hi everyone, I have the same problem.
I'm working in python with company-jedi package.
After run `pyvenv-workon` RET `myvenv` to activate my virtual enviroment, `company-complete-common` always returns `No completion found.`. 
Before this, company works well.

Any suggestions?

**Comment by dgutov** [comment]
@cactail You can ask on StackExchange, Reddit, or the `company-jedi` issue tracker.

**Comment by Necktwi** [comment]
`company-complete` not working yet! I did add `(setq rtags-completions-enabled t)`. `M-x company-complete` gives:
```
Company: An error occurred in auto-begin
Company: backend company-rtags async timeout with args (candidates shader)
```
I do see the rdm server printing the commands upon typing in emacs in `.cpp` buffer
```
/usr/local/bin/rc --current-file=/home/Necktwi/workspace/displaz/src/render/View3D.cpp -b --unsaved-file=/home/Necktwi/workspace/displaz/src/render/View3D.cpp:/tmp/wCZHc0 -z -t128 --code-complete-at /home/Necktwi/workspace/displaz/src/render/View3D.cpp:1048:22: --synchronous-completions --elisp --code-complete-prefix=shader
```
Why is this issue closed?

**Comment by dgutov** [comment]
@Necktwi You're apparently having some problems with your `rtags` setup.

I suggest you look at its documentation, read through its existing bug reports, and possibly report yours to its issue tracker: https://github.com/Andersbakken/rtags

You could also try one of the LSP-based solutions instead.
