### ISSUE TITLE
Remove redundant code in company-css.el

### ISSUE THREAD

**Issue by tromey** [company-mode/company-mode#708]
`company-css.el` has a few things that also exist in css-mode.  Since css-mode is included in Emacs, I think company-css should just `require` it and use its definitions.  The css-mode definitions seem to be more up to date.

The particular things I see are `company-css-property-alist`, `company-css-value-classes`, `company-css-pseudo-classes`.  (I suspect `company-css-html-tags` is probably redundant with something in sgml-mode as well)

**Comment by dgutov** [comment]
We should probably deprecate `company-css` altogether now that its features been merged into Emacs (all of them, right?).

So we'll add a similar condition to `company-backends` definition as what's there for `company-elisp`.
