### ISSUE TITLE
visual-line-mode/variable-pitch-mode popups

### ISSUE THREAD

**Issue by ksjogo** [company-mode/company-mode#71]
Hi,
when visual-line-mode and variable-pitch-mode (I use it for LaTeX) are active the popup lines while sprawl throughout the lines and are not aligned. (without pitch it has problems at the end of a visual line, the first popup line wraps).
Is it maybe possible to add a functionality like pos-tip, resulting in a stable display in all circumstances?

**Comment by dgutov** [comment]
See the latest NEWS entry regarding `variable-pitch-mode` support.
