### ISSUE TITLE
Get stuck when typing if the candidates list shows.

### ISSUE THREAD

**Issue by moyotar** [company-mode/company-mode#710]
OS: windows 10
emacs-version: GNU Emacs 25.2.1 (i686-w64-mingw32) of 2017-04-25
company version: 0.9.0
Used backend: (company-ycmd company-files company-keywords company-capf company-yasnippet)

In a python project, I often get stuck when typing if the candidates list shows. What's worst, if I had used
`company-select-next` or  `company-select-previous` to move selection but finally didn't choose anyone and kept typing more or `backspace`, I would get seriously stuck.

**Comment by dgutov** [comment]
That's a lot of backends to merge together. Why both `company-ycmd` and `company-capf` together?

**Comment by dgutov** [comment]
What happens if you try them separately? Does any single backend have this same effect?

**Comment by moyotar** [comment]
With `company-ycmd` as the only backend, It makes no differences.

**Comment by dgutov** [comment]
Do you also see this problem with the default company-mode configuration? With adding `company-ycmd` to `company-backends` being the only modification?

**Comment by moyotar** [comment]
Uh.. I commented my config about company and found no completions.

> Emacs 25.2.1 (i686-w64-mingw32) of 2017-04-25 on LAPHROAIG
> Company 0.9.0
> 
> company-backends: (company-bbdb company-nxml company-css company-eclim company-semantic company-clang company-xcode company-cmake company-capf company-files
> 			  (company-dabbrev-code company-gtags company-etags company-keywords)
> 			  company-oddmuse company-dabbrev)
> 
> Used backend: company-capf
> Prefix: "pri"
> Completions: none

**Comment by moyotar** [comment]
Just now I used `company-files` to test and found I can't reproduce the situation like using `company-ycmd` , because when the candidates list shows, I'm told that `Matching input is required` if keeping typing.

**Comment by dgutov** [comment]
> Uh.. I commented my config about company and found no completions

Now add `company-ycmd` to `company-backends`. Do you see that problem?

**Comment by moyotar** [comment]
Yes!

**Comment by moyotar** [comment]
I manually used `company-ycmd` and I saw that problem.

**Comment by moyotar** [comment]
It seems that I need to call @ptrv @abingham now.

**Comment by moyotar** [comment]
@ptrv @abingham Even There's no candidates list showing, I could get stuck, but not worse than with that shows.

**Comment by moyotar** [comment]
@ptrv @abingham My fault. I close the synchronous completion request. And it works better.

**Comment by dgutov** [comment]
> I close the synchronous completion request

What does that mean?
