### ISSUE TITLE
company-clang-arguments "file not found" if using a space.

### ISSUE THREAD

**Issue by gatoWololo** [company-mode/company-mode#711]
Hello,
Thank you so much for the amazing work on company-mode.

I use a dir-locals.el to set `company-clang-arguments` to point to my include directories: `("-I/home/path/to/include/directory/", "-I/second/path/", ...)`.

Instead, if I have a space character between "-I" and "/home/..." I get a clang error: `"header.h" file not found`. Both methods work from the command line.

It's not a big issue, but I thought I would post it here for anyone who runs across this issue in the future.

**Comment by dgutov** [comment]
A space like `"-I /home/..."` or `"-I" "/home/..."`?

**Comment by gatoWololo** [comment]
A space like `"-I /path/.../". Which works fine when copying the clang auto complete command to a terminal and running it directly.

**Comment by dgutov** [comment]
That's normal. It's like an escaped space on the command line: it wouldn't work either.
