### ISSUE TITLE
Emacs 26 threads?

### ISSUE THREAD

**Issue by aaronjensen** [company-mode/company-mode#717]
Hi, I was wondering if any consideration has been put into whether or not the new lisp thread system would be able to help to make lisp backends async? I'm thinking of things like company-dabbrev that can sometimes cause a slight stutter. In an ideal implementation I'd be able to set `company-idle-delay` to 0 for all backend combinations and not notice any stutter.

**Comment by dgutov** [comment]
Most likely not.

Emacs threads are not concurrent (only one Lisp threads runs at a time), so I don't see how it can speed up dabbrev in any way. Using an external process maybe, but that's a different architecture.

**Comment by aaronjensen** [comment]
Perhaps not speed it up, but could it yield to input in any of its looping?

**Comment by dgutov** [comment]
That's an interesting question. But what would it do when control returns to it after input? The collected results are already invalid, strictly speaking.

On the other hand, even without threading, we could add an `input-pending-p` condition to `company-dabbrev--search-buffer`.

**Comment by aaronjensen** [comment]
They may not be completely invalid, they may be a superset of the valid results. For example, if I type "exclamation", and company kicks in at "ex" and finishes after I type "c", filtering it down further would be faster. I know that different fuzzy finders may need to handle that differently, but maybe it'd work in many cases.

Also, I think that the stutter I was seeing recently was coming from backends other than `company-dabbrev`, or from a combination of many backends running. This is what I had:

```lisp
'((company-dabbrev-code company-gtags company-etags company-keywords)
    company-files 
    company-dabbrev)
```

By removing `(company-dabbrev-code company-gtags company-etags company-keywords)` it sped things up. I'll run at `company-idle-delay` 0 and for a bit and see how it goes. 

That said, I have a fast computer and I think that this would generally be a good improvement that could be applied to many of the lisp backends.

**Comment by dgutov** [comment]
> They may not be completely invalid, they may be a superset of the valid results

That maybe be true. So if you want to try your hand at a threads-based backend, please go ahead. Without threads, I think we can also use per-buffer caches for a close-enough improvement.

> the stutter I was seeing recently was coming from backends other than company-dabbrev

From `company-dabbrev-code`, then? It shares the implementation and has the same tradeoffs.

**Comment by aaronjensen** [comment]
> From company-dabbrev-code, then? It shares the implementation and has the same tradeoffs.

Possibly yeah, I wasn't sure if it was one of the others (or the combination of all of them working at once).

Today I'm back to seeing lagging with `company-dabbrev`. I tried to wrap the body of `company-dabbrev--search-buffer` with `while-no-input`, but for some reason it actually lost input events while typing rapidly. Is there something about that that consumes events?

> Without threads, I think we can also use per-buffer caches for a close-enough improvement.

Yeah, that'd help probably. When would it be recomputed? Without a reliable way to interrupt on input I'd be worried that the recompute may cause stutter if you start typing after an idle period, during a recompute. Maybe I'm missing something obvious though.

**Comment by dgutov** [comment]
> Is there something about that that consumes events?

Not something I can answer off the top of my head, sorry.

> When would it be recomputed?

It will be flushed in `before-change-functions` and recomputed on demand. It should help when the actual problem is not the size of a single huge buffer, but lots of buffers.

**Comment by Fuco1** [comment]
I've written something for sallet ([code](https://github.com/Fuco1/sallet/blob/master/sallet-concurrent.el#L152), [architecture](https://github.com/Fuco1/sallet/blob/master/dev-notes-concurrent.org)) which is my clone of helm where I run chunks of code for 10 miliseconds and then yield to the loop... the problem with this approach is that you have to manually do this and write all the code with this in mind up-front. However it works quite nicely in practice.

I'm failing to understand what's the point of the new thread model in Emacs.  If only one lisp thread can run at the same time all we can do is wait for IO which we can do now already with sentinels?

**Comment by aaronjensen** [comment]
I tried porting company-dabbrev to threads and ran into crashes and general slowness. It wasn't a good experience. I've reported them.

It's interesting that you've gotten it working well. 

I believe the point is that it won't interrupt IO, or it would interrupt it less and allow it to continue. Ideally typing would be responsive always and background work would only be done in the background.

What are sentinels?

**Comment by Fuco1** [comment]
Note that I'm not using threads but [deferred.el](https://github.com/kiwanami/emacs-deferred).  Yea, typing is responsive because the thing uses idle timers as the implementation.  So while events are coming in nothing happens and when there's a bit of time something is scheduled to run for 10 ms and then it stops.  I'm using closures to make the functions "restartable" (they keep their own internal state that way).

Sentinels are attached to processes spawned by Emacs to monitor what's going on.  I guess I wanted to say filters which are also run on IO/wait and process the process output.

**Comment by aaronjensen** [comment]
Ah, those sentinels, I was thinking about user input. 

And yes, I just skimmed your architecture page and I see now that you're not using threads. I'd guess that the point of emacs threads is to make it easier to write that code... in theory you can sprinkle yields in. Also, they've said that some day they may move to a different scheduler, so it'd be forward compatible with that.

That said, from my limited testing, it doesn't seem ready to use. The approach you're using seems like it'd work well. I've already modified company-dabbrev to abort when input is pending, but this, for some reason, isn't perfect and still slows down typing when you have long buffers open. I haven't figured out why yet.

**Comment by dgutov** [comment]
Some pathological case in the regexp engine, maybe? When a `re-search-forward` call takes too long even over 10000 chars.

**Comment by aaronjensen** [comment]
Ah, that's an interesting possibility. In that case we could actually bound `re-search-forward` to something smaller and loop, yeah?

**Comment by aaronjensen** [comment]
I just tested again in the modes I've had that have been problematic and I'm not noticing the slowdown I have before. I've recently revamped/greatly sped up my mode-line and am now using the latest company w/ the flicker fixes, so perhaps something else has been fixed in the process. I'll keep an eye out and experiment w/ a `re-search-forward` bound if I find any more issues.

**Comment by dgutov** [comment]
Hmm, actually, it's 10000 only for "backward" searches. It's a literal in the code. You can try lowering it, but the first thing to try is to similarly limit the spans of forward searches (the last 6 lines in `company-dabbrev--search-buffer`).
