### ISSUE TITLE
When does company call backends with `nil` as the candidate?

### ISSUE THREAD

**Issue by cpitclaudel** [company-mode/company-mode#718]
I'm seeing this happen on user machines, in particular for `meta` queries.

**Comment by dgutov** [comment]
Sounds like a bug. Have a repro?

**Comment by cpitclaudel** [comment]
No, unfortunately :/ I've only seen this on user machines...
I'll try to collect one.

**Comment by cpitclaudel** [comment]
I don't have a repro for this, so let's close it
