### ISSUE TITLE
Option to call company-completion-finished-hook even on implicit completion

### ISSUE THREAD

**Issue by raxod502** [company-mode/company-mode#719]
Currently, `company-completion-finished-hook` is only called if the user explicitly accepts a completion candidate. If they type out an exact match for one of the candidates, and then just go on typing, then that action is not considered a completion.

However, having such "implicit" completions call the hook would be very useful for statistical tools like `company-statistics`. See https://github.com/company-mode/company-statistics/issues/11, which is what [prompted](https://github.com/company-mode/company-statistics/issues/11#issuecomment-334316316) this issue.

Can an option be added to allow for this behavior (calling `company-completion-finished-hook` when the completions menu is implicitly dismissed with an exact match for a candidate)?

**Comment by dgutov** [comment]
I think we can add a new hook, and third-party code can choose to use it.

Something like `company-completion-unique-hook`?

**Comment by raxod502** [comment]
Sounds like a great idea. Another name idea would be `company-implicit-completion-hook`.

**Comment by dgutov** [comment]
I think `company-completion-cancelled-hook` might be enough. Just check that the argument passed to it is the symbol `unique`.
