### ISSUE TITLE
company-mode conflict with ac-php while edit php file

### ISSUE THREAD

**Issue by chenpoyang** [company-mode/company-mode#723]
while edit php files, i want to use ac-php for auto-completion; while edit C/C++ file i want to use irony-server and company-mode for auto-completion, how to wirte to config files about company-mode?

**Comment by dgutov** [comment]
You can enable `company-mode` and `auto-complete-mode` in different buffers depending on the mode, just take care not to enable both.

**Comment by ichirika** [comment]
```
(add-hook 'php-mode-hook
          '(lambda ()
             (require 'company-php)
             (company-mode t)
             (ac-php-core-eldoc-setup) ;; enable eldoc
             (make-local-variable 'company-backends)
             (add-to-list 'company-backends 'company-ac-php-backend)))
```

**Comment by ichirika** [comment]
```
(defun my-c++-hooks ()
  "Enable the hooks in the preferred order: 'yas -> auto-complete -> irony'."
  ;; if yas is not set before (auto-complete-mode 1), overlays may persist after
  ;; an expansion.

  (c-set-style "cc-mode")
 
  (company-mode)
  (flycheck-mode)
  (set 'irony-known-modes '(c-mode c++-mode))
  (when (member major-mode irony-known-modes)
    (irony-mode 1)))	

(add-hook 'c-mode-hook 'c++-mode)
(add-hook 'c++-mode-hook 'my-c++-hooks)
(add-hook 'irony-mode-hook (lambda()
			     (make-local-variable 'company-backends)
			     (add-to-list 'company-backends 'company-irony)
			     (add-to-list 'company-backends 'company-irony-c-headers)
			     ))

```

**Comment by chenpoyang** [comment]
i close global-company-mode, and use company-mode in different mode instead:
<pre>
(add-hook 'emacs-lisp-mode-hook (lambda()
							 (company-mode)))

(add-hook 'css-mode-hook (lambda()
						   (company-mode)))

(add-to-list 'auto-mode-alist '("\\.c\\'" . c++-mode))
(add-hook 'c++-mode-hook (lambda()
						   (company-mode)))

(add-hook 'objc-mode-hook (lambda()
							(company-mode)))
</pre>
