### ISSUE TITLE
Candidate buffer breaks at end of line with visual line mode

### ISSUE THREAD

**Issue by LindyBalboa** [company-mode/company-mode#724]
Arch Linux
Emacs up to date with master, all packages updated
using ycmd

Related: issue #249 and issue auto-complete/auto-complete#374

Also has the problem of sometimes when typing past the end of the window, the next visual line wraps to the BOTTOM of the candidate buffer, so it can jump ~10 lines.

![image](https://user-images.githubusercontent.com/20605205/31537170-71708e7c-b001-11e7-85bd-83538e7fab0e.png)

**Comment by dgutov** [comment]
Could you give a step-by-step repro starting with `emacs -Q`?

**Comment by LindyBalboa** [comment]
I just tried with an extemely stripped down .emacs and was not able to reproduce it. When I get a chance I will try to comment everything out and re-enable bit by bit until I find the culprit.

**Comment by dgutov** [comment]
Found it. Caused by native line numbering, patch incoming.

**Comment by LindyBalboa** [comment]
Wondeful news. Sorry I wasn't able to get around to aiding more in the hunt. Thanks for the work 👍
