### ISSUE TITLE
company is looking for TAGS for certain filetypes

### ISSUE THREAD

**Issue by Opioid** [company-mode/company-mode#725]
I've been using company for a while and it used to provide completion suggestions for all file types. A while ago it started complaining about a missing TAGS file under certain circumstances, e.g. when I'm editing C++ or javascript files, and refuses to provide any auto-completion. 
It still works fine for simple text files.
Is there a way to tell company to stop looking for a tags file and just default to the most simple behavior if there is not any tags system installed?

**Comment by dgutov** [comment]
> A while ago it started complaining about a missing TAGS file under certain circumstances

Do you have the exact message?

A reproduction scenario would also be most helpful.

**Comment by Opioid** [comment]
This is weird, I get the following message while editing a completely unrelated file.

Company: An error occurred in auto-begin
Company: backend (company-dabbrev-code company-gtags company-etags company-keywords) user-error: File d:/Workspace/lwvr_poc2/LWVR/LightweightVRPoC2.mweb/src/TAGS does not exist

I never noticed that the files are completely unrelated. They are not in the same folder or logically part of the same project or anything.

I used to experiment with etags for js but have since purged it from my emacs init.el Could there be some leftovers anywhere? I'm puzzled why it still insists on those tags, in a c++ file no less.

**Comment by dgutov** [comment]
You're probably setting `tags-file-name` to this value somehow, somewhere.

**Comment by Opioid** [comment]
You are exactly right. This solved my problem. Thanks for the help!

But does this mean that you can only have one tags file? I suppose one of those tags packages take care of this.

**Comment by dgutov** [comment]
> But does this mean that you can only have one tags file?

In Emacs 26, you should be able to call `visit-tags-table` with the second argument `t` and have this work, but `setq-local` is not enough.
