### ISSUE TITLE
company-clang on windows: slow and only for built-in types?

### ISSUE THREAD

**Issue by Opioid** [company-mode/company-mode#726]
I added clang.exe to path on windows so company-clang is automatically loaded now. If I look at *clang-output* I can see that it is doing something, so it seems to work.
However it takes a very long time time generate suggestions for e.g. "dou". In the end however it will give me some options to choose from ("double" etc.). 
If I start typing the name of a variable defined in the same file however, I will never see auto-complete suggestions, whereas before having access to clang this would work.
Is this intended?

**Comment by dgutov** [comment]
`M-x company-diag`, please. And you wouldn't happen to have the problem project somewhere I can try it?

**Comment by Opioid** [comment]
Emacs 25.2.1 (x86_64-w64-mingw32) of 2017-04-24 on LAPHROAIG
Company 0.9.4

company-backends: (company-bbdb company-nxml company-css company-eclim company-semantic company-clang company-xcode company-cmake company-capf company-files
			  (company-dabbrev-code company-gtags company-etags company-keywords)
			  company-oddmuse company-dabbrev)

Used backend: company-dabbrev
Major mode: messages-buffer-mode
Prefix: ""
Completions:
  "m_materials"
 [...] many more, including the thing I'm trying to auto-complete

I'm currently trying this on a single file from a larger project. I suspect I can reproduce it with a minimal file. I will try that.

**Comment by Opioid** [comment]
On linux it feels faster and therefore more usable. But on the windows machine I'm wondering if it wouldn't be better to disable the company-clang backend and just use company. Is there a flag to control this?

**Comment by dgutov** [comment]
> Is there a flag to control this?

You remove `company-clang` from `company-backends`.

But you should try `company` from MELPA. A recent contribution should speed up `company-clang` on all OSes, and it hasn't made its way into a release yet.

**Comment by Opioid** [comment]
Thank you! 
I actually use company from MELPA. I wonder if the slow-down could also be related to clang sometimes not finding a certain header file corecrt.h. It only complains sometimes though, but in those cases the auto-suggestion just fails as far as I can tell. Maybe it would be cool to fall back to the default company auto-suggestion for those cases.

**Comment by dgutov** [comment]
When it doesn't find the correct includes, completion should be faster, if anything.

> Maybe it would be cool to fall back to the default company auto-suggestion for those cases.

Doesn't sound great to me. You either set up the backend correctly, or simply disable it and enjoy hassle-free completion using symbols from the open buffers.

**Comment by dgutov** [comment]
> I actually use company from MELPA.

Is it the most recent version?

**Comment by Opioid** [comment]
I think so, company-20171006.1442.

Regarding the correct setting of the completion backend. Is it possible to control company-clang-arguments from two different places?
I currently have a .dir-locals.el per project wich contain something like
`         (eval . (setq-local company-clang-arguments
							 (list
							  (concat "-std=c++14")
							  (concat "-I" my-project-path)
							  )
							 ))`
But I would also like to add information from init.el about where this <corecrt.h> can be found (As soon as I find that damn place).

**Comment by dgutov** [comment]
> I think so, company-20171006.1442.

Seems so.

> I would also like to add information from init.el about where this <corecrt.h> can be found (As soon as I find that damn place).

In `init.el`, you can set it inside an `eval-after-load` block. Or you can use Customize.

Then, you would modify it in dir-locals like `(setq-local c-c-a (append c-c-a ...))`.

Or you can set the whole of it in `find-file-hook`.

**Comment by Opioid** [comment]
Thanks. Turns out supplying corecrt.h just leads to another error (clang error: '_Ty' does not refer to a value). Do you happen to have some experience with getting this to run on windows?

**Comment by dgutov** [comment]
None at all, sorry.
