### ISSUE TITLE
hook for company-doc-buffer

### ISSUE THREAD

**Issue by knobo** [company-mode/company-mode#729]
I would like to have something like this, as I want to make a syntax highlighting mode for the documentation buffer- Maybe the compleation backend should also be an argument?

``` lisp
(defcustom company-doc-buffer-hook nil
  "Hook run before string is inserted in *company-documentation* buffer.
The hook is called with one argument that is the string to be inserted in
to the documentation buffer."
  :type 'hook)

(defun company-doc-buffer (&optional string)
  (with-current-buffer (get-buffer-create "*company-documentation*")
    (run-hook-with-args 'company-doc-buffer-hook string)
    (erase-buffer)
    (when string
      (save-excursion
        (insert string)))
    (current-buffer)))

```

**Comment by dgutov** [comment]
> a syntax highlighting mode for the documentation buffer

Why isn't the documentation syntax highlighted already? In your case.

**Comment by knobo** [comment]
I don't know. I use common lisp, and nobody made any syntax highlighting mode for the documentation. And *company-documentation* is just in fundamental mode.

**Comment by dgutov** [comment]
What's the backend?

**Comment by knobo** [comment]
common lisp, with company-slime

**Comment by knobo** [comment]
https://github.com/anwyn/slime-company

**Comment by dgutov** [comment]
Why not open a feature request there for it to add syntax highlighting?

**Comment by knobo** [comment]
in slime-company or company?

**Comment by dgutov** [comment]
slime-company

**Comment by knobo** [comment]
Thanx.
