### ISSUE TITLE
Emacs display fails after company activation

### ISSUE THREAD

**Issue by MageSlayer** [company-mode/company-mode#730]
Hi

It's kind of difficult to describe, but quite often right after using company popup emacs buffer becomes permanently messed up. See screenshot. No error is emitted though. Reopening file removes the issue until next time company pops up.

![emacs1](https://user-images.githubusercontent.com/583635/31765266-7f40cbfa-b4cc-11e7-8c92-9f9c5fcb91b2.png)

Tested under emacs-25.2.2 in terminal and company-mode-20171017.1638

**Comment by dgutov** [comment]
Hi!

Do you have a step-by-step reproduction scenario? Starting with `emacs -Q`, describing exact buffer contents, and so on?

I've never seen anything like what's going on on the screenshot.

**Comment by MageSlayer** [comment]
Well.
I managed to reproduce the issue in "emacs -Q -nw" mode.
However it is only seen when RLS/lsp-mode is turned on.
I think that's something to do with lsp-rust/lsp-mode modes. 
They are really unstable and mess things up.

I guess this issue can be closed as invalid.
Thanks anyway.

**Comment by dgutov** [comment]
Could you file a report there?

**Comment by MageSlayer** [comment]
Yes. 
This time I am still trying to reproduce it :)

**Comment by MageSlayer** [comment]
Looks like it's related to https://github.com/emacs-lsp/lsp-mode/issues/132
