### ISSUE TITLE
Unicode symbol in company popup

### ISSUE THREAD

**Issue by jbharat** [company-mode/company-mode#732]
Hi. I am not sure if it is a bug or not. I am using spacemacs. 

In the company popup sometimes I see this unicode symbol(image attached). This moves all the text below it. Once the popup closes, the text moves back. I understand that this is caused by the unicode symbol in my font. I want to disable showing unicode symbols. Any help to debug this would be great. 
![screenshot-from-2017-10-30-21-53-45](https://user-images.githubusercontent.com/6837979/32199924-053ff51e-be23-11e7-9ae5-8a146f001206.png)

I use the same setup on mac and ubuntu and have observed this issue on both. Emacs version is 25.3. Using Ubuntu Mono font.

If this issue is not relevant to company-mode and is because of some other package, please let me know. I will close this. Thank you.

**Comment by dgutov** [comment]
> Any help to debug this would be great

Try the spacemacs gitter channel?

Oh whichever backend gives you these completions. Call `M-x company-diag` to find it (or look at the mode-line, although I'm not sure if company's entry is hidden in spacemacs).

**Comment by jbharat** [comment]
Thanks. I had posted on spacemacs gitter channel already. Didnt get any response. I will check company-diag.
