### ISSUE TITLE
Documentation popup

### ISSUE THREAD

**Issue by vemv** [company-mode/company-mode#733]
Hi!

I have taken a look at https://github.com/company-mode/company-mode/issues/68 , https://github.com/company-mode/company-mode/issues/138 , https://github.com/company-mode/company-mode/issues/561 .

I also took the time to try out https://github.com/expez/company-quickhelp/ . It works (after a painful debug session: https://github.com/railwaycat/homebrew-emacsmacport won't display pos-tip tooltips at all). Even though it does, it has several issues on OSX:

* No styling is applied
* Bad positioning if `company` was invoked near buffer boundaries
* Bad positioning on full screen mode.
* Docstring popups appear even if there are no useful docstrings (I don't want to see a docstring called `No documentation found`)
* Silently unsupported in `railwaycat/homebrew-emacsmacport`

All this seems to indicate that if no documentation-box facility comes from company-mode, we are condemned to use some or other hacks.

I don't know the exact reason why company-mode offers no documentation-box. Is it due to author preference (which is legit: you may prefer help buffers), complexity avoidance (you may want the whole codebase to serve as few purposes as possible), or actual layout problems?

Hopefully it's not the latter case. Intituively, if you are able to implement a widget as complex as this:

![image](https://user-images.githubusercontent.com/1162994/32284673-3df2aaea-bf28-11e7-97d6-f526d27ec38f.png)

...you are also able to stick a rectangle, next to it, containing a fixed string?

It's easy to imagine that that'd have relatively small difficulty to you.

I can understand though, as mentioned, that you may not want this feature (you owe me nothing, and I accept that!). This is especially true if one was to maintain a comprehensive feature that auto-integrated with lots of backends. But how about:

- offer an opt-in "documentation rectangle", that users can fill
- make the users' responsibility to trigger, hide, fill and update the rectangle
- rectangle could have a fixed width if that makes things easier. Again, users' responsibility to ensure the provided string appears readable/pretty.
- maybe offer some simple callbacks.

Does this sound feasible?

Cheers - Victor

**Comment by dgutov** [comment]
Hey!

> https://github.com/railwaycat/homebrew-emacsmacport won't display pos-tip tooltips at all

As a Linux user, can't really say I sympathize :)

> Is it due to author preference (which is legit: you may prefer help buffers), complexity avoidance (you may want the whole codebase to serve as few purposes as possible)

These considerations, sure (they set personal priorities).

And also the number of people helping. Which is very close to zero, especially in the area of popup rendering.

> ...you are also able to stick a rectangle, next to it, containing a fixed string?

Yeah, probably. Except the position of the rectangle will require some thought. On a more global level, it will need a sane API, a test suite, and an implementation, of course (++). There is a third-party package that does that already, but it's not in GNU ELPA (and will never be there), so company-mode cannot use it.

> Does this sound feasible?

Yes. In the sense that I can offer some guidance if you're going to do the work. Otherwise -- we'll probably have to wait for someone else to come along.

> make the users' responsibility to trigger, hide, fill and update the rectangle, ...

All this stuff will be easy to resolve, compared to the things I mentioned above (++).

**Comment by vemv** [comment]
Thanks for the input! Appreciated.

At least now I know the exact reasoning behind.

I'd sure hack on this if I had the time.

Meanwhile, I just realised that 'popup' doc is not necessarily the best or only way. Printing the doc to the minibuffer seems a robust alternative. CIDER does this, not in a way that I like, but seems easy to tweak :)

**Comment by dgutov** [comment]
> Printing the doc to the minibuffer seems a robust alternative

It's not just one or the other: a backend can both return a `meta` string to be shown in the echo area, and a `doc-buffer` with a more expansive documentation.
