### ISSUE TITLE
calling another backend with a backend

### ISSUE THREAD

**Issue by CeleritasCelery** [company-mode/company-mode#734]
I am writing a company backend that takes candidates from the fish shell. The prefix logic is fairly simple (just `company-grab-symbol`) and there are times when fish gives me no candidates, but I could get some candidates from another backend like `company-capf` or `company-files`. So inside the candidate phase I call `company-other-backend` and that does what I need. However, when I run `company-diag` it credits my backend with providing the candidates instead of any of the other ones. Is this the intended behavior?

**Comment by dgutov** [comment]
You call `company-other-backend` from inside your backend? This is unsupported behavior. It's cool if it works, but it might break in a future version with no warning.

So yes, it's intended.

**Comment by CeleritasCelery** [comment]
Didn't know that. Guess I will approach this differently then. Is there a way to defer to other backends after you have returned a non-nil prefix? My concern is that I have no simple way to know if I will get candidates until I call a fish sub shell, which is too slow for `prefix` command. I saw there is also `company-begin-backend` but I assume I shouldn't be using that to call another backend either.

**Comment by dgutov** [comment]
The main idea is that you just don't do that (the backends are supposed to be smart and exhaustive). If the user wants to invoke `company-other-backend`, let them do that. It's an interactive function.

There are various ways to delegate to another backend, of course, but `company-diag` still won't know that you're doing that.

**Comment by CeleritasCelery** [comment]
Fair enough. putting `company-diag` aside, where can I read about the "various ways to delegate to another backend"? Are there any non-interactive ways?

**Comment by dgutov** [comment]
Plain Elisp stuff, for instance. If you know the name of a backend function, you can call it.

If you necessarily want the next backend configured by the user, you might have to duplicate `company-other-backend` a bit. But there's no need to call `company-begin-backend`.

**Comment by CeleritasCelery** [comment]
Thank you
