### ISSUE TITLE
Carriage return characters in documentation popup

### ISSUE THREAD

**Issue by sebhofer** [company-mode/company-mode#736]
I'm using company-mode with spacemacs to edit F# files under Windows 10. I keep seeing carriage return characters (^M) and sometimes HTML special entities (such as &gt) in the documentation popup. Is there a way to filter those out? (Or is company-mode not the right place to do this anyway?)

This is not a huge issue, but it can sometimes make the documentation hard to read. I'd be happy for advice!

**Comment by dgutov** [comment]
> Or is company-mode not the right place to do this anyway?

Probably not. But the appropriate place to report it depends on a couple of things.

What's the used backend?

Do you see the same problem when the documentation buffer is displayed in a window (command normally bound to `C-h`)?

**Comment by dgutov** [comment]
https://github.com/fsharp/emacs-fsharp-mode/issues
