### ISSUE TITLE
Company semantic activated when editing commentary

### ISSUE THREAD

**Issue by tautologyclub** [company-mode/company-mode#739]
This happens an awful lot, enough for me to consider disabling semantic in C-mode. But of course I'd rather have an actual solution because it does make life a lot easier otherwise.

When I edit a block comment in a c-file, it can go something like this:

    /* This function reads a hardware port. */

and when I punctuate "port", emacs freezes and the echo-area says

    Parsing symmetric.hpp (LL)...done

etc. So I guess it's trying to find a struct called 'port' and give me completion candidates for it, by parsing the entire boost library. This makes the buffer inaccessable for up to a minute before the parser randomly quits. Everytime I punctuate a word in a comment.

So first of all, I would like completion disabled in comment fields. Is this doable? Second of all, I'm curious why semantic goes through the entire boost library to look for completions instead of just my included files -- but I guess that question is outside the scope of company-semantic.

**Comment by dgutov** [comment]
`company-semantic` does check `(not (company-in-string-or-comment))`. Could you try edebug-ing it?

**Comment by tautologyclub** [comment]
Ps, the second part has nothing to do with semantic btw, it was company-gtags that was the culprit... I removed it from the backends list and the problem went away. So the problem is solved for ME, but if company-gtags is actively maintained, that's certainly something for them to look into...

**Comment by dgutov** [comment]
Which part?

`company-gtags` checks `(not (company-in-string-or-comment))` as well.

**Comment by tautologyclub** [comment]
It's version 0.8.1 if that makes a difference, but as soon as I removed company-gtags from backends list, the behaviour stopped.

**Comment by dgutov** [comment]
> It's version 0.8.1 if that makes a difference

Not really. That version still includes the check.

If you'd like to help solving this, a step-by-step reproduction scenario would be the first step.

**Comment by tautologyclub** [comment]
Sure thing. The behaviour just returned, even with gtags disabled. Shouldn't this be a buffer-local company setting tho, not something that is set for each backend...?

There's nothing to reproduce really, just any time I edit commented or quoted stuff in a .c/.h buffer some parser kicks in. I will try to check the profiler for the culprit. I'm not that experienced with debugging elisp so any pointers are welcome.

**Comment by dgutov** [comment]
> Shouldn't this be a buffer-local company setting tho, not something that is set for each backend...?

Some backends do work in comments. Dictionary-based, for instance.

> any time I edit commented or quoted stuff in a .c/.h buffer some parser kicks in

That sounds like Semantic. Try disabling `semantic-mode`, for instance. Then look into `semantic-idle-scheduler-mode`, maybe.

**Comment by tautologyclub** [comment]
So I ran the profiler and  typed "socket." in my header file. I get this really long chain of calls that start with company-idle-begin. Eventually it ends up with company-capf calling semantic-symref-something. But I thought I had semantic-idle-scheduler-mode enabled. This is in my init file anyway:

    (add-to-list 'semantic-default-submodes 'global-semantic-idle-scheduler-mode)
    (add-to-list 'semantic-default-submodes 'global-semanticdb-minor-mode)

But actually it wasn't enabled for whatever reason. Trying enabling it "manually" in my init file, we will see how it works.

**Comment by dgutov** [comment]
@tautologyclub Any news?
