### ISSUE TITLE
Proportional font support

### ISSUE THREAD

**Issue by nickmccurdy** [company-mode/company-mode#741]
When rendered with a proportional/variable-pitch font, lines in the company completion display do not align because they're dependent on the font width being consistent (monospace).

In [Proportional fonts break company overlays](https://emacs.stackexchange.com/questions/35891/proportional-font-breaks-company-overlays), it is suggested that ad-hoc frames should be used for popups, which may need to be an internal change in Emacs. Would a feature like this be possible, and if not, what can we do to help get this in Emacs core?

**Comment by dgutov** [comment]
> what can we do to help get this in Emacs core?

Write to the emacs-devel mailing list. Probably have to get into writing C code.

I see this feature pop up in discussions from time to time. I think Martin Rudalics is working on it, but the progress seems slow.

**Comment by nickmccurdy** [comment]
Thanks, that's what I thought unfortunately. We can leave this open if you want to track the issue upstream or close it if you feel it's off topic to this project.

**Comment by dgutov** [comment]
https://github.com/tumashu/company-childframe/ is our current response to this question.

**Comment by fehmud** [comment]
> https://github.com/tumashu/company-childframe/ is our current response to this question.

Unfortunately, that link is broken. Here is an alternative: [https://github.com/ilohmar/company-childframe](https://github.com/ilohmar/company-childframe).

Thanks for maintaining Company.

**Comment by dgutov** [comment]
Erm, that link was indeed broken. But yours is outdated as well.

This is the package, with its new name: https://github.com/tumashu/company-posframe/

**Comment by carschandler** [comment]
I'd love to be able to use proportional fonts for this!

**Comment by dgutov** [comment]
@carschandler This should work now on the master branch (can be install from MELPA). See the linked NEWS entry for the caveat.

**Comment by carschandler** [comment]
Cool! I'll try it out. Thanks!

**Comment by carschandler** [comment]
@dgutov it's working really well! Bravo. I did need to change my line number fonts to be monospaced as well for it to look right (seemed to be a side-effect of the line numbers disappearing once completion menu shows)

**Comment by dgutov** [comment]
> seemed to be a side-effect of the line numbers disappearing once completion menu shows

Yes, it's kinda tricky because the numbers disappear but the spaces are still rendered by Emacs's internals, not the popup rendering code.
