### ISSUE TITLE
Feature Request: Add company-quit (code provided) bound to RET.

### ISSUE THREAD

**Issue by rswgnu** [company-mode/company-mode#743]
In using company, I found I was always pressing RET to quit out of it, whether or not I had selected a completion yet and sometimes when a partial completion had been done.  If I had not selected a completion from the popup list, I want to exit and leave just what had been completed in the buffer, not to have more completion done.  If I select a completion, then the full completion should be inserted when I press RET.  This code does that and seems like a sensible default to have, so I'd suggest adding it if you agree.

If you want a full completion, then just press M-TAB or TAB until you get there.

```
(defun company-quit ()
  "Insert any selected completion and quit completing."
  (interactive)
  (when (and company-selection-changed company--manual-action
             (if (boundp 'company-tng--overlay) company-tng--overlay company-preview-overlay))
    (company--insert-candidate
     (nth company-selection company-candidates)))
  (company-cancel))
```

**Comment by dgutov** [comment]
Sorry, I don't think this will work for the default UI.

If you're going to use it in conjunction with company-tng, let's see if the other users of it agree first.

**Comment by rswgnu** [comment]
On Fri, Dec 1, 2017 at 6:30 AM, Dmitry Gutov <notifications@github.com>
wrote:

> Sorry, I don't think this will work for the default UI.
>
​Ok, it would just be nice to understand what the issues are.​
​​
​One question is why by default do you want to complete more than has
already been completed if no completion is selected and your press return?​

> If you're going to use it in conjunction with company-tng, let's see if
> the other users of it agree first.
>
​Sure.  I am loving this setup (I complete only when a completion key is
pressed) and find exiting the popup with RET works really well.  If a
completion was selected, it is inserted.  If not, none is.  Common
completions are already inserted prior to pressing return, so they work too.

**Comment by dgutov** [comment]
> why by default do you want to complete more than has already been completed if no completion is selected

In the default UI, the first completion is selected by default. There's no way to have "no completion is selected".

**Comment by rswgnu** [comment]
On Fri, Dec 1, 2017 at 1:43 PM, Dmitry Gutov <notifications@github.com>
wrote:

> why by default do you want to complete more than has already been
> completed if no completion is selected
>
> In the default UI, the first completion is selected by default. There's no
> way to have "no completion is selected".
>
​So if someone is idling on a partially typed identifier and doesn't want
to do any completion they have to type a space and delete the space or
press C-g to abort rather than the more natural RET to exit without
completing, right?  I just found that very unergonomic and am surprised
others have not said the same.

Visually, the first candidate does not appear selected when the popup first
appears, so that is another inconsistency that disappears under my
suggested model.
I guess if you explicitly asked for completion you might want a default
selection but that would not be true when completions appear after an idle
timeout.

Again, I have things working well for me now, I just thought we could
improve the out-of-the-box usability, especially for less experienced users.

**Comment by dgutov** [comment]
> press C-g to abort rather than the more natural RET

Yes.

> Visually, the first candidate does not appear selected when the popup first appears

It does. Only with company-tng it doesn't.

> Again, I have things working well for me now, I just thought we could improve the out-of-the-box usability, especially for less experienced users.

I'm glad, and thanks. :-)

**Comment by nikital** [comment]
I'm coming over from the discussion on #706. To summarize, there seems to be some colliding package that might trigger a completion while company-tng is in it's "unselected" state, creating an unintuitive experience. Robert rightfully thought that it's the default experience and wanted to make this modification....

If @rswgnu posts a minimal config to reproduce it, I might be able to provide a better default integration (For example advicing `company-complete-selection` to make it aware of the unselected state when company-tng is active).

**Comment by rswgnu** [comment]
On Fri, Dec 8, 2017 at 3:12 PM, Nikita Leshenko <notifications@github.com> wrote:
> I'm coming over from the discussion on #706. To summarize, there seems to be some colliding package that might trigger a completion while company-tng is in it's "unselected" state, creating an unintuitive experience. Robert rightfully thought that it's the default experience and wanted to make this modification....

​Yes.​

> If ​​@​​rswgnu posts a minimal config to reproduce it, I might be able to provide a better default integration (For example advicing company-complete-selection to make it aware of the unselected state when company-tng is active).

​I have now tested a minimal configuration and have found the following:


```
emacs -Q
load company and company-tng
(global-company-mode 1)
(company-tng-configure-default)
```

Then in the *scratch* buffer in lisp-interaction-mode, I type:
(ba

Step 1: I then press TAB ​and nothing happens.  I run {M-x company-complete RET} and the completions popup appears as expected.
Step 2: I press RET and get a beep and an error message.
Step 3: I press TAB and the first completion is selected.  TAB again moves through the list.
Step 4: I press RET and the selected completion is accepted and a newline is added to my buffer, putting me on the next line.

----
So here are the changes to defaults I would expect:

1. TAB should start company completion and popup the completions list in step 1.
2. After step 1, RET should quit company mode and do nothing else.
3. In step 4, RET should quit company mode, actually insert the completion in the buffer, and do nothing else.
   Why would I want to go to a new line after completing something?
   One often wants to type something after the completion.

My company configuration now does all of this.  You can see it in this gist.  It is ashame it has to be so extensive.  Maybe you can help shorten it.

Bob

**Comment by rswgnu** [comment]
The gist is here:  https://gist.github.com/rswgnu/85ca5c69bb26551f3f27500855893dbe

**Comment by jojojames** [comment]
* I do believe TNG came out of wanting a more 'ycmd' like experience so some of my comments will appeal to that original mindset.

See https://github.com/company-mode/company-mode/issues/526 and
https://github.com/company-mode/company-mode/issues/216.

> Step 1: I then press TAB ​and nothing happens. I run {M-x company-complete RET} and the completions popup appears as expected.

Do you expect something to happen when you press TAB? (I only ask because in the next sentence you write 'as expected' for the M-x command.)
What do you expect TAB to do if you haven't typed anything yet? Will it insert TAB (4 spaces/etc) or start company-complete?

I'll insert your proposal inline so it's easier to read.

> TAB should start company completion and popup the completions list in step 1.

Here are reasons why I don't think it makes sense

1. YCMD does not manually start if you press TAB.
2. If company rebinds this by default, it would be very intrusive, in my opinion. (How do I insert 4 spaces now?)

> Step 2: I press RET and get a beep and an error message.

I do think there's a bug (or at least unexpected behavior) here but it's that a new line should be inserted and not RET completing the candidate.
I think our expectations are different here but the result is the same (the beep and error message). I think my expectation is more in line with company-tng though.

> After step 1, RET should quit company mode and do nothing else.

Please, no. :( The whole purpose of TNG (at least in my mind) is so that RET is not bound!

YCMD does not bind RET, by pressing TAB, you are selecting the candidate already.

> Step 3: I press TAB and the first completion is selected. TAB again moves through the list.
> Step 4: I press RET and the selected completion is accepted and a newline is added to my buffer, putting me on the next line.

Sounds about right to me..

> In step 4, RET should quit company mode, actually insert the completion in the buffer, and do nothing else.

Strongly against this.

> Why would I want to go to a new line after completing something?

The TAB *is* the completion. By the time you've pressed RET, your completion is technically done. That's how YCMD does it.

I'm actually somewhat curious in company-tng's value-add for you @rswgnu. It seems like you can accomplish what you're looking for with the
other company-frontends and rebinding TAB, RET yourself.

**Comment by dgutov** [comment]
> Strongly against this.

Then that settles this. Sorry, Robert. You still can modify the behavior for yourself, though.

(Please continue with the conversation if you want, though)

**Comment by rswgnu** [comment]
On Mon, Dec 11, 2017 at 8:59 AM, Dmitry Gutov <notifications@github.com>
wrote:

> Strongly against this.
>
> Then that settles this. Sorry, Robert. You still can modify the behavior
> for yourself, though.
>
> (Please continue with the conversation if you want, though)
>
​No problem, will do.
​

**Comment by rswgnu** [comment]
jojojames wrote:

> I do believe TNG came out of wanting a more 'ycmd' like experience so some of my comments will appeal to that original mindset. See #526 and #216.

I wrote:
>> Step 1: I then press TAB ​and nothing happens. I run {M-x company-complete RET} and the completions popup appears as expected.

> Do you expect something to happen when you press TAB? (I only ask because in the next sentence you write 'as expected' for the M-x command.)
What do you expect TAB to do if you haven't typed anything yet? Will it insert TAB (4 spaces/etc) or start company-complete?

I expect it to do the company-equivalent of indent-for-tab-command, that is indent when appropriate, move to the indentation or complete.

> I'll insert your proposal inline so it's easier to read.

>> TAB should start company completion and popup the completions list in step 1.

> Here are reasons why I don't think it makes sense
> YCMD does not manually start if you press TAB.
> If company rebinds this by default, it would be very intrusive, in my opinion. (How do I insert 4 spaces now?)

Same way as you would with the original Emacs TAB binding.

>> Step 2: I press RET and get a beep and an error message.

> I do think there's a bug (or at least unexpected behavior) here but it's that a new line should be inserted and not RET completing the candidate.

Let's be clear about this.  I only want RET to insert a completion if tng has added an overlay in the buffer reflecting selection of a completion already.  If there is no such overlay, then RET should just terminate completion and insert nothing, so it would be similar to having RET set to ignore in this case.

Suppose company/tng inserts a partial completion of a symbol in the buffer and then you want to terminate completion and start typing the rest of the symbol.  How do you do it?  If you press SPC, then you have to remove the SPC.  Same if RET inserts a character.  With my technique, you just press RET and type, no extra keys.

> I think our expectations are different here but the result is the same (the beep and error message). I think my expectation is more in line with company-tng though.

I guess so, I just don't see how it is better, though.

>> After step 1, RET should quit company mode and do nothing else.
Please, no. :( The whole purpose of TNG (at least in my mind) is so that RET is not bound!

Please explain what advantage that provides besides being able to immediately insert a newline.
With the default TNG configuration, after a PARTIAL completion is done, how to you end completion and leave the completion in the buffer?

> YCMD does not bind RET, by pressing TAB, you are selecting the candidate already.

But it is not yet really inserted in the buffer yet so that C-g can abort, right?

>> Step 3: I press TAB and the first completion is selected. TAB again moves through the list.
>> Step 4: I press RET and the selected completion is accepted and a newline is added to my buffer, putting me on the next line.

> Sounds about right to me..

But more often than not after completing a symbol you want to keep typing on the same line, so this is not good.

>> In step 4, RET should quit company mode, actually insert the completion in the buffer, and do nothing else.

> Strongly against this.

Why though?  Tell me what pros and cons you see rather than just what you like and dislike.

>> Why would I want to go to a new line after completing something?

>The TAB is the completion. By the time you've pressed RET, your completion is technically done. That's how YCMD does it.

I know nothing about YCMD and am concerned only with tng at this point.  If the completion were completely done then the popup would disappear after TAB selected a full completion but that is not how it works is it?  You still need a key to terminate the popup.  That's much of what we are discussing, how things work when terminating company mode.

> I'm actually somewhat curious in company-tng's value-add for you @rswgnu. It seems like you can accomplish what you're looking for with the other company-frontends and rebinding TAB, RET yourself.

Maybe.  I like TAB to start completing at appropriate times and for TAB to cycle through completions in the list as well as inserting the completion into the buffer.  But I still want to use RET as my company mode popup termination key.  I don't know why the two seem incompatible.

Unforunately, the commentary in the company-tng.el file neglects to say how one finalizes completion and dismisses the completion popup.  Maybe @nikital could fix that and then we would have a baseline from which to discuss how to best do it.

**Comment by jojojames** [comment]
> *I know nothing about YCMD* and am concerned only with tng at this point. If the completion were completely done then the popup would disappear after TAB selected a full completion but that is not how it works, is it? You still need a key to terminate the popup. That's much of what we are discussing, how things work when terminating company mode.

It really feels like this is the biggest point. It seems you misunderstand the YCMD approach to completion and its tradeoffs. This is detailed in the above links I mentioned. You can always load up vim with ycmd and try it out. The behavior matches almost exactly. Most users coming from vim want and expect this kind of completion behavior.

I'm just curious what your use case for tng is if you're basically subverting all the benefits of 'tab and go'.

Here are some snippets of pros:

@nikital
```
Regarding RET, I agree with Aaron that having it unbound is very important, especially in languages such as lisp or python that have no semicolons at the end of the line, which makes it likely to have the tooltip active when you are at the end of the line and you want RET to actually insert a new line.
```

@aaronjensen
```
@rswgnu I believe you're describing (more or less) the original company behavior. company-tng was requested and built by people who want exactly what you are saying you don't want. We want to be able to have the selection of the item (via tab/shift-tab) be the confirmation. The extra keypress to select is specifically what we don't want.

It sounds like you maybe want some hybrid, but I'm not sure exactly what it is that you want that the original company behavior does not support.
```

```
That's right, and this is exactly the behavior that all of who asked for and contributed to company-tng wanted.

Again, it sounds like you want a hybrid, specifically you want to be able to press RET when nothing has been selected to dismiss company-mode or to (actually) insert the candidate if one is selected without also inserting a newline. It looks like you wrote a function to do what you want. Perhaps if you want to pull request that function @dgutov may be interested in having it built-in so others could bind it to whatever they wanted, if they wanted to be used in conjunction with company-tng. I would say it should not be the default, however.
```

Last point:

I'm not sure a conversation about changing the defaults of a feature *designed* to match another feature (ycmd) without knowing how the original feature (ycmd) works is going to end well. 

Last point#2:

I do think you can get what you want with vanilla company and tweaking the frontends used. It seems like what you're describing is what company supports out of the box.

I'll like a snippet from ycm.

https://valloric.github.io/YouCompleteMe/

```
First, realize that no keyboard shortcuts had to be pressed to get the list of completion candidates at any point in the demo. The user just types and the suggestions pop up by themselves. If the user doesn't find the completion suggestions relevant and/or just wants to type, they can do so; the completion engine will not interfere.

When the user sees a useful completion string being offered, they press the TAB key to accept it. This inserts the completion string. Repeated presses of the TAB key cycle through the offered completions.

If the offered completions are not relevant enough, the user can continue typing to further filter out unwanted completions.
```

**Comment by rswgnu** [comment]
Thanks for the detailed response @jojojames.

I see that TNG and I guess YCMD are designed to let you press TAB to complete and then continue typing any self-inserting character after full completion has been done to both dismiss the completion popup and to insert the character.  So you don't think of having a company-quit command because this is combined with the self-insertion function.  This has the advantage that you just keep typing after a completion is found.

However, there are downsides to this as well, I believe:

1. No good way to end completion with a partial completion and then type the rest manually.  How do you do this?

2. Mistyping the wrong self-inserting character ends completion and you must restart it.

If company-mode behaved as I wanted out of the box, I would not have had to produce such a long configuration for it (linked to in an earlier message) to make it work more intuitively.  I think your thought that I want a hybrid approach of default company-mode and TNG is right.  I think the only thing I am changing about TNG is adding RET to immediately quit out of completion and leave whatever completion has been inserted.

I have things configured as I want and have shared this configuration.  If everyone is happy with the existing TNG and company-mode out-of-the-box, then that is good and fair enough.

**Comment by aaronjensen** [comment]
> No good way to end completion with a partial completion and then type the rest manually. How do you do this?

`C-g` does this for me if you really want to dismiss the popup. That said, so does just typing the rest manually. There's no need to end the completion, you just type. That's the point.

> Mistyping the wrong self-inserting character ends completion and you must restart it.

I've been annoyed by this before, but I don't want to have backspace always pop the completion. I typically just backspace again over a known good character and retype it. One could also bind something to `company-complete`. Do you have a suggestion to improve this while keeping everything else about company-tng?

**Comment by rswgnu** [comment]
On Thu, Dec 14, 2017 at 12:19 PM, Aaron Jensen <notifications@github.com>
wrote:

> No good way to end completion with a partial completion and then type the
> rest manually. How do you do this?
>
> C-g does this for me if you really want to dismiss the popup.
>
​But that removes the partial completion, which is not what you want in
this instance.​

> That said, so does just typing the rest manually. There's no need to end
> the completion, you just type. That's the point.
>
​Yes, I mentioned that as one benefit of the approach.​


> Mistyping the wrong self-inserting character ends completion a
> ​​
> nd you must restart it.
>
> I've been annoyed by this before,
>
​Ok, someone else sees an issue here.​

> ​​
> but I don't want to have backspa
> ​​
> c
> ​​
> e
> ​​
> ​​
> ​​
> a
> ​​
> l
> ​​
> w
> ​​
> a
> ​​
> y
> ​​
> s
> ​​
> ​​
> p
> ​​
> o
> ​​
> p
> ​​
> ​​
> ​​
> t
> ​​
> h
> ​​
> e
> ​​
> ​​
> c
> ​​
> o
> ​​
> m
> ​​
> p
> ​​
> l
> ​​
> e
> ​​
> t
> ​​
> i
> ​​
> o
> ​​
> n
> ​​
> .
>
> You mean re-enable completion, I take it.

> ​​
> I typically just backspace again over a known good ch
> ​​
> aracter and retype it.
>
> So this is one scenario where effort is increased with TNG.

> One could also bind something to company-complete.
>
​To do what?​


> Do you have
> ​​
> a sugges
> ​​
> tion to improve this while keeping everything else about company-tng?
> ​​
>
> ​Binding RET to a new company-quit function was my idea.  It does not
prevent you from ending completion with other self-insert characters.  It
just always gives you a single, non-abort key out of the completion popup.
For the 50% or less times that you'd immediately want to add a newline to
your buffer, you then have to press RET twice.  Not much effort.

Now there is a more extensive idea that wrongly typed characters would not
terminate completion but I understand that that is a no-go for TNG users
based on their fundamental goal.

Bob
​

**Comment by aaronjensen** [comment]
> ​But that removes the partial completion, which is not what you want in
> this instance.​

It *is* what I want. I only hit C-g when I don't want a completion. Otherwise I just keep typing or move the point or whatever.

> ​To do what?​

Re-open the completion dialog.



> For the 50% or less times that you'd immediately want to add a newline to
> your buffer, you then have to press RET twice.  Not much effort.

This is where we differ. I have never thought to myself, "man, that completion dialog is really distracting. I really wish I could close it and leave my point exactly where it is so that I can examine my code without it in the way." I have, however, thought to myself, "I'm so sick of having to press enter to select a completion that I'm going to learn elisp and write a way to do it the way I want to." 

> Now there is a more extensive idea that wrongly typed characters would not
> terminate completion but I understand that that is a no-go for TNG users
> based on their fundamental goal.

I'd be happy with something that would automatically reopen the popup if I backspace the "wrongly typed character" that didn't also open a popup every time I backspaced anything else. If there's a way to do that I think that would still keep to the spirit of TNG and I would vote for incorporating.

**Comment by rswgnu** [comment]
> On Dec 14, 2017, at 10:19 PM, Aaron Jensen <notifications@github.com> wrote:
> 
> ​But that removes the partial completion, which is not what you want in
> this instance.​
> 
> It is what I want. I only hit C-g when I don't want a completion. Otherwise I just keep typing or move the point or whatever.
> 

I was talking about when you wanted a partial completion but I get what you mean.
> For the 50% or less times that you'd immediately want to add a newline to your buffer, you then have to press RET twice. Not much effort.
> 
> This is where we differ. I have never thought to myself, "man, that completion dialog is really distracting. I really wish I could close it and leave my point exactly where it is so that I can examine my code without it in the way." I have, however, thought to myself, "I'm so sick of having to press enter to select a completion that I'm going to learn elisp and write a way to do it the way I want to."
> 
Glad you scratched your itch.
> Now there is a more extensive idea that wrongly typed characters would not terminate completion but I understand that that is a no-go for TNG users based on their fundamental goal.
> 
> I'd be happy with something that would automatically reopen the popup if I backspace the "wrongly typed character" that didn't also open a popup every time I backspaced anything else. If there's a way to do that I think that would still keep to the spirit of TNG and I would vote for incorporating.
> 
It could certainly be possible.  Emacs can accommodate all.

**Comment by nikital** [comment]
I just wanted to note that I don't understand what you mean by "partial completion". In the default configuration company-tng would insert the entire completion candidate on each TAB, so it's not clear to me how you would get a partial completion.

I'm asking because company-tng is young and I want to make sure that the inconvenience you're experiencing isn't due to some bug in company-tng. Also please make sure you applied #748, it could affect you since you initiate the completion explicitly on TAB.

**Comment by dgutov** [comment]
BTW,`company-require-match` can be a good way to *avoid* the "I mistyped and the popup disappeared" problem.

**Comment by rswgnu** [comment]
On Fri, Dec 15, 2017 at 10:14 AM, Nikita Leshenko <notifications@github.com> wrote:
I just wanted to note that I don't understand what you mean by "partial completion". In the default configuration company-tng would insert the entire completion candidate on each TAB, so it's not clear to me how you would get a partial completion.

​For testing, assign company-complete to TAB.  Then in your *scratch* lisp interaction buffer on a newline type:

(bac

and press TAB.  You should see:

(back

in your buffer with the list of full completions that start with 'back' in the completions popup.  In such cases, sometimes I would want to quit and type the rest myself or enter my own as yet unbound symbol.​

> I'm asking because company-tng is young and I want to make sure that the inconvenience you're experiencing isn't due to some bug in company-tng. Also please make sure you applied #748, it could affect you since you initiate the completion explicitly on TAB.

Yes, thanks, I updated to apply that commit.  @dgutov your idea to utilize company-require-match does not work in company-tng mode because it allows any self-inserting-character that does not match to terminate company-mode, overriding this setting.  I think the setting is only relevant with tng when first invoking completion but @nikital knows better.

I do not think there is a bug in company-tng or company but just that the defaults could use some basic improvements.  Please see my config at [rsw-company-config](https://gist.github.com/rswgnu/85ca5c69bb26551f3f27500855893dbe#file-rsw-company-config-el) for any ideas.

**Comment by nikital** [comment]
OK, I see what you mean by partial completion. I just tried your config on a vanilla Emacs with the latest company. Assuming I wanted to call the yet-undefined `(backpack)`.
1. Typed `(bac`
2. Pressed TAB (bound to company-complete)
3. Got `(back` with the tooltip open
4. Typed `pack)` with the tooltip still open, the result was `(backpack)` and the tooltip disappeared as soon as I started typing.

Assuming we change company-tng so that RET will dismiss the tooltip. Would your flow look like this?
1. `(bac`
2. TAB
3. `(back` with tooltip
4. RET to dismiss the tooltip
5. `pack)`

Looks like the same result but with an extra keystroke (RET). Why would you want to dismiss the tooltip in this concrete example? In company-tng's mindset if you don't need the tooltip you just ignore it's existence and continue typing, it will either disappear or offer you more relevant suggestions as you keep typing.

**Comment by rswgnu** [comment]
Yes, the flow would look as you describe.  Unlike one other person, I find the tooltip very distracting if I am no longer looking for completions, so I prefer to type without it there at that point.  I want one key that I can press that I always know will dismiss the completions.

It is not bad the way you have things.  I think it was more troublesome when I first tried company-mode without tng and since it had the require completion flag set, I couldn't get out without adding a full completion or aborting, neither of which were desired.

I'm still trying to get company and jedi to complete really well in Python.  Again, it is a case of out-of-the-box behavior just not performing well because the overall solution probably hasn't been tested much.

**Comment by nikital** [comment]
> I want one key that I can press that I always know will dismiss the completions.

C-g, like a lot of people suggested? If you don't like it, maybe bind ESC? Any other non-self-inserting key?

You said earlier that C-g removes the partial completion for you, but I just tried it with your config and it doesn't...
1. `(bac`
2. TAB
3. `(back` with tooltip
4. `C-g`, the tooltip disappears, `(back` remains
5. `pack)`

If you **specifically** want RET and nothing else to dismiss the tooltip, I'm sorry but I don't think it's a reasonable default given company-tng's mindset of not interfering with self-inserting keys.

**Comment by rswgnu** [comment]
C-g removes any completion produced by the popup, so I can use that to simply dismiss the completion popup.  I am fine with other keys dismissing the completion popup but I'd like return to do it without having to type a space or add a newline.  I think we have resolved that this will not be the default in TNG but it is easy enough for me to use it.

**Comment by Lokdex** [comment]
> C-g, like a lot of people suggested? If you don't like it, maybe bind ESC? Any other non-self-inserting key?

Sorry to revive this, but I'm just going through making a config since I am starting to use emacs full time, and was just wondering how to properly bind ESC to close the pop up of the completion. I tried all the methods I know and was able to find, but none of them worked. Perhaps you could share an insight on this? Thanks in advance.

**Comment by dgutov** [comment]
`ESC` is indeed difficult to bind. It seems to be hardwired to act as `Meta`.

Maybe some others will have better suggestions, but I'd say this question would be better addressed to either the Emacs Help or the Emacs Devel mailing lists.

**Comment by Lokdex** [comment]
Well... I truly don't now know how much I am "breaking" emacs workflow, or how damaging this may be, but I found out you can actually do this:
```
(global-unset-key (kbd "<escape>"))
(global-set-key (kbd "<escape>") (kbd "C-g"))
```
And apparently it does close the company pop up, and so far its working just fine. And it even works better with whick-key, because it no longer says stuff like `C-c - ESC` is undefined. I hope it doesn't break anything... I guess time will tell. But posting it here anyway in case it helps someone like me.

**Comment by dgutov** [comment]
Nah, it's probably fine. I just haven't tried doing exactly that.

Congrats. :-)
