### ISSUE TITLE
Question about grouping backends

### ISSUE THREAD

**Issue by dieggsy** [company-mode/company-mode#744]
I recently wrote https://github.com/dieggsy/company-eshell-autosuggest, which includes a backend that grabs any input before point in eshell, and provides as a candidate the single previous history item that matches the input.

The inteded use for this was to rely on something other than company for eshell completion on `tab`, and use company solely as a mechanism for these history autosuggestions (similar to what fish shell does). In this regard it works well.

However, some may want to use company as their main completion mechanism (see https://github.com/dieggsy/company-eshell-autosuggest/issues/1), and have history suggestions as a sort of "fall back". I saw #142 and was wondering about grouping my backend with `company-capf`. I tried setting `company-backends` to `'((company-capf company-eshell-autosuggest))`, but I only get candidates from the latter if the former has candidates as well. (Note that `company-eshell-autosuggest` works on prefixes like `some input` with a space in the middle or trailing). It seems that they only work together if their prefixes are the same. 

Is that how it's supposed to work, and is there any way to group these (or similar) backends?

**Comment by dgutov** [comment]
> It seems that they only work together if their prefixes are the same

Yup! Otherwise, how would we insert the completion? To do that, we delete the current prefix and insert the completion.

For your scenario to work better, we'd have to track prefixes corresponding to each completion. I'm not saying it can't work, but it would require some redesign, at least.

**Comment by dieggsy** [comment]
@dgutov Hmm, thanks. If this is related to #426, feel free to close
