### ISSUE TITLE
Bug: Arguments to version< are reversed

### ISSUE THREAD

**Issue by rswgnu** [company-mode/company-mode#746]
This occurred in 2 places in company.el, making the test for an old version of Emacs always return true for new versions of Emacs.  In one case, this kept company-elisp from being loaded.

See the attached patch for a fix.

[company-patch.txt](https://github.com/company-mode/company-mode/files/1533324/company-patch.txt)

**Comment by dgutov** [comment]
But that's the point: we don't use `company-elisp` with newer version of Emacs.

And the new version of Emacs doesn't include margins in window-width.

What is the problem you are solving here?

**Comment by rswgnu** [comment]
On Tue, Dec 5, 2017 at 6:51 PM, Dmitry Gutov <notifications@github.com>
wrote:

> But that's the point: we don't use company-elisp with newer version of
> Emacs.
> ​​
>
> ​Then I would suggest you add what versions of Emacs utilize it in the
file's commentary section.  Could you explain what backend is used for
Elisp so I could look at it?
How would anyone know this?  Where would one look?

The problem was at one point I couldn't complete M-x commands (I would an
error: Company not enabled) so I thought I had an Elisp configuration
problem.

> And the new version of Emacs doesn't incl
> ​​
> ude margins in window
> ​​
> -width.
> ​​
>
> ​My mistake.​
​​
| ​​
What is the problem you are solving here?
​​

M-: win <TAB>

reports: Company not enabled

and won't complete.  How can I make company complete Elisp in the
minibuffer?

>

**Comment by dgutov** [comment]
> Could you explain what backend is used for Elisp so I could look at it?

`company-capf`.

> How would anyone know this? Where would one look?

**Comment by dgutov** [comment]
> How can I make company complete Elisp in the minibuffer?

It just doesn't work in the minibuffer, sorry. We don't know how to paint the popup when the minibuffer is active.

**Comment by rswgnu** [comment]
On Tue, Dec 5, 2017 at 7:52 PM, Dmitry Gutov <notifications@github.com>
wrote:

> Could you explain what backend is used for Elisp so I could look at it?
>
> company-capf.
>

​The word Lisp or Elisp does not appear once in that file.  There is no
commentary in the file.  At least a few sentences about what each file does
and what it applies to would help and would
probably take less than an hour to write.

| How would anyone know this? Where would one look?

I am just pointing out some things that might reduce the number of
questions you get.
Thanks for your response.

Bob

**Comment by dgutov** [comment]
It's not elisp-specific. See also the mention of `CAPF` on the home page: http://company-mode.github.io/

**Comment by rswgnu** [comment]
On Tue, Dec 5, 2017 at 7:53 PM, Dmitry Gutov <notifications@github.com>
wrote:

> How can I make company complete Elisp in the minibuffer?
>
> It just doesn't work in the minibuffer, sorry.
>
​Ok.  I would note that prominently in the README if it is not there
already as most people would be looking for that as a builtin feature.​


> W
> ​​
> e don't know how to paint the popup when the minibuffer is active.
> ​​
>
> ​OK, then I need to figure out how to stop company-mode from preventing
standard completion with TAB in the minibuffer when evaluating Elisp
expressions.
Any pointers on configuration?

Bob

**Comment by rswgnu** [comment]
On Tue, Dec 5, 2017 at 8:07 PM, Dmitry Gutov <notifications@github.com>
wrote:

> It's not elisp-specific. See also the mention of CAPF on the home page:
> http://company-mode.github.io/
>
So just add this sentence in the capf file commentary:

The CAPF back-end provides a bridge to the standard
completion-at-point-functions facility, and thus can support any major mode
that defines a proper completion function, including Emacs Lisp.

Then in the company-elisp file, note in the commentary that this is used
only in Emacs versions of <VERSION> or less.  In newer versions,
company-capf is used instead.

Bob

**Comment by rswgnu** [comment]
On Tue, Dec 5, 2017 at 8:11 PM, Robert Weiner <rsw@gnu.org> wrote:

> On Tue, Dec 5, 2017 at 7:53 PM, Dmitry Gutov <notifications@github.com>
> wrote:
>
>> We don't know how to paint the popup when the minibuffer is active.
>>
>> ​​
>>
>> ​OK, then I need to figure out how to stop company-mode from preventing
> standard completion with TAB in the minibuffer when evaluating Elisp
> expressions.
>

​I have a potential solution that seems to work for me.  See if this change
could be made to company.

In order to have C-M-i use company completion in the modes its supports, I
use:

 (global-set-key [remap completion-at-point] 'company-complete)

But then trying to do completion when evaluating Elisp with M-:
triggers a company-mode user error because company-complete is called
when ​company-mode is nil.  So we just change company-complete to call
completion-at-point whenever company-mode is nil instead and then normal
completion happens in the minibuffer.

(defun company-complete ()
  "Insert the common part of all candidates or the current selection.
The first time this is called, the common part is inserted, the second
time, or when the selection has been changed, the selected candidate is
inserted."
  (interactive)
  (if company-mode
      (when (company-manual-begin)
(if (or company-selection-changed
(eq last-command 'company-complete-common))
            (call-interactively 'company-complete-selection)
  (call-interactively 'company-complete-common)
  (setq this-command 'company-complete-common)))
    (completion-at-point)))

I'll open an issue on this after you commment on it, if it is worth
pursuing.

Bob

**Comment by dgutov** [comment]
> So just add this sentence in the capf file commentary:

Added, thanks!

> So we just change company-complete to call completion-at-point whenever company-mode is nil

Not a good idea for `company-complete`, but you can do it in your own configuration. In general, though, it's not expected that users remap completion-at-point to company-complete.
