### ISSUE TITLE
company-semantic does not show struct elements

### ISSUE THREAD

**Issue by nyqvist** [company-mode/company-mode#747]
Hi!

When using company mode with semantic I get auto-completions for functions when I start to type them, but not for struct members. For example, when I enter '.' or '->' there are no auto-completions for that struct. Semantic knows about the struct and its member, and when I call the function `semantic-analyse-possible-completions` I get the possible completions as a list in another window.

Is it possible to integrate `semantic-analys-possible-completions` into company-semantic, or maybe I have missed something in my config?

I have set up company mode like this:
```
(use-package company
  :ensure t
  :init
  (setq company-backends '((company-dabbrev-code
                            company-semantic
                            company-gtags)))
  (add-hook 'after-init-hook 'global-company-mode)
  (setq company-idle-delay 0.1)
  (use-package company-quickhelp
    :ensure t
    :init
    (company-quickhelp-mode 1)))
```

**Comment by dgutov** [comment]
`company-semantic-completions` calls `semantic-analyze-possible-completions`.

If you can find what it's doing wrong, or not doing enough, please tell us.

**Comment by nyqvist** [comment]
I got it to work after I removed `company-dabbrev-code` from `company-backends`.

**Comment by dgutov** [comment]
Did `(company-dabbrev-code 'prefix)` and `(company-semantic 'prefix)` evaluate to different values in that context?

**Comment by nyqvist** [comment]
I am not sure why, but when I add `company-drabbev-code` again it is working.. So now I dont know why it was not working from the beginning, sorry.

**Comment by dgutov** [comment]
OK. Please let me know if it happens again and you have more info.
