### ISSUE TITLE
company-tooltip get offset by beacon

### ISSUE THREAD

**Issue by stardiviner** [company-mode/company-mode#755]
I have following config:
```elisp
(defun my-company-start-animation (backend)
    ;; beacon
    (let ((beacon-size 20)
          (beacon-color "cyan"))
      (beacon-blink)))
(add-hook 'company-completion-started-hook #'my-company-start-animation)
```
But the company tooltip offset by the beacon.
With some testing, in some buffers, it is not affected, and in some other buffers like git commit buffer (raise by `magit`) will be affected.
Is there a good workaround this issue?

**Comment by dgutov** [comment]
What do you mean offset? Can't reproduce, seems to be positioned fine.

**Comment by stardiviner** [comment]
Here is a screenshot:

![image](https://user-images.githubusercontent.com/378699/36058470-aa090ef4-0e5b-11e8-945f-b265d1a06855.png)

And here is my reproduct steps:
```elisp
(package-initialize)
(global-company-mode)
(beacon-mode)

;; animation effect on company completion
;; - `beacon-blink', `beacon--shine'
(defun my-company-start-animation (backend)
  ;; beacon
  (let ((beacon-size 20)
        (beacon-color "cyan"))
    (beacon-blink)))
(defun my-company-success-animation (backend)
  ;; beacon
  (let ((beacon-size 20)
        (beacon-color "green"))
    (beacon-blink)))
(defun my-company-fail-animation (backend)
  ;; beacon
  (let ((beacon-size 20)
        (beacon-color "dark red"))
    (beacon-blink)))

(add-hook 'company-completion-started-hook #'my-company-start-animation)
(add-hook 'company-completion-finished-hook #'my-company-success-animation)
(add-hook 'company-completion-cancelled-hook #'my-company-fail-animation)

;;; type (setq
```

**Comment by dgutov** [comment]
All right, can reproduce now, thank you.

Not sure what to suggest, though, aside from using company-childframe. Beacon changes how the buffer looks, and it's hard to anticipate in a general way (patches welcome, though).

Why do you need it in `company-completion-started-hook`, though? I'd think the popup is indication enough.

**Comment by stardiviner** [comment]
I see. Thanks. @dgutov
