### ISSUE TITLE
Can not detect the user defined function and words in Lisp 

### ISSUE THREAD

**Issue by LuhengStat** [company-mode/company-mode#757]
I am changed form auto complete to company mode, and found it is more user friendly and
fast. However, when I write the Lisp codes, the company mode can not detect the newly defined function and the words in the page. How to add this feature? Thanks.

**Comment by dgutov** [comment]
I think you're talking about a function that's written, but not defined.

To "define" it, evaluate its definition with `C-M-x`.

**Comment by LuhengStat** [comment]
Yes, Could the company mode detect the function that just written without load it?

**Comment by dgutov** [comment]
You can use `company-dabbev-code` for that.

**Comment by LuhengStat** [comment]
Thanks.
