### ISSUE TITLE
wrong-type-argument arrayp nil

### ISSUE THREAD

**Issue by sebastiencs** [company-mode/company-mode#758]
When using `company-lsp`, I often get this error. 
I'm not sure if the error comes from `company-lsp` or `company-mode`
```
Debugger entered--Lisp error: (wrong-type-argument arrayp nil)
  replace-regexp-in-string("\\([^[:graph:] ]\\)\\|\\(﻿\\)\\|[[:multibyte:]]" #f(compiled-function (match) #<bytecode 0x1884b01>) nil)
  company--clean-string(nil)
  company--create-lines(0 32)
  company-pseudo-tooltip-show(15 24 0)
  company-pseudo-tooltip-show-at-point(276 0)
  #f(compiled-function (command) "`company-mode' frontend similar to a tooltip but based on overlays." #<bytecode 0x1885b21>)(post-command)
  apply(#f(compiled-function (command) "`company-mode' frontend similar to a tooltip but based on overlays." #<bytecode 0x1885b21>) post-command)
  company-pseudo-tooltip-frontend(post-command)
  company-pseudo-tooltip-unless-just-one-frontend(post-command)
  company-call-frontends(post-command)
  company-post-command()
  company-idle-begin(#<buffer main.rs> #<window 3 on main.rs> 130 276)
  apply(company-idle-begin (#<buffer main.rs> #<window 3 on main.rs> 130 276))
  timer-event-handler([t 23166 48844 20486 nil company-idle-begin (#<buffer main.rs> #<window 3 on main.rs> 130 276) nil 319000])

```

**Comment by dgutov** [comment]
Looks like there's a `nil` inside the returned completions list. I.e. `company-lsp` problem.

@tigersoldier, any ideas?

**Comment by tigersoldier** [comment]
Can you set `lsp-print-io` to t and paste the response for the completion request that triggers this issue?

**Comment by sebastiencs** [comment]
Ok this happens with the `annotation` command. When the return value contains newlines.

Example of string that cause an error on `annotation`
```
"pub fn statuses(&self, options: Option<&mut StatusOptions>)\n
                    -> Result<Statuses, Error> (Function)"
```

@tigersoldier From the lsp side, this is the `completionItem`:
```json
    {
      "label": "statuses",
      "kind": 3,
      "detail": "pub fn statuses(&self, options: Option<&mut StatusOptions>)\n                    -> Result<Statuses, Error>",
      "insertText": "statuses(${1:options})",
      "insertTextFormat": 2
    },
```

**Comment by dgutov** [comment]
Annotations are allowed to be nil. Not every completion has an annotation.

**Comment by sebastiencs** [comment]
> Annotations are allowed to be nil. Not every completion has an annotation.

It isn't nil, it just contains a newline, which I think cause the error

**Comment by dgutov** [comment]
Yup, that's it! `comment-string-strip` doesn't expect a multiline value.

Can be fixed in company-mode, although there's not much point in having a multiline annotation, is there?

**Comment by sebastiencs** [comment]
Yep, that needs to be fixed on the server side too.

Thanks !
