### ISSUE TITLE
Error from python-shell-completion-at-point

### ISSUE THREAD

**Issue by mambolevis** [company-mode/company-mode#759]
Hi,

The following error appears in the `*Python*` buffer when it tries any autocompletion.
`In [2]: ne`
After typing one or two words, this error is shown:

```
Company: An error occurred in auto-begin
Company: backend (company-capf :with company-yasnippet) error "Invalid search bound (wrong side of point)" with args (prefix)
```
As suggested by https://github.com/jorgenschaefer/elpy/issues/1297#issuecomment-365431046
the following workaround can be used to solve the problem:

```
(defadvice python-shell-completion-at-point (before fix-company-bug activate)
  "Fix a bug in company, modifying the current point"
  (goto-char (point-max)))
```

It looks like a bug in company. 

Thanks

**Comment by dgutov** [comment]
The other way to avoid the error is to get rid of `company-sort-by-occurrence` in `company-transformers`, since apparently this completion function doesn't work with it.

And yet another way to do it, try this advice instead:

```el
(defadvice python-shell-completion-at-point (around fix-company-bug activate)
  "python-shell-completion-at-point breaks when point is before the prompt"
  (when (>= (point) (cdr comint-last-prompt))
    ad-do-it))
```

**Comment by mambolevis** [comment]
Yes, I commented the option:  `(setq company-transformers '(company-sort-by-occurrence))` and it works without using the any advice. 

I also tested your advice version considering the option `company-sort-by-occurrence in company-transformers` and it works.

Let me aks you something: What is the difference between the two advices versions? it is just for learning. 

Thanks,

**Comment by dgutov** [comment]
The advice from the Elpy thread creates a workaround based on the assumption that the completion function being called from a different buffer position is a bug (which is incorrect). In the end, it seems to work, but it's more luck than anything else.

The second one creates an early abort for the case we know the completion function can't handle (it raises the error when point is before the last prompt).

**Comment by mambolevis** [comment]
Thank you for your time, support and explanation.

**Comment by mambolevis** [comment]
@dgutov 
Hi, 
The completion in the `inferior-python-mode` is not working any more. I updated company (`company-20180225.1741)` and elpy  (`elpy-20180223.1119`). I am not really sure, but I think the problem started after updating company from melpa. 
Let me please exchange my python and company configuration, maybe you can give me a piece of advice.

```
(use-package python
  :defer t
  ;; :preface
  ;; (add-hook 'inferior-python-mode-hook
  ;;           (lambda ()
  ;;             (company-mode -1)))
  :mode ("\\.py\\'" . python-mode)
  :config
  ;;--------------------------------------------------------------------------
    ;;;  comment/uncoment the block to consider python, jupyter or ipython
  ;;--------------------------------------------------------------------------
  ;; Use the Python standard interpreter (default)
  ;; (setq python-shell-interpreter "python"
  ;;       python-shell-interpreter-args "-i")

  ;; Use Jupyter console (recommended for interactive Python)
  ;; (setq python-shell-interpreter "jupyter"
  ;;       python-shell-interpreter-args "console --simple-prompt")

  ;; Use IPython:
  (if (executable-find "ipython")
      (setq python-shell-interpreter "ipython"
            python-shell-interpreter-args "-i --simple-prompt"))
  ;;--------------------------------------------------------------------------
  (setq python-shell-completion-native-enable nil)
  (add-hook 'python-mode-hook #'my/python-mode-hook)
  ;; Error from python-shell-completion-at-point
  ;; https://github.com/company-mode/company-mode/issues/759
  (defadvice python-shell-completion-at-point (around fix-company-bug activate)
    "python-shell-completion-at-point breaks when point is before the prompt"
    (when (>= (point) (cdr comint-last-prompt))
      ad-do-it)))
```



```
(use-package company
  :ensure t
  :demand
  :preface
  ;;----------------------------------------------------------------------------
  ;;;  Add yasnippet to all company backends
  ;;----------------------------------------------------------------------------
  (defun company-mode/backend-with-yas (backend)
    "Add BACKEND to jasnippet."
    (if (and (listp backend) (member 'company-yasnippet backend))
        backend
      (append (if (consp backend) backend (list backend))
              '(:with company-yasnippet))))
  (eval-after-load "yasnippet"
    '(progn
       (setq company-backends
             (mapcar #'company-mode/backend-with-yas company-backends))))
  ;;----------------------------------------------------------------------------
  :bind
  (:map company-active-map
        ("C-n" . company-select-next)
        ("C-p" . company-select-previous)
        ("RET" . company-complete-common)
        ("<tab>" . company-complete-selection))
  :bind ("C-<tab>" . company-manual-begin)
  :config
  (setq company-minimum-prefix-length 1
        ;;company-tooltip-align-annotations t
        company-idle-delay 0
        company-transformers '(company-sort-by-occurrence)
        )
  (global-company-mode 1))
```

**Comment by dgutov** [comment]
@mambolevis Is it really in `inferior-python-mode` buffers? Are you seeing any errors?

I've just found an obvious kind of problem with the advice I posted, see it updated here: https://github.com/company-mode/company-mode/issues/759#issuecomment-366474078 But that was only a problem in `python-mode` buffers.

**Comment by mambolevis** [comment]
`I've just found an obvious kind of problem with the advice I posted, see it updated here:`
Ok, already considered.

`Is it really in inferior-python-mode buffers? Are you seeing any errors?`
Well, in python-mode itself,  I get autocompletion and in the mode line appears: `company <jedi>`
![image](https://user-images.githubusercontent.com/13024208/36669910-cfb1bef6-1af6-11e8-976d-ee3078ce6044.png)

After C-c C-c the script runs without problems. Nonetheless, it is not possible to use autocompletion in the` inferior-python-mode` buffer:
![image](https://user-images.githubusercontent.com/13024208/36669974-feba8110-1af6-11e8-8271-8e7b2f771f15.png)

I don't see any error: I started both emacs as: `runemacs --debug-init` and turned `toggle-debug-on-error`

**Comment by dgutov** [comment]
> it is not possible to use autocompletion in theinferior-python-mode buffer

OK. Try disabling `company-mode`. Does `C-M-i` show you any completions?

**Comment by dgutov** [comment]
Also, try commenting out the `ipython` setup.

**Comment by mambolevis** [comment]
> OK. Try disabling company-mode. Does C-M-i show you any completions?

I disabled `company-mode` and also tested `C-M-i `and the message is: `No matches`

> Also, try commenting out the ipython setup.

I also tried with the  ipython setup commented, but the problem is still there:  `No matches`
![image](https://user-images.githubusercontent.com/13024208/36680811-1d01f2e6-1b17-11e8-9ac7-d9ddaaa605ca.png)

Any idea or suggestion? 

I am planning to build emacs soon (probably today ). Do you have any suggestion which version should I build?

**Comment by dgutov** [comment]
> I disabled company-mode and also tested C-M-iand the message is: No matches

That means company-mode is not at fault, and the problem is with either your Emacs version, your config, or the combination of them.

> I am planning to build emacs soon (probably today ). Do you have any suggestion which version should I build?

Try emacs-26 or master. Both are currently pretty stable.

BTW, another thing to do with your current version of Emacs is to comment out this:

```el
(setq python-shell-completion-native-enable nil)
```

**Comment by mambolevis** [comment]
I have already build emacs-26 and made all tests again and the problem is still there.  However, an error is shown when I try to turn-on  `company-jedy `
```
Configuring package company-jedi...done
Company: An error occurred in auto-begin
Company: backend company-jedi async timeout with args (candidates )
user-error: Cannot complete at point
```
And the whole `*Backtrace*`

Debugger entered--Lisp error: (error "Company: backend company-jedi async timeout with args (candidates )")
  signal(error ("Company: backend company-jedi async timeout with args (candidates )"))
  error("Company: backend %s async timeout with args %s" company-jedi (candidates ""))
  company--force-sync(company-call-backend-raw (candidates "") company-jedi)
  company-call-backend(candidates "")
  company--fetch-candidates("")
  company-calculate-candidates("")
  company--begin-new()
  company--perform()
  company-auto-begin()
  company-manual-begin()
  company-begin-backend(company-jedi)
  company-jedi(interactive)
  funcall-interactively(company-jedi interactive)
  call-interactively(company-jedi record nil)
  command-execute(company-jedi record)
  #f(compiled-function (cmd) #<bytecode 0x3d4d51d>)("company-jedi")
  ivy-call()
  ivy-read("M-x " [0 cmake-ide ansi-color-apply-overlay-face isearch--state-pop-fun--cmacro -flatten-n 0 -is-infix\? xselect--int-to-cons magit-submodule-update tls-format-message tramp-adb-parse-device-names tramp-find-user help-variable 0 0 0 tramp-gvfs-handle-copy-file tramp-do-copy-or-rename-file-out-of-band template nsm-permanent-host-settings is-finding-directory mixal web-mode-warning-face tidal cl-print--preprocess ivy-sort-file-function-default tls-success run-stuff -some\? Franklin\ Gothic\ Demi\ Cond 0 jedi:-virtualenv-version checkdoc-package-keywords-flag ! Load\ snippets\.\.\. 0 dired-input nil :caller counsel-M-x)
  counsel-M-x()
  funcall-interactively(counsel-M-x)
  call-interactively(counsel-M-x nil nil)
  command-execute(counsel-M-x)

**Comment by dgutov** [comment]
> an error is shown when I try to turn-on company-jedy

Then don't do that. It's not used in inferior buffers, is it? Sorry I can't help you debug it, but it doesn't seem related to the problem in question.

**Comment by dgutov** [comment]
> I have already build emacs-26 and made all tests again and the problem is still there

Is it a recent build? Does the problem reproduce with `emacs -Q`?

**Comment by mambolevis** [comment]
> Is it a recent build? 

Yes, I build it yesterday: `GNU Emacs 26.0.91 (build 1, x86_64-w64-mingw32) of 2018-02-26`

> Does the problem reproduce with emacs -Q?
- I started emacs: `runemacs -Q`
- Started the Python process first with ‘M-x run-python’ or ‘C-c C-p’
- After evaluating the buffer C-c C-c the following message is displayed:  `Shell native completion is disabled, using fallback`

**Comment by dgutov** [comment]
In that case, `M-x report-emacs-bug` seems to be in order.

**Comment by mambolevis** [comment]
Yes, starting emacs as (`runemacs -Q`) I made several tests with different computers and different emacs versions (`25,26 including pre-tests and my own build versions`) but unfortunately the Shell native completion is disabled. I have already reported that issue. 

On the other hand, I found and correct the problem in my new configuration: The use `gc-cons-threshold 800000` caused some issues in my configuration. I change it to `gc-cons-threshold 50000000` and everything is working fine. 
```
(setq package-enable-at-startup nil
      file-name-handler-alist nil
      message-log-max 16384
      gc-cons-threshold 402653184
      gc-cons-percentage 0.6)

(add-hook 'after-init-hook
          `(lambda ()
             (setq file-name-handler-alist file-name-handler-alist-old
                   ;; reduce the frequency of garbage collection by making it happen on
                   ;; each 50MB of allocated data (the default is on every 0.76MB)
                   gc-cons-threshold 50000000
                   gc-cons-percentage 0.1)
             (garbage-collect)) t)
```
Before closing this issue, I would like to ask you, which parameter do you use to build emacs?
In my case is (may be you have any recommendation): 
`"--prefix=/c/emacs/emacs-26 --without-imagemagick --with-modules 'CFLAGS=-O2 -gdwarf-4 -g3'"`

Thanks

**Comment by dgutov** [comment]
> I found and correct the problem in my new configuration: The use gc-cons-threshold 800000 caused some issues in my configuration

I'm glad you did. I was not aware that this setting can cause any problems aside from longer GC pauses, though.

> which parameter do you use to build emacs?

Just the default ones. That means without modules or Xwidgets (they are disabled by default).

**Comment by dgutov** [comment]
BTW, I've finally added a workaround for `inferior-python-mode`. You shouldn't need that advice anymore.

**Comment by mambolevis** [comment]
Thanks. Could you please provide the link to the workaround for inferior-python-mode?
When can I test it? I am now trying to solve this issue.

**Comment by dgutov** [comment]
https://github.com/company-mode/company-mode/commit/5c2425b9863810a395efcbc25abaa5348a7bfe23
and
https://github.com/company-mode/company-mode/commit/0dc69458d12c51db8af8a16d5325dd26ce3d15c1

> When can I test it?

When MELPA builds the new version, I presume.

> I am now trying to solve this issue.

Were you still having an issue? Wasn't the advice working?

**Comment by mambolevis** [comment]
> Were you still having an issue? Wasn't the advice working?

Your solution with the advice worked perfectly. I supposed the new workaround also works. Unfortunately, I can not test it because the` inferior-python-mode` in my configuration stopped to work.

I am just waiting that someone reported that the `inferior-python-mode` is working in his/her configuration. I al also searching possible solutions meanwhile.

**Comment by dgutov** [comment]
> just waiting that someone reported that the inferior-python-mode is working in his/her configuration

Well, it's working in mine, in different Emacs versions. I'm not using Windows, though.

Have you searched the Emacs bug tracker? https://debbugs.gnu.org/30651 seems relevant.

**Comment by mambolevis** [comment]
> Have you searched the Emacs bug tracker? https://debbugs.gnu.org/30651 seems relevant.

Yes, the mail is relevant but it doesn't solve the problem. It shows how to silent the problem but not how to achieve an actual auto-completion in `inferior-python-mode`.

After searching similar cases (I found many references) and considering my own experience with the auto-completion in the `inferior-python-mode` I can conclude that in fact it is a bug which is more visible in windows.

Do you know what are the dependencies of `inferior-python-mode` in terms of OS, python packages or any other?

**Comment by dgutov** [comment]
No extra packages, just a Python REPL, maybe compiled with Readline support (or maybe not necessarily). Anyway, I'm on GNU/Linux, where it sorta works right away.

I don't program in Python anyway, so I'm not the person to ask, really.

**Comment by mambolevis** [comment]
Thank you, for your support.
