### ISSUE TITLE
Boxed X icons/chars beside spacemacs buffer

### ISSUE THREAD

**Issue by trippleflux** [company-mode/company-mode#761]
![no-icons](https://user-images.githubusercontent.com/1216215/36588524-ff2822f8-18ba-11e8-8d3f-064543295060.png)

As screenshot above, there are suppose to be a circled's character beside the spacemacs buffer, but in my case all of it displayed as circled's x, these are only happened on my self build emacs x64 25.3.1, it doesn't happened on [built](https://sourceforge.net/projects/emacsbinw64/files/release/)

Using the [built](https://sourceforge.net/projects/emacsbinw64/files/release/) without touching my ~/.emacs.d directory, it can displayed all of the circled's chars fine, but for my own emacs built somehow it unable to do it.

on hovering the boxed x characters i am getting it's on company-mode

My spacemacs is develop branch @ 93ec42177e0d1584ecfa837258227f2210f5a499

How to fixes this?

My spacemacs config file : 
[spacemacs.txt](https://github.com/syl20bnr/spacemacs/files/1751216/spacemacs.txt)

**Comment by dgutov** [comment]
This is about some customization made in Spacemacs. See https://github.com/syl20bnr/spacemacs/#getting-help, or just report the bug there.

But in all likelihood, you just need to install a font that supports the necessary characters.
