### ISSUE TITLE
Non-prefix backends: `highlights' instead of `match'?

### ISSUE THREAD

**Issue by Sarcasm** [company-mode/company-mode#762]
Hello,
Sorry for the bad title.

I'm wondering if the `match` command, could not be improved or superseded by an `highlight` command to better support non-prefix matches.

I'm using [cquery](https://github.com/cquery-project/emacs-cquery) and [company-lsp](https://github.com/tigersoldier/company-lsp).
Cquery returns non-prefix matches but company-lsp does not display the match information well IMHO.
At this time, company-lsp sets `match` to the length of `arg`:

```elisp
(defun company-lsp (command &optional arg &rest _)
  "Define a company backend for lsp-mode.
See the documentation of `company-backends' for COMMAND and ARG."
  (interactive (list 'interactive))
  (cl-case command
    (interactive (company-begin-backend #'company-lsp))
    ...
    (match (length arg))
    (post-completion (company-lsp--post-completion arg))))
```

* https://github.com/tigersoldier/company-lsp/blob/4512d062c38922d8b8cf402ca6043c246e915694/company-lsp.el#L412

In my Emacs theme, I customize the company faces so the matched part is underlined, this means I get the following result:

![image](https://user-images.githubusercontent.com/424046/36821823-300f0cd6-1cf5-11e8-9b12-389a120eae25.png)

It's kind of ugly, as everything is underlined.
I think most people don't differentiate the match in their theme (e.g. company-mode default faces don't IIUC), so it is not noticed.

To get something slightly more correct, at least when the completion is a prefix, I made a quick'n'dirty change of the code to:

```diff
-    (match (length arg))
+    (match (length company-prefix))
```

However, for non-prefix completion it's not really better:

![image](https://user-images.githubusercontent.com/424046/36821488-78fd2e98-1cf3-11e8-82dd-c1e6fc8e002d.png)

With the current `match`, I guess the best would be to match from the first to the last matching character:

```
da|
---
[defa]rg
```

But what I'd really like to see, is:

```
da|
---
[d]ef[a]rg
```

I'm thinking `match` could allow another kind of return value, or a new command `highlights` could be provided, to return a list of character indices, e.g.:

```elisp
(highlights '(0 3))
```

What do you think?

**Comment by dgutov** [comment]
Hi! The title is fine.

> With the current match, I guess the best would be to match from the first to the last matching character

Indeed. And that's what `company-capf` does (which is only noticeable in the partial-completion case). It got broken by the current Emacs master, though. I'll have to look into that.

> But what I'd really like to see, is:

That's something I considered back when `match` was introduced. No backends had the necessary info to support this, though.

I think there can be one downside to this choice: more "visual noise", you'll have to search for the last highlight a bit longer. Which is the only really useful bit, I think, because it's what tells you which characters you should type next. But IDK if the difference will be in any way significant, and anyway the behavior can be customizable.

So I'm 100% on board with your proposal. But if you can, try using both options for a little while (`highlights` vs property-implemented `match`), and see which one you really prefer.

**Comment by Sarcasm** [comment]
Thank you for your feedback, the difficulty will be to know which characters to highlight as in the case of cquery, the fuzzyness is done on the server side.

For reference, I think it can look good in other places, I don't find it noisy in VS Code for example:

![image](https://code.visualstudio.com/assets/docs/editor/intellisense/intellisense_packagejson.gif)

Or Sublime Text:
![image](https://user-images.githubusercontent.com/424046/36844003-1f62e93c-1d51-11e8-89c5-0ae587d4d3b0.png)

And live: https://rawgit.com/farzher/fuzzysort/master/test.html

**Comment by dgutov** [comment]
> the difficulty will be to know which characters to highlight as in the case of cquery, the fuzzyness is done on the server side

Maybe take example from Ido, and adapt the following code:

```el
      (setq re (concat (regexp-quote (string (aref ido-text 0)))
		       (mapconcat (lambda (c)
				    (concat "[^" (string c) "]*"
					    (regexp-quote (string c))))
				  (substring ido-text 1) "")))
```

It will need some grouping added, though.

But how does VS Code do the highlighting in these cases ([like this one](https://code.visualstudio.com/assets/docs_carousel/intellisense_b.png))? Also client-side?

> I think it can look good in other places, I don't find it noisy in VS Code for example

Noisy in comparison. As in "showing extra, not very useful information". I don't think it's possible to evaluate this based in pictures, outside of one's own workflow. But it's probably a matter of personal perception anyway.

**Comment by Sarcasm** [comment]
> But how does VS Code do the highlighting in these cases (like this one)? Also client-side?

I looked at the code, and while I'm not certain, I think it's done client side, and it's possible that the highlights mismatch the methodology of the server but as long as they both depends on the same set of characters I guess it's okay-ish.

Maybe @MaskRay would know better than me (e.g. if cquery has an API to expose the highlights to VS Code).

**Comment by MaskRay** [comment]
I don't know much about company. Can you examples how you customize company?

```elisp
(set-face-attribute 'company-tooltip-annotation nil :foreground "slate gray")
(set-face-attribute 'company-tooltip-common nil :foreground "green")
```

But I cannot get the matched string in candidates underlined.

**Comment by Sarcasm** [comment]
> I don't know much about company. Can you give examples how you customize company faces?

I will be honest, I'm not sure which line is responsible for the result, but here is my company-mode faces:

```elisp
   ;; Company
   `(company-echo-common ((t (:underline t))))
   `(company-preview ((t (:inherit shadow))))
   `(company-preview-common ((t (:inherit company-preview :underline t))))
   `(company-scrollbar-bg ((t (:inherit company-tooltip :background "SteelBlue3"))))
   `(company-scrollbar-fg ((t (:background "DeepSkyBlue4"))))
   `(company-template-field ((t (:background "DeepSkyBlue3" :foreground "black"))))
   `(company-tooltip ((t (:background "LightSteelBlue1" :foreground "dark slate gray"))))
   `(company-tooltip-annotation ((t (:inherit company-tooltip :foreground "slate gray"))))
   `(company-tooltip-annotation-selection ((t (:inherit company-tooltip-annotation :background "LightSteelBlue3"))))
   `(company-tooltip-common ((t (:inherit company-tooltip :underline t))))
   `(company-tooltip-common-selection ((t (:inherit company-tooltip-selection :underline t))))
   `(company-tooltip-mouse ((t (:inherit company-tooltip-selection))))
   `(company-tooltip-selection ((t (:inherit company-tooltip :background "LightSteelBlue3"))))
```
source:  https://github.com/Sarcasm/.emacs.d/blob/544591c02faa019872a48ffecfe559014a43380a/theme/sarcasm-theme.el#L203-L216

It's probably one of those that specify `underline`:


Regarding doing the match client-side.
I was actually thinking, in the case of company, to request the highlights for the 10s or so candidates that are displayed, we don't need it for all the returned candidates.
But it may still add a few back and forth of request that may not be desired.

**Comment by MaskRay** [comment]
After changing company-lsp to use `    (match (length company-prefix))`, `company-tooltip-common` decides the face.

**Comment by dgutov** [comment]
> `company-tooltip-common`

It is indeed the face. Also: `company-tooltip-common-selection`, if defined.

Speaking of client-side logic, try out this one:

```el
(defun company-flex-highlights (input string)
  (let ((re
         (mapconcat
          (lambda (c)
            (format "[^%s]*\\(%s\\)" (string c) (string c)))
          input ""))
        (case-fold-search (company-call-backend 'ignore-case))
        res ref)
    (when (string-match re string)
      (setq res (setq ref (nthcdr 2 (match-data))))
      (while ref
        (setcdr ref (nthcdr 2 ref))
        (setq ref (cdr ref)))
      res)))
```

Can somebody imagine a fuzzy-matching use case where this would return a wrong result?

**Comment by Sarcasm** [comment]
> Can somebody imagine a fuzzy-matching use case where this would return a wrong result?

```elisp
(company-flex-highlights "ab" "0a0b.ab") -> (1 3)
```

If `.` is considered a separator, and the last `ab` a full word, I think the fuzzy matchers will prefer it over the lone `a` and `b`.

**Comment by dgutov** [comment]
Yes, but they will prefer it in terms of *sorting*, right? If the user then types `a` again, or even `.` itself, this candidate should match. So it won't be fair to highlight the last `ab`, because that would imply that the user is not allowed to type anymore.

(I've been thinking of this exact question for a while.)

PS: Oops, forgot a regexp-quote, fixed now.

**Comment by Sarcasm** [comment]
Some fuzzy search tools will highlights the bests.
One example, is fzf:

> ## md|
> **md**abc
> abmd.**md**
> **md**abcmd.

> ## md.|
> mdabc**md.**
> ab<b>md.</b>md


After typing more text, the highlights jumped back from `abmd.[md]` to `ab[md.]md`.

I think it's what I want.

If I have a few a directory with only 3 files:

```
abc.c
abc.h
Makefile
```

If I type just `c`, the file where `c` is the most distinctive, is the extension of `abc.[c]`, if that's the reason this candidate is show first, then I'd like to know it with the highlights.
I think highlighting the characters that resulted in this list of candidates, in this order, allow the user to learn (unconsciously?) how the matcher work.

**Comment by dgutov** [comment]
@Sarcasm Please take a look at #798, and let us know if you have any comments.
