### ISSUE TITLE
command that create cider-repl if non existed, otherwise switch-to-repl

### ISSUE THREAD

**Issue by cinsk** [company-mode/company-mode#763]
Hello,

Is there any command that call `cider-jack-in` if no repl buffer connected to the current buffer, otherwise call `cider-switch-to-repl`?  All I can do is following function, but I want to know better alternative.  Thanks.

    (defun cider-switch-to-repl-create ()
      (interactive)
      (condition-case nil
          (call-interactively 'cider-switch-to-repl-buffer)
        (user-error
         (call-interactively 'cider-jack-in))))

**Comment by dgutov** [comment]
Sorry, this is not CIDER's bug tracker.
