### ISSUE TITLE
Company doesn't show completion automatically

### ISSUE THREAD

**Issue by amosbird** [company-mode/company-mode#765]
Hi, I have 
```
company-auto-complete = t
company-begin-commands = '(self-insert-command ...)
company-idle-delay = 0.1
company-minimum-prefix-length = 2
```

however, company only shows completion candidates after I invoke `company-complete` interactively. What can I do to make it show completion menu while I'm typing? Thanks!

**Comment by dgutov** [comment]
Does it work with the default config?

**Comment by amosbird** [comment]
Ah,  it turns out there is a hook that locally sets `company-idle-delay = never`.
