### ISSUE TITLE
company-tng doesn't show the first candidate on magit commit buffer.

### ISSUE THREAD

**Issue by amosbird** [company-mode/company-mode#766]
![](https://la.wentropy.com/CYZO.png)

Hi,  company-tng is a great frontend and it works well in most cases. However when doing magit commit, there is a small rendering issue as shown in the picture above. I'm using emacs 27.0.50 with latest magit and company.

**Comment by dgutov** [comment]
Are you sure the default config doesn't have this problem?

**Comment by amosbird** [comment]
Ah, sorry it's not reproducible with plain emacs. It seems to be a theme confliction.

**Comment by amosbird** [comment]
Found the reason. It's due to `truncate-line-mode` . I'm not sure if this counts as an issue.

![](https://la.wentropy.com/S-eb.png)

**Comment by dgutov** [comment]
What's `truncate-line-mode`?

If I just `M-x toggle-truncate-lines` in `vc-git-log-edit-mode` (not Magit), I can't reproduce.

**Comment by amosbird** [comment]
Hmm, this weird right hand side bar seems to be the cause.
![](https://la.wentropy.com/AuVv.png)





![](https://la.wentropy.com/CRZz.png)

**Comment by amosbird** [comment]
duplicated with https://github.com/company-mode/company-mode/issues/235   https://github.com/company-mode/company-mode/issues/180

**Comment by dgutov** [comment]
That's fill-column-indicator. A known incompatibility: https://github.com/alpaker/Fill-Column-Indicator/issues/54
