### ISSUE TITLE
Configure company to accept input only if I've interacted with the pop-up menu

### ISSUE THREAD

**Issue by kshenoy** [company-mode/company-mode#767]
By default, company will show a pop-up menu and automatically highlight the first selection and if I don't want to use the suggestion, I can continue typing and there are no issues.

The issue arises when the menu pops up and I want to press a RET/TAB (while typing and not to accept company's suggestions). Now I have to press `C-g` to kill it and only then press RET/TAB.

Is it possible to configure company to just show the pop-up menu but not select any entry. That way, any RET/TAB will be treated as complete-selection or complete-common only if we've explicitly pressed `M-n` or `M-p` and selected an entry. If not, it'll just be treated as a regular RET/TAB.

Also, is it possible to show the sources of completion eg. `y` to indicate yasnippet etc.

Since `M-[1-9]` can be used to quickly select an entry from the pop-up menu, is it possible to configure the pop-up menu to show the numbers to simplify the process of selecting an entry?

**EDIT:**

I found out about `company-explicit-action-p` and tried this and it seems to work for now. 

    (bind-keys :map company-active-map
               :filter (company-explicit-action-p)
               ("<return>" . company-complete-selection)
               ("RET"      . company-complete-selection)
               ("<tab>"    . company-complete-common)
               ("TAB"      . company-complete-common))

I don't know yet if there are any downsides to doing it this way. If not, that answers part of the question.

Also found out about `company-show-numbers` and that answers one question but raises another - what's a good way for me to learn about all these options?

**Comment by dgutov** [comment]
You might want to try `company-tng`.

**Comment by dgutov** [comment]
The `:filter` thing is pretty cool, though.

**Comment by dgutov** [comment]
> what's a good way for me to learn about all these options?

Like the homepage says: `M-x customize-group RET company`.

**Comment by kshenoy** [comment]
Thanks! I've it set up just the way I want it. Posting [link](https://github.com/kshenoy/dotfiles/blob/5e59ffe35b95c083e6d334388d6bfc3a0304d9f2/emacs.d/config.org#dont-get-in-the-way-of-mah-typing) to my config in case anyone else's interested.
