### ISSUE TITLE
Is there any way to group candidates by meta?

### ISSUE THREAD

**Issue by DungxNguyen** [company-mode/company-mode#770]
Hi,
I wonder if there is any way to group/order candidates by meta? For example, when i have a list of candidates, i want to order candidates that are parameters of current function on top.
I check the list candidate-transformers, it can re-order the candidates list, but it only takes candidates as argument.
Best,
Dung~

- [ ]

**Comment by dgutov** [comment]
You can get a candidate's meta by calling `(company-call-backend candidate 'meta)`.

**Comment by DungxNguyen** [comment]
I tried
`(print (company-call-backend candidate 'meta))`
but it prints "nil" all time.

Btw, this is the implementation of my transform function
`(defun company-transform-python (candidates)
  (let ((top))
    (mapcar #'(lambda (c)
        (if (string-equal (company-call-backend c 'meta) "param")
            (progn
              (add-to-list 'top c)
              (setq candidates (delete c candidates)))))
        candidates) 
    (append top candidates)))
`
Apparently, it didn't work.

**Comment by dgutov** [comment]
> I tried

Tried it where? Try adding that to the transformer code. And use `message` instead of `print`.

> Apparently, it didn't work.

If the above doesn't help you, try edebug-ing the definition (`C-u C-M-x`) and step through it (with SPC) when it gets called.

**Comment by DungxNguyen** [comment]
I tried to append a company transformer in python mode. This is my full source code
`(defun company-transform-python (candidates)
  (let ((top))
    (mapcar #'(lambda (c)
        ;; (if (string-equal (company-call-backend c 'meta) "param")
            (progn
	      (message c)
	      (message (company-call-backend c 'meta))
              ;; (add-to-list 'top c)
              ;; (setq candidates (delete c candidates))
	      ));;)
        candidates) 
    (append top candidates)))


(defun my-python-conf()
  (setq-local company-transformers
          (append company-transformers '(company-transform-python))))

(add-hook 'python-mode-hook 'my-python-conf)
`
It only prints out candidates but not meta of them. I debugged it at each statement, and the statement (company-call-backend c 'meta) always return nil.

**Comment by DungxNguyen** [comment]
I got it, you mistook the call of `(company-call-backend candidate 'meta)`. It must be `(company 'meta candidate)`
Hence, these code works as I expected. I post here just in case someone needs it.
```
(defun company-transform-python (candidates)
  (let ((top))
    (mapcar #'(lambda (c)
         (if (string-equal (company-call-backend 'annotation c) "param")
            (progn
	      ;; (message c)
	      (message (company-call-backend 'annotation c))
              (add-to-list 'top c)
              (setq candidates (delete c candidates))
	      )))
        candidates) 
    (append (nreverse top) candidates)))


(defun my-python-conf()
  (setq-local company-transformers
          (append company-transformers '(company-transform-python))))

(add-hook 'python-mode-hook 'my-python-conf)
```

**Comment by dgutov** [comment]
> It must be [EDITED] (company-call-backend 'meta candidate)

Indeed, sorry about that.

**Comment by dgutov** [comment]
You wanted to actually group by annotation, then?

**Comment by DungxNguyen** [comment]
I tried both annotation and meta. Because the particular information by the backend I'm using right now, I fit more with annotation.
Is there a more elegant way to group by annotation?

**Comment by dgutov** [comment]
> Is there a more elegant way to group by annotation?

Probably not (transformers are the way to go, I'd say).

You're welcome!
