### ISSUE TITLE
Let company support complete major-mode syntax font-lock keywords

### ISSUE THREAD

**Issue by stardiviner** [company-mode/company-mode#772]
Like this major-mode [dtrace-script-mode](https://github.com/dotemacs/dtrace-script-mode).
Support completing keywords in https://github.com/dotemacs/dtrace-script-mode/blob/master/dtrace-script-mode.el#L124

**Comment by dgutov** [comment]
I don't know how to implement your suggestion.

**Comment by stardiviner** [comment]
I will find a way how to get all those keywords. If it is possible. I might try to write a simple company backend. I want to take a try on writing company-mode backend for a long time.

**Comment by stardiviner** [comment]
After a try, seems unable to implement it.
