### ISSUE TITLE
Disable auto-completion

### ISSUE THREAD

**Issue by tmarti2** [company-mode/company-mode#773]
Hi,
I'm using company-mode on emacs, and I'm having trouble figuring how to turn off completion.
I Installed everything using opam and installed company-mode via M-x list-packages...
And then I did "opam user-setup install".
I'd like to turn off auto-completion when i'm typing and instead have a shortcut that does the same thing when I use it.
I know it must be easy to do, but I can't figure out how to do it...
There is this functions in opam-user-setup :
`(defun opam-setup-complete ()
  (if (require 'company nil t)
    (opam-setup-add-ocaml-hook
      (lambda ()
         (company-mode)
         (defalias 'auto-complete 'company-complete)))
    (require 'auto-complete nil t)))

(defun opam-setup-ocp-indent ()
  (opam-setup-complete)
  (autoload 'ocp-setup-indent "ocp-indent" "Improved indentation for Tuareg mode")
  (autoload 'ocp-indent-caml-mode-setup "ocp-indent" "Improved indentation for Caml mode")
  (add-hook 'tuareg-mode-hook 'ocp-setup-indent t)
  (add-hook 'caml-mode-hook 'ocp-indent-caml-mode-setup  t))`
Thanks

**Comment by dgutov** [comment]
`(setq company-idle-delay nil)`
