### ISSUE TITLE
customize wild card character

### ISSUE THREAD

**Issue by casouri** [company-mode/company-mode#774]
In company, asterisk serves as a wild card. but I need to stretch my finger a bit to reach it every time.

Is there a customization for that? So I can set, for example, single quote as a wild card.

**Comment by dgutov** [comment]
Server as a wild card where?

**Comment by casouri** [comment]
Like this: 
<img width="232" alt="screen shot 2018-03-25 at 10 17 46 am" src="https://user-images.githubusercontent.com/13118647/37876097-d45fc496-3015-11e8-8f8c-02a03a9b49b3.png">

I'm not sure if I understand it correctly since I just found it by accident, but it seems like a asterisk can match any character.

**Comment by dgutov** [comment]
What major mode? What backend is used?

**Comment by dgutov** [comment]
Ah, OK. This looks like `elisp-completion-at-point`.

**Comment by dgutov** [comment]
Unfortunately, looks like it is hardcoded (in `completion-pcm--string->pattern`). Please feel free to file a feature request for Emacs with `M-x report-emacs-bug`.

**Comment by casouri** [comment]
Ah---- So this is handled by the back-end. Thanks. 😄
