### ISSUE TITLE
disable company-complete-selection when company-tng doesn't select anything

### ISSUE THREAD

**Issue by amosbird** [company-mode/company-mode#775]
I have `C-i` binds to `company-complete-selection` in `company-active-map`. `C-i` is also used for current line reindentation. When company is active, `C-i` always completes something. Since `company-tng` acts as if there isn't any candidate be selected, can we also make it not grab the completion key (`C-i` in my case) ?

**Comment by dgutov** [comment]
See the `:filter` example here: https://github.com/company-mode/company-mode/issues/767

**Comment by amosbird** [comment]
Great!
