### ISSUE TITLE
Why is the default value of `company-minimum-prefix-length` 3?

### ISSUE THREAD

**Issue by re-mx** [company-mode/company-mode#776]
Hello

I am an Emacs novice and rookie. Your work is great！

But I have a little unclear: Why did you set the default value of `company-minimum-prefix-length` to `3`?

In many other editors and IDEs, the default value of similar variables is `2` or less.

Thank you very much, and sorry for my poor English.

**Comment by dgutov** [comment]
Hi!

> In many other editors and IDEs, the default value of similar variables is 2 or less.

Any particular examples? I just checked out Atom, and it only starts offering "words in all buffers" completions after you type 3 chars.

**Comment by re-mx** [comment]
<img width="1280" alt="2018-03-26 5 57 59" src="https://user-images.githubusercontent.com/26828933/37901010-86eb9cd6-3122-11e8-9ea3-07c53b5be70a.png">

**Comment by dgutov** [comment]
Is it a "words from all buffers" completion source on the screenshot? Doesn't look like it.

Does it work the same is less well-supported languages, in VS Code?

**Comment by re-mx** [comment]
No... They don't seem to have "words from all buffers" complete. When they write languages that they don't support, they don't have any completions.

So my question is "Why 3 is default?"
Whether language that company-mode support is good, the default value is 3.

**Comment by dgutov** [comment]
Well, it's a safe default. And we don't have separate values for different backends, so we use the highest for all of them.

As a user, you of course can change it to suit your backends, and even create local values in different buffers.

**Comment by re-mx** [comment]
Thanks.

I also don't expect any change. After all, safety is the first.

I just want to know the consequences of changing this value...However, I may already know it (for example, the completion result is incomplete)

Thank you again for your help.

**Comment by dgutov** [comment]
> I just want to know the consequences of changing this value

The popup will show up more often, sometimes disrupting typing... maybe using more CPU.

That's about it.

**Comment by re-mx** [comment]
I may have experienced delays for backends...And what you say about the CPU should not be a problem on any modern computer.
