### ISSUE TITLE
Avoid conflicts with completion-at-point, perhaps?

### ISSUE THREAD

**Issue by joaotavora** [company-mode/company-mode#778]
I find this to be useful in my configuration
```lisp
(advice-add 'completion-at-point :before (lambda (&rest _args) (company-cancel)))
```
Should something like this be in `company.el`?

I'm asking because, if user invokes `completion-at-point` (usually interactively), he intends for another, non-company.el system to take over, and this may conflict with a currently active company tooltip. I believe it's better to `company-cancel` in this situation.

**Comment by dgutov** [comment]
IDK, this wouldn't hurt, but I don't recall ever having the problem this is supposed to be fixing (`company-cancel` is just one `C-g` away).

Packages are not really supposed to use advice unless they really need to, though. Maybe put it on the wiki?

**Comment by joaotavora** [comment]
> company-cancel is just one C-g away).

This will likely compete with the exit key for the `completion-at-point` UI too, so it's not an option.

> Maybe put it on the wiki?

Perhaps. But why force the user of an optional package to reconfigure it so it doesn't break a core Emacs thing?

> Packages are not really supposed to use advice unless they really need to, though

I think this warrants it, seeing that `completion-at-point` is public, unlikely to go away, and the advice ignores arguments. 

Otherwise you could hook a dummy onto `completion-at-point-functions` but that's more problematic since you can't easily ensure that your hook runs before all others.

**Comment by joaotavora** [comment]
Had forgotten about `pre-command-hook`. What about this?

```diff
--- #<buffer company.el>
+++ /home/capitaomorte/.emacs.d/elpa/company-20180317.1008/company.el
@@ -1649,21 +1649,23 @@
   (and (symbolp command) (get command 'company-keep)))
 
 (defun company-pre-command ()
-  (company--electric-restore-window-configuration)
-  (unless (company-keep this-command)
-    (condition-case-unless-debug err
-        (when company-candidates
-          (company-call-frontends 'pre-command)
-          (unless (company--should-continue)
-            (company-abort)))
-      (error (message "Company: An error occurred in pre-command")
-             (message "%s" (error-message-string err))
-             (company-cancel))))
-  (when company-timer
-    (cancel-timer company-timer)
-    (setq company-timer nil))
-  (company-echo-cancel t)
-  (company-uninstall-map))
+  (if (eq this-command 'completion-at-point)
+      (company-cancel) ; avoid competing with `completion-at-point'
+    (company--electric-restore-window-configuration)
+    (unless (company-keep this-command)
+      (condition-case-unless-debug err
+          (when company-candidates
+            (company-call-frontends 'pre-command)
+            (unless (company--should-continue)
+              (company-abort)))
+        (error (message "Company: An error occurred in pre-command")
+               (message "%s" (error-message-string err))
+               (company-cancel))))
+    (when company-timer
+      (cancel-timer company-timer)
+      (setq company-timer nil))
+    (company-echo-cancel t)
+    (company-uninstall-map)))
 
 (defun company-post-command ()
   (when (and company-candidates

Diff finished.  Wed Mar 28 21:30:35 2018
```

**Comment by dgutov** [comment]
> This will likely compete with the exit key for the completion-at-point UI too, so it's not an option.

What do you mean? First one presses `C-g`, and then `C-M-i`.

The patch looks okay to me (although note that this seems to fail to cancel the timer or restore the window configuration when necessary), but could you explain the problem scenario again? Do you quickly switch between company and `completion-at-point` often?

**Comment by joaotavora** [comment]
```
emacs -Q -L . -l company-elisp.el -f global-company-mode
```
Now type `com` and wait for the yellow widget. Now type `C-M-i` and wait for the `*Completions*` window. Typing a `C-g` with the widget and the window merely cancels the window, but if you hadn't summoned the widget (or with the patch), `C-g` would have closed the window.

**Comment by joaotavora** [comment]
> The patch looks okay to me (although note that this seems to fail to cancel the timer or restore the window configuration when necessary

I'll look into those details but let's agree on the actual problem first.

**Comment by joaotavora** [comment]
> What do you mean? First one presses C-g, and then C-M-i.

BTW, I think I now understand what you mean... but If one forgets the first C-g the second one is ambiguous.

**Comment by joaotavora** [comment]
Nice one! Couldn't grok the docstring out of lazyness but that's exactly what was needed
