### ISSUE TITLE
Bad performance using company-css

### ISSUE THREAD

**Issue by seagle0128** [company-mode/company-mode#779]
GNU Emacs 25.3
Ubuntu 16.04 LTS

While I edit vue files with `web-mode` and `company`, it's very slaggy. After profiling, it shows `company-css` has bad performance. In Emacs 26, no issue since `company-css` is disabled by default (why?). I attached the screenshot and file for troubleshooting purpose.

![9845b30e91699fd89ffdfb66c4a369b5bbd5bbcb_1_629x500](https://user-images.githubusercontent.com/140797/38778897-0234c86a-40f3-11e8-93c7-556a4f4f0110.png)
[Pos.vue.zip](https://github.com/company-mode/company-mode/files/1912744/Pos.vue.zip)

**Comment by dgutov** [comment]
> In Emacs 26, no issue since company-css is disabled by default (why?).

Because the built-in completion function in `css-mode` has all the features now.

> After profiling, it shows company-css has bad performance.

I wonder which `company-grab` call takes all this time. Could you attach the file with this problem?

**Comment by seagle0128** [comment]
Thanks for the quick reply.
I have already uploaded the file, in pos.vue.zip.

**Comment by dgutov** [comment]
Oh, ok. Thanks.

It should be better now.

**Comment by seagle0128** [comment]
Thanks for the quick fixing.
