### ISSUE TITLE
company-semantic-summary-and-doc only selects up to first newline

### ISSUE THREAD

**Issue by ermingol23** [company-mode/company-mode#780]
The function `company-semantic-summary-and-doc()` found in `company-semantic.el` is not documented, but I assume the regexp `("\n*\\(.*\\)$")` in the function is intended to strip any leading newlines from the documentation string. However, the part of the regexp expression within parentheses only selects text from the docstring up to the **first** newline and all lines following are dropped.

Changing the rexexp to for instance `"\n*\\(\\(\\n.*\\)*\\)$"` will instead select **all** lines from the docstring **except** any initial newlines.

**Comment by dgutov** [comment]
It's only used for the `meta` call.

It's normal and expected for it to be trimmed to just the first non-empty line. The `doc-buffer` action uses a different code path.

How does the result usually look on your end?

**Comment by ermingol23** [comment]
When using company-quickhelp 2.3.0 I got only documentation up till the first newline. When investigating this I found that the code called eventually resulted in a call to `company-semantic-summary-and-doc` and then the regex which only selected everything up till the first newline... When I modified the regex I got all of the documentation and I have so far not seen any unwanted behavior. This was a couple of months ago and I really can't remember all the details and unfortunately I got the mail 6 days ago. :(

**Comment by dgutov** [comment]
@ermingol23 Did you modify code in company-mode or company-quickhelp? That might be important the next time you update the packages.

Let me know if you recall the details.

**Comment by ermingol23** [comment]
I have now gone down memory lane and debugged what happens. Assume you have a two C-functions defined like this in a buffer where semantic-mode is enabled

    /**
     * Foo foo foo foo foo foo foo foo foo foo foo foo foo foo foo foo foo
     * foo foo foo foo foo foo foo foo foo foo foo foo.
     *
     * Baz baz baz baz baz baz baz baz baz baz baz baz baz baz baz baz baz baz baz
     * baz baz baz baz baz baz baz baz baz baz baz baz baz baz baz baz baz baz.
     */
    void foobar(void)
    {
    }

    /**
     * Foo foo foo foo foo foo foo foo foo foo foo foo foo foo foo foo foo
     * foo foo foo foo foo foo foo foo foo foo foo foo.
     *
     * Bar bar bar bar bar bar bar bar bar bar bar bar bar bar bar bar bar bar bar
     * bar bar bar bar bar bar bar bar bar bar bar bar bar bar bar bar bar bar.
     */
    void foo(void)
    {
    }

When you type `foo` company starts completing and offers a pop-up menu that contains `foo` and `foobar`. When foobar is highlighted in the menu company-quickhelp shows a tooltip that contains the documentation string for `foobar` alas it only contains the `Foo foo foo...` part and not the `Baz baz baz...` part due to that `company-semantic-summary-and-doc` just selects up to the first newline.

The stack-trace looks like this (when within `company-semantic-summary-and-doc`

    company-semantic-summary-and-doc(("foobar" function ...))
    company-semantic(meta "foobar")
    apply(company-semantic (meta "foobar"))
    company-call-backend-raw(meta "foobar")
    apply(company-call-backend-raw (meta "foobar"))
    company--force-sync(company-call-backend-raw (meta "foobar") company-semantic)
    company-call-backend(meta "foobar")
    company-fetch-metadata()
    company-echo-show(company-fetch-metadata)
    apply(company-echo-show company-fetch-metadata)
    timer-event-handler([t 0 0 10000 nil company-echo-show (company-fetch-metadata) idle 0])

And company-quickhelp shows what `company-semantic-summary-and-doc` returns for the given sematic tag.

Should company-quickhelp fetch the documentation string in some other way and if so how in order to get the complete documentation string from semantic via company-semantic? What is the idea behind `company-semantic-summary-and-doc` only selecting everything up till the first newline and not the complete documentation string?

**Comment by dgutov** [comment]
> The stack-trace looks like this

There is no company-quickhelp in that stack trace, however.

> Should company-quickhelp fetch the documentation string in some other way

Yes. And looking at the code, I think it does.

**Comment by dgutov** [comment]
> What is the idea behind company-semantic-summary-and-doc only selecting everything up till the first newline and not the complete documentation string?

It's displayed in the echo area.
