### ISSUE TITLE
Current line jumps to middle of screen when company is invoked

### ISSUE THREAD

**Issue by tim-hilt** [company-mode/company-mode#781]
When i type something in the Buffer and company-mode gets invoked, it makes the current line jump to the middle of the screen.
I think this behavior is not so much of a bug, but it's distracting. 

I would rather like a solution that always keeps my current line in the middle when i'm in Emacs (regardless of wether it's at the bottom of the screen or not), but i didn't find anything so far.
**If someone reads this and knows a solution to the second issue, please comment** (Even though this is not the right place to request something like this).

But for the maintainers: 
Is there some way to disable or workaround the jumping? Is this purely happening, so that the list of completion-candidates can be fully shown?
Like i said- it might be a wanted behavior, but it's sometimes really distracting and not very easy on the eyes.

All help will be highly appreciated!
Greetings,
Tim

**Comment by dgutov** [comment]
This is not the intended behavior, and I don't see it.

Can you write a step-by-step reproduction starting with `emacs -Q -L ~/.emacs.d/elpa/company-xxx -l company`?

**Comment by tim-hilt** [comment]
Sorry for responding so late! 
In the meantime i found out, that the described behavior was caused by [https://github.com/emacsmirror/centered-cursor-mode](centered-cursor-mode)! 
Closing.
