### ISSUE TITLE
Have php variables show up only or just before functions

### ISSUE THREAD

**Issue by jonnycyr** [company-mode/company-mode#782]
Here's what I'm currently using for company with PHP:
```
(add-hook 'php-mode-hook
            (lambda ()
              (set (make-local-variable 'company-backends)
                   '((php-extras-company company-dabbrev-code) company-capf company-files))))
(setq company-minimum-prefix-length 1) 
(setq company-idle-delay 0.1)
```

How do I make it so that if I'm typing a string that starts with $ company-mode will only show variables, or at least variables before functions? Currently, if I have a variable called $var, if I try to type $v the auto complete menu shows up and shows me all the functions that start with var before showing me the variable var.

**Comment by dgutov** [comment]
That's either up to the backend (`php-extras-company`), in which cases mixing in the results from `company-dabbrev-code` might be a problem. Or, if you can differentiate them by the text, you can add an appropriate sorting function to `company-transformers`.

**Comment by jonnycyr** [comment]
Cool, thank you for response. I've been looking through the company source code, I didn't realize that it was so well documented so I've been coming up with my own ways to incorporate company-mode with php. Turns out it was the backend, I switched to using company-php from melpa: 
https://melpa.org/#/company-php
'''
(add-hook 'php-mode-hook
         '(lambda ()
            (require 'company-php)
            (company-mode t)
            (add-to-list 'company-backends 'company-ac-php-backend )))
'''

The above works wonderfully, typing any string with $ will only show variables. I'll add another comment once I get company-quickhelp working with this.

**Comment by jonnycyr** [comment]
I was previously mistaken - company-ac-php-backend does not show variables. But mixing in company-dabbrev-code works wonderfully, i.e. 
```
(add-to-list 'company-backends '(company-dabbrev-code company-ac-php-backend))
```

Also, company-php's most recent update added in company-quickhelp functionality.
