### ISSUE TITLE
How to let company detect the keywords in yasnippet

### ISSUE THREAD

**Issue by LuhengStat** [company-mode/company-mode#783]
How to let company detect the keywords in yasnippet? 
The yasnippet defined in ESS mode or python mode can
not be detected. How to set these? Thanks.

**Comment by dgutov** [comment]
Do you have `yas-minor-mode` enabled? It should take care of all this.

**Comment by LuhengStat** [comment]
Yes, But it did not work. All the yasnippet in Ess, Python( Elpy) or Auctex is not work.

**Comment by LuhengStat** [comment]
All my settings concerns company mode is below:

;; company-mode 
(global-company-mode)
(define-key company-active-map (kbd "C-h") 'company-show-doc-buffer)
(define-key company-active-map (kbd "C-n") 'company-select-next) 
(define-key company-active-map (kbd "C-p") 'company-select-previous)
(define-key company-active-map [tab] 'company-complete-common)
;;(define-key company-active-map (kbd "<C-tab>") 'company-select-previous)
(setq company-selection-wrap-around t
      company-tooltip-align-annotations t
      company-idle-delay 0.36
      company-minimum-prefix-length 2
      company-tooltip-limit 9
      company-show-numbers nil)

;; Add yasnippet support for all company backends
(defvar company-mode/enable-yas t
  "Enable yasnippet for all backends.")

(defun company-mode/backend-with-yas (backend)
  (if (or (not company-mode/enable-yas) (and (listp backend) (member 'company-yasnippet backend)))
      backend
    (append (if (consp backend) backend (list backend))
            '(:with company-yasnippet))))

(setq company-backends (mapcar #'company-mode/backend-with-yas company-backends))

(require 'yasnippet)
(yas-global-mode 1)
(yas-minor-mode 1)

**Comment by LuhengStat** [comment]
Just need to add the hook to the corresponding mode:

(add-hook 'ess-mode-hook
            (lambda ()
              (set (make-local-variable 'company-backends)
                   '((company-dabbrev-code company-yasnippet)))))
(add-hook 'elpy-mode-hook
            (lambda ()
              (set (make-local-variable 'company-backends)
                   '((company-dabbrev-code company-yasnippet)))))
(add-hook 'LaTeX-mode-hook
            (lambda ()
              (set (make-local-variable 'company-backends)
                   '((company-dabbrev-code company-yasnippet)))))

**Comment by LuhengStat** [comment]
The right way should be:
(add-hook 'ess-mode-hook
            (lambda ()
              (set (make-local-variable 'company-backends)
                   (list
                    (cons 'company-yasnippet
                          (car company-backends))))))
(add-hook 'elpy-mode-hook
            (lambda ()
              (set (make-local-variable 'company-backends)
                   (list
                    (cons 'company-yasnippet
                          (car company-backends))))))
(add-hook 'LaTeX-mode-hook
            (lambda ()
              (set (make-local-variable 'company-backends)
                   (list
                    (cons 'company-yasnippet
                          (car company-backends))))))
