### ISSUE TITLE
clang cannot complete inside a class under msys2(c++)

### ISSUE THREAD

**Issue by Epoch0404** [company-mode/company-mode#784]
environment: windows 10, using emacs through msys2
clang 5.0.1
emacs 25.2.1

emacs configuration associated with company mode:

(require 'company)
(add-hook 'after-init-hook 'global-company-mode)

(require 'company-c-headers)
(add-to-list 'company-backends 'company-c-headers)
(add-hook 'c++-mode-hook (lambda ()
			    (setq flycheck-clang-language-standard "c++11")
			   (flycheck-mode)
			    (setq company-clang-arguments '("-std=c++11"))
			   (setq company-clang-executable "c:/msys64/mingw64/bin/clang++.exe")))

issues:
for the situation below:
class foo{
public:
    int foo_arg1;
    int get_foo_arg1(){
        return foo_*** 
    }
};

the place with *** is where I supposed that clang should give me the completion, but clang doesn't work and I check the clang-output , it shows:
<stdin>:12:3: error: expected '}'
};
  ^
<stdin>:4:1: note: to match this '{'
{
^
<stdin>:9:12: error: 'foo' does not refer to a value
    return foo
           ^
<stdin>:3:7: note: declared here
class foo
      ^
<stdin>:9:15: error: expected '}'
    return foo<U+0000>
              ^
<stdin>:8:3: note: to match this '{'
  {
  ^
<stdin>:9:15: error: expected ';' after class
    return foo<U+0000>
              ^
              ;
4 errors generated.

and the clang-error  shows:

Mon Apr 23 14:45:02 2018
clang failed with error 1:
c:/msys64/mingw64/bin/clang++.exe -fsyntax-only -Xclang -code-completion-macros -x c++ -std=c++11 -Xclang -code-completion-at=-:9:15 -

<stdin>:12:3: error: expected '}'
};
  ^
<stdin>:4:1: note: to match this '{'
{
^
<stdin>:9:12: error: 'foo' does not refer to a value
    return foo
           ^
<stdin>:3:7: note: declared here
class foo
      ^
<stdin>:9:15: error: expected '}'
    return foo<U+0000>
              ^
<stdin>:8:3: note: to match this '{'
  {
  ^
<stdin>:9:15: error: expected ';' after class
    return foo<U+0000>
              ^
              ;
4 errors generated.

however, for another situation, if I separate the definition and implementation , clang works and give me right completion

like this:
class foo
{
public:
    int foo_arg1;
    int get_foo_arg1();
}

int foo::get_foo_arg1()
{
    return foo_***
}
 
this time it show the correct completion option 

btw, I have also tried the "human completion" by using M-x clang-complete at the first situation, and it says no completion at the point.

PS: I had experiment the same situation under ubuntu 16.04, with emacs 25.1 and clang3.8, it works for both situations.

**Comment by Epoch0404** [comment]
I guess it's clang's problem. 
I have tried the example at manjaro 17.1 with clang 6.0.0, and the first example cannot work too, so maybe it had some big change at version 5 of clang, or  maybe it's the problem of the repository of pacman?

**Comment by dgutov** [comment]
You can see the command line near `clang failed with error 1`. So you can experiment with running the same command from the terminal by replacing `-` with the file name, e.g.:

```sh
c:/msys64/mingw64/bin/clang++.exe -fsyntax-only -Xclang -code-completion-macros -x c++ -std=c++11 -Xclang -code-completion-at=-:9:15 test.cpp
```

If you find out something we need to change, I'm all ears.
