### ISSUE TITLE
complete problem with minus char

### ISSUE THREAD

**Issue by hubola** [company-mode/company-mode#786]
Hi,
When I use the company-mode auto completion then it's working but if there is an "-" in the function name it doesn't working from that character.

example:
(set  => I can select the set-cursor-color function
(set- => There is no match

What is the problem or how can I find the problem ?

My company config:
(add-hook 'after-init-hook 'global-company-mode)

(setq company-backends
  '(
    (
     company-files
     company-dabbrev
     company-keywords
     company-capf
     company-yasnippet
     )
    (company-abbrev company-dabbrev)
    ))

(setq company-dabbrev-downcase nil)

cheers,
Lajos

**Comment by dgutov** [comment]
Remove `company-dabbrev` from the first group.
