### ISSUE TITLE
Merging disparate backends

### ISSUE THREAD

**Issue by dgutov** [company-mode/company-mode#79]
`company-backends` allows list elements containing several backends. If it sees one, the results from the contained group are merged on an equal basis: if at least one of them returns a non-nil prefix, that prefix is returned, and all completion candidates returned from backends that respond with the same prefix are merged.

Problem: some backends are tied to specific major or minor modes, and others work in just about any context (like `dabbrev-code`, `keywords` and `yasnippet`). So creating a group containing one of the latter set and putting it at the front of `company-backends` virtually guarantees that no other elements of that list will be ever used.

Proposal: add a keyword that will separate "primary" backends from "secondary" backends in a group. `company--multi-backend-adapter` will only consider `prefix` results from backends before that keyword, and if all of them return nil, the next element in `company-backends` will be tried.

What name to use for the keyword?

Current candidates: `:secondary`, `:and`, `:skip-prefix`.

**Comment by vspinu** [comment]
I am reading through this discussion and, quite frankly I don't understand how you came up with `:with` keywords. 

The original requirement of @dgutov was 

> add a keyword that will separate "primary" backends from "secondary" backends in a group. company--multi-backend-adapter will only consider prefix results from backends before that keyword

And then @proofit404  proposed 

> :with also a nice keyword for this. But for example I want yasnippet back end work together with any other back end.

Let's consider `(A B :with C)`. The @dgutov's quote above means "Use C only if A or B are used" the @proofit404's quote says "Use C with A and B".  So how did you end up with implementing `Use A and B with C'? 

Now `:with` is also used in `company-sort-by-backend-importance` and its meaning there is completely unrelated to all of the discussion above. 

If anything, `:secondary` is the most generic and has clear correspondence to the English language. `(A B :secondary C)` means just that, `C` is the secondary backend. That being said, it's not a good API to use :with for two marginally related things. 

I think grouped backends should have similar interface to normal backends. You would like to have keywords for such actions like `:sorted`, `:duplicated`, `:ignore-case`, `:transform` that would overwrite the behavior of sub-backends. 

How about building grouped backends hierarchically? Each grouped backend is a sublist with its own key-value pairs and can contain other sub list. No need to limit yourself to 2 layers only.  Then have plist style key-value pairs within each group to qualify what it should do with respect to the immediate parent backend. For example

```elisp
`(setq company-backends 
      '(A 
        (B (C :importance 2)) ; a number to allow multiple importance levels; default 1
        (D E :sorted t :duplicated nil)
        (F G (C :when-others-matched t)) ; refers to parent group (F, G ..)
        (H I J :transformer 'my-function)
        ....
         ))
```

The current :with functionality is split into `:importance` and `:when-other-matched`.  
 
I can give it a stab if you like.

**Comment by proofit404** [comment]
Nesting candidates in such manner is overkill to me. Separation `:with` keyword into `:importance` and `:secondary` is necessary only if user want to customize sort order with different transformer in my opinion.

**Comment by vspinu** [comment]
It's a coherent implementation, and it's easy to program with. From user's prospective, it's all lisp, people are used to nested lists. It should be straightforward to make a nice customization interface for this.

**Comment by dgutov** [comment]
> So how did you end up with implementing `Use A and B with C'?

Because, in my mind, `:with` stands for "augmented with". Which makes C a subordinate of A and B.

> Now :with is also used in company-sort-by-backend-importance and its meaning there is completely unrelated to all of the discussion above.

"importance" is just how I called it when implementing that transformer, you're welcome to suggest a closer name. The request was exactly to separate candidates coming from before and after `:with`.

> If anything, :secondary is the most generic and has clear correspondence to the English language.

`:secondary` doesn't make it too obvious that it creates a relation between *all* backends in the group, not just the one coming before or after it.

`:when-others-matched` is closer, but "matched" doesn't seem to be the exactly right word, and `company-backends` is on track to obsoletion anyway (in favor of `completion-at-point-functions`) , so there's not much sense in creating this kind of big overhaul, with metadata and nesting.
