### ISSUE TITLE
Extend backend interface to provide option to insert the candidate

### ISSUE THREAD

**Issue by yyoncho** [company-mode/company-mode#790]
In lsp-mode the insert operation is calculated after the item is calculated after the item is inserted. Current solution uses post-completion to do the modification but it does not work in some of the cases(e. g. when completion is triggered by ".", when the item to complete contains "."). Also there is blinking when the item has been inserted because the real completion has to be retrieved from the remote server.

**Comment by dgutov** [comment]
> it does not work in some of the cases (e. g. when completion is triggered by ".", when the item to complete contains ".")

Why? How?

> Also there is blinking when the item has been inserted because the real completion has to be retrieved from the remote server.

Not sure what we're going to do about that. A new backend action, by itself, is not going to help.

**Comment by yyoncho** [comment]
So here it is how `company-lsp` mode works at this point: let say you have method `foo(String bar)`. In this case the company label(candidate) will be `foo(String bar)` and once you type `foo` and press enter you will have the text `foo(String bar)` inserted in  the buffer. Then `company` calls `post-completion` in which `company-lsp` should revert the buffer in the state before completion with prefix inserted and then calls the server to retrieve the correct text to be inserted which in this case is foo($1:bar). I noticed that `company-prefix` was not correct at that point so in order to workaround this `company-lsp` keeps a backup of the last prefix. Since the item resolving (i. e. the server call) is performed at this point having the wrong text inserted(`foo(String bar)`) there is a blinking.

Here it is one more case: let say you have to complete the following namespace: `com.bar.foo`. Once you type `com.b` the prefix is calculated incorretly to be `b`(should be `com.b`) since "." is completion character. Also there is a case in which the correct prefix is `b` e. g. when we are trying to complete `com.bMethodInvocation`).

I guess I might be missing something and there is a way to fix all issues but it will look like a workaroud of the fact that the backend cannot do the candidate insertion.IMO such method looks like a natural fit for company backend interface. I already have the fix and I am testing it and after that if you agree I could send you a pull request.

**Comment by yyoncho** [comment]
Yes, it is up to the backend to calculate the prefix but in this case, the correct prefix is either `com.b` or just `b` depending on the selected item.

> Hmm, you mean leave the insertion up to the backend entirely?

Yes.
> Will that also help get rid of the workaround where "company-lsp keeps a backup of the last prefix"?

Yes, the point is that lsp is not interested in the prefix at all - it just wants the buffer to be in the state before the candidate has been inserted. 
Here it is the change that I am testing right now(which seems to work for company-lsp).
https://github.com/yyoncho/company-mode/commit/bccf0f64a83af237a8233b710b6189a893a0208c

**Comment by dgutov** [comment]
> the point is that lsp is not interested in the prefix at all

But how does the popup look when there's no single prefix? Are the texts all properly aligned?

**Comment by yyoncho** [comment]
>> the point is that lsp is not interested in the prefix at all

> But how does the popup look when there's no single prefix? Are the texts all properly aligned?

By not interested in the prefix I mean that the insert candidate function of the `company-lsp` does not need current prefix unlike the company--insert-candidate which perfoms delete prefix/insert candidate.

**Comment by dgutov** [comment]
I'm asking about the popup. It must have a related problem.

**Comment by yyoncho** [comment]
Closing the issue - the problem is that even if we do the insertion `company-lsp` still have to calculate the correct prefix, therefore, it could be able to update the item post completion.
