### ISSUE TITLE
Help with creating Octave backend?

### ISSUE THREAD

**Issue by okamsn** [company-mode/company-mode#791]
Hello,

I am trying to create a backend for GNU Octave, which I have put together from bits and pieces on the Web. So far, my functions seem to be working individually for the most part, but I'm not sure how to bring it all together. The Octave REPL has a command "completion_matches", which I've been trying to use.

To get the prefix, I have 
```lisp
(defun company-octave-grab-prefix ()
  "Get the completion target, including '.' for completing struct members. Octave REPL has a function 'completion_matches' to give candidates."
  (interactive)
  (if (looking-at "\\_>")
      (buffer-substring-no-properties (point)
                        (save-excursion
                          (skip-chars-backward "a-zA-Z_.0-9")
                          (point)))
    (unless (and (char-after)
                 (eq (char-syntax (char-after)) ?w))
      "")))
```

It works except for words ending with '.', which I have to correct still. Without the `(looking-at)` condition, it works.

To get the possible matches from the Octave REPL, I have

```lisp
(defun company-octave-get-candidates (prefix)
  "Use Octave REPL's 'completion_matches' function to get candidates. If candidate has a '.' (i.e., it's completing a structure member), get the member only."
  (inferior-octave-send-list-and-digest
   (list (concat "completion_matches ('" prefix "');\n")))
  ;; Split candidates if they have an '.', keeping the last resulting item, then combine the resulting lists
  (mapcan (lambda (x) (if (listp x) x nil))
          (cl-loop for candidate in inferior-octave-output-list
                   collect (last (split-string candidate "\\.")))))
```

And this will return a list of completions. For example, if I do 
```octave
someName = struct('someMember', 5, 'someOtherMember', 7);
```
And test `(comapny-octave-get-candidates "someN")` it will return `("someName")` and for `(comapny-octave-get-candidates "someName.")` it will return `("someMember" "someOtherMember")`. 

I have tried defining the backend as 

```lisp
(defun company-octave-backend (command &optional arg &rest ignored)
  "Define the backend for interacting with the Octave REPL."
  (interactive (list 'interactive))
  (cl-case command
    (interactive (company-begin-backend 'company-octave-backend))
    (prefix (if (eq major-mode 'octave-mode)
                (company-octave-grab-prefix)))
    (candidates (company-octave-get-candidates))
    ;; (annotation ())
    (init (inferior-octave))))
```
For Octave, I want to try to use company-capf, company-files, and company-dabbrev-code, so I do

```lisp
(add-to-list 'company-backends '(company-octave-backend company-dabbrev-code company-capf company-files))
```
However, it doesn't seem to be working. I understand that for the case of words ending with '.', I must learn to use a better regex, but why doesn't it work for normal symbols?

Thank you.

**Comment by dgutov** [comment]
Umm. Have you tried `M-x run-octave`?

`company-capf` should provide completios after that.

**Comment by okamsn** [comment]
Yes, I can use `company-capf` to get completions from the REPL, but it's not providing candidates from the other backends.

Can I use `company-dabbrev-code` to complete words in the buffer, that I have not submitted to the Octave REPL? I thought that is what it did, but I may have misunderstood.

For example, if I do
```octave
someName = 3; someOtherName=5;
```
I'm trying to have both show when I type the word `some`. Currently, I must pass the variable definition to the Octave REPL, and then it will complete for that variable. 

Have I done something wrong adding the grouped backends to the backend list?

Thank you.

**Comment by dgutov** [comment]
Your example includes `company-octave-backend`. Have you tried without it?

**Comment by okamsn** [comment]
I have tried `(add-to-list 'company-backends '(company-dabbrev-code company-capf company-files))` and then enabling Company mode. The command `company-capf` does not work, but the command `company-complete` makes a pop-up of the correct completions. Is this normal behavior?

Prefixes are now being collect, using 
```lisp
(if (or (looking-at "\\_>") (looking-back "[a-zA-z_0-9]+\\.")) ...)
```
However, for completing structure members, completing the member replaces the structure name. For example,  if I have
```octave
dog = struct; dog.tail = 1; dog.paw = 3;
```
and I try to complete 'dog.', I will see the correct candidates 'paw' and 'tail' in the pop-up, but selecting one of these candidates will replace the word 'dog.' with 'paw' or 'tail'. Is there a way to change this?

If not, when Octave returns a match for "dog." it will give `("dog.paw" "dog.tail")`, so is there a way to display the candidates differently than what will be inserted into the buffer?

Thank you.

**Comment by dgutov** [comment]
> The command company-capf does not work, but the command company-complete makes a pop-up of the correct completions. Is this normal behavior?

Not really. I mean, it might be normal is there is no external Octave process, but it's not what you'd want to have.

> (if (or (looking-at "\\_>") (looking-back "[a-zA-z_0-9]+\\.")) ...)

Where is this code from?

> so is there a way to display the candidates differently than what will be inserted into the buffer?

That depends on whether you are the author of the backend in question.
