### ISSUE TITLE
completion-backends: Group with differing prefixes

### ISSUE THREAD

**Issue by ecraven** [company-mode/company-mode#792]
I'm trying to get good completion in eshell, with the following problem:
I have two backends, company-pcomplete (which returns only the last token before point as a prefix), and company-eshell-autosuggest (which returns the entire command line so far as a prefix). I've tried grouping both with variants of `:with` and `:separate`, but cannot get company-mode to show completions from *both* backends.
For example, with the following input:
````
> ls foo|
````
company-pcomplete returns "foo" for prefix, while company-eshell-autosuggest returns "ls foo".

How do I correctly set this up so that *both* are asked for candidates and all candidates appear in one long list?

[clarification: company-pcomplete is a fallback to eshell's builtin pcomplete, eshell-autosuggest completes based on history (so it needs the entire command line, not just the last token, like pcomplete)]

**Comment by dgutov** [comment]
Currently impossible, sorry. Prefix equality is the criterion on which we combine the results from the grouped backends.

**Comment by ecraven** [comment]
Hm.. any idea on how to implement this, maybe with a custom backend that somehow combines both?

**Comment by dgutov** [comment]
With some `substring` calls, probably. :)

There is an example in the `candidates` implementation in `company-capf`, but it's pretty complex.

**Comment by dgutov** [comment]
I'm going to close this in favor of #426.
