### ISSUE TITLE
company-files.el: add support for environment variables completion 

### ISSUE THREAD

**Issue by cslux** [company-mode/company-mode#793]
Hey!

I was wondering if it makes sense to add support to complete on environment variables, especially \\${?HOME}?. 

So far I was able to add support to get completion candidates, but when I complete, the content gets insert far back. This is because $HOME is shorter than the substituted value of $HOME, but I wasn't able to find the location where the calculation happens. Does this happen in company-files.el or in company.el?

``` patch
1 file changed, 3 insertions(+), 2 deletions(-)
company-files.el | 5 +++--

modified   company-files.el
@@ -67,7 +67,7 @@ The values should use the same format as `completion-ignored-extensions'."
   (let* ((root (if (eq system-type 'windows-nt)
                    "[a-zA-Z]:/"
                  "/"))
-         (begin (concat "\\(?:\\.\\{1,2\\}/\\|~/\\|" root "\\)")))
+         (begin (concat "\\(?:\\.\\{1,2\\}/\\|~/\\|\\${?HOME}?\\|" root "\\)")))
     (list (concat "\"\\(" begin "[^\"\n]*\\)")
           (concat "\'\\(" begin "[^\'\n]*\\)")
           (concat "\\(?:[ \t=]\\|^\\)\\(" begin "[^ \t\n]*\\)"))))
@@ -77,7 +77,8 @@ The values should use the same format as `completion-ignored-extensions'."
   ;; When surrounded with quotes, it can include spaces.
   (let (file dir)
     (and (cl-dolist (regexp company-files--regexps)
-           (when (setq file (company-grab-line regexp 1))
+           (when (and (setq file (company-grab-line regexp 1))
+                      (setq file (substitute-in-file-name file)))
              (cl-return file)))
          (company-files--connected-p file)
          (setq dir (file-name-directory file))
```

Thank you for your help!

Christian

**Comment by dgutov** [comment]
> wondering if it makes sense to add support to complete on environment variables

Umm, I'd say that maybe not.

`company-files` can and often is useful in contexts where one can enter a file path (essentially, a source file for almost any programming language). You can only enter environment variables this way, however, in only a few languages (basically, shell scripts).

If the completion function in `sh-mode` doesn't support environment variables completion, maybe file a request (with `M-x report-emacs-bug`).

**Comment by cslux** [comment]
Thank you for your answer. 

Yeah, makes sense to add support to `sh-mode` not `company-files.el`. 

I'm closing this issue.
