### ISSUE TITLE
How to create a company transformer for a specific mode company-keywords?

### ISSUE THREAD

**Issue by stardiviner** [company-mode/company-mode#794]
I'm adding `company-keywords` support for `dockerfile-mode`.
```elisp
(add-to-list 'company-keywords-alist
               '(dockerfile-mode
                 "FROM"
                 "ADD" "COPY"
                 "RUN" "CMD" "ENTRYPOINT"
                 "VOLUME" "ENV" "EXPOSE"  "LABEL" "ARG"
                 "STOPSIGNAL" "USER"  "WORKDIR"
                 "ONBUILD" "HEALTHCHECK" "SHELL"))
```
But typing upper case keyword is not comfortable, I wish it can be a list of lower-case keywords, and use `company-transformers` (which is specific on a major mode like `dockerfile-mode`) to auto insert a upper-case converted keywords into buffer. Just like package [sqlup-mode](https://github.com/trevoke/sqlup-mode.el) did.
I think this method is useful for many modes which also use upper-case keywords. WDYT?

**Comment by dgutov** [comment]
I think you should create a separate backend, and mix it into the group with `company-keywords`.
