### ISSUE TITLE
Prefix should return nil when suitable, but lots of backends don't

### ISSUE THREAD

**Issue by wyuenho** [company-mode/company-mode#800]
According to the docs and source code, if a backend returns nil in response to a prefix command, the next backend will be given a chance to run, but a lot of simple backends like keywords, files and dabbrev-code just return an empty string when failing to grab a prefix, so they can't be composed in a backend list.

I'm not sure if this is a new change, but to me, backends should only return `'stop` or `""` if they are highly accurate backends that people usually put in front, like clang, css, xcode, semantic and eclim, everything else should return a `nil` when suitable so people can mix and match fail back backend orders.

**Comment by dgutov** [comment]
> when failing to grab a prefix

What do you mean by "failing"?

> everything else should return a nil when suitable

When?

**Comment by wyuenho** [comment]
Ahhh nevermind, I've finally achieved what I want with the `:separate` keyword.

Thank you!
