### ISSUE TITLE
CompilerException when completing at point

### ISSUE THREAD

**Issue by dpetranek** [company-mode/company-mode#801]
This issue only shows up when using Cider - company continues to work just fine for e.g. elisp

I start typing, and after 3 characters (in this example 'def') are entered company attempts to complete, I get this message:

> Company: backend company-capf error "Symbol’s function definition is void: CompilerException" with args (candidates def)

This is the result after enabling `toggle-debug-on-error`:

> Debugger entered--Lisp error: (void-function CompilerException)
>   CompilerException("def" nil t)
>   all-completions("def" CompilerException nil)
>   completion-pcm--all-completions("" ("def" point) CompilerException nil)
>   completion-basic-all-completions("def" CompilerException nil 3)
>   #[257 "\300
> \2368\301\242\302\242\303\304\242$\207" [2 ("def") (CompilerException) nil (3) completion-styles-alist] 6 "\n\n(fn STYLE)"](basic)
>   completion--some(#[257 "\300
> \2368\301\242\302\242\303\304\242$\207" [2 ("def") (CompilerException) nil (3) completion-styles-alist] 6 "\n\n(fn STYLE)"] (basic partial-completion emacs22))
>   completion--nth-completion(2 "def" CompilerException nil 3 nil)
>   completion-all-completions("def" CompilerException nil 3)
>   company-capf(candidates "def")
>   apply(company-capf (candidates "def"))
>   company-call-backend-raw(candidates "def")
>   company--fetch-candidates("def")
>   company-calculate-candidates("def")
>   company--begin-new()
>   company--perform()
>   company-auto-begin()
>   company-idle-begin(#<buffer test.clj> #<window 12 on test.clj> 1662 34973)
>   apply(company-idle-begin (#<buffer test.clj> #<window 12 on test.clj> 1662 34973))
>   timer-event-handler([t 23330 32543 238085 nil company-idle-begin (#<buffer test.clj> #<window 12 on test.clj> 1662 34973) nil 685000])
>

**Comment by dgutov** [comment]
> company continues to work just fine for e.g. elisp

Please report this to CIDER, then.

**Comment by dpetranek** [comment]
I've reported it to CIDER, but I'm now seeing it for other backends, currently in js2-mode. So it may not be the fault of a third party.

Here's the new stacktrace:

> Debugger entered--Lisp error: (void-function CompilerException)
>   CompilerException("CloudApiSer" nil t)
>   all-completions("CloudApiSer" CompilerException nil)
>   completion-pcm--all-completions("" ("CloudApiSer" point) CompilerException nil)
>   completion-basic-all-completions("CloudApiSer" CompilerException nil 11)
>   #[257 "\300
> \2368\301\242\302\242\303\304\242$\207" [2 ("CloudApiSer") (CompilerException) nil (11) completion-styles-alist] 6 "\n\n(fn STYLE)"](basic)
>   completion--some(#[257 "\300
> \2368\301\242\302\242\303\304\242$\207" [2 ("CloudApiSer") (CompilerException) nil (11) completion-styles-alist] 6 "\n\n(fn STYLE)"] (basic partial-completion emacs22))
>   completion--nth-completion(2 "CloudApiSer" CompilerException nil 11 nil)
>   completion-all-completions("CloudApiSer" CompilerException nil 11)
>   company-capf(candidates "CloudApiSer")
>   apply(company-capf (candidates "CloudApiSer"))
>   company-call-backend-raw(candidates "CloudApiSer")
>   company--fetch-candidates("CloudApiSer")
>   company-calculate-candidates("CloudApiSer")
>   company--begin-new()
>   company--perform()
>   company-auto-begin()
>   company-idle-begin(#<buffer LoadDefinitionEditCtrl.js> #<window 6 on *Backtrace*> 12517 1033)
>   apply(company-idle-begin (#<buffer LoadDefinitionEditCtrl.js> #<window 6 on *Backtrace*> 12517 1033))
>   timer-event-handler([t 23331 60044 591411 nil company-idle-begin (#<buffer LoadDefinitionEditCtrl.js> #<window 6 on *Backtrace*> 12517 1033) nil 268000])

Company version: 0.9.6
Emacs version: GNU Emacs 25.3.1 (x86_64-pc-linux-gnu, GTK+ Version 3.22.28) of 2018-04-10

**Comment by dgutov** [comment]
There hasn't been any significant changes in company-mode in months. And you're using a years-old version of Emacs. So I find the fault being here quite unlikely.

Anyway, what's the backend used there? Try `M-x company-diag`.

**Comment by dpetranek** [comment]
It's almost certainly a problem I caused for myself, but I've not had much luck debugging it.

M-x company-diag doesn't work, it produces the same error. Here's the stacktrace:

> Debugger entered--Lisp error: (void-function CompilerException)
>   CompilerException("" nil t)
>   all-completions("" CompilerException nil)
>   completion-pcm--all-completions("" (point) CompilerException nil)
>   completion-basic-all-completions("" CompilerException nil 0)
>   #[257 "\300
> \2368\301\242\302\242\303\304\242$\207" [2 ("") (CompilerException) nil (0) completion-styles-alist] 6 "\n\n(fn STYLE)"](basic)
>   completion--some(#[257 "\300
> \2368\301\242\302\242\303\304\242$\207" [2 ("") (CompilerException) nil (0) completion-styles-alist] 6 "\n\n(fn STYLE)"] (basic partial-completion emacs22))
>   completion--nth-completion(2 "" CompilerException nil 0 nil)
>   completion-all-completions("" CompilerException nil 0)
>   company-capf(candidates "")
>   apply(company-capf (candidates ""))
>   company-call-backend-raw(candidates "")
>   apply(company-call-backend-raw (candidates ""))
>   company--force-sync(company-call-backend-raw (candidates "") company-capf)
>   company-call-backend(candidates "")
>   company-diag()
>   funcall-interactively(company-diag)
>   call-interactively(company-diag record nil)
>   command-execute(company-diag record)
>   #[257 "\306!\262\307\300!\203

**Comment by dgutov** [comment]
> it produces the same error

Sorry, it should catch that error now. Please try the latest master.

**Comment by dpetranek** [comment]
Sorry for the delay, I've tried it now.My company-version is still 0.9.6, but the folder in my /elpa directory is company-20180615.1508 and I've verified that the above commit is present.

I still get the same CompilerException, though:

> Debugger entered--Lisp error: (void-function CompilerException)
>   CompilerException("def" nil t)
>   all-completions("def" CompilerException nil)
>   completion-pcm--all-completions("" ("def" point) CompilerException nil)
>   completion-basic-all-completions("def" CompilerException nil 3)
>   #[257 "\300
> \2368\301\242\302\242\303\304\242$\207" [2 ("def") (CompilerException) nil (3) completion-styles-alist] 6 "\n\n(fn STYLE)"](basic)
>   completion--some(#[257 "\300
> \2368\301\242\302\242\303\304\242$\207" [2 ("def") (CompilerException) nil (3) completion-styles-alist] 6 "\n\n(fn STYLE)"] (basic partial-completion emacs22))
>   completion--nth-completion(2 "def" CompilerException nil 3 nil)
>   completion-all-completions("def" CompilerException nil 3)
>   company-capf(candidates "def")
>   apply(company-capf (candidates "def"))
>   company-call-backend-raw(candidates "def")
>   company--fetch-candidates("def")
>   company-calculate-candidates("def")
>   company--begin-new()
>   company--perform()
>   company-auto-begin()
>   company-idle-begin(#<buffer loader.clj> #<window 3 on test.clj> 2485 39037)
>   apply(company-idle-begin (#<buffer loader.clj> #<window 3 on test.clj> 2485 39037))
>   timer-event-handler([t 23337 2837 732616 nil company-idle-begin (#<buffer test.clj> #<window 3 on test.clj> 2485 39037) nil 603000])

**Comment by dgutov** [comment]
The above commit only fixed `company-diag`. You can try it to get more info.

**Comment by dpetranek** [comment]
Okay, I understand now. Here's the company-diag output:

> Emacs 25.3.1 (x86_64-pc-linux-gnu) of 2018-06-07 on localhost
> Company 0.9.6
> 
> company-backends: (company-tide company-bbdb company-nxml company-css company-eclim company-semantic company-clang company-xcode company-cmake company-capf company-files
>               (company-dabbrev-code company-gtags company-etags company-keywords)
>               company-oddmuse company-dabbrev)
> 
> Used backend: company-capf
> Major mode: clojure-mode
> Prefix: ""
> Completions: none(error fetching)

**Comment by dpetranek** [comment]
No, js2-mode is currently working fine.
