### ISSUE TITLE
Option to add pcomplete to capf backend

### ISSUE THREAD

**Issue by memeplex** [company-mode/company-mode#804]
For modes that use pcomplete a common pattern is adding pcomplete-completions-at-point to completion-at-point-functions so as to channel pcomplete through company capf backend.

The major problem with this is not that it requires extra setup but that this setup interferes with the one provided by the underlying major mode. Take for example eshell that explicitly distinguishes between the pcomplete and cap lists, you don't want to mess with those lists.

So why not adding an option to include the pcomplete cap functions into the capf backend?

**Comment by memeplex** [comment]
See for instance the implementation of eshell. They use pcomplete (Tab) for command completion and cap (M-Tab) for elisp completion. Furthermore they dynamically switch the cap functions since they use cap as a workaround fallback, because of some pcomplete corner cases.

The general point is that having to change the cap functions just to make company work with pcomplete is not the cleaner solution since it could invalidate some assumptions of the major mode which set them in the first place. In the case of eshell it would mix two sources of completions that are intended to be separated (maybe you want them both at company level but that's another matter) and it would fail when eshell dynamically changes the list.

In any case I would add pcomplete to cap functions in an around advice to the capf backend, not as a permanent change of the list. But an option would be preferable IMO. It would signal that company is accommodating to the underlying preexisting frameworks and not the other way around.

**Comment by memeplex** [comment]
Or maybe a pcomplete backend. This seems cleaner to me, I didn't suggest it at first because I assumed it would be easier to modify the list capf already consumes.

**Comment by dgutov** [comment]
> Furthermore they dynamically switch the cap functions since they use cap as a workaround fallback, because of some pcomplete corner cases.

I'm not sure which function you mean exactly, but doesn't it only manipulate the local value?

**Comment by memeplex** [comment]
I think we have a misunderstanding here. I'm not saying that company is
overriding/interfering with the major mode behavior, I'm just saying that
in order to get pcomplete in company **the user** has to add it to the
(local or global, that isn't my point) list of cap functions, because this
is the only way company currently provides to access pcomplete. Now, this
could interfere with the "optimal" configuration provided by the mode that
may deliberately not include pcomplete in the list of cap functions. It
would be better to add pcomplete to company without going through the cap
functions.

Regarding the eshell functions, take a quick look at the ones bound to Tab
and M-Tab and you will see the kind of messy stuff that is happening there.

**Comment by dgutov** [comment]
> you will see the kind of messy stuff that is happening there

I'm not a fan, but I think it's something to be fixed in Emacs itself. So please file bug reports, patches, etc.

In the meantime, is there a particular user scenario that your suggestion helps with?
