### ISSUE TITLE
How to complete if there's a single candidate with no preview/tooltip?

### ISSUE THREAD

**Issue by vemv** [company-mode/company-mode#807]
Hi!

I don't know how to write a frontend (if that was needed) to blindly complete something without a preview.

I tend to prefer that behavior to that of `company-preview-frontend`, even if it is a bit risky.

One could call it 'optimistic' completion (you hope that you won't have to undo), as opposed to the pessimistic approach of double-checking a candidate (which makes me hit TAB twice / think twice).

Thanks - Victor

**Comment by dgutov** [comment]
I don't understand the question. Frontends don't perform completion, they only show information.

Have you tried `company-tng`?

**Comment by vemv** [comment]
Hi, thanks for the answer!

I want company-mode to complete an autocompletion with a single TAB hit _if_ there's only one candidate, without preview or popup.

Taking a look to company-tng.el, thanks. Assuming it does that, can it coexist gracefully with the default frontends? i.e. it is only used if that is the 'last resource'.

**Comment by dgutov** [comment]
I'm not quite sure how you want it to work, but company-tng is unlikely to be the exact match (it has its own workflow).

You could write your own command that checks that there's only one completion, and if so, applies it.

**Comment by vemv** [comment]
Thank you for the reply.

So there's no built-in for the described behavior? It's the one I get from
stock Atom for example.

Writing my own could work but I'm afraid of relying on company internals.

**Comment by dgutov** [comment]
Could you show how it works in Atom? With a gif, maybe.

**Comment by vemv** [comment]
## Atom 

### Scenario 1

Cursor is at `|`

```ruby
class AddExclusive < ActiveRecord::Migration
  def change
    add_column :foo, :exclusive, :boolean
    add_col|
  end
end
```

If I hit the keybinding (let's call it `<tab>` for simplicity), `add_col` will expand to `add_column`, with no preview, popup, or confirmation.

### Scenario 2

Cursor is at `|`

```ruby
class AddExclusive < ActiveRecord::Migration
  def change
    add_column :foo, :exclusive, :boolean
    add_collation :bar
    add_col|
  end
end
```

If I hit `<tab>`, a popup will appear offering me the `add_column` and `add_collation` candidates, and I can further interact with the popup, cancel it, etc.

**Comment by dgutov** [comment]
Bind `TAB` to `company-complete`, then.

**Comment by vemv** [comment]
`company-complete` by default shows the preview, due to
`company-preview-if-just-one-frontend`. That makes me hit TAB twice. If I
remove that frontend, I still have to hit TAB twice.

**Comment by dgutov** [comment]
No, it doesn't. The preview frontend is only shown when you're simply typing and completion begins on a timer.

**Comment by vemv** [comment]
Perhaps the fact that I (setq company-idle-delay nil) in my config has
something to do

**Comment by dgutov** [comment]
Nope.

**Comment by vemv** [comment]
This was due to having both `company-dabbrev-code` and `company-dabbrev` in `company-backends`. Removing the former fixed the 'double tab' behavior for me.

Thanks for the guidance!
