### ISSUE TITLE
Regex in company-dabbrev-code is not customizable

### ISSUE THREAD

**Issue by vemv** [company-mode/company-mode#808]
Hey there,

company-dabbrev.el has the `company-dabbrev-char-regexp` defcustom, while company-dabbrev-code.el has no customizable regexp.

One might want to customize such regexes for per-language rules (lisps accept `-` as part of a word, most other languages don't)

Thanks - Victor

**Comment by dgutov** [comment]
> lisps accept - as part of a word, most other languages don't

Doesn't `company-dabbrev-code--make-regexp` already handle this case? By using the "word constituent" and "symbol constituent" constructs.

**Comment by vemv** [comment]
Mind to point out the specific part where that happens? There might be some elisp regexp idiosyncracy I'm unaware of.

**Comment by dgutov** [comment]
The `\\s_` part.

**Comment by dgutov** [comment]
In Lisp (Emacs Lisp, at least), `-` is not part of a word. But it's part of a symbol name.

**Comment by vemv** [comment]
> The \\s_ part.

Is `\\s_` aware of the major mode?

(I'm trying to understand why the same regexp is applied to different languages)

**Comment by dgutov** [comment]
Yes. It means "symbol constituent": https://www.gnu.org/software/emacs/manual/html_node/elisp/Regexp-Backslash.html#Regexp-Backslash, and those are described in the syntax table.

The major mode sets up the syntax table.

**Comment by vemv** [comment]
Alright! Thanks for the explanation.

Closing this then.

In any case it might be worth adding a docstring to `company-dabbrev-code--make-regexp` explaining that regex customization goes through the mode's syntax table (I guess many emacs users don't know that)

**Comment by dgutov** [comment]
Err, usually somebody tried to change something when they encounter a problem. It would be great to know which problem you had.

**Comment by vemv** [comment]
It's a bit complicated/custom and solved by now, but thanks for the willingness.
