### ISSUE TITLE
Exceptions in the latest update

### ISSUE THREAD

**Issue by seagle0128** [company-mode/company-mode#809]
I got these errors after upgrading to the latest version.

```elisp
Debugger entered--Lisp error: (wrong-type-argument listp 0)
  company-fill-propertize(#("search" 0 2 (face (completions-common-part)) 2 3 (face (completions-first-difference))) nil 40 t " " " ")
  company--create-lines(0 7)
  company-pseudo-tooltip-show(8 12 0)
  company-pseudo-tooltip-show-at-point(3319 2)
  company-pseudo-tooltip-frontend(post-command)
  company-pseudo-tooltip-unless-just-one-frontend(post-command)
  company-call-frontends(post-command)
  company-post-command()
  company-idle-begin(#<buffer init-window.el> #<window 3 on init-window.el> 2836 3319)
  apply(company-idle-begin (#<buffer init-window.el> #<window 3 on init-window.el> 2836 3319))
  timer-event-handler([t 23356 37467 797826 nil company-idle-begin (#<buffer init-window.el> #<window 3 on init-window.el> 2836 3319) nil 962000])
```

**Comment by dgutov** [comment]
@joaotavora Please take a look.

**Comment by dgutov** [comment]
@joaotavora And could you also add a high-level test for this scenario? Similarly to `company-fill-propertize-overrides-face-property` etc.

**Comment by dgutov** [comment]
OK, I fixed it by reverting the face<->font-lock-face change.

It would be great to have a test or two for this, though.

**Comment by joaotavora** [comment]
Hehe, curious how this was fixed by reverting your suggestion.  I guess I should have tested better before applying it. I can't reproduce though.

**Comment by joaotavora** [comment]
> I can't reproduce thoug

( Didn't try very hard yet also)

**Comment by dgutov** [comment]
> Can you explain summarily what was happening?

The backtrace shows that the completion was propertized with `face` and not `font-lock-face`. Apparently the latter is only used by the partial-completion completion style, and the "normal" ones use `face`. Looks like a random historical accident.

**Comment by joaotavora** [comment]
> My suggestion was to look up face, though. :) That actually seems to work, even if it fails on the CI.

Right. Sorry then.

**Comment by joaotavora** [comment]
Anyway, the tests do test rendering, so I'm not sure what happened. And are "high level" (enable company-mode and simulate calling `company-complete`)

**Comment by dgutov** [comment]
All the present tests use partial completion. A test using the `basic` completion style should demonstrate this problem. E.g.

```
  (company-capf-with-buffer
    "(with|)"
    (company-mode)
  ...
```

**Comment by joaotavora** [comment]
alright, I'll add the test. But the real fix should be another than  24bbc85, I think.  The match request shouldn't ever return a cons.

**Comment by joaotavora** [comment]
i.e. either this
```diff
diff --git a/company-capf.el b/company-capf.el
index 7e76dfc..47bb084 100644
--- a/company-capf.el
+++ b/company-capf.el
@@ -131,7 +131,7 @@
                    ((and match-start (not has-face-p))
                     (push (cons match-start pos) chunks)
                     (setq match-start nil))))
-           (if chunks (nreverse chunks) (cons 0 (length arg)))))))
+           (if chunks (nreverse chunks) (list (cons 0 (length arg))))))))
     (`duplicates t)
     (`no-cache t)   ;Not much can be done here, as long as we handle
                     ;non-prefix matches.

```

or this

```diff
diff --git a/company-capf.el b/company-capf.el
index 7e76dfc..f1ceb1e 100644
--- a/company-capf.el
+++ b/company-capf.el
@@ -131,7 +131,7 @@
                    ((and match-start (not has-face-p))
                     (push (cons match-start pos) chunks)
                     (setq match-start nil))))
-           (if chunks (nreverse chunks) (cons 0 (length arg)))))))
+           (if chunks (nreverse chunks) (length arg))))))
     (`duplicates t)
     (`no-cache t)   ;Not much can be done here, as long as we handle
                     ;non-prefix matches.
```

**Comment by joaotavora** [comment]
Otherwise it will break again if some completion method doesn't have neither `face` or `font-lock-face`.

**Comment by dgutov** [comment]
Sounds good. What if you return `nil` there, though?

**Comment by joaotavora** [comment]
> What if you return nil there, though?

nil should be fine (no regions). It can't happen right now.  Do you want it to? why?

**Comment by joaotavora** [comment]
I do think we better keep the "or". Even when testing interactively, the `company-non-prefix-fancy-capf-highlighting` test fails.

**Comment by dgutov** [comment]
> nil should be fine (no regions). It can't happen right now. Do you want it to? why?

Instead of `(length arg)`? Because then it will default to `company-common`, which is the length of the actual prefix match.

**Comment by dgutov** [comment]
> Even when testing interactively, the company-non-prefix-fancy-capf-highlighting test fails.

Apparently, because ERT uses a temp buffer, and font-lock-mode doesn't get enabled there. Not sure how to force it.

Hopefully the performance overhead is not much.

**Comment by joaotavora** [comment]
> Apparently, because ERT uses a temp buffer, and font-lock-mode doesn't get enabled there. Not sure how to force it.

But tests run in "my" temp buffer, not ERT's. 

> Instead of (length arg)? Because then it will default to company-common, which is the length of the actual prefix match.

I see. Then it's a good idea, yes. I confused `length arg` with `company-common`

**Comment by dgutov** [comment]
> But tests run in "my" temp buffer, not ERT's.

Which also has a name beginning with a space, thus font-lock-mode does not get enabled.

I think using `ert-with-test-buffer` can solve that problem.

**Comment by joaotavora** [comment]
> Which also has a name beginning with a space, thus font-lock-mode does not get enabled. font-lock-mode

Hmm I did try `(font-lock-mode 1)` and `(font-lock-ensure)`.

> I think using ert-with-test-buffer can solve that problem.

It doesn't.  But it's a nice macro I didn't know about.

**Comment by dgutov** [comment]
Unfortunately, `font-lock-mode` disables itself `(when (or noninteractive (eq (aref (buffer-name) 0) ?\s))`.

**Comment by joaotavora** [comment]
> noninteractive

We can let-bind that, right?

> (eq (aref (buffer-name) 0) ?\s))

Shouldn't ert-with-test-buffer take care of that?

**Comment by dgutov** [comment]
> Shouldn't ert-with-test-buffer take care of that?

That was my thinking. Didn't have time to try and investigate so far.
