### ISSUE TITLE
company-ispell-dictionary only works if dictionary file open in emacs

### ISSUE THREAD

**Issue by bbo2adwuff** [company-mode/company-mode#811]
Using plain word-list dictionary with `company-ispell-dictionary` only works when I have the dictionary file (in my case `english-words.txt`) open in a buffer.

Just copied the setup from here: https://emacs.stackexchange.com/a/18522/19743

```elisp
(require 'company)
(add-hook 'after-init-hook 'global-company-mode)

(defun text-mode-hook-setup ()
  ;; make `company-backends' local is critcal
  ;; or else, you will have completion in every major mode, that's very annoying!
  (make-local-variable 'company-backends)

  ;; company-ispell is the plugin to complete words
  (add-to-list 'company-backends 'company-ispell)

  ;; OPTIONAL, if `company-ispell-dictionary' is nil, `ispell-complete-word-dict' is used
  ;;  but I prefer hard code the dictionary path. That's more portable.
  (setq company-ispell-dictionary (file-truename "~/.emacs.d/misc/english-words.txt")))

(add-hook 'text-mode-hook 'text-mode-hook-setup)
```

Completion works when having `english-words.txt` open in a buffer. When killing the buffer completion does not work anymore. I guess it should work without having the file open in a buffer, right?

emacs 26.1
company 20180704.701

**Comment by dgutov** [comment]
What does `M-x ispell-check-version` tell you?

**Comment by bbo2adwuff** [comment]
`@(#) International Ispell Version 3.1.20 (but really Aspell 0.60.6.1)`

**Comment by dgutov** [comment]
Ah, the problem is likely that this backend is at the end of the list. And one of the elements in the default value takes over, e.g. the group that contains the `company-dabbrev` backend.

You need to make sure that this backend is reached. E.g. by `(setq company-backends '(company-aspell)`, instead of `add-to-list`.

**Comment by bbo2adwuff** [comment]
Issue is not solved by using `setq` instead of `add-to-list`. I still need to have the dictionary txt file open in another buffer.

I use text.txt buffer for testing, see below.

When using `setq` then I get following value for `company-backends`:

```
Value:
(company-ispell company-bbdb company-eclim company-semantic company-clang company-xcode company-cmake company-capf company-files
                (company-dabbrev-code company-gtags company-etags company-keywords)
                company-oddmuse company-dabbrev)
Original value was 
(company-bbdb company-eclim company-semantic company-clang company-xcode company-cmake company-capf company-files
              (company-dabbrev-code company-gtags company-etags company-keywords)
              company-oddmuse company-dabbrev)
Local in buffer test.txt; global value is (company-ispell)
```



When using `add-to-list` then I get following value for `company-backends`:
```
Value:
(company-bbdb company-eclim company-semantic company-clang company-xcode company-cmake company-capf company-files
              (company-dabbrev-code company-gtags company-etags company-keywords)
              company-oddmuse company-dabbrev company-ispell)
Original value was 
(company-bbdb company-eclim company-semantic company-clang company-xcode company-cmake company-capf company-files
              (company-dabbrev-code company-gtags company-etags company-keywords)
              company-oddmuse company-dabbrev)
Local in buffer test.txt; global value is 
(company-bbdb company-eclim company-semantic company-clang company-xcode company-cmake company-capf company-files
              (company-dabbrev-code company-gtags company-etags company-keywords)
              company-oddmuse company-dabbrev)
```

**Comment by dgutov** [comment]
Why does it change the global value if `(make-local-variable 'company-backends)` goes first?

**Comment by bbo2adwuff** [comment]
Oh sorry you meant to use it also with the `(make-local-variable 'company-backends)`.

Well when doing that completion doesn't work at all anymore. Not even with having the dictionary file open.

```
Value: (company-ispell)
Original value was 
(company-bbdb company-eclim company-semantic company-clang company-xcode company-cmake company-capf company-files
              (company-dabbrev-code company-gtags company-etags company-keywords)
              company-oddmuse company-dabbrev)
Local in buffer test.txt; global value is 
(company-bbdb company-eclim company-semantic company-clang company-xcode company-cmake company-capf company-files
              (company-dabbrev-code company-gtags company-etags company-keywords)
              company-oddmuse company-dabbrev)
```

**Comment by dgutov** [comment]
Does `M-x company-ispell` show you any completions?

**Comment by bbo2adwuff** [comment]
`Cannot complete at point` in both cases (with dictionary file open and without).
But surprisingly in the first case the words in the dictionary file are shown in the pop-up.

**Comment by dgutov** [comment]
That means that the backend doesn't work, for some reason.

Try `edebug`-ing some functions in `company-ispell`, maybe.

https://www.gnu.org/software/emacs/manual/html_node/elisp/Using-Edebug.html

**Comment by bbo2adwuff** [comment]
edebug doesn't return anything neither for `company-ispell-available` nor for `company-ispell`.

**Comment by dgutov** [comment]
It's a debugger. It's not supposed to return anything.

Try to find out why `company-ispell-available` doesn't return true.

**Comment by bbo2adwuff** [comment]
Well I meant what `edebug` returns in the minibuffer when moving with SPACE and the only difference I see in case one (file open) and case two (file not open) is that in case two I get a nil here:
https://github.com/company-mode/company-mode/blob/master/company-ispell.el#L50

**Comment by dgutov** [comment]
`(eq company-ispell-available 'unknown)` means it's never been tested (to see if the program works). Which is not, in itself, a problem.

**Comment by dgutov** [comment]
> it returns a result

From `company-begin-backend`? That's some shallow debugging.

**Comment by bbo2adwuff** [comment]
This issue can be closed as it works now with the current emacs and current company-mode.

Sorry, before I didn't have enough time to do a proper debug and then I forgot, and now I tried the code above again and it works :)

**Comment by dgutov** [comment]
Thanks for checking!
