### ISSUE TITLE
Company-search-candidates and company-filter-candidates don't work well with evil

### ISSUE THREAD

**Issue by mssdvd** [company-mode/company-mode#812]
I am not sure if this is a company issue or a evil issue.
During a search when I press `C-r` or `C-o` to navigate in reverse order or filter the candidates, evil commands are executed instead of company ones. The same happens during filtering.

**Comment by dgutov** [comment]
I don't do Evil, so try filing it in the Evil tracker first. Either somebody there can fix it, or point out what we should be doing differently.
