### ISSUE TITLE
Variable-width font in buffer --> use fixed-width font in tooltip?

### ISSUE THREAD

**Issue by joostkremers** [company-mode/company-mode#814]
Hi,

I would like to use `company-mode` in my LaTeX buffers, which in principle works well with [`company-auctex`](https://github.com/alexeyr/company-auctex), but I also prefer using a variable-width font in my LaTeX buffers. This doesn't work so well with tooltip completion, because the face in the tooltip is also variable-width, which causes alignment issues:

![screenshot from 2018-07-20 11-05-57](https://user-images.githubusercontent.com/191630/42993941-0bbb3df0-8c0d-11e8-95cb-89ab50bd2d6d.png)

I thought about using `face-remapping-alist` to make the relevant faces use a fixed-width font, but it turns out I'd have to set a bunch of them.

So I was wondering if it would be a good idea to either a) always use a fixed-width font in the tooltips; or b) create a base face for the tooltip (e.g., `company-tooltip`) and let all other tooltip faces inherit it, so that it would be enough to set (or remap) this one face only.

Or is there perhaps already some way to solve my problem and I'm simply overlooking it?

**Comment by memeplex** [comment]
I've run into the same problem. I like having variable width fonts in my tooltips but they wreak havoc with company menu. Is it possible for company to use a different face? Why is it using the same one to begin with? Is it because the menu is implemented using a tooltip frame or just because it seemed like the right choice to use the same face?

**Comment by memeplex** [comment]
Didn't say anything, `company-tooltip` just inherits from `tooltip`, that's completely fine! Sorry.

**Comment by memeplex** [comment]
Btw @joostkremers why can't you just customize `company-tooltip` I did that to avoid my `tooltip` variable width font and it worked just fine.

**Comment by joostkremers** [comment]
I just tried remapping the `tooltip` face, that didn't work. I can remap `company-tooltip`, but that only works for the face of the tooltip, it doesn't fix the alignment issue:

![screenshot from 2018-07-28 00-36-10](https://user-images.githubusercontent.com/191630/43349183-75d7581c-91fe-11e8-8e57-cdd2f4982f19.png)

But this may not be an issue for `company-mode`, it's probably something that should be handled in `tooltip.el`.

**Comment by dgutov** [comment]
Guys, this is a years-old issue, and it's been documented many times in this issue tracker. Just use search.

And no, it's not easy to fix. Company doesn't use tooltip.el either.

Try https://github.com/sebastiencs/company-box, as one alternative.

**Comment by joostkremers** [comment]
Hi Dmitry,

sorry for the noise, I did do a search for my issue but apparently didn't try hard enough... I found the other threads now.

I tried `company-posframe` as an alternative (as mentioned in another thread) but found it too slow. `company-box` works better, thanks for the tip.
