### ISSUE TITLE
Addition of sh-mode keywords

### ISSUE THREAD

**Issue by terlar** [company-mode/company-mode#820]
I was planning to add some keywords for `sh-mode` but then realized it is not so clear at what level you should put it. It is tricky because there are many different shells with their specialties and that much of the functionality in shells is in regular built-ins (e.g. `return`) which kind of could be regarded as keywords as they are heavily used in syntax.

First problem I thought about solving by basing the keywords only on the POSIX-specification and leave out the custom things.

The list could be at one of three levels or further additions could also be made.

```emacs-lisp
  '(sh-mode
    ;; Keywords
    "case" "do" "done" "elif" "else" "esac" "fi" "for" "if" "in" "then" "until" "while"
    ;; Special Built-In Utilities
    "break" "continue" "eval" "exec" "exit" "export" "readonly" "return" "set" "shift" "times" "trap" "unset"
    ;; Utilities with specified behaviour
    "alias" "bg" "cd" "command" "false" "fc" "fg" "getopts" "hash" "jobs" "kill" "newgrp" "pwd" "read" "true" "umask" "unalias" "wait")
```

Which level would you suggest or is this a lost cause in general?

References:
- [Reserved Words (keywords)](http://pubs.opengroup.org/onlinepubs/9699919799/utilities/V3_chap02.html#tag_18_04)
 - [Special Built-In Utilities](http://pubs.opengroup.org/onlinepubs/9699919799/utilities/V3_chap02.html#tag_18_14)
 - [Utilities with specified behaviour](http://pubs.opengroup.org/onlinepubs/9699919799/utilities/V3_chap02.html#tag_18_09_01_01)

**Comment by dgutov** [comment]
Honestly? I don't know.

Doesn't `sh-completion-at-point-function` handle keywords already?

**Comment by terlar** [comment]
I haven't heard about that function before, but I did some investigation and found out that it is quite limited. It includes `if`, `while`, `until` and `for` and commands in `exec-path`:

```elisp
(defun sh--cmd-completion-table (string pred action)
  (let ((cmds
         (append (when (fboundp 'imenu--make-index-alist)
                   (mapcar #'car
                           (condition-case nil
                               (imenu--make-index-alist)
                             (imenu-unavailable nil))))
                 (mapcar (lambda (v) (concat v "="))
                         (sh--vars-before-point))
                 (locate-file-completion-table
                  exec-path exec-suffixes string pred t)
                 '("if" "while" "until" "for"))))
    (complete-with-action action cmds string pred)))
```

The reason I thought about it is that I have seen many people adding these keywords to a list, and I also had such a list and figured it would be nice out of the box experience.

I understand if you would like to skip it as the gain is not that big. Feel free to close if that is the case.

**Comment by dgutov** [comment]
> found out that it is quite limited. It includes if, while, until and for and commands in exec-path

If you file a bug report, I'm pretty sure it can be improved.

**Comment by terlar** [comment]
Sounds good, I will try that. Thank you for your time.

**Comment by saf-dmitry** [comment]
As of now, `sh-script.el` in `sh-mode` still provides completion only for "if", "while", "until", and "for". Maybe we should add the keywords to `company-keywords-alist` nevertheless?

**Comment by dgutov** [comment]
Okay, sure.

Though it would be nicer to the users if the sh-mode completion fn had them (then they won't have to mix in the keywords backend with a manual configuration).

Open a PR?

**Comment by saf-dmitry** [comment]
Done.
