### ISSUE TITLE
candidates-cache not used accross consecutive completions

### ISSUE THREAD

**Issue by kermorgant** [company-mode/company-mode#823]
Hi,

I've looked at the ``company-calculate-candidates`` function and observed its behaviour during completion with [company-phpactor](https://github.com/emacs-php/phpactor.el/blob/09dba9c2aaf59b93bcda88f767e17a51bd843636/company-phpactor.el#L74).

I'm intrigued by the caching mechanism : I've noticed company-calculate-candidates feeds a company-``candidates-cache`` variable, but this variable is not persistent accross consecutive completions (when narrowing down towards the good candidate).

Have I missed something ? what is the purpose of this ``candidates-cache`` if not fot that use case ?

**Comment by kermorgant** [comment]
The following code gets executed, still investigating why...

```elisp
(defun company--continue ()
  (when (company-call-backend 'no-cache company-prefix)
    ;; Don't complete existing candidates, fetch new ones.
    (setq company-candidates-cache nil))
```

**Comment by dgutov** [comment]
Is a different backend being used, maybe?

**Comment by kermorgant** [comment]
ah, thanks, I hadn't that in mind. I had a hook for php-mode doing this

```elisp
  (setq company-backends
        '((;; list of backends
           company-phpactor
           company-files          ; files & directory
           ))))
```

removing company-files activated the cache.

But how should I do if I want a list of specific company-backends activated for php and still have caching for company-phpactor ? Is that doable without adding caching in company-phpactor ?

**Comment by dgutov** [comment]
Then someone would have to implement a per-backend caching in the grouping adapter. Which is a bit more involved.

**Comment by kermorgant** [comment]
Well, I just realized I was "grouping" those 2 backends... Not sure I needed that but thanks again for the help !
