### ISSUE TITLE
Can't get it work right.

### ISSUE THREAD

**Issue by karambaq** [company-mode/company-mode#824]
Hey there, I trying to configurate company-mode right, but can't, help me please.

I use doom-emacs

Part of my config with company settings:

    ;; Company mode
    (setq company-minimum-prefix-length 1)
    (setq company-auto-complete nil)
    (setq company-idle-delay 0)
    (setq company-require-match 'never)
    
    (eval-after-load 'company
          '(progn
                 (define-key company-active-map (kbd "TAB") 'company-complete-common-or-cycle)
                     (define-key company-active-map (kbd "<tab>") 'company-complete-common-or-cycle)
                         (define-key company-active-map (kbd "S-TAB") 'company-select-previous)
                             (define-key company-active-map (kbd "<backtab>") 'company-select-previous)))
    (setq company-frontends
              '(company-pseudo-tooltip-unless-just-one-frontend
                    company-preview-frontend
                        company-echo-metadata-frontend))

So, I open empty python file, and trying to import something, doesn't match anything:
<img width="1463" alt="2018-08-11 16 49 18" src="https://user-images.githubusercontent.com/14233969/43992485-7f6ed2b2-9d87-11e8-9369-7510b0607356.png">

Ok, after, I declare a variable, and at the next line trying to write her name, doesn't match:

<img width="1463" alt="2018-08-11 16 51 28" src="https://user-images.githubusercontent.com/14233969/43992498-aa73e6fa-9d87-11e8-8b18-578b7571bf27.png">

But after I press `C-n`, it works, but it seems like it's not a company:

<img width="1463" alt="2018-08-11 16 51 44" src="https://user-images.githubusercontent.com/14233969/43992508-cc58bd2c-9d87-11e8-995d-f9be68f5b051.png">

After that, I try to test empty `.txt` file and it looks like it works:

<img width="1463" alt="2018-08-11 17 00 24" src="https://user-images.githubusercontent.com/14233969/43992525-2db279f0-9d88-11e8-8357-a15bcd36f93d.png">

But when I insert a `_` in the first line, it don't:

<img width="1463" alt="2018-08-11 17 00 15" src="https://user-images.githubusercontent.com/14233969/43992528-3d5b7ea6-9d88-11e8-8794-db0fc2867bf8.png">

But `C-n` did the job again, so I don't clearly understand what's going on. Hope you can help me.

**Comment by jonnycyr** [comment]
Are you adding anything to company-backends at all? In the code that you've presented it seems like you're only adjusting company-frontends. You might want to check this out: https://github.com/proofit404/company-anaconda

Here's a quick example of setting a backend:
```
(set (make-local-variable 'company-backends)
       '((company-dabbrev-code company-ac-php-backend)))
```

Of course you could also just append to the company-backends list with the backend of your choice, I just like to do above within a hook to a language mode since I don't want the PHP backend showing up in non PHP mode buffers.

**Comment by dgutov** [comment]
@karambaq You're probably calling some command that doom-emacs has bound to `C-n`, Vim-style. That's the problem with starter kits. If it has a support chat, you should probably ask for clarifications there.
