### ISSUE TITLE
Echo area blinks when trying to go past the first and last candidates

### ISSUE THREAD

**Issue by vemv** [company-mode/company-mode#825]
Hi!

When I'm at the last candidate and I press <kbd>down</kbd>, the docsig is rendered again, causing the echo area to blink.

Same  for the first candidate / <kbd>up</kbd>.

IMO, things are being unnecesarily recomputed and the UX is not pleasing either.

Kindly consider fixing.

Thanks - Victor

**Comment by vemv** [comment]
I noticed a similar blinky experience for large docsigs:

![2018-08-27 10 55 04](https://user-images.githubusercontent.com/1162994/44651496-dde44980-a9e9-11e8-948f-0f493c296323.gif)

I tried to compensate it by 'padding' each docsig so they all have the same line count, but even then they'll blink

**Comment by vemv** [comment]
Any hint about this? Could you reproduce the issue?

**Comment by vemv** [comment]
I gave a shot to debugging this. Couldn't find any fishy code.

Also I remembered that in Emacs, pressing any given key will clear the minibuffer (https://stackoverflow.com/questions/39011107/how-to-keep-the-minibuffer-in-emacs-to-not-be-cleared ) so I was fighting against Emacs - not company-mode :)

**Comment by dgutov** [comment]
Alas.

I've never noticed this to be a problem before, though.

Maybe in this case it is more egregious because CIDER (right?) returns multiline strings there. And it makes the echo area jump up and down, among other things.

**Comment by vemv** [comment]
Thanks for the reply!

>  CIDER (right?) returns multiline strings there

Right. It seems to me the right thing to do, since Clojure docstrings are already multi-line and cannot be trivially summarized as one line (unless one decided to display only the function's arguments, and no docstrings at all).

**Comment by dgutov** [comment]
Elisp's docstrings are also multiple. And other languages' too.

And yet...

**Comment by dgutov** [comment]
What's your value of `company-echo-truncate-lines`, BTW?

**Comment by vemv** [comment]
> Elisp's docstrings are also multiple. And other languages' too.

But they are trimmed:

![image](https://user-images.githubusercontent.com/1162994/46870339-9c3f1f00-ce2e-11e8-979c-a8d9a20a9ff0.png)

(you can see below my popup there's the defun in question - with a multiline docstring)

The official Clojure docstrings (i.e. `clojure.core`) tend to be messy which is why CIDER might have opted to display multi-line docstrings.

So trimming might be acceptable for some languages, but not so much for others.

> What's your value of company-echo-truncate-lines, BTW?

nil

**Comment by dgutov** [comment]
> But they are trimmed

That's my point. If you want to see the full docstring, press `f1`.

> nil

OK. That's the non-default value, to be clear.

**Comment by vemv** [comment]
> That's my point. If you want to see the full docstring, press f1.

Very nice, I'll look into it. Looks like CIDER has some room for improvement here.
