### ISSUE TITLE
Company autocompletion like YCM

### ISSUE THREAD

**Issue by ChoppinBlockParty** [company-mode/company-mode#826]
Hi,
Have read [this pull](https://github.com/company-mode/company-mode/pull/524) and [this wiki](https://github.com/company-mode/company-mode/wiki/Switching-from-AC), however nothing from there is working. Can anyone shed the light on what is the last state of this feature? How it can be used to achieve YCM-like TAB autocompletion?

**Comment by dgutov** [comment]
What exactly isn't working?

**Comment by dgutov** [comment]
You can try https://github.com/company-mode/company-mode/blob/master/company-tng.el instead.

It allows different workflow, probably closer to your expectations.

**Comment by Alexander-Shukaev** [comment]
@ChoppinBlockParty, were you satisfied with `company-tng`?

**Comment by dgutov** [comment]
Any troubles with `company-tng` should be turned into separate reports.
