### ISSUE TITLE
Filtering or relocating completion that matches prefex

### ISSUE THREAD

**Issue by xendk** [company-mode/company-mode#831]
I love the new company-tng configuration, it replaces and improves on most of the handhackery I was using.

However, is there a way to either skip the first suggestion when it completely matches the prefix, or alternatively relocate it to the end of suggestions (as I realize removing it probably messes with those using templates)?

If, using the dabbrev completer for example, I have typed 'bind` and it suggests `bind`, `binding` and `bindings`, I have to press tab twice for it to actually change anything.

**Comment by dgutov** [comment]
How about using `company-transformers`?

**Comment by xendk** [comment]
But of course....

In case someone else ponders this, here is what I came up with:

(defun xen-company-sort (candidates)
  "Sort CANDIDATES so if the first match prefix, it'll be moved to the end."
  (when (equal (car candidates) (company-call-backend 'prefix))
    (setq candidates (cdr candidates))
    (nconc candidates (list (company-call-backend 'prefix))))
  candidates)

Leave out the nconc to completely eliminate it.
