### ISSUE TITLE
Feature Request: Allow Filtering yasnippet completions when triggered by trigger sequence

### ISSUE THREAD

**Issue by wberrier** [company-mode/company-mode#840]
This seems somewhat related to #485 , but the idea is that I'm grouping company-lsp/cquery (c++) and company-yasnippet together via:

```elisp
(push '(company-lsp :with company-yasnippet) company-backends)
```

Completing without input (prefix) shows all globals and snippets as expected.

But, when I have completions from a trigger character ('.' or '->') then all the snippets show up in the completions, which is never desired behavior in this setup.

It would be great to only show snippets in completions if completion list isn't triggered by a trigger sequence.

I've considered trying to set up `company-transformers` to perform this filter, and maybe that's a way to implement this?  Not sure...

Thoughts?

**Comment by wberrier** [comment]
Also note, using `:separate` as suggested in #485 does indeed help by putting all the snippets at the bottom, but I think it would be preferable if the snippets weren't in the list at all.

**Comment by dgutov** [comment]
Try this:

```lisp
(defun company-yasnippet-unless-member-access (command &optional arg &rest ignore)
  (if (eq command 'prefix)
      (let ((prefix (company-yasnippet 'prefix)))
        (and prefix
             (save-excursion
               (forward-char (- (length prefix)))
               (not (looking-back (rx (or "." "->")) (line-beginning-position))))
             prefix))
    (company-yasnippet command arg)))
```

And use this backend instead of `company-yasnippet` directly.

**Comment by wberrier** [comment]
That works great, thanks!

Some questions:

Is there a way to automatically use all the "triggers" specified for that particular language?  Seems like different languages are going to have their particular cases when it's not appropriate to show snippets...

For example, here's some additional cases for c++ where snippets probably shouldn't be shown:

* `std::`
* `#include <`
* `#include "`

Also, is this something that would be provided with company-yasnippet (and have the lookback chars be a defcustom, or language specific alist, etc...), or should I just put it in my local config?

**Comment by dgutov** [comment]
> Is there a way to automatically use all the "triggers" specified for that particular language?

If there were an existing convention to specify them in language mode definitions, we could. I'm not aware of one, though.

> or should I just put it in my local config?

This, at least for now. And I also think it works better as a wrapper backend, because whether we want to avoid snippets after trigger characters depends on the presence of other backends (and whether they provide snippets for completions).

**Comment by wberrier** [comment]
Sounds good, and thanks, it works much better.

I'll leave it up to you whether you want to close this issue or not...

**Comment by dgutov** [comment]
Let's leave it open for now.

**Comment by dgutov** [comment]
Check out the latest master, the behavior should be improved.
