### ISSUE TITLE
Duplicate Entries in from company-clang backend

### ISSUE THREAD

**Issue by ahsanp** [company-mode/company-mode#841]
Hi. I'm trying to use company-clang for completion of C/C++ code. I have turned off company-semantic. For the most part company-clang works great. However under a few cases it produces duplicate candidates

![screenshot from 2018-11-04 21-19-56](https://user-images.githubusercontent.com/16830690/47976300-6c72e800-e077-11e8-8e00-5c0e4d2b297c.png)

The output of the company-diag is the following

`Emacs 26.1 (x86_64-pc-linux-gnu) of 2018-05-29 on lcy01-amd64-029
Company 0.9.6

company-backends: (company-c-headers company-bbdb company-eclim company-clang company-xcode company-cmake company-capf company-files
		   (company-dabbrev-code company-gtags company-etags company-keywords)
		   company-oddmuse company-dabbrev)

Used backend: company-clang
Major mode: c-mode
Prefix: #("std" 0 1
  (fontified t)
  1 2
  (fontified t)
  2 3
  (fontified t))

Completions:
  "stdout"
  #("stdout" 0 1 (meta "struct _IO_FILE * stdout"))
  "stdin"
  #("stdin" 0 1 (meta "struct _IO_FILE * stdin"))
  "stderr"
  #("stderr" 0 1 (meta "struct _IO_FILE * stderr"))`

Can someone please point me to what I'm doing wrong?

**Comment by dgutov** [comment]
Hmm, not sure. I'm seeing the same behavior.

It seems Clang started to output these duplicated fairly recently (some new version of it). And I'm not sure what's the semantic meaning of having both `stderr : stderr` and `stderr : [#struct _IO_FILE *#]stderr` in the output, if we're going to filter them out.

As a quick fix, though, you can use this:

```diff
diff --git a/company-clang.el b/company-clang.el
index 962db1e..b2d719d 100644
--- a/company-clang.el
+++ b/company-clang.el
@@ -336,6 +336,7 @@ passed via standard input."
                  (or (company-clang--prefix) 'stop)))
     (candidates (cons :async
                       (lambda (cb) (company-clang--candidates arg cb))))
+    (duplicates t)
     (meta       (company-clang--meta arg))
     (annotation (company-clang--annotation arg))
     (post-completion (let ((anno (company-clang--annotation arg)))
```

**Comment by dgutov** [comment]
@Sarcasm do you have any suggestions, maybe? Like an easy way to filter out the unwanted lines.

**Comment by dgutov** [comment]
> I found out why it is the way it is.

Thanks!

> So I'm tempted to say that this is correct.

They are fairly useless for completion, though. Should we skip all entries like of the form `COMPLETION: foo : foo`? The patch below does that:

```diff
diff --git a/company-clang.el b/company-clang.el
index 962db1e..d43eebb 100644
--- a/company-clang.el
+++ b/company-clang.el
@@ -134,11 +134,12 @@ or automatically through a custom `company-clang-prefix-guesser'."
           (when (string-match ":" match)
             (setq match (substring match 0 (match-beginning 0)))))
         (let ((meta (match-string-no-properties 2)))
-          (when (and meta (not (string= match meta)))
-            (put-text-property 0 1 'meta
-                               (company-clang--strip-formatting meta)
-                               match)))
-        (push match lines)))
+          (unless (equal match meta)
+            (when meta
+              (put-text-property 0 1 'meta
+                                 (company-clang--strip-formatting meta)
+                                 match))
+            (push match lines)))))
     lines))
 
 (defun company-clang--meta (candidate)
```

**Comment by Sarcasm** [comment]
TBH, I don't know the clang CLI completion output format.
I guess it is ok, if this happens only for identity preprocessor `#defines`.

In practice a preprocessor define is available in all contexts, but the define expansion may not be.
So it's possible you filter out the preprocessor define in places where the expansion is not available, in which case you don't remove a duplicate, but an unique value.
But that could be a feature, because if the expansion does not make sense, then the define doesn't either.

In an ideal world, if I had to handle this case, I think I would try to show the difference, that one is a macro and the other a global variable, a type, a function, ... (#756).

**Comment by dgutov** [comment]
> But that could be a feature, because if the expansion does not make sense, then the define doesn't either.

I hope so.

> I would try to show the difference, that one is a macro and the other a global variable, a type, ...

It would be easier to see why the duplicates are there, but the said duplicates won't become more useful, I believe.

So let's try the easier option first and see if it causes any problems. Thanks!

**Comment by dgutov** [comment]
It did cause problems, alas. Reverting. :-(

So... I don't see an easy way to distinguish duplicate macros from "real" ones. And as for returning `duplicates t` in `company-clang`, it might remove the more-informative entries instead.

I'm kind of hoping for this to be fixed in Clang now.

**Comment by dgutov** [comment]
Added a fix that filters out such duplicates manually.
