### ISSUE TITLE
strange after-init-hook?

### ISSUE THREAD

**Issue by titaniumbones** [company-mode/company-mode#842]
I'm getting an error on startup that I'm having trouble tracking down, and am wondering if you can help me figure out where it comes from.  

I initialize ocmpany with use-package: 

```
(use-package company
      :ensure t
      :hook
      (after-init . 'global-company-mode) )
```
I would expect that the value of `after-init-hook` would now include `global-company-mode` , but instead it looks like this:

(#[0 "\303\211\235\203\0\304\"\301\305!\210\210	\205\0\306 \210\307\211\207" [command-line-args desktop-save-mode inhibit-startup-screen "--no-desktop" delete 0 desktop-read t] 4] global-emojify-mode company global-flycheck-mode x-wm-set-size-hint tramp-register-archive-file-name-handler table--make-cell-map)
```
Several of these are mysterious to me but the only one that errors out is `company` which gives the following (called manually here):

```
Debugger entered--Lisp error: (error "Autoloading file /home/matt/.emacs.d/elpa/company-20181012.2220/company.elc failed to define function company")
  (company)
  eval((company) nil)
  eval-expression((company) nil nil 127)
  funcall-interactively(eval-expression (company) nil nil 127)
  call-interactively(eval-expression nil nil)
  command-execute(eval-expression)
```

Any idea what might be causing this? Thanks!

Matt

**Comment by dgutov** [comment]
This doesn't look like a `company` question. It's a `use-package` question, which I'm still not familiar with.

Please use whatever support channels it has.
