### ISSUE TITLE
Company-backends: nil

### ISSUE THREAD

**Issue by loysollivier** [company-mode/company-mode#843]
I'm trying to use company for shell completion, my config is fairly simple:
```
  (add-hook 'shell-mode-hook 'company-mode)
  (define-key shell-mode-map (kbd "TAB") #'company-manual-begin)
```
But in my shell buffer when I run `company-diag` I get the following:
```
Emacs 25.3.2 (x86_64-pc-linux-gnu) of 2017-09-12 on lcy01-32
Company 0.9.7

company-backends: nil
Used backend: nil
Major mode: shell-mode
Prefix: nil
Completions: none
```

Although company-mode is there. How could I debug it further ? Find company logs or other...

Thanks for the help !

**Comment by dgutov** [comment]
The value of this variable is set when the `company` package is loaded, not when the mode is activated.

Anyway, somewhere your configuration overrides it to `nil`. Try `cd ~/.emacs.d && ag company-backends`, or something like that.

**Comment by loysollivier** [comment]
Hum I didn't know. I thought it would load all the backends and just pick the correct one afterward.
I haven't found yet where it is overridden but adding this to my config solves the issue.
`(add-to-list 'company-backends 'company-capf)`

Thanks !
