### ISSUE TITLE
How can I disable company inside comments (c-mode)?

### ISSUE THREAD

**Issue by mrbig033** [company-mode/company-mode#844]
- GNU Emacs 27.0.50
- Company 20181105.2312
- [.emacs.d](https://github.com/mrbig033/dotfiles/tree/master/emacs/emacs_default)
- [packages](https://github.com/mrbig033/dotfiles/blob/master/emacs/emacs_default/packs.el#L711)
- gcc (Debian 6.3.0-18+deb9u1) 6.3.0 20170516
- clang version 3.8.1-24

Configuration:

```
(use-package company
:defer t
:ensure t
:init
(setq company-auto-complete t)
(setq company-minimum-prefix-length 3)
(setq company-idle-delay 0.2))
```
I which I could disable company, but only inside comments. Couldn't find how. I appreciate any suggestion on how to solve this.

**Comment by dgutov** [comment]
It depends on the backend that you're using. There's no global setting.

**Comment by mrbig033** [comment]
I haven't configured any backends, but I provided the versions of the software I thought might be relevant. Please let me know if there's anything more I can provide.

Emacs says this about the variable "company-backend":

``` emacs-lisp
company-backend is a buffer-local variable defined in company.el.

Value in #<buffer ex.c>
nil
```

**Comment by dgutov** [comment]
I would ask what `M-x company-diag` says, but you should probably just remove `company-dabbrev` from `company-backends`. Possibly, only do that in a buffer-local value in `c-mode` buffers.

**Comment by mrbig033** [comment]
#### Output of `company-diag`:

``` emacs-lisp
Emacs 27.0.50 (x86_64-pc-linux-gnu) of 2018-11-24 on do
Company 0.9.7

company-backends: (company-bbdb company-eclim company-semantic company-clang company-xcode company-cmake company-capf company-files
	      (company-dabbrev-code company-gtags company-etags company-keywords)
	      company-oddmuse company-dabbrev)

Used backend: company-clang
Major mode: c-mode
Prefix: stop
Completions: none
```

I search for `company-dabbrev` on my init and saw no mention of it. I don't know how it got there. Is this not a default? Anyway, how can I take it out?

**Comment by dgutov** [comment]
> Is this not a default?

It is indeed the default, and the default behavior.

> Anyway, how can I take it out?

**Comment by mrbig033** [comment]
Thanks, @dgutov. I (didn't have the time to learn how to do to customize this variable, and also my semester ended and I won't have to program in C for a while. Thank you for your kind answers.

**Comment by dgutov** [comment]
Sorry I don't have the time by field basic questions like this in detail, but a web search for "emacs customize variable" would easily give you the full instructions. In short: `M-x customize-variable`.

**Comment by mrbig033** [comment]
No problem, I understand! Again, thank you for your patience.
