### ISSUE TITLE
`company-ispell` does not complete Portuguese accentuated characters correctly

### ISSUE THREAD

**Issue by mrbig033** [company-mode/company-mode#848]
#### Runtime Environment

- MX Linux 17
- GNU Emacs 27.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.22.11)
of 2018-11-28
- Evil version 1.2.13
- [.emacs.d](https://github.com/mrbig033/dotfiles/tree/master/emacs/emacs_default)
- [packages](https://github.com/mrbig033/dotfiles/blob/master/emacs/emacs_default/packs.el)
- company-20181207.147

#### use-package

``` emacs-lisp
(use-package company
  :ensure t
  :init
  (setq company-ispell-dictionary (file-truename "~/.emacs.d/etc/brasileiro.txt"))
  (setq company-tooltip-limit 5)
  (setq company-auto-complete-chars '(32 40 46 41))
  ;; (setq company-auto-complete-chars '("SPC" "(" "." ")")
  (setq company-auto-complete t)
  (setq company-idle-delay 0.2)
  (setq company-show-numbers t)
  (setq company-dabbrev-code-modes t)
  (setq company-dabbrev-downcase nil)
  (setq company-minimum-prefix-length 2)
  (setq company-dabbrev-code-everywhere t)
  (setq company-dabbrev-other-buffers 'all)
  (setq company-dabbrev-ignore-buffers "nil")
  (add-hook 'global-company-mode-hook 'company-quickhelp-mode)
  :config
  (global-company-mode 1))
```

#### Issue

For example: the word `possível` is inserted as `poss�vel/B` (literally `posse\355vel/B`), and a warning buffer opens with the following message:

```emacs-lisp
These default coding systems were tried to encode text
in the buffer ‘scratch.md’:
  (utf-16-unix (525 . 4194285) (536 . 4194285)) (utf-8-unix (525 .
  4194285) (536 . 4194285))
However, each of them encountered characters it couldn’t encode:
  utf-16-unix cannot encode these: � �
  utf-8-unix cannot encode these: � �

Click on a character (or switch to this window by ‘C-x o’
and select the characters by RET) to jump to the place it appears,
where ‘C-u g a’ will give information about it.

Select one of the safe coding systems listed below,
or cancel the writing with C-x q and edit the buffer
   to remove or modify the problematic characters,
or specify any other coding system (and risk losing
   the problematic characters).

  raw-text no-conversion
```

The dictionary was uncompressed from `/usr/share/ispell`. I tried the original `brasileiro.mwl` format before renaming to txt. The accentuated character does not show on the tooltip, but I'm unable to screenshot it because the tooltip goes away when I run the screenshooter.

#### I'm using this function to configure company for ispell

``` emacs-lisp
(defun my/company-ispell ()
  (interactive)
  (set (make-local-variable 'company-backends)
       '(company-ispell company-dabbrev-code))
  (message " company-ispell enabled"))
```

**Comment by dgutov** [comment]
> the tooltip goes away when I run the screenshooter

You can remove the `company-quickhelp-mode` line and try again.

More importantly, does `M-x ispell-complete-word` work with that dictionary? Evaluate `(setq ispell-complete-word-dict (file-truename "~/.emacs.d/etc/brasileiro.txt"))` before calling it.

**Comment by dgutov** [comment]
The dictionary might be misencoded, though. I've just installed the `ibrazilian` package and tried the same thing using the `ispell` command line program. The correction it gave me didn't show the proper unicode character either.

**Comment by mrbig033** [comment]
### M-x ispell-complete-word does not work with this dictionary

![M-x ispell-complete-word does not work with this dictionary ](https://user-images.githubusercontent.com/36245777/50018454-29792e00-ffae-11e8-830a-1da41bbac7f0.png)

**Comment by dgutov** [comment]
Then `M-x report-emacs-bug` is probably your best bet.

It is possible, of course, that the dictionary file is encoded wrong. You can try recoding it to e.g. UTF8. I'm not quite sure what the expected format and encoding for dictionary files is.

**Comment by mrbig033** [comment]
I opened the dictionary file, ran `set-buffer-file-coding-system` and chose `utf8`. It's fixed. Closing.
