### ISSUE TITLE
Feature: Option to only insert candidate from list into buffer upon selection

### ISSUE THREAD

**Issue by lagooned** [company-mode/company-mode#849]
It is often time the case when using company-lsp, there is a disconnect between what company mode displays the completion as (in the completion suggestions) and what the the completion will be inserted into the buffer as. 

In this case, it would be useful for company mode to disable the automatic insertion of the candidate into the buffer that occurs when navigating the completions menu. Another option is to have a hook that would  delete backward the length of the candidate upon selecting a new candidate.

I've attached screenshots of this situation:

![no_complete](https://user-images.githubusercontent.com/638729/50045929-c6949f00-0060-11e9-9a30-55ffed684847.png)
![complete_inserted_into_buffer](https://user-images.githubusercontent.com/638729/50045931-ce544380-0060-11e9-9d88-827893fd4354.png)
![text_inserted_into_buffer_typing](https://user-images.githubusercontent.com/638729/50045933-d57b5180-0060-11e9-8d8a-3992dace6ae1.png)

Maybe this is simply something that I have missed in my configs so please have a look:

```
(use-package company
  :diminish company-mode
  :commands company-mode
  :bind
  (:map company-active-map
        ("<tab>"    . nil)
        ("<return>" . nil)
        ("RET"      . nil)
        ("\e\e\e"   . nil)
        ("M-n"      . company-select-next-or-abort)
        ("M-p"      . company-select-previous-or-abort)
        ("M-i"      . company-complete-common-or-cycle)
        ("C-n"      . gmacs/company-cancel-complete-next)
        ("C-p"      . gmacs/company-cancel-complete-prev)
        ("M-g"      . company-abort)
        ("M-j"      . company-complete-selection)
        ("M-m"      . company-complete-selection)
        ("C-v"      . company-next-page)
        ("M-v"      . company-previous-page))
  :init
  (setq company-idle-delay 0.1
        company-minimum-prefix-length 2
        company-show-numbers t)
  :config
  ;; set backend as local var in respective prog mode
  (setq company-backends nil))

(defun gmacs/company-cancel-complete-prev ()
  (interactive)
  (company-abort)
  (evil-complete-previous))

(defun gmacs/company-cancel-complete-next ()
  (interactive)
  (company-abort)
  (evil-complete-next))
```

**Comment by dgutov** [comment]
You seem to be asking for what is already the default behavior.

What keys exactly are you pressing to navigate the menu?

If you are using a "starter kit" of some sort, you might be better off asking on their support channel first.

**Comment by lagooned** [comment]
ACTUALLY, I figured it out. There was a strange interaction between my config and evil-collection-company that made the selection somehow add to the buffer. I will investigate.

Thanks for confirming the default behavior!
