### ISSUE TITLE
Is there any more elegant way to resolve conflicts with other modes?

### ISSUE THREAD

**Issue by re-mx** [company-mode/company-mode#850]
Hello:

I am referring to a conflict like the one mentioned in #416 . The solutions I see are generally like Mr. Purcell:

```elisp
(defvar-local remx-foo-on-p nil)

(defun remx/turn-off-foo (&rest _)
  (when (setq remx-foo-on-p (bound-and-true-p foo-mode))
    (foo-mode -1)))

(defun remx/turn-on-foo (&rest _)
  (when remx-foo-on-p
    (foo-mode 1)))

(add-hook 'company-completion-started-hook 'remx/turn-off-foo)
(add-hook 'company-completion-finished-hook 'remx/turn-on-foo)
(add-hook 'company-completion-cancelled-hook 'remx/turn-on-foo)
```

This is a good solution, but if I have a lot of conflicting modes like this (Honestly... I have at least three such modes)... I will be very tired.

So I'd like to ask if there is any better way?

Thank you!

**Comment by dgutov** [comment]
> (add-hook 'company-completion-finished-hook 'remx/turn-on-foo)
(add-hook 'company-completion-cancelled-hook 'remx/turn-on-foo)

Starting with `0.9.9`, you can replace these with one line:

```
(add-hook 'company-after-completion-hook 'remx/turn-on-foo)
```

**Comment by dgutov** [comment]
Aside from that, it depends on what causes the conflict.

If it's due to overlay-based rendering of the popup, you can try https://github.com/tumashu/company-posframe or https://github.com/sebastiencs/company-box instead.

Which "such modes" are you referring to, BTW?

**Comment by re-mx** [comment]
@dgutov Thanks.

I will close this PR...because I found that they can't be completely replaced.

**Comment by re-mx** [comment]
@dgutov Thanks. and forgive my poor English.

It is a mode similar to `page-break-lines`. For example: [indent-guide-mode](https://github.com/zk-phi/indent-guide), `fci-mode`, etc.

But I found that replacing the two hooks with `company-after-completion-hook` is not completely effective - sometimes the `page-break-lines` is permanently closed.

**Comment by dgutov** [comment]
> But I found that replacing the two hooks with company-after-completion-hook is not completely effective

:confused: I really doubt it should make a difference: this hook is called pretty much from the same place as the other two.

> I am not going to introduce other tools to solve this problem

Okay then. But I don't have any other suggestions, sorry.

**Comment by re-mx** [comment]
Thanks.

**Comment by dgutov** [comment]
> I found that replacing the two hooks with company-after-completion-hook is not completely effective

You might want to upgrade to the latest version now.

**Comment by re-mx** [comment]
I have updated and the problem has been resolved

Thank you!

**Comment by ACEMerlin** [comment]
Here is a marco to simplify this:
```lisp
(defmacro lain/fix-company-conflict (mode)
    (let ((status (intern (format "lain//%s-company-status" mode)))
	  (disable-fn (intern (format "lain//disable-%s-when-company-activates" mode)))
	  (enable-fn (intern (format "lain//enable-%s-when-company-deactivates" mode))))
      `(progn
	 (defvar-local ,status nil)
	 (defun ,disable-fn (&rest _)
	   (when (setq ,status (bound-and-true-p ,mode))
	     (,mode -1)))
	 (defun ,enable-fn (&rest _)
	   (when ,status
	     (,mode +1)))
	 (add-hook 'company-completion-started-hook #',disable-fn)
	 (add-hook 'company-after-completion-hook #',enable-fn))))
```
then use it like this
```lisp
(with-eval-after-load 'company
  (lain/fix-company-conflict page-break-lines-mode))
```
