### ISSUE TITLE
`company-cancel` sometimes not called?

### ISSUE THREAD

**Issue by Alexander-Shukaev** [company-mode/company-mode#853]
Remember #180?  Well, I had this solution implemented ever since.  Recently, I noticed that fill column indicator started to disappear permanently.  Now I know that this is because of `company-cancel` not running somehow (of course, since it should restore fill column indicator).  I have no exact idea why it happens but one reproduction scenario might help perhaps.  Using `company-tng`, simply type some garbage after candidate was inserted.

![output-2018-12-21-02 44 44](https://user-images.githubusercontent.com/911281/50320575-52795180-04cd-11e9-84d0-d81b8018d99a.gif)

I also saw it happening without `company-tng`, e.g. when typing something inside of Emacs Lisp string `"..."`, I saw that `company` got triggered but never properly canceled though no completion overlay even appeared (there was nothing to complete really).

**Comment by dgutov** [comment]
Any chance you can repro without `company-tng`?

**Comment by Alexander-Shukaev** [comment]
As already mentioned above, yes, I can be reproduced without `company-tng`, e.g.

![output-2018-12-21-13 17 25](https://user-images.githubusercontent.com/911281/50342366-09ec8300-0523-11e9-94ff-cf44578b993b.gif)

**Comment by Alexander-Shukaev** [comment]
```
company is a dependency package.

     Status: Installed in ‘company-20181213.2321/’ (unsigned).
    Version: 20181213.2321
    Summary: Modular text completion framework
   Requires: emacs-24.3
Required by: company-ycmd-20180520.1053, company-php-20181110.303, company-flx-20180103.518
   Homepage: http://company-mode.github.io/
   Keywords: abbrev convenience matching 
Other versions: 20181213.2321 (melpa), 0.9.9 (melpa.stable), 0.9.9 (gnu).
```

**Comment by dgutov** [comment]
I can see it, thank you.

**Comment by dgutov** [comment]
Should be fixed now. Thank you for reporting.
