### ISSUE TITLE
Grouping not working as expected when using :separate

### ISSUE THREAD

**Issue by larebsyed** [company-mode/company-mode#856]
**Issue**
- When using :separate keyword in backend grouping, the suggestions are not grouped properly

**Expected**
- The suggestions from different backends should be separately grouped

**Actual**
- The suggestion are not grouped by backends

**Backends group**
((:separate company-lsp :separate company-tabnine :separate company-yasnippet) company-lsp)

**This is what I see:**
image
![image](https://user-images.githubusercontent.com/12972892/50512930-b2b45880-0ab6-11e9-8f7f-c724c2b232f8.png)

Ideally the `retry` completion should come after `return` completion. It was working fine before recent releases.

**Company Diag:**

```Emacs 27.0.50 (x86_64-pc-linux-gnu) of 2018-12-14 on inventionist
Company 0.9.9

company-backends: ((:separate company-lsp :separate company-tabnine :separate company-yasnippet)
 company-lsp)

Used backend: (:separate company-lsp :separate company-tabnine :separate company-yasnippet)

Major mode: js2-mode
Prefix: #("ret" 0 3
  (fontified t ws-butler-chg chg help-echo "Code has no side effects" cursor-sensor-functions
             (js2-echo-error)
             face
             (:foreground "#6ce5636d8492")
             color-identifiers:fontified t))

Completions:
  #("return" 0 6 (lsp-completion-prefix #("re" 0 2 (fontified t ws-butler-chg chg)) lsp-completion-item #s(hash-table size 65 test equal rehash-size 1.5 rehash-threshold 0.8125 data ("label" "return" "kind" 14 "sortText" "0" "data" #s(hash-table size 65 test equal rehash-size 1.5 rehash-threshold 0.8125 data ("uri" "file:///home/lareb/Project/Cresta/chat-agent/client/containers/Suggestions/selectors/suggestionSelectedSelector.js" "offset" 291 "entryName" "return")))))) "  (Keyword)"
  #("return" 0 6 (company-backend company-tabnine))
  #("response_time" 0 13 (company-backend company-tabnine))
  #("retry" 0 5 (company-backend company-tabnine))
  #("retrieveAvailableSkills" 0 23 (company-backend company-tabnine))
  #("retryLeft" 0 9 (company-backend company-tabnine))
  #("returns" 0 7 (company-backend company-tabnine))
  #("returned" 0 8 (company-backend company-tabnine))
  #("returnValue" 0 11 (company-backend company-tabnine))
  #("retrieve" 0 8 (company-backend company-tabnine))
  #("reselect" 0 8 (company-backend company-tabnine))
```

**Transformers**

```(lsp-prefix-company-transformer spacemacs//company-transformer-cancel company-sort-by-occurrence company-sort-by-statistics)```

Oddly when I disable `company-sort-by-statistics` the grouping works fine

**Comment by dgutov** [comment]
What does `M-x company-diag` say?

**Comment by larebsyed** [comment]
This is what I see:
![image](https://user-images.githubusercontent.com/12972892/50512821-f22e7500-0ab5-11e9-8be0-510af906efcc.png)

Company Diag:
`Emacs 27.0.50 (x86_64-pc-linux-gnu) of 2018-12-14 on inventionist
Company 0.9.9

company-backends: ((:separate company-lsp :separate company-tabnine :separate company-yasnippet)
 company-lsp)

Used backend: (:separate company-lsp :separate company-tabnine :separate company-yasnippet)

Major mode: js2-mode
Prefix: #("ret" 0 3
  (fontified t ws-butler-chg chg help-echo "Code has no side effects" cursor-sensor-functions
             (js2-echo-error)
             face
             (:foreground "#6ce5636d8492")
             color-identifiers:fontified t))

Completions:
  #("return" 0 6 (lsp-completion-prefix #("re" 0 2 (fontified t ws-butler-chg chg)) lsp-completion-item #s(hash-table size 65 test equal rehash-size 1.5 rehash-threshold 0.8125 data ("label" "return" "kind" 14 "sortText" "0" "data" #s(hash-table size 65 test equal rehash-size 1.5 rehash-threshold 0.8125 data ("uri" "file:///home/lareb/Project/Cresta/chat-agent/client/containers/Suggestions/selectors/suggestionSelectedSelector.js" "offset" 291 "entryName" "return")))))) "  (Keyword)"
  #("return" 0 6 (company-backend company-tabnine))
  #("response_time" 0 13 (company-backend company-tabnine))
  #("retry" 0 5 (company-backend company-tabnine))
  #("retrieveAvailableSkills" 0 23 (company-backend company-tabnine))
  #("retryLeft" 0 9 (company-backend company-tabnine))
  #("returns" 0 7 (company-backend company-tabnine))
  #("returned" 0 8 (company-backend company-tabnine))
  #("returnValue" 0 11 (company-backend company-tabnine))
  #("retrieve" 0 8 (company-backend company-tabnine))
  #("reselect" 0 8 (company-backend company-tabnine))
`

**Comment by dgutov** [comment]
What's your value of `company-transformers`?

**Comment by larebsyed** [comment]
**Transformers**

```(lsp-prefix-company-transformer spacemacs//company-transformer-cancel company-sort-by-occurrence company-sort-by-statistics)```

**Comment by dgutov** [comment]
I don't know if we can discuss this on a superficial level like that. Each transformer either does its job, or not, and you can give examples when they don't.

But there's no point in having *two* sorting transformers in the list. They'll just conflict with each other.
