### ISSUE TITLE
company-statistics--save prevents quitting emacs with read-only filesystem

### ISSUE THREAD

**Issue by leezu** [company-mode/company-mode#860]
Recently my filesystem had to be emergency remounted as read-only. I observed that I could not quit or kill emacs anymore. The following showed up in my log upon trying to quit emacs:

```
company-statistics--save: Opening output file: Read-only file system, /home/leonard/.emacs.d/.cache/company-statistics-cache.el
Error running timer ‘savehist-autosave’: (file-error "Opening output file" "Read-only file system" "/home/leonard/.emacs.d/.cache/savehist")
```

This prevented quitting emacs.

I am not sure if `company-statistics--save` prevented the shutdown, or just warned about the read-only file system. Possibly the behavior of  `company-statistics--save` is sane and `savehist-autosave` is at fault. If so, please close this. Otherwise, please consider fixing.

**Comment by dgutov** [comment]
Please report that at https://github.com/company-mode/company-statistics/issues.
