### ISSUE TITLE
Company in ledger mode adds trailing spaces to partial account names

### ISSUE THREAD

**Issue by ngleb** [company-mode/company-mode#861]
I'm using ledger-mode together with company mode. Issue started happening since 0.9.9 stable release (I checked  0.9.7 and 0.9.8, no issue).

The problem is the following:
in ledger, I have account names like:
```
Assets:Savings:Account1
Assets:Cash
```
etc.

Previous versions correctly inserted partial account names, like "Assets:" without trailing space so I could start typing the next part. Now I have trailing space after like this "Assets: ".

So, I type "Asse", what for the completion to appear, hit Enter. Or I can choose another candidate and hit Enter. It adds space after semicolon but it wasn't the case before the new version.

If I disable company mode in this particular ledger buffer, then everything also works correctly.

I checked the history of commits, but I didn't see something unusual. What have changed?

update: current master - same behavior, trailing space.

**Comment by dgutov** [comment]
What does `M-x company-diag` say?

**Comment by dgutov** [comment]
Seems like you should report this to ledger-mode (`company-capf` delegates to the major mode's completion function).

**Comment by ngleb** [comment]
But why it works with company 0.9.8 and not with 0.9.9?

**Comment by ngleb** [comment]
@dgutov 
It seems ledger-mode developing is not going very well. I tried debugging company functions, but it didn't help, at some point it just inserts the trailing whitespace. I found a function called "ledger-trim-trailing-whitespace" in ledger that is called somewhere. Do you think it could be the reason why the trailing space added when using company and not ledger-magic-tab (with its own completion)?

https://github.com/ledger/ledger-mode/blob/master/ledger-complete.el#L258

**Comment by dgutov** [comment]
Oh.

`ledger-mode` uses `pcomplete-completions-at-point` as its completion function. I can not advise you further, except noting that it has some known problems with CAPF, because it doesn't really adhere to the interface. Sorry. :(

You can try debugging whatever functions in `ledger` that have `pcomplete` in their names, but I'm not sure if it'll lead you anywhere.

**Comment by ngleb** [comment]
ledger-mode no longer uses `pcomplete`, and I no longer have this issue. In all cases completion with company works as expected.
