### ISSUE TITLE
company-gtags: Invalid search bound (wrong side of point)

### ISSUE THREAD

**Issue by kaiwk** [company-mode/company-mode#862]
Generate tags with GNU Global (6.6.3) in a JavaScript project, when it complete word gives the following error:

> Debugger entered--Lisp error: (error "Invalid search bound (wrong side of point)")

I also found if I execute `gtags` in the project root, `company-gtags` won't do the completion. Only if I use gtags in the way like `gtags --gtagslabel=ctags` or `gtags --gtagslabel=pygments`, it can work but with error I mentioned above.

version: 0.9.9

**Comment by dgutov** [comment]
Does it always trigger this error? Any kind of completion, anywhere, with company-gtags?

**Comment by dgutov** [comment]
Could you create an example project where this problem occurs, generate the gtags database, zip it up and post it here? Or upload it somewhere and paste the url.

**Comment by kaiwk** [comment]
It seems the gtags problem. I delete the gtags file and regenerate them, somehow it works again. Besides, when the problem occured, I was also using ggtags-mode, but today I uninstalled the ggtags-mode.

**Comment by dgutov** [comment]
> Besides, when the problem occured, I was also using ggtags-mode

Unlikely, but it could be the reason for the problem as well. If you could repro and file a corresponding bug, that could help somebody as well.
