### ISSUE TITLE
Completion menu flickers on every input char

### ISSUE THREAD

**Issue by netjune** [company-mode/company-mode#865]
```company-backends``` is set to ```'(company-capf))```.

I can see the completion menu disappered and then showed again on every input char.

company version: 0.9.9

**Comment by dgutov** [comment]
`M-x company-diag`

**Comment by dgutov** [comment]
Never mind. What's the major mode?

**Comment by netjune** [comment]
The major mode is golang-mode.

The result of ```M-x company-diag```:
```
Emacs 26.1.90 (x86_64-apple-darwin17.7.0) of 2018-12-26 on jundeMac
Company 0.9.9

company-backends: (company-capf)

Used backend: company-capf
Major mode: go-mode
Prefix: "co"
Completions:
  #("complex" 0 1 (eglot--lsp-completion (:label #("complex" 0 1 (eglot--lsp-completion #2)) :kind 3 :detail "func(real FloatType, imag FloatType) ComplexType" :insertText "complex(${1:real FloatType}, ${2:imag FloatType})$0" :insertTextFormat 2 :textEdit (:range (:start (:line 286 :character 3) :end (:line 286 :character 5)) :newText "complex(${1:real FloatType}, ${2:imag FloatType})$0")) font-lock-face completions-common-part) 1 2 (font-lock-face completions-common-part) 2 3 (font-lock-face completions-first-difference)) #(" func(real FloatType, imag FloatType) ComplexType (snippet)" 1 49 (face font-lock-function-name-face))
  #("copy" 0 1 (eglot--lsp-completion (:label #("copy" 0 1 (eglot--lsp-completion #2)) :kind 3 :detail "func(dst []Type, src []Type) int" :insertText "copy(${1:dst []Type}, ${2:src []Type})$0" :insertTextFormat 2 :textEdit (:range (:start (:line 286 :character 3) :end (:line 286 :character 5)) :newText "copy(${1:dst []Type}, ${2:src []Type})$0")) font-lock-face completions-common-part) 1 2 (font-lock-face completions-common-part) 2 3 (font-lock-face completions-first-difference)) #(" func(dst []Type, src []Type) int (snippet)" 1 33 (face font-lock-function-name-face))
  #("complex128" 0 1 (eglot--lsp-completion (:label "complex128" :kind 7 :detail "complex128" :insertText #("complex128" 0 1 (eglot--lsp-completion #2)) :insertTextFormat 1 :textEdit (:range (:start (:line 286 :character 3) :end (:line 286 :character 5)) :newText "complex128")) font-lock-face completions-common-part) 1 2 (font-lock-face completions-common-part) 2 3 (font-lock-face completions-first-difference)) #(" complex128" 1 11 (face font-lock-function-name-face))
  #("complex64" 0 1 (eglot--lsp-completion (:label "complex64" :kind 7 :detail "complex64" :insertText #("complex64" 0 1 (eglot--lsp-completion #2)) :insertTextFormat 1 :textEdit (:range (:start (:line 286 :character 3) :end (:line 286 :character 5)) :newText "complex64")) font-lock-face completions-common-part) 1 2 (font-lock-face completions-common-part) 2 3 (font-lock-face completions-first-difference)) #(" complex64" 1 10 (face font-lock-function-name-face))
  #("conn" 0 1 (eglot--lsp-completion (:label "conn" :kind 6 :detail "*websocket.WSConn" :insertText #("conn" 0 1 (eglot--lsp-completion #2)) :insertTextFormat 1 :textEdit (:range (:start (:line 286 :character 3) :end (:line 286 :character 5)) :newText "conn")) font-lock-face completions-common-part) 1 2 (font-lock-face completions-common-part) 2 3 (font-lock-face completions-first-difference)) #(" *websocket.WSConn" 1 18 (face font-lock-function-name-face))
```

**Comment by joaotavora** [comment]
OK I'm here. AFAIU if the completions take a long time to fetch the menu will flicker a bit, since it re-fetches on every keystroke.  The typing responsiveness shouldn't be harmed, though.

Also, @netjune can you reproduce this from an emacs -Q run that has only eglot, company, go-mode and some basic Go hello world program?

**Comment by netjune** [comment]
Yes, I can reproduce it with emacs -Q.

**Comment by netjune** [comment]
Another problem:

I set ```company-minimum-prefix-length``` to 2 to prevent lsp to give too many completion items when I input a whitespace char. This affects the completion after a trigger char(such as '.'):

1. Company show completion menu after a trigger char(such as '.').
2. After I inputed one char, the completion menu disappearred.
3. After I inputed another char, the completion menu showed again.

**Comment by netjune** [comment]
Another question: Does company-capf support completion snippet?

**Comment by netjune** [comment]
I didn't see any delay, only flicker.

**Comment by joaotavora** [comment]
> Yes, I can reproduce it with emacs -Q.

And can we have the recipe? I.e. can you provide instructions, starting with `emacs -Q` so that any person can experience the same thing as you.

> I didn't see any delay, only flicker.

First of all "flicker" is very subjective.  Perhaps you can record a small video showing what you see. It would have to have a fairly good frame rate so that it doesn't hide the flicker.

In Eglot, as well as in SLY, when you type in the company popup you are requesting new completions for every keystroke.  It should never block your typing, i.e. you should be able to type very quickly, but that means that it doesn't always have time to seamlessly update the tooltip.  It's a compromise: fast typing for some "flicker".  In some early SLY versions, it used blocked for each keystroke meaning you would probably see no flicker but it was frustrating when you were typing quickly.

However "flicker" can also be due to many other factors (and this is why the Emacs -Q recipe is important).

**Comment by netjune** [comment]
I uploaded all elisp files to http://119.37.194.6/upload/company_eglot_flicker-elisp.tar.bz2 and the screen record file to http://119.37.194.6/upload/company_eglot_flicker.mp4.

0. you need to install golang and go langserver(go get github.com/sourcegraph/go-langserver) first. And make sure emacs can find the the go langserver's excutable.
1. download the file from the url
2. extract files to ```~/test/ttt```
3. emacs -Q
4. eval the following code in emacs:
```
(add-to-list 'load-path "~/test/ttt")
(load "~/test/ttt/autoloads.el")

(defun my-find-project (dir)
  `(my . ,dir))

(setq project-find-functions (list #'my-find-project))

(cl-defmethod project-roots ((project (head my)))
  (list (cdr project)))

(add-hook 'go-mode-hook 'my-lsp-enable-eglot)

(defun my-lsp-enable-eglot ()
  (interactive)
  (unless (bound-and-true-p eglot--managed-mode)
	  (message "=== enable eglot: %s" buffer-file-name)

	  (flymake-mode 1)
	  (company-mode 1)

	  (setq-local company-backends '(company-capf))
	  (setq-local company-minimum-prefix-length 2)
	  (setq-local company-transformers nil)

	  (eglot-ensure)))

```
5. create a new golang file with the following content:
```

package main

import (
	"fmt"
)

main () {
	fmt
}
```
6. Insert a '.' char after "fmt" in the main function. There will be completion menu. Then input "Prin" slowly. You will see the flicker.

**Comment by joaotavora** [comment]
Thanks @netjune.

As far as I can see from the video, it is only when you type a letter that the dialog briefly flickers.  It seems to be consistent with my explanation. I don't know how company-mode's display engine works. Perhaps it is just Emacs's. Perhaps it could delay redisplay a bit to sometimes avoid a redisplay cycle when the dialog isn't ready.

**Comment by dgutov** [comment]
> Until yesterday, I was completely unaware that `accept-process-output' or `input-pending-p' could run timers that do redisplay (https://lists.gnu.org/archive/html/bug-gnu-emacs/2013-08/msg00308.html)

:man_shrugging: That might be it.

**Comment by joaotavora** [comment]
> 🤷‍♂️ That might be it.

Serious archeology skills, but what do you suggest?

I can only 🤷‍♂️ myself

**Comment by dgutov** [comment]
Ask for a solid, minimal repro and see which code is best reasonably changed: yours or third-party.

Myself, I was kind of hoping I've dealt with most of the flickering problems with the recent changes to `company--fetch-candidates`.

**Comment by joaotavora** [comment]
> Ask for a solid, minimal repro

Not sure I follow. I can see flickering, for some definition of "flickering". I've always seen it in Sly and Eglot, which fetch candidates for every keystroke.  Isn't the popup _supposed_ to be torn down each time you type a new letter until  new completion candidates arrive?

**Comment by dgutov** [comment]
> I've always seen it in Sly and Eglot, which fetch candidates for every keystroke.

I've mentioned `company-clang` here already. Try reproducing with it. Maybe add some necessary element for it to reproduce.

> Isn't the popup supposed to be torn down each time you type a new letter until new completion candidates arrive?

Hidden. The difference is unimportant, though. Anyway, it's hidden in pre-command-hook and displayed in post-command-hook. Redisplay doesn't normally happen during that time, unless something triggers it.

**Comment by joaotavora** [comment]
> Hidden. The difference is unimportant, though. Anyway, it's hidden in pre-command-hook and displayed in post-command-hook. Redisplay doesn't normally happen during that time, unless something triggers it.

I see. Well, I did this in Eglot and it seems to have gone away...

```diff
diff --git a/eglot.el b/eglot.el
index 2d1c367..d2bee09 100644
--- a/eglot.el
+++ b/eglot.el
@@ -1852,7 +1852,8 @@ is not active."
            (funcall
             (completion-table-dynamic
              (lambda (_ignored)
-               (let* ((resp (jsonrpc-request server
+               (let* ((inhibit-redisplay t)
+                      (resp (jsonrpc-request server
                                              :textDocument/completion
                                              (eglot--CompletionParams)
                                              :deferred :textDocument/completion
```

Now, should this go into Eglot and SLY or maybe company-capf.el?

**Comment by joaotavora** [comment]
> I _think_ your change is in the right place

Really? Display-related company-specific-handholding code in a backend that's used by other frontends?

Of course there are company-specific hints there, like :company-x things, but these could in principle be generalized to other frontends, and they express information that only the backend has.

> We could add that binding to `company--fetch-candidates`, but it might not help in the async case either.

I haven't looked, but that seems better.  I don't know what you mean "async" case (SLY and Eglot are "async" for my definition of "async").  But even if your "async" is a different thing, some flicker correction is better than no flicker correction at all.

**Comment by joaotavora** [comment]
> Is there an option to use cache?

@netjune Not really, unless you can make sure that the new character doesn't widen the completion set. Otherwise you are missing completions.

**Comment by dgutov** [comment]
> Display-related company-specific-handholding code in a backend that's used by other frontends?

I'm pretty sure none of them would mind. But okay, it's not something I really want to argue about.

> I don't know what you mean "async" case

See the "Asynchronous Backends" section in the `company-backends` docstring.

**Comment by joaotavora** [comment]
> I'm pretty sure none of them would mind. But okay, it's not something I really want to argue about.

They probably wouldn't, but it's not very pretty.  And I'd have to repeat it both SLY and Eglot, which is a code smell.

Then again, I don't mind the flickering in the first place, it kinda helps me understand that it is actually working.

> See the "Asynchronous Backends" section in the `company-backends` docstring.

OK, will do.  I'll try to come up with something that ameliorates the problem, if it doesn't outright solve it.

**Comment by dgutov** [comment]
Actually, we already had `inhibit-redisplay` there, it just didn't cover the "synchronous" case.

@netjune Please see if it solves your problem.

**Comment by joaotavora** [comment]
> OK, will do. I'll try to come up with something that ameliorates the problem, if it doesn't outright solve it.

Oh, I see you fixed it already. Thanks!

**Comment by dgutov** [comment]
> Then again, I don't mind the flickering in the first place, it kinda helps me understand that it is actually working

It could be a debugging aid, but many people consider flickering annoying, myself included.

**Comment by netjune** [comment]
It works well now. Thank you very much.

**Comment by netjune** [comment]
> Not really, unless you can make sure that the new character doesn't widen the completion set. Otherwise you are missing completions.

In most cases, the new character doesn't widen the completion set.

I tried with a normal golang project(about 30 files). I see there is a delay after inputing a char during completion. And the go-langserver process takes 100% cpu. I haven't tried other lsp servers. 

I have used company-lsp before. It has a customize variable to enable cache. It clears the cache after company finished or cancelled.

**Comment by dgutov** [comment]
> Not really, unless you can make sure that the new character doesn't widen the completion set

When an extra inputted char would do that?

I think the bigger issue is server-side sorting, not filtering.

**Comment by joaotavora** [comment]
> When an extra inputted char would do that?

If the input pattern is a regexp for example.  As I said, it's up to the server to decide what completions to provide given just a buffer position.

Also, LSP can return incomplete lists and thus a new character would bring new completions. 

All these cases could be solved with some heuristic (an incomplete completions list is marked as such) but I believied it would complicate the code too much.  Patches welcome, though. 

> I think the bigger issue is server-side sorting, not filtering.

If the server were very well-behaved and did, say, nothing but prefix completion, I don't see how adding a character would mess with server-side sorting.

> I tried with a normal golang project(about 30 files). I see there is a delay after each char inputing during completion. And the go-langserver process takes 100% cpu. 


Perhaps it's the golang server that could use some caching.  It's in a much better place to do that.

**Comment by dgutov** [comment]
> and did, say, nothing but prefix completion

I'm talking about fuzzy completion, of course.

> Perhaps it's the golang server that could use some caching. It's in a much better place to do that.

Agreed.

**Comment by netjune** [comment]
> All these cases could be solved with some heuristic (an incomplete completions list is marked as such) but I believied it would complicate the code too much.

Maybe LSP can provide more information with the completion items to let company-mode to know whether the completion list should be updated on every char inputting.

Currently, most completion in my use is simple prefix completion which can be cached. And Emacs can work with less power(on mobile PC).
