### ISSUE TITLE
[company-capf]: company-minimum-prefix-length shouldn't affect the completion following a trigger char

### ISSUE THREAD

**Issue by netjune** [company-mode/company-mode#866]
I set company-minimum-prefix-length to 2 to prevent company-mode to give too many completion items when I input a whitespace char.

1. The company-mode shows a completion menu after a trigger char(such as '.' for golang).
2. After I input one char, the completion menu disappearred.
3. After I input another char, the completion menu shows again.

The problem is in 2. The completion menu shouldn't be hidden then.

**Comment by dgutov** [comment]
That depends on the completion function. Let me guess, Eglot again?

@joaotavora `:company-prefix-length` should handle the case of `.abc` as well. See `company-clang--prefix`.

**Comment by netjune** [comment]
>Let me guess, Eglot again?

Yes.

**Comment by joaotavora** [comment]
> @joaotavora `:company-prefix-length` should handle the case of `.abc` as well. See `company-clang--prefix`.

I can't understand. Can you elaborate?

**Comment by dgutov** [comment]
It should return non-nil even after `.abc`, not just after `.`.

Your implementation only looks back to see if it's preceded by a trigger character.

Have you benchmarked it, by the way? Behavior aside, having a loop with looking-back inside seems like it can be slow.

**Comment by dgutov** [comment]
I think it should do what `company-grab-symbol-cons` does. First calculate the prefix, then skip that many chars back, and then do what it currently does.

The non-nil value is `LENGTH` in `(PREFIX . LENGTH)` in the documentation of the `prefix` action in `company-backends`. You should probably return `t`.

> It isn't slow because the regexps in question never take it very far back.

I'm not sure `looking-back` knows that a simple regexp means do not go back too far. `looking-back`, when no passed a lower bound, always starts from the beginning of the buffer. If using `preceding-char` is not an option, better to pass `line-beginning-position` as the lower bound.

BTW, try opening a large buffer an evaluate `(benchmark 1 '(looking-back "\\."))` near its beginning, as well as near its end. The numbers are clearly different. Yes, the regexp scanner is fast, but why waste CPU cycles.

**Comment by dgutov** [comment]
> a number or a string whose length you are referring to by "that many"

A string. `"abc"`, in this example. Basically, mimic what the aforementioned function does.

> You ask to complete at a given position and hope the server replies with some sane results.

Hmm. Not sure what's the best approach, but `(skip-chars-backward "^([{ \t")` might do the trick.

> 2\. If It triggered via a trigger char, `company-minimum-prefix-length` should temporarily be ignored.

That would require some changes in Company core, not sure how complex.

> I don't think so, looking at the implementation, `greedy` has to be `t`, too. Otherwise it does what `re-search-backward` does.

`(benchmark 1 '(looking-back "s"))` show time proportional to the current line number (as long as the preceding char is not `s`). I think that's the only evidence we need. Maybe `re-search-backward` is similarly slow too, IDK. Anyway, setting the lower bound is always a good idea.

**Comment by dgutov** [comment]
> It used to behave greedily by default though, I think.

I'm using a recent build from `master`.

**Comment by dgutov** [comment]
> If It triggered via a trigger char, `company-minimum-prefix-length` should temporarily be ignored.

This is also not ideal, BTW. Even if I `C-g` after typing the trigger char, then change my mind and type `a`, completion should pop up right away, IMO.

**Comment by joaotavora** [comment]
>  Anyway, setting the lower bound is always a good idea.

Never said it wasn't :-) Just that something like, say, `(looking-back ".+")` is much much worse than `(looking-back "s")`, which are the types of regexps that I'm passing to `looking-back` right now.

> This is also not ideal, BTW. Even if I `C-g` after typing the trigger char, then change my mind and type `a`, completion should pop up right away, IMO.

Nothing is ideal in LSP/Emacs, because LSP is not made for Emacs (in theory it shouldn't be made for any editor but V\**cough*\*Scod\**cough*\*e)

Anyway, I forgot a basic premise here.  I'm coding a `capf` function in Eglot and Sly. I don't want to depend on Company at all, so using `company-x` vars isn't gonna fly.  I'm using these `:company-x` things in hopes that they will become standard or something.

But I'll try to figure something out within this confination.

**Comment by dgutov** [comment]
> because LSP is not made for Emacs

:man_shrugging: That is sad, of course.

>  I'm using these `:company-x` things in hopes that they will become standard or something.

I think they kind of are, or are going to be.

**Comment by joaotavora** [comment]
> I think they kind of are, or are going to be.

You should think about bringing company's frontend into core though, and make that work mostly, if not almost exlusively, with capf functions (You probably _have_ though about it, but it is easier said than done, I've had the same pending project with yasnippet for 5+ years)

**Comment by dgutov** [comment]
You've asked before, and I've responded: if somebody else does the work, I won't mind, but in the meantime Company in ELPA works well enough for most people (and there's a project on bundling ELPA packages with Emacs releases).

We can revisit this when CAPF is at full feature parity with native backends. And hopefully by that time it'll also be easier to understand and make completion functions for.

**Comment by joaotavora** [comment]
> You've asked before, and I've responded

I though you wouldn't mind a bit of extra lobbying

> Company in ELPA works well enough for most people

Agree, I've been using it more and more lately.

> We can revisit this when CAPF is at full feature parity with native backends.

What's missing? Some features are only useful for some frontends, right?

**Comment by dgutov** [comment]
> you wouldn't mind a bit of extra lobbying

I'm fine with it, but without extra arguments it won't change much. The bottleneck here is my lower motivation (after all these years) and not boundless free time. There are also other things in the core I should be dedicating efforts to.

> Some features are only useful for some frontends, right?

I don't see your point. Company exercises (almost) its full capabilities, and then some.

> What's missing?

Fuzzy matching, for one thing, so I'm following that discussion. An easier way to write "asynchronous" completion functions. And the "generic methods" proposal of yours might not hurt.

On the flip side, there are a few features I wanted to see in Company before tagging the version 1.0: completion from inside a symbol, posframe-like frontend, or ideally, a popup library that works everywhere with graceful degradation, TAB working inside yasnippet field overlays...

**Comment by joaotavora** [comment]
Back to the case in point, I seem to have fixed it, but I don't really know how...
```diff
diff --git a/eglot.el b/eglot.el
index 2d1c367..4001a50 100644
--- a/eglot.el
+++ b/eglot.el
@@ -1911,9 +1911,11 @@ is not active."
                (insert formatted)
                (current-buffer)))))
        :company-prefix-length
-       (cl-some #'looking-back
-                (mapcar #'regexp-quote
-                        (plist-get completion-capability :triggerCharacters)))
+       (save-excursion
+         (re-search-backward
+          (regexp-opt
+           (cl-coerce (plist-get completion-capability :triggerCharacters) 'list))
+          (line-beginning-position) t))
        :exit-function
        (lambda (comp _status)
          (let ((comp (if (get-text-property 0 'eglot--lsp-completion comp)
```

Seems to work alright:

![peek 2019-02-05 19-58](https://user-images.githubusercontent.com/387011/52300933-0bfa8c00-2981-11e9-87d1-3575a19add3f.gif)

**Comment by dgutov** [comment]
Err, what about `foo.bla; qux|`? Seems like it's going to be a false positive.

**Comment by joaotavora** [comment]
> Err, what about `foo.bla; qux|`? Seems like it's going to be a false positive.

Right... nothing to see here. :-)

**Comment by joaotavora** [comment]
> > Err, what about `foo.bla; qux|`? Seems like it's going to be a false positive.

> Right... nothing to see here. :-)

Yeah I got to use some heuristic, or be extra heroic and remember data about the invocation where the trigger char matched.

**Comment by dgutov** [comment]
In cases such as this, I always wonder how VS Code behaves, and whether it handles this kind of scenario well.

**Comment by joaotavora** [comment]
> I don't see your point. Company exercises (almost) its full capabilities, and then some.

No point, just confirming.

Actually what I meant is that we could add more features after company is in core, not before it.  And it shouldn't break the "external" company backends.  But it's late and I'm tired and I don't know if I thinking this right.

> Fuzzy matching, for one thing, so I'm following that discussion.

OK, I've been working on that.

> An easier way to write "asynchronous" completion functions.

That would be Stefans `backend` completion style.

>  And the "generic methods" proposal of yours might not hurt.

That would be nice, but mostly orthogonal.

>  TAB working inside yasnippet field overlays...

Hmm? you have an issue open for that?

**Comment by joaotavora** [comment]
> In cases such as this, I always wonder how VS Code behaves, and whether it handles this kind of scenario well.

Probably does heuristics.  And lots of servers serve VS-code specific messages.

**Comment by joaotavora** [comment]
What about this?
```diff
diff --git a/eglot.el b/eglot.el
index 2d1c367..e997f0a 100644
--- a/eglot.el
+++ b/eglot.el
@@ -1911,9 +1911,11 @@ is not active."
                (insert formatted)
                (current-buffer)))))
        :company-prefix-length
-       (cl-some #'looking-back
-                (mapcar #'regexp-quote
-                        (plist-get completion-capability :triggerCharacters)))
+       (save-excursion
+         (re-search-backward
+          (regexp-opt
+           (cl-coerce (plist-get completion-capability :triggerCharacters) 'list))
+          (- (point) company-minimum-prefix-length) t))
        :exit-function
        (lambda (comp _status)
          (let ((comp (if (get-text-property 0 'eglot--lsp-completion comp)
```

Minus the bit about the `company-minimum-prefix-length`, it does the right thing. 

Or maybe

```diff
diff --git a/eglot.el b/eglot.el
index 2d1c367..017c26f 100644
--- a/eglot.el
+++ b/eglot.el
@@ -1911,9 +1911,12 @@ is not active."
                (insert formatted)
                (current-buffer)))))
        :company-prefix-length
-       (cl-some #'looking-back
-                (mapcar #'regexp-quote
-                        (plist-get completion-capability :triggerCharacters)))
+       (save-excursion
+         (re-search-backward
+          (regexp-opt
+           (cl-coerce (plist-get completion-capability :triggerCharacters) 'list))
+          (if (car bounds) (1- (car bounds)) (line-beginning-position))
+           t))
        :exit-function
        (lambda (comp _status)
          (let ((comp (if (get-text-property 0 'eglot--lsp-completion comp)
```

Since I realize I'm already using `thing-at-point` anyway further up.

**Comment by joaotavora** [comment]
I fixed this Eglot issue, so @dgutov feel free to close the company issue

**Comment by dgutov** [comment]
> Actually what I meant is that we could add more features after company is in core, not before it.

completion-at-point could also exercise the important ones, even the asynchronous completion.

> Hmm? you have an issue open for that?

There are a few. They mostly talk about company-template, but the same conflict exists with Yasnippet, IIRC: https://github.com/company-mode/company-mode/issues/515, https://github.com/company-mode/company-mode/issues/281.

**Comment by dgutov** [comment]
> Probably does heuristics. And lots of servers serve VS-code specific messages.

Is there no way for Eglot to make use of them. I understand it's a complication, but if that's what's needed for feature parity...

**Comment by dgutov** [comment]
So you've decided to rely on thing-at-point here. OK, not the worst choice.

**Comment by netjune** [comment]
It works well now. Thank you.
