### ISSUE TITLE
Set the completion key to the right arrow key

### ISSUE THREAD

**Issue by billywade** [company-mode/company-mode#867]
Related to #640, I'd like to set up Company to only complete when I press the right arrow key instead of RET as it currently stands. How would I go about setting that up? Is there a way to do it in one binding or do I bind completion to the right arrow and unbind to RET separately?

**Comment by dgutov** [comment]
> Is there a way to do it in one binding

Nope.

> do I bind completion to the right arrow and unbind to RET separately

Yep.
