### ISSUE TITLE
company-clang: should return PREFIX nil in case of an error

### ISSUE THREAD

**Issue by vylu** [company-mode/company-mode#868]
I'm trying to configure company with company-clang and company-gtags backends. Usually I prefer company-clang, but if it fails for any reason (for example, can't find header file, etc) and does not return any candidates, I would like to continue with next backend (company-gtags). However, problem is that company stops on company-clang even if it fails with an error and returns no candidates.

My guess it is because company-clang does not return PREFIX nil in case of an error.

**Comment by dgutov** [comment]
The `prefix` action does not call the background process. It needs to be fast.

**Comment by vylu** [comment]
Is there anything what could be done? Because as it is now it is clearly wrong -- one backend fails, but company does not advance to the next backend.

**Comment by dgutov** [comment]
In general, when a backend fails, it's a reason to fix its configuration, or stop using it. Fuzzy failover is not my favorite idea.

You can try writing a composite backend that delegates, or simply use a more advanced Clang-based backend.

**Comment by dgutov** [comment]
In general, when a backend fails, it's a reason to fix its configuration, or stop using it. Fuzzy failover is not my favorite idea.

You can try writing a composite backend that delegates, or simply use a more advanced Clang-based backend.

**Comment by vylu** [comment]
I see your point regarding fixing configuration. In my case project build system is very complex and effort configuring company-clang properly will not pay off. For me it is ok to see proper completions (clang) when those can be resolved, and see all completions (gtags) when other backends fails because of wrong configuration/etc. 

composite backend is a good idea. 

Feel free to close this issue.
