### ISSUE TITLE
how to activate company in echo area to auto complete file paths with org-insert-link

### ISSUE THREAD

**Issue by avocadoras** [company-mode/company-mode#869]
Is there a way to have company auto complete a file path when inserting a link in org mode? Could this functionality also be activate when inserting them literally with `[[][]]` I cannot get company to search for the file path when I type the square brackets.

![screen shot 2019-02-11 at 9 49 39 am](https://user-images.githubusercontent.com/36335687/52574830-b8ee6200-2de2-11e9-9ea3-3745a3c62580.png)

**Comment by fraricci** [comment]
Hello and thanks for this awesome package.
I have the same problem, I cannot get a file path completed after a "[".
Example, in org-mode when I want to insert a link to a file
I start writing "[[~/Documents/" but when I try to get suggestion
from company typing <TAB> it doesn't work. I need to add a space
as "[[ ~/Documents/" to get it. Is there any solution for this?

Thanks in advance

**Comment by dgutov** [comment]
@fraricci Just pushed a fix for this to master, please take a look when you have a chance.

@avocadoras Does this solve your problem as well? TBH I wasn't clear on what your problem is: completion inside the buffer or (like I thought as first) completion in the minibuffer when typing after `Link: `.

**Comment by fraricci** [comment]
perfect it works!

thank you

**Comment by avocadoras** [comment]
@dgutov My bad, I was new to Emacs when I submitted the issue. Back then, I wished to autocomplete relative paths right after calling `C-c C-l`.  I think I was trying to type in the link completely, including the scheme, that I wished to get an autocomplete candidate list. However, I rarely have a use case for this today, since I can get the same result using Ivy. 

Auto completion works when I type `[[`, so all good! I'll close this issue.
