### ISSUE TITLE
company-yasnippet not always showing snippet name

### ISSUE THREAD

**Issue by mac230** [company-mode/company-mode#871]
I use company-yasnippet to insert snippets into buffers in a variety of different modes (emacs-lisp-mode, org-mode, ess-mode, etc...).  I've noticed that in ess-mode, company displays the snippet key on the left and the snippet name on the right when completing from the company-yasnippet backend.  This is quite nice, since you can give a more descriptive name while using a short snippet key, e.g., key="print", name="print an object" -> I then see "print      print an object" in the company completion popup.  I can't seem to get this same behavior from other modes, however, and am wondering why.  A couple of notes:

1. In both cases, the backend completing is listed as "company-yasnippet" in the modeline.
2. M-x company-diag with a completion showing the name has "(yas-annotation" followed by the snippet name text.  When the name is not showing, this is absent from the company-diag text.
3. company-tooltip-align-annotations is set to "t" for both cases. 

Company backends for my my ess setup (which shows the name) and shell-mode (which does not):

`;; ess-mode`
`'((company-files company-R-objects company-yasnippet company-R-args company-R-library :separate))`
`;; shell-mode`
`'(company-files company-yasnippet :separate)`

**Comment by dgutov** [comment]
Shouldn't shell-mode entry have more parens? For grouping.

**Comment by mac230** [comment]
Wow, that indeed does fix the issue and I now get names along w/ keys in the company popup in shell.  Thank you very much for the quick reply and simple solution. 

What's different given company was using the company-yasnippet backend w/o the grouping parens in the first place?

**Comment by dgutov** [comment]
> What's different given company was using the company-yasnippet backend w/o the grouping parens in the first place?

The first backend in the list was used instead, I think. Or else you were triggering some bug, for which I need a step-by-step repro.

**Comment by mac230** [comment]
Not necessary, but thanks for the offer.

In case it helps anyone else w/ this or similar issues, the display of the snippet name also disappears when company-yasnippet is the only completing backend.  

So, if I make a snippet as follows:
key="listp"
name="listp - check if list"
and set company-backends as follows:

`'((company-elisp company-yasnippet :separate))`

when I type "list", I'll see both "list" (from the company-elisp backend) and "listp    listp - check if list" (from the company-yasnippet backend).  As soon as I then type "p", "listp" will be the only thing shown since there is no longer any candidate from company-elisp.

**Comment by dgutov** [comment]
That's easy: the inline preview backend doesn't show annotations.

**Comment by dgutov** [comment]
But you can set up `company-frontends` to only use the popup frontend.

**Comment by mac230** [comment]
Thanks for the follow-up on that.  I had not explored frontends previously.  

`(set (make-local-variable 'company-frontends) '(company-pseudo-tooltip-frontend company-echo-metadata-frontend))`

gives me the result I'm looking for.
