### ISSUE TITLE
company-clang doesn't display clang candidates

### ISSUE THREAD

**Issue by lplatter** [company-mode/company-mode#872]
I am trying to get completion to work with company-clang. In particular, I would like to get completion candidates that are from header files that I provide with

dir-locals.el

When I look at the buffer clang-output. I can see the correct completion candidates.

However, in the code itself I only get the message

> no completion found

Any idea what I am doing wrong? I follow the standard advice for setting up company.

My setup in .emacs

    (require 'company)
    (add-hook 'after-init-hook 'global-company-mode)
    (require 'cc-mode)
    (define-key c-mode-map  (kbd "<tab>") 'company-complete)
    (define-key c++-mode-map (kbd "<tab>") 'company-complete)

Using M-x company-diag I get

    Emacs 26.1 (x86_64-apple-darwin14.5.0) of 2018-05-28 on builder10-10.porkrind.org
    Company 0.9.9
    
    company-backends: (company-irony company-clang company-xcode company-ropemacs company-cmake company-capf company-ob-ipython
    	       (company-dabbrev-code company-gtags company-etags company-keywords))
    Used backend: company-clang
    Major mode: c++-mode
    Prefix: #("gsl_e" 0 1
      (fontified t)
      1 2
      (fontified t)
      2 3
      (fontified t)
      3 4
      (fontified t)
      4 5
      (fontified t))
    
    Completions: none

**Comment by dgutov** [comment]
Might be some incompatibility with the Clang you have installed (if so, that would be unfortunate).

Could you post the contents of `*clang-output*` in that case? Or at least a part, including the lines with "correct completion candidates".

**Comment by lplatter** [comment]
The output has an error message but I everything was working before I updated from MELPA. So I think company-clang was able to deal with the error prior to the update.

>  In file included from <stdin>:16:
> ./TwoBodyInteraction.hh:8:10: fatal error: 'tr1/cmath' file not found
> #include <tr1/cmath>
>          ^~~~~~~~~~~
> 1 error generated.
> COMPLETION: gsl_eigen_francis_workspace : gsl_eigen_francis_workspace
> COMPLETION: gsl_eigen_gen_workspace : gsl_eigen_gen_workspace
> COMPLETION: gsl_eigen_genherm_workspace : gsl_eigen_genherm_workspace
> COMPLETION: gsl_eigen_genhermv_workspace : gsl_eigen_genhermv_workspace
> COMPLETION: gsl_eigen_gensymm_workspace : gsl_eigen_gensymm_workspace
> COMPLETION: gsl_eigen_gensymmv_workspace : gsl_eigen_gensymmv_workspace
> COMPLETION: gsl_eigen_genv_workspace : gsl_eigen_genv_workspace
> COMPLETION: gsl_eigen_herm_workspace : gsl_eigen_herm_workspace
> COMPLETION: gsl_eigen_hermv_workspace : gsl_eigen_hermv_workspace
> COMPLETION: gsl_eigen_nonsymm_workspace : gsl_eigen_nonsymm_workspace
> COMPLETION: gsl_eigen_nonsymmv_workspace : gsl_eigen_nonsymmv_workspace
> COMPLETION: gsl_eigen_sort_t : gsl_eigen_sort_t
> COMPLETION: gsl_eigen_symm_workspace : gsl_eigen_symm_workspace
> COMPLETION: gsl_eigen_symmv_workspace : gsl_eigen_symmv_workspace

**Comment by dgutov** [comment]
> everything was working before I updated from MELPA

Any idea what the version was before the update? You could try different versions using the Git checkout, you know.

**Comment by dgutov** [comment]
Oh. I get it. This is the change: https://github.com/company-mode/company-mode/commit/d00bbbac3be99d042024734fc417ecad253a52e4

**Comment by dgutov** [comment]
Since some includes are failing, apparently in your case the "original" definitions are not available, just the identity defines. I think it should work once you make sure there are not include-related errors anymore.

**Comment by lplatter** [comment]
First of all thanks for the help! 

I am not sure what's going on. I have included boost's tr1 headers into .dir-locals.el and have eliminated the error message. 

However, in a simpler file (small set of headers) I am able to get completion to work.

How can I find the problem. clang-error buffer does not exist anymore and M-x company-diag gives

Emacs 26.1 (x86_64-apple-darwin14.5.0) of 2018-05-28 on builder10-10.porkrind.org
Company 0.9.9

company-backends: (company-irony company-clang company-xcode company-ropemacs company-cmake company-capf company-ob-ipython
	       (company-dabbrev-code company-gtags company-etags company-keywords))

> Used backend: company-clang
> Major mode: c++-mode
> Prefix: #("gsl_matri" 0 1
>   (fontified t)
>   1 2
>   (fontified t)
>   2 3
>   (fontified t)
>   3 4
>   (fontified t)
>   4 5
>   (fontified t)
>   5 6
>   (fontified t)
>   6 7
>   (fontified t)
>   7 8
>   (fontified t)
>   8 9
>   (fontified t))
> 
> Completions: none

**Comment by lplatter** [comment]
Ok, so is company clang also supposed to be able to complete types defined in the header function. This is what I am actually trying to do and I just realized it works with functions.

**Comment by dgutov** [comment]
> is company clang also supposed to be able to complete types defined in the header function

In the header files, you mean? Yes, it should.

> clang-error buffer does not exist anymore

`*clang-output*` should still exist.

**Comment by cburn11** [comment]
I have run into the same issue testing out my cpp emacs config on ubuntu's 19.04 beta, which currently has clang-8 as its defualt and company-20190402.2323 from melpa. The completion popup did not display all the results from *clang-output*.

I took screenshots; I was unsure of the best way to document the *clang-output* and popup.

For instance, including <string> and asking for completions on std::str gave the following:

[std::str incomplete](https://i.imgur.com/oWJbHzR.png)

Including <fstream> and searching on an instance of std::ifstream gave:

[std::ifstream incomplete](https://i.imgur.com/BWDJlbr.png)

But once I reverted back to company-0.9.6 and clang-7, the popup contained all of the results from *clang-output*:

[std::ifstream complete](https://i.imgur.com/rqnzewx.png)
[std::str complete](https://i.imgur.com/RupYUzm.png)

I think it's two separate issues: the output from both clang versions for std::str is the same, but only company-0.9.6 displays all results.

The clang output on the search on the std::ifstream instance is slightly different from clang-7 and clang-8.

**Comment by dgutov** [comment]
You seem to be right.

I've already addressed the changes between company-0.9.6 and the current version, see the issue linked to that commit. I'm moderately sure the change is correct.

As for Clang 8, though, it seems to have changed the output indeed. I've no idea what those `InBase`, `Inaccessible`, etc, mean. Have you seen any relevant release notes?

**Comment by cburn11** [comment]
I have not seen release notes, but I think the relevant commits are:

InBase, 10/24/2018 [commit abaf72c](https://github.com/llvm-mirror/clang/commit/abaf72c02d9ce6cc9d53b99fd0851ebe66cef129#diff-039c27f1146f96ffcbdddda16ed7d01a)

Inaccessible, 12/3/2018 [commit 43d57f5](https://github.com/llvm-mirror/clang/commit/43d57f5da141e4bea8e05e1312034a896afde6fc#diff-039c27f1146f96ffcbdddda16ed7d01a)

**Comment by dgutov** [comment]
@cburn11 Thank you, that's really helpful. Could you file a separate issue for Clang 8 incompatibility, though?

**Comment by dgutov** [comment]
This one should now be fixed by the latest commit.
