### ISSUE TITLE
Company error (wrong-type-argument stringp nil)

### ISSUE THREAD

**Issue by VisionaryAppDev** [company-mode/company-mode#876]
Hi everyone, 

Company mode just throws me some error when I am typing. Just after open Emacs, I switch to scratch file and then I type a few word and suddenly, it throw me an error in Backtrace as below:
```
Debugger entered--Lisp error: (wrong-type-argument stringp nil)
  string-match("r" nil)
  company-auto-complete-p("r")
  company--continue()
  company--perform()
  company-post-command()

```

I have configure my company mode as following:
```
(use-package company
  :ensure t
  :init
  (add-hook 'after-init-hook 'global-company-mode)
  :config
  (progn
    (setq-default company-dabbrev-other-buffers 'all
                  company-tooltip-align-annotations t
                  company-dabbrev-code-everywhere t)
    (setq company-auto-complete t)
    (setq company-backends '(
  			                 company-lsp
			                 company-elisp
			                 company-css
			                 ;; company-restclient
			                 company-files
			                 company-capf
			                 company-keywords
			                 ;; company-gtags 
			                 ;; company-yasnippet
                                         ;; company-web-html
                                         ;; company-ispell
                                        ;; esh-autosuggest
                                        company-semantic
			                 company-dabbrev-code
			                 company-dabbrev
			                 ))
    

    (setq company-tooltip-limit 20                      
	      company-idle-delay 0                         
	      company-echo-delay 0                          
	      company-tooltip-idle-delay 0
	      company-minimum-prefix-length 1
	      company-tooltip-flip-when-above t
	      company-selection-wrap-around t
	      company-require-match nil
	      company-show-numbers t
	      company-auto-complete-chars nil               
	      company-begin-commands '(self-insert-command) 
	      company-tooltip-align-annotations t)          
    )
```

 By the way, I think this configuration is a little slow especially in lsp-mode. if anyone has any suggestion and feedback, please kindly share.

**Comment by dgutov** [comment]
Your values of `company-auto-complete` and `company-auto-complete-chars` are incompatible.

**Comment by VisionaryAppDev** [comment]
@dgutov please explain what do you mean by incompatible and what should i do?

**Comment by dgutov** [comment]
Why are you setting `company-auto-complete-chars` to nil?

**Comment by VisionaryAppDev** [comment]
@dgutov  It's because company mode always show completion at point. For example, I type "var" then it shows the full meaning or suggestion, "variable". I don't want that suggestion, I want only "var" so i press enter, tab, space or almost anything, company mode still complete that word for me while i don't want. I think escape might be able to solve but doing so is not a solution because it's already bind to Evil mode and it's so annoying if i have to do this all the time.

**Comment by dgutov** [comment]
Set `company-auto-complete` to nil, then.

**Comment by VisionaryAppDev** [comment]
Now i set   `company-auto-complete-chars nil` and `company-auto-complete` to nil. I think the problem stop occur now.
