### ISSUE TITLE
Capf backend in shell mode incorrectly completing directories

### ISSUE THREAD

**Issue by memeplex** [company-mode/company-mode#879]
I have set

```
(global-set-key (kbd "C-<tab>") #'company-complete)
```

In shell mode (`M-x shell`) I type:

```
cd /ho<C-Tab>    ->   cd /home/
cd /home/<C-Tab>    ->  cd /home/..
```
The problem is in:

```
(defun company-complete ()
...
    (if (or company-selection-changed
            (eq last-command 'company-complete-common))
        (call-interactively 'company-complete-selection)
      (call-interactively 'company-complete-common)
      (setq this-command 'company-complete-common))))
```

Here the second consecutive `<C-Tab>` is making `(eq last-command 'company-complete-common)` true but `company-selection-changed` remains false, so the second time the first entry `..` is automatically but wrongly chosen.

**Comment by memeplex** [comment]
I'm not sure whether the problem is that the `last-command` test shouldn't be done if `(company-manual-begin)` or that `company-selection-changed` should be true.

**Comment by dgutov** [comment]
Why are you pressing `C-TAB` again, if not to insert the current selection?

**Comment by memeplex** [comment]
Maybe I'm not being clear. This is the initial state:

```
cd /ho
```

Now I press `<C-Tab>` once and get:

```
cd /home/
```

Now I want to continue completing the path with another subdirectory under `/home` so I press `<C-Tab>` again, but instead of a menu with `..` and some users I get:

```
cd /home/..
```

Which is hardly what I (and anybody else, I guess) want.

**Comment by dgutov** [comment]
OK, I can see the problem. It's that the previous invocation of `company-complete` already performed insertion and finished completion. Whereas our our `last-command` check expects that if it was the previous command, it didn't finish the completion.

**Comment by dgutov** [comment]
Should work now, using a tiny trick.

**Comment by memeplex** [comment]
Great, I'm looking at your commit. Will test it later and close this if everything goes well. Thanks!
