### ISSUE TITLE
Not showing any candidates with company-dabbrev

### ISSUE THREAD

**Issue by zzhjerry** [company-mode/company-mode#882]
No candidate is showing up with `company-mode` enabled. The cursor is behind `UP` and I'm expecting a list of candidates since there are other similar symbols. Like:
![image](https://user-images.githubusercontent.com/4972027/54657453-83851480-4b04-11e9-9312-318ad7053490.png)

Value of `comapny-backends` is:

```
Value: ((company-tern :with company-yasnippet)
 (company-dabbrev-code company-gtags company-etags company-keywords :with company-yasnippet)
 (company-files :with company-yasnippet)
 (company-dabbrev :with company-yasnippet))
```
Value of `company-dabbrev-other-buffers` is `all`.
Value of `company-minimum-prefix-length` is `2`

 I searched other issues and found no solution. 

What's the problem and how may I solve it?

**Comment by dgutov** [comment]
What does `M-x company-diag` say?

**Comment by zzhjerry** [comment]
Thanks for replying. `company-diag` says

```
Emacs 25.3.1 (x86_64-apple-darwin17.2.0) of 2018-03-23 on zhangzhaohengs-MacBook-Pro.local
Company 0.9.9

company-backends: ((company-tern :with company-yasnippet)
 (company-dabbrev-code company-gtags company-etags company-keywords :with company-yasnippet)
 (company-files :with company-yasnippet)
 (company-dabbrev :with company-yasnippet))

Used backend: (company-tern :with company-yasnippet)

Major mode: js2-mode
Prefix: #("UP" 0 2
  (fontified t font-lock-face js2-object-property))

Completions: none
```

**Comment by dgutov** [comment]
> company-tern

There you go. It's being used, but not returning any completions in the given context.

**Comment by zzhjerry** [comment]
Wouldn't the backend to be used being passed to the next one in this case?

**Comment by dgutov** [comment]
Nope. We don't do that.

Search the issue tracker, there are a few discussions about that.
