### ISSUE TITLE
company-clang doesn't work for self defined macro and linux header

### ISSUE THREAD

**Issue by lzfgnu** [company-mode/company-mode#884]
![Screenshot from 2019-04-13 23-18-03](https://user-images.githubusercontent.com/25069103/56081684-ab854080-5e42-11e9-8a2b-905482eaef1a.png)
![Screenshot from 2019-04-13 23-19-13](https://user-images.githubusercontent.com/25069103/56081686-b049f480-5e42-11e9-9a13-6126a1e81240.png)

**Comment by cburn11** [comment]
As @dgutov recently pointed out https://github.com/company-mode/company-mode/issues/872#issuecomment-464351116 in issue https://github.com/company-mode/company-mode/issues/872

it's https://github.com/company-mode/company-mode/commit/d00bbbac3be99d042024734fc417ecad253a52e4 where company-clang drops the results from clang.

If you open the *clang-output* while you try to autocomplete, clang does return results for [TEST](https://i.imgur.com/CqYw81e.png) and [socklen](https://i.imgur.com/IytpAMK.png), but drops them for the popup.

Revert the changes in that commit, and company-clang includes all the results from clang for [TEST](https://i.imgur.com/cwVfyYs.png) and [socklen](https://i.imgur.com/YpPz0PO.png).

**Comment by dgutov** [comment]
Sorry about that, upon further inspection, it was indeed a wrong change. Reverting it now.
