### ISSUE TITLE
clang 8 code completion incompatibility

### ISSUE THREAD

**Issue by cburn11** [company-mode/company-mode#885]
Clang 8 adds new tags for code completion results for declarations. 

[commit abaf72](https://github.com/llvm-mirror/clang/commit/abaf72c02d9ce6cc9d53b99fd0851ebe66cef129#diff-039c27f1146f96ffcbdddda16ed7d01a) adds the (InBase) tag. 

[commit 43d57f](https://github.com/llvm-mirror/clang/commit/43d57f5da141e4bea8e05e1312034a896afde6fc#diff-039c27f1146f96ffcbdddda16ed7d01a) adds the (Inaccessible).

The prior behavior was to add a (Hidden) tag if, for example, a declaration, in a derived class hid a base class member: 
> COMPLETION: operator= (Hidden) : [#MY_BASE &#]MY_BASE::operator=(<#const MY_BASE &#>)

Currently, the regexp template string in company-clang.el, lines 113, 114:

`
(defconst company-clang--completion-pattern
"^COMPLETION: \\_<\\(%s[a-zA-Z0-9_:]*\\)\\(?: : \\(.*\\)$\\)?$")
`

 does not match any result that contains has anything other than single space between the prefix and the subsequent colon. Now that clang tags anything in the base with a (InBase) tag, the current regular expression drops useful results too. For example, the clang result:

> COMPLETION: m_public_int_1 (InBase) : [#int#][#MY_BASE::#]m_public_int_1

is not matched by the regex because of the new (InBase) tag.

Some suggested temporary fixes:

1. update the regex to match any of the declaration tags:

```
--- a/company-clang.el
+++ b/company-clang.el
@@ -111,7 +111,7 @@ or automatically through a custom `company-clang-prefix-guesser'."
 ;; TODO: Handle Pattern (syntactic hints would be neat).
 ;; Do we ever see OVERLOAD (or OVERRIDE)?
 (defconst company-clang--completion-pattern
-  "^COMPLETION: \\_<\\(%s[a-zA-Z0-9_:]*\\)\\(?: : \\(.*\\)$\\)?$")
+  "^COMPLETION: \\_<\\(%s[a-zA-Z0-9_:]*\\)\\(?:[ (,)a-zA-Z0-9]* : \\(.*\\)$\\)?$")
 
 (defconst company-clang--error-buffer-name "*clang-error*")
```

2. update the regex to match results with just the (InBase) tag:

```
--- a/company-clang.el
+++ b/company-clang.el
@@ -111,7 +111,7 @@ or automatically through a custom `company-clang-prefix-guesser'."
 ;; TODO: Handle Pattern (syntactic hints would be neat).
 ;; Do we ever see OVERLOAD (or OVERRIDE)?
 (defconst company-clang--completion-pattern
-  "^COMPLETION: \\_<\\(%s[a-zA-Z0-9_:]*\\)\\(?: : \\(.*\\)$\\)?$")
+  "^COMPLETION: \\_<\\(%s[a-zA-Z0-9_:]*\\)\\(?:\\(?: (InBase)\\)? : \\(.*\\)$\\)?$")
 
 (defconst company-clang--error-buffer-name "*clang-error*")
```
In my opinion, this is the most desirable temporary workaround: [It keeps the useful completion results](https://i.imgur.com/bDGXphi.png)

3. (Not practical, but technically works) Patch out the new behavior in clang:

```
--- a/lib/Sema/CodeCompleteConsumer.cpp
+++ b/lib/Sema/CodeCompleteConsumer.cpp
@@ -555,11 +555,11 @@ void PrintingCodeCompleteConsumer::ProcessCodeCompleteResults(
         std::vector<std::string> Tags;
         if (Results[I].Hidden)
           Tags.push_back("Hidden");
-        if (Results[I].InBaseClass)
+        /*if (Results[I].InBaseClass)
           Tags.push_back("InBase");
         if (Results[I].Availability ==
             CXAvailabilityKind::CXAvailability_NotAccessible)
-          Tags.push_back("Inaccessible");
+          Tags.push_back("Inaccessible");*/
         if (!Tags.empty())
           OS << " (" << llvm::join(Tags, ",") << ")";
       }

```

**Comment by dgutov** [comment]
Thank you for all the detail. :+1: 

I'm almost done with option 1 already, but option 2 does sound more attractive (e.g. for performance).

So there are no other tags so far, and `Inaccessible` and `Hidden` methods are basically those the programmer couldn't use anyway. Is that correct?

Have you tried your change? Does it give good results? In that case I can just install it. Permanently, so to speak.

**Comment by dgutov** [comment]
It would be best if you opened a PR, otherwise, it hard for me to properly attribute the change in the commit.

**Comment by cburn11** [comment]
So far, there are only 3 tags for declarations. (Hidden) has been there since the beginning. I have not delved far enough into clang to say definitively what the tags mean, but just a simple base and derived class generates all three tags in a way that their names are descriptive:

```
class MY_BASE {

  int m_priv_int_1;
  int m_priv_int_2;

public:

  int m_public_int_1;
  int m_public_int_2;
};

class MY_DERIVED : public MY_BASE {

  int m_priv_derived_int;
  int m_priv_int_2;
  
public:

  int m_public_derived_int;
  int m_public_int_2;
  
};

int main(int argc, char * argv[]) {

  MY_BASE b;

  MY_DERIVED d;
  d.
  
  return 0;
}
```
Completion request on "d." generates:

```
COMPLETION: m_priv_derived_int (Inaccessible) : [#int#]m_priv_derived_int
COMPLETION: m_priv_int_1 (InBase,Inaccessible) : [#int#][#MY_BASE::#]m_priv_int_1
COMPLETION: m_priv_int_2 (Inaccessible) : [#int#]m_priv_int_2
COMPLETION: m_priv_int_2 (Hidden,InBase,Inaccessible) : [#int#]MY_BASE::m_priv_int_2
COMPLETION: m_public_derived_int : [#int#]m_public_derived_int
COMPLETION: m_public_int_1 (InBase) : [#int#][#MY_BASE::#]m_public_int_1
COMPLETION: m_public_int_2 : [#int#]m_public_int_2
COMPLETION: m_public_int_2 (Hidden,InBase) : [#int#]MY_BASE::m_public_int_2
COMPLETION: MY_BASE (InBase) : MY_BASE::
COMPLETION: MY_DERIVED : MY_DERIVED::
COMPLETION: operator= : [#MY_DERIVED &#]operator=(<#const MY_DERIVED &#>)
COMPLETION: operator= : [#MY_DERIVED &#]operator=(<#MY_DERIVED &&#>)
COMPLETION: operator= (Hidden,InBase) : [#MY_BASE &#]MY_BASE::operator=(<#const MY_BASE &#>)
COMPLETION: operator= (Hidden,InBase) : [#MY_BASE &#]MY_BASE::operator=(<#MY_BASE &&#>)
COMPLETION: ~MY_BASE (InBase) : [#void#][#MY_BASE::#]~MY_BASE()
COMPLETION: ~MY_DERIVED : [#void#]~MY_DERIVED()
```
The compiler would return an error if any of the members marked Hidden or Inaccessible were accessed.

Option 2 filters the results desirably in that simple test. I tried it on some other projects and it "seems" to work fine. 

I called it a temporary fix because editing the regex template string every a tag is added seems error, but these are the first additional tags since this files origin, so the current convenience is probably fine.

I forked the project and created a pull request.

**Comment by dgutov** [comment]
Thank you, merged.

> editing the regex template string every a tag is added seems error

Let's see if there are going to be new tags that we won't want to filter out.
