### ISSUE TITLE
Feature request: file path auto-completion with file path alias supported.

### ISSUE THREAD

**Issue by hanzhixing** [company-mode/company-mode#887]
I'm currently using spacemacs as my first editor. [There is an issue submitted to spacemacs](https://github.com/syl20bnr/spacemacs/issues/12194)

I want a feature like below.

1. Configuration(in json) imagined
{
    "@/": "../source-files/src/"
}
2. In source file
`import Foo from '@/components/Foo' // <--- ../source-files/src/componets/Foo.js`

3. Without expansion.
`@/components/..` must be reserved as typed.

When after I enter a `@/`, I wish to see the candidates options like after entering `~/`.

I know now the `~` is a feature built in the Bash itself, file path aliases like this can not be configured in other way.

(I guest it is right place to submit this issue to `company-mode`.)

Is it possible enhancing current `company-files` to support this?

Or, thank you if you let me know how to approach this.

**Comment by dgutov** [comment]
I'd review a PR. (Note that it will require copyright assignment if the changes are >15 lines total).

**Comment by hanzhixing** [comment]
> I'd review a PR. (Note that it will require copyright assignment if the changes are >15 lines total).

You mean there are already related PRs/issues? Could you link it here?

**Comment by dgutov** [comment]
No, I basically meant the standard "patch welcome".
