### ISSUE TITLE
doesn't complete when I type __pool_allocator

### ISSUE THREAD

**Issue by lzfgnu** [company-mode/company-mode#888]
__pool_allocator is provided by GNU c, and it is located in "/usr/include/c++/7/ext/pool_allocator.h".

it's weird that when I write #include "usr/include/c++/7/ext/pool_allocator.h", company-mode works.
but when I write #include <ext/pool_allocator.h>, It doesn't work

I guess that the reason may related to the prefix __, because It can complete bitmap_allocator, which doesn't contain prefix __. what's more, when I type using namespace __gnu_cxx, it doesn't complete __gnu_cxx either.

My emacs version is 25.2.2, clang version is 7.0, and company-mode version is 0.9.6
![111](https://user-images.githubusercontent.com/25069103/56796271-c5f8ea00-6844-11e9-89a3-c2d10d7f98aa.png)
![2](https://user-images.githubusercontent.com/25069103/56795678-90073600-6843-11e9-8ffa-0993186d7339.png)
![3](https://user-images.githubusercontent.com/25069103/56795687-92699000-6843-11e9-9e4b-d7cc928cf7d4.png)
![4](https://user-images.githubusercontent.com/25069103/56795698-95648080-6843-11e9-8857-23656dc40476.png)

**Comment by dgutov** [comment]
And what's your value of `company-clang-arguments`?

**Comment by dgutov** [comment]
> company-mode version is 0.9.6

This version is quite old, you could also try updating.

**Comment by lzfgnu** [comment]
> And what's your value of `company-clang-arguments`?

Thank you for replying. should I add the header paths to these arguments?
![1](https://user-images.githubusercontent.com/25069103/56815456-002db000-6874-11e9-9595-3652e54c30bf.png)

**Comment by dgutov** [comment]
Try adding them as `"-Ipath/to/headers", "-Ianother/path/to/headers"`.

**Comment by cburn11** [comment]
I ran into a similar problem with clang code completion and the gcc headers.  The issue is with the way clang treats the headers it auto includes as `-internal-isystem`. When you `#include <ext/pool_allocator.h>` that .h is in `/usr/include/c++/7` subject to your gcc version, but clang -x c++ typically include that directory as `-internal-isystem /usr/include/c++/7` and subsequently ignores `-I /usr/include/c++/7`. 

With a simple file (completion.cpp):

```
#include <ext/pool_allocator.h>

int main(int argc, char * argv[]) {

  __gnu_cxx::__p
  
  return 0;
}
```
calling clang on the command line for the code completion after __p doesn't return any result:

```
clifford@clang-container:~/projects/clang-test$ clang -fsyntax-only -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -Xclang -code-completion-macros -x c++ -Xclang -code-completion-at=completion.cpp:5:16 completion.cpp
clifford@clang-container:~/projects/clang-test$ 
```
The verbose output shows that clang is ignoring the -I includes:

```
clifford@clang-container:~/projects/clang-test$ clang -v -fsyntax-only -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -Xclang -code-completion-macros -x c++ -Xclang -code-completion-at=completion.cpp:5:16 completion.cpp
clang version 9.0.0 (https://llvm.org/git/clang.git 30418fa5f7bd6b2ef238385acb3fa07c938981cb) (https://llvm.org/git/llvm.git 4a926e0ed80f52da39d38645ee602a17b3189b46)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /home/clifford/installs/current/llvm-gcc/bin
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/6
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/6.5.0
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/7
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/7.3.0
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/8
Selected GCC installation: /usr/lib/gcc/x86_64-linux-gnu/7.3.0
Candidate multilib: .;@m64
Selected multilib: .;@m64
 "/home/clifford/installs/2019-04-19/llvm-gcc/bin/clang-9" -cc1 -triple x86_64-unknown-linux-gnu -fsyntax-only -disable-free -disable-llvm-verifier -discard-value-names -main-file-name completion.cpp -mrelocation-model static -mthread-model posix -mdisable-fp-elim -fmath-errno -masm-verbose -mconstructor-aliases -munwind-tables -fuse-init-array -target-cpu x86-64 -dwarf-column-info -debugger-tuning=gdb -v -resource-dir /home/clifford/installs/2019-04-19/llvm-gcc/lib/clang/9.0.0 -I /usr/include/c++/7 -I /usr/include/x86_64-linux-gnu/c++/7 -internal-isystem /usr/lib/gcc/x86_64-linux-gnu/7.3.0/../../../../include/c++/7.3.0 -internal-isystem /usr/lib/gcc/x86_64-linux-gnu/7.3.0/../../../../include/x86_64-linux-gnu/c++/7.3.0 -internal-isystem /usr/lib/gcc/x86_64-linux-gnu/7.3.0/../../../../include/x86_64-linux-gnu/c++/7.3.0 -internal-isystem /usr/lib/gcc/x86_64-linux-gnu/7.3.0/../../../../include/c++/7.3.0/backward -internal-isystem /usr/local/include -internal-isystem /home/clifford/installs/2019-04-19/llvm-gcc/lib/clang/9.0.0/include -internal-externc-isystem /usr/include/x86_64-linux-gnu -internal-externc-isystem /include -internal-externc-isystem /usr/include -fdeprecated-macro -fdebug-compilation-dir /home/clifford/projects/clang-test -ferror-limit 19 -fmessage-length 193 -fobjc-runtime=gcc -fcxx-exceptions -fexceptions -fdiagnostics-show-option -fcolor-diagnostics -code-completion-macros -code-completion-at=completion.cpp:5:16 -x c++ completion.cpp -faddrsig
clang -cc1 version 9.0.0 based upon LLVM 9.0.0svn default target x86_64-unknown-linux-gnu
ignoring nonexistent directory "/include"
ignoring duplicate directory "/usr/include/c++/7"
  as it is a non-system directory that duplicates a system directory
ignoring duplicate directory "/usr/include/x86_64-linux-gnu/c++/7"
  as it is a non-system directory that duplicates a system directory
ignoring duplicate directory "/usr/include/x86_64-linux-gnu/c++/7"
#include "..." search starts here:
#include <...> search starts here:
 /usr/include/c++/7
 /usr/include/x86_64-linux-gnu/c++/7
 /usr/lib/gcc/x86_64-linux-gnu/7.3.0/../../../../include/c++/7.3.0/backward
 /usr/local/include
 /home/clifford/installs/2019-04-19/llvm-gcc/lib/clang/9.0.0/include
 /usr/include/x86_64-linux-gnu
 /usr/include
End of search list.
```
You can coax clang into not including the standard c++ includes with the -nostdc++ flag, and then clang returns the results for which you were looking:

```
clifford@Ubuntu-Laptop:~/Documents/cpp-test$ clang -fsyntax-only -nostdinc++ -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -Xclang -code-completion-macros -x c++ -Xclang -code-completion-at=completion.cpp:6:16 completion.cpp
In file included from completion.cpp:1:
In file included from /usr/include/c++/7/ext/pool_allocator.h:48:
/usr/include/c++/7/bits/functexcept.h:79:20: warning: '__format__' attribute argument not supported: gnu_printf [-Wignored-attributes]
    __attribute__((__format__(__gnu_printf__, 1, 2)));
                   ^
COMPLETION: __cxx11 : __cxx11
COMPLETION: __pool_alloc : __pool_alloc<<#typename _Tp#>>
COMPLETION: __pool_alloc_base : __pool_alloc_base
1 warning generated.
```
And so you could alter company-clang-arguments to pass those same flags:

```
(push "-I/usr/include/c++/7" company-clang-arguments)
(push "-I/usr/include/x86_64-linux-gnu/c++/7" company-clang-arguments)
(push "-nostdinc++" company-clang-arguments)
```
And you get __gnu_cxx and __pool_allocator completions.

![Screenshot from 2019-04-26 12-33-26](https://user-images.githubusercontent.com/36324624/56835457-1febb680-6829-11e9-919f-f384f3a042fa.png)
![Screenshot from 2019-04-26 12-33-36](https://user-images.githubusercontent.com/36324624/56835471-2a0db500-6829-11e9-9ae6-db93e76adfdc.png)
 But you are stuck manually adding all of your header locations to the company-clang-arguments list.

**Comment by dgutov** [comment]
@cburn11 But if it already considers the necessary directory a system header path, why doesn't it suggest appropriate completions? Do you know?

**Comment by cburn11** [comment]
No I don't understand what the driver is doing internally. It does not treat the default included c++ standard library headers the same way. Altering completion.cpp, and asking for completions on stri:

```
#include <ext/pool_allocator.h>

#include <string>

int main(int argc, char * argv[]) {

  std::stri
  
  return 0;
}
```
produces correct results:

```
clifford@Ubuntu-Laptop:~/Documents/cpp-test$ clang -fsyntax-only -Xclang -code-completion-macros -x c++ -Xclang -code-completion-at=completion.cpp:7:11 completion.cpp
COMPLETION: streambuf : streambuf
COMPLETION: streamoff : streamoff
COMPLETION: streampos : streampos
COMPLETION: streamsize : streamsize
COMPLETION: string : string
COMPLETION: string_literals : string_literals
COMPLETION: stringbuf : stringbuf
COMPLETION: stringstream : stringstream
COMPLETION: strtod : [#double#]strtod(<#const char *__restrict __nptr#>, <#char **__restrict __endptr#>)
COMPLETION: strtof : [#float#]strtof(<#const char *__restrict __nptr#>, <#char **__restrict __endptr#>)
COMPLETION: strtol : [#long#]strtol(<#const char *__restrict __nptr#>, <#char **__restrict __endptr#>, <#int __base#>)
COMPLETION: strtold : [#long double#]strtold(<#const char *__restrict __nptr#>, <#char **__restrict __endptr#>)
COMPLETION: strtoll : [#long long#]strtoll(<#const char *__restrict __nptr#>, <#char **__restrict __endptr#>, <#int __base#>)
COMPLETION: strtoul : [#unsigned long#]strtoul(<#const char *__restrict __nptr#>, <#char **__restrict __endptr#>, <#int __base#>)
COMPLETION: strtoull : [#unsigned long long#]strtoull(<#const char *__restrict __nptr#>, <#char **__restrict __endptr#>, <#int __base#>)
```
But string is presumably brought in by the same `-internal-isystem /usr/include/c++/7` as ext/pool_allocator.h

**Comment by dgutov** [comment]
Is it because one is part of the standard and another is a GNU extension that needs an extra compiler flag, maybe?

**Comment by lzfgnu** [comment]
But why doesn't it complete bitmap_allocator and malloc_allocator, which are located in the same path as __pool_allocator.

**Comment by cburn11** [comment]
If bitmap_allocator.h is picked up by clang through `internal-isystem /usr/include/ext`, clang seems to ignore symbols in that header that start with a double underscore like namespace __detail, but still finds symbols like bitmap_allocator that don't start with double underscore.

If clang picks up bitmap_allocator.h through a regular `-I` it seems to be able to find the symbols starting with double underscore.

I wonder if there is a flag to the driver to modify that behavior?

**Comment by dgutov** [comment]
If you use such a symbol in a program (one that's "hidden"), does it compile and run?

**Comment by lzfgnu** [comment]
yes, it does

**Comment by dgutov** [comment]
17:39, April 27, 2019, linzf <notifications@github.com>:yes, it doesIn that case, it's probably a Clang bug.One thing to try is a newer version (I hear 8.0 is available). If it doesn't suggest the expected completions either, the second stop would be Clang mailing lists.

**Comment by lzfgnu** [comment]
> 17:39, April 27, 2019, linzf <notifications@github.com>:yes, it doesIn that case, it's probably a Clang bug.One thing to try is a newer version (I hear 8.0 is available). If it doesn't suggest the expected completions either, the second stop would be Clang mailing lists.

You are right, it's a clang bug！today I use vim with youcompleteme，it doesn' complete the __pool_allocator either.

**Comment by dgutov** [comment]
Then you're welcome to try Clang 8 and, if it's not fixed there, please submit a bug report.

You can also try one of the third-party backends that use Clang like https://github.com/Sarcasm/company-irony/.
