### ISSUE TITLE
Any way to show numbers on the left?

### ISSUE THREAD

**Issue by AmaiKinono** [company-mode/company-mode#889]
Having `M-<digit>` to select a candidate is nice, but when one of the candidates are too long, it's hard to find out which one corresponds to which number:

![2019-04-28-014054_693x190_scrot](https://user-images.githubusercontent.com/28714352/56853200-11032200-6957-11e9-8fb3-4b9e503c2a94.png)

But having them on the left would make it so convenient.

I looked into the code, and the position seems to be hardcoded? Could we have an option to decide which side should the numbers go?

**Comment by dgutov** [comment]
There is one now!
