### ISSUE TITLE
why these versions are not equal?

### ISSUE THREAD

**Issue by sjkyspa** [company-mode/company-mode#890]
https://github.com/company-mode/company-mode/blob/3eda0ba23921d43b733f7975e56d490a34b9f30b/company-clang.el#L287

https://github.com/company-mode/company-mode/blob/3eda0ba23921d43b733f7975e56d490a34b9f30b/company-clang.el#L270

**Comment by sjkyspa** [comment]
`(defun company-clang--check-version (min apple-min)
  (pcase company-clang--version
    (`(apple . ,ver) (>= ver apple-min))
    (`(normal . ,ver) (>= ver min))
    (_ (error "pcase-exhaustive is not in Emacs 24.3!"))))
`

the error occured for the clang command under version like 
`
Apple LLVM version 10.0.1 (clang-1001.0.46.4)
Target: x86_64-apple-darwin18.5.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
`

**Comment by dgutov** [comment]
What error?

And what does `(company-clang-version)` return on your machine?

The versions are not equal because Apple being Apple, it uses a different numbering scheme.

**Comment by sjkyspa** [comment]
@dgutov 
company-clang--version is a variable defined in ‘company-clang.el’.
Its value is (apple . 10.0)

the error is "pcase-exhaustive is not in Emacs 24.3!"

**Comment by dgutov** [comment]
Thank you. But I honestly don't undertstand what could be going wrong. `company-clang--check-version` should take its first branch, and that's it.

Are you looking up the value of `company-clang--version` in the source file's buffer?

**Comment by sjkyspa** [comment]
Thanks for you reply. But after reinstall all the packages the problem has gone.

**Comment by dgutov** [comment]
OK. That's good new anyway.
