### ISSUE TITLE
company-mu completion backend

### ISSUE THREAD

**Issue by nils-schween** [company-mode/company-mode#892]
Hi everyone,

four days ago the main mu4e developer djcb commited a major change concerning the completion of contacts, when writing an email with mu4e. In 2014 the company-mode community wrote an backend for mu4e contact completion.
Take a look a the following pull request 
https://github.com/company-mode/company-mode/pull/233 

This backend seems to rely on mu4e's function 
mu4e~sort-contacts-for-completion.

I believe this, because a look in my Emacs' *Messages* Buffer shows the following error message:

Company: backend company-capf error "Symbol’s function definition is void: mu4e~sort-contacts-for-completion" with args (candidates nil)

Unfortunately, djcb removed that function in the mentioned commit. But see for yourself
https://github.com/djcb/mu/commit/7563b89c9cda397d43dd3d8d985a677bb3c8495f

I am not sure, how to deal with this. Should someone remove company's backend for mu4e contact completion or should it be adapted? Deactivating company-mode completely in mu4e's compose mode, allows to test djcb's newly written completion framework for contacts. It works quite well.

What do you think?

Nils
P.S.: To reproduce the error, just pull the latest version of mu/mu4e, try to compose an email and fill in the "to field" of the email's header.

**Comment by dgutov** [comment]
There is no dedicated completion backend for `mu` in `company`.

Please `M-x toggle-debug-on-error`, reproduce the problem and post the resulting backtrace.

**Comment by nils-schween** [comment]
@dgutov Thanks for taking a loot at it.
Here is the required output:
`Debugger entered--Lisp error: (void-function mu4e~sort-contacts-for-completion)
  mu4e~sort-contacts-for-completion((#("Nils MySurname <nils.mysurname@myemailprovider.com>" 0 30 (font-lock-face completions-common-part) 30 31 (font-lock-face completions-first-difference))))
  company-capf(candidates "nils.mysurname@myemailprovider")
  apply(company-capf (candidates "nils.mysurname@myemailprovider"))
  company-call-backend-raw(candidates "nils.mysurname@myemailprovider")
  company--fetch-candidates("nils.mysurname@myemailprovider")
  company-calculate-candidates("nils.mysurname@myemailprovider" nil)
  company--begin-new()
  company--perform()
  company-auto-begin()
  company-idle-begin(#<buffer *draft*> #<window 3 on *draft*> 109 100)
  apply(company-idle-begin (#<buffer *draft*> #<window 3 on *draft*> 109 100))
  timer-event-handler([t 23771 58216 514321 nil company-idle-begin (#<buffer *draft*> #<window 3 on *draft*> 109 100) nil 700000])
  read-event(nil t 3)
  sit-for(3)
  flyspell-check-word-p()
  flyspell-post-command-hook()

`
I hope that this helps.
Nils

**Comment by dgutov** [comment]
It's a bug in mu. Seems to have been fixed 2 days ago: https://github.com/djcb/mu/commit/0d33e64dc9b7659603c27433e888c6318032ce82

**Comment by nils-schween** [comment]
@dgutov Very cool. I did a clean build of mu/mu4e and its working again. Thank you!
