### ISSUE TITLE
company-gtags can not complete function declaration tag

### ISSUE THREAD

**Issue by maobaoqi** [company-mode/company-mode#893]
Hi, I found a question when only using company-gtags to complete code.
For example, There is a head file under project folder, and run `gtags` command in this project folder.
![2019-05-15_23-58](https://user-images.githubusercontent.com/3353791/57790531-77938880-772a-11e9-9efc-7b3d221a4fe1.png)
After generate TAG files, create another cpp file and edit it. Then, `just_test()` can not be completed by company-gtags but `namedWindow()` and `fun1_testing()` can be completed. Cursor on `just_test()`, jumpping is right. So, How to solve this question? thanks!

**Comment by dgutov** [comment]
Does GNU Global support such declarations? I.e. includes them in the generated index?

**Comment by dgutov** [comment]
So apparently it doesn't:

```
$ global -c
HEAD_HPP
fun1_testing
namedWindow
```

Apparently they offer support on the mailing lists: https://www.gnu.org/software/global/maillist.html

**Comment by maobaoqi** [comment]
@dgutov thanks for your reply. I think GNU Global can index such declarations. use `global -s` can list the declarations and jumpping is right. But company can not complete it.

**Comment by dgutov** [comment]
> use global -s can list the declarations

Can you show a command that lists both declarations and definitions?

**Comment by dgutov** [comment]
> and jumpping is right

Using the ggtags package?

**Comment by dgutov** [comment]
Reopen with further info.
