### ISSUE TITLE
Need help finding by PR #873 is failing tests

### ISSUE THREAD

**Issue by rswgnu** [company-mode/company-mode#896]
Could someone familiar with company-mode internals look at this.  I would like to get this merged but need some added insight.  The changes to core company-mode are small but the error trace is complex.

See automated test failures for the pull request here:

https://github.com/company-mode/company-mode/pull/873

**Comment by dgutov** [comment]
Normally we check whether the backend is a group with

```
(or (symbolp backend)
                    (functionp backend))
```

but you're calling `(listp backend)`. Which gives a wrong result when backend is a lambda. Because an anonymous function is also a list (at least when not byte-compiled).

**Comment by rswgnu** [comment]
Thanks for the explanation.  I will make the update soon and see if that resolves it.
