### ISSUE TITLE
Feature request: annotate with backend used for completion

### ISSUE THREAD

**Issue by nverno** [company-mode/company-mode#897]
I think a useful debugging technique for quick feedback would be the ability
to set a debug flag so completion candidates were annotated with the
backend that was used to provide the completion.

This might well require a bunch of extra work or maybe there is already
a way to get similar feedback?  Something like how hippie-expand can 
give feedback on the current expansion function?

Anyway, if there is interest I would be happy to take a stab at it with a little
direction on where to start.

**Comment by dgutov** [comment]
The current backend is normally shown in the mode-line. Is that not enough for your purposes?

**Comment by nverno** [comment]
Oh wow, I had been `dimish`ing it so long I never noticed this feature. Yes, it is great, thankyou
