### ISSUE TITLE
company crashes in semantic-mode

### ISSUE THREAD

**Issue by LastStarDust** [company-mode/company-mode#899]
I have recently started using the company-mode for autocompletion in C/C++, but it is giving me a hard time because of continuous crashes. I have googled my issue and it seems somewhat related to issue #614 

The crashes seem to occur when semantic-mode is enabled and the cursor is on some string literal or comment section (not code). The most common case is when for example I initialize a string:
```cpp
std::string(" cursor_is_here ");
```
I have attached the section of my emacs configuration regarding auto-completion and jump-to-definition.

- [jojo_emacs_autocompletion.el.zip](https://github.com/company-mode/company-mode/files/3339171/jojo_emacs_autocompletion.el.zip)

Info:

- OS : Ubuntu 18.04 64 bit
- Emacs : GNU Emacs 26.2 (build 2, x86_64-pc-linux-gnu, GTK+ Version 3.22.30)
- Company : 20190430.1852 (melpa)
- Used backend: company-semantic
- Major mode: c++-mode

Backtrace: 
```lisp
Debugger entered--Lisp error: (error "Nothing to complete")
  signal(error ("Nothing to complete"))
  error("Nothing to complete")
  semantic-analyze-possible-completions(nil)
  semantic-analyze-completion-at-point-function()
  completion--capf-wrapper(semantic-analyze-completion-at-point-function optimist)
  run-hook-wrapped(completion--capf-wrapper semantic-analyze-completion-at-point-function optimist)
  company--capf-data-real()
  company--capf-data()
  company-capf(prefix)
  apply(company-capf prefix)
  company-call-backend-raw(prefix)
  apply(company-call-backend-raw prefix)
  company--force-sync(company-call-backend-raw (prefix) company-capf)
  company-call-backend(prefix)
  company--begin-new()
  company--perform()
  company-auto-begin()
  company-idle-begin(#<buffer wgEditXML.hpp> #<window 3 on wgEditXML.hpp> 2758 10438)
  apply(company-idle-begin (#<buffer wgEditXML.hpp> #<window 3 on wgEditXML.hpp> 2758 10438))
  timer-event-handler([t 23830 1531 104124 nil company-idle-begin (#<buffer wgEditXML.hpp> #<window 3 on wgEditXML.hpp> 2758 10438) nil 727000])
```

**Comment by dgutov** [comment]
Regarding the backtrace, I have nothing else to recommend other than `M-x report-emacs-bug`. Yes, apparently there are still problems with Semantic's CAPF support.

But aside from that: why does Info say "Used backend: company-semantic" if the backtrace mentions `company-capf` instead? You can try to make sure `company-semantic` is in `company-backends`, and hopefully it will work better for you.

**Comment by LastStarDust** [comment]
I found the used backend by issuing `company-diag`. `company-semantic` is correctly listed in the `company-backends` list, too.

**Comment by dgutov** [comment]
What does `company-diag` show at the exact position where you're experiencing the problem?

**Comment by LastStarDust** [comment]
Sorry, but I have no idea how to locate said position.

**Comment by dgutov** [comment]
When you see the error, it depends on the cursor's position.

**Comment by zzell** [comment]
@LastStarDust had same problem in C mode, fixed it with following code:
```elisp
(add-hook 'c-mode-hook
          (lambda() (setq-local company-backends
                                '(company-clang
                                  company-dabbrev-code
                                  company-keywords
                                  company-files
                                  company-dabbrev))))
```
Found solution [here](https://gist.github.com/atilaneves/f78918db2de53f2cf45d#file-init-el-L354)

**Comment by LastStarDust** [comment]
Thank you for the hint.

**Comment by LastStarDust** [comment]
I had already solved by completely disabling company-semantic.
