### ISSUE TITLE
Company Tooltip Align Annotation Doesn't Work?

### ISSUE THREAD

**Issue by ianpan870102** [company-mode/company-mode#900]
As titled, I failed to see the difference between `company-tooltip-align-annotation` set to `t` or `nil`, could someone please point me in the right direction? Cheers!

**Comment by mpereira** [comment]
Same.

**Comment by ianpan870102** [comment]
Oh actually I figured out the differences but forgot to close the issue.
@mpereira  Here are some examples to help you understand. In a nutshell, `company-tooltip-align-annotation` aligns the parameter hints etc. to the right-hand-side.

### With alignment:

![image](https://user-images.githubusercontent.com/36686900/82901527-a6c11480-9f90-11ea-8257-63a9ba4d2f28.png)

### Without alignment:

![image](https://user-images.githubusercontent.com/36686900/82901592-bd676b80-9f90-11ea-8ec6-29c23b85dade.png)

**Comment by ianpan870102** [comment]
My suggestion: set it to `t`, it's better-looking.

**Comment by mpereira** [comment]
Ah, I get it now. Thanks for letting me know @ianpan870102!

By the way, `company-tooltip-align-annotation` is missing an "s" at the end on your last comment. 🙂

Thanks again.

**Comment by ianpan870102** [comment]
My pleasure

> By the way, company-tooltip-align-annotation is missing an "s" at the end 

Good catch, fixed!
