### ISSUE TITLE
calling `candidates` twice when completion fails in some input cases

### ISSUE THREAD

**Issue by ouonline** [company-mode/company-mode#901]
Hi,

I am writing my own completion backend (link here: https://github.com/ouonline/emacs-company-ofc) and find that in some circumstances `candidates` is called twice. I tried to add some debug info in `company.el` and found some clues that may be helpful for this problems.

The following settings are related to `company-mode` in my `~/.emacs`：

```emacs
(require 'company)
(setq company-idle-delay 0.0)
(setq company-selection-wrap-around t)
(setq company-tooltip-align-annotations t)
(setq company-tooltip-flip-when-above t)

(add-to-list 'load-path "~/.emacs.d/company-ofc") ;; this is my backend
(setq company-backends '(company-ofc))

;; face settings are omitted

(add-hook 'prog-mode-hook (lambda () (company-mode)))
(add-hook 'nxml-mode-hook (lambda () (company-mode)))
```

### environments

debian unstable
emacs 26.2
company 20190430.1852 in melpa

### reproduction steps

invoke `emacs /path/to/company-ofc.el` in console and type `candtt` in a new blank line. `toggle-debug-on-error` is enabled to get debug messages.

### results

In `*Messages*` it shows

```
Loading /etc/emacs/site-start.d/00debian.el (source)...done
[yas] Prepared just-in-time loading of snippets successfully.
For information about GNU Emacs and the GNU system, type <f1> C-a.
Debug on Error enabled globally
in company--continue prefix -> candt
in company--continue prefix -> candtt
in company--begin-new prefix -> candtt
Entering debugger...
```

The three lines starting with `in company--` are debug messages added to `company.el` by me. I put an error message in `company--begin-new` in order to get the call stack.

In `*Backtrace*` the call stack is(function details are omitted)

```
company--begin-new
company--perform
company-auto-begin
company-idle-begin
timer-event-handler
```

It seems like that the first condition in `company--perform` in `company.el` triggers this problem

```emacs
(defun company--perform ()
  (or (and company-candidates (company--continue))
      (and (company--should-complete) (company--begin-new)))
  (if (not company-candidates)
      (setq company-backend nil)
    (setq company-point (point)
          company--point-max (point-max))
    (company-ensure-emulation-alist)
    (company-enable-overriding-keymap company-active-map)
    (company-call-frontends 'update)))
```

That's all I know about this problem.

Thanks.

**Comment by dgutov** [comment]
Hi!

Why put the error message in `company--begin-new`, and not in your `candidates` handler? I would be curious to see the full call stack.

**Comment by ouonline** [comment]
> Hi!
> 
> Why put the error message in `company--begin-new`, and not in your `candidates` handler? I would be curious to see the full call stack.

Hi,

After adding the debug meesge in my `candidates` I got the full call stack:

```
Debugger entered--Lisp error: (error #("backtrace with input -> candtt" 24 30 (fontified nil)))
  signal(error (#("backtrace with input -> candtt" 24 30 (fontified nil))))
  error("backtrace with input -> %s" #("candtt" 0 6 (fontified nil)))
  (progn (error "backtrace with input -> %s" input))
  (if (string= input "candtt") (progn (error "backtrace with input -> %s" input)))
  company-ofc-find-candidate(#("candtt" 0 6 (fontified nil)))
  (cond ((eql command (quote init)) (company-ofc-init)) ((eql command (quote prefix)) (company-ofc-grab-prefix company-ofc-token-pattern)) ((eql command (quote candidates)) (company-ofc-find-candidate arg)) ((e$
  company-ofc(candidates #("candtt" 0 6 (fontified nil)))
  apply(company-ofc (candidates #("candtt" 0 6 (fontified nil))))
  company-call-backend-raw(candidates #("candtt" 0 6 (fontified nil)))
  company--fetch-candidates(#("candtt" 0 6 (fontified nil)))
  company-calculate-candidates(#("candtt" 0 6 (fontified nil)) nil)
  company--continue()
  company--perform()
  company-post-command()
```

and after I press `c` in the `*Backtrace*` it shows

```
Debugger entered--Lisp error: (error #("Company: backend company-ofc error \"backtrace with input -> candtt\" with args (candidates candtt)" 60 66 (fontified nil)))
  signal(error (#("Company: backend company-ofc error \"backtrace with input -> candtt\" with args (candidates candtt)" 60 66 (fontified nil))))
  error("Company: backend %s error \"%s\" with args %s" company-ofc #("backtrace with input -> candtt" 24 30 (fontified nil)) (candidates #("candtt" 0 6 (fontified nil))))
  company-call-backend-raw(candidates #("candtt" 0 6 (fontified nil)))
  company--fetch-candidates(#("candtt" 0 6 (fontified nil)))
  company-calculate-candidates(#("candtt" 0 6 (fontified nil)) nil)
  company--continue()
  company--perform()
  company-post-command()
```

**Comment by dgutov** [comment]
Okay. And what exactly is the problem here?

**Comment by ouonline** [comment]
> Okay. And what exactly is the problem here?

My question is why `candidates` is called again with the same prefix after my `candidates` returning empty candidate list in the first call?

**Comment by ouonline** [comment]
> > Okay. And what exactly is the problem here?
> 
> My question is why `candidates` is called again with the same prefix after my `candidates` returning empty candidate list in the first call?

`candidates` is called twice with the same prefix (`candtt` in previous post). Both calls return an empty candidate list. I think `candidates` should be called exactly once for the same prefix.

**Comment by dgutov** [comment]
I see. That indeed feels suboptimal, but is it a problem in practice? E.g. is your completion function slow enough that it's noticeable? I think, in the case of "no completions", the first branch should finish very quickly.

Anyway, please try out this patch:

```diff
diff --git a/company.el b/company.el
index 2b92f85..f8af147 100644
--- a/company.el
+++ b/company.el
@@ -1618,8 +1618,11 @@ prefix match (same case) will be prioritized."
         (cl-return c)))))
 
 (defun company--perform ()
-  (or (and company-candidates (company--continue))
-      (and (company--should-complete) (company--begin-new)))
+  (cond
+   (company-candidates
+    (company--continue))
+   ((company--should-complete)
+    (company--begin-new)))
   (if (not company-candidates)
       (setq company-backend nil)
     (setq company-point (point)
```

**Comment by dgutov** [comment]
> My question is why candidates is called again with the same prefix

I'm guessing the previous author wrote it this way as a shorter version of this `cond`. Maybe there's a case which is not covered by it, but I'm failing to think of one.

**Comment by ouonline** [comment]
> I see. That indeed feels suboptimal, but is it a problem in practice? E.g. is your completion function slow enough that it's noticeable? I think, in the case of "no completions", the first branch should finish very quickly.

I tested this patch and `candidates` was called twice. I added extra messages in this patch

```emacs
(defun company--perform ()
  (cond
   (company-candidates
    (progn
      (message "case 1")
      (company--continue)))
   ((company--should-complete)
    (progn
      (message "case 2")
      (company--begin-new))))
```

and `*Message*` shows

```
case 2 [3 times]
in the first line of my find-candidate input -> can
case 2
in the first line of my find-candidate input -> cand
case 1
in the first line of my find-candidate input -> candt
case 1
in the first line of my find-candidate input -> candtt
case 2
in the first line of my find-candidate input -> candtt
```

This problem affects nothing in my daily use so far. But I wonder whether it would cause other misterious problems. And as a programmer I feel a little uncomfortable with this 'abnormal' behavior :)

Feel free to close this issue and thanks a lot for replying :)

**Comment by dgutov** [comment]
Sorry, I looked at it back in July, concluded it works as expected, but forgot to report back.

It goes like this:

* You typed `candtt`, it reaches the `company--continue` branch, call `candidates`, receives the empty list, cancels completion.
* Since the last action was also a normal command, `post-command-hook` comes into play. It calls `company-post-command` which schedules `company-idle-begin` to be called on a timer at this position. And when the time passes it calls `company--begin-new`, which also tries to find completions and fails.

We could try an guard specifically against this scenario (e.g. repurpose `company-point` for it), but it doesn't seem to actually hurt anyone, and I'm wary of side-effects.
