### ISSUE TITLE
Propertize annotation

### ISSUE THREAD

**Issue by knobo** [company-mode/company-mode#902]
Can I propertize annotations?

something like this?

``` lisp
(defun company-sass-include--annotation (candidate)
  (propertize (format "(%s)"
                      (get-text-property 0 'meta candidate))
              'face (get-css-color-face (get-text-property 0 'meta candidate))))
```

**Comment by knobo** [comment]
Maybe I could make a frontend that uses some functions from rainbow-mode to colorize annotations that looks like a color. Is that be possible?

**Comment by knobo** [comment]
I included the color in the minibuffer, but I'd like to be able to set the color in the meta annotation part of the compleation. 

So consider this a feature request.

![image](https://user-images.githubusercontent.com/89921/60984825-9eda9080-a33c-11e9-88b4-474913ecde36.png)

**Comment by dgutov** [comment]
It's not trivial, given than we the apply the annotation face with `font-lock-append-text-property` (see `company-fill-propertize`). You could try unsetting the foreground color on `company-tooltip-annotation-selection` and `company-tooltip-annotation` faces, and then propertizing the annotation strings with `face`. That will inevitably be brittle, though.

**Comment by dgutov** [comment]
> Maybe I could make a frontend that uses some functions from rainbow-mode to colorize annotations that looks like a color. Is that be possible?

A frontend is a whole visualization. For instance, the tooltip is a frontend. You can, of course, write your own (or copy and modify), but that's not something you could offer to other users, I think.

**Comment by knobo** [comment]
Having a custom function to propertize the annotation should be easy and useful to implement. I could even add properties that could take me to the source location of the completion and stuff like that.

**Comment by knobo** [comment]
Ah... location... I can actually specify that :)

**Comment by dgutov** [comment]
> Having a custom function to propertize the annotation should be easy and useful to implement.

Would you like to propose a patch? :)

**Comment by dgutov** [comment]
> location... I can actually specify that

Yup. And there is a key binding for it.

**Comment by jcs090218** [comment]
Is there any plan for this? Cuz I have an emacs package that fuzzy match all the candidates, it will be nice if I can propertize key characters. :(

**Comment by dgutov** [comment]
@jcs090218 To propertize fuzzy matching, you should implement the backend `match` command.

**Comment by knobo** [comment]
Could we just check if the text i already propertized, then don't add any properties if it is already any?

**Comment by dgutov** [comment]
This is likely to be incompatible with certain backends.

Second, what would it be propertized with? How do I trust that to be compatible with the popular color themes? And the default one especially.

**Comment by nverno** [comment]
Would it be possible to just append the company properties up to the start of the annotation if the annotation was propertized?

**Comment by knobo** [comment]
How about adding a property that would say inhibit-prioritization, or something like that?

**Comment by dgutov** [comment]
> Second, what would it be propertized with? How do we trust that to be compatible with the popular color themes? And the default one especially.

**Comment by knobo** [comment]
How does company-mode make it self compatible with the color themes?

**Comment by dgutov** [comment]
By using a set of well-known faces.

**Comment by knobo** [comment]
So the plugins should also then use well-known faces.

**Comment by Sarcasm** [comment]
Just a thought, but maybe it's not the annotation that should be propertized, but more allowing company to add some decorations (e.g. a color box with your CSS example) to a candidate.

Maybe a bit far-fetched, but this could be a icon-like decoration, see #756.
The icon here could be dynamically generated per candidate, and contain a colored square for example.

**Comment by dgutov** [comment]
Speaking of icons, how would that work on a HiDPI system?

(I'm admittedly biased on that issue.)

**Comment by dgutov** [comment]
To add to the above: I kind of like the idea, but the icons related functionality would have to be more advanced than we previously discussed. If someone would like to submit a concrete proposal, I'd certainly take a look.

**Comment by dgutov** [comment]
Getting back to the current issue, I think there's a semi-hidden feature that can help: the undocumented `pre-render` backend command. It was added in https://github.com/company-mode/company-mode/issues/437.

@knobo Let me know if it works for you, or you have any further questions.

**Comment by knobo** [comment]
yes it works :) 
![compl](https://user-images.githubusercontent.com/89921/89158670-bcdde900-d56e-11ea-9912-6f2549b1c01d.png)

**Comment by knobo** [comment]
But I was not able to set the background to white when the color is dark.

**Comment by dgutov** [comment]
Can you show me some code?

**Comment by knobo** [comment]
I'll clean up the code put it in a repo one day.

``` lisp
(defun company-sass-pre-render (str &optional annotation-p)
  "Prerender color."
  (let ((color (if (string-match "#[a-fA-F0-9]\\{3,6\\}" str)
                    (match-string 0 str))))
    (if color (propertize str
                          'face `((:foreground ,color)
                                  (:background
                                   ,(if (> 0.5 1 (rainbow-x-color-luminance color))
                                        "white" "black"))))
      str)))
```

**Comment by knobo** [comment]
oh... I see what happened there :o 
Bug in my code :( ` ,(if (> 0.5 1 ` that 1 should not be there

**Comment by knobo** [comment]
![image](https://user-images.githubusercontent.com/89921/89525092-f8ceb380-d7e5-11ea-834a-0f1b47c8b98e.png)
Maybe I'll make the background color the indicating color, and the foreground dependent on luminance.

**Comment by knobo** [comment]
![image](https://user-images.githubusercontent.com/89921/89525370-5c58e100-d7e6-11ea-9037-903e6bae00fb.png)

Thank you for your help :)

**Comment by dgutov** [comment]
Excellent!
