### ISSUE TITLE
Test `company-idle-begin-allows-async-candidates` failed on Emacs 27.

### ISSUE THREAD

**Issue by cireu** [company-mode/company-mode#906]
```
Selector: t
Passed:  123
Failed:  1 (1 unexpected)
Skipped: 1
Total:   125/125

Started at:   2019-08-10 12:16:20+0800
Finished.
Finished at:  2019-08-10 12:16:21+0800

.......................................................................F.....................s...............................

F company-idle-begin-allows-async-candidates
    (ert-test-failed
     ((should
       (equal
	'("abc" "abd")
	company-candidates))
      :form
      (equal
       ("abc" "abd")
       nil)
      :value nil :explanation
      (different-types
       ("abc" "abd")
       nil)))
```

**Comment by cireu** [comment]
@dgutov  After bisect, I find this commit in Emacs broke unit test

https://github.com/emacs-mirror/emacs/commit/f1e65b73ca20f72717d0b50fa5d983668a49bc38

**Comment by cireu** [comment]
I found running test interactively (load test files and `M-x ert-run-test-interactively`) can pass, but run it with `make test` will fail.

**Comment by dgutov** [comment]
Interesting. Thank you for the report.

**Comment by dgutov** [comment]
Apparently it only happens in a terminal, and only in certain terminals (doesn't happen with xterm, for example).

I've added a workaround now; might file a report against the core later.
