### ISSUE TITLE
Is it possible to show candidates through Ivy/Counsel?

### ISSUE THREAD

**Issue by mrbig033** [company-mode/company-mode#911]
### Runtime Environment

- OS: MX Linux 18.3
- [dotfiles](https://github.com/mrbig033/dotfiles)
- GNU Emacs 27.0.50
- Org mode version 9.2.3
- Evil version 1.2.14
- Company version: 0.9.10
- [~/.emacs.d](https://github.com/mrbig033/emacs.d)

### Issue

If this is not possible, I leave that as a suggestion as it would be quite useful. Thanks.

**Comment by clemera** [comment]
You can use `counsel-company` which comes with the `counsel` package.
