### ISSUE TITLE
Don't auto-select first candidate

### ISSUE THREAD

**Issue by jtherrmann** [company-mode/company-mode#913]
I am trying to achieve the following behavior:

- When the popup with the completion candidates first opens, no candidate is selected.
- When I run `company-select-next`, it selects the first candidate.
- This behavior should still apply when there is only one candidate available (so the popup opens with a single candidate, not yet selected).

This is to avoid accidentally triggering completion when attempting to insert a newline with `RET`.

This is similar to #246 and #430. I read the conversations on those issues, and it seems to me that the main takeaway points are:

1. This behavior would require significant modification to the `company` code because many places in the code assume that a candidate is selected.
2. It is suggested to either unbind `RET` so that it does not trigger completion, or to use `C-j` to insert a newline while the popup is active.

I am sympathetic to the first point, but I would like to revisit this issue because it is important to my workflow. I am not very happy with the suggestions described in the second point, and would like to see if there is a way to achieve the desired behavior.

If it is still not feasible to add this as an option to `company`, are there any suggested workarounds?

Thank you to whoever takes the time to respond to this :)

**Comment by dgutov** [comment]
Have you tried `company-tng`?

**Comment by jtherrmann** [comment]
Aha, that's pretty much exactly what I want. Thank you :)

**Comment by jtherrmann** [comment]
In case anyone still wants the behavior described in my post, without the automatic text insertion provided by `company-tng`, this is the workaround that I had implemented before learning about `company-tng`:

```elisp
(defvar jth-company-active nil
  "Represents whether the user has begun selecting candidates from the company-mode completions list.")

;;; The docs for company-completion-started-hook say that the hook is called
;;; with an argument that represents whether the completion was started
;;; manually.
(defun jth-company-deactivate (dummy)
  (setq jth-company-active nil))

(add-hook 'company-completion-started-hook 'jth-company-deactivate)

(defun jth-company-next ()
  (interactive)
  (if jth-company-active
      (command-execute 'company-select-next)
    (setq jth-company-active t)))

(defun jth-company-ret ()
  (interactive)
  (if jth-company-active
      (command-execute 'company-complete-selection)
    (command-execute 'company-abort)
    (command-execute (key-binding (kbd "RET")))))

(define-key company-active-map (kbd "C-n") 'jth-company-next)
(define-key company-active-map (kbd "C-p") 'company-select-previous)

(define-key company-active-map (kbd "RET") 'jth-company-ret)
```

It should be easy enough to set font faces where appropriate in order to make it appear that the first candidate is not selected until after the first call to `jth-company-next`.

But `company-tng` seems like an even better solution, so I'll try that for now.
