### ISSUE TITLE
deffered error when using company-mode

### ISSUE THREAD

**Issue by kirk86** [company-mode/company-mode#918]
Hi I was wondering if you could provide some insights regarding the following error 
![image](https://user-images.githubusercontent.com/2902390/66579642-09d27800-eb75-11e9-9da3-18e48ad36eeb.png)

I don't quite understand where it is coming from?

In addition I see some cluttering in my buffers coming from python `epc` I presume
![image](https://user-images.githubusercontent.com/2902390/66579747-34243580-eb75-11e9-9919-4226b3d9775d.png)

Is that necessary?

BTW my backend is company-jedi if that helps.

**Comment by dgutov** [comment]
> I don't quite understand where it is coming from?

From `company-jedi`, I suppose. Company itself doesn't use `deferred`.

**Comment by dgutov** [comment]
Same, I suppose.

**Comment by kirk86** [comment]
Seems to be a closed issue here https://github.com/syohex/emacs-company-jedi/issues/34 but I still get this error.
