### ISSUE TITLE
Cursor position off and flashing when completing first line

### ISSUE THREAD

**Issue by MatthewZMD** [company-mode/company-mode#919]
This issue only occurs on the first line. 

Here is the behavior gif:
![cursor](https://user-images.githubusercontent.com/12422335/66587826-34aed300-eb59-11e9-8922-45ae7c329e23.gif)

Due to this, sometimes when I type really fast, some things even go to the second line...

[Configurations](https://github.com/MatthewZMD/.emacs.d#company)
Version: GNU Emacs 27.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.8) of 2019-10-09

**Comment by MatthewZMD** [comment]
![secondline](https://user-images.githubusercontent.com/12422335/66588765-2a8dd400-eb5b-11e9-95f3-b95d9bca83a8.gif)

Here is a gif showing the text somehow went to the second line

**Comment by dgutov** [comment]
Any change you can give a minimal reproduction scenario starting with `emacs -Q -L ~/.emacs.d/elpa/company-xxx -l company`? Step by step.

From what I see, on the first gif you have some sort of git-commit buffer?

**Comment by MatthewZMD** [comment]
It is actually in a org-edit-special buffer

**Comment by dgutov** [comment]
Err, Org is notoriously heavy on the use of display-related text properties in the buffer.

Maybe you could report it to Org developers? They can see whether the problem could be fixed on their side. Or, if not, suggest an improvement to how the tooltip should be implemented.

In the meantime, you can try one of the replacements for the tooltip:

https://github.com/tumashu/company-posframe
https://github.com/sebastiencs/company-box

**Comment by MatthewZMD** [comment]
Hmmm, I've been using my workflow like this everything was working until a couple of days ago.

It could due to my upgrade of emacs-snapshot... maybe something new introduced broke this functionality.

Company-Posframe seems like a good alternative, but it doesn't work in terminal.. :(

Do you happen to know whether company-box works in the terminal as well?

**Comment by dgutov** [comment]
No, neither of them will work in the terminal.

> It could due to my upgrade of emacs-snapshot... maybe something new introduced broke this functionality

Or an update for Org? Either way, if that's the case, you might want to investigate which version created the problem. Then we might have a chance of fixing it promptly.
