### ISSUE TITLE
Fix disappearing line numbers during company-mode tooltip drop-down?

### ISSUE THREAD

**Issue by ianpan870102** [company-mode/company-mode#921]
I'm using display-line-numbers to show line numbers on the left-hand-side of my code (not just the one in my mode-line). However, whenever the company-mode autocomplete suggestion is activated (i.e. the tooltip drop-down), those line numbers of the lines that the tooltip covers will disappear, until the drop-down is gone. This results in a somehow flashy visual effect. How could I stop the line numbers from disappearing?

**Comment by dgutov** [comment]
Use `company-posframe` or `company-box`.

**Comment by amosbird** [comment]
unfortunately neither works in terminal emacs.

**Comment by ianpan870102** [comment]
Yes, I believe posframe is for gui only

**Comment by dgutov** [comment]
> unfortunately neither works in terminal emacs

At the moment the best I can suggest is your open an Emacs bug report asking for a popup library working in terminal.
