### ISSUE TITLE
Integration with company-capf 

### ISSUE THREAD

**Issue by Nidish96** [company-mode/company-mode#922]
I've added `company-capf` to `company-backends` in order to use the completion-at-point-functions in addition to `elpy-company-backend`. 

I have a use case where there are some completions that only `company-capf` knows and the elpy backend doesn't. In these cases, when I hit `company-complete`, I always get `No completion found`. However, when I type `company-capf`, I get my completion.

Any pointers as to where to start looking for the issue?

**Comment by dgutov** [comment]
`M-x company-diag` should help anyway.
