### ISSUE TITLE
Official guideline for other packages to add to `company-backends`

### ISSUE THREAD

**Issue by ilohmar** [company-mode/company-mode#923]
I seem to recall that, reading some docs or maybe code of the out-of-the-box backends, there once was a common understanding how backends should be written:
- they should check if they apply (in particular, to the current `major-mode`)
- they should thus work when simply adding them to a globally customized `company-backends`

Maybe that was just in my head, or maybe it has changed since, so here goes: what are other packages supposed to do if they want to enable their company backend in a certain major- or minor-mode?
[ There is no use debating whether they should change completion backends at all -- it's what "people" want, it seems :) ]

Several packages now set a buffer-local value of `company-backends`, either containing only their specific backend, or prepending it to the global value.

Are there any guidelines how to handle this?  I do have an opinion on that myself, but I am not willing to fight multiple uphill battles on these questions; surely not without some "official" backing...

**Comment by dgutov** [comment]
Could you give a couple of examples of "misbehaving" ones?

I'm only aware of the `company-go` instructions that recommend adding a buffer-local var. But there's no code to add it automatically.

**Comment by nverno** [comment]
`ess` sets a buffer-local value, the consensus there being the ordering of backends is important, so it is best not to pollute the global binding

**Comment by ilohmar** [comment]
@dgutov Here are those that do the buffer-local thing automatically:

I am working on some `eglot` PRs, and that changed (recently, I think) to set a buffer-local value containing only the `company-capf` backend.

`geiser-company` (part of the Geiser package for Scheme development) also makes the variable buffer-local and adds its own backend to it.

I am currently not aware of other ones, but will add info when coming across any.

But are you saying that my original impression is correct, that this is not how it's supposed to work?

**Comment by dgutov** [comment]
Okay then. To be clear, there are two preferred ways to integrate with Company.

* Use `completion-at-point-functions` and convey extra information through the `:company-*` additional properties like e.g. `elisp-completion-at-point` does. In this scenario some minor mode can and should call `add-hook`.

* Define a Company backend like described in Commentary at the top of `company.el` and in `company-backends` docstring. Then, in the documentation, describe how you recommend it to be used. Buffer-local values are allowed, but usually not necessary. Examples:

  https://github.com/tigersoldier/company-lsp#usage
  https://github.com/pythonic-emacs/company-anaconda#usage

**Comment by dgutov** [comment]
Speaking of Eglot, I think @joaotavora is going to undo that change soon.

**Comment by dgutov** [comment]
Speaking of Eglot, I think we came to a conclusion with @joaotavora that that change will be reverted.

If not, I'm open to addressing any remaining problems.

**Comment by ilohmar** [comment]
Thanks for the clarification.

**Comment by joaotavora** [comment]
> Speaking of Eglot, I think we came to a conclusion with @joaotavora that that change will be reverted.

I didn't revert it by I provided an opt-out, `eglot-stay-out-of`, that you can add `company` to.

**Comment by dgutov** [comment]
If I were to choose, I prefer an opt-in version, like a function `eglot-company-setup` that one could add to `eglot-mode-hook`. But then you'll need to clean up when Eglot session is shut down, too...

Is `company-clang` the only problem here that you've seen in practice?

**Comment by joaotavora** [comment]
> If I were to choose, I prefer an opt-in version, like a function eglot-company-setup that one could add to eglot-mode-hook. But then you'll need to clean up when Eglot session is shut down, too...

Would be easier to default `eglot-stay-out-of` to `(company)` in that case.  But I like the consistency.  Eglot does the same with Flymake, Imenu, Xref, Company, and pretty soon Yasnippet too.  As LSP servers get better and better all the bundled stuff that come with those 
libraries is going to become obsolete, at least for the duration of the Eglot session.

> Is company-clang the only problem here that you've seen in practice?

Yes. But there are others in front of `company-capf` right?

**Comment by dgutov** [comment]
Oh well.

> But there are others in front of company-capf right?

Right. And they're supposedly useful enough to be there in the default value. Still, we can consider removing `company-eclim` and `company-semantic` as well, with instructions on how to re-add them.

But by "same thing" to you mean that you override the value entirely? I'd imagine when there's just one hook variable for the corresponding feature, adding a local hook should be enough. The new element is added at the beginning of the list anyway.

**Comment by stardiviner** [comment]
This indeed a problem for some packages adding to `company-backends`. They sometimes add it globally caused some weird error on some major mode which does not belong to that backend. So I think this suggestion of adding a official guide is very necessary!

**Comment by dgutov** [comment]
When a package adds to the value globally, a major mode check in the prefix function is a must.

**Comment by stardiviner** [comment]
I found many packages has my previous mentioned situation. I searched my PR list about company backend.
- https://github.com/tonini/alchemist.el/pull/248
- https://github.com/joaotavora/sly-company/pull/3
- https://github.com/tonini/alchemist.el/pull/138
- https://github.com/holomorph/systemd-mode/pull/12

**Comment by dgutov** [comment]
Yes, it's a bit of a mess, unfortunately.

**Comment by joaotavora** [comment]
You can scratch sly-company from that list.  It's totally obsolete, unsupported, dead, joined the choir invisible, ceased to be: an ex-package.

**Comment by yugaego** [comment]
The requested official guidelines have now been published as a part of the [`Contributing` file](https://github.com/company-mode/company-mode/blob/master/CONTRIBUTING.md#guidelines-for-third-party-packages).

**Comment by dgutov** [comment]
And with that, the issue can be closed. Thanks all!
