### ISSUE TITLE
Race condition when company-completing quickly

### ISSUE THREAD

**Issue by joaotavora** [company-mode/company-mode#924]
Hi @dgutov, I've just fixed a bug in Eglot which might have been just working around a bug in Company.  This is the commit: https://github.com/joaotavora/eglot/commit/d5859b53bdef12f2c7cb8cb51b5e2223e609769f

I wrote the commit message as if I was reporting this bug, more or less.  Here it is:

"For some reason, probably related to the way that Eglot tries to maintain the responsiveness of Company completion tooltips (see below), the user's explicit input will sometimes be surprisingly deleted by Company, leading to a horrible completion experience.

This is sometimes hard to reproduce, but appears to match this description perfectly: https://github.com/joaotavora/eglot/issues/319#issuecomment-542955432

Fortunately, Company has a good fix for this, which is to pass `:company-require-match 'never` in the completion-at-point function.  This is the fix applied in this commit.

However, this line shouldn't be required since the default value for `company-require-match` is `company-explicit-action-p`, presumably meaning that the auto-deletion should never take place for characters typed by the user.

This points to a bug in Company, or at least something which may have been exacerbated by the way that Eglot aggressively fetches completions from the server by passing `:cancel-on-input t` to `jsonrpc-request`, discarding out-of-date replies.  Perhaps that discarding step bears with it some side-effects that make the `company-explicit-action-p` test return `nil` instead of the correct `t`.  Company interprets this as _carte blanche_ to delete the last inserted character."

**Comment by dgutov** [comment]
> Perhaps that discarding step bears with it some side-effects that make the company-explicit-action-p test return nil instead of the correct t

Only if it's in the reverse (*), but how?

(*) When `require-match` is on, and new input results in no matches, `company--continue-failed` can delete some of the latest input. But I'd really like to see a stable repro.

`company-explicit-action-p` simply checks the values of two variables, and they are only dependent on the commands invoked by the user. Meaning that if the user typed for example `TAB` or `M-n` or `M-p` during the current completion, input with no matches will indeed be deleted.

Maybe the way that "Eglot tries to maintain the responsiveness" can sometimes lead to it returning an empty list of completions unexpectedly sometimes? To simplify reproduction, you can set `company-require-match` to `t`.

**Comment by joaotavora** [comment]
> Only if it's in the reverse (*), but how?

I believed that when `company-explicit-action-p` returns `t` then delition is **not** performed, right?  Is typing a letter not an "explicit action"?

Anyway, maybe indeed I messed up the commit message, and there's no way to fix it :-/.  No biggie.

> Maybe the way that "Eglot tries to maintain the responsiveness" can sometimes lead to it returning an empty list of completions unexpectedly sometimes?

I believe it would be "always".  If the user types while the request is still ongoing, the `jsonpc-request` returns `nil` immediately (it can return another value, if you want, but Eglot uses the default, which is `nil`).

But the `nil` shouldn't have an effect because in the meantime a new character has been typed and company should theorically already be taking note of that, and moving on.  Which is appears to do, but not always.

> To simplify reproduction, you can set company-require-match to t.

Can a user that sets that override the `never` setting in my completion function? I hope not.  Otherwise, another variable to smash.

What is the purpose of this feature, btw, if you can explain it in 2 or 3 lines?

**Comment by dgutov** [comment]
> I believed that when company-explicit-action-p returns t then delition is not performed, right?

Not how it works.

> I believe it would be "always". If the user types while the request is still ongoing, the jsonpc-request returns nil immediately

That would indeed be a problem when "require match" mechanics is in effect. You try try and mitigate this to only return nil on use input when `non-essential` is t.

> But the nil shouldn't have an effect because in the meantime a new character has been typed and company should theorically already be taking note of that, and moving on.

In theory, maybe. But it would mean safeguarding the code to be compatible with wrapping it in `while-no-input`.

> What is the purpose of this feature, btw, if you can explain it in 2 or 3 lines?

It's to mimic an old IDE behavior. And maybe combo box behavior as well.

When you press `Ctrl-Space` to invoke the completion popup, and then mistype while trying to narrow down the matches. Any input that results in no matches doesn't get accepted.

**Comment by joaotavora** [comment]
> That would indeed be a problem when "require match" mechanics is in effect. You can try and mitigate this to only return nil on user input when non-essential is t.

Didn't know about `non-essential` the docstring is very confusing. So you are saying I should do this?

```
diff --git a/eglot.el b/eglot.el
index 9a0960d..0ff486d 100644
--- a/eglot.el
+++ b/eglot.el
@@ -1931,7 +1931,7 @@ is not active."
                                        :textDocument/completion
                                        (eglot--CompletionParams)
                                        :deferred :textDocument/completion
-                                       :cancel-on-input t))
+                                       :cancel-on-input non-essential))
                 (setq items (append
                              (if (vectorp resp) resp (plist-get resp :items))
                              nil))
```

Or should it be `(not non-essential)`?

And how would this fix things?

**Comment by dgutov** [comment]
> So you are saying I should do this?

I think so.

> And how would this fix things?

Before Company calls a backend, `non-essential` is bound to `(not (company-explicit-action-p))`. So it will cover the cases where input resulting in no matches would be automatically erased, at least unless `require-match` is set to `t`. Although the latter case can be handled inside Company, by binding `non-essential` to a slightly different value.

The downside here is that `M-x completion-at-point` won't benefit from your `cancel-on-input` because it doesn't binding `non-essential` to anything. But then, the benefits to it are minor anyway.

**Comment by joaotavora** [comment]
>    So you are saying I should do this?

> I think so.

Which version exactly?  I admit to be utterly confused with the double, triple negations of `non` and `not`. So, while I believe you, I also need to understand how this would work exactly. 

`non-essential` is true when something that is _essential_ is occurring, right?

And what exactly is a "Company explicit action"? Typing of a character is _not_ one, right?

 Let me ask you like this: under what conditions should I force the user to wait for the potentially slow `jsonrpc-request` to complete?

> The downside here is that M-x completion-at-point won't benefit from your cancel-on-input because it doesn't binding non-essential to anything. But then, the benefits to it are minor anyway.

Right.  This part I think I understand.  Actually, not even minor, I can't see _any_ benefit.  Quite the contrary: when `M-x completion-at-point` I don't want to `cancel-on-input`, I want to have to wait, or explicitly `C-g` myself out of it.

So apparently no downside to your strategy, except that I don't understand it fully.

**Comment by dgutov** [comment]
> Which version exactly?

The first one.

> non-essential is true when something that is essential is occurring, right?

No. That would be terrible naming.

> And what exactly is a "Company explicit action"?

Like I said: "the user pressed for example TAB or M-n or M-p during the current completion". In other words, performing any kind of explicit interaction with the popup. Simply typing doesn't count, of course.

> under what conditions should I force the user to wait for the potentially slow jsonrpc-request to complete?

See above. Or if the user typed `C-M-i`, which is also explicit intent to perform completion.

> when M-x completion-at-point I don't want to cancel-on-input, I want to have to wait, or explicitly C-g myself out of it

Great :-)

**Comment by joaotavora** [comment]
> No. That would be terrible naming.

OK, I see my mistake and the whole confusion. I misread the docstring. It states 

   "Whether the currently executing code is performing an essential task." 

IMO it should say 

  "Non-nil if currently executing code is not performing essential tasks". 

Then it says "This variable should be non-nil only when running code which should not disturb the user." I somehow read that as "not disturbed by the user".

**Comment by dgutov** [comment]
> OK, I see my mistake and the whole confusion

:+1: 

> IMO it should say

You can probably go and commit the improved docstring to master right away.

> I somehow read that as "not disturbed by the user".

TBH, I'm not sure what "code which is not disturbed by the user" might mean.

**Comment by joaotavora** [comment]
> TBH, I'm not sure what "code which is not disturbed by the user" might mean.

I'm not saying it makes sense, I said I read it like that.  But code that "should not be disturbed by the user" would make it _essential_ code.

**Comment by dgutov** [comment]
Oh. :ok:
