### ISSUE TITLE
Move faces to own defgroup

### ISSUE THREAD

**Issue by skangas** [company-mode/company-mode#927]
I suggest to move all faces to their own `defgroup` named something like company-faces. This in order to make `M-x customize-group RET company RET` less cluttered.

Thanks in advance.

**Comment by dgutov** [comment]
Is there a precedent for separation like this?

**Comment by skangas** [comment]
> Is there a precedent for separation like this?

Yes, see `M-x customize-group RET faces RET`.

**Comment by dgutov** [comment]
Thanks for the suggestion.

This should do it.
