### ISSUE TITLE
Configuration with buffer local variables

### ISSUE THREAD

**Issue by mpfeifer** [company-mode/company-mode#928]
Hi there,

i understood company configuration like this:

1. User defines global list of backends
2. in the context where point resides company picks first backend that returns a result and shows the proposed completions

If I am wrong here please dont hesitate to tell me... Otherwise I was wondering if it is not more efficient to have buffer local definition of company's current backends? Or what is the reason to do it with this global list?

Thanks

**Comment by dgutov** [comment]
Performance-wise, the difference is negligible. Having a global list is more transparent, to see the whole configuration at a glance.

As a user, though, you can set up buffer-local values yourself.

**Comment by clemera** [comment]
> As a user, though, you can set up buffer-local values yourself.

I want to configure local backends and want to fallback to the global ones if no completion is found by the local ones. Is the following the appropriate way to do that?

    (setq-local company-backends
                (append ....local-backends...
                        (default-value 'company-backends)))

**Comment by dgutov** [comment]
@clemera Pretty much, yes.

**Comment by clemera** [comment]
@dgutov Nice, thanks!
