### ISSUE TITLE
company-clang can't complete in orgsrc block (org 9.2.6)

### ISSUE THREAD

**Issue by Loutine** [company-mode/company-mode#929]
environment : 
system: archlinux
emas version: 26.2
org-mode version: 9.2.6
problem: 
I am using org-mode as my notebook to write some code examples,and using company-clang to complete c or cpp code, before I updated my org-mode it worked well in orgsrc block, but after I installed the org 9.2.6 it doesn't work any more(just in orgsrc) , it still works well in .c or .cpp file.

seems that the src block have no buffer-file-name so the company-clang can't get the data.

I 've changed some code of company-clang.el to add a temporary file name for src block and it works

here is my solution:

change this
```emacs-lisp
(defsubst company-clang--guess-pch-file (file)
  (let ((dir (directory-file-name (file-name-directory file))))
    (when (equal (file-name-nondirectory dir) "Classes")
      (setq dir (file-name-directory dir)))
    (car (directory-files dir t "\\([^.]h\\|[^h]\\).pch\\'" t))))
```
to this
```emacs-lisp
(defsubst company-clang--guess-pch-file (file)
  (let ((f-dir (file-name-directory file))
        )
    (if f-dir
        (let ((dir (directory-file-name f-dir)))
          (when (equal (file-name-nondirectory dir) "Classes")
            (setq dir (file-name-directory dir)))
          (car (directory-files dir t "\\([^.]h\\|[^h]\\).pch\\'" t)))
      (car (directory-files default-directory
                            t "\\([^.]h\\|[^h]\\).pch\\'" t))
      )))
```
and compile it 

then add this to my .emacs file
```emacs-lisp

(defun set-org-src-buffer-name ()
  (interactive)
  (cond
   ((equal major-mode 'c-mode)
    (setq buffer-file-name "temp.c"))
   ((equal major-mode 'c++-mode)
    (setq buffer-file-name "temp.cpp"))
   ))

(add-hook 'org-src-mode-hook 'set-org-src-buffer-name)
```

hope can add it to company-clang and perfect it. :smile:

**Comment by dgutov** [comment]
Hi!

Was there something in particular in the new Org release that made it break to begin with?

**Comment by Loutine** [comment]
It's strange that I haven't found the information about the problem in release note, but org9.2 really changed a lot.
Besides,the problem only appears when I am writting c or cpp in orgsrc, not only company-clang ,company-irony also has the same problem,company-jedi worked well for python. :thinking:

**Comment by dgutov** [comment]
Maybe you should start with a bug report for Org Mode.

Please keep me posted.
