### ISSUE TITLE
No completion found when company-styles is flex

### ISSUE THREAD

**Issue by manuel-uberti** [company-mode/company-mode#932]
Hi,

first of all thanks for `compay-mode`, such a great package.

I am having an issue with `company-mode`, but since it is related to the development version of Emacs feel free to close my ticket until things on Emacs trunk are more stable (or the next release is out).

This is the problem I have, running from `emacs -Q`:

- install CIDER
- install company
- <kbd>M-x global-company-mode</kbd>
- evaluate this code in `*scratch*`: `(setq completion-styles '(flex))`
- clone the related project and visit this file: https://github.com/manuel-uberti/boodle/blob/master/src/clj/boodle/utils.clj
- <kbd>C-c C-x j j</kbd>
- at line 10, type `(json/g`
- no completion popup is shown, so try <kbd>M-x company-complete-common</kbd>
- the message `No completion found` is shown in the echo area

This is the ouput of <kbd>M-x company-diag</kbd>:
```
Emacs 27.0.50 (x86_64-debian-linux-gnu) of 2019-11-19 on hathaway
Company 0.9.10

company-backends: (company-bbdb company-eclim company-semantic company-clang company-xcode company-cmake company-capf company-files
	      (company-dabbrev-code company-gtags company-etags company-keywords)
	      company-oddmuse company-dabbrev)

Used backend: (company-dabbrev-code company-gtags company-etags company-keywords)

Major mode: clojure-mode
Prefix: ""
Completions:
  "true"
  "json/parse-string"
  "slurp"
  ":body"
  "request"
  "request"
  "request-body->map"
  "defn"
  "Double/parseDouble"
  "s/replace"
  "empty?"
  "string?"
  "str->double"
  "defn"
  "record"
  "record"
  "assoc"
  "Double/parseDouble"
  "s/replace"
  "record"
  "assoc"
  "empty?"
  "string?"
  "record"
  "record"
  "record-str->double"
  "defn"
  "record"
  "record"
  "assoc"
  "Integer/parseInt"
  "s/replace"
  "record"
  "assoc"
  "empty?"
  "string?"
  "record"
  "record"
  "record-str->integer"
  "defn"
  "str->integer"
  "str->integer"
  "sequential?"
  "strs->integers"
  "defn"
  "Integer/parseInt"
  "empty?"
  "string?"
  "str->integer"
  "defn"
  "or-zero"
  "defn"
  "repl/pst"
  "with-err-str"
  "stacktrace"
  "defn"
  "body"
  "*err*"
  "binding"
  "java.io.StringWriter"
  "body"
  "with-err-str"
  "defmacro"
  "record"
  "assoc"
  "today"
  "to-local-date"
  "record"
  "record"
  "record-str->date"
  "defn"
  "jt/with-max-value"
  ":day-of-month"
  "jt/property"
  "jl/local-date"
  "last-day-of-month"
  "defn"
  "jt/with-min-value"
  ":day-of-month"
  "jt/property"
  "jl/local-date"
  "first-day-of-month"
  "defn"
  "date-str"
  "date-format"
  "jl/local-date"
  "date-str"
  "to-local-date"
  "defn"
  "jl/local-date"
  "format-date"
  "today-str"
  "defn"
  "jl/local-date"
  "today"
  "defn"
  "date"
  "date-format"
  "jf/format"
  "date"
  "format-date"
  "defn"
  "date-format"
  "json/g"
  "java-time.local"
  "java-time.format"
  "java-time.core"
  "clojure.string"
  "repl"
  "clojure.repl"
  "json"
  "cheshire.core"
  ":require"
  "boodle.utils"
```

Without changing `completion-styles`, everything works as expected from `emacs -Q`.

**Comment by dgutov** [comment]
Does `M-x completion-at-point` work fine with the same settings?

Did you call `company-diag` on the same position in the buffer? Because it shows that `company-capf` is not used.

**Comment by manuel-uberti** [comment]
- `completion-at-point` shows no candidates popup either, but results in a `No match` message
- this is the result of `company-diag` with point in the position where I called `completion-at-point`:
```
Emacs 27.0.50 (x86_64-debian-linux-gnu) of 2019-11-19 on hathaway
Company 0.9.10

company-backends: (company-bbdb company-eclim company-semantic company-clang company-xcode company-cmake company-capf company-files
	      (company-dabbrev-code company-gtags company-etags company-keywords)
	      company-oddmuse company-dabbrev)

Used backend: company-capf
Major mode: clojure-mode
Prefix: "json/"
Completions: none
```

**Comment by dgutov** [comment]
> completion-at-point shows nothing either, but results in a No match message

This points to a problem with CIDER, then. /Cc @bbatsov 

I don't have it installed currently, so it's hard for me to debug or give concrete suggestions.

**Comment by manuel-uberti** [comment]
Actually, following the tip [here](https://docs.cider.mx/cider/0.23/usage/code_completion.html), this fixes this problem since it sets its own value for `completion-styles`:

```emacs-lisp
(add-hook 'cider-repl-mode-hook #'cider-company-enable-fuzzy-completion)
(add-hook 'cider-mode-hook #'cider-company-enable-fuzzy-completion)
```

I'm closing this, I guess. :)
