### ISSUE TITLE
[company-clang] Add project-relative include directories

### ISSUE THREAD

**Issue by cyrus-and** [company-mode/company-mode#933]
I have a C++ project where I use some custom relative import directories:

```
CXXFLAGS := -Ifoo -Ibar -Ibaz
```

In order to make it work with Company, the only solution I've found so far is placing the following `.dir-locals.el` in the project root:

```el
((nil
  .
  ((eval
    .
    (let ((root (locate-dominating-file default-directory ".dir-locals.el")))
      (setq company-clang-arguments
            (list
             "-I" (expand-file-name "foo" root)
             "-I" (expand-file-name "bar" root)
             "-I" (expand-file-name "baz" root))))))))
```

Besides being incredibly ugly, it requires `eval` or anyway something that is not *safe* according to Emacs so every time I need to accept the prompt (adding an exception in `~/.emacs` is not an option).

So what would be the *classical* solution in such scenario?

**Comment by dgutov** [comment]
You can declare your own variable, mark it as safe, and set it to a list like `'("foo" "bar" "baz")` in the dir-locals file. And also add a hook to `c-mode-hook` in your init file that would change `company-clang-arguments` locally to a value formatted like this above.

**Comment by cyrus-and** [comment]
Thanks for the advice, but this is a quite common scenario, too common to require users to implement their own custom solution IMHO.

**Comment by cyrus-and** [comment]
Feel free to close this if it's a *wontfix*.

**Comment by dgutov** [comment]
It might be less than optimal, but do you have a counter-proposal?

This might be common, but it's also common for users to have to include directories outside of their project tree (extra library includes, and so on). So even we add a special var for project dirs in particular, will that really help a lot in the common case?

Additionally, there are some third-party projects that fill in this variable's value. Such as https://github.com/atilaneves/cmake-ide.

**Comment by cyrus-and** [comment]
I've switched to `lsp-mode` + `company-lsp` as `company-clang` is not usable due to the delay introduced by having to call the `clang` command every time.

Anyway, the problem is similar even in this new scenario, and the solution is that `clangd` supports [`compile_commands.json`][1] and in particular [`compile_flags.txt`][2], which is just a way to provide additional flags to `clang`. The only difference with respect to this issue is that `clang` is *invoked* using the same directory as `compile_flags.txt` thus allowing to avoid absolute paths which is the main concern here.

A possible solution could be make `company-clang` support [`compile_flags.txt`][2] (easy) and [`compile_commands.json`][1] (maybe harder). Obviously this could introduce security flaws if implemented poorly and might not be worth it.

[1]: https://releases.llvm.org/8.0.0/tools/clang/tools/extra/docs/clangd/Installation.html#compile-commands-json
[2]: https://releases.llvm.org/8.0.0/tools/clang/tools/extra/docs/clangd/Installation.html#compile-flags-txt

**Comment by cyrus-and** [comment]
Thanks! It now properly reads the `compile_flags.txt` file but `clang` is stil executed in the directory of the current file, so relative paths in `compile_flags.txt` won't work.

I guess the solution is to run `clang` from the directory where the `txt` file is located, but since the source file is passed via stdin (why is that though?) this would break the case where there is an `#include "sibling_file.h"` in the same directory of `current_file.c` as it will not be *automatically* found by `clang` no more.

**Comment by dgutov** [comment]
Indeed. But if the user creates `compile_flags.txt`, would they really prefer the latter over the former?

**Comment by cyrus-and** [comment]
No, I think both cases need to be fixed, putting absolute paths in `compile_flags.txt` to refer project-local files is useless as it will only work for *one* developer, i.e., the project cannot be moved.

Is there a reason why the source is passed file via stdin and not via command line?

**Comment by dgutov** [comment]
> I think both cases need to be fixed

How?

> Is there a reason why the source is passed file via stdin and not via command line?

Because the file contents are normally not saved to disk while the user is typing. But what would that change?

**Comment by cyrus-and** [comment]
> Because the file contents are normally not saved to disk while the user is typing.

Well, that a good reason.

> But what would that change?

Because given a `file.cpp` containing `#include "file.h"`, if you run `clang ... /path/to/file.cpp` from any directory it should be able to resolve `/path/to/file.h` even though there is no explicit `-I /path/to/`. But this is speculation according how *compiling* files usually work, I'm not sure if things change in this scenario...

> How?

A possible solution could be to run `clang` from the directory containing `compile_command.txt` AND add an additional `-I` flag with the directory containing the file passed via stdin.

**Comment by cyrus-and** [comment]
> Well, that a good reason.

Also apparently, `clang` requires that the source file is passed via stdin, it dies with the following if I try otherwise:

```
fatal error: cannot locate code-completion file <stdin>
```

**Comment by dgutov** [comment]
Hah, looks like recent Clang does require input from stdin. Earlier versions supported completion via filename as well (and initially Clang didn't support input from stdin at all).

> A possible solution could be to run clang from the directory containing compile_command.txt AND add an additional -I flag with the directory containing the file passed via stdin.

Good idea. Pushed.

**Comment by cyrus-and** [comment]
Sweet thank you, it works just fine!
