### ISSUE TITLE
Always call :exit-function with 'finished upon company-complete-selection

### ISSUE THREAD

**Issue by non-Jedi** [company-mode/company-mode#935]
This is the behavior from vanilla emacs completion. For example when completing `\div` with candidates:

- `\div`
- `\divideontimes`

if you `company-complete-selection` on `\div`, `:exit-function` will be called `'exact` rather than `'finished`.

Relevant docstring (`completion-extra-properties`):

```
‘:exit-function’: Function to run after completion is performed.

   The function must accept two arguments, STRING and STATUS.
   STRING is the text to which the field was completed, and
   STATUS indicates what kind of operation happened:
     ‘finished’ - text is now complete
     ‘sole’     - text cannot be further completed but
                  completion is not finished
     ‘exact’    - text is a valid completion but may be further
                  completed.
```

This came up in relation to https://github.com/JuliaEditorSupport/julia-emacs/pull/82 which uses `:exit-function` to replace the latex code with a unicode symbol when `:exit-function` is called with `'finished`.

In gif form:

company behavior:

![company-behavior](https://user-images.githubusercontent.com/17915621/69746060-77c90380-1111-11ea-9b4b-727a6f6e2111.gif)

vanilla emacs completion:

![vanilla-emacs-behavior](https://user-images.githubusercontent.com/17915621/69745695-ba3e1080-1110-11ea-8f52-d909edf1777c.gif)

**Comment by dgutov** [comment]
Wish I could do that, but if you look up the history of that code, #217 will pop up.

Simply reverting the corresponding change and always calling it with `finished` will make pcomplete always insert spaces again. See the end of `pcomplete-completions-at-point` for why/how that happens.

IDK, maybe the only way to solve this properly is to somehow make the completion process (and especially its finalization) closer to what `completion-at-point` does. Would that mean showing the popup again if there are more completions at the new position of point...? IDK. I'm not sure what the predicate would be, but it'll probably have something to do with "fields".

/Cc @monnier for maybe better ideas.

**Comment by monnier** [comment]
> IDK, maybe the only way to solve this properly is to somehow make the
> completion process (and especially its finalization) closer to what
> `completion-at-point` does. Would that mean showing the popup again if there
> are more completions at the new position of point...? IDK.  I'm not sure what
> the predicate would be, but it'll probably have something to do with
> "fields".

Right, I suspect that

    (= (car (completion-boundaries arg table nil ""))
       (length arg))

is a better solution than (eq (try-completion) t) (and it should also be more efficient).


        Stefan

**Comment by dgutov** [comment]
On 05.12.2019 5:22, monnier wrote:
>  > IDK, maybe the only way to solve this properly is to somehow make the
>  > completion process (and especially its finalization) closer to what
>  > `completion-at-point` does. Would that mean showing the popup again 
> if there
>  > are more completions at the new position of point...? IDK. I'm not 
> sure what
>  > the predicate would be, but it'll probably have something to do with
>  > "fields".
> 
> Right, I suspect that
> 
> (= (car (completion-boundaries arg table nil ""))
> (length arg))
> 
> is a better solution than (eq (try-completion) t) (and it should also be 
> more efficient).

Thank you, Stefan. That seems to work well.

Should completion--done do the same thing, maybe?

**Comment by dgutov** [comment]
OK, this is likely the best we can do. Ivy and others should probably adopt the same logic.

**Comment by non-Jedi** [comment]
This seems to work for my use-case. Thanks so much. :)

**Comment by monnier** [comment]
> Should completion--done do the same thing, maybe?

Hmm... I think we should in the following part (in minibuffer-force-complete)

        (completion--done (buffer-substring-no-properties start (point))
                          'finished (when done "Sole completion"))))

and the other place where we should do, we already do:

                       ;; If the completion introduces a new field, then
                       ;; completion is not finished.
                       (completion--done result
                                         (if (eq (car bounds) (length result))
                                             'exact 'finished)))))))

(i.e. in `completion-list-insert-choice-function`).


        Stefan
