### ISSUE TITLE
Can I get completion from specific files using other modes?

### ISSUE THREAD

**Issue by alienbogart** [company-mode/company-mode#936]
First of all thank you very much for this awesome project. 

Let's say I'm working on `index.html` using `web-mode` and on `style. css` using `css-mode`. If I create a class on `style. css`, would it be possible for it to be completed on the `index.html`? `(setq company-dabbrev-other-buffers 't)` only get completions from the same mode, and `(setq company-dabbrev-other-buffers 'all)` will get it from files in all modes, and that's not what I want. 

Maybe there's a way to have completions by project using something projectile?

**Comment by dgutov** [comment]
This sounds similar to https://github.com/company-mode/company-mode/issues/709, which is unresolved.

But you could around-advice `company-dabbrev-other-buffers` to bind `major-mode` to a different value depending on the context inside the file. That would require some coding.

**Comment by mrbig033** [comment]
> That would require some coding

Okay. I'm not really a programmer yet (I wish I could study Lisp, but right now I can only use Emacs to learn other languages...), so that's a bit complicated for me at the moment. But, if you can give a bit more details on how to achieve that, I'm great at recognizing patterns and following instructions.

Thanks, @dgutov!

**Comment by dgutov** [comment]
Around-advice is done with `advice-add`.

Temporary value binding is done with `let`.

As for how to figure out the exact language context at point... that would require some digging. Maybe `html-mode` has some function, though.

**Comment by rileyrg** [comment]
Just a little "beep" here. Any advances?  I had hoped company-lsp would work in an mhtml mode buffer but i doesn't despite html-ls chugging away in lsp-mode for mhtml.

**Comment by dgutov** [comment]
@rileyrg If `lsp-html` is working fine in mhtml, how could `company-lsp` not work?

If it's the case, please report that to https://github.com/tigersoldier/company-lsp/issues

**Comment by rileyrg** [comment]
Maybe I'm doing something wrong? Before I raise any issues maybe you could cast your eye here. I'm calling lsp mode for mxhtml buffers (triggered for my .html.twig file just fine). company-diag shows that only company-dabbrev is providing completions and that comes after company-lsp.  I have required lsp-html but it's unclear to me just how I should configure to actually modify or direct company-lsp further. As you can see here lsp is connected to htlm-ls

![Screenshot from 2019-12-30 23-08-53](https://user-images.githubusercontent.com/362891/71602594-684a3980-2b59-11ea-9b6f-57649ea0687e.png)


> 
> company-backends: (company-lsp company-capf company-files company-web-html
>              (company-dabbrev-code company-gtags company-keywords)
>              company-dabbrev)
> 
> Used backend: company-dabbrev
> Major mode: mhtml-mode
> Prefix: ""
> Completions:
>   "2018"
>   "TODO"
>   "from"

[https://github.com/rileyrg/Emacs-Customisations/blob/master/lisp/emacs-config.org](My Emacs Config)

**Comment by dgutov** [comment]
mxhtml? :confused: 

In any case, the answer is "I don't know". `lsp-html` and `company-lsp` are maintained by roughly the same people, so your best bet is to ask them.

**Comment by rileyrg** [comment]
Apologies. mhtml.

**Comment by dgutov** [comment]
Maybe the addition in https://github.com/company-mode/company-mode/pull/1485 can help.

It only allows finer-grained filtering by modes, though, not specific files.
