### ISSUE TITLE
About company-enable-overriding-keymap

### ISSUE THREAD

**Issue by tumashu** [company-mode/company-mode#938]
Is it possible change the function company-enable-overriding-keymap
like the below:

The reason is that I need change company-active-map in  company-posframe,
If have this function, I can add advice function to  replace `company-active-map' 
with `company-posframe-active-map', no need to edit company-active-map in
company-posframe package.

```
(defun company-enable-overriding-keymap (keymap)
  (company-uninstall-map)
  (setq company-my-keymap (symbol-value keymap)))

(company-enable-overriding-keymap 'company-active-map)

```

**Comment by dgutov** [comment]
You mean the advise would look at the keymap's symbol value and replace it if it's `company-active-map`?

**Comment by dgutov** [comment]
In any case, you could compare values (with `eq`) instead.

But why changing `company-active-map` is a problem? And, more importantly, why do you need to change it?

**Comment by tumashu** [comment]
company-posframe need override some key, for example: bind mouse to 'ignore, 
because posframe do not suppore mouse,

using (define-key company-active-map ) in company-posframe-mode not better then advice, for advice can disable

**Comment by tumashu** [comment]
```
In any case, you could compare values (with eq) instead.
```
good idea :-)

**Comment by tumashu** [comment]
wow, defsubst is a macro to defun, ompany-enable-overriding-keymap can be adviced, need not change it, thanks again.

**Comment by dgutov** [comment]
Ah, the question was about turning it into a defus, first of all?

That's easy.
