### ISSUE TITLE
company-gtags error on complete function with args in web-mode

### ISSUE THREAD

**Issue by bloodhero** [company-mode/company-mode#940]
1. major-mode: web-mode
2. global: 6.6.3
3. project: drupal website
4. company-mode version: 0.9.10

first, i follow [GNU Global setup for Drupal](https://www.drupal.org/node/2328747) generate the GTAGS file.

then i open one file in drupal project, and enable company-mode.

it can auto-complete functons.

but when i select function with args. it will move my cursor to beginning of the file, and report error :

`Company: backend (company-dabbrev-code company-gtags company-etags company-keywords) error "Invalid search bound (wrong side of point)" with args (post-completion variable_get)`

**Comment by dgutov** [comment]
Hi!

Does it happen with any Drupal project? Does it happen every time?

If you have a small example project I can try it with, that would help.

**Comment by bloodhero** [comment]
in my [drupal 7.69 ](https://www.drupal.org/project/drupal/releases/7.69)
1. generate GTAGS in drupal root dir follow [GNU Global setup for Drupal](https://www.drupal.org/node/2328747)

2. use emacs open any php file in drupal dir.

this happens twice in my home pc and work pc.

**Comment by dgutov** [comment]
Can't reproduce.

Does `M-x company-tags` followed by completion really lead to that error?

Try `M-x toggle-debug-on-error` to produce a usable stack trace.

**Comment by dgutov** [comment]
And, uh, quick question: how does this work if `web-mode` is not in `company-gtags-modes` by default?

What other custom settings are required to reproduce this?

**Comment by bloodhero** [comment]
> Try M-x toggle-debug-on-error to produce a usable stack trace.

i have done `M-x toggle-debug-on-error` , this is  stack trace.

`Debugger entered--Lisp error: (error "Invalid search bound (wrong side of point)")
  search-backward(">" 39204 t)
  company-template-c-like-templatify("($name, $default = NULL)")
  company-gtags(post-completion #("variable_get" 0 12 (meta "function variable_get($name, $default = NULL) {" location ("c:/Apache24/htdocs/includes/bootstrap.inc" . 1233) company-backend company-gtags)))
  apply(company-gtags post-completion #("variable_get" 0 12 (meta "function variable_get($name, $default = NULL) {" location ("c:/Apache24/htdocs/includes/bootstrap.inc" . 1233) company-backend company-gtags)))
  company--multi-backend-adapter((company-dabbrev-code company-gtags company-etags company-keywords) post-completion #("variable_get" 0 12 (meta "function variable_get($name, $default = NULL) {" location ("c:/Apache24/htdocs/includes/bootstrap.inc" . 1233) company-backend company-gtags)))
  apply(company--multi-backend-adapter (company-dabbrev-code company-gtags company-etags company-keywords) (post-completion #("variable_get" 0 12 (meta "function variable_get($name, $default = NULL) {" location ("c:/Apache24/htdocs/includes/bootstrap.inc" . 1233) company-backend company-gtags))))
  #[0 "\302	!\203`

i have nothing special in  custom settings , please check [ my own custom settings](https://github.com/bloodhero/.emacs.d)

> Does M-x company-tags followed by completion really lead to that error?

No, the error only happen when i select completion candidates which function name with args.

> how does this work if web-mode is not in company-gtags-modes by default?

i have add web-mode in variable company-gtags-modes , and same error produce.

what version global you use? i think this maybe the reason to produce the error

**Comment by nverno** [comment]
I wonder if this issue is related to https://github.com/ocaml/tuareg/issues/223.

What happens if you set 


    (defalias 'ggtags-fontify-code #'ignore)

**Comment by bloodhero** [comment]
i have debug my custom emacs setting, find that only in web-mode this error will happen, no matter Company-Gtags-Modes variable has a web-mode value.

in php-mode, company-gtags works well.

**Comment by bloodhero** [comment]
i put `(defalias 'ggtags-fontify-code #'ignore)` in my init.el,  same error.

**Comment by dgutov** [comment]
Still can't reproduce.

Not with company 0.9.10 and web-mode 16, nor with the latest versions.

The oldest version of Emacs I have at hand is 25.2, so please re-test with that. Or something newer.

**Comment by dgutov** [comment]
> i have nothing special in custom settings , please check my own custom settings

Sorry, I won't. If there's something in there that is required to reproduce the problem, please find it yourself.

You can start with `emacs -Q -L ~/.emacs.d/elpa/company-xxx -L ~/.emacs.d/elpa/web-mode-yyy -l company -l web-mode`.

**Comment by bloodhero** [comment]
i realize that my emacs version is too old. i will update it and give a try.

**Comment by bloodhero** [comment]
i comment all my custom setting, manually enable web-mode and company-mode with
`M-x web-mode` and `M-x company-mode`, and **try to complete function `variable_get($name, $default = NULL)`**, same error

```
company-call-backend-raw: Company: backend (company-dabbrev-code company-gtags company-etags company-keywords) error "Invalid search bound (wrong side of point)" with args (post-completion variable_get)
```

my emacs version is 26.3 now.

it seems like company-mode isn't compatible with web-mode.

**Comment by bloodhero** [comment]
in php-mode, all works well, maybe i should change to php-mode.

**Comment by dgutov** [comment]
I have tried reproducing with web-mode as well -- and couldn't. With different versions of Emacs, company and web-mode.

Try reinstalling company and web-mode first.

And if the problem is still there, please write a step-by-step scenario starting with `emacs -Q` and mention the versions of all components involved.
