### ISSUE TITLE
In C and C++ mode, locations of `*' and `&' are different between function declaration and completion candidates

### ISSUE THREAD

**Issue by nanuda** [company-mode/company-mode#942]
I'm using lsp and company-lsp.

Let' say I declare a function foo in header file likes below
`void foo(int* n);` // Note that the asterisk is on the type side

But the signature of foo function in completion candidates is like `void foo(int *n)`. Now asterisk is on the variable side. After I selected the candidate, inserted function is same as candidate signature.

I just want function declaration and inserted function to have same signature. Is there any way to solve this issue?

**Comment by dgutov** [comment]
This is a question for [company-lsp](https://github.com/tigersoldier/company-lsp/), not the general framework (which is this tracker is for).

I would imagine that this detail depends on the particular language server in use, but maybe the lsp-mode folks can give a recommendation for how this could be configured.
