### ISSUE TITLE
company-tng completes whole argument definition on completion with lsp-mode

### ISSUE THREAD

**Issue by Mallchad** [company-mode/company-mode#943]
I've noticed a strange behavior specific to using company and lsp (specifically in C++) where company inserts any arguments declared for a function exactly, with all commas, names and types are inserted into the buffer and adds a space after a full stop.
![image](https://user-images.githubusercontent.com/45771609/72624750-61843a80-393f-11ea-8317-77823117b929.png)
![image](https://user-images.githubusercontent.com/45771609/72624808-7c56af00-393f-11ea-848f-82a381885958.png)
Now, this isn't very useful to me because clearly I have to go back and edit, well, delete the parameter list if I do not want an error. I believe this likely has some fault in lsp-mode but I wondered what could be done on company side, all I want is in situations like this is a little workaround that doesn't have the extra space and stops at the end of the function name so I can fill in the function manually. Especially since normal company is fine and stops completion at the first bracket.
This is all the company configuration I have 
![image](https://user-images.githubusercontent.com/45771609/72625179-38b07500-3940-11ea-80fd-f19f51d33d0c.png)

**Comment by dgutov** [comment]
#881 has a related discussion.

Second, you should try disabling snippets in lsp-mode.

But AFAICS there are two variables that can affect this. `lsp-enable-snippet` and `company-lsp-enable-snippet`. Maybe set them both to nil.

@yyoncho Am I reading this right? Shouldn't there be only one variable?

**Comment by yyoncho** [comment]
> Second, you should try disabling snippets in lsp-mode.

As per our reddit discussion this is not enough since company-mode will not perform `post-completion`. In order to work we have to put lsp-mode in mode that it doesn't have to perform any post-completion.

@Mallchad can you open a feature request for that in lsp-mode? 

> But AFAICS there are two variables that can affect this. lsp-enable-snippet and company-lsp-enable-snippet. Maybe set them both to nil.

The lsp-enable-snippet is the flag to use, company-lsp-enable-snippet is no longer used. Also, ATM the maintainer of company-lsp is not active and we have troubles getting PRs merged - thus we started implementing capf backend which FTR is ready to be used.

**Comment by dgutov** [comment]
> As per our reddit discussion this is not enough since company-mode will not perform post-completion

Right, thank you for the reminder.

> In order to work we have to put lsp-mode in mode that it doesn't have to perform any post-completion.

Looking at all the previous discussions, it sounds like this isn't too easy to do? But it would solve the complete-common problem too.

> The lsp-enable-snippet is the flag to use, company-lsp-enable-snippet is no longer used.

OK.

> Also, ATM the maintainer of company-lsp is not active and we have troubles getting PRs merged - thus we started implementing capf backend which FTR is ready to be used.

I see. You could adopt it into the lsp-mode organization, though, couldn't you?

**Comment by dgutov** [comment]
Please try https://github.com/company-mode/company-mode/pull/946, you both.

**Comment by yyoncho** [comment]
> Looking at all the previous discussions, it sounds like this isn't too easy to do? But it would solve the complete-common problem too.

If memory serves me right it wasn't that hard - we have to implement what the VIM project(YCM?) was doing.

> I see. You could adopt it into the lsp-mode organization, though, couldn't you?

Not sure what is the way to do it - but either way having capf frontend makes lsp-mode self-contained and in the process, we fixed some outstanding issues (e. g. client-side caching was user-configurable, now it is by default, the prefix to match calculation was not correct).

**Comment by dgutov** [comment]
> If memory serves me right it wasn't that hard - we have to implement what the VIM project(YCM?) was doing.

We've been talking about it quite a long time ago without progress. I figured it must be hard, then.

> Not sure what is the way to do it

Fork it into the org, then talk to the MELPA guys about switching over the source.

> but either way having capf frontend makes lsp-mode self-contained and in the process, we fixed some outstanding issues (e. g. client-side caching was user-configurable, now it is by default, the prefix to match calculation was not correct).

...but if the CAPF version is all upsides and no downsides, indeed, there's no reason to do it. Aside from user confusion, I guess (does Spacemacs use company-lsp?).

**Comment by Mallchad** [comment]
@dgutov I just got a chance to try the pull request and it does indeed achieve the desired behavior, thank you. @yyoncho noted on the PR that it feels somewhat unnatural because the preview text does not line up with the inserted text. 
Additional notes, for some reason company-lsp shoves the whole popup completion box 1 character to right. I initially ignored this behavior it's natural and normal of other completion frameworks like Microsoft Visual Studio and helm-elisp.
![image](https://user-images.githubusercontent.com/45771609/73178227-bd517f00-4108-11ea-95a6-ccad3111d93c.png)
I now realize that this behavior is likely incorrect as in normal emacs lisp completion the popup lines up exactly.
![image](https://user-images.githubusercontent.com/45771609/73178314-e7a33c80-4108-11ea-818f-0527203b128f.png)
I believe (somehow) this was contributing or a part of to the initial problem where maybe the candidates were being read or written incorrectly to the candidate's list.
Additionally, I can replicate the indented behavior with normal company-clang, which I believe is built-in to company-mode and seems to be working when I disable lsp-mode without any prior modification.
![image](https://user-images.githubusercontent.com/45771609/73178554-66987500-4109-11ea-9518-8a8c12f2c2a3.png)
As you can see, again, the completion box lines up with the actual text.
Actually these three comparisons made me realize something that was off.
The argument list is colored differently when comparing company-lsp to company-clang. I'm sure this is the case when comparing company-lsp to other backends but I don't have time to check right now.
So I can only assume that at some point the argument list isn't being marked as post-completion, or a completion tooltip, or whatever the *green text* in the popup menu means is being read to or written incorrectly, most likely on the side of company-lsp, if not company-tng is manipulating or reading the candidates in a way it shouldn't.
People have mentioned issues like this for company-tng a fair few times so if the company-lsp maintainer is inactive I'm sure people who were looking for a solution would find a fork if it was mentioned in the Wiki/README of company-mode or company-lsp.

**Comment by yyoncho** [comment]
@dgutov 

> a long time ago without progress. I figured it must be hard, then.

My priority was implementing the capf.

> ...but if the CAPF version is all upsides and no downsides, indeed, there's no reason to do it. Aside from user confusion, I guess (does Spacemacs use company-lsp?).

capf is yet to be tested - other than that we havent completely sorted out the flex completion story.

**Comment by yyoncho** [comment]
@Mallchad The offset comes from clangd it sends the labels prefixed with " ". 

As a side note, vscode does not do the placement like emacs do but it moves the completion box with the cursor.

**Comment by dgutov** [comment]
> My priority was implementing the capf

:+1: 

> The offset comes from clangd it sends the labels prefixed with " "

Someone should probably send them a bug report.

> vscode does not do the placement like emacs do but it moves the completion box with the cursor

So does that "mask" the aforementioned behavior? Or maybe makes it "right"?

**Comment by dgutov** [comment]
@Mallchad 

So you see an improvement? It's good to hear.

If you press TAB to insert a completion, then type `(` (for example), the arglist is not inserted anymore?

Regarding colors, yes, the arglist is colored differently between `company-clang` and `company-lsp`, and it hints at the core of the problem (the LSP protocol doesn't allow clients to easily differentiate between the method name and the arguments list), and why `post-completion` is necessary with LSP clients. Or at least has been necessary so far. Let's hope Ivan has some success changing that.

**Comment by yyoncho** [comment]
> So does that "mask" the aforementioned behavior? Or maybe makes it "right"?

My wild guess is that it fixes something related to vscode but I haven't tested vscode client. Otherwise, it does not make sense at all.

**Comment by Mallchad** [comment]
I assume specific cases were not taken into out with Language Server Protocol since it's meant to be fairly universal. Maybe that's something we should take up directly, I don't think it's too much of an ask. If not I believe a work around could probably be reached somewhere in lsp-mode or company-lsp by manipulating the inputs taken directly from clangd.
 Actually, I'm curious if it will be any different with clss or cquery, I'll have to check it out when I get a chance but it might be helpful to known if it's specific to a language server or just the protocol itself.
If we still draw up a blank it might be worth checking out what others have said for VSCode, Atom, and Vim implimentations have mentioned any similar problems, or if problems have been fixed prior which unintentionally caused downstream issues.
