### ISSUE TITLE
Could company also give me the prefix when using the match command?

### ISSUE THREAD

**Issue by AmaiKinono** [company-mode/company-mode#948]
When using the match command, currently company gives me the candidate and asks for positions where prefix occurs in the candidate. I'm working on some non-prefix completion stuff and I found this awkward. What I can do is:

1. Create a function that receives two strings, and returns all the positions where string1 occurs in string2. When responsing on `match`, call this function with `(company-grab-symbol)` and the candidate.

2. Give the candidate some text property to store this data when preparing them, and just get it when responsing on `match`.

I don't know if 1 is the right thing to do (it calls `company-grab-symbol` when we should already have the prefix), and 2 is not elegant. I looked into the `match` command part of `company-capf` and it looks like magic (I know it can uses the faces, kinda like the second approach, but I didn't figure out what's the `:company-match` thing).

My thought is we should have both the prefix and candidate here. It's so unnatural we can only use the candidate.

**Comment by dgutov** [comment]
Number 2 is what we usually do, and I think it's fine.

But you can try the 1 approach by referencing the global variable `company-prefix`. It's unlikely to go away in the near future.

**Comment by dgutov** [comment]
`company-capf` indeed uses the second approach. The faces are pre-computed on candidate strings.

**Comment by AmaiKinono** [comment]
Thanks for reply. Now I see the common practice, so I'll close the issue.
