### ISSUE TITLE
company-pseudo-tooltip-hide-temporarily breaks font-lock/theme colours

### ISSUE THREAD

**Issue by thatismatt** [company-mode/company-mode#950]
When there is only one completion left the tooltip is hidden and the single completion appears inline, for me this causes the following 10 lines of the screen to loose all their font-locking colours.

e.g. in an elisp buffer type `eval-` wait for the company tooltip to appear. I only have one completion that starts with `eval-b`, so typing `b` closes the tooltip, at this point all the font locking colours disappear, i.e. text is just white on black. Tabbing to complete using the single suggestion causes the font locking colours to return.

Investigating the code a little I found `company-pseudo-tooltip-hide-temporarily` and `company-pseudo-tooltip-hide`, and noticed that I can get the issue to go away by changing the definition of `company-pseudo-tooltip-hide-temporarily` to:

```lisp
(defun company-pseudo-tooltip-hide-temporarily ()
  (company-pseudo-tooltip-hide))
```

I don't expect that this is the correct solution to the problem, but I thought it might be useful in diagnosing the cause of the issue.

I've managed to reproduce this issue in Emacs snapshot (28.0.50) & Emacs 25.3.1.

(BTW thanks for a great library!)

**Comment by dgutov** [comment]
Ohh, not sure how I managed to miss that.

Thank you for the report, should be fixed now.

**Comment by thatismatt** [comment]
Awesome, that's fixed it for me :grin: thank you.
