### ISSUE TITLE
Error running timer using company-mode

### ISSUE THREAD

**Issue by avatar-lavventura** [company-mode/company-mode#953]
I am trying to use `company-mode`. => `(add-hook 'after-init-hook 'global-company-mode)`

I am having the following error:

```
Error running timer ‘company-idle-begin’: (wrong-number-of-arguments (lambda (when company-fci-mode-on-p (fc\
i-mode 1)) nil) 1)
```

**[Q]** What may be the reason for this error, is there any way to fix it?

**Comment by dgutov** [comment]
You have an extra hook somewhere, one that uses `company-fci-mode-on-p`. Which is not defined in this package.

**Comment by avatar-lavventura** [comment]
I think one of the following hook in my `.emacs` file was causing this issue:

```
(add-hook 'company-completion-started-hook 'company-turn-off-fci)
(add-hook 'company-completion-finished-hook 'company-maybe-turn-on-fci)
(add-hook 'company-completion-cancelled-hook 'company-maybe-turn-on-fci)
```

**Comment by dgutov** [comment]
One of these functions doesn't accept any arguments?

**Comment by avatar-lavventura** [comment]
When I commented them out, the error I am getting is gone
