### ISSUE TITLE
company-bbdb is not supporting From:

### ISSUE THREAD

**Issue by OGAWAHirofumi** [company-mode/company-mode#957]
Current company-bbdb is not supporting From: and Reply-To: etc.
The following diff, works for me.
[removed redundat " *", and make sure case-fold-search is t]

```diff
--- company-bbdb.el.orig	2020-02-07 15:36:23.963820703 +0900
+++ company-bbdb.el	2020-02-25 17:08:02.084513385 +0900
@@ -50,8 +50,10 @@
     (interactive (company-begin-backend 'company-bbdb))
     (prefix (and (memq major-mode company-bbdb-modes)
                  (featurep 'bbdb-com)
-                 (looking-back "^\\(To\\|Cc\\|Bcc\\): *.*? *\\([^,;]*\\)"
-                               (line-beginning-position))
+                 (let ((case-fold-search t))
+                   (looking-back
+                    "^\\([^ :]*-\\)?\\(To\\|B?Cc\\|From\\):.*? *\\([^,;]*\\)"
+                    (line-beginning-position)))
                  (match-string-no-properties 2)))
     (candidates (company-bbdb--candidates arg))
     (sorted t)
```

**Comment by dgutov** [comment]
Thank you.

Do you want to submit a PR? That would be a tad easier to merge.

**Comment by yurikoif** [comment]
Hi, I just encountered a bug right after installing this recent update.
When I was typing a slash /, it somehow triggered file name completion.
I do not know if they are indeed relevant though. Can you take a look?

**Comment by dgutov** [comment]
@yurikoif In a message buffer?

**Comment by yurikoif** [comment]
> @yurikoif In a message buffer?

Thanks for your fast reply and sorry for being this late. The bug seems to be fixed in some later version so all is good now!
