### ISSUE TITLE
How to contribute a new backend?

### ISSUE THREAD

**Issue by c-alpha** [company-mode/company-mode#959]
Hi, I've requested (and received) the copyright assignment form via the `emacs-devel` mailing list. I'll mention `company-mode` as well, and sign the assignment agreement once I've received it.

What next after that?

Make a PR here? Or propose it in an email to the `emacs-devel` mailing list (it's a small file, so could well attach it to the mail)?

Any hints appreciated.

**Comment by dgutov** [comment]
Hi!

Either way is fine.

However, if it's a niche backend (not one that would the majority of company-mode users would use), maybe the best way to publish it is a separate package, going through MELPA. Or GNU ELPA.

What kind of backend is it?

> I'll mention company-mode as well, and sign the assignment agreement once I've received it.

Putting 'emacs' as the program name for the assignment should suffice.

**Comment by c-alpha** [comment]
> [...]
> However, if it's a niche backend (not one that would the majority of company-mode users would use), maybe the best way to publish it is a separate package, going through MELPA. Or GNU ELPA.
> 
> What kind of backend is it?
> [...]

It is for [EUDC](https://www.gnu.org/software/emacs/manual/html_mono/eudc.html), he Emacs Unified Directory Client, a common interface to directory servers and contact information. This will allow email addresses coming from LDAP servers to be offered for completion in relevant headers in message buffers.

**Comment by dgutov** [comment]
Sounds a bit niche to me.

But other than that, wouldn't you prefer to have this completion also supported by `M-x completion-at-point`? If Emacs has some EUDC support already, this might fit better as a patch for `message.el`. See `message-completion-alist` and so on.

To go this route, you might want to ask further questions on emacs-devel. Alternatively, to publish this backend as-is as a separate package on GNU ELPA, an email to emacs-devel should work as well.

**Comment by c-alpha** [comment]
> Sounds a bit niche to me.

EUDC is part of core Emacs. Depends how you gauge "niche" then...

> But other than that, wouldn't you prefer to have this completion also supported by `M-x completion-at-point`? If Emacs has some EUDC support already, this might fit better as a patch for `message.el`. See `message-completion-alist` and so on.
> [...]

I presume the same points would equally apply to BBDB (but for which there is a `company-mode` backend, and one for `helm`, too)?

Strictly speaking, no other integrations would be needed, as EUDC provides a `eudc-expand-inline` function. Bind that to a key chord (e.g. `C-c TAB`) and you're done. When there's more than one candidate, it displays a list, and lets you choose one with arrows & enter. Similar applies for `bbdb-complete-name`, and any other completion system, btw.

But that means I will have to remember & use different key chords, depending on where I want the completion to come from, and the UI will be different in each case. So IMHO there is still an added value in aggregating candidates from different sources under the `company-mode` UI. That way, I can have a uniform completion interface and UX across all my Emacs work. I would speculate that thoughts along similar lines once upon a time made the case for including a BBDB backend? Needless to mention that I personally certainly prefer the `company-mode` UX over all the other options.

From a maintainer's viewpoint, the unique added value of EUDC is that it gives access to contacts information from LDAP servers, i.e. greatly helps Emacs users in corporate environments.

As EUDC is part of core Emacs, and touts itself as "the Emacs Unified Directory Client, a common interface to directory servers and contact information", and ships with a BBDB backend, a further thought could be that EUDC could perhaps become (at some point in the future) the one & only source for contacts information for any completion system?

**Comment by c-alpha** [comment]
> [...]
> But that means I will have to remember & use different key chords, depending on where I want the completion to come from, and the UI will be different in each case. So IMHO there is still an added value in aggregating candidates from different sources under the `company-mode` UI. That way, I can have a uniform completion interface and UX across all my Emacs work. I would speculate that thoughts along similar lines once upon a time made the case for including a BBDB backend? Needless to mention that I personally certainly prefer the `company-mode` UX over all the other options.
> [...]

Ok, maybe I missed your point about `completion-at-point`, with which you might have been thinking of `company`'s CAPF backend?

That however still leaves the question why there is a BBDB backend. BBDB could offer completions via `completion-at-point`, too.

**Comment by dgutov** [comment]
> EUDC is part of core Emacs. Depends how you gauge "niche" then...

Just instinct. And yes, IMO Emacs historically contains a number of "niche" packages.

> I presume the same points would equally apply to BBDB (but for which there is a company-mode backend, and one for helm, too)?

Yes. If I was making that decision now, I would also ask the submitter to create a `completion-at-point` function instead. If it's a good fit, of course. People are welcome to do that, and when that happens I'd happily remove that backend.

> Ok, maybe I missed your point about completion-at-point, with which you might have been thinking of company's CAPF backend?

Yes, that's right. If you hook into `completion-at-point-functions`, `company-capf` will use it. That's the main idea.

**Comment by c-alpha** [comment]
Thanks for sharing your thoughts. I'll meditate over this and see whether or how to proceed.

**Comment by alexmurray** [comment]
@c-alpha did you ever get anywhere with a `completion-at-point` or company-backend for eudc? This would be a great addition IMO.

**Comment by c-alpha** [comment]
> @c-alpha did you ever get anywhere with a `completion-at-point` or company-backend for eudc? This would be a great addition IMO.

Well, I have it working, basically. It is not implemented via `completion-at-point`, but as a "regular" company back-end. It was almost done when the discussion above started, so I frankly didn't bother to re-write it for `completion-at-point`.

Since EUDC queries may take a couple of seconds to complete (remote servers and stuff; of course depending on which and how many servers you have configured), I have added two set-up functions. The first one registers it as a normal company back-end, so EUDC will be consulted in any message-ish completion context. This is for when your EUDC set-up returns results fast.

```elisp
(require 'company-eudc)
(company-eudc-activate-autocomplete)
```

The second one is intended for binding it to a key-chord. This is for when your EUDC set-up may result in multi-second queries. In such a set-up, you will probably not want it to kick in unless invoked explicitly.

```elisp
(require 'company-eudc)
(with-eval-after-load \"message\"
  (define-key message-mode-map (kbd "<C-tab>") 'company-eudc-expand-inline))
```

**Comment by dgutov** [comment]
@c-alpha Did you ever publish it anywhere?

**Comment by c-alpha** [comment]
> @c-alpha Did you ever publish it anywhere?

Um, no; it’s just sitting in my `experimental-packages` folder and gets loaded on startup. Frankly, after your initial comments it didn’t seem likely to be adopted, so I just kept it my personal setup. If there’s interest, I’ll be happy to make a PR still.

**Comment by alexmurray** [comment]
I'm definitely interested fwiw 😁 and would love it if you could send a PR.

**Comment by dgutov** [comment]
...to MELPA, for example.

**Comment by dgutov** [comment]
Or GNU ELPA, if you don't mind the copyright assignment thing.

**Comment by c-alpha** [comment]
I have signed the copyright assignment with FSF for my other contributions to Emacs already. So no worries about licensing status, and all options available on that front.

Ok, here's my proposal: I'll make a PR here so you can see what we're talking about. If the consensus should be to merge the PR, fine. If the consensus should be otherwise, (M)ELPA can still be a way to get it published.

Sounds like a plan?

**Comment by alexmurray** [comment]
FWIW I would love to see this code to play with it myself so that sounds fine to me (as an outside observer) :smile:

**Comment by dgutov** [comment]
> Ok, here's my proposal: I'll make a PR here so you can see what we're talking about. If the consensus should be to merge the PR, fine. If the consensus should be otherwise, (M)ELPA can still be a way to get it published.

No objection from me.

**Comment by c-alpha** [comment]
PR is #997
