### ISSUE TITLE
Request for company-avy

### ISSUE THREAD

**Issue by WhatDothLife** [company-mode/company-mode#960]
Since there is a candidate selection in ivy called `ivy-avy` that makes use of the well-known package [avy](https://github.com/abo-abo/avy), it would be great to see this being implemented for company as well. E.g. pressing `C-a` would index all the possible candidates that are shown. You then simply press the corresponding key to select it, instead of using your arrows keys to navigate there.

This is what `ivy-avy` looks like:
![ivy-avy](https://user-images.githubusercontent.com/33008303/76012182-2604f600-5f16-11ea-8c95-4cfe75977e60.png)

**Comment by dgutov** [comment]
You are welcome to do it and publish as a new package.

I'm unlikely to use it myself, so there's little change I will have time to keep it up-to-date, even.

Let me know if you have any questions regarding how to start.

**Comment by WhatDothLife** [comment]
Thank you for your offer. I'll consider it, if I decide to do it myself.

**Comment by WhatDothLife** [comment]
To implement it I need to iterate over all shown candidates of the current overlay. How'd you implement this?

**Comment by dgutov** [comment]
You mean all completions? It's stored in the variable `company-candidates`.

How to display it, is a different question.

**Comment by WhatDothLife** [comment]
Do you mind if we switch to another medium? E.g. IRC, Reddit, or whatever you prefer.

**Comment by dgutov** [comment]
I don't really use IRC. Reddit, meaning direct messages?

Personally, I prefer this one. Whatever questions you might have, the answers could help someone else reading it.

**Comment by WhatDothLife** [comment]
> Personally, I prefer this one. Whatever questions you might have, the answers could help someone else reading it.

Fine, so I just realized that there is already a somehow similar feature implemented that can be used by enabling `company-show-numbers`. While this allows to choose one the first ten candidates, I want to iterate over **all visible** candidates to index them. By visible I mean the candidates shown in the completion overlay.

> You mean all completions? It's stored in the variable company-candidates.

So this does not help.

**Comment by dgutov** [comment]
Also see `company-tooltip-offset`.

**Comment by yugaego** [comment]
For reference: quick-access functionality (which used to be enabled by now obsolete `company-show-numbers` variable) was discussed in Issue #188. In that discussion, `a-la avy` behavior was considered alongside the alternatives too.
