### ISSUE TITLE
company-backends settings

### ISSUE THREAD

**Issue by taigacute** [company-mode/company-mode#961]
Hi a vimmer new come to emacs.  have a question , i want set the `company-cap :with company-yasnippet`  but got `:with` function init error,so how  can i set it.

```elisp
(load-package company
  :commands company-complete-common company-manual-begin company-grab-line
  :after-call pre-command-hook after-find-file
  :init
  (setq company-tooltip-align-annotations t
        company-tooltip-limit 14
        company-idle-delay 0
        company-echo-delay (if (display-graphic-p) nil 0)
        company-minimum-prefix-length 2
        company-require-match 'never
        company-dabbrev-ignore-case nil
        company-dabbrev-downcase nil
        company-global-modes '(not erc-mode message-mode help-mode gud-mode eshell-mode shell-mode)
        company-backends '(company-capf :with company-yasnippet)
        company-frontends '(company-pseudo-tooltip-frontend
                            company-echo-metadata-frontend))
  :config
  (add-hook 'company-mode-hook #'evil-normalize-keymaps)
  (global-company-mode +1))
```

**Comment by dgutov** [comment]
As you probably found out, you needed to wrap the value into extra parens. Because `:with` is only valid inside a grouped backend.

**Comment by taigacute** [comment]
@dgutov thanks for your reply. i just come from vim .some problems.I hope to have a similar experience with vim。
I set this on `:config`  `(setq company-backends '((company-capf company-yasnippet)))` company-yasnippet doesnt work. but i write this
 ` (push '(company-capf company-yasnippet) company-backends)` on `go-mode-hook`  by lambda it works. dont know why.

another question, i found the company-yasnippet will set all snippet to company even `company-capf` work with lsp. i also get them..like `fmt . `  i can get snippet s when input `.` it's wired.

**Comment by dgutov** [comment]
> on go-mode-hook by lambda it works. dont know why

Sorry, I have no experience with `use-package`.

> another question, i found the company-yasnippet will set all snippet to company even company-capf work with lsp. i also get them..like fmt . i can get snippet s when input . it's wired.

Not sure what you're asking, but LSP has its own snippet support. So mixing in `company-yasnippet` might be extraneous. You can create a buffer-local value of `company-backends` in buffers managed by `lsp-mode` and avoid including the latter backend in the group there.

https://github.com/osv/company-web has some Emmet integration.

**Comment by taigacute** [comment]
sorry for my bad english , I mean is there a way to not show it when lsp completion
![image](https://user-images.githubusercontent.com/41671631/76518718-970a5780-649a-11ea-835d-1ca944e57ac9.png)

**Comment by dgutov** [comment]
That's how I understood it, yes. My best suggestion is not to put it together with `company-capf` in those buffers.

**Comment by taigacute** [comment]
Does that mean I can't use them at the same time?

**Comment by dgutov** [comment]
Isn't that what you are asking for? When lsp-mode is used, avoid using it.

lsp-mode should have its own snippet support anyway.

**Comment by taigacute** [comment]
Yes, but the snippets of lsp provide are limited, yasnippet I can customize as many as I need.its more useful than lsp snippets.

**Comment by dgutov** [comment]
Then I don't understand why you don't want them shown.

But anyway, you can bind `M-x company-yasnippet` to a separate key combination.

**Comment by taigacute** [comment]
Hmm,Because I want to get similar behavior to vim. I have used vim for many years,
![test](https://user-images.githubusercontent.com/41671631/76534840-fecd9c00-64b4-11ea-947e-fc43e375ad4d.gif)

**Comment by taigacute** [comment]
Its possible to remove company-yasnippet candidate when input point `.`?Because company-yasnippet should work just before the point.

**Comment by dgutov** [comment]
Do you mean to disable `company-yasnippet` when there is a dot before the beginning of the prefix?

**Comment by taigacute** [comment]
This is just the way I thought about, and I'm not sure if it is feasible. I don't understand the design of the company,  I just switched from vim to emacs for 2 months. Maybe there is a better design? It looks like company merges  candidates of all company backends？The problem is that the candidates of company-yasnippet only work before the point, and getting its dates after the point is superfluous. what do you think?

**Comment by dgutov** [comment]
You can try this, to test out the behavior:

```lisp
(defun company-yasnippet/disable-after-dot (fun command &optional arg &rest _ignore)
  (if (eq command 'prefix)
      (let ((prefix (funcall fun 'prefix)))
        (when (and prefix (not
                           (eq
                            (char-before (- (point) (length prefix)))
                            ?.)))
          prefix))
    (funcall fun command arg)))

(advice-add #'company-yasnippet :around #'company-yasnippet/disable-after-dot)
```

**Comment by taigacute** [comment]
@dgutov  It's work fine! thanks
