### ISSUE TITLE
Request to split `company--create-lines' function

### ISSUE THREAD

**Issue by galeo** [company-mode/company-mode#962]
I'm trying to implement the feature of displaying icons before completing candidates (#756). I need to select the corresponding icon based on the type of candidate. Some libraries add extra text properties at the beginning of the candidates(e.g., **eglot** has `elogt--lsp-item` and **lsp-mode** has `lsp-completion-item`), which contain the symbol kind information. For example, the following is a candidate returned by eglot:
```elisp
#("shape" 0 1 (eglot--lsp-item (:label "shape" :detail "Shape" :filterText "shape" :insertTextFormat 1 :insertText #("shape" 0 1 (eglot--lsp-item #2)) :kind 6) face (completions-common-part)) 1 2 (face (completions-common-part)) 2 3 (face (completions-first-difference)))
```
You can see this symbol `:kind`  is `6`, corresponding to `Variable`.

A company frontend could use `company--create-lines` to generate popup content. This function is very powerful. It accepts two parameters, `selection` and `limit`, and returns the generated lines containing multiple tooltip faces directly. I was thinking about adding a advice function to `company-fill-propertize`, by modifying the parameters `str` and `left` to get the candidate type and add the icon, respectively. However, the completion candidate will lose additional information similar to the above after code `(setq value (company--clean-string (company-reformat value)))`, making it impossible to obtain the candidate type.

This function is pretty involved. I can't do much more than copy it directly to init.el and modify it. But this way is not what I want, this function is nearly 100 lines.

So is it possible to split this function? This way, for each element, the user could get a well-defined way to customize, without having to copy the whole function.

Thanks in advance.

**Comment by dgutov** [comment]
I'll look into it.

**Comment by dgutov** [comment]
So what kind of split did you have in mind?

And did you ever encounter the problem of information loss that you are describing, in practice?

In theory, you are right, but it probably matters only when either the first char of the completion is an unprintable character, or a double-width multibyte char. Or the backend uses `keep-prefix` as its `ignore-case` value, which is not the case for LSP.

From what I understand, you can implement this exactly by advising `company-fill-propertize`. So let's take a look at whatever problems you have with it.

**Comment by galeo** [comment]
> it probably matters only when either the first char of the completion is an unprintable character, or a double-width multibyte char. Or the backend uses `keep-prefix` as its `ignore-case` value, which is not the case for LSP.

Yes. AFAIK, company-dabbrev and company-ispell both use `keep-prefix` as the default value of `ignore-case`.  If a grouped backend contains one of them, then `(company-call-backend 'ignore-case)` will return `keep-prefix`.

```elisp
(let ((company-backend '(company-capf
                         :separate company-dabbrev)))
  (company-call-backend 'ignore-case))
```

In this case, the code of positive logic will be executed in `company-reformat`, causing the original information of the candidate item will be lost.

I always group company-dabbrev with other backends and use it to complete only in string or comment. I think other peope may have this usage as well. Anyway, it is better to get the type information directly from the original content provided by the company backend. 

`items`

**Comment by galeo** [comment]
> From what I understand, you can implement this exactly by advising `company-fill-propertize`. 

Yes. This can be achieved if the original candidate information can be retained in the `VALUE` argument passed to `company-fill-propertize`. The original information should be restored to `value` after code `(setq value (company--clean-string (company-reformat value)))`.

**Comment by dgutov** [comment]
I've shuffled the calls a little, and now `company-fill-propertize` should receive `value` unchanged in the majority of cases.

This area could use more work, but it should be enough for your purpose. Please let me know if something is still missing.

**Comment by galeo** [comment]
> This area could use more work, but it should be enough for your purpose. Please let me know if something is still missing.

This is enough for me. Thanks so much. 

For #756,  in addition to supporting the display of icons, it is now necessary to write corresponding code for different completion backends to extract the type information of candidate items. Would you consider adding a command in the company backend definition to specifically handle the type information of the completion items or even the symbol kind icons in the future?

**Comment by dgutov** [comment]
This sounds like a question better discussed in the issue you linked. But yes, we can get to there.

But you can experiment first by supporting only LSP (for instance) or using the approach taken by company-box.

**Comment by galeo** [comment]
> But you can experiment first by supporting only LSP (for instance) or using the approach taken by company-box.

I have already implemented a very rough version, here is the effect of using elgot to complete the swift code.

<img width="914" alt="Screen Shot 2020-03-19 at 12 49 00 AM" src="https://user-images.githubusercontent.com/1025559/76985629-7dc24900-697b-11ea-8880-c988de6e8af3.png">

The symbol kind icons are from Apple's [SF Symbols](https://developer.apple.com/design/human-interface-guidelines/sf-symbols/overview/) (San Francisco font).

**Comment by dgutov** [comment]
Cool. Does it work in the terminal as well?

Anyway, please feel free to start posting the status updates in the main discussion.

**Comment by galeo** [comment]
> Does it work in the terminal as well?

Yes. These icons are just text characters and can be displayed in the default tooltip frontend.

> Anyway, please feel free to start posting the status updates in the main discussion.

I may have explained how to do this, hope others could get some help. I think you may have more thinking and I would like to see this feature implemented by you in the future.  So it may be more appropriate for you to give a summarize.

Thanks.
