### ISSUE TITLE
company-yasnippet does not show available snippets in Lisp parentheses ()

### ISSUE THREAD

**Issue by stardiviner** [company-mode/company-mode#966]
I have defined snippets like `defun`, `template`, `set-face-attribute` etc in `emacs-lisp-mode`.
When I input `defu` **without parenthese (** , company-mode shows available snippets `defun`. But company-mode report can't complete at point when in parenthese `(defu )`. Even I try manually `[M-x company-yasnippet]`.

BTW, here is my `company-backends`:
```
(setq-default company-backends
                `((company-capf         ; `completion-at-point-functions'
                   ,@(if (and (featurep 'company-tabnine)
                              (or (derived-mode-p 'c-mode)
                                  (derived-mode-p 'c++-mode)))
                         (list 'company-tabnine))
                   ;; :with company-semantic
                   :separate company-yasnippet
                   :separate company-tempo  ; tempo: flexible template insertion
                   :separate company-keywords
                   :separate company-abbrev)
                  company-dabbrev-code
                  company-files))
```

This does not only happens in `emacs-lisp-mode`, also in `clojure-mode` etc Lisp-like major-modes.
And the `yas-key-syntaxes` is the default value: `(yas-try-key-from-whitespace "w_.()" "w_." "w_" "w")`.

**Comment by dgutov** [comment]
Does it, or does it not work with `M-x company-yasnippet`?

I can't reproduce, FWIW. And there's no snippet `defun` here, only `def` which expands to defun.

**Comment by stardiviner** [comment]
It does not work with `M-x company-yasnippet`.
I defined snippet for `defun`:
```snippet
# name: defun
# key: defun
# --
defun $1 (${2:arguments})
  "${3:DOCSTRINGS}"
  (interactive)
  $0
```
For snippet key `defvar`:
```snippet
# name: defvar
# key: defvar
# --
defvar $1 ${2:&optional "${0}"}
```

**Comment by dgutov** [comment]
Does it work with original snippets?

What if you don't type `defun` and press `M-x company-yasnippet` inside `()`?

**Comment by stardiviner** [comment]
Tried press `M-x company-yasnippet` inside `()`, Emacs reports `Cannot complete at point`. No snippets candidates.

**Comment by dgutov** [comment]
OK. What does `M-x company-diag` say when invoked inside parens?

**Comment by stardiviner** [comment]
`M-x company-diag` inside `()` got this:
```
Emacs 28.0.50 (x86_64-pc-linux-gnu) of 2020-03-13 on dark
Company 0.9.12

company-backends: ((company-capf :separate company-yasnippet :separate company-tempo :separate company-keywords :separate company-abbrev)
 company-dabbrev-code company-files)

Used backend: (company-capf :separate company-yasnippet :separate company-tempo :separate company-keywords :separate company-abbrev)

Major mode: emacs-lisp-mode
Prefix: ""
Completions:
  #("myemail" 0 7 (company-backend company-abbrev))
  #("mygmail" 0 7 (company-backend company-abbrev))
  #("mygmailformat" 0 13 (company-backend company-abbrev))
  #("myhomepage" 0 10 (company-backend company-abbrev))
  #("mynick" 0 6 (company-backend company-abbrev))
  #("myqq" 0 4 (company-backend company-abbrev))
  #("mytwitter" 0 9 (company-backend company-abbrev))
```

------------------------------

And `M-x company-diag` inside `(defu` got this:
```
Emacs 28.0.50 (x86_64-pc-linux-gnu) of 2020-03-13 on dark
Company 0.9.12

company-backends: ((company-capf :separate company-yasnippet :separate company-tempo :separate company-keywords :separate company-abbrev)
 company-dabbrev-code company-files)

Used backend: (company-capf :separate company-yasnippet :separate company-tempo :separate company-keywords :separate company-abbrev)

Major mode: emacs-lisp-mode
Prefix: "defu"
Completions:
  #("defun" 0 4 (face (completions-common-part)) 4 5 (face (completions-first-difference)))
  #("defun*" 0 4 (face (completions-common-part)) 4 5 (face (completions-first-difference)))
  #("defun-gmm" 0 4 (face (completions-common-part)) 4 5 (face (completions-first-difference)))
  #("defun-markdown-buffer" 0 4 (face (completions-common-part)) 4 5 (face (completions-first-difference)))
  #("defun-markdown-ref-checker" 0 4 (face (completions-common-part)) 4 5 (face (completions-first-difference)))
  #("defun-motion" 0 4 (face (completions-common-part)) 4 5 (face (completions-first-difference)))
```

**Comment by dgutov** [comment]
OK.

What if you set `company-backends` to `'(company-yasnippet)` before calling it?

**Comment by stardiviner** [comment]
Atfer set this. Still no completion candidates.

**Comment by dgutov** [comment]
What does `M-x company-diag` say?

**Comment by stardiviner** [comment]
For `()` and `(defun` both get this result:
```
Emacs 28.0.50 (x86_64-pc-linux-gnu) of 2020-03-13 on dark
Company 0.9.12

company-backends: (company-yasnippet)

Used backend: company-yasnippet
Major mode: emacs-lisp-mode
Prefix: nil
Completions: none
```

I noticed the `prefix: nil`. Seems this is the problem?

**Comment by dgutov** [comment]
All right. Have you by any chance copied the previous version of advice from https://github.com/company-mode/company-mode/pull/965#issuecomment-599406993 into your init script and then forgot about it?

**Comment by stardiviner** [comment]
Interesting, I indeed copied it from PR. I confirmed this advice caused this problem. I already removed it now. Really Thanks A LOT !! @dgutov

**Comment by dgutov** [comment]
:ok_hand:

Please try to keep track of your init directory contents.

**Comment by stardiviner** [comment]
Ok, I actually did have a minimal Emacs config testing before reporting this issue. But that advice is in `init-company-mode`. I missed that. So I though it was company-mode issue. Sorry, I should be more careful. Now I improved my minimal-init.el file now. Thanks for your mention. :)
