### ISSUE TITLE
autoload break company.

### ISSUE THREAD

**Issue by sstepashka** [company-mode/company-mode#969]
Hi,

In my config I have the following code:
```elisp
(setq
 company-idle-delay 0.3
 company-show-numbers t
 company-transformers nil
 company-semantic-modes '(c-mode c++-mode jde-mode java-mode python-mode)
 company-minimum-prefix-length 1)

(autoload 'company "company")

(add-hook 'after-init-hook
          (lambda ()
            (when (require 'company nil 'noerror)
              (global-company-mode))))
```

When I open org file, company doesn't how popup for words.

But once I replaced autoload on require, everything works well.

BTW, manual company-complete shows everything well. something happens with idle time?

I would really appreciate help to fix the issue.

**Comment by dgutov** [comment]
What happens if you just delete that line? It doesn't make much sense.

**Comment by sstepashka** [comment]
The same as if I had autoload. Autocompletion doesn't work.

**Comment by dgutov** [comment]
OK. Try `-debug-init`: https://www.gnu.org/software/emacs/manual/html_node/efaq/Debugging-a-customization-file.html
