### ISSUE TITLE
What is company-clang--guess-pch-file trying to matching?

### ISSUE THREAD

**Issue by xuchunyang** [company-mode/company-mode#972]
Hello,

I got a question about the regexp pattern used in the following:

```elisp
(defsubst company-clang--guess-pch-file (file)
  (let ((dir (directory-file-name (file-name-directory file))))
    (when (equal (file-name-nondirectory dir) "Classes")
      (setq dir (file-name-directory dir)))
    (car (directory-files dir t "\\([^.]h\\|[^h]\\).pch\\'" t))))
```

according to https://clang.llvm.org/docs/UsersManual.html#generating-a-pch-file, the pch file looks like `test.h.pch`, shouldn't the filename be matched? this pattern doesn't match `test.h.pch`

```elisp
(string-match "\\([^.]h\\|[^h]\\).pch\\'" "test.h.pch")
;; => nil
```

**Comment by dgutov** [comment]
Good question. I don't have a good answer, and this code is 10 years old now. Maybe @nschum could remember, but probably not.

Were you looking into support for precompiled headers?

**Comment by dgutov** [comment]
Judging by the commentary, though, the code is trying to distinguish between "precompiled headers" and "prefix files".

**Comment by dgutov** [comment]
I don't really use Clang myself, so I don't have an answer to that unfortunately.

Does the documented feature related to `-include` make sense? Does it work, it does it need fixing?

**Comment by xuchunyang** [comment]
I'm not familiar with Clang too. I don't understand the documentation.

> company-clang-set-prefix is an interactive compiled Lisp function in
> `company-clang.el'.
> 
> (company-clang-set-prefix &optional PREFIX)
> 
> Use PREFIX as a prefix (-include ...) file for clang completion.

maybe "a prefix file" means a c header file? I have not used this command, however, since Clang does have the `-include` option, so company-clang-set-prefix probably works.

**Comment by dgutov** [comment]
Maybe it does, maybe it doesn't. But the intention seems to be to looks for a file that the user probably generated manually, to speed up completion.

There is some very similar logic in https://github.com/Golevka/emacs-clang-complete-async/blob/master/auto-complete-clang-async.el#L86, except in the end it uses `-include-pch`, and not just `-include` like we do.

Some time ago, Vim's clang_complete included using it as a possible optimization as well: https://github.com/xavierd/clang_complete/commit/cecca90ae43972e1a20fb75e126238d174ed7125. But not the current version.
