### ISSUE TITLE
Unexpected completion triggered when typing in string

### ISSUE THREAD

**Issue by isolet** [company-mode/company-mode#973]
Given 

```
(setq company-auto-complete t
      company-auto-complete-chars "?\"'")
```
, if one is typing `ack` in a string, i.e. "ack*" (where `*` means cursor), pressing <kbd>C-e</kbd> will trigger completion if current candidate is something like `acknowledge`. 

This will not happen if current text is not surrounded by `""` as by digging into `company-auto-complete-p`, the `INPUT` params received `"` after <kbd>C-e</kbd> and `"` is a member of `company-auto-complete-chars`.

**Comment by dgutov** [comment]
This seems to help:

```diff
diff --git a/company.el b/company.el
index 12ba0c8..7072540 100644
--- a/company.el
+++ b/company.el
@@ -1575,9 +1575,8 @@ prefix match (same case) will be prioritized."
       (setq company-prefix new-prefix)
       (company-update-candidates c)
       c)
-     ((and (> (point) company-point)
-           (company-auto-complete-p (buffer-substring-no-properties
-                                     (point) company-point)))
+     ((and (characterp last-command-event)
+           (company-auto-complete-p (string last-command-event)))
       ;; auto-complete
       (save-excursion
         (goto-char company-point)
```

It's such an old piece of code, though, that I worry about breakage. If you use this feature a lot, could you try it for a while and see whether some unexpected side-effect comes up?

**Comment by isolet** [comment]
Just tried, seems works, thanks. Since I have English words completion in strings and some of they are prefixes of other, I use <kbd>C-e</kbd> to skip `"` quite often. I will play with the patch for some days !

**Comment by dgutov** [comment]
OK, let's try it.
