### ISSUE TITLE
eshell - using (fn param) syntax breaks all lookups

### ISSUE THREAD

**Issue by falloutphil** [company-mode/company-mode#974]
Emacs 26.3 on Ubuntu 18.04.

Take a fresh install of Emacs (no packages and no init).
Install `company` package from elpa using standard package installer.

Without any further setup if I `M-x company-mode` in an `eshell` buffer I get pop-up completion for files and directories and also lisp functions, which is great.

However, if I try to call some lisp using the standard calling convention (i.e. nested in brackets `(foo)` ), no completion happens, and instead I get the following message:

`Completion function pcomplete-completions-at-point uses a deprecated calling convention`

The error may or may not be due to the hack around tab usage as per issue https://github.com/company-mode/company-mode/issues/409

**To summarize:**

1. The following give popup completions:
`cd /home/`
`find-`

2. But the following gives the error and breaks future lisp look-ups:
`(find-`

This is despite `find-file test.txt` and `(find-file "test.txt")` both being valid `eshell` syntax.
 
I could live with this, but what is killing me is after this occurs, no further completions will work in `eshell` for _any_ type of lisp function.  This includes the unbracketed calling convention that worked before I attempted the bracketed call.

File and directory completion does still continue to work correctly tho.

To resolve the problem I have to kill emacs and start over.  Reactivating `company-mode` and/or killing the particular `eshell` session does not resolve the issue.

So two questions:

1. Ideally how do I make completion work for both function calling conventions?

But if that isn't resolvable with config.

2. How can I stop breaking of the all lisp completions when using bracketed expressions?

**Comment by dgutov** [comment]
The reason for it to stop working can be seen in `completion--capf-wrapper`. As soon as `pcomplete-completions-at-point` starts behaving obviously improperly, it's not considered as a source of completions anymore. And I guess it's only misbehaving in some situations.

Alas, your best bet is reporting that with `M-x report-emacs-bug`. The problem is not in `company`, and the required fix will not be made here.

You can include this same info, as well as what you see after typing `M-x completion-at-point`.

**Comment by falloutphil** [comment]
Thanks for explanation.

Bug raised with emacs:
https://debbugs.gnu.org/cgi/bugreport.cgi?bug=40651

**Comment by dgutov** [comment]
The bug is being worked on, see https://github.com/company-mode/company-mode/discussions/1278 and the linked debbugs.

In the meantime, I'll apply the workaround suggested there.
