### ISSUE TITLE
Is company-capf called on every keystroke?

### ISSUE THREAD

**Issue by didibus** [company-mode/company-mode#975]
I'm authoring https://github.com/didibus/anakondo which adds a completion-at-point function for Clojure modes.

When I use it with company-mode using company-capf, it seems that my candidates function, the third argument of the list returned by completion-at-point, is called over and over as each keystroke is typed.

I happen to use some backend process for the completion, and while that's fast, it seems with company calling it again on each keystroke it is a bit slower than I'd want it.

When I use completion-at-point this is really fast.

It seems the difference is that completion at point calls my candidates function only once, and then as the user types more or erases some characters, it just re-filters my list of candidates appropriately. While it seems company-capf just calls my candidates function over and over again.

My particular candidates function returns all possible completion for the symbol at point. So in theory, once a company popup has appeared, it shouldn't ever need to ever call my function again, it should just apply prefix filtering over the results.

Is there something I can do about this?

Regards

**Comment by dgutov** [comment]
Yes. And normally it's not an issue because the completion tables either poll a background process, or do their own caching, or are simply fast enough that this isn't noticeable.

But the use of `completion-table-with-cache`, where the cache is stored lexically, indeed makes a difference.

So one way to deal with would be to use a different kind of cache (store it in a package-private variable and key it on the position of the beginning of the current prefix, for instance).

**Comment by dgutov** [comment]
Here's a patch that might improve this inside `company-capf`, but TBH I'm kinda worried to apply it, given we've dealt with some subtle issues in this area not too long ago. But maybe try it anyway.

```diff
diff --git a/company-capf.el b/company-capf.el
index cb30a80..c0f6139 100644
--- a/company-capf.el
+++ b/company-capf.el
@@ -105,7 +105,10 @@ so we can't just use the preceding variable instead.")
             (length (cons prefix length))
             (t prefix))))))
     (`candidates
-     (company-capf--candidates arg))
+     (if company-capf--current-completion-data
+         (company--candidates-from-data
+          company-capf--current-completion-data arg)
+       (company-capf--candidates arg)))
     (`sorted
      company-capf--sorted)
     (`match
@@ -162,28 +165,31 @@ so we can't just use the preceding variable instead.")
   (let ((res (company--capf-data)))
     (company-capf--save-current-data res)
     (when res
-      (let* ((table (nth 3 res))
-             (pred (plist-get (nthcdr 4 res) :predicate))
-             (meta (completion-metadata
-                    (buffer-substring (nth 1 res) (nth 2 res))
-                    table pred))
-             (candidates (completion-all-completions input table pred
-                                                     (length input)
-                                                     meta))
-             (sortfun (cdr (assq 'display-sort-function meta)))
-             (last (last candidates))
-             (base-size (and (numberp (cdr last)) (cdr last))))
-        (when base-size
-          (setcdr last nil))
-        (setq company-capf--sorted (functionp sortfun))
-        (when sortfun
-          (setq candidates (funcall sortfun candidates)))
-        (if (not (zerop (or base-size 0)))
-            (let ((before (substring input 0 base-size)))
-              (mapcar (lambda (candidate)
-                        (concat before candidate))
-                      candidates))
-          candidates)))))
+      (company--candidates-from-data res input))))
+
+(defun company--candidates-from-data (data input)
+  (let* ((table (nth 3 data))
+         (pred (plist-get (nthcdr 4 data) :predicate))
+         (meta (completion-metadata
+                (buffer-substring (nth 1 data) (nth 2 data))
+                table pred))
+         (candidates (completion-all-completions input table pred
+                                                 (length input)
+                                                 meta))
+         (sortfun (cdr (assq 'display-sort-function meta)))
+         (last (last candidates))
+         (base-size (and (numberp (cdr last)) (cdr last))))
+    (when base-size
+      (setcdr last nil))
+    (setq company-capf--sorted (functionp sortfun))
+    (when sortfun
+      (setq candidates (funcall sortfun candidates)))
+    (if (not (zerop (or base-size 0)))
+        (let ((before (substring input 0 base-size)))
+          (mapcar (lambda (candidate)
+                    (concat before candidate))
+                  candidates))
+      candidates)))
 
 (defun company--capf-post-completion (arg)
   (let* ((res company-capf--current-completion-data)
```

**Comment by didibus** [comment]
Ok thanks, I'll try the patch and report back.

> So one way to deal with would be to use a different kind of cache (store it in a package-private variable and key it on the position of the beginning of the current prefix, for instance)

Right now I'm using completion-table-with-cache, but ya, this doesn't really work since as the user types more or less letters, it's a cache miss on everyone.

Are you saying I could make a custom caching which would instead say cache only on the first letter of the prefix? That could be a good idea.

One question with this, so that means that company-capf calls my completion-at-point function only once per symbol completion? But then calls my candidates fn which it returns on every keystroke? Do I understand that correctly?

Cause the Emacs capf docs kind of say that capf might call the completion function many time, but wouldn't call the candidates function many time. So that seem like it be a different behavior.

**Comment by dgutov** [comment]
> Right now I'm using completion-table-with-cache, but ya, this doesn't really work since as the user types more or less letters, it's a cache miss on everyone.

With company-capf, you mean?

> Are you saying I could make a custom caching which would instead say cache only on the first letter of the prefix?

On the buffer position of the first character of the prefix.

> Cause the Emacs capf docs kind of say that capf might call the completion function many time, but wouldn't call the candidates function many time.

Could you point me to the exact documentation page? The manual is available on the web.

**Comment by didibus** [comment]
> Could you point me to the exact documentation page? The manual is available on the web.

Ya, maybe I'm understanding it wrong, as I do think I am a bit confused about the exact behavior, but this part of the doc here: https://www.gnu.org/software/emacs/manual/html_node/elisp/Completion-in-Buffers.html

> The functions on this hook should generally return quickly, since they may be called very often (e.g., from post-command-hook). Supplying a function for collection is strongly recommended if generating the list of completions is an expensive operation. Emacs may internally call functions in completion-at-point-functions many times, but care about the value of collection for only some of these calls. By supplying a function for collection, Emacs can defer generating completions until necessary.

Combined with:

> Additionally, the collection should generally not be pre-filtered based on the current text between start and end, because that is the responsibility of the caller of completion-at-point-functions to do that according to the completion styles it decides to use.

This gave me the impression that Emacs would never call your function again on a completion, as it will filter the returned list as the text between start and end gets modified.

**Comment by didibus** [comment]
I tried the patch, it didn't really seem to do much.

I'll try the caching you mentioned.

Though I guess what I mean is it would be nice if on the first time capf is called for a prefix, like how company activates after two chars are typed, and I return the completion list with the candidate function for collection. If capf could call that and know, ok, I got all possible candidates for those 2 characters, so now if the user types more or less, it doesn't call the function again, it just filters the result from the first time it called it.

This is the behavior with `complete-symbol` and standard `completion-at-point`.

That said, I can see a downside to this as well, in that the completion engine can't decide when to invalidate or not. So maybe it is best the current behavior. If having my own cache works, it does give me more control over it. I can already think of one example that might benefit from me having that fine grain control.

I'll report back if I was able to fix it with a cache.

**Comment by didibus** [comment]
Added a buffer local cache based of the last start position, works great!

Thanks for the suggestion.

**Comment by dgutov** [comment]
> This gave me the impression that Emacs would never call your function again on a completion, as it will filter the returned list as the text between start and end gets modified.

The impression is more or less correct: it can call it more than once, especially to apply some of the more advanced completion styles. But not as often as the `completion-at-point-functions` element. For strictly prefix completion, it *should* only call it once.

`company-capf` doesn't exactly follow this description in your particular case (basically, using a lexical cache), but the patch I posted should have fixed that. It does so in my testing, at least.

Doing your own caching is usually more flexible, though. So if it works well for you now, very good.

**Comment by didibus** [comment]
> Doing your own caching is usually more flexible, though. So if it works well for you now, very good

Ya, I actually benefit from this flexibility right now, since there is a scenario when I need to invalidate the cache. So maybe leaving caching up to the completion functions themselves is the better way to go.
