### ISSUE TITLE
company shows some '_' in some places

### ISSUE THREAD

**Issue by nniixxoossccnn** [company-mode/company-mode#977]
I install company on my Emacs,

But it displays like this when completing in Chinese:

```
测试变量
     测_试_变_量A
     测_试_变_量B

```

'_' Appears between each Chinese character in the candidate

**Comment by nniixxoossccnn** [comment]
Linux
Emacs version: 26.3

emacs -nw

**Comment by dgutov** [comment]
Hi!

What does `M-x company-diag` say? In particular, I'd like to see the entries that turn to the example above in the popup.

**Comment by nniixxoossccnn** [comment]
company-diag:

```
Emacs 26.3 (x86_64-unknown-linux-gnu) of 2020-04-26 on nil
Company 0.9.12 

company-backends: (company-bbdb company-eclim company-semantic company-clang company-xcode company-cmake company-capf company-files
              (company-dabbrev-code company-gtags company-ctags company-keywords)
              company-oddmuse company-dabbrev)

Used backend: (company-dabbrev-code company-gtags company-ctags company-keywords)

Major mode: python-mode
Prefix: #("这是测试" 0 4
  (fontified t))

Completions:
  "这是测试变量B"
  "这是测试变量A"

```

**Comment by nniixxoossccnn** [comment]
![2020-04-26-110146_338x235_scrot](https://user-images.githubusercontent.com/62413320/80296402-79285600-87ad-11ea-9083-4856948e97ea.png)

**Comment by dgutov** [comment]
OK. What's the value of `buffer-file-coding-system` in that buffer?

**Comment by nniixxoossccnn** [comment]
utf-8-emacs-unix

**Comment by dgutov** [comment]
Hmm, I haven't been able to reproduce this. My popup looks fine.

I have an idea what must be causing this, but to fix it, I need an exact test case.

Can you reproduce it starting with `emacs -Q -L ~/.emacs.d/elpa/company-* -l company`?

Do you maybe have a file that trigger it when editing?

**Comment by nniixxoossccnn** [comment]
These problems occur when calling company for Chinese completion in all places.
I think this problem is still my own try to solve it, because only I encountered. close

**Comment by dgutov** [comment]
Unless it's really a configuration problem, do come back with more details.
