### ISSUE TITLE
Following wiki for Writing Backends, it seems multi-line meta not supported in Message area?

### ISSUE THREAD

**Issue by ahungry** [company-mode/company-mode#981]
https://github.com/company-mode/company-mode/wiki/Writing-backends

If I follow that guide and create a sample meta that has a newline in it, it appears only the first line is displayed in the Message area.

If I also 'message' myself, a multi-line message works as expected.

Is it by design that we can't have multi-line meta shown in message area?  (I use Emacs in tty mode, so don't see an inline hover at all).

**Comment by dgutov** [comment]
That depends on the value of `company-echo-truncate-lines`. By default, only one line is shown, yes.

When you want to show a long documentation, `doc-buffer` is generally the way to do it. The user will have to call it explicitly or use an extra package like `company-quickhelp`.

**Comment by ahungry** [comment]
Thanks, that makes sense.  I noticed multi-line is a bit jarring in GUI and TTY mode, as scrolling company candidates as such causes a lot of flicker.

I recall sometime ago I was tinkering with a fork of company-quickhelp that would use popup for tty based popups similar to what ac-mode used to do, but again, it was a lot of work for a sub-par result.

Granted it doesn't help users who are in non-graphical environments, but last night I was toying with an idea of showing the more verbose documentation on an inotify message area - that way it doesn't disrupt the Emacs layout, but still provides "popup" like documentation.

Small video here (firefox may complain about bad format, but chromium seems to show it fine):

https://ahungry.com/img/company-janet.mp4

Do you think that'd be useful as a company frontend? (to show 'doc' info by pinging a notification-daemon ala inotify-send commands?)

**Comment by dgutov** [comment]
> I noticed multi-line is a bit jarring in GUI and TTY mode, as scrolling company candidates as such causes a lot of flicker

That's one of the reasons. I think window jumping is a bad side-effect in general.

> Do you think that'd be useful as a company frontend? (to show 'doc' info by pinging a notification-daemon ala inotify-send commands?)

It looks interesting, and I'm happy if it works for you, but I see obvious limitations there, e.g. the previous notifications don't disappear right away. It could be helpful for some users, so why not publish to MELPA.
