### ISSUE TITLE
company-backends vs. completion-at-point-functions

### ISSUE THREAD

**Issue by clemera** [company-mode/company-mode#982]
What kind of features can be achieved by company-backends which aren't possible by using `completion-at-point-functions` via `company-capf`? In which cases is it recommended for package authors to provide company backends  instead of providing functions for `completion-at-point-functions`?

Is there some plan to integrate backends into `completion-at-point-functions` someday via some kind of wrapper or would that be incompatible/impossible/undesirable?

**Comment by dgutov** [comment]
> What kind of features can be achieved by company-backends which aren't possible by using completion-at-point-functions via company-capf?

Async calling convention and backend grouping.

> In which cases is it recommended for package authors to provide company backends instead of providing functions for completion-at-point-functions?

I hesitate to make an official recommendation.

> Is there some plan to integrate backends into completion-at-point-functions someday via some kind of wrapper or would that be incompatible/impossible/undesirable?

There is some plan, but we'll have to wait and see. I'm hoping for a new version of the `completion-at-point-functions` API.

**Comment by clemera** [comment]
Thank you very much that is all I wanted to know, sometimes the Emacs completion landscape can be a bit confusing. Thank you for all your nice work on company, it's a great achievement!
