### ISSUE TITLE
Smarter completion ordering? (Emacs Lisp)

### ISSUE THREAD

**Issue by contrapunctus-1** [company-mode/company-mode#984]
When working on [Chronometrist](https://github.com/contrapunctus-1/chronometrist) today, I typed `(c-m-s-p|)` (| being the cursor), pressed TAB, and got (in this order) -
```
c-macro-vsemi-status-unknown-p
c-state-get-min-scan-pos
chronometrist-midnight-spanning-p
comint-previous-matching-input-string-position
```

While perhaps not of critical importance, it'd be a nice touch/refinement if Company could prefer results from the current project (maybe utilizing Cask, when available?), followed by the dependencies of the project (again, maybe using Cask to get them), followed by any other results. Thoughts?

Company v0.9.12 from MELPA, Emacs v26.1 on Debian Testing

**Comment by dgutov** [comment]
Check out the `company-transformers` use option.

Some more advanced transformers are available as plugins. E.g. `company-statistics`. No segregation of this project/other projects that I know of, though/
