### ISSUE TITLE
elpy -> company-mode -> tramp interaction

### ISSUE THREAD

**Issue by kordosky** [company-mode/company-mode#985]
While coding in emacs with elpy enabled I've found that I get a freeze of a few minutes after typing 

`os.chdir("/ho`

I'm just trying to change to my home directory. After the third character emacs freezes. It is not sensitive to ctrl-G. This happens the first time in an emacs session. It also happens with other function calls (e.x. os.stat()). The /xx also does not have to be the start of a valid path.

What appears to be happening is that elpy is using company to complete the text string. Company seems to interpret the /xx as something tramp should try to handle and passes it to tramp. Tramp ends up calling ssh. The most relevant part of the backtrace seems to be:

![Selection_077](https://user-images.githubusercontent.com/30102514/82739214-d4495c00-9d0b-11ea-8aa8-002197872f6b.jpg)

Sorry for the image. There are some unicode characters in the text that screw up markdown. 

My questions are: (1) Is if this is the desired behavior from the standpoint of company-mode?  (2) Is there something about the way elpy is using company-mode that could be at issue? (3) Can anyone duplicate the issue? Perhaps it has to do with my tramp or ssh setups (both are pretty unremarkable).  Duplication is simple:

`
import os
os.chdir("/xx

`

**Comment by kordosky** [comment]
Sorry, left off the versions:
Company 0.9.12
Elpy 1.33.0
Tramp 2.2.11-24.5
Emacs 24.5.1

**Comment by dgutov** [comment]
What if you try to reproduce it without company?

`M-x eshell`, type `cd /ho`, abort company popup if it comes up, then press `C-M-i`.

**Comment by dgutov** [comment]
> Emacs 24.5.1

In any case, though, you might want to try a newer Emacs first. This version is 5 years old.

**Comment by kordosky** [comment]
Thanks,
I tried "M-x eshell  cd /ho"
it didn't freeze (I could step back a character) and then C-M-i produced "cd use-package-/:hook"

**Comment by dgutov** [comment]
Hmm, what if you do this instead?

* C-x C-f
* Enter `/ho`
* Press TAB

**Comment by kordosky** [comment]
Emacs 26 doesn't have the error, but I think it's only because elpy throws errors on initialization and doesn't run correctly. I don't get any command completion.  The errors are:
'
Error (use-package): elpy/:init: Symbol’s value as variable is void: xref-location-marker
Error (use-package): elpy/:catch: Symbol’s value as variable is void: xref-location-marker
'
Also, when I "list-packages" and click on elpy it states emacs-24.4 as a dependency.

**Comment by dgutov** [comment]
Something to report, maybe? But it shouldn't be hard to fix: `xref-location-marker` is in Emacs 25+. It's a function though, not a variable.

> Also, when I "list-packages" and click on elpy it states emacs-24.4 as a dependency

That just means it's the minimum version.

**Comment by dgutov** [comment]
Nothing further seems likely to happen here, so closing.
