### ISSUE TITLE
tooltip background changed to yellow

### ISSUE THREAD

**Issue by tspiteri** [company-mode/company-mode#987]
#986 has changed the tooltip background to yellow even for >=88-color-terminals with light backgrounds.

I think (but I'm not sure, I don't really know faces) the proper way to do what #986 wants is to *not* change the `default`, but add a case `(t (:background "yellow"))` below the other cases, so that when the other cases do not match, the background is set to yellow. In the case of company-tooltip I think you could even change `((class color) (min-colors 88) (background dark))` to `t` as that is the final condition and sets the background to yellow.

**Comment by dgutov** [comment]
Thank you for the report.

The current code actually works fine in my Emacs 27, but behaves like you describe in Emacs 26.3.

Let's see what the docs say...

**Comment by isolet** [comment]
The code does not work for me in my Emacs 27.0.91.

**Comment by dgutov** [comment]
How old is your build? It seems to have been fixed in https://debbugs.gnu.org/40336 (two months ago).

**Comment by dgutov** [comment]
In any case, let's make a backward-compatible fix.

**Comment by isolet** [comment]
<kbd>M-x</kbd> `emacs-version` gives `GNU Emacs 27.0.91 (build 1, x86_64-apple-darwin19.4.0, Carbon Version 162 AppKit 1894.4) of 2020-05-08`.

**Comment by dgutov** [comment]
Ah, sorry. I forgot: I'm on Emacs 28 now. That's where it's fixed.

**Comment by dgutov** [comment]
@tspiteri Good suggestion, but having it in a separate case should allow easier change in the future.
