### ISSUE TITLE
Company makes the cursor jump to the top of the buffer in Pascal mode

### ISSUE THREAD

**Issue by ssakatausa** [company-mode/company-mode#988]
When I use the company mode editing a code in the pascal mode, the cursor jumps to the top of the buffer randomly and frequently. Because the problem disappears if I disable the company mode, the problem seems to be in the combination of the comapny and pascal modes. To verify my guess, I did the following:
  1. Started emacs with the -Q option
  2. Manually add the directory of the company mode files to load-path and load company.el.
  3. Run global-company-mode to enable the global company mode.
  4. Open a new pascal file (which automatically starts the pascal mode)
  5. Type in a pascal code like:

          program company;
          var
              a: integer;
              b: real
              c: boolean;
              d: string;
   
    While doing this, the cursor jumps to the top of the buffer a few times.

I am using Emacs 26.1 in Debian Linux Buster with Company Mode 20200525.101. 

Thanks!

**Comment by dgutov** [comment]
What does `M-x company-diag` say?

What does `M-: completion-at-point-functions RET` show?

**Comment by ssakatausa** [comment]
M-x company-diag  yields:

Emacs 26.1 (x86_64-pc-linux-gnu) of 2019-09-22 on x86-grnet-01
Company 0.9.12

company-backends: (company-bbdb company-eclim company-semantic company-clang company-xcode company-cmake company-capf company-files
	      (company-dabbrev-code company-gtags company-etags company-keywords)
	      company-oddmuse company-dabbrev)

Used backend: company-capf
Major mode: pascal-mode
Prefix: stop
Completions: none


The value of  completion-at-point-functions is (tags-completion-at-point-function).

**Comment by dgutov** [comment]
Hmm.

And do you have a tags file visited?

**Comment by ssakatausa** [comment]
Oh, sorry, I reported the global value of completion-at-point-functions by mistake. Its value is

    (pascal-completions-at-point t)

when the pascal mode is on.

**Comment by dgutov** [comment]
Okay, thank you.

It's a bug in `pascal-mode`, which is a part of Emacs. Because you can turn off `company-mode`, then type out this file and, if you press `C-M-i` after each character, you should see different errors along the way. Both `End of buffer` and (if add some newlines at the end in order not to see those) `args-out-of-range` ones.

Could you `M-x report-emacs-bug` with these details?

**Comment by ssakatausa** [comment]
Thanks for your reply! I will do report-emacs-bug.

**Comment by dgutov** [comment]
Fixed in Emacs 28 (whenever it comes out).
