### ISSUE TITLE
Company mode stops working

### ISSUE THREAD

**Issue by benwainwright** [company-mode/company-mode#991]
Hi there!

I use `company-mode` in conjunction with `lsp-mode` and it seems that when I'm using it, after a period of time, it just... stops working. `lsp-mode` appears to be still active and working, but the company autosuggestion box seems to just stop appearing. At the present time I only seem to be able to resolve it by restarting emacs. Any suggestions on what I can do to debug this would be much appreciated...

**Comment by dgutov** [comment]
Does it stop working in all buffers? E.g. in `*scratch*` as well?

**Comment by benwainwright** [comment]
It doesn't *appear* to; but it's quite possible I've not spent enough time in `*scratch*` for it to happen. Mostly I've noticed this in `typescript-mode` buffers.

**Comment by dgutov** [comment]
What does `M-x company-diag` say, after that happens?

**Comment by benwainwright** [comment]
Ok, this just happened in a `js-mode` buffer. I ran `M-x company-diag` and got this:

```
Emacs 28.0.50 (x86_64-apple-darwin18.7.0) of 2020-06-17 on MC-S118697
Company 0.9.12

company-backends: (company-bbdb company-eclim company-semantic company-clang company-xcode company-cmake company-capf company-files
     (company-dabbrev-code company-gtags company-etags company-keywords)
     company-oddmuse company-dabbrev)

Used backend: company-capf
Major mode: js-mode
Prefix: "proces"
Completions: none
```

**Comment by dgutov** [comment]
Try `(company-capf 'completions "")`. It will probably return nothing as well.

See what the value of `completion-at-point-functions` is. Is it contains an element from `lsp-mode`, you should report this to them.

You can also try to look for their network log buffer and debug from there.

**Comment by benwainwright** [comment]
> Try evaluating (company-capf 'completions ""). It will probably return nothing as well.

It returns `nil`

> See what the value of completion-at-point-functions is. Is it contains an element from lsp-mode, you should report this to them.

```
completion-at-point-functions is a variable defined in ‘minibuffer.el’.
Its value is (lsp-completion-at-point)
Local in buffer IsSpike.spec.js; global value is 
(tags-completion-at-point-function)
```

Ok, thanks. I'll raise an issue on the `lsp-mode` repository.

**Comment by dgutov** [comment]
Sorry, some correction. The expression to evaluate here is `(company-capf 'candidates "")`.

If you want to make double-sure it's not company-mode's problem.

**Comment by benwainwright** [comment]
Thanks; I'll check that once the issue reappears :)

**Comment by benwainwright** [comment]
Ok; they've made a fix over at `lsp-mode` that has resolved my issue. Thanks for your help :)
