### ISSUE TITLE
No tooltip when the last character of prefix is white space.

### ISSUE THREAD

**Issue by yanghaoxie** [company-mode/company-mode#994]
I am writing a company backend that include white space as prefix, I noticed that when the tooltip does **NOT** show up when the last character of prefix is white space, although `company-diag` suggests that there are candidates.

I provide a gif file to show the phenomena. According to the figure, we have following observations:

1. When the prefix is `b`, `company-diag` reports the prefix is `b` and there are candidates. `Company` shows tooltip.
2. When the prefix is `b `, `company-diag` reports the prefix is `b ` and there are candidates. `Company` does **NOT** show tooltip.
3. When the prefix is `b n`, `company-diag` reports the prefix is `b n` and there are candidates. `Company`  shows tooltip.
4. After input `b n`, `company` shows tooltip, delete `n`, however, `company` shows tooltip, too. This observation is **NOT** consistent with `observation 2` .

![company](https://user-images.githubusercontent.com/10540480/86740127-b2dfcd80-c036-11ea-93d2-f1dcd58caec0.gif)

Thank you for your help. I hope I explained myself clearly.

**Comment by dgutov** [comment]
Hi!

What does `C-h k SPC` say? I wonder which command it's bound to.

**Comment by dgutov** [comment]
We'd have to determine what makes your configuration special.

This example backend doesn't seem to exhibit the problem:

```
(defun test-backend (command &optional arg &rest _rest)
  (cl-case command
    ('prefix (buffer-substring
              (line-beginning-position)
              (point)))
    ('candidates
     (mapcar
      (lambda (s)
        (concat arg s))
      '("a" "b" "c")))))
```

**Comment by yanghaoxie** [comment]
Thank you for your help.

`C-h k SPC` says
```
SPC runs the command self-insert-command (found in global-map), which
is an interactive built-in function in ‘C source code’.

It is bound to many ordinary text characters.

(self-insert-command N &optional C)

  Probably introduced at or before Emacs version 22.1.

Insert the character you type.
Whichever character C you type to run this command is inserted.
The numeric prefix argument N says how many times to repeat the insertion.
Before insertion, ‘expand-abbrev’ is executed if the inserted character does
not have word syntax and the previous character in the buffer does.
After insertion, ‘internal-auto-fill’ is called if
‘auto-fill-function’ is non-nil and if the ‘auto-fill-chars’ table has
a non-nil value for the inserted character.  At the end, it runs
‘post-self-insert-hook’.

[back]
```

I used following code to test the `test-backend`, and the observations are the same, the gif file is at the ending.
```
(defun test-backend (command &optional arg &rest _rest)
  (interactive (list 'interactive))
  (cl-case command
    (interactive (company-begin-backend 'test-backend))
    (prefix (buffer-substring
              (line-beginning-position)
              (point)))
    (candidates
     (mapcar
      (lambda (s)
        (concat arg s))
      '("a" "b" "c")))))

(add-hook 'inferior-python-mode-hook
	      (lambda ()
		(add-to-list (make-local-variable 'company-backends) '(test-backend))))
```
![company-test-backend](https://user-images.githubusercontent.com/10540480/88457502-ba69f800-ceb9-11ea-8058-12f033a57578.gif)

**Comment by dgutov** [comment]
What about this backend?

```
(defun test-backend (command &optional arg &rest _rest)
  (interactive (list 'interactive))
  (cl-case command
    (interactive (company-begin-backend 'test-backend))
    (prefix (buffer-substring
              (line-beginning-position)
              (point)))
    (candidates
     (mapcar
      (lambda (s)
        (concat arg s))
      '("a" "b" "c")))
    (no-cache t)))
```

Note the last line.

And what's your value of `company-idle-delay`?

**Comment by yanghaoxie** [comment]
1. The observation is the same for this backend, and `company-idle-delay` is `0` in this and all previous experiments.

2. I also tried to set `company-idle-delay` to `0.5`, and the observation is the same.

**Comment by dgutov** [comment]
Well, I can't reproduce that.

Could you write a full reproduction scenario starting with `emacs -Q -L ~/.emacs.d/elpa/company-xyz`?

BTW, I have just released version 0.9.13. You might as well upgrade to that.

**Comment by yanghaoxie** [comment]
Thank you for your help.
I will write a full reproduction later.
Thanks again.:)

**Comment by dgutov** [comment]
@yanghaoxie Any news?
