### ISSUE TITLE
Company section can not display

### ISSUE THREAD

**Issue by vanniuner** [company-mode/company-mode#995]
I need restart emacs to reslove the question which company section can not display at start emacs seconds mninutes latter.
The buffer \*Messages\* out bleow:
```
Company: An error occurred in auto-begin
Company: backend company-capf error "Invalid regexp: "Regular expression too big"" with args (candidates )

```

**Comment by dgutov** [comment]
What does `M-x company-diag` say?

You can also `M-x toggle-debug-on-error` followed by `M-x company-complete-common` for better backtrace.
