### ISSUE TITLE
Easy way to determine when there's no selection

### ISSUE THREAD

**Issue by kiennq** [company-mode/company-mode#998]
Currently `company-tng` is advice against `company-fill-propertize` so that the selection will not be shown.

Doing that affect third party frontends that needs to know about currently highlighted selection.
For example:
- to adding front icon for output from `company--create-lines` and adjust icon background to match with selection.
- Provide different key binding depends on if there's selection or not. Like, press `Enter` when there's no selection will just enter new line, but will enter selected item when there is.

Is there an easy way to determine if there's no selection in company popup?

**Comment by dgutov** [comment]
> to adding front icon for output from company--create-lines and adjust icon background to match with selection.

This one should be doable already. If `company-fill-propertize` is advised, and it calls the icon-generating logic, it could pass a boolean arg (to indicate the current item is selected.

> Provide different key binding depends on if there's selection or not. Like, press Enter when there's no selection will just enter new line, but will enter selected item when there is.

Sounds like you want to bring in that feature from `company-tng` more organically into company-mode proper. It shouldn't be too hard, but I don't have a list of places to change. It could probably start with a user option to choose whether the default selection is `0` or `nil`.

> Is there an easy way to determine if there's no selection in company popup?

Currently, no. This possibility lives purely inside `company-tng`.

**Comment by dgutov** [comment]
> It could probably start with a user option to choose whether the default selection is 0 or nil.

Or it would determine whether most uses of `company-selection` should check `company-selection-changed` is non-nil as well.

**Comment by kiennq** [comment]
> It could probably start with a user option to choose whether the default selection is `0` or `nil`.

Oh, I was thinking the same thing and kind of got it working in my private change.



> Or it would determine whether most uses of `company-selection` should check `company-selection-changed` is non-nil as well.

I'm not really understand this. Do you suggest that I should check `company-selection` and `company-selection-changed` together?
That may not work since:
- Without `company-tng`, `company-selection == 0` and `company-selection-changed = nil` mean first item is **selected**
- With `company-tng`, the same condition mean **no item** is selected



> This one should be doable already. If `company-fill-propertize` is advised, and it calls the icon-generating logic, it could pass a boolean arg (to indicate the current item is selected.

Advising `company-fill-propertize` is a little bit tricky, since one has to advise again that function with lowest depth, else it will not work. Anyway, I don't think advising a function should be official way :)

**Comment by dgutov** [comment]
> I'm not really understand this. Do you suggest that I should check company-selection and company-selection-changed together?

It would require a new var either way, of course, to support both workflows. Just like in your PR.

> Advising company-fill-propertize is a little bit tricky, since one has to advise again that function with lowest depth

That depends on how the images are rendered (whether the selection number is passed, or a "selected" boolean).

> Anyway, I don't think advising a function should be official way :)

Sure. But we're not really discussing official functionality, are we? Or if we are, the new var should be a defcustom, and it should affect the behavior without `company-tng` enabled as well.

**Comment by kiennq** [comment]
> That depends on how the images are rendered (whether the selection number is passed, or a "selected" boolean).

This leads back to original question: "how to determine the selection", doesn't it?



> Sure. But we're not really discussing official functionality, are we? Or if we are, the new var should be a defcustom, and it should affect the behavior without `company-tng` enabled as well.

I mean it should be official way for third party packages of `company-mode`. Those will just need to temporary bind the new var insteading of advising, which should be last effort.

**Comment by dgutov** [comment]
It's in master now.
